--- @meta AbilityType

--- @alias AbilityType integer
--- | `ABILITY_TYPE_ACTIONLIST` # 50
--- | `ABILITY_TYPE_AREAEFFECT` # 22
--- | `ABILITY_TYPE_AREATELEPORT` # 26
--- | `ABILITY_TYPE_ATTACKERINTERCEPT` # 66
--- | `ABILITY_TYPE_ATTACKERREFLECT` # 65
--- | `ABILITY_TYPE_AVAREACH` # 95
--- | `ABILITY_TYPE_AVOIDDEATH` # 86
--- | `ABILITY_TYPE_BASIC` # 91
--- | `ABILITY_TYPE_BLADETURN` # 40
--- | `ABILITY_TYPE_BLINK` # 4
--- | `ABILITY_TYPE_BLOCK` # 52
--- | `ABILITY_TYPE_BONUS` # 5
--- | `ABILITY_TYPE_CHANGEAPPEARANCE` # 64
--- | `ABILITY_TYPE_CHARGE` # 18
--- | `ABILITY_TYPE_CLIENTFX` # 85
--- | `ABILITY_TYPE_COMBATRESOURCE` # 14
--- | `ABILITY_TYPE_COSTMECHANICOVERRIDE` # 84
--- | `ABILITY_TYPE_CREATEINTERACTABLE` # 46
--- | `ABILITY_TYPE_CREATEINVENTORYITEM` # 24
--- | `ABILITY_TYPE_CUSTOMTARGETAREA` # 101
--- | `ABILITY_TYPE_DEPRECATED_0` # 70
--- | `ABILITY_TYPE_DAMAGE` # 1
--- | `ABILITY_TYPE_DAMAGEIMMUNE` # 109
--- | `ABILITY_TYPE_DAMAGELIMIT` # 25
--- | `ABILITY_TYPE_DAMAGESHIELD` # 15
--- | `ABILITY_TYPE_DAMAGETRANSFER` # 102
--- | `ABILITY_TYPE_DEFEND` # 62
--- | `ABILITY_TYPE_DERIVEDSTATCACHE` # 94
--- | `ABILITY_TYPE_DESPAWNOVERRIDE` # 82
--- | `ABILITY_TYPE_DIRECTEDMOVEMENTABILITY` # 89
--- | `ABILITY_TYPE_DISABLECLIENTTURNING` # 108
--- | `ABILITY_TYPE_DISABLEITEMSETS` # 103
--- | `ABILITY_TYPE_DISARM` # 67
--- | `ABILITY_TYPE_DISORIENT` # 32
--- | `ABILITY_TYPE_DISPEL` # 44
--- | `ABILITY_TYPE_DODGE` # 56
--- | `ABILITY_TYPE_EXHAUSTED` # 54
--- | `ABILITY_TYPE_FACETARGET` # 106
--- | `ABILITY_TYPE_FEAR` # 27
--- | `ABILITY_TYPE_FILLSOULGEM` # 80
--- | `ABILITY_TYPE_FIRETRIGGER` # 71
--- | `ABILITY_TYPE_FLIGHT` # 31
--- | `ABILITY_TYPE_FOLLOWWAYPOINTPATH` # 104
--- | `ABILITY_TYPE_FREECAST` # 59
--- | `ABILITY_TYPE_FREEINTERACT` # 63
--- | `ABILITY_TYPE_GRANTABILITY` # 76
--- | `ABILITY_TYPE_HARDDISMOUNT` # 99
--- | `ABILITY_TYPE_HEAL` # 2
--- | `ABILITY_TYPE_HIDE` # 77
--- | `ABILITY_TYPE_HOTBARSLOTOVERRIDE` # 112
--- | `ABILITY_TYPE_IMMUNITY` # 19
--- | `ABILITY_TYPE_INTERACTREFUSALOVERRIDE` # 39
--- | `ABILITY_TYPE_INTERCEPT` # 20
--- | `ABILITY_TYPE_INTERRUPT` # 51
--- | `ABILITY_TYPE_JUMP` # 35
--- | `ABILITY_TYPE_KNOCKBACK` # 17
--- | `ABILITY_TYPE_LOSMOVEPOSITION` # 107
--- | `ABILITY_TYPE_LEAP` # 72
--- | `ABILITY_TYPE_LEVITATE` # 48
--- | `ABILITY_TYPE_LIGHTHEAVYATTACKOVERRIDE` # 93
--- | `ABILITY_TYPE_LINKTARGET` # 100
--- | `ABILITY_TYPE_MISDIRECT` # 58
--- | `ABILITY_TYPE_MODIFYCOOLDOWN` # 47
--- | `ABILITY_TYPE_MODIFYDURATION` # 55
--- | `ABILITY_TYPE_MOUNT` # 38
--- | `ABILITY_TYPE_MOUNTBLOCK` # 97
--- | `ABILITY_TYPE_MOVEPOSITION` # 16
--- | `ABILITY_TYPE_NOAGGRO` # 43
--- | `ABILITY_TYPE_NOKILL` # 42
--- | `ABILITY_TYPE_NOLOCKPICK` # 79
--- | `ABILITY_TYPE_NOSEETARGET` # 88
--- | `ABILITY_TYPE_NONCOMBATBONUS` # 87
--- | `ABILITY_TYPE_NONEXISTENT` # 41
--- | `ABILITY_TYPE_NONE` # 0
--- | `ABILITY_TYPE_OFFBALANCE` # 53
--- | `ABILITY_TYPE_PACIFY` # 49
--- | `ABILITY_TYPE_PARRY` # 68
--- | `ABILITY_TYPE_PATHLINE` # 69
--- | `ABILITY_TYPE_PERSISTENTRADIUS` # 98
--- | `ABILITY_TYPE_PHASETHROUGH` # 23
--- | `ABILITY_TYPE_PLAYERFLIGHT` # 115
--- | `ABILITY_TYPE_PREVENTHEALING` # 114
--- | `ABILITY_TYPE_RANDOMBRANCH` # 96
--- | `ABILITY_TYPE_RECALL` # 75
--- | `ABILITY_TYPE_REFLECTION` # 21
--- | `ABILITY_TYPE_REGISTERTRIGGER` # 6
--- | `ABILITY_TYPE_REMOVETYPE` # 12
--- | `ABILITY_TYPE_REPAIR` # 113
--- | `ABILITY_TYPE_RESOURCETAP` # 111
--- | `ABILITY_TYPE_RESURRECT` # 3
--- | `ABILITY_TYPE_REVEAL` # 73
--- | `ABILITY_TYPE_REWINDTIME` # 92
--- | `ABILITY_TYPE_SEESTEALTH` # 30
--- | `ABILITY_TYPE_SETAIMATTARGET` # 105
--- | `ABILITY_TYPE_SETCOOLDOWN` # 13
--- | `ABILITY_TYPE_SETHOTBAR` # 78
--- | `ABILITY_TYPE_SETPERSONALITY` # 90
--- | `ABILITY_TYPE_SETTARGET` # 7
--- | `ABILITY_TYPE_SHOWNON` # 57
--- | `ABILITY_TYPE_SIEGEAREAEFFECT` # 61
--- | `ABILITY_TYPE_SIEGECLUSTERAREAEFFECT` # 36
--- | `ABILITY_TYPE_SIEGECREATE` # 60
--- | `ABILITY_TYPE_SIEGEPACKUP` # 74
--- | `ABILITY_TYPE_SILENCE` # 11
--- | `ABILITY_TYPE_SLOWFALL` # 34
--- | `ABILITY_TYPE_SNARE` # 10
--- | `ABILITY_TYPE_SOULGEMRESURRECT` # 81
--- | `ABILITY_TYPE_STAGGER` # 33
--- | `ABILITY_TYPE_STEALTH` # 29
--- | `ABILITY_TYPE_STOPMOVING` # 110
--- | `ABILITY_TYPE_STUN` # 9
--- | `ABILITY_TYPE_SUMMON` # 37
--- | `ABILITY_TYPE_THREAT` # 8
--- | `ABILITY_TYPE_TRAUMA` # 28
--- | `ABILITY_TYPE_UPDATEDEATHDIALOG` # 83
--- | `ABILITY_TYPE_VAMPIRE` # 45

ABILITY_TYPE_ACTIONLIST = 50
ABILITY_TYPE_AREAEFFECT = 22
ABILITY_TYPE_AREATELEPORT = 26
ABILITY_TYPE_ATTACKERINTERCEPT = 66
ABILITY_TYPE_ATTACKERREFLECT = 65
ABILITY_TYPE_AVAREACH = 95
ABILITY_TYPE_AVOIDDEATH = 86
ABILITY_TYPE_BASIC = 91
ABILITY_TYPE_BLADETURN = 40
ABILITY_TYPE_BLINK = 4
ABILITY_TYPE_BLOCK = 52
ABILITY_TYPE_BONUS = 5
ABILITY_TYPE_CHANGEAPPEARANCE = 64
ABILITY_TYPE_CHARGE = 18
ABILITY_TYPE_CLIENTFX = 85
ABILITY_TYPE_COMBATRESOURCE = 14
ABILITY_TYPE_COSTMECHANICOVERRIDE = 84
ABILITY_TYPE_CREATEINTERACTABLE = 46
ABILITY_TYPE_CREATEINVENTORYITEM = 24
ABILITY_TYPE_CUSTOMTARGETAREA = 101
ABILITY_TYPE_DEPRECATED_0 = 70
ABILITY_TYPE_DAMAGE = 1
ABILITY_TYPE_DAMAGEIMMUNE = 109
ABILITY_TYPE_DAMAGELIMIT = 25
ABILITY_TYPE_DAMAGESHIELD = 15
ABILITY_TYPE_DAMAGETRANSFER = 102
ABILITY_TYPE_DEFEND = 62
ABILITY_TYPE_DERIVEDSTATCACHE = 94
ABILITY_TYPE_DESPAWNOVERRIDE = 82
ABILITY_TYPE_DIRECTEDMOVEMENTABILITY = 89
ABILITY_TYPE_DISABLECLIENTTURNING = 108
ABILITY_TYPE_DISABLEITEMSETS = 103
ABILITY_TYPE_DISARM = 67
ABILITY_TYPE_DISORIENT = 32
ABILITY_TYPE_DISPEL = 44
ABILITY_TYPE_DODGE = 56
ABILITY_TYPE_EXHAUSTED = 54
ABILITY_TYPE_FACETARGET = 106
ABILITY_TYPE_FEAR = 27
ABILITY_TYPE_FILLSOULGEM = 80
ABILITY_TYPE_FIRETRIGGER = 71
ABILITY_TYPE_FLIGHT = 31
ABILITY_TYPE_FOLLOWWAYPOINTPATH = 104
ABILITY_TYPE_FREECAST = 59
ABILITY_TYPE_FREEINTERACT = 63
ABILITY_TYPE_GRANTABILITY = 76
ABILITY_TYPE_HARDDISMOUNT = 99
ABILITY_TYPE_HEAL = 2
ABILITY_TYPE_HIDE = 77
ABILITY_TYPE_HOTBARSLOTOVERRIDE = 112
ABILITY_TYPE_IMMUNITY = 19
ABILITY_TYPE_INTERACTREFUSALOVERRIDE = 39
ABILITY_TYPE_INTERCEPT = 20
ABILITY_TYPE_INTERRUPT = 51
ABILITY_TYPE_JUMP = 35
ABILITY_TYPE_KNOCKBACK = 17
ABILITY_TYPE_LOSMOVEPOSITION = 107
ABILITY_TYPE_LEAP = 72
ABILITY_TYPE_LEVITATE = 48
ABILITY_TYPE_LIGHTHEAVYATTACKOVERRIDE = 93
ABILITY_TYPE_LINKTARGET = 100
ABILITY_TYPE_MISDIRECT = 58
ABILITY_TYPE_MODIFYCOOLDOWN = 47
ABILITY_TYPE_MODIFYDURATION = 55
ABILITY_TYPE_MOUNT = 38
ABILITY_TYPE_MOUNTBLOCK = 97
ABILITY_TYPE_MOVEPOSITION = 16
ABILITY_TYPE_NOAGGRO = 43
ABILITY_TYPE_NOKILL = 42
ABILITY_TYPE_NOLOCKPICK = 79
ABILITY_TYPE_NOSEETARGET = 88
ABILITY_TYPE_NONCOMBATBONUS = 87
ABILITY_TYPE_NONEXISTENT = 41
ABILITY_TYPE_NONE = 0
ABILITY_TYPE_OFFBALANCE = 53
ABILITY_TYPE_PACIFY = 49
ABILITY_TYPE_PARRY = 68
ABILITY_TYPE_PATHLINE = 69
ABILITY_TYPE_PERSISTENTRADIUS = 98
ABILITY_TYPE_PHASETHROUGH = 23
ABILITY_TYPE_PLAYERFLIGHT = 115
ABILITY_TYPE_PREVENTHEALING = 114
ABILITY_TYPE_RANDOMBRANCH = 96
ABILITY_TYPE_RECALL = 75
ABILITY_TYPE_REFLECTION = 21
ABILITY_TYPE_REGISTERTRIGGER = 6
ABILITY_TYPE_REMOVETYPE = 12
ABILITY_TYPE_REPAIR = 113
ABILITY_TYPE_RESOURCETAP = 111
ABILITY_TYPE_RESURRECT = 3
ABILITY_TYPE_REVEAL = 73
ABILITY_TYPE_REWINDTIME = 92
ABILITY_TYPE_SEESTEALTH = 30
ABILITY_TYPE_SETAIMATTARGET = 105
ABILITY_TYPE_SETCOOLDOWN = 13
ABILITY_TYPE_SETHOTBAR = 78
ABILITY_TYPE_SETPERSONALITY = 90
ABILITY_TYPE_SETTARGET = 7
ABILITY_TYPE_SHOWNON = 57
ABILITY_TYPE_SIEGEAREAEFFECT = 61
ABILITY_TYPE_SIEGECLUSTERAREAEFFECT = 36
ABILITY_TYPE_SIEGECREATE = 60
ABILITY_TYPE_SIEGEPACKUP = 74
ABILITY_TYPE_SILENCE = 11
ABILITY_TYPE_SLOWFALL = 34
ABILITY_TYPE_SNARE = 10
ABILITY_TYPE_SOULGEMRESURRECT = 81
ABILITY_TYPE_STAGGER = 33
ABILITY_TYPE_STEALTH = 29
ABILITY_TYPE_STOPMOVING = 110
ABILITY_TYPE_STUN = 9
ABILITY_TYPE_SUMMON = 37
ABILITY_TYPE_THREAT = 8
ABILITY_TYPE_TRAUMA = 28
ABILITY_TYPE_UPDATEDEATHDIALOG = 83
ABILITY_TYPE_VAMPIRE = 45
