--- @meta AbilityTooltipTextColors

--- @alias AbilityTooltipTextColors integer
--- | `ABILITY_TOOLTIP_TEXT_COLOR_ABILITY_INFO` # 10
--- | `ABILITY_TOOLTIP_TEXT_COLOR_BODY` # 2
--- | `ABILITY_TOOLTIP_TEXT_COLOR_BRONZE_ABILITY` # 6
--- | `ABILITY_TOOLTIP_TEXT_COLOR_DEFAULT` # 0
--- | `ABILITY_TOOLTIP_TEXT_COLOR_FAILED_REQUIREMENT` # 4
--- | `ABILITY_TOOLTIP_TEXT_COLOR_GOLD_ABILITY` # 8
--- | `ABILITY_TOOLTIP_TEXT_COLOR_NAME` # 1
--- | `ABILITY_TOOLTIP_TEXT_COLOR_NEW_EFFECT` # 14
--- | `ABILITY_TOOLTIP_TEXT_COLOR_SILVER_ABILITY` # 7
--- | `ABILITY_TOOLTIP_TEXT_COLOR_SPECIAL_HEADER` # 5
--- | `ABILITY_TOOLTIP_TEXT_COLOR_UPGRADES` # 15
--- | `ABILITY_TOOLTIP_TEXT_COLOR_UPGRADE_TO_ABILITY` # 9
--- | `ABILITY_TOOLTIP_TEXT_COLOR_USE_INFO_TYPE1` # 11
--- | `ABILITY_TOOLTIP_TEXT_COLOR_USE_INFO_TYPE2` # 12
--- | `ABILITY_TOOLTIP_TEXT_COLOR_USE_INFO_TYPE3` # 13
--- | `ABILITY_TOOLTIP_TEXT_COLOR_VALID_REQUIREMENT` # 3

ABILITY_TOOLTIP_TEXT_COLOR_ABILITY_INFO = 10
ABILITY_TOOLTIP_TEXT_COLOR_BODY = 2
ABILITY_TOOLTIP_TEXT_COLOR_BRONZE_ABILITY = 6
ABILITY_TOOLTIP_TEXT_COLOR_DEFAULT = 0
ABILITY_TOOLTIP_TEXT_COLOR_FAILED_REQUIREMENT = 4
ABILITY_TOOLTIP_TEXT_COLOR_GOLD_ABILITY = 8
ABILITY_TOOLTIP_TEXT_COLOR_NAME = 1
ABILITY_TOOLTIP_TEXT_COLOR_NEW_EFFECT = 14
ABILITY_TOOLTIP_TEXT_COLOR_SILVER_ABILITY = 7
ABILITY_TOOLTIP_TEXT_COLOR_SPECIAL_HEADER = 5
ABILITY_TOOLTIP_TEXT_COLOR_UPGRADES = 15
ABILITY_TOOLTIP_TEXT_COLOR_UPGRADE_TO_ABILITY = 9
ABILITY_TOOLTIP_TEXT_COLOR_USE_INFO_TYPE1 = 11
ABILITY_TOOLTIP_TEXT_COLOR_USE_INFO_TYPE2 = 12
ABILITY_TOOLTIP_TEXT_COLOR_USE_INFO_TYPE3 = 13
ABILITY_TOOLTIP_TEXT_COLOR_VALID_REQUIREMENT = 3
