--- @meta AbilityProgressionResult

--- @alias AbilityProgressionResult integer
--- | `ABILITY_PROGRESSION_RESULT_ABILITY_NOT_KNOWN` # 1
--- | `ABILITY_PROGRESSION_RESULT_INVALID_LINE` # 3
--- | `ABILITY_PROGRESSION_RESULT_MORPH_CHOSEN` # 6
--- | `ABILITY_PROGRESSION_RESULT_MORPH_NOT_CHOSEN` # 8
--- | `ABILITY_PROGRESSION_RESULT_NOT_ENOUGH_MONEY` # 5
--- | `ABILITY_PROGRESSION_RESULT_NOT_HIGH_ENOUGH_LEVEL` # 7
--- | `ABILITY_PROGRESSION_RESULT_NO_MORE_UPGRADES` # 2
--- | `ABILITY_PROGRESSION_RESULT_NO_SKILL_POINTS` # 10
--- | `ABILITY_PROGRESSION_RESULT_NO_VALID_UPGRADE` # 9
--- | `ABILITY_PROGRESSION_RESULT_SUCCESS` # 0
--- | `ABILITY_PROGRESSION_RESULT_TOO_LOW_LEVEL` # 4

ABILITY_PROGRESSION_RESULT_ABILITY_NOT_KNOWN = 1
ABILITY_PROGRESSION_RESULT_INVALID_LINE = 3
ABILITY_PROGRESSION_RESULT_MORPH_CHOSEN = 6
ABILITY_PROGRESSION_RESULT_MORPH_NOT_CHOSEN = 8
ABILITY_PROGRESSION_RESULT_NOT_ENOUGH_MONEY = 5
ABILITY_PROGRESSION_RESULT_NOT_HIGH_ENOUGH_LEVEL = 7
ABILITY_PROGRESSION_RESULT_NO_MORE_UPGRADES = 2
ABILITY_PROGRESSION_RESULT_NO_SKILL_POINTS = 10
ABILITY_PROGRESSION_RESULT_NO_VALID_UPGRADE = 9
ABILITY_PROGRESSION_RESULT_SUCCESS = 0
ABILITY_PROGRESSION_RESULT_TOO_LOW_LEVEL = 4
