--- @meta AccessibilitySetting

--- @alias AccessibilitySetting integer
--- | `ACCESSIBILITY_SETTING_ACCESSIBILITY_MODE` # 0
--- | `ACCESSIBILITY_SETTING_ACCESSIBLE_QUICKWHEELS` # 9
--- | `ACCESSIBILITY_SETTING_GAMEPAD_AIM_ASSIST_INTENSITY` # 10
--- | `ACCESSIBILITY_SETTING_MOUSE_AIM_ASSIST_INTENSITY` # 11
--- | `ACCESSIBILITY_SETTING_NARRATION_VOICE_SPEED` # 6
--- | `ACCESSIBILITY_SETTING_NARRATION_VOICE_TYPE` # 7
--- | `ACCESSIBILITY_SETTING_NARRATION_VOLUME` # 8
--- | `ACCESSIBILITY_SETTING_SCREEN_NARRATION` # 5
--- | `ACCESSIBILITY_SETTING_SEND_TRANSCRIPT_TO_TEXT_CHAT` # 3
--- | `ACCESSIBILITY_SETTING_TEXT_CHAT_NARRATION` # 2
--- | `ACCESSIBILITY_SETTING_TEXT_INPUT_NARRATION` # 12
--- | `ACCESSIBILITY_SETTING_VOICE_CHAT_ACCESSIBILITY` # 1
--- | `ACCESSIBILITY_SETTING_ZONE_CHAT_NARRATION` # 4

ACCESSIBILITY_SETTING_ACCESSIBILITY_MODE = 0
ACCESSIBILITY_SETTING_ACCESSIBLE_QUICKWHEELS = 9
ACCESSIBILITY_SETTING_GAMEPAD_AIM_ASSIST_INTENSITY = 10
ACCESSIBILITY_SETTING_MOUSE_AIM_ASSIST_INTENSITY = 11
ACCESSIBILITY_SETTING_NARRATION_VOICE_SPEED = 6
ACCESSIBILITY_SETTING_NARRATION_VOICE_TYPE = 7
ACCESSIBILITY_SETTING_NARRATION_VOLUME = 8
ACCESSIBILITY_SETTING_SCREEN_NARRATION = 5
ACCESSIBILITY_SETTING_SEND_TRANSCRIPT_TO_TEXT_CHAT = 3
ACCESSIBILITY_SETTING_TEXT_CHAT_NARRATION = 2
ACCESSIBILITY_SETTING_TEXT_INPUT_NARRATION = 12
ACCESSIBILITY_SETTING_VOICE_CHAT_ACCESSIBILITY = 1
ACCESSIBILITY_SETTING_ZONE_CHAT_NARRATION = 4
