--- @meta AccountNamingError

--- @alias AccountNamingError integer
--- | `ACCOUNT_NAME_RULE_INCORRECT_LENGTH` # 1
--- | `ACCOUNT_NAME_RULE_INVALID_CHARACTERS` # 7
--- | `ACCOUNT_NAME_RULE_MUST_END_WITH_NUMBER_OR_LETTER` # 5
--- | `ACCOUNT_NAME_RULE_MUST_START_WITH_LETTER` # 4
--- | `ACCOUNT_NAME_RULE_NO_ERROR` # 0
--- | `ACCOUNT_NAME_RULE_NO_SPACES` # 6
--- | `ACCOUNT_NAME_RULE_TOO_MANY_IDENTICAL_ADJACENT_CHARACTERS` # 2
--- | `ACCOUNT_NAME_RULE_TOO_MANY_PUNCTUATION_CHARACTERS` # 3

ACCOUNT_NAME_RULE_INCORRECT_LENGTH = 1
ACCOUNT_NAME_RULE_INVALID_CHARACTERS = 7
ACCOUNT_NAME_RULE_MUST_END_WITH_NUMBER_OR_LETTER = 5
ACCOUNT_NAME_RULE_MUST_START_WITH_LETTER = 4
ACCOUNT_NAME_RULE_NO_ERROR = 0
ACCOUNT_NAME_RULE_NO_SPACES = 6
ACCOUNT_NAME_RULE_TOO_MANY_IDENTICAL_ADJACENT_CHARACTERS = 2
ACCOUNT_NAME_RULE_TOO_MANY_PUNCTUATION_CHARACTERS = 3
