--- @meta AccountResendActivationResult

--- @alias AccountResendActivationResult integer
--- | `ACCOUNT_RESEND_ACTIVATION_RESULT_ACCOUNT_ALREADY_ACTIVATED_ERROR` # 2
--- | `ACCOUNT_RESEND_ACTIVATION_RESULT_ERROR` # 3
--- | `ACCOUNT_RESEND_ACTIVATION_RESULT_SUCCESS` # 0
--- | `ACCOUNT_RESEND_ACTIVATION_RESULT_TIMEOUT` # 4
--- | `ACCOUNT_RESEND_ACTIVATION_RESULT_USER_NOT_FOUND_ERROR` # 1

ACCOUNT_RESEND_ACTIVATION_RESULT_ACCOUNT_ALREADY_ACTIVATED_ERROR = 2
ACCOUNT_RESEND_ACTIVATION_RESULT_ERROR = 3
ACCOUNT_RESEND_ACTIVATION_RESULT_SUCCESS = 0
ACCOUNT_RESEND_ACTIVATION_RESULT_TIMEOUT = 4
ACCOUNT_RESEND_ACTIVATION_RESULT_USER_NOT_FOUND_ERROR = 1
