--- @meta AccountEmailRequestResult

--- @alias AccountEmailRequestResult integer
--- | `ACCOUNT_EMAIL_REQUEST_RESULT_EMAIL_ALREADY_TAKEN` # 6
--- | `ACCOUNT_EMAIL_REQUEST_RESULT_ERROR` # 2
--- | `ACCOUNT_EMAIL_REQUEST_RESULT_INVALID_EMAIL_ADDRESS` # 3
--- | `ACCOUNT_EMAIL_REQUEST_RESULT_MESSAGE_RATE_LIMIT` # 4
--- | `ACCOUNT_EMAIL_REQUEST_RESULT_SERVICE_NOT_FOUND` # 5
--- | `ACCOUNT_EMAIL_REQUEST_RESULT_SUCCESS` # 0
--- | `ACCOUNT_EMAIL_REQUEST_RESULT_SUCCESS_EMAIL_UPDATED` # 1
--- | `ACCOUNT_EMAIL_REQUEST_RESULT_TIMEOUT` # 7

ACCOUNT_EMAIL_REQUEST_RESULT_EMAIL_ALREADY_TAKEN = 6
ACCOUNT_EMAIL_REQUEST_RESULT_ERROR = 2
ACCOUNT_EMAIL_REQUEST_RESULT_INVALID_EMAIL_ADDRESS = 3
ACCOUNT_EMAIL_REQUEST_RESULT_MESSAGE_RATE_LIMIT = 4
ACCOUNT_EMAIL_REQUEST_RESULT_SERVICE_NOT_FOUND = 5
ACCOUNT_EMAIL_REQUEST_RESULT_SUCCESS = 0
ACCOUNT_EMAIL_REQUEST_RESULT_SUCCESS_EMAIL_UPDATED = 1
ACCOUNT_EMAIL_REQUEST_RESULT_TIMEOUT = 7
