--- @meta AchievementPointValue

--- @alias AchievementPointValue integer
--- | `ACHIEVEMENT_POINT_HIGH` # 15
--- | `ACHIEVEMENT_POINT_LEGENDARY_DEED` # 0
--- | `ACHIEVEMENT_POINT_LOW` # 5
--- | `ACHIEVEMENT_POINT_MEDIUM` # 10
--- | `ACHIEVEMENT_POINT_VERY_HIGH` # 50

ACHIEVEMENT_POINT_HIGH = 15
ACHIEVEMENT_POINT_LEGENDARY_DEED = 0
ACHIEVEMENT_POINT_LOW = 5
ACHIEVEMENT_POINT_MEDIUM = 10
ACHIEVEMENT_POINT_VERY_HIGH = 50
