--- @meta AchievementPersistenceLevel

--- @alias AchievementPersistenceLevel integer
--- | `ACHIEVEMENT_PERSISTENCE_ACCOUNT` # 1
--- | `ACHIEVEMENT_PERSISTENCE_CHARACTER` # 0
--- | `ACHIEVEMENT_PERSISTENCE_UNDEFINED` # -1

ACHIEVEMENT_PERSISTENCE_ACCOUNT = 1
ACHIEVEMENT_PERSISTENCE_CHARACTER = 0
ACHIEVEMENT_PERSISTENCE_UNDEFINED = -1
