--- @meta ActionBarSettingChoice

--- @alias ActionBarSettingChoice integer
--- | `ACTION_BAR_SETTING_CHOICE_AUTOMATIC` # 2
--- | `ACTION_BAR_SETTING_CHOICE_OFF` # 0
--- | `ACTION_BAR_SETTING_CHOICE_ON` # 1

ACTION_BAR_SETTING_CHOICE_AUTOMATIC = 2
ACTION_BAR_SETTING_CHOICE_OFF = 0
ACTION_BAR_SETTING_CHOICE_ON = 1
