--- @meta ActionBarLockedReason

--- @alias ActionBarLockedReason integer
--- | `ACTION_BAR_LOCKED_REASON_COMBAT` # 1
--- | `ACTION_BAR_LOCKED_REASON_NONE` # 0
--- | `ACTION_BAR_LOCKED_REASON_NOT_RESPECCABLE` # 2

ACTION_BAR_LOCKED_REASON_COMBAT = 1
ACTION_BAR_LOCKED_REASON_NONE = 0
ACTION_BAR_LOCKED_REASON_NOT_RESPECCABLE = 2
