--- @meta ActivityFinderStatus

--- @alias ActivityFinderStatus integer
--- | `ACTIVITY_FINDER_STATUS_COMPLETE` # 3
--- | `ACTIVITY_FINDER_STATUS_FORMING_GROUP` # 5
--- | `ACTIVITY_FINDER_STATUS_IN_PROGRESS` # 2
--- | `ACTIVITY_FINDER_STATUS_NONE` # 0
--- | `ACTIVITY_FINDER_STATUS_QUEUED` # 1
--- | `ACTIVITY_FINDER_STATUS_READY_CHECK` # 4

ACTIVITY_FINDER_STATUS_COMPLETE = 3
ACTIVITY_FINDER_STATUS_FORMING_GROUP = 5
ACTIVITY_FINDER_STATUS_IN_PROGRESS = 2
ACTIVITY_FINDER_STATUS_NONE = 0
ACTIVITY_FINDER_STATUS_QUEUED = 1
ACTIVITY_FINDER_STATUS_READY_CHECK = 4
