--- @meta ActiveCombatTipConditionResult

--- @alias ActiveCombatTipConditionResult integer
--- | `ACTIVE_COMBAT_TIP_RESULT_FAILURE` # 1
--- | `ACTIVE_COMBAT_TIP_RESULT_NO_ACTION` # 2
--- | `ACTIVE_COMBAT_TIP_RESULT_SUCCESS` # 0

ACTIVE_COMBAT_TIP_RESULT_FAILURE = 1
ACTIVE_COMBAT_TIP_RESULT_NO_ACTION = 2
ACTIVE_COMBAT_TIP_RESULT_SUCCESS = 0
