--- @meta ActiveCombatTipColors

--- @alias ActiveCombatTipColors integer
--- | `ACTIVE_COMBAT_TIP_COLOR_FAILURE` # 1
--- | `ACTIVE_COMBAT_TIP_COLOR_NORMAL` # 2
--- | `ACTIVE_COMBAT_TIP_COLOR_SUCCESS` # 0

ACTIVE_COMBAT_TIP_COLOR_FAILURE = 1
ACTIVE_COMBAT_TIP_COLOR_NORMAL = 2
ACTIVE_COMBAT_TIP_COLOR_SUCCESS = 0
