--- @meta ActivityQueueResult

--- @alias ActivityQueueResult integer
--- | `ACTIVITY_QUEUE_RESULT_CAMPAIGN_MISMATCH` # 18
--- | `ACTIVITY_QUEUE_RESULT_CANNOT_QUEUE_IN_BATTLEGROUND` # 22
--- | `ACTIVITY_QUEUE_RESULT_DEPRECATED_REUSE_ME` # 1
--- | `ACTIVITY_QUEUE_RESULT_DESTINATION_NO_LONGER_VALID` # 16
--- | `ACTIVITY_QUEUE_RESULT_DLC_LOCKED` # 6
--- | `ACTIVITY_QUEUE_RESULT_ERROR_GROUP_FINDER` # 33
--- | `ACTIVITY_QUEUE_RESULT_GROUP_OR_INSTANCE_FULL` # 25
--- | `ACTIVITY_QUEUE_RESULT_GROUP_STRUCTURE_CHANGED` # 20
--- | `ACTIVITY_QUEUE_RESULT_GROUP_TOO_LARGE` # 3
--- | `ACTIVITY_QUEUE_RESULT_INCOMPATIBLE_GROUP` # 9
--- | `ACTIVITY_QUEUE_RESULT_INCOMPATIBLE_REGION` # 10
--- | `ACTIVITY_QUEUE_RESULT_INVALID_LEVEL` # 4
--- | `ACTIVITY_QUEUE_RESULT_IN_TRIBUTE_MATCH` # 30
--- | `ACTIVITY_QUEUE_RESULT_LOCATION_RESTRICTION` # 5
--- | `ACTIVITY_QUEUE_RESULT_MEMBERS_OFFLINE` # 14
--- | `ACTIVITY_QUEUE_RESULT_MEMBER_LOCATION_NOT_VALID` # 17
--- | `ACTIVITY_QUEUE_RESULT_MEMEBER_CANCELED_READY_CHECK` # 19
--- | `ACTIVITY_QUEUE_RESULT_NEW_SEARCH_INITIATED` # 21
--- | `ACTIVITY_QUEUE_RESULT_NOT_GROUP_LEADER` # 2
--- | `ACTIVITY_QUEUE_RESULT_NOT_IMPLEMENTED` # 7
--- | `ACTIVITY_QUEUE_RESULT_NO_ACTIVITIES_SELECTED` # 8
--- | `ACTIVITY_QUEUE_RESULT_NO_GROUP` # 11
--- | `ACTIVITY_QUEUE_RESULT_ON_QUEUE_COOLDOWN` # 12
--- | `ACTIVITY_QUEUE_RESULT_QUEUE_BUSY` # 23
--- | `ACTIVITY_QUEUE_RESULT_QUEUE_FULL` # 24
--- | `ACTIVITY_QUEUE_RESULT_QUEUE_TTL_EXPIRED` # 15
--- | `ACTIVITY_QUEUE_RESULT_REQUEST_QUEUED` # 26
--- | `ACTIVITY_QUEUE_RESULT_REQUEST_QUEUE_FAILURE` # 27
--- | `ACTIVITY_QUEUE_RESULT_SUCCESS` # 0
--- | `ACTIVITY_QUEUE_RESULT_TRIBUTE_ACCESS_DENIED` # 31
--- | `ACTIVITY_QUEUE_RESULT_TRIBUTE_CASUAL_LFG_DISABLED` # 32
--- | `ACTIVITY_QUEUE_RESULT_TRIBUTE_COMPETITIVE_LFG_DISABLED` # 28
--- | `ACTIVITY_QUEUE_RESULT_TRIBUTE_INVALID_AREA` # 29
--- | `ACTIVITY_QUEUE_RESULT_UNSPECIFIED_INTERNAL_ERROR` # 13

ACTIVITY_QUEUE_RESULT_CAMPAIGN_MISMATCH = 18
ACTIVITY_QUEUE_RESULT_CANNOT_QUEUE_IN_BATTLEGROUND = 22
ACTIVITY_QUEUE_RESULT_DEPRECATED_REUSE_ME = 1
ACTIVITY_QUEUE_RESULT_DESTINATION_NO_LONGER_VALID = 16
ACTIVITY_QUEUE_RESULT_DLC_LOCKED = 6
ACTIVITY_QUEUE_RESULT_ERROR_GROUP_FINDER = 33
ACTIVITY_QUEUE_RESULT_GROUP_OR_INSTANCE_FULL = 25
ACTIVITY_QUEUE_RESULT_GROUP_STRUCTURE_CHANGED = 20
ACTIVITY_QUEUE_RESULT_GROUP_TOO_LARGE = 3
ACTIVITY_QUEUE_RESULT_INCOMPATIBLE_GROUP = 9
ACTIVITY_QUEUE_RESULT_INCOMPATIBLE_REGION = 10
ACTIVITY_QUEUE_RESULT_INVALID_LEVEL = 4
ACTIVITY_QUEUE_RESULT_IN_TRIBUTE_MATCH = 30
ACTIVITY_QUEUE_RESULT_LOCATION_RESTRICTION = 5
ACTIVITY_QUEUE_RESULT_MEMBERS_OFFLINE = 14
ACTIVITY_QUEUE_RESULT_MEMBER_LOCATION_NOT_VALID = 17
ACTIVITY_QUEUE_RESULT_MEMEBER_CANCELED_READY_CHECK = 19
ACTIVITY_QUEUE_RESULT_NEW_SEARCH_INITIATED = 21
ACTIVITY_QUEUE_RESULT_NOT_GROUP_LEADER = 2
ACTIVITY_QUEUE_RESULT_NOT_IMPLEMENTED = 7
ACTIVITY_QUEUE_RESULT_NO_ACTIVITIES_SELECTED = 8
ACTIVITY_QUEUE_RESULT_NO_GROUP = 11
ACTIVITY_QUEUE_RESULT_ON_QUEUE_COOLDOWN = 12
ACTIVITY_QUEUE_RESULT_QUEUE_BUSY = 23
ACTIVITY_QUEUE_RESULT_QUEUE_FULL = 24
ACTIVITY_QUEUE_RESULT_QUEUE_TTL_EXPIRED = 15
ACTIVITY_QUEUE_RESULT_REQUEST_QUEUED = 26
ACTIVITY_QUEUE_RESULT_REQUEST_QUEUE_FAILURE = 27
ACTIVITY_QUEUE_RESULT_SUCCESS = 0
ACTIVITY_QUEUE_RESULT_TRIBUTE_ACCESS_DENIED = 31
ACTIVITY_QUEUE_RESULT_TRIBUTE_CASUAL_LFG_DISABLED = 32
ACTIVITY_QUEUE_RESULT_TRIBUTE_COMPETITIVE_LFG_DISABLED = 28
ACTIVITY_QUEUE_RESULT_TRIBUTE_INVALID_AREA = 29
ACTIVITY_QUEUE_RESULT_UNSPECIFIED_INTERNAL_ERROR = 13
