--- @meta ActionBarSlotType

--- @alias ActionBarSlotType integer
--- | `ACTION_TYPE_ABILITY` # 1
--- | `ACTION_TYPE_CHAMPION_SKILL` # 6
--- | `ACTION_TYPE_COLLECTIBLE` # 7
--- | `ACTION_TYPE_CRAFTED_ABILITY` # 3
--- | `ACTION_TYPE_EMOTE` # 8
--- | `ACTION_TYPE_ITEM` # 2
--- | `ACTION_TYPE_NOTHING` # 0
--- | `ACTION_TYPE_QUEST_ITEM` # 10
--- | `ACTION_TYPE_QUICK_CHAT` # 9

ACTION_TYPE_ABILITY = 1
ACTION_TYPE_CHAMPION_SKILL = 6
ACTION_TYPE_COLLECTIBLE = 7
ACTION_TYPE_CRAFTED_ABILITY = 3
ACTION_TYPE_EMOTE = 8
ACTION_TYPE_ITEM = 2
ACTION_TYPE_NOTHING = 0
ACTION_TYPE_QUEST_ITEM = 10
ACTION_TYPE_QUICK_CHAT = 9
