--- @meta ActionSlotType

--- @alias ActionSlotType integer
--- | `ACTION_SLOT_TYPE_BLOCK` # 4
--- | `ACTION_SLOT_TYPE_HEAVY_ATTACK` # 6
--- | `ACTION_SLOT_TYPE_LIGHT_ATTACK` # 5
--- | `ACTION_SLOT_TYPE_NORMAL_ABILITY` # 0
--- | `ACTION_SLOT_TYPE_OTHER` # 3
--- | `ACTION_SLOT_TYPE_ULTIMATE` # 2
--- | `ACTION_SLOT_TYPE_WEAPON_ATTACK` # 1

ACTION_SLOT_TYPE_BLOCK = 4
ACTION_SLOT_TYPE_HEAVY_ATTACK = 6
ACTION_SLOT_TYPE_LIGHT_ATTACK = 5
ACTION_SLOT_TYPE_NORMAL_ABILITY = 0
ACTION_SLOT_TYPE_OTHER = 3
ACTION_SLOT_TYPE_ULTIMATE = 2
ACTION_SLOT_TYPE_WEAPON_ATTACK = 1
