--- @meta AddOnLoadState

--- @alias AddOnLoadState integer
--- | `ADDON_STATE_DEPENDENCIES_DISABLED` # 5
--- | `ADDON_STATE_DISABLED` # 3
--- | `ADDON_STATE_ENABLED` # 2
--- | `ADDON_STATE_ERROR_STATE_UNABLE_TO_LOAD` # 6
--- | `ADDON_STATE_NO_STATE` # 0
--- | `ADDON_STATE_TOC_LOADED` # 1
--- | `ADDON_STATE_VERSION_MISMATCH` # 4

ADDON_STATE_DEPENDENCIES_DISABLED = 5
ADDON_STATE_DISABLED = 3
ADDON_STATE_ENABLED = 2
ADDON_STATE_ERROR_STATE_UNABLE_TO_LOAD = 6
ADDON_STATE_NO_STATE = 0
ADDON_STATE_TOC_LOADED = 1
ADDON_STATE_VERSION_MISMATCH = 4
