--- @meta AdvancedStatDisplayFormat

--- @alias AdvancedStatDisplayFormat integer
--- | `ADVANCED_STAT_DISPLAY_FORMAT_FLAT` # 1
--- | `ADVANCED_STAT_DISPLAY_FORMAT_FLAT_AND_PERCENT` # 3
--- | `ADVANCED_STAT_DISPLAY_FORMAT_FLAT_OR_PERCENT` # 4
--- | `ADVANCED_STAT_DISPLAY_FORMAT_NONE` # 0
--- | `ADVANCED_STAT_DISPLAY_FORMAT_PERCENT` # 2

ADVANCED_STAT_DISPLAY_FORMAT_FLAT = 1
ADVANCED_STAT_DISPLAY_FORMAT_FLAT_AND_PERCENT = 3
ADVANCED_STAT_DISPLAY_FORMAT_FLAT_OR_PERCENT = 4
ADVANCED_STAT_DISPLAY_FORMAT_NONE = 0
ADVANCED_STAT_DISPLAY_FORMAT_PERCENT = 2
