--- @meta AdvancedStatDisplayType

--- @alias AdvancedStatDisplayType integer
--- | `ADVANCED_STAT_DISPLAY_TYPE_ALL_XP` # 49
--- | `ADVANCED_STAT_DISPLAY_TYPE_ARMOR` # 29
--- | `ADVANCED_STAT_DISPLAY_TYPE_BASH_COST` # 2
--- | `ADVANCED_STAT_DISPLAY_TYPE_BASH_DAMAGE` # 3
--- | `ADVANCED_STAT_DISPLAY_TYPE_BLEED_DAMAGE` # 19
--- | `ADVANCED_STAT_DISPLAY_TYPE_BLEED_RESIST` # 27
--- | `ADVANCED_STAT_DISPLAY_TYPE_BLOCK_COST` # 1
--- | `ADVANCED_STAT_DISPLAY_TYPE_BLOCK_MITIGATION` # 7
--- | `ADVANCED_STAT_DISPLAY_TYPE_BLOCK_SPEED` # 45
--- | `ADVANCED_STAT_DISPLAY_TYPE_CC_BREAK_COST` # 8
--- | `ADVANCED_STAT_DISPLAY_TYPE_COLD_DAMAGE` # 10
--- | `ADVANCED_STAT_DISPLAY_TYPE_COLD_RESIST` # 40
--- | `ADVANCED_STAT_DISPLAY_TYPE_CRITICAL_CHANCE` # 25
--- | `ADVANCED_STAT_DISPLAY_TYPE_CRITICAL_DAMAGE` # 23
--- | `ADVANCED_STAT_DISPLAY_TYPE_CRITICAL_HEALING` # 22
--- | `ADVANCED_STAT_DISPLAY_TYPE_CRITICAL_PERCENT` # 21
--- | `ADVANCED_STAT_DISPLAY_TYPE_CRITICAL_RESIST` # 34
--- | `ADVANCED_STAT_DISPLAY_TYPE_DISEASE_DAMAGE` # 11
--- | `ADVANCED_STAT_DISPLAY_TYPE_DISEASE_RESIST` # 33
--- | `ADVANCED_STAT_DISPLAY_TYPE_DODGE_COST` # 4
--- | `ADVANCED_STAT_DISPLAY_TYPE_EARTH_DAMAGE` # 12
--- | `ADVANCED_STAT_DISPLAY_TYPE_EARTH_RESIST` # 39
--- | `ADVANCED_STAT_DISPLAY_TYPE_FIRE_DAMAGE` # 13
--- | `ADVANCED_STAT_DISPLAY_TYPE_FIRE_RESIST` # 31
--- | `ADVANCED_STAT_DISPLAY_TYPE_FROST_RESIST` # 36
--- | `ADVANCED_STAT_DISPLAY_TYPE_GENERIC_DAMAGE` # 20
--- | `ADVANCED_STAT_DISPLAY_TYPE_GENERIC_RESIST` # 42
--- | `ADVANCED_STAT_DISPLAY_TYPE_HEALING_DONE` # 43
--- | `ADVANCED_STAT_DISPLAY_TYPE_HEALING_DONE_BONUSES` # 51
--- | `ADVANCED_STAT_DISPLAY_TYPE_HEALING_TAKEN` # 44
--- | `ADVANCED_STAT_DISPLAY_TYPE_HEALING_TAKEN_BONUSES` # 50
--- | `ADVANCED_STAT_DISPLAY_TYPE_MAGIC_DAMAGE` # 14
--- | `ADVANCED_STAT_DISPLAY_TYPE_MAGIC_RESIST` # 41
--- | `ADVANCED_STAT_DISPLAY_TYPE_MONSTER_KILL_XP` # 47
--- | `ADVANCED_STAT_DISPLAY_TYPE_NONE` # 0
--- | `ADVANCED_STAT_DISPLAY_TYPE_OBLIVION_DAMAGE` # 15
--- | `ADVANCED_STAT_DISPLAY_TYPE_OBLIVION_RESIST` # 38
--- | `ADVANCED_STAT_DISPLAY_TYPE_PHYSICAL_DAMAGE` # 16
--- | `ADVANCED_STAT_DISPLAY_TYPE_PHYSICAL_PENETRATION` # 28
--- | `ADVANCED_STAT_DISPLAY_TYPE_PHYSICAL_RESIST` # 35
--- | `ADVANCED_STAT_DISPLAY_TYPE_PLAYER_KILL_XP` # 48
--- | `ADVANCED_STAT_DISPLAY_TYPE_POISON_DAMAGE` # 17
--- | `ADVANCED_STAT_DISPLAY_TYPE_POISON_RESIST` # 37
--- | `ADVANCED_STAT_DISPLAY_TYPE_SHOCK_DAMAGE` # 18
--- | `ADVANCED_STAT_DISPLAY_TYPE_SHOCK_RESIST` # 32
--- | `ADVANCED_STAT_DISPLAY_TYPE_SNEAK_COST` # 5
--- | `ADVANCED_STAT_DISPLAY_TYPE_SNEAK_SPEED_REDUCTION` # 6
--- | `ADVANCED_STAT_DISPLAY_TYPE_SPELL_PENETRATION` # 26
--- | `ADVANCED_STAT_DISPLAY_TYPE_SPELL_RESIST` # 30
--- | `ADVANCED_STAT_DISPLAY_TYPE_SPRINT_COST` # 24
--- | `ADVANCED_STAT_DISPLAY_TYPE_SPRINT_SPEED` # 9
--- | `ADVANCED_STAT_DISPLAY_TYPE_ULTIMATE_REGEN_COMBAT` # 46

ADVANCED_STAT_DISPLAY_TYPE_ALL_XP = 49
ADVANCED_STAT_DISPLAY_TYPE_ARMOR = 29
ADVANCED_STAT_DISPLAY_TYPE_BASH_COST = 2
ADVANCED_STAT_DISPLAY_TYPE_BASH_DAMAGE = 3
ADVANCED_STAT_DISPLAY_TYPE_BLEED_DAMAGE = 19
ADVANCED_STAT_DISPLAY_TYPE_BLEED_RESIST = 27
ADVANCED_STAT_DISPLAY_TYPE_BLOCK_COST = 1
ADVANCED_STAT_DISPLAY_TYPE_BLOCK_MITIGATION = 7
ADVANCED_STAT_DISPLAY_TYPE_BLOCK_SPEED = 45
ADVANCED_STAT_DISPLAY_TYPE_CC_BREAK_COST = 8
ADVANCED_STAT_DISPLAY_TYPE_COLD_DAMAGE = 10
ADVANCED_STAT_DISPLAY_TYPE_COLD_RESIST = 40
ADVANCED_STAT_DISPLAY_TYPE_CRITICAL_CHANCE = 25
ADVANCED_STAT_DISPLAY_TYPE_CRITICAL_DAMAGE = 23
ADVANCED_STAT_DISPLAY_TYPE_CRITICAL_HEALING = 22
ADVANCED_STAT_DISPLAY_TYPE_CRITICAL_PERCENT = 21
ADVANCED_STAT_DISPLAY_TYPE_CRITICAL_RESIST = 34
ADVANCED_STAT_DISPLAY_TYPE_DISEASE_DAMAGE = 11
ADVANCED_STAT_DISPLAY_TYPE_DISEASE_RESIST = 33
ADVANCED_STAT_DISPLAY_TYPE_DODGE_COST = 4
ADVANCED_STAT_DISPLAY_TYPE_EARTH_DAMAGE = 12
ADVANCED_STAT_DISPLAY_TYPE_EARTH_RESIST = 39
ADVANCED_STAT_DISPLAY_TYPE_FIRE_DAMAGE = 13
ADVANCED_STAT_DISPLAY_TYPE_FIRE_RESIST = 31
ADVANCED_STAT_DISPLAY_TYPE_FROST_RESIST = 36
ADVANCED_STAT_DISPLAY_TYPE_GENERIC_DAMAGE = 20
ADVANCED_STAT_DISPLAY_TYPE_GENERIC_RESIST = 42
ADVANCED_STAT_DISPLAY_TYPE_HEALING_DONE = 43
ADVANCED_STAT_DISPLAY_TYPE_HEALING_DONE_BONUSES = 51
ADVANCED_STAT_DISPLAY_TYPE_HEALING_TAKEN = 44
ADVANCED_STAT_DISPLAY_TYPE_HEALING_TAKEN_BONUSES = 50
ADVANCED_STAT_DISPLAY_TYPE_MAGIC_DAMAGE = 14
ADVANCED_STAT_DISPLAY_TYPE_MAGIC_RESIST = 41
ADVANCED_STAT_DISPLAY_TYPE_MONSTER_KILL_XP = 47
ADVANCED_STAT_DISPLAY_TYPE_NONE = 0
ADVANCED_STAT_DISPLAY_TYPE_OBLIVION_DAMAGE = 15
ADVANCED_STAT_DISPLAY_TYPE_OBLIVION_RESIST = 38
ADVANCED_STAT_DISPLAY_TYPE_PHYSICAL_DAMAGE = 16
ADVANCED_STAT_DISPLAY_TYPE_PHYSICAL_PENETRATION = 28
ADVANCED_STAT_DISPLAY_TYPE_PHYSICAL_RESIST = 35
ADVANCED_STAT_DISPLAY_TYPE_PLAYER_KILL_XP = 48
ADVANCED_STAT_DISPLAY_TYPE_POISON_DAMAGE = 17
ADVANCED_STAT_DISPLAY_TYPE_POISON_RESIST = 37
ADVANCED_STAT_DISPLAY_TYPE_SHOCK_DAMAGE = 18
ADVANCED_STAT_DISPLAY_TYPE_SHOCK_RESIST = 32
ADVANCED_STAT_DISPLAY_TYPE_SNEAK_COST = 5
ADVANCED_STAT_DISPLAY_TYPE_SNEAK_SPEED_REDUCTION = 6
ADVANCED_STAT_DISPLAY_TYPE_SPELL_PENETRATION = 26
ADVANCED_STAT_DISPLAY_TYPE_SPELL_RESIST = 30
ADVANCED_STAT_DISPLAY_TYPE_SPRINT_COST = 24
ADVANCED_STAT_DISPLAY_TYPE_SPRINT_SPEED = 9
ADVANCED_STAT_DISPLAY_TYPE_ULTIMATE_REGEN_COMBAT = 46
