--- @meta Alliance

--- @alias Alliance integer
--- | `ALLIANCE_ALDMERI_DOMINION` # 1
--- | `ALLIANCE_DAGGERFALL_COVENANT` # 3
--- | `ALLIANCE_EBONHEART_PACT` # 2
--- | `ALLIANCE_NONE` # 0

ALLIANCE_ALDMERI_DOMINION = 1
ALLIANCE_DAGGERFALL_COVENANT = 3
ALLIANCE_EBONHEART_PACT = 2
ALLIANCE_NONE = 0
