--- @meta AmbientOcclusionType

--- @alias AmbientOcclusionType integer
--- | `AMBIENT_OCCLUSION_TYPE_HBAO` # 2
--- | `AMBIENT_OCCLUSION_TYPE_LSAO` # 3
--- | `AMBIENT_OCCLUSION_TYPE_NONE` # 0
--- | `AMBIENT_OCCLUSION_TYPE_SSAO` # 1
--- | `AMBIENT_OCCLUSION_TYPE_SSGI` # 4

AMBIENT_OCCLUSION_TYPE_HBAO = 2
AMBIENT_OCCLUSION_TYPE_LSAO = 3
AMBIENT_OCCLUSION_TYPE_NONE = 0
AMBIENT_OCCLUSION_TYPE_SSAO = 1
AMBIENT_OCCLUSION_TYPE_SSGI = 4
