--- @meta AnimationPlayback

--- @alias AnimationPlayback integer
--- | `ANIMATION_PLAYBACK_INVALID` # -1
--- | `ANIMATION_PLAYBACK_LOOP` # 1
--- | `ANIMATION_PLAYBACK_ONE_SHOT` # 0
--- | `ANIMATION_PLAYBACK_PING_PONG` # 2

ANIMATION_PLAYBACK_INVALID = -1
ANIMATION_PLAYBACK_LOOP = 1
ANIMATION_PLAYBACK_ONE_SHOT = 0
ANIMATION_PLAYBACK_PING_PONG = 2
