--- @meta AntiAliasingType

--- @alias AntiAliasingType integer
--- | `ANTIALIASING_TYPE_DLSS` # 3
--- | `ANTIALIASING_TYPE_FXAA` # 1
--- | `ANTIALIASING_TYPE_NONE` # 0
--- | `ANTIALIASING_TYPE_NVAA` # 4
--- | `ANTIALIASING_TYPE_TAA` # 2

ANTIALIASING_TYPE_DLSS = 3
ANTIALIASING_TYPE_FXAA = 1
ANTIALIASING_TYPE_NONE = 0
ANTIALIASING_TYPE_NVAA = 4
ANTIALIASING_TYPE_TAA = 2
