--- @meta AntiquityFilter

--- @alias AntiquityFilter integer
--- | `ANTIQUITY_FILTER_SHOW_ALL` # 0
--- | `ANTIQUITY_FILTER_SHOW_COMPLETED` # 1
--- | `ANTIQUITY_FILTER_SHOW_IN_PROGRESS` # 2
--- | `ANTIQUITY_FILTER_SHOW_NOT_STARTED` # 3

ANTIQUITY_FILTER_SHOW_ALL = 0
ANTIQUITY_FILTER_SHOW_COMPLETED = 1
ANTIQUITY_FILTER_SHOW_IN_PROGRESS = 2
ANTIQUITY_FILTER_SHOW_NOT_STARTED = 3
