--- @meta AntiquityQuality

--- @alias AntiquityQuality integer
--- | `ANTIQUITY_QUALITY_BLUE` # 2
--- | `ANTIQUITY_QUALITY_GOLD` # 4
--- | `ANTIQUITY_QUALITY_GREEN` # 1
--- | `ANTIQUITY_QUALITY_ORANGE` # 5
--- | `ANTIQUITY_QUALITY_PURPLE` # 3
--- | `ANTIQUITY_QUALITY_WHITE` # 0

ANTIQUITY_QUALITY_BLUE = 2
ANTIQUITY_QUALITY_GOLD = 4
ANTIQUITY_QUALITY_GREEN = 1
ANTIQUITY_QUALITY_ORANGE = 5
ANTIQUITY_QUALITY_PURPLE = 3
ANTIQUITY_QUALITY_WHITE = 0
