--- @meta AntiquityAbandonResult

--- @alias AntiquityAbandonResult integer
--- | `ANTIQUITY_ABANDON_RESULT_NOT_IN_PROGRESS` # 1
--- | `ANTIQUITY_ABANDON_RESULT_SUCCESS` # 0

ANTIQUITY_ABANDON_RESULT_NOT_IN_PROGRESS = 1
ANTIQUITY_ABANDON_RESULT_SUCCESS = 0
