--- @meta AntiquityDifficulty

--- @alias AntiquityDifficulty integer
--- | `ANTIQUITY_DIFFICULTY_ADVANCED` # 3
--- | `ANTIQUITY_DIFFICULTY_INTERMEDIATE` # 2
--- | `ANTIQUITY_DIFFICULTY_MASTER` # 4
--- | `ANTIQUITY_DIFFICULTY_SIMPLE` # 1
--- | `ANTIQUITY_DIFFICULTY_TRIVIAL` # 0
--- | `ANTIQUITY_DIFFICULTY_ULTIMATE` # 5

ANTIQUITY_DIFFICULTY_ADVANCED = 3
ANTIQUITY_DIFFICULTY_INTERMEDIATE = 2
ANTIQUITY_DIFFICULTY_MASTER = 4
ANTIQUITY_DIFFICULTY_SIMPLE = 1
ANTIQUITY_DIFFICULTY_TRIVIAL = 0
ANTIQUITY_DIFFICULTY_ULTIMATE = 5
