--- @meta AntiquityDiggingColors

--- @alias AntiquityDiggingColors integer
--- | `ANTIQUITY_DIGGING_COLORS_DIG_POWER_END` # 3
--- | `ANTIQUITY_DIGGING_COLORS_DIG_POWER_START` # 2
--- | `ANTIQUITY_DIGGING_COLORS_STABILITY_END` # 1
--- | `ANTIQUITY_DIGGING_COLORS_STABILITY_START` # 0

ANTIQUITY_DIGGING_COLORS_DIG_POWER_END = 3
ANTIQUITY_DIGGING_COLORS_DIG_POWER_START = 2
ANTIQUITY_DIGGING_COLORS_STABILITY_END = 1
ANTIQUITY_DIGGING_COLORS_STABILITY_START = 0
