--- @meta AntiquityScryingResult

--- @alias AntiquityScryingResult integer
--- | `ANTIQUITY_SCRYING_RESULT_AWAITING_COMBINATION` # 5
--- | `ANTIQUITY_SCRYING_RESULT_FAILED_REQUIREMENT` # 13
--- | `ANTIQUITY_SCRYING_RESULT_INCORRECT_ZONE` # 8
--- | `ANTIQUITY_SCRYING_RESULT_INTERNAL_ERROR` # 6
--- | `ANTIQUITY_SCRYING_RESULT_INVALID_ANTIQUITY` # 7
--- | `ANTIQUITY_SCRYING_RESULT_IN_COMBAT` # 14
--- | `ANTIQUITY_SCRYING_RESULT_IS_USING_FURNITURE` # 15
--- | `ANTIQUITY_SCRYING_RESULT_LEAD_NOT_ACQUIRED` # 4
--- | `ANTIQUITY_SCRYING_RESULT_MAX_IN_PROGRESS_ANTIQUITIES` # 10
--- | `ANTIQUITY_SCRYING_RESULT_MAX_PROGRESS` # 1
--- | `ANTIQUITY_SCRYING_RESULT_NOT_ENOUGH_SKILL` # 2
--- | `ANTIQUITY_SCRYING_RESULT_NOT_REPEATABLE` # 3
--- | `ANTIQUITY_SCRYING_RESULT_NO_ADDITIONAL_PROGRESS` # 11
--- | `ANTIQUITY_SCRYING_RESULT_NO_PROGRESS` # 12
--- | `ANTIQUITY_SCRYING_RESULT_SCRYING_TOOL_LOCKED` # 9
--- | `ANTIQUITY_SCRYING_RESULT_SUCCESS` # 0

ANTIQUITY_SCRYING_RESULT_AWAITING_COMBINATION = 5
ANTIQUITY_SCRYING_RESULT_FAILED_REQUIREMENT = 13
ANTIQUITY_SCRYING_RESULT_INCORRECT_ZONE = 8
ANTIQUITY_SCRYING_RESULT_INTERNAL_ERROR = 6
ANTIQUITY_SCRYING_RESULT_INVALID_ANTIQUITY = 7
ANTIQUITY_SCRYING_RESULT_IN_COMBAT = 14
ANTIQUITY_SCRYING_RESULT_IS_USING_FURNITURE = 15
ANTIQUITY_SCRYING_RESULT_LEAD_NOT_ACQUIRED = 4
ANTIQUITY_SCRYING_RESULT_MAX_IN_PROGRESS_ANTIQUITIES = 10
ANTIQUITY_SCRYING_RESULT_MAX_PROGRESS = 1
ANTIQUITY_SCRYING_RESULT_NOT_ENOUGH_SKILL = 2
ANTIQUITY_SCRYING_RESULT_NOT_REPEATABLE = 3
ANTIQUITY_SCRYING_RESULT_NO_ADDITIONAL_PROGRESS = 11
ANTIQUITY_SCRYING_RESULT_NO_PROGRESS = 12
ANTIQUITY_SCRYING_RESULT_SCRYING_TOOL_LOCKED = 9
ANTIQUITY_SCRYING_RESULT_SUCCESS = 0
