--- @meta ApplyOutfitChangesResult

--- @alias ApplyOutfitChangesResult integer
--- | `APPLY_OUTFIT_CHANGES_RESULT_ALTERATION_UNAVAILABLE` # 2
--- | `APPLY_OUTFIT_CHANGES_RESULT_BLACKLISTED_COLLECTIBLES` # 5
--- | `APPLY_OUTFIT_CHANGES_RESULT_BLOCKED_COLLECTIBLES` # 6
--- | `APPLY_OUTFIT_CHANGES_RESULT_INSUFFICIENT_FUNDS` # 3
--- | `APPLY_OUTFIT_CHANGES_RESULT_INVALID_DATA` # 1
--- | `APPLY_OUTFIT_CHANGES_RESULT_SUCCESS` # 0
--- | `APPLY_OUTFIT_CHANGES_RESULT_UNOWNED_COLLECTIBLES` # 4
--- | `APPLY_OUTFIT_CHANGES_RESULT_UNUSABLE_BY_COMPANION` # 7

APPLY_OUTFIT_CHANGES_RESULT_ALTERATION_UNAVAILABLE = 2
APPLY_OUTFIT_CHANGES_RESULT_BLACKLISTED_COLLECTIBLES = 5
APPLY_OUTFIT_CHANGES_RESULT_BLOCKED_COLLECTIBLES = 6
APPLY_OUTFIT_CHANGES_RESULT_INSUFFICIENT_FUNDS = 3
APPLY_OUTFIT_CHANGES_RESULT_INVALID_DATA = 1
APPLY_OUTFIT_CHANGES_RESULT_SUCCESS = 0
APPLY_OUTFIT_CHANGES_RESULT_UNOWNED_COLLECTIBLES = 4
APPLY_OUTFIT_CHANGES_RESULT_UNUSABLE_BY_COMPANION = 7
