--- @meta ApprovedURLType

--- @alias ApprovedURLType integer
--- | `APPROVED_URL_ESO_ACCOUNT` # 1
--- | `APPROVED_URL_ESO_ACCOUNT_LINKING` # 6
--- | `APPROVED_URL_ESO_ACCOUNT_STORE` # 2
--- | `APPROVED_URL_ESO_ACCOUNT_SUBSCRIPTION` # 3
--- | `APPROVED_URL_ESO_FORUMS` # 5
--- | `APPROVED_URL_ESO_HELP` # 4
--- | `APPROVED_URL_ESO_HOMEPAGE` # 0

APPROVED_URL_ESO_ACCOUNT = 1
APPROVED_URL_ESO_ACCOUNT_LINKING = 6
APPROVED_URL_ESO_ACCOUNT_STORE = 2
APPROVED_URL_ESO_ACCOUNT_SUBSCRIPTION = 3
APPROVED_URL_ESO_FORUMS = 5
APPROVED_URL_ESO_HELP = 4
APPROVED_URL_ESO_HOMEPAGE = 0
