--- @meta ArmoryBuildRestoreResult

--- @alias ArmoryBuildRestoreResult integer
--- | `ARMORY_BUILD_RESTORE_RESULT_BAD_INDEX` # 3
--- | `ARMORY_BUILD_RESTORE_RESULT_BUSY` # 2
--- | `ARMORY_BUILD_RESTORE_RESULT_COOLDOWN` # 4
--- | `ARMORY_BUILD_RESTORE_RESULT_EFFECT_COUNT_LIMIT` # 11
--- | `ARMORY_BUILD_RESTORE_RESULT_INVALID_PLAYER_STATE` # 5
--- | `ARMORY_BUILD_RESTORE_RESULT_IN_COMBAT` # 10
--- | `ARMORY_BUILD_RESTORE_RESULT_IN_WEREWOLF_FORM` # 9
--- | `ARMORY_BUILD_RESTORE_RESULT_NO_GEAR_SPACE` # 7
--- | `ARMORY_BUILD_RESTORE_RESULT_NO_INTERACTION` # 12
--- | `ARMORY_BUILD_RESTORE_RESULT_REMOVE_GEAR_FAILURE` # 8
--- | `ARMORY_BUILD_RESTORE_RESULT_RESTORE_FAILED` # 1
--- | `ARMORY_BUILD_RESTORE_RESULT_SPECIAL_HOTBAR_ACTIVE` # 13
--- | `ARMORY_BUILD_RESTORE_RESULT_SUCCESS` # 0
--- | `ARMORY_BUILD_RESTORE_RESULT_TIMEOUT` # 6

ARMORY_BUILD_RESTORE_RESULT_BAD_INDEX = 3
ARMORY_BUILD_RESTORE_RESULT_BUSY = 2
ARMORY_BUILD_RESTORE_RESULT_COOLDOWN = 4
ARMORY_BUILD_RESTORE_RESULT_EFFECT_COUNT_LIMIT = 11
ARMORY_BUILD_RESTORE_RESULT_INVALID_PLAYER_STATE = 5
ARMORY_BUILD_RESTORE_RESULT_IN_COMBAT = 10
ARMORY_BUILD_RESTORE_RESULT_IN_WEREWOLF_FORM = 9
ARMORY_BUILD_RESTORE_RESULT_NO_GEAR_SPACE = 7
ARMORY_BUILD_RESTORE_RESULT_NO_INTERACTION = 12
ARMORY_BUILD_RESTORE_RESULT_REMOVE_GEAR_FAILURE = 8
ARMORY_BUILD_RESTORE_RESULT_RESTORE_FAILED = 1
ARMORY_BUILD_RESTORE_RESULT_SPECIAL_HOTBAR_ACTIVE = 13
ARMORY_BUILD_RESTORE_RESULT_SUCCESS = 0
ARMORY_BUILD_RESTORE_RESULT_TIMEOUT = 6
