--- @meta ArmoryBuildEquipSlotState

--- @alias ArmoryBuildEquipSlotState integer
--- | `ARMORY_BUILD_EQUIP_SLOT_STATE_EMPTY` # 0
--- | `ARMORY_BUILD_EQUIP_SLOT_STATE_INACCESSIBLE` # 3
--- | `ARMORY_BUILD_EQUIP_SLOT_STATE_MISSING` # 1
--- | `ARMORY_BUILD_EQUIP_SLOT_STATE_VALID` # 2

ARMORY_BUILD_EQUIP_SLOT_STATE_EMPTY = 0
ARMORY_BUILD_EQUIP_SLOT_STATE_INACCESSIBLE = 3
ARMORY_BUILD_EQUIP_SLOT_STATE_MISSING = 1
ARMORY_BUILD_EQUIP_SLOT_STATE_VALID = 2
