--- @meta ArmoryBuildOperationType

--- @alias ArmoryBuildOperationType integer
--- | `ARMORY_BUILD_OPERATION_TYPE_NONE` # 0
--- | `ARMORY_BUILD_OPERATION_TYPE_RESTORE` # 2
--- | `ARMORY_BUILD_OPERATION_TYPE_SAVE` # 1

ARMORY_BUILD_OPERATION_TYPE_NONE = 0
ARMORY_BUILD_OPERATION_TYPE_RESTORE = 2
ARMORY_BUILD_OPERATION_TYPE_SAVE = 1
