--- @meta ArmoryBuildSaveResult

--- @alias ArmoryBuildSaveResult integer
--- | `ARMORY_BUILD_SAVE_RESULT_BAD_INDEX` # 3
--- | `ARMORY_BUILD_SAVE_RESULT_BUSY` # 2
--- | `ARMORY_BUILD_SAVE_RESULT_COOLDOWN` # 4
--- | `ARMORY_BUILD_SAVE_RESULT_EFFECT_COUNT_LIMIT` # 9
--- | `ARMORY_BUILD_SAVE_RESULT_INVALID_PLAYER_STATE` # 5
--- | `ARMORY_BUILD_SAVE_RESULT_IN_COMBAT` # 8
--- | `ARMORY_BUILD_SAVE_RESULT_IN_WEREWOLF_FORM` # 7
--- | `ARMORY_BUILD_SAVE_RESULT_NO_INTERACTION` # 10
--- | `ARMORY_BUILD_SAVE_RESULT_SAVE_FAILED` # 1
--- | `ARMORY_BUILD_SAVE_RESULT_SPECIAL_HOTBAR_ACTIVE` # 11
--- | `ARMORY_BUILD_SAVE_RESULT_SUCCESS` # 0
--- | `ARMORY_BUILD_SAVE_RESULT_TIMEOUT` # 6

ARMORY_BUILD_SAVE_RESULT_BAD_INDEX = 3
ARMORY_BUILD_SAVE_RESULT_BUSY = 2
ARMORY_BUILD_SAVE_RESULT_COOLDOWN = 4
ARMORY_BUILD_SAVE_RESULT_EFFECT_COUNT_LIMIT = 9
ARMORY_BUILD_SAVE_RESULT_INVALID_PLAYER_STATE = 5
ARMORY_BUILD_SAVE_RESULT_IN_COMBAT = 8
ARMORY_BUILD_SAVE_RESULT_IN_WEREWOLF_FORM = 7
ARMORY_BUILD_SAVE_RESULT_NO_INTERACTION = 10
ARMORY_BUILD_SAVE_RESULT_SAVE_FAILED = 1
ARMORY_BUILD_SAVE_RESULT_SPECIAL_HOTBAR_ACTIVE = 11
ARMORY_BUILD_SAVE_RESULT_SUCCESS = 0
ARMORY_BUILD_SAVE_RESULT_TIMEOUT = 6
