--- @meta AttributeTooltipColors

--- @alias AttributeTooltipColors integer
--- | `ATTRIBUTE_TOOLTIP_COLOR_CURRENT_VALUE` # 1
--- | `ATTRIBUTE_TOOLTIP_COLOR_EFFECT` # 2
--- | `ATTRIBUTE_TOOLTIP_COLOR_NAME` # 0

ATTRIBUTE_TOOLTIP_COLOR_CURRENT_VALUE = 1
ATTRIBUTE_TOOLTIP_COLOR_EFFECT = 2
ATTRIBUTE_TOOLTIP_COLOR_NAME = 0
