--- @meta AttributePointAllocationMode

--- @alias AttributePointAllocationMode integer
--- | `ATTRIBUTE_POINT_ALLOCATION_MODE_FULL` # 1
--- | `ATTRIBUTE_POINT_ALLOCATION_MODE_PURCHASE_ONLY` # 0

ATTRIBUTE_POINT_ALLOCATION_MODE_FULL = 1
ATTRIBUTE_POINT_ALLOCATION_MODE_PURCHASE_ONLY = 0
