--- @meta AudioSpeakerConfigurations

--- @alias AudioSpeakerConfigurations integer
--- | `AUDIO_SPEAKER_CONFIG_FIVE_POINT_ONE` # 7
--- | `AUDIO_SPEAKER_CONFIG_FIVE_POINT_ZERO` # 6
--- | `AUDIO_SPEAKER_CONFIG_FOUR_POINT_ONE` # 5
--- | `AUDIO_SPEAKER_CONFIG_FOUR_POINT_ZERO` # 4
--- | `AUDIO_SPEAKER_CONFIG_MONO` # 1
--- | `AUDIO_SPEAKER_CONFIG_SEVEN_POINT_ONE` # 8
--- | `AUDIO_SPEAKER_CONFIG_STEREO` # 2
--- | `AUDIO_SPEAKER_CONFIG_TWO_POINT_ONE` # 3
--- | `AUDIO_SPEAKER_CONFIG_USE_WINDOWS_SETTING` # 0

AUDIO_SPEAKER_CONFIG_FIVE_POINT_ONE = 7
AUDIO_SPEAKER_CONFIG_FIVE_POINT_ZERO = 6
AUDIO_SPEAKER_CONFIG_FOUR_POINT_ONE = 5
AUDIO_SPEAKER_CONFIG_FOUR_POINT_ZERO = 4
AUDIO_SPEAKER_CONFIG_MONO = 1
AUDIO_SPEAKER_CONFIG_SEVEN_POINT_ONE = 8
AUDIO_SPEAKER_CONFIG_STEREO = 2
AUDIO_SPEAKER_CONFIG_TWO_POINT_ONE = 3
AUDIO_SPEAKER_CONFIG_USE_WINDOWS_SETTING = 0
