--- @meta AudioSetting

--- @alias AudioSetting integer
--- | `AUDIO_SETTING_AMBIENT_ENABLED` # 6
--- | `AUDIO_SETTING_AMBIENT_VOLUME` # 7
--- | `AUDIO_SETTING_AUDIO_ENABLED` # 0
--- | `AUDIO_SETTING_AUDIO_VOLUME` # 1
--- | `AUDIO_SETTING_BACKGROUND_AUDIO` # 12
--- | `AUDIO_SETTING_COMBAT_MUSIC_MODE` # 20
--- | `AUDIO_SETTING_FOOTSTEPS_ENABLED` # 14
--- | `AUDIO_SETTING_FOOTSTEPS_VOLUME` # 15
--- | `AUDIO_SETTING_INTRO_MUSIC` # 21
--- | `AUDIO_SETTING_MUSIC_ENABLED` # 2
--- | `AUDIO_SETTING_MUSIC_VOLUME` # 3
--- | `AUDIO_SETTING_SFX_ENABLED` # 4
--- | `AUDIO_SETTING_SFX_VOLUME` # 5
--- | `AUDIO_SETTING_SOUND_ENABLED` # 16
--- | `AUDIO_SETTING_SPEAKER_SETUP` # 13
--- | `AUDIO_SETTING_UI_ENABLED` # 8
--- | `AUDIO_SETTING_UI_VOLUME` # 9
--- | `AUDIO_SETTING_VIDEO_ENABLED` # 18
--- | `AUDIO_SETTING_VIDEO_VOLUME` # 19
--- | `AUDIO_SETTING_VOICE_CHAT_VOLUME` # 17
--- | `AUDIO_SETTING_VO_ENABLED` # 10
--- | `AUDIO_SETTING_VO_VOLUME` # 11

AUDIO_SETTING_AMBIENT_ENABLED = 6
AUDIO_SETTING_AMBIENT_VOLUME = 7
AUDIO_SETTING_AUDIO_ENABLED = 0
AUDIO_SETTING_AUDIO_VOLUME = 1
AUDIO_SETTING_BACKGROUND_AUDIO = 12
AUDIO_SETTING_COMBAT_MUSIC_MODE = 20
AUDIO_SETTING_FOOTSTEPS_ENABLED = 14
AUDIO_SETTING_FOOTSTEPS_VOLUME = 15
AUDIO_SETTING_INTRO_MUSIC = 21
AUDIO_SETTING_MUSIC_ENABLED = 2
AUDIO_SETTING_MUSIC_VOLUME = 3
AUDIO_SETTING_SFX_ENABLED = 4
AUDIO_SETTING_SFX_VOLUME = 5
AUDIO_SETTING_SOUND_ENABLED = 16
AUDIO_SETTING_SPEAKER_SETUP = 13
AUDIO_SETTING_UI_ENABLED = 8
AUDIO_SETTING_UI_VOLUME = 9
AUDIO_SETTING_VIDEO_ENABLED = 18
AUDIO_SETTING_VIDEO_VOLUME = 19
AUDIO_SETTING_VOICE_CHAT_VOLUME = 17
AUDIO_SETTING_VO_ENABLED = 10
AUDIO_SETTING_VO_VOLUME = 11
