--- @meta AvANotificationsSettingChoice

--- @alias AvANotificationsSettingChoice integer
--- | `AVA_NOTIFICATIONS_SETTING_CHOICE_ALWAYS_SHOW` # 1
--- | `AVA_NOTIFICATIONS_SETTING_CHOICE_AUTOMATIC` # 2
--- | `AVA_NOTIFICATIONS_SETTING_CHOICE_DONT_SHOW` # 0

AVA_NOTIFICATIONS_SETTING_CHOICE_ALWAYS_SHOW = 1
AVA_NOTIFICATIONS_SETTING_CHOICE_AUTOMATIC = 2
AVA_NOTIFICATIONS_SETTING_CHOICE_DONT_SHOW = 0
