--- @meta BackgroundListFilterType

--- @alias BackgroundListFilterType integer
--- | `BACKGROUND_LIST_FILTER_TYPE_ACHIEVEMENT` # 9
--- | `BACKGROUND_LIST_FILTER_TYPE_DESCRIPTION` # 2
--- | `BACKGROUND_LIST_FILTER_TYPE_FURNITURE_KEYWORDS` # 4
--- | `BACKGROUND_LIST_FILTER_TYPE_HINT` # 6
--- | `BACKGROUND_LIST_FILTER_TYPE_HUE_CATEGORY` # 8
--- | `BACKGROUND_LIST_FILTER_TYPE_ITEM_TAGS` # 5
--- | `BACKGROUND_LIST_FILTER_TYPE_NAME` # 1
--- | `BACKGROUND_LIST_FILTER_TYPE_RARITY` # 7
--- | `BACKGROUND_LIST_FILTER_TYPE_SEARCH_KEYWORDS` # 3

BACKGROUND_LIST_FILTER_TYPE_ACHIEVEMENT = 9
BACKGROUND_LIST_FILTER_TYPE_DESCRIPTION = 2
BACKGROUND_LIST_FILTER_TYPE_FURNITURE_KEYWORDS = 4
BACKGROUND_LIST_FILTER_TYPE_HINT = 6
BACKGROUND_LIST_FILTER_TYPE_HUE_CATEGORY = 8
BACKGROUND_LIST_FILTER_TYPE_ITEM_TAGS = 5
BACKGROUND_LIST_FILTER_TYPE_NAME = 1
BACKGROUND_LIST_FILTER_TYPE_RARITY = 7
BACKGROUND_LIST_FILTER_TYPE_SEARCH_KEYWORDS = 3
