--- @meta BackgroundListFilterTarget

--- @alias BackgroundListFilterTarget integer
--- | `BACKGROUND_LIST_FILTER_TARGET_ACHIEVEMENT_ID` # 6
--- | `BACKGROUND_LIST_FILTER_TARGET_ANTIQUITY_ID` # 9
--- | `BACKGROUND_LIST_FILTER_TARGET_BAG_SLOT` # 1
--- | `BACKGROUND_LIST_FILTER_TARGET_COLLECTIBLE_ID` # 2
--- | `BACKGROUND_LIST_FILTER_TARGET_CRAFTED_ABILITY_COMBINATION` # 14
--- | `BACKGROUND_LIST_FILTER_TARGET_CRAFTED_ABILITY_ID` # 13
--- | `BACKGROUND_LIST_FILTER_TARGET_CRAFTED_ABILITY_SCRIPT_ID` # 15
--- | `BACKGROUND_LIST_FILTER_TARGET_DYE_ID` # 8
--- | `BACKGROUND_LIST_FILTER_TARGET_FURNITURE_ID` # 4
--- | `BACKGROUND_LIST_FILTER_TARGET_HELP_ID` # 7
--- | `BACKGROUND_LIST_FILTER_TARGET_ITEM_SET_ID` # 10
--- | `BACKGROUND_LIST_FILTER_TARGET_MARKET_PRODUCT_ID` # 3
--- | `BACKGROUND_LIST_FILTER_TARGET_MARKET_PRODUCT_ID_BREADTH` # 5
--- | `BACKGROUND_LIST_FILTER_TARGET_QUEST_ITEM_ID` # 11
--- | `BACKGROUND_LIST_FILTER_TARGET_TRIBUTE_PATRON_ID` # 12

BACKGROUND_LIST_FILTER_TARGET_ACHIEVEMENT_ID = 6
BACKGROUND_LIST_FILTER_TARGET_ANTIQUITY_ID = 9
BACKGROUND_LIST_FILTER_TARGET_BAG_SLOT = 1
BACKGROUND_LIST_FILTER_TARGET_COLLECTIBLE_ID = 2
BACKGROUND_LIST_FILTER_TARGET_CRAFTED_ABILITY_COMBINATION = 14
BACKGROUND_LIST_FILTER_TARGET_CRAFTED_ABILITY_ID = 13
BACKGROUND_LIST_FILTER_TARGET_CRAFTED_ABILITY_SCRIPT_ID = 15
BACKGROUND_LIST_FILTER_TARGET_DYE_ID = 8
BACKGROUND_LIST_FILTER_TARGET_FURNITURE_ID = 4
BACKGROUND_LIST_FILTER_TARGET_HELP_ID = 7
BACKGROUND_LIST_FILTER_TARGET_ITEM_SET_ID = 10
BACKGROUND_LIST_FILTER_TARGET_MARKET_PRODUCT_ID = 3
BACKGROUND_LIST_FILTER_TARGET_MARKET_PRODUCT_ID_BREADTH = 5
BACKGROUND_LIST_FILTER_TARGET_QUEST_ITEM_ID = 11
BACKGROUND_LIST_FILTER_TARGET_TRIBUTE_PATRON_ID = 12
