--- @meta Bag

--- @alias Bag integer
--- | `BAG_BACKPACK` # 1
--- | `BAG_BANK` # 2
--- | `BAG_BUYBACK` # 4
--- | `BAG_COMPANION_WORN` # 17
--- | `BAG_GUILDBANK` # 3
--- | `BAG_HOUSE_BANK_EIGHT` # 14
--- | `BAG_HOUSE_BANK_FIVE` # 11
--- | `BAG_HOUSE_BANK_FOUR` # 10
--- | `BAG_HOUSE_BANK_NINE` # 15
--- | `BAG_HOUSE_BANK_ONE` # 7
--- | `BAG_HOUSE_BANK_SEVEN` # 13
--- | `BAG_HOUSE_BANK_SIX` # 12
--- | `BAG_HOUSE_BANK_TEN` # 16
--- | `BAG_HOUSE_BANK_THREE` # 9
--- | `BAG_HOUSE_BANK_TWO` # 8
--- | `BAG_SUBSCRIBER_BANK` # 6
--- | `BAG_VIRTUAL` # 5
--- | `BAG_WORN` # 0

BAG_BACKPACK = 1
BAG_BANK = 2
BAG_BUYBACK = 4
BAG_COMPANION_WORN = 17
BAG_GUILDBANK = 3
BAG_HOUSE_BANK_EIGHT = 14
BAG_HOUSE_BANK_FIVE = 11
BAG_HOUSE_BANK_FOUR = 10
BAG_HOUSE_BANK_NINE = 15
BAG_HOUSE_BANK_ONE = 7
BAG_HOUSE_BANK_SEVEN = 13
BAG_HOUSE_BANK_SIX = 12
BAG_HOUSE_BANK_TEN = 16
BAG_HOUSE_BANK_THREE = 9
BAG_HOUSE_BANK_TWO = 8
BAG_SUBSCRIBER_BANK = 6
BAG_VIRTUAL = 5
BAG_WORN = 0
