--- @meta BattlegroundQueryContextType

--- @alias BattlegroundQueryContextType integer
--- | `BGQUERY_ASSIGNED_AND_LOCAL` # 3
--- | `BGQUERY_ASSIGNED_CAMPAIGN` # 2
--- | `BGQUERY_LOCAL` # 1
--- | `BGQUERY_UNKNOWN` # 0

BGQUERY_ASSIGNED_AND_LOCAL = 3
BGQUERY_ASSIGNED_CAMPAIGN = 2
BGQUERY_LOCAL = 1
BGQUERY_UNKNOWN = 0
