--- @meta BattlegroundKillType

--- @alias BattlegroundKillType integer
--- | `BATTLEGROUND_KILL_TYPE_ASSIST` # 1
--- | `BATTLEGROUND_KILL_TYPE_KILLED_BY_ENEMY_TEAM` # 4
--- | `BATTLEGROUND_KILL_TYPE_KILLED_BY_MY_TEAM` # 2
--- | `BATTLEGROUND_KILL_TYPE_KILLING_BLOW` # 0
--- | `BATTLEGROUND_KILL_TYPE_STOLEN_BY_ENEMY_TEAM` # 3

BATTLEGROUND_KILL_TYPE_ASSIST = 1
BATTLEGROUND_KILL_TYPE_KILLED_BY_ENEMY_TEAM = 4
BATTLEGROUND_KILL_TYPE_KILLED_BY_MY_TEAM = 2
BATTLEGROUND_KILL_TYPE_KILLING_BLOW = 0
BATTLEGROUND_KILL_TYPE_STOLEN_BY_ENEMY_TEAM = 3
