--- @meta BattlegroundGameType

--- @alias BattlegroundGameType integer
--- | `BATTLEGROUND_GAME_TYPE_CAPTURE_THE_FLAG` # 1
--- | `BATTLEGROUND_GAME_TYPE_CRAZY_KING` # 5
--- | `BATTLEGROUND_GAME_TYPE_DEATHMATCH` # 2
--- | `BATTLEGROUND_GAME_TYPE_DOMINATION` # 4
--- | `BATTLEGROUND_GAME_TYPE_KING_OF_THE_HILL` # 3
--- | `BATTLEGROUND_GAME_TYPE_MURDERBALL` # 6
--- | `BATTLEGROUND_GAME_TYPE_NONE` # 0

BATTLEGROUND_GAME_TYPE_CAPTURE_THE_FLAG = 1
BATTLEGROUND_GAME_TYPE_CRAZY_KING = 5
BATTLEGROUND_GAME_TYPE_DEATHMATCH = 2
BATTLEGROUND_GAME_TYPE_DOMINATION = 4
BATTLEGROUND_GAME_TYPE_KING_OF_THE_HILL = 3
BATTLEGROUND_GAME_TYPE_MURDERBALL = 6
BATTLEGROUND_GAME_TYPE_NONE = 0
