--- @meta BattlegroundState

--- @alias BattlegroundState integer
--- | `BATTLEGROUND_STATE_FINISHED` # 5
--- | `BATTLEGROUND_STATE_NONE` # 0
--- | `BATTLEGROUND_STATE_POSTGAME` # 4
--- | `BATTLEGROUND_STATE_PREGAME` # 1
--- | `BATTLEGROUND_STATE_RUNNING` # 3
--- | `BATTLEGROUND_STATE_STARTING` # 2

BATTLEGROUND_STATE_FINISHED = 5
BATTLEGROUND_STATE_NONE = 0
BATTLEGROUND_STATE_POSTGAME = 4
BATTLEGROUND_STATE_PREGAME = 1
BATTLEGROUND_STATE_RUNNING = 3
BATTLEGROUND_STATE_STARTING = 2
