--- @meta BattlegroundTeam

--- @alias BattlegroundTeam integer
--- | `BATTLEGROUND_TEAM_FIRE_DRAKES` # 1
--- | `BATTLEGROUND_TEAM_INVALID` # 0
--- | `BATTLEGROUND_TEAM_PIT_DAEMONS` # 2
--- | `BATTLEGROUND_TEAM_STORM_LORDS` # 3

BATTLEGROUND_TEAM_FIRE_DRAKES = 1
BATTLEGROUND_TEAM_INVALID = 0
BATTLEGROUND_TEAM_PIT_DAEMONS = 2
BATTLEGROUND_TEAM_STORM_LORDS = 3
