--- @meta BattlegroundLeaderboardType

--- @alias BattlegroundLeaderboardType integer
--- | `BATTLEGROUND_LEADERBOARD_TYPE_DEATHMATCH` # 1
--- | `BATTLEGROUND_LEADERBOARD_TYPE_FLAG_GAMES` # 3
--- | `BATTLEGROUND_LEADERBOARD_TYPE_LAND_GRAB` # 2
--- | `BATTLEGROUND_LEADERBOARD_TYPE_NONE` # 0

BATTLEGROUND_LEADERBOARD_TYPE_DEATHMATCH = 1
BATTLEGROUND_LEADERBOARD_TYPE_FLAG_GAMES = 3
BATTLEGROUND_LEADERBOARD_TYPE_LAND_GRAB = 2
BATTLEGROUND_LEADERBOARD_TYPE_NONE = 0
