--- @meta BlockState

--- @alias BlockState integer
--- | `BLOCK_STATE_ACTIVE` # 2
--- | `BLOCK_STATE_BLOCKED` # 4
--- | `BLOCK_STATE_CLIENT_REQUESTED` # 6
--- | `BLOCK_STATE_DRAINED` # 3
--- | `BLOCK_STATE_IDLE` # 1
--- | `BLOCK_STATE_NONE` # 0
--- | `BLOCK_STATE_OVERRIDDEN` # 5

BLOCK_STATE_ACTIVE = 2
BLOCK_STATE_BLOCKED = 4
BLOCK_STATE_CLIENT_REQUESTED = 6
BLOCK_STATE_DRAINED = 3
BLOCK_STATE_IDLE = 1
BLOCK_STATE_NONE = 0
BLOCK_STATE_OVERRIDDEN = 5
