--- @meta BookMedium

--- @alias BookMedium integer
--- | `BOOK_MEDIUM_ANIMAL_SKIN` # 2
--- | `BOOK_MEDIUM_ELVEN_SCROLL` # 10
--- | `BOOK_MEDIUM_LETTER` # 4
--- | `BOOK_MEDIUM_METAL` # 8
--- | `BOOK_MEDIUM_METAL_TABLET` # 9
--- | `BOOK_MEDIUM_NONE` # 0
--- | `BOOK_MEDIUM_NOTE` # 5
--- | `BOOK_MEDIUM_RUBBING_PAPER` # 3
--- | `BOOK_MEDIUM_SCROLL` # 6
--- | `BOOK_MEDIUM_STONE_TABLET` # 7
--- | `BOOK_MEDIUM_YELLOWED_PAPER` # 1

BOOK_MEDIUM_ANIMAL_SKIN = 2
BOOK_MEDIUM_ELVEN_SCROLL = 10
BOOK_MEDIUM_LETTER = 4
BOOK_MEDIUM_METAL = 8
BOOK_MEDIUM_METAL_TABLET = 9
BOOK_MEDIUM_NONE = 0
BOOK_MEDIUM_NOTE = 5
BOOK_MEDIUM_RUBBING_PAPER = 3
BOOK_MEDIUM_SCROLL = 6
BOOK_MEDIUM_STONE_TABLET = 7
BOOK_MEDIUM_YELLOWED_PAPER = 1
