--- @meta BossRank

--- @alias BossRank integer
--- | `BOSS_RANK_EXTRA` # 8
--- | `BOSS_RANK_FIVE` # 5
--- | `BOSS_RANK_FOUR` # 4
--- | `BOSS_RANK_NOT_A_BOSS` # 0
--- | `BOSS_RANK_ONE` # 1
--- | `BOSS_RANK_SEVEN` # 7
--- | `BOSS_RANK_SIX` # 6
--- | `BOSS_RANK_THREE` # 3
--- | `BOSS_RANK_TWO` # 2

BOSS_RANK_EXTRA = 8
BOSS_RANK_FIVE = 5
BOSS_RANK_FOUR = 4
BOSS_RANK_NOT_A_BOSS = 0
BOSS_RANK_ONE = 1
BOSS_RANK_SEVEN = 7
BOSS_RANK_SIX = 6
BOSS_RANK_THREE = 3
BOSS_RANK_TWO = 2
