--- @meta BotCurrentlySearchingForGroupStatus

--- @alias BotCurrentlySearchingForGroupStatus integer
--- | `BOT_CURRENTLY_SEARCHING_FOR_GROUP_STATUS_AWAITING_QUEUE_RESPONSE` # 2
--- | `BOT_CURRENTLY_SEARCHING_FOR_GROUP_STATUS_NOT_SEARCHING` # 0
--- | `BOT_CURRENTLY_SEARCHING_FOR_GROUP_STATUS_SEARCHING` # 1

BOT_CURRENTLY_SEARCHING_FOR_GROUP_STATUS_AWAITING_QUEUE_RESPONSE = 2
BOT_CURRENTLY_SEARCHING_FOR_GROUP_STATUS_NOT_SEARCHING = 0
BOT_CURRENTLY_SEARCHING_FOR_GROUP_STATUS_SEARCHING = 1
