--- @meta BuffTypeCategory

--- @alias BuffTypeCategory integer
--- | `BUFF_TYPE_CATEGORY_ANY_BUFF` # 4
--- | `BUFF_TYPE_CATEGORY_ANY_DEBUFF` # 8
--- | `BUFF_TYPE_CATEGORY_ANY_MAJOR_BUFF_OR_DEBUFF` # 9
--- | `BUFF_TYPE_CATEGORY_ANY_MINOR_BUFF_OR_DEBUFF` # 10
--- | `BUFF_TYPE_CATEGORY_MAJOR_BUFF` # 3
--- | `BUFF_TYPE_CATEGORY_MAJOR_DEBUFF` # 7
--- | `BUFF_TYPE_CATEGORY_MINOR_BUFF` # 2
--- | `BUFF_TYPE_CATEGORY_MINOR_DEBUFF` # 6
--- | `BUFF_TYPE_CATEGORY_NONE` # 0
--- | `BUFF_TYPE_CATEGORY_NO_BUFF` # 1
--- | `BUFF_TYPE_CATEGORY_NO_DEBUFF` # 5

BUFF_TYPE_CATEGORY_ANY_BUFF = 4
BUFF_TYPE_CATEGORY_ANY_DEBUFF = 8
BUFF_TYPE_CATEGORY_ANY_MAJOR_BUFF_OR_DEBUFF = 9
BUFF_TYPE_CATEGORY_ANY_MINOR_BUFF_OR_DEBUFF = 10
BUFF_TYPE_CATEGORY_MAJOR_BUFF = 3
BUFF_TYPE_CATEGORY_MAJOR_DEBUFF = 7
BUFF_TYPE_CATEGORY_MINOR_BUFF = 2
BUFF_TYPE_CATEGORY_MINOR_DEBUFF = 6
BUFF_TYPE_CATEGORY_NONE = 0
BUFF_TYPE_CATEGORY_NO_BUFF = 1
BUFF_TYPE_CATEGORY_NO_DEBUFF = 5
