--- @meta BuffDebuffEnabledChoice

--- @alias BuffDebuffEnabledChoice integer
--- | `BUFF_DEBUFF_ENABLED_CHOICE_ALWAYS_SHOW` # 1
--- | `BUFF_DEBUFF_ENABLED_CHOICE_AUTOMATIC` # 2
--- | `BUFF_DEBUFF_ENABLED_CHOICE_DONT_SHOW` # 0

BUFF_DEBUFF_ENABLED_CHOICE_ALWAYS_SHOW = 1
BUFF_DEBUFF_ENABLED_CHOICE_AUTOMATIC = 2
BUFF_DEBUFF_ENABLED_CHOICE_DONT_SHOW = 0
