--- @meta BuffType

--- @alias BuffType integer
--- | `BUFF_TYPE_DEPRECATED_INCREASE_ULT_COST` # 59
--- | `BUFF_TYPE_EMPOWER` # 37
--- | `BUFF_TYPE_MAJOR_AEGIS` # 52
--- | `BUFF_TYPE_MAJOR_BERSERK` # 43
--- | `BUFF_TYPE_MAJOR_BREACH` # 41
--- | `BUFF_TYPE_MAJOR_BRITTLE` # 12
--- | `BUFF_TYPE_MAJOR_BRUTALITY` # 2
--- | `BUFF_TYPE_MAJOR_COURAGE` # 49
--- | `BUFF_TYPE_MAJOR_COWARDICE` # 39
--- | `BUFF_TYPE_MAJOR_DEFILE` # 32
--- | `BUFF_TYPE_MAJOR_ENDURANCE` # 16
--- | `BUFF_TYPE_MAJOR_EVASION` # 26
--- | `BUFF_TYPE_MAJOR_EXPEDITION` # 36
--- | `BUFF_TYPE_MAJOR_FORCE` # 45
--- | `BUFF_TYPE_MAJOR_FORTITUDE` # 14
--- | `BUFF_TYPE_MAJOR_GALLOP` # 54
--- | `BUFF_TYPE_MAJOR_HEROISM` # 20
--- | `BUFF_TYPE_MAJOR_INTELLECT` # 18
--- | `BUFF_TYPE_MAJOR_MAIM` # 30
--- | `BUFF_TYPE_MAJOR_MANGLE` # 34
--- | `BUFF_TYPE_MAJOR_MENDING` # 22
--- | `BUFF_TYPE_MAJOR_PROPHECY` # 8
--- | `BUFF_TYPE_MAJOR_PROTECTION` # 28
--- | `BUFF_TYPE_MAJOR_RESOLVE` # 10
--- | `BUFF_TYPE_MAJOR_SAVAGERY` # 4
--- | `BUFF_TYPE_MAJOR_SLAYER` # 47
--- | `BUFF_TYPE_MAJOR_SORCERY` # 6
--- | `BUFF_TYPE_MAJOR_TIMIDITY` # 63
--- | `BUFF_TYPE_MAJOR_VITALITY` # 24
--- | `BUFF_TYPE_MAJOR_VULNERABILITY` # 61
--- | `BUFF_TYPE_MINOR_AEGIS` # 51
--- | `BUFF_TYPE_MINOR_BERSERK` # 42
--- | `BUFF_TYPE_MINOR_BREACH` # 40
--- | `BUFF_TYPE_MINOR_BRITTLE` # 11
--- | `BUFF_TYPE_MINOR_BRUTALITY` # 1
--- | `BUFF_TYPE_MINOR_COURAGE` # 48
--- | `BUFF_TYPE_MINOR_COWARDICE` # 38
--- | `BUFF_TYPE_MINOR_DEFILE` # 31
--- | `BUFF_TYPE_MINOR_ENDURANCE` # 15
--- | `BUFF_TYPE_MINOR_ENERVATION` # 55
--- | `BUFF_TYPE_MINOR_EVASION` # 25
--- | `BUFF_TYPE_MINOR_EXPEDITION` # 35
--- | `BUFF_TYPE_MINOR_FORCE` # 44
--- | `BUFF_TYPE_MINOR_FORTITUDE` # 13
--- | `BUFF_TYPE_MINOR_GALLOP` # 53
--- | `BUFF_TYPE_MINOR_HEROISM` # 19
--- | `BUFF_TYPE_MINOR_INTELLECT` # 17
--- | `BUFF_TYPE_MINOR_LIFESTEAL` # 57
--- | `BUFF_TYPE_MINOR_MAGICKASTEAL` # 58
--- | `BUFF_TYPE_MINOR_MAIM` # 29
--- | `BUFF_TYPE_MINOR_MANGLE` # 33
--- | `BUFF_TYPE_MINOR_MENDING` # 21
--- | `BUFF_TYPE_MINOR_PROPHECY` # 7
--- | `BUFF_TYPE_MINOR_PROTECTION` # 27
--- | `BUFF_TYPE_MINOR_RESOLVE` # 9
--- | `BUFF_TYPE_MINOR_SAVAGERY` # 3
--- | `BUFF_TYPE_MINOR_SLAYER` # 46
--- | `BUFF_TYPE_MINOR_SORCERY` # 5
--- | `BUFF_TYPE_MINOR_TIMIDITY` # 62
--- | `BUFF_TYPE_MINOR_TOUGHNESS` # 50
--- | `BUFF_TYPE_MINOR_UNCERTAINTY` # 56
--- | `BUFF_TYPE_MINOR_VITALITY` # 23
--- | `BUFF_TYPE_MINOR_VULNERABILITY` # 60
--- | `BUFF_TYPE_NONE` # 0

BUFF_TYPE_DEPRECATED_INCREASE_ULT_COST = 59
BUFF_TYPE_EMPOWER = 37
BUFF_TYPE_MAJOR_AEGIS = 52
BUFF_TYPE_MAJOR_BERSERK = 43
BUFF_TYPE_MAJOR_BREACH = 41
BUFF_TYPE_MAJOR_BRITTLE = 12
BUFF_TYPE_MAJOR_BRUTALITY = 2
BUFF_TYPE_MAJOR_COURAGE = 49
BUFF_TYPE_MAJOR_COWARDICE = 39
BUFF_TYPE_MAJOR_DEFILE = 32
BUFF_TYPE_MAJOR_ENDURANCE = 16
BUFF_TYPE_MAJOR_EVASION = 26
BUFF_TYPE_MAJOR_EXPEDITION = 36
BUFF_TYPE_MAJOR_FORCE = 45
BUFF_TYPE_MAJOR_FORTITUDE = 14
BUFF_TYPE_MAJOR_GALLOP = 54
BUFF_TYPE_MAJOR_HEROISM = 20
BUFF_TYPE_MAJOR_INTELLECT = 18
BUFF_TYPE_MAJOR_MAIM = 30
BUFF_TYPE_MAJOR_MANGLE = 34
BUFF_TYPE_MAJOR_MENDING = 22
BUFF_TYPE_MAJOR_PROPHECY = 8
BUFF_TYPE_MAJOR_PROTECTION = 28
BUFF_TYPE_MAJOR_RESOLVE = 10
BUFF_TYPE_MAJOR_SAVAGERY = 4
BUFF_TYPE_MAJOR_SLAYER = 47
BUFF_TYPE_MAJOR_SORCERY = 6
BUFF_TYPE_MAJOR_TIMIDITY = 63
BUFF_TYPE_MAJOR_VITALITY = 24
BUFF_TYPE_MAJOR_VULNERABILITY = 61
BUFF_TYPE_MINOR_AEGIS = 51
BUFF_TYPE_MINOR_BERSERK = 42
BUFF_TYPE_MINOR_BREACH = 40
BUFF_TYPE_MINOR_BRITTLE = 11
BUFF_TYPE_MINOR_BRUTALITY = 1
BUFF_TYPE_MINOR_COURAGE = 48
BUFF_TYPE_MINOR_COWARDICE = 38
BUFF_TYPE_MINOR_DEFILE = 31
BUFF_TYPE_MINOR_ENDURANCE = 15
BUFF_TYPE_MINOR_ENERVATION = 55
BUFF_TYPE_MINOR_EVASION = 25
BUFF_TYPE_MINOR_EXPEDITION = 35
BUFF_TYPE_MINOR_FORCE = 44
BUFF_TYPE_MINOR_FORTITUDE = 13
BUFF_TYPE_MINOR_GALLOP = 53
BUFF_TYPE_MINOR_HEROISM = 19
BUFF_TYPE_MINOR_INTELLECT = 17
BUFF_TYPE_MINOR_LIFESTEAL = 57
BUFF_TYPE_MINOR_MAGICKASTEAL = 58
BUFF_TYPE_MINOR_MAIM = 29
BUFF_TYPE_MINOR_MANGLE = 33
BUFF_TYPE_MINOR_MENDING = 21
BUFF_TYPE_MINOR_PROPHECY = 7
BUFF_TYPE_MINOR_PROTECTION = 27
BUFF_TYPE_MINOR_RESOLVE = 9
BUFF_TYPE_MINOR_SAVAGERY = 3
BUFF_TYPE_MINOR_SLAYER = 46
BUFF_TYPE_MINOR_SORCERY = 5
BUFF_TYPE_MINOR_TIMIDITY = 62
BUFF_TYPE_MINOR_TOUGHNESS = 50
BUFF_TYPE_MINOR_UNCERTAINTY = 56
BUFF_TYPE_MINOR_VITALITY = 23
BUFF_TYPE_MINOR_VULNERABILITY = 60
BUFF_TYPE_NONE = 0
