--- @meta BuffsSettings

--- @alias BuffsSettings integer
--- | `BUFFS_SETTING_ALL_ENABLED` # 0
--- | `BUFFS_SETTING_BUFFS_ENABLED` # 1
--- | `BUFFS_SETTING_BUFFS_ENABLED_FOR_SELF` # 2
--- | `BUFFS_SETTING_BUFFS_ENABLED_FOR_TARGET` # 3
--- | `BUFFS_SETTING_DEBUFFS_ENABLED` # 4
--- | `BUFFS_SETTING_DEBUFFS_ENABLED_FOR_SELF` # 5
--- | `BUFFS_SETTING_DEBUFFS_ENABLED_FOR_TARGET` # 6
--- | `BUFFS_SETTING_DEBUFFS_ENABLED_FOR_TARGET_FROM_OTHERS` # 9
--- | `BUFFS_SETTING_LONG_EFFECTS` # 7
--- | `BUFFS_SETTING_PERMANENT_EFFECTS` # 8

BUFFS_SETTING_ALL_ENABLED = 0
BUFFS_SETTING_BUFFS_ENABLED = 1
BUFFS_SETTING_BUFFS_ENABLED_FOR_SELF = 2
BUFFS_SETTING_BUFFS_ENABLED_FOR_TARGET = 3
BUFFS_SETTING_DEBUFFS_ENABLED = 4
BUFFS_SETTING_DEBUFFS_ENABLED_FOR_SELF = 5
BUFFS_SETTING_DEBUFFS_ENABLED_FOR_TARGET = 6
BUFFS_SETTING_DEBUFFS_ENABLED_FOR_TARGET_FROM_OTHERS = 9
BUFFS_SETTING_LONG_EFFECTS = 7
BUFFS_SETTING_PERMANENT_EFFECTS = 8
