--- @meta CadwellProgressionLevel

--- @alias CadwellProgressionLevel integer
--- | `CADWELL_PROGRESSION_LEVEL_BRONZE` # 0
--- | `CADWELL_PROGRESSION_LEVEL_GOLD` # 2
--- | `CADWELL_PROGRESSION_LEVEL_SILVER` # 1

CADWELL_PROGRESSION_LEVEL_BRONZE = 0
CADWELL_PROGRESSION_LEVEL_GOLD = 2
CADWELL_PROGRESSION_LEVEL_SILVER = 1
