--- @meta CameraSetting

--- @alias CameraSetting integer
--- | `CAMERA_SETTING_ASSASSINATION_CAMERA` # 15
--- | `CAMERA_SETTING_DISTANCE` # 4
--- | `CAMERA_SETTING_DISTANCE_SYNCED` # 6
--- | `CAMERA_SETTING_DISTANCE_UNSHEATHED` # 5
--- | `CAMERA_SETTING_FIRST_PERSON_FIELD_OF_VIEW` # 7
--- | `CAMERA_SETTING_FIRST_PERSON_HEAD_BOB` # 8
--- | `CAMERA_SETTING_FOV_CHANGES_ALLOWED` # 13
--- | `CAMERA_SETTING_INVERT_Y` # 0
--- | `CAMERA_SETTING_SCREEN_SHAKE` # 16
--- | `CAMERA_SETTING_SENSITIVITY_FIRST_PERSON` # 3
--- | `CAMERA_SETTING_SENSITIVITY_THIRD_PERSON` # 2
--- | `CAMERA_SETTING_SMOOTHING` # 1
--- | `CAMERA_SETTING_THIRD_PERSON_FIELD_OF_VIEW` # 12
--- | `CAMERA_SETTING_THIRD_PERSON_HORIZONTAL_OFFSET` # 10
--- | `CAMERA_SETTING_THIRD_PERSON_HORIZONTAL_POSITION_MULTIPLIER` # 9
--- | `CAMERA_SETTING_THIRD_PERSON_SIEGE_WEAPONRY` # 14
--- | `CAMERA_SETTING_THIRD_PERSON_VERTICAL_OFFSET` # 11

CAMERA_SETTING_ASSASSINATION_CAMERA = 15
CAMERA_SETTING_DISTANCE = 4
CAMERA_SETTING_DISTANCE_SYNCED = 6
CAMERA_SETTING_DISTANCE_UNSHEATHED = 5
CAMERA_SETTING_FIRST_PERSON_FIELD_OF_VIEW = 7
CAMERA_SETTING_FIRST_PERSON_HEAD_BOB = 8
CAMERA_SETTING_FOV_CHANGES_ALLOWED = 13
CAMERA_SETTING_INVERT_Y = 0
CAMERA_SETTING_SCREEN_SHAKE = 16
CAMERA_SETTING_SENSITIVITY_FIRST_PERSON = 3
CAMERA_SETTING_SENSITIVITY_THIRD_PERSON = 2
CAMERA_SETTING_SMOOTHING = 1
CAMERA_SETTING_THIRD_PERSON_FIELD_OF_VIEW = 12
CAMERA_SETTING_THIRD_PERSON_HORIZONTAL_OFFSET = 10
CAMERA_SETTING_THIRD_PERSON_HORIZONTAL_POSITION_MULTIPLIER = 9
CAMERA_SETTING_THIRD_PERSON_SIEGE_WEAPONRY = 14
CAMERA_SETTING_THIRD_PERSON_VERTICAL_OFFSET = 11
