--- @meta CameraOptionsPreview

--- @alias CameraOptionsPreview integer
--- | `CAMERA_OPTIONS_PREVIEW_FORCE_FIRST_PERSON` # 2
--- | `CAMERA_OPTIONS_PREVIEW_FORCE_THIRD_PERSON` # 1
--- | `CAMERA_OPTIONS_PREVIEW_NONE` # 0

CAMERA_OPTIONS_PREVIEW_FORCE_FIRST_PERSON = 2
CAMERA_OPTIONS_PREVIEW_FORCE_THIRD_PERSON = 1
CAMERA_OPTIONS_PREVIEW_NONE = 0
