--- @meta CampaignLevelRequirementType

--- @alias CampaignLevelRequirementType integer
--- | `CAMPAIGN_LEVEL_REQ_TYPE_CHAMPION_RANK` # 2
--- | `CAMPAIGN_LEVEL_REQ_TYPE_NONE` # 0
--- | `CAMPAIGN_LEVEL_REQ_TYPE_PLAYER_LEVEL` # 1

CAMPAIGN_LEVEL_REQ_TYPE_CHAMPION_RANK = 2
CAMPAIGN_LEVEL_REQ_TYPE_NONE = 0
CAMPAIGN_LEVEL_REQ_TYPE_PLAYER_LEVEL = 1
