--- @meta CampaignQueueRequestStateType

--- @alias CampaignQueueRequestStateType integer
--- | `CAMPAIGN_QUEUE_REQUEST_STATE_CONFIRMING` # 2
--- | `CAMPAIGN_QUEUE_REQUEST_STATE_FINISHED` # 3
--- | `CAMPAIGN_QUEUE_REQUEST_STATE_PENDING_ACCEPT` # 5
--- | `CAMPAIGN_QUEUE_REQUEST_STATE_PENDING_JOIN` # 0
--- | `CAMPAIGN_QUEUE_REQUEST_STATE_PENDING_LEAVE` # 4
--- | `CAMPAIGN_QUEUE_REQUEST_STATE_WAITING` # 1

CAMPAIGN_QUEUE_REQUEST_STATE_CONFIRMING = 2
CAMPAIGN_QUEUE_REQUEST_STATE_FINISHED = 3
CAMPAIGN_QUEUE_REQUEST_STATE_PENDING_ACCEPT = 5
CAMPAIGN_QUEUE_REQUEST_STATE_PENDING_JOIN = 0
CAMPAIGN_QUEUE_REQUEST_STATE_PENDING_LEAVE = 4
CAMPAIGN_QUEUE_REQUEST_STATE_WAITING = 1
