--- @meta CampaignBuffType

--- @alias CampaignBuffType integer
--- | `CAMPAIGNBUFF_DEFENSIVE_ARTIFACT` # 1
--- | `CAMPAIGNBUFF_EMPEROR` # 3
--- | `CAMPAIGNBUFF_KEEP` # 2
--- | `CAMPAIGNBUFF_OFFENSIVE_ARTIFACT` # 0

CAMPAIGNBUFF_DEFENSIVE_ARTIFACT = 1
CAMPAIGNBUFF_EMPEROR = 3
CAMPAIGNBUFF_KEEP = 2
CAMPAIGNBUFF_OFFENSIVE_ARTIFACT = 0
