--- @meta CampaignReassignmentErrorReason

--- @alias CampaignReassignmentErrorReason integer
--- | `CAMPAIGN_REASSIGN_ERROR_CAMPAIGNS_DISABLED` # 14
--- | `CAMPAIGN_REASSIGN_ERROR_DEPRECATED_1` # 11
--- | `CAMPAIGN_REASSIGN_ERROR_DEPRECATED_2` # 12
--- | `CAMPAIGN_REASSIGN_ERROR_DESTINATION_CAMPAIGN_ALLIANCE_LOCKED` # 17
--- | `CAMPAIGN_REASSIGN_ERROR_DESTINATION_CAMPAIGN_DISABLED` # 4
--- | `CAMPAIGN_REASSIGN_ERROR_DESTINATION_CAMPAIGN_IN_CONFLICT` # 5
--- | `CAMPAIGN_REASSIGN_ERROR_INITIALIZATION_ERROR` # 9
--- | `CAMPAIGN_REASSIGN_ERROR_INSUFFICIENT_FUNDS` # 8
--- | `CAMPAIGN_REASSIGN_ERROR_INVALID_DB_STATE` # 6
--- | `CAMPAIGN_REASSIGN_ERROR_INVALID_DESTINATION_CAMPAIGN` # 1
--- | `CAMPAIGN_REASSIGN_ERROR_LEVEL_REQUIREMENT_NOT_MET` # 15
--- | `CAMPAIGN_REASSIGN_ERROR_NONE` # 0
--- | `CAMPAIGN_REASSIGN_ERROR_REASSIGNMENT_IN_PROGRESS` # 7
--- | `CAMPAIGN_REASSIGN_ERROR_REASSIGNMENT_ON_COOLDOWN` # 3
--- | `CAMPAIGN_REASSIGN_ERROR_REASSIGN_ON_END_INVALID` # 16
--- | `CAMPAIGN_REASSIGN_ERROR_REQUIREMENTS_NOT_MET` # 13
--- | `CAMPAIGN_REASSIGN_ERROR_UNCHANGED_DESTINATION_CAMPAIGN` # 2
--- | `CAMPAIGN_REASSIGN_ERROR_UNCHANGED_DESTINATION_PENDING_CAMPAIGN` # 10

CAMPAIGN_REASSIGN_ERROR_CAMPAIGNS_DISABLED = 14
CAMPAIGN_REASSIGN_ERROR_DEPRECATED_1 = 11
CAMPAIGN_REASSIGN_ERROR_DEPRECATED_2 = 12
CAMPAIGN_REASSIGN_ERROR_DESTINATION_CAMPAIGN_ALLIANCE_LOCKED = 17
CAMPAIGN_REASSIGN_ERROR_DESTINATION_CAMPAIGN_DISABLED = 4
CAMPAIGN_REASSIGN_ERROR_DESTINATION_CAMPAIGN_IN_CONFLICT = 5
CAMPAIGN_REASSIGN_ERROR_INITIALIZATION_ERROR = 9
CAMPAIGN_REASSIGN_ERROR_INSUFFICIENT_FUNDS = 8
CAMPAIGN_REASSIGN_ERROR_INVALID_DB_STATE = 6
CAMPAIGN_REASSIGN_ERROR_INVALID_DESTINATION_CAMPAIGN = 1
CAMPAIGN_REASSIGN_ERROR_LEVEL_REQUIREMENT_NOT_MET = 15
CAMPAIGN_REASSIGN_ERROR_NONE = 0
CAMPAIGN_REASSIGN_ERROR_REASSIGNMENT_IN_PROGRESS = 7
CAMPAIGN_REASSIGN_ERROR_REASSIGNMENT_ON_COOLDOWN = 3
CAMPAIGN_REASSIGN_ERROR_REASSIGN_ON_END_INVALID = 16
CAMPAIGN_REASSIGN_ERROR_REQUIREMENTS_NOT_MET = 13
CAMPAIGN_REASSIGN_ERROR_UNCHANGED_DESTINATION_CAMPAIGN = 2
CAMPAIGN_REASSIGN_ERROR_UNCHANGED_DESTINATION_PENDING_CAMPAIGN = 10
