--- @meta CampaignUnassignRequestType

--- @alias CampaignUnassignRequestType integer
--- | `CAMPAIGN_UNASSIGN_TYPE_HOME_USE_ALLIANCE_POINTS` # 0
--- | `CAMPAIGN_UNASSIGN_TYPE_HOME_USE_GOLD` # 1

CAMPAIGN_UNASSIGN_TYPE_HOME_USE_ALLIANCE_POINTS = 0
CAMPAIGN_UNASSIGN_TYPE_HOME_USE_GOLD = 1
