--- @meta CampaignRulesetType

--- @alias CampaignRulesetType integer
--- | `CAMPAIGN_RULESET_TYPE_CYRODIIL` # 1
--- | `CAMPAIGN_RULESET_TYPE_DEPRECATED1` # 2
--- | `CAMPAIGN_RULESET_TYPE_DEPRECATED2` # 3
--- | `CAMPAIGN_RULESET_TYPE_IMPERIAL_CITY` # 4

CAMPAIGN_RULESET_TYPE_CYRODIIL = 1
CAMPAIGN_RULESET_TYPE_DEPRECATED1 = 2
CAMPAIGN_RULESET_TYPE_DEPRECATED2 = 3
CAMPAIGN_RULESET_TYPE_IMPERIAL_CITY = 4
