--- @meta CampaignHoldingType

--- @alias CampaignHoldingType integer
--- | `HOLDINGTYPE_DEFENSIVE_ARTIFACT` # 3
--- | `HOLDINGTYPE_KEEP` # 0
--- | `HOLDINGTYPE_OFFENSIVE_ARTIFACT` # 4
--- | `HOLDINGTYPE_OUTPOST` # 2
--- | `HOLDINGTYPE_RESOURCE` # 1

HOLDINGTYPE_DEFENSIVE_ARTIFACT = 3
HOLDINGTYPE_KEEP = 0
HOLDINGTYPE_OFFENSIVE_ARTIFACT = 4
HOLDINGTYPE_OUTPOST = 2
HOLDINGTYPE_RESOURCE = 1
