--- @meta CampaignAllianceLockReason

--- @alias CampaignAllianceLockReason integer
--- | `CAMPAIGN_ALLIANCE_LOCK_REASON_CAMPAIGN_ENTERED_AND_ASSIGNED` # 3
--- | `CAMPAIGN_ALLIANCE_LOCK_REASON_CHARACTER_ASSIGNED` # 2
--- | `CAMPAIGN_ALLIANCE_LOCK_REASON_ENTERED_CAMPAIGN` # 1

CAMPAIGN_ALLIANCE_LOCK_REASON_CAMPAIGN_ENTERED_AND_ASSIGNED = 3
CAMPAIGN_ALLIANCE_LOCK_REASON_CHARACTER_ASSIGNED = 2
CAMPAIGN_ALLIANCE_LOCK_REASON_ENTERED_CAMPAIGN = 1
