--- @meta CardinalDirection

--- @alias CardinalDirection integer
--- | `CARDINAL_DIRECTION_EAST` # 2
--- | `CARDINAL_DIRECTION_NORTH` # 0
--- | `CARDINAL_DIRECTION_SOUTH` # 3
--- | `CARDINAL_DIRECTION_WEST` # 1

CARDINAL_DIRECTION_EAST = 2
CARDINAL_DIRECTION_NORTH = 0
CARDINAL_DIRECTION_SOUTH = 3
CARDINAL_DIRECTION_WEST = 1
