--- @meta CenterScreenAnnounceType

--- @alias CenterScreenAnnounceType integer
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_ABILITY_PROGRESSION_RANK_MORPH` # 12
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_ABILITY_PROGRESSION_RANK_UPDATE` # 11
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_ACHIEVEMENT_AWARDED` # 1
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_ACTIVITY_COMPLETE` # 61
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_ANTIQUITY_DIGGING_GAME_UPDATE` # 47
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_ANTIQUITY_DIG_SITES_UPDATED` # 33
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_ANTIQUITY_LEAD_ACQUIRED` # 46
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_ANTIQUITY_SCRYING_RESULT` # 34
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_ARTIFACT_CONTROL_STATE` # 2
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_AVENGE_KILL` # 8
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_BAG_CAPACITY_CHANGED` # 57
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_BANK_CAPACITY_CHANGED` # 58
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_BATTLEGROUND_MINUTE_WARNING` # 52
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_BATTLEGROUND_NEARING_VICTORY` # 53
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_BATTLEGROUND_OBJECTIVE` # 54
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_CHAMPION_LEVEL_ACHIEVED` # 25
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_CHAMPION_POINT_GAINED` # 24
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_COLLECTIBLES_UPDATED` # 42
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_COMPANION_ACTIVE_SKILL_UNLOCKED` # 9
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_COMPANION_SKILL_LINE_ADDED` # 10
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_CONSOLIDATED_STATION_SETS_UPDATED` # 69
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_CORONATE_EMPEROR` # 4
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_COUNTDOWN` # 51
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_CRAFTING_RESULTS` # 67
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_CYRODIIL_KEEP_REWARD` # 45
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_DAEDRIC_ARTIFACT_OBJECTIVE_STATE_CHANGED` # 3
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_DAILY_LOGIN_REWARD_CLAIMED` # 36
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_DEPOSE_EMPEROR` # 5
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_DISCOVERY_EXPERIENCE` # 23
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_DISPLAY_ANNOUNCEMENT` # 64
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_DUEL_COUNTDOWN` # 50
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_DUEL_FINISHED` # 48
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_DUEL_NEAR_BOUNDARY` # 49
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_ENDLESS_DUNGEON_ATTEMPTS_REMAINING_CHANGED` # 70
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_ENDLESS_DUNGEON_BUFF_ADDED` # 71
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_ENDLESS_DUNGEON_PROGRESS` # 68
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_ENLIGHTENMENT_GAINED` # 55
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_ENLIGHTENMENT_LOST` # 56
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_ESO_PLUS_SUBSCRIPTION_CHANGED` # 65
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_EXPERIENCE_GAIN` # 26
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_FORCE_RESPEC` # 59
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_JUSTICE_INFAMY_CHANGED` # 37
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_JUSTICE_NOW_KOS` # 38
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_JUSTICE_NO_LONGER_KOS` # 39
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_KEEP_GATE_CHANGED` # 6
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_LEVEL_GAIN` # 27
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_LORE_BOOK_LEARNED` # 18
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_LORE_BOOK_LEARNED_SKILL_EXPERIENCE` # 19
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_LORE_COLLECTION_COMPLETED` # 16
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_LORE_COLLECTION_COMPLETED_SKILL_EXPERIENCE` # 17
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_OBJECTIVE_COMPLETED` # 28
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_OUTFIT_CHANGES_APPLIED` # 43
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_PLEDGE_OF_MARA_RESULT` # 0
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_POI_DISCOVERED` # 35
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_QUEST_ADDED` # 32
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_QUEST_COMPLETED` # 29
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_QUEST_CONDITION_COMPLETED` # 31
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_QUEST_PROGRESSION_CHANGED` # 30
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_RAID_TRIAL` # 22
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_REVENGE_KILL` # 7
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_RIDING_SKILL_IMPROVEMENT` # 44
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_SINGLE_COLLECTIBLE_UPDATED` # 41
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_SINGLE_TRIBUTE_CARD_UPDATED` # 40
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_SKILL_LINE_ADDED` # 13
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_SKILL_POINTS_GAINED` # 21
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_SKILL_POINTS_PARTIAL_GAINED` # 20
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_SKILL_RANK_UPDATE` # 14
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_SKILL_XP_UPDATE` # 15
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_SYSTEM_BROADCAST` # 66
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_TIMED_ACTIVITY_COMPLETED` # 60
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_TRIBUTE_CLUB_RANK_CHANGED` # 63
--- | `CENTER_SCREEN_ANNOUNCE_TYPE_TRIBUTE_GAME_STATE_CHANGED` # 62

CENTER_SCREEN_ANNOUNCE_TYPE_ABILITY_PROGRESSION_RANK_MORPH = 12
CENTER_SCREEN_ANNOUNCE_TYPE_ABILITY_PROGRESSION_RANK_UPDATE = 11
CENTER_SCREEN_ANNOUNCE_TYPE_ACHIEVEMENT_AWARDED = 1
CENTER_SCREEN_ANNOUNCE_TYPE_ACTIVITY_COMPLETE = 61
CENTER_SCREEN_ANNOUNCE_TYPE_ANTIQUITY_DIGGING_GAME_UPDATE = 47
CENTER_SCREEN_ANNOUNCE_TYPE_ANTIQUITY_DIG_SITES_UPDATED = 33
CENTER_SCREEN_ANNOUNCE_TYPE_ANTIQUITY_LEAD_ACQUIRED = 46
CENTER_SCREEN_ANNOUNCE_TYPE_ANTIQUITY_SCRYING_RESULT = 34
CENTER_SCREEN_ANNOUNCE_TYPE_ARTIFACT_CONTROL_STATE = 2
CENTER_SCREEN_ANNOUNCE_TYPE_AVENGE_KILL = 8
CENTER_SCREEN_ANNOUNCE_TYPE_BAG_CAPACITY_CHANGED = 57
CENTER_SCREEN_ANNOUNCE_TYPE_BANK_CAPACITY_CHANGED = 58
CENTER_SCREEN_ANNOUNCE_TYPE_BATTLEGROUND_MINUTE_WARNING = 52
CENTER_SCREEN_ANNOUNCE_TYPE_BATTLEGROUND_NEARING_VICTORY = 53
CENTER_SCREEN_ANNOUNCE_TYPE_BATTLEGROUND_OBJECTIVE = 54
CENTER_SCREEN_ANNOUNCE_TYPE_CHAMPION_LEVEL_ACHIEVED = 25
CENTER_SCREEN_ANNOUNCE_TYPE_CHAMPION_POINT_GAINED = 24
CENTER_SCREEN_ANNOUNCE_TYPE_COLLECTIBLES_UPDATED = 42
CENTER_SCREEN_ANNOUNCE_TYPE_COMPANION_ACTIVE_SKILL_UNLOCKED = 9
CENTER_SCREEN_ANNOUNCE_TYPE_COMPANION_SKILL_LINE_ADDED = 10
CENTER_SCREEN_ANNOUNCE_TYPE_CONSOLIDATED_STATION_SETS_UPDATED = 69
CENTER_SCREEN_ANNOUNCE_TYPE_CORONATE_EMPEROR = 4
CENTER_SCREEN_ANNOUNCE_TYPE_COUNTDOWN = 51
CENTER_SCREEN_ANNOUNCE_TYPE_CRAFTING_RESULTS = 67
CENTER_SCREEN_ANNOUNCE_TYPE_CYRODIIL_KEEP_REWARD = 45
CENTER_SCREEN_ANNOUNCE_TYPE_DAEDRIC_ARTIFACT_OBJECTIVE_STATE_CHANGED = 3
CENTER_SCREEN_ANNOUNCE_TYPE_DAILY_LOGIN_REWARD_CLAIMED = 36
CENTER_SCREEN_ANNOUNCE_TYPE_DEPOSE_EMPEROR = 5
CENTER_SCREEN_ANNOUNCE_TYPE_DISCOVERY_EXPERIENCE = 23
CENTER_SCREEN_ANNOUNCE_TYPE_DISPLAY_ANNOUNCEMENT = 64
CENTER_SCREEN_ANNOUNCE_TYPE_DUEL_COUNTDOWN = 50
CENTER_SCREEN_ANNOUNCE_TYPE_DUEL_FINISHED = 48
CENTER_SCREEN_ANNOUNCE_TYPE_DUEL_NEAR_BOUNDARY = 49
CENTER_SCREEN_ANNOUNCE_TYPE_ENDLESS_DUNGEON_ATTEMPTS_REMAINING_CHANGED = 70
CENTER_SCREEN_ANNOUNCE_TYPE_ENDLESS_DUNGEON_BUFF_ADDED = 71
CENTER_SCREEN_ANNOUNCE_TYPE_ENDLESS_DUNGEON_PROGRESS = 68
CENTER_SCREEN_ANNOUNCE_TYPE_ENLIGHTENMENT_GAINED = 55
CENTER_SCREEN_ANNOUNCE_TYPE_ENLIGHTENMENT_LOST = 56
CENTER_SCREEN_ANNOUNCE_TYPE_ESO_PLUS_SUBSCRIPTION_CHANGED = 65
CENTER_SCREEN_ANNOUNCE_TYPE_EXPERIENCE_GAIN = 26
CENTER_SCREEN_ANNOUNCE_TYPE_FORCE_RESPEC = 59
CENTER_SCREEN_ANNOUNCE_TYPE_JUSTICE_INFAMY_CHANGED = 37
CENTER_SCREEN_ANNOUNCE_TYPE_JUSTICE_NOW_KOS = 38
CENTER_SCREEN_ANNOUNCE_TYPE_JUSTICE_NO_LONGER_KOS = 39
CENTER_SCREEN_ANNOUNCE_TYPE_KEEP_GATE_CHANGED = 6
CENTER_SCREEN_ANNOUNCE_TYPE_LEVEL_GAIN = 27
CENTER_SCREEN_ANNOUNCE_TYPE_LORE_BOOK_LEARNED = 18
CENTER_SCREEN_ANNOUNCE_TYPE_LORE_BOOK_LEARNED_SKILL_EXPERIENCE = 19
CENTER_SCREEN_ANNOUNCE_TYPE_LORE_COLLECTION_COMPLETED = 16
CENTER_SCREEN_ANNOUNCE_TYPE_LORE_COLLECTION_COMPLETED_SKILL_EXPERIENCE = 17
CENTER_SCREEN_ANNOUNCE_TYPE_OBJECTIVE_COMPLETED = 28
CENTER_SCREEN_ANNOUNCE_TYPE_OUTFIT_CHANGES_APPLIED = 43
CENTER_SCREEN_ANNOUNCE_TYPE_PLEDGE_OF_MARA_RESULT = 0
CENTER_SCREEN_ANNOUNCE_TYPE_POI_DISCOVERED = 35
CENTER_SCREEN_ANNOUNCE_TYPE_QUEST_ADDED = 32
CENTER_SCREEN_ANNOUNCE_TYPE_QUEST_COMPLETED = 29
CENTER_SCREEN_ANNOUNCE_TYPE_QUEST_CONDITION_COMPLETED = 31
CENTER_SCREEN_ANNOUNCE_TYPE_QUEST_PROGRESSION_CHANGED = 30
CENTER_SCREEN_ANNOUNCE_TYPE_RAID_TRIAL = 22
CENTER_SCREEN_ANNOUNCE_TYPE_REVENGE_KILL = 7
CENTER_SCREEN_ANNOUNCE_TYPE_RIDING_SKILL_IMPROVEMENT = 44
CENTER_SCREEN_ANNOUNCE_TYPE_SINGLE_COLLECTIBLE_UPDATED = 41
CENTER_SCREEN_ANNOUNCE_TYPE_SINGLE_TRIBUTE_CARD_UPDATED = 40
CENTER_SCREEN_ANNOUNCE_TYPE_SKILL_LINE_ADDED = 13
CENTER_SCREEN_ANNOUNCE_TYPE_SKILL_POINTS_GAINED = 21
CENTER_SCREEN_ANNOUNCE_TYPE_SKILL_POINTS_PARTIAL_GAINED = 20
CENTER_SCREEN_ANNOUNCE_TYPE_SKILL_RANK_UPDATE = 14
CENTER_SCREEN_ANNOUNCE_TYPE_SKILL_XP_UPDATE = 15
CENTER_SCREEN_ANNOUNCE_TYPE_SYSTEM_BROADCAST = 66
CENTER_SCREEN_ANNOUNCE_TYPE_TIMED_ACTIVITY_COMPLETED = 60
CENTER_SCREEN_ANNOUNCE_TYPE_TRIBUTE_CLUB_RANK_CHANGED = 63
CENTER_SCREEN_ANNOUNCE_TYPE_TRIBUTE_GAME_STATE_CHANGED = 62
