--- @meta CenterScreenAnnouncementCategory

--- @alias CenterScreenAnnouncementCategory integer
--- | `CSA_CATEGORY_ANIMATED_CONTROL` # 11
--- | `CSA_CATEGORY_COUNTDOWN_TEXT` # 6
--- | `CSA_CATEGORY_ENDLESS_DUNGEON_STAGE_STARTED_TEXT` # 10
--- | `CSA_CATEGORY_EXTERNAL_HANDLE` # 8
--- | `CSA_CATEGORY_INVALID` # 0
--- | `CSA_CATEGORY_LARGE_TEXT` # 2
--- | `CSA_CATEGORY_MAJOR_TEXT` # 5
--- | `CSA_CATEGORY_NO_TEXT` # 3
--- | `CSA_CATEGORY_RAID_COMPLETE_TEXT` # 4
--- | `CSA_CATEGORY_ROLLING_METER_PROGRESS_TEXT` # 9
--- | `CSA_CATEGORY_SCRYING_PROGRESS_TEXT` # 7
--- | `CSA_CATEGORY_SMALL_TEXT` # 1

CSA_CATEGORY_ANIMATED_CONTROL = 11
CSA_CATEGORY_COUNTDOWN_TEXT = 6
CSA_CATEGORY_ENDLESS_DUNGEON_STAGE_STARTED_TEXT = 10
CSA_CATEGORY_EXTERNAL_HANDLE = 8
CSA_CATEGORY_INVALID = 0
CSA_CATEGORY_LARGE_TEXT = 2
CSA_CATEGORY_MAJOR_TEXT = 5
CSA_CATEGORY_NO_TEXT = 3
CSA_CATEGORY_RAID_COMPLETE_TEXT = 4
CSA_CATEGORY_ROLLING_METER_PROGRESS_TEXT = 9
CSA_CATEGORY_SCRYING_PROGRESS_TEXT = 7
CSA_CATEGORY_SMALL_TEXT = 1
