--- @meta ChampionDisciplineType

--- @alias ChampionDisciplineType integer
--- | `CHAMPION_DISCIPLINE_TYPE_COMBAT` # 0
--- | `CHAMPION_DISCIPLINE_TYPE_CONDITIONING` # 1
--- | `CHAMPION_DISCIPLINE_TYPE_WORLD` # 2

CHAMPION_DISCIPLINE_TYPE_COMBAT = 0
CHAMPION_DISCIPLINE_TYPE_CONDITIONING = 1
CHAMPION_DISCIPLINE_TYPE_WORLD = 2
