--- @meta ChampionSkillType

--- @alias ChampionSkillType integer
--- | `CHAMPION_SKILL_TYPE_NORMAL` # 0
--- | `CHAMPION_SKILL_TYPE_NORMAL_SLOTTABLE` # 1
--- | `CHAMPION_SKILL_TYPE_STAT_POOL_SLOTTABLE` # 2

CHAMPION_SKILL_TYPE_NORMAL = 0
CHAMPION_SKILL_TYPE_NORMAL_SLOTTABLE = 1
CHAMPION_SKILL_TYPE_STAT_POOL_SLOTTABLE = 2
