--- @meta ChampionPurchaseResult

--- @alias ChampionPurchaseResult integer
--- | `CHAMPION_PURCHASE_ABILITY_CAP_EXCEEDED` # 8
--- | `CHAMPION_PURCHASE_ABILITY_LINE_LEVEL_NOT_MET` # 9
--- | `CHAMPION_PURCHASE_ATTRIBUTE_CAP_EXCEEDED` # 6
--- | `CHAMPION_PURCHASE_CARRYING_DAEDRIC_ARTIFACT` # 3
--- | `CHAMPION_PURCHASE_CHAMPION_BAR_ILLEGAL_SLOT` # 18
--- | `CHAMPION_PURCHASE_CHAMPION_BAR_NOT_CHAMPION_SKILL` # 17
--- | `CHAMPION_PURCHASE_CHAMPION_BAR_ON_COOLDOWN` # 22
--- | `CHAMPION_PURCHASE_CHAMPION_BAR_SKILL_NOT_PURCHASED` # 20
--- | `CHAMPION_PURCHASE_CHAMPION_BAR_SKILL_NOT_SLOTTABLE` # 19
--- | `CHAMPION_PURCHASE_CHAMPION_BAR_WRONG_DISCIPLINE` # 21
--- | `CHAMPION_PURCHASE_CHAMPION_NOT_UNLOCKED` # 14
--- | `CHAMPION_PURCHASE_CP_DISABLED` # 2
--- | `CHAMPION_PURCHASE_INTERNAL_ERROR` # 1
--- | `CHAMPION_PURCHASE_INVALID_ABILITY` # 10
--- | `CHAMPION_PURCHASE_INVALID_ATTRIBUTE` # 5
--- | `CHAMPION_PURCHASE_IN_COMBAT` # 11
--- | `CHAMPION_PURCHASE_IN_NOCP_BATTLEGROUND` # 13
--- | `CHAMPION_PURCHASE_IN_NOCP_CAMPAIGN` # 12
--- | `CHAMPION_PURCHASE_NOT_ENOUGH_POINTS` # 7
--- | `CHAMPION_PURCHASE_RESPEC_FAILED` # 4
--- | `CHAMPION_PURCHASE_SKILL_NEEDS_REFUND` # 16
--- | `CHAMPION_PURCHASE_SKILL_NOT_CONNECTED` # 15
--- | `CHAMPION_PURCHASE_SUCCESS` # 0

CHAMPION_PURCHASE_ABILITY_CAP_EXCEEDED = 8
CHAMPION_PURCHASE_ABILITY_LINE_LEVEL_NOT_MET = 9
CHAMPION_PURCHASE_ATTRIBUTE_CAP_EXCEEDED = 6
CHAMPION_PURCHASE_CARRYING_DAEDRIC_ARTIFACT = 3
CHAMPION_PURCHASE_CHAMPION_BAR_ILLEGAL_SLOT = 18
CHAMPION_PURCHASE_CHAMPION_BAR_NOT_CHAMPION_SKILL = 17
CHAMPION_PURCHASE_CHAMPION_BAR_ON_COOLDOWN = 22
CHAMPION_PURCHASE_CHAMPION_BAR_SKILL_NOT_PURCHASED = 20
CHAMPION_PURCHASE_CHAMPION_BAR_SKILL_NOT_SLOTTABLE = 19
CHAMPION_PURCHASE_CHAMPION_BAR_WRONG_DISCIPLINE = 21
CHAMPION_PURCHASE_CHAMPION_NOT_UNLOCKED = 14
CHAMPION_PURCHASE_CP_DISABLED = 2
CHAMPION_PURCHASE_INTERNAL_ERROR = 1
CHAMPION_PURCHASE_INVALID_ABILITY = 10
CHAMPION_PURCHASE_INVALID_ATTRIBUTE = 5
CHAMPION_PURCHASE_IN_COMBAT = 11
CHAMPION_PURCHASE_IN_NOCP_BATTLEGROUND = 13
CHAMPION_PURCHASE_IN_NOCP_CAMPAIGN = 12
CHAMPION_PURCHASE_NOT_ENOUGH_POINTS = 7
CHAMPION_PURCHASE_RESPEC_FAILED = 4
CHAMPION_PURCHASE_SKILL_NEEDS_REFUND = 16
CHAMPION_PURCHASE_SKILL_NOT_CONNECTED = 15
CHAMPION_PURCHASE_SUCCESS = 0
