--- @meta ChannelType

--- @alias ChannelType integer
--- | `CHAT_CHANNEL_EMOTE` # 6
--- | `CHAT_CHANNEL_GUILD_1` # 12
--- | `CHAT_CHANNEL_GUILD_2` # 13
--- | `CHAT_CHANNEL_GUILD_3` # 14
--- | `CHAT_CHANNEL_GUILD_4` # 15
--- | `CHAT_CHANNEL_GUILD_5` # 16
--- | `CHAT_CHANNEL_MONSTER_EMOTE` # 10
--- | `CHAT_CHANNEL_MONSTER_SAY` # 7
--- | `CHAT_CHANNEL_MONSTER_WHISPER` # 9
--- | `CHAT_CHANNEL_MONSTER_YELL` # 8
--- | `CHAT_CHANNEL_OFFICER_1` # 17
--- | `CHAT_CHANNEL_OFFICER_2` # 18
--- | `CHAT_CHANNEL_OFFICER_3` # 19
--- | `CHAT_CHANNEL_OFFICER_4` # 20
--- | `CHAT_CHANNEL_OFFICER_5` # 21
--- | `CHAT_CHANNEL_PARTY` # 3
--- | `CHAT_CHANNEL_SAY` # 0
--- | `CHAT_CHANNEL_SYSTEM` # 11
--- | `CHAT_CHANNEL_UNUSED_1` # 5
--- | `CHAT_CHANNEL_USER_CHANNEL_1` # 22
--- | `CHAT_CHANNEL_USER_CHANNEL_2` # 23
--- | `CHAT_CHANNEL_USER_CHANNEL_3` # 24
--- | `CHAT_CHANNEL_USER_CHANNEL_4` # 25
--- | `CHAT_CHANNEL_USER_CHANNEL_5` # 26
--- | `CHAT_CHANNEL_USER_CHANNEL_6` # 27
--- | `CHAT_CHANNEL_USER_CHANNEL_7` # 28
--- | `CHAT_CHANNEL_USER_CHANNEL_8` # 29
--- | `CHAT_CHANNEL_USER_CHANNEL_9` # 30
--- | `CHAT_CHANNEL_WHISPER` # 2
--- | `CHAT_CHANNEL_WHISPER_SENT` # 4
--- | `CHAT_CHANNEL_YELL` # 1
--- | `CHAT_CHANNEL_ZONE` # 31
--- | `CHAT_CHANNEL_ZONE_LANGUAGE_1` # 32
--- | `CHAT_CHANNEL_ZONE_LANGUAGE_2` # 33
--- | `CHAT_CHANNEL_ZONE_LANGUAGE_3` # 34
--- | `CHAT_CHANNEL_ZONE_LANGUAGE_4` # 35
--- | `CHAT_CHANNEL_ZONE_LANGUAGE_5` # 36
--- | `CHAT_CHANNEL_ZONE_LANGUAGE_6` # 37
--- | `CHAT_CHANNEL_ZONE_LANGUAGE_7` # 38

CHAT_CHANNEL_EMOTE = 6
CHAT_CHANNEL_GUILD_1 = 12
CHAT_CHANNEL_GUILD_2 = 13
CHAT_CHANNEL_GUILD_3 = 14
CHAT_CHANNEL_GUILD_4 = 15
CHAT_CHANNEL_GUILD_5 = 16
CHAT_CHANNEL_MONSTER_EMOTE = 10
CHAT_CHANNEL_MONSTER_SAY = 7
CHAT_CHANNEL_MONSTER_WHISPER = 9
CHAT_CHANNEL_MONSTER_YELL = 8
CHAT_CHANNEL_OFFICER_1 = 17
CHAT_CHANNEL_OFFICER_2 = 18
CHAT_CHANNEL_OFFICER_3 = 19
CHAT_CHANNEL_OFFICER_4 = 20
CHAT_CHANNEL_OFFICER_5 = 21
CHAT_CHANNEL_PARTY = 3
CHAT_CHANNEL_SAY = 0
CHAT_CHANNEL_SYSTEM = 11
CHAT_CHANNEL_UNUSED_1 = 5
CHAT_CHANNEL_USER_CHANNEL_1 = 22
CHAT_CHANNEL_USER_CHANNEL_2 = 23
CHAT_CHANNEL_USER_CHANNEL_3 = 24
CHAT_CHANNEL_USER_CHANNEL_4 = 25
CHAT_CHANNEL_USER_CHANNEL_5 = 26
CHAT_CHANNEL_USER_CHANNEL_6 = 27
CHAT_CHANNEL_USER_CHANNEL_7 = 28
CHAT_CHANNEL_USER_CHANNEL_8 = 29
CHAT_CHANNEL_USER_CHANNEL_9 = 30
CHAT_CHANNEL_WHISPER = 2
CHAT_CHANNEL_WHISPER_SENT = 4
CHAT_CHANNEL_YELL = 1
CHAT_CHANNEL_ZONE = 31
CHAT_CHANNEL_ZONE_LANGUAGE_1 = 32
CHAT_CHANNEL_ZONE_LANGUAGE_2 = 33
CHAT_CHANNEL_ZONE_LANGUAGE_3 = 34
CHAT_CHANNEL_ZONE_LANGUAGE_4 = 35
CHAT_CHANNEL_ZONE_LANGUAGE_5 = 36
CHAT_CHANNEL_ZONE_LANGUAGE_6 = 37
CHAT_CHANNEL_ZONE_LANGUAGE_7 = 38
