--- @meta ChapterUpgradeSource

--- @alias ChapterUpgradeSource integer
--- | `CHAPTER_UPGRADE_SOURCE_IN_GAME` # 1
--- | `CHAPTER_UPGRADE_SOURCE_PREGAME` # 0

CHAPTER_UPGRADE_SOURCE_IN_GAME = 1
CHAPTER_UPGRADE_SOURCE_PREGAME = 0
