--- @meta Chapter

--- @alias Chapter integer
--- | `CHAPTER_BADLANDS` # 5
--- | `CHAPTER_BASE_GAME` # 0
--- | `CHAPTER_DUNE` # 6
--- | `CHAPTER_GLACIER` # 2
--- | `CHAPTER_MAGMA` # 7
--- | `CHAPTER_MESA` # 3
--- | `CHAPTER_PENINSULA` # 8
--- | `CHAPTER_SCARP` # 4
--- | `CHAPTER_VOLCANO` # 1

CHAPTER_BADLANDS = 5
CHAPTER_BASE_GAME = 0
CHAPTER_DUNE = 6
CHAPTER_GLACIER = 2
CHAPTER_MAGMA = 7
CHAPTER_MESA = 3
CHAPTER_PENINSULA = 8
CHAPTER_SCARP = 4
CHAPTER_VOLCANO = 1
