--- @meta ChapterPurchaseState

--- @alias ChapterPurchaseState integer
--- | `CHAPTER_PURCHASE_STATE_PRE_PURCHASE` # 0
--- | `CHAPTER_PURCHASE_STATE_PURCHASED` # 2
--- | `CHAPTER_PURCHASE_STATE_UPGRADE` # 1

CHAPTER_PURCHASE_STATE_PRE_PURCHASE = 0
CHAPTER_PURCHASE_STATE_PURCHASED = 2
CHAPTER_PURCHASE_STATE_UPGRADE = 1
