--- @meta CharacterCreateOptionRestrictionReason

--- @alias CharacterCreateOptionRestrictionReason integer
--- | `CHARACTER_CREATE_OPTION_RESTRICTION_REASON_NONE` # 0
--- | `CHARACTER_CREATE_OPTION_RESTRICTION_REASON_REQUIRES_COLLECTIBLE` # 1
--- | `CHARACTER_CREATE_OPTION_RESTRICTION_REASON_REQUIRES_ENTITLEMENT` # 2

CHARACTER_CREATE_OPTION_RESTRICTION_REASON_NONE = 0
CHARACTER_CREATE_OPTION_RESTRICTION_REASON_REQUIRES_COLLECTIBLE = 1
CHARACTER_CREATE_OPTION_RESTRICTION_REASON_REQUIRES_ENTITLEMENT = 2
