--- @meta CharacterResolution

--- @alias CharacterResolution integer
--- | `CHARACTER_RESOLUTION_HIGH` # 2
--- | `CHARACTER_RESOLUTION_LOW` # 0
--- | `CHARACTER_RESOLUTION_MEDIUM` # 1
--- | `CHARACTER_RESOLUTION_ULTRA` # 3

CHARACTER_RESOLUTION_HIGH = 2
CHARACTER_RESOLUTION_LOW = 0
CHARACTER_RESOLUTION_MEDIUM = 1
CHARACTER_RESOLUTION_ULTRA = 3
