--- @meta ChatBubbleSetting

--- @alias ChatBubbleSetting integer
--- | `CHAT_BUBBLE_SETTING_ENABLED` # 0
--- | `CHAT_BUBBLE_SETTING_ENABLED_FOR_LOCAL_PLAYER` # 1
--- | `CHAT_BUBBLE_SETTING_ENABLED_ONLY_FROM_CONTACTS` # 2
--- | `CHAT_BUBBLE_SETTING_SPEED_MODIFIER` # 3

CHAT_BUBBLE_SETTING_ENABLED = 0
CHAT_BUBBLE_SETTING_ENABLED_FOR_LOCAL_PLAYER = 1
CHAT_BUBBLE_SETTING_ENABLED_ONLY_FROM_CONTACTS = 2
CHAT_BUBBLE_SETTING_SPEED_MODIFIER = 3
