--- @meta ChatChannelCategoryHeaders

--- @alias ChatChannelCategoryHeaders integer
--- | `CHAT_CATEGORY_HEADER_CHANNELS` # 1
--- | `CHAT_CATEGORY_HEADER_COMBAT` # 45
--- | `CHAT_CATEGORY_HEADER_GUILDS` # 10

CHAT_CATEGORY_HEADER_CHANNELS = 1
CHAT_CATEGORY_HEADER_COMBAT = 45
CHAT_CATEGORY_HEADER_GUILDS = 10
