--- @meta ChatChannelCategories

--- @alias ChatChannelCategories integer
--- | `CHAT_CATEGORY_COMBAT_ALLIANCE_POINTS` # 48
--- | `CHAT_CATEGORY_COMBAT_BLOCK_ABSORBED_DEFEND` # 58
--- | `CHAT_CATEGORY_COMBAT_DEATH` # 61
--- | `CHAT_CATEGORY_COMBAT_DIRECT_DAMAGE` # 51
--- | `CHAT_CATEGORY_COMBAT_DIRECT_HEAL` # 53
--- | `CHAT_CATEGORY_COMBAT_DODGE_PARRY_MISS` # 57
--- | `CHAT_CATEGORY_COMBAT_DOT` # 52
--- | `CHAT_CATEGORY_COMBAT_DRAIN` # 56
--- | `CHAT_CATEGORY_COMBAT_ENERGIZE` # 55
--- | `CHAT_CATEGORY_COMBAT_EXPERIENCE` # 45
--- | `CHAT_CATEGORY_COMBAT_GAINED_EFFECT` # 49
--- | `CHAT_CATEGORY_COMBAT_HOT` # 54
--- | `CHAT_CATEGORY_COMBAT_LOST_EFFECT` # 50
--- | `CHAT_CATEGORY_COMBAT_OTHER` # 60
--- | `CHAT_CATEGORY_COMBAT_RANK_POINTS` # 47
--- | `CHAT_CATEGORY_COMBAT_RESIST` # 59
--- | `CHAT_CATEGORY_COMBAT_TELVAR_STONES` # 46
--- | `CHAT_CATEGORY_EMOTE` # 8
--- | `CHAT_CATEGORY_GUILD_1` # 10
--- | `CHAT_CATEGORY_GUILD_2` # 11
--- | `CHAT_CATEGORY_GUILD_3` # 12
--- | `CHAT_CATEGORY_GUILD_4` # 13
--- | `CHAT_CATEGORY_GUILD_5` # 14
--- | `CHAT_CATEGORY_MONSTER_EMOTE` # 44
--- | `CHAT_CATEGORY_MONSTER_SAY` # 41
--- | `CHAT_CATEGORY_MONSTER_WHISPER` # 43
--- | `CHAT_CATEGORY_MONSTER_YELL` # 42
--- | `CHAT_CATEGORY_OFFICER_1` # 15
--- | `CHAT_CATEGORY_OFFICER_2` # 16
--- | `CHAT_CATEGORY_OFFICER_3` # 17
--- | `CHAT_CATEGORY_OFFICER_4` # 18
--- | `CHAT_CATEGORY_OFFICER_5` # 19
--- | `CHAT_CATEGORY_PARTY` # 7
--- | `CHAT_CATEGORY_SAY` # 1
--- | `CHAT_CATEGORY_SYSTEM` # 9
--- | `CHAT_CATEGORY_WHISPER_INCOMING` # 3
--- | `CHAT_CATEGORY_WHISPER_OUTGOING` # 4
--- | `CHAT_CATEGORY_YELL` # 2
--- | `CHAT_CATEGORY_ZONE` # 6
--- | `CHAT_CATEGORY_ZONE_CHINESE_S` # 26
--- | `CHAT_CATEGORY_ZONE_ENGLISH` # 20
--- | `CHAT_CATEGORY_ZONE_FRENCH` # 21
--- | `CHAT_CATEGORY_ZONE_GERMAN` # 22
--- | `CHAT_CATEGORY_ZONE_JAPANESE` # 23
--- | `CHAT_CATEGORY_ZONE_RUSSIAN` # 24
--- | `CHAT_CATEGORY_ZONE_SPANISH` # 25

CHAT_CATEGORY_COMBAT_ALLIANCE_POINTS = 48
CHAT_CATEGORY_COMBAT_BLOCK_ABSORBED_DEFEND = 58
CHAT_CATEGORY_COMBAT_DEATH = 61
CHAT_CATEGORY_COMBAT_DIRECT_DAMAGE = 51
CHAT_CATEGORY_COMBAT_DIRECT_HEAL = 53
CHAT_CATEGORY_COMBAT_DODGE_PARRY_MISS = 57
CHAT_CATEGORY_COMBAT_DOT = 52
CHAT_CATEGORY_COMBAT_DRAIN = 56
CHAT_CATEGORY_COMBAT_ENERGIZE = 55
CHAT_CATEGORY_COMBAT_EXPERIENCE = 45
CHAT_CATEGORY_COMBAT_GAINED_EFFECT = 49
CHAT_CATEGORY_COMBAT_HOT = 54
CHAT_CATEGORY_COMBAT_LOST_EFFECT = 50
CHAT_CATEGORY_COMBAT_OTHER = 60
CHAT_CATEGORY_COMBAT_RANK_POINTS = 47
CHAT_CATEGORY_COMBAT_RESIST = 59
CHAT_CATEGORY_COMBAT_TELVAR_STONES = 46
CHAT_CATEGORY_EMOTE = 8
CHAT_CATEGORY_GUILD_1 = 10
CHAT_CATEGORY_GUILD_2 = 11
CHAT_CATEGORY_GUILD_3 = 12
CHAT_CATEGORY_GUILD_4 = 13
CHAT_CATEGORY_GUILD_5 = 14
CHAT_CATEGORY_MONSTER_EMOTE = 44
CHAT_CATEGORY_MONSTER_SAY = 41
CHAT_CATEGORY_MONSTER_WHISPER = 43
CHAT_CATEGORY_MONSTER_YELL = 42
CHAT_CATEGORY_OFFICER_1 = 15
CHAT_CATEGORY_OFFICER_2 = 16
CHAT_CATEGORY_OFFICER_3 = 17
CHAT_CATEGORY_OFFICER_4 = 18
CHAT_CATEGORY_OFFICER_5 = 19
CHAT_CATEGORY_PARTY = 7
CHAT_CATEGORY_SAY = 1
CHAT_CATEGORY_SYSTEM = 9
CHAT_CATEGORY_WHISPER_INCOMING = 3
CHAT_CATEGORY_WHISPER_OUTGOING = 4
CHAT_CATEGORY_YELL = 2
CHAT_CATEGORY_ZONE = 6
CHAT_CATEGORY_ZONE_CHINESE_S = 26
CHAT_CATEGORY_ZONE_ENGLISH = 20
CHAT_CATEGORY_ZONE_FRENCH = 21
CHAT_CATEGORY_ZONE_GERMAN = 22
CHAT_CATEGORY_ZONE_JAPANESE = 23
CHAT_CATEGORY_ZONE_RUSSIAN = 24
CHAT_CATEGORY_ZONE_SPANISH = 25
