--- @meta ChromaMousepadEffectType

--- @alias ChromaMousepadEffectType integer
--- | `CHROMA_MOUSEPAD_EFFECT_TYPE_BREATHING` # 1
--- | `CHROMA_MOUSEPAD_EFFECT_TYPE_CUSTOM` # 2
--- | `CHROMA_MOUSEPAD_EFFECT_TYPE_INVALID` # 6
--- | `CHROMA_MOUSEPAD_EFFECT_TYPE_NONE` # 0
--- | `CHROMA_MOUSEPAD_EFFECT_TYPE_SPECTRUMCYCLING` # 3
--- | `CHROMA_MOUSEPAD_EFFECT_TYPE_STATIC` # 4
--- | `CHROMA_MOUSEPAD_EFFECT_TYPE_WAVE` # 5

CHROMA_MOUSEPAD_EFFECT_TYPE_BREATHING = 1
CHROMA_MOUSEPAD_EFFECT_TYPE_CUSTOM = 2
CHROMA_MOUSEPAD_EFFECT_TYPE_INVALID = 6
CHROMA_MOUSEPAD_EFFECT_TYPE_NONE = 0
CHROMA_MOUSEPAD_EFFECT_TYPE_SPECTRUMCYCLING = 3
CHROMA_MOUSEPAD_EFFECT_TYPE_STATIC = 4
CHROMA_MOUSEPAD_EFFECT_TYPE_WAVE = 5
