--- @meta ChromaKeyboardWaveEffectDirection

--- @alias ChromaKeyboardWaveEffectDirection integer
--- | `CHROMA_KEYBOARD_WAVE_EFFECT_DIRECTION_INVALID` # 3
--- | `CHROMA_KEYBOARD_WAVE_EFFECT_DIRECTION_LEFT_TO_RIGHT` # 1
--- | `CHROMA_KEYBOARD_WAVE_EFFECT_DIRECTION_NONE` # 0
--- | `CHROMA_KEYBOARD_WAVE_EFFECT_DIRECTION_RIGHT_TO_LEFT` # 2

CHROMA_KEYBOARD_WAVE_EFFECT_DIRECTION_INVALID = 3
CHROMA_KEYBOARD_WAVE_EFFECT_DIRECTION_LEFT_TO_RIGHT = 1
CHROMA_KEYBOARD_WAVE_EFFECT_DIRECTION_NONE = 0
CHROMA_KEYBOARD_WAVE_EFFECT_DIRECTION_RIGHT_TO_LEFT = 2
