--- @meta ChromaBlendMode

--- @alias ChromaBlendMode integer
--- | `CHROMA_BLEND_MODE_ADDITIVE` # 1
--- | `CHROMA_BLEND_MODE_COLOR_DODGE` # 2
--- | `CHROMA_BLEND_MODE_NORMAL` # 0

CHROMA_BLEND_MODE_ADDITIVE = 1
CHROMA_BLEND_MODE_COLOR_DODGE = 2
CHROMA_BLEND_MODE_NORMAL = 0
