--- @meta ChromaMouseWaveEffectDirection

--- @alias ChromaMouseWaveEffectDirection integer
--- | `CHROMA_MOUSE_WAVE_EFFECT_DIRECTION_BACK_TO_FRONT` # 1
--- | `CHROMA_MOUSE_WAVE_EFFECT_DIRECTION_FRONT_TO_BACK` # 0

CHROMA_MOUSE_WAVE_EFFECT_DIRECTION_BACK_TO_FRONT = 1
CHROMA_MOUSE_WAVE_EFFECT_DIRECTION_FRONT_TO_BACK = 0
