--- @meta ChromaMouseEffectType

--- @alias ChromaMouseEffectType integer
--- | `CHROMA_MOUSE_EFFECT_TYPE_BLINKING` # 1
--- | `CHROMA_MOUSE_EFFECT_TYPE_BREATHING` # 2
--- | `CHROMA_MOUSE_EFFECT_TYPE_CUSTOM` # 3
--- | `CHROMA_MOUSE_EFFECT_TYPE_CUSTOM2` # 8
--- | `CHROMA_MOUSE_EFFECT_TYPE_INVALID` # 9
--- | `CHROMA_MOUSE_EFFECT_TYPE_NONE` # 0
--- | `CHROMA_MOUSE_EFFECT_TYPE_REACTIVE` # 4
--- | `CHROMA_MOUSE_EFFECT_TYPE_SPECTRUMCYCLING` # 5
--- | `CHROMA_MOUSE_EFFECT_TYPE_STATIC` # 6
--- | `CHROMA_MOUSE_EFFECT_TYPE_WAVE` # 7

CHROMA_MOUSE_EFFECT_TYPE_BLINKING = 1
CHROMA_MOUSE_EFFECT_TYPE_BREATHING = 2
CHROMA_MOUSE_EFFECT_TYPE_CUSTOM = 3
CHROMA_MOUSE_EFFECT_TYPE_CUSTOM2 = 8
CHROMA_MOUSE_EFFECT_TYPE_INVALID = 9
CHROMA_MOUSE_EFFECT_TYPE_NONE = 0
CHROMA_MOUSE_EFFECT_TYPE_REACTIVE = 4
CHROMA_MOUSE_EFFECT_TYPE_SPECTRUMCYCLING = 5
CHROMA_MOUSE_EFFECT_TYPE_STATIC = 6
CHROMA_MOUSE_EFFECT_TYPE_WAVE = 7
