--- @meta ChromaKeyboardBreathingEffectType

--- @alias ChromaKeyboardBreathingEffectType integer
--- | `CHROMA_KEYBOARD_BREATHING_EFFECT_TYPE_INVALID` # 3
--- | `CHROMA_KEYBOARD_BREATHING_EFFECT_TYPE_RANDOM_COLORS` # 2
--- | `CHROMA_KEYBOARD_BREATHING_EFFECT_TYPE_TWO_COLORS` # 1

CHROMA_KEYBOARD_BREATHING_EFFECT_TYPE_INVALID = 3
CHROMA_KEYBOARD_BREATHING_EFFECT_TYPE_RANDOM_COLORS = 2
CHROMA_KEYBOARD_BREATHING_EFFECT_TYPE_TWO_COLORS = 1
