--- @meta ChromaKeypadBreathingEffectType

--- @alias ChromaKeypadBreathingEffectType integer
--- | `CHROMA_KEYPAD_BREATHING_EFFECT_TYPE_INVALID` # 3
--- | `CHROMA_KEYPAD_BREATHING_EFFECT_TYPE_RANDOM_COLORS` # 2
--- | `CHROMA_KEYPAD_BREATHING_EFFECT_TYPE_TWO_COLORS` # 1

CHROMA_KEYPAD_BREATHING_EFFECT_TYPE_INVALID = 3
CHROMA_KEYPAD_BREATHING_EFFECT_TYPE_RANDOM_COLORS = 2
CHROMA_KEYPAD_BREATHING_EFFECT_TYPE_TWO_COLORS = 1
