--- @meta ChromaMouseReactiveEffectDuration

--- @alias ChromaMouseReactiveEffectDuration integer
--- | `CHROMA_MOUSE_REACTIVE_EFFECT_DURATION_LONG` # 3
--- | `CHROMA_MOUSE_REACTIVE_EFFECT_DURATION_MEDIUM` # 2
--- | `CHROMA_MOUSE_REACTIVE_EFFECT_DURATION_NONE` # 0
--- | `CHROMA_MOUSE_REACTIVE_EFFECT_DURATION_SHORT` # 1

CHROMA_MOUSE_REACTIVE_EFFECT_DURATION_LONG = 3
CHROMA_MOUSE_REACTIVE_EFFECT_DURATION_MEDIUM = 2
CHROMA_MOUSE_REACTIVE_EFFECT_DURATION_NONE = 0
CHROMA_MOUSE_REACTIVE_EFFECT_DURATION_SHORT = 1
