--- @meta ChromaKeypadEffectType

--- @alias ChromaKeypadEffectType integer
--- | `CHROMA_KEYPAD_EFFECT_TYPE_BREATHING` # 1
--- | `CHROMA_KEYPAD_EFFECT_TYPE_CUSTOM` # 2
--- | `CHROMA_KEYPAD_EFFECT_TYPE_INVALID` # 7
--- | `CHROMA_KEYPAD_EFFECT_TYPE_NONE` # 0
--- | `CHROMA_KEYPAD_EFFECT_TYPE_REACTIVE` # 3
--- | `CHROMA_KEYPAD_EFFECT_TYPE_SPECTRUMCYCLING` # 4
--- | `CHROMA_KEYPAD_EFFECT_TYPE_STATIC` # 5
--- | `CHROMA_KEYPAD_EFFECT_TYPE_WAVE` # 6

CHROMA_KEYPAD_EFFECT_TYPE_BREATHING = 1
CHROMA_KEYPAD_EFFECT_TYPE_CUSTOM = 2
CHROMA_KEYPAD_EFFECT_TYPE_INVALID = 7
CHROMA_KEYPAD_EFFECT_TYPE_NONE = 0
CHROMA_KEYPAD_EFFECT_TYPE_REACTIVE = 3
CHROMA_KEYPAD_EFFECT_TYPE_SPECTRUMCYCLING = 4
CHROMA_KEYPAD_EFFECT_TYPE_STATIC = 5
CHROMA_KEYPAD_EFFECT_TYPE_WAVE = 6
