--- @meta ChromaCustomEffectType

--- @alias ChromaCustomEffectType integer
--- | `CHROMA_CUSTOM_EFFECT_TYPE_RING` # 2
--- | `CHROMA_CUSTOM_EFFECT_TYPE_SINGLE_COLOR` # 0
--- | `CHROMA_CUSTOM_EFFECT_TYPE_SINGLE_COLOR_FADING` # 1

CHROMA_CUSTOM_EFFECT_TYPE_RING = 2
CHROMA_CUSTOM_EFFECT_TYPE_SINGLE_COLOR = 0
CHROMA_CUSTOM_EFFECT_TYPE_SINGLE_COLOR_FADING = 1
