--- @meta ChromaKeyboardEffectType

--- @alias ChromaKeyboardEffectType integer
--- | `CHROMA_KEYBOARD_EFFECT_TYPE_BREATHING` # 1
--- | `CHROMA_KEYBOARD_EFFECT_TYPE_CUSTOM` # 2
--- | `CHROMA_KEYBOARD_EFFECT_TYPE_CUSTOM_KEY` # 8
--- | `CHROMA_KEYBOARD_EFFECT_TYPE_INVALID` # 9
--- | `CHROMA_KEYBOARD_EFFECT_TYPE_NONE` # 0
--- | `CHROMA_KEYBOARD_EFFECT_TYPE_REACTIVE` # 3
--- | `CHROMA_KEYBOARD_EFFECT_TYPE_RESERVED` # 7
--- | `CHROMA_KEYBOARD_EFFECT_TYPE_SPECTRUMCYCLING` # 5
--- | `CHROMA_KEYBOARD_EFFECT_TYPE_STATIC` # 4
--- | `CHROMA_KEYBOARD_EFFECT_TYPE_WAVE` # 6

CHROMA_KEYBOARD_EFFECT_TYPE_BREATHING = 1
CHROMA_KEYBOARD_EFFECT_TYPE_CUSTOM = 2
CHROMA_KEYBOARD_EFFECT_TYPE_CUSTOM_KEY = 8
CHROMA_KEYBOARD_EFFECT_TYPE_INVALID = 9
CHROMA_KEYBOARD_EFFECT_TYPE_NONE = 0
CHROMA_KEYBOARD_EFFECT_TYPE_REACTIVE = 3
CHROMA_KEYBOARD_EFFECT_TYPE_RESERVED = 7
CHROMA_KEYBOARD_EFFECT_TYPE_SPECTRUMCYCLING = 5
CHROMA_KEYBOARD_EFFECT_TYPE_STATIC = 4
CHROMA_KEYBOARD_EFFECT_TYPE_WAVE = 6
