--- @meta ChromaCustomEffectGridStyle

--- @alias ChromaCustomEffectGridStyle integer
--- | `CHROMA_CUSTOM_EFFECT_GRID_STYLE_ANIMATED` # 2
--- | `CHROMA_CUSTOM_EFFECT_GRID_STYLE_FULL` # 1
--- | `CHROMA_CUSTOM_EFFECT_GRID_STYLE_STATIC_CELLS` # 0

CHROMA_CUSTOM_EFFECT_GRID_STYLE_ANIMATED = 2
CHROMA_CUSTOM_EFFECT_GRID_STYLE_FULL = 1
CHROMA_CUSTOM_EFFECT_GRID_STYLE_STATIC_CELLS = 0
