--- @meta ChromaHeadsetEffectType

--- @alias ChromaHeadsetEffectType integer
--- | `CHROMA_HEADSET_EFFECT_TYPE_BREATHING` # 2
--- | `CHROMA_HEADSET_EFFECT_TYPE_CUSTOM` # 4
--- | `CHROMA_HEADSET_EFFECT_TYPE_INVALID` # 5
--- | `CHROMA_HEADSET_EFFECT_TYPE_NONE` # 0
--- | `CHROMA_HEADSET_EFFECT_TYPE_SPECTRUMCYCLING` # 3
--- | `CHROMA_HEADSET_EFFECT_TYPE_STATIC` # 1

CHROMA_HEADSET_EFFECT_TYPE_BREATHING = 2
CHROMA_HEADSET_EFFECT_TYPE_CUSTOM = 4
CHROMA_HEADSET_EFFECT_TYPE_INVALID = 5
CHROMA_HEADSET_EFFECT_TYPE_NONE = 0
CHROMA_HEADSET_EFFECT_TYPE_SPECTRUMCYCLING = 3
CHROMA_HEADSET_EFFECT_TYPE_STATIC = 1
