--- @meta ChromaKeyboardReactiveEffectDuration

--- @alias ChromaKeyboardReactiveEffectDuration integer
--- | `CHROMA_KEYBOARD_REACTIVE_EFFECT_DURATION_INVALID` # 4
--- | `CHROMA_KEYBOARD_REACTIVE_EFFECT_DURATION_LONG` # 3
--- | `CHROMA_KEYBOARD_REACTIVE_EFFECT_DURATION_MEDIUM` # 2
--- | `CHROMA_KEYBOARD_REACTIVE_EFFECT_DURATION_NONE` # 0
--- | `CHROMA_KEYBOARD_REACTIVE_EFFECT_DURATION_SHORT` # 1

CHROMA_KEYBOARD_REACTIVE_EFFECT_DURATION_INVALID = 4
CHROMA_KEYBOARD_REACTIVE_EFFECT_DURATION_LONG = 3
CHROMA_KEYBOARD_REACTIVE_EFFECT_DURATION_MEDIUM = 2
CHROMA_KEYBOARD_REACTIVE_EFFECT_DURATION_NONE = 0
CHROMA_KEYBOARD_REACTIVE_EFFECT_DURATION_SHORT = 1
