--- @meta ChromaDeviceType

--- @alias ChromaDeviceType integer
--- | `CHROMA_DEVICE_TYPE_HEADSET` # 3
--- | `CHROMA_DEVICE_TYPE_INVALID` # 7
--- | `CHROMA_DEVICE_TYPE_KEYBOARD` # 1
--- | `CHROMA_DEVICE_TYPE_KEYPAD` # 5
--- | `CHROMA_DEVICE_TYPE_MOUSE` # 2
--- | `CHROMA_DEVICE_TYPE_MOUSEPAD` # 4
--- | `CHROMA_DEVICE_TYPE_SYSTEM` # 6

CHROMA_DEVICE_TYPE_HEADSET = 3
CHROMA_DEVICE_TYPE_INVALID = 7
CHROMA_DEVICE_TYPE_KEYBOARD = 1
CHROMA_DEVICE_TYPE_KEYPAD = 5
CHROMA_DEVICE_TYPE_MOUSE = 2
CHROMA_DEVICE_TYPE_MOUSEPAD = 4
CHROMA_DEVICE_TYPE_SYSTEM = 6
