--- @meta ChromaMouseBreathingEffectType

--- @alias ChromaMouseBreathingEffectType integer
--- | `CHROMA_MOUSE_BREATHING_EFFECT_TYPE_INVALID` # 4
--- | `CHROMA_MOUSE_BREATHING_EFFECT_TYPE_ONE_COLOR` # 1
--- | `CHROMA_MOUSE_BREATHING_EFFECT_TYPE_RANDOM_COLORS` # 3
--- | `CHROMA_MOUSE_BREATHING_EFFECT_TYPE_TWO_COLORS` # 2

CHROMA_MOUSE_BREATHING_EFFECT_TYPE_INVALID = 4
CHROMA_MOUSE_BREATHING_EFFECT_TYPE_ONE_COLOR = 1
CHROMA_MOUSE_BREATHING_EFFECT_TYPE_RANDOM_COLORS = 3
CHROMA_MOUSE_BREATHING_EFFECT_TYPE_TWO_COLORS = 2
