--- @meta ChromaKeypadReactiveEffectDuration

--- @alias ChromaKeypadReactiveEffectDuration integer
--- | `CHROMA_KEYPAD_REACTIVE_EFFECT_DURATION_INVALID` # 4
--- | `CHROMA_KEYPAD_REACTIVE_EFFECT_DURATION_LONG` # 3
--- | `CHROMA_KEYPAD_REACTIVE_EFFECT_DURATION_MEDIUM` # 2
--- | `CHROMA_KEYPAD_REACTIVE_EFFECT_DURATION_NONE` # 0
--- | `CHROMA_KEYPAD_REACTIVE_EFFECT_DURATION_SHORT` # 1

CHROMA_KEYPAD_REACTIVE_EFFECT_DURATION_INVALID = 4
CHROMA_KEYPAD_REACTIVE_EFFECT_DURATION_LONG = 3
CHROMA_KEYPAD_REACTIVE_EFFECT_DURATION_MEDIUM = 2
CHROMA_KEYPAD_REACTIVE_EFFECT_DURATION_NONE = 0
CHROMA_KEYPAD_REACTIVE_EFFECT_DURATION_SHORT = 1
