--- @meta ClaimRewardResult

--- @alias ClaimRewardResult integer
--- | `CLAIM_REWARD_RESULT_CHOICE_INVALID_DEFS` # 11
--- | `CLAIM_REWARD_RESULT_CHOICE_INVALID_TYPE` # 12
--- | `CLAIM_REWARD_RESULT_CHOICE_MISSING` # 10
--- | `CLAIM_REWARD_RESULT_FAILED_REQ` # 2
--- | `CLAIM_REWARD_RESULT_INVALID` # 0
--- | `CLAIM_REWARD_RESULT_INVALID_CHOICE` # 9
--- | `CLAIM_REWARD_RESULT_INVALID_LEVEL` # 14
--- | `CLAIM_REWARD_RESULT_ITEM_INVALID_DEFS` # 4
--- | `CLAIM_REWARD_RESULT_ITEM_INVALID_QUANTITY` # 7
--- | `CLAIM_REWARD_RESULT_ITEM_INVALID_REQUIRED_LEVEL` # 6
--- | `CLAIM_REWARD_RESULT_ITEM_NOT_ENOUGH_SPACE` # 5
--- | `CLAIM_REWARD_RESULT_ITEM_UNIQUENESS_FAILURE` # 8
--- | `CLAIM_REWARD_RESULT_NO_DAILY_LOGIN_REWARD_FOUND` # 13
--- | `CLAIM_REWARD_RESULT_NO_PENDING_REWARD` # 3
--- | `CLAIM_REWARD_RESULT_SUCCESS` # 1

CLAIM_REWARD_RESULT_CHOICE_INVALID_DEFS = 11
CLAIM_REWARD_RESULT_CHOICE_INVALID_TYPE = 12
CLAIM_REWARD_RESULT_CHOICE_MISSING = 10
CLAIM_REWARD_RESULT_FAILED_REQ = 2
CLAIM_REWARD_RESULT_INVALID = 0
CLAIM_REWARD_RESULT_INVALID_CHOICE = 9
CLAIM_REWARD_RESULT_INVALID_LEVEL = 14
CLAIM_REWARD_RESULT_ITEM_INVALID_DEFS = 4
CLAIM_REWARD_RESULT_ITEM_INVALID_QUANTITY = 7
CLAIM_REWARD_RESULT_ITEM_INVALID_REQUIRED_LEVEL = 6
CLAIM_REWARD_RESULT_ITEM_NOT_ENOUGH_SPACE = 5
CLAIM_REWARD_RESULT_ITEM_UNIQUENESS_FAILURE = 8
CLAIM_REWARD_RESULT_NO_DAILY_LOGIN_REWARD_FOUND = 13
CLAIM_REWARD_RESULT_NO_PENDING_REWARD = 3
CLAIM_REWARD_RESULT_SUCCESS = 1
