--- @meta ClaimKeepResultType

--- @alias ClaimKeepResultType integer
--- | `CLAIM_KEEP_RESULT_TYPE_CAMPAIGN_NOT_READY` # 4
--- | `CLAIM_KEEP_RESULT_TYPE_DUPLICATE_CLAIM_IN_PROGRESS` # 8
--- | `CLAIM_KEEP_RESULT_TYPE_GUILD_ALREADY_HAS_KEEP` # 16
--- | `CLAIM_KEEP_RESULT_TYPE_INSUFFICIENT_PERMISSION` # 11
--- | `CLAIM_KEEP_RESULT_TYPE_INTERNAL_ERROR` # 12
--- | `CLAIM_KEEP_RESULT_TYPE_INVALID_WORLD` # 3
--- | `CLAIM_KEEP_RESULT_TYPE_KEEP_ALREADY_CLAIMED` # 7
--- | `CLAIM_KEEP_RESULT_TYPE_KEEP_DOES_NOT_EXIST` # 5
--- | `CLAIM_KEEP_RESULT_TYPE_KEEP_NOT_CLAIMABLE` # 6
--- | `CLAIM_KEEP_RESULT_TYPE_KEEP_NOT_OWNED_BY_ALLIANCE` # 14
--- | `CLAIM_KEEP_RESULT_TYPE_KEEP_NOT_OWNED_BY_GUILD_ALLIANCE` # 15
--- | `CLAIM_KEEP_RESULT_TYPE_NOT_IN_CAMPAIGN` # 2
--- | `CLAIM_KEEP_RESULT_TYPE_NOT_IN_GUILD` # 10
--- | `CLAIM_KEEP_RESULT_TYPE_SOCIAL_DISABLED` # 9
--- | `CLAIM_KEEP_RESULT_TYPE_STILL_ON_COOLDOWN` # 13
--- | `CLAIM_KEEP_RESULT_TYPE_SUCCESS` # 1

CLAIM_KEEP_RESULT_TYPE_CAMPAIGN_NOT_READY = 4
CLAIM_KEEP_RESULT_TYPE_DUPLICATE_CLAIM_IN_PROGRESS = 8
CLAIM_KEEP_RESULT_TYPE_GUILD_ALREADY_HAS_KEEP = 16
CLAIM_KEEP_RESULT_TYPE_INSUFFICIENT_PERMISSION = 11
CLAIM_KEEP_RESULT_TYPE_INTERNAL_ERROR = 12
CLAIM_KEEP_RESULT_TYPE_INVALID_WORLD = 3
CLAIM_KEEP_RESULT_TYPE_KEEP_ALREADY_CLAIMED = 7
CLAIM_KEEP_RESULT_TYPE_KEEP_DOES_NOT_EXIST = 5
CLAIM_KEEP_RESULT_TYPE_KEEP_NOT_CLAIMABLE = 6
CLAIM_KEEP_RESULT_TYPE_KEEP_NOT_OWNED_BY_ALLIANCE = 14
CLAIM_KEEP_RESULT_TYPE_KEEP_NOT_OWNED_BY_GUILD_ALLIANCE = 15
CLAIM_KEEP_RESULT_TYPE_NOT_IN_CAMPAIGN = 2
CLAIM_KEEP_RESULT_TYPE_NOT_IN_GUILD = 10
CLAIM_KEEP_RESULT_TYPE_SOCIAL_DISABLED = 9
CLAIM_KEEP_RESULT_TYPE_STILL_ON_COOLDOWN = 13
CLAIM_KEEP_RESULT_TYPE_SUCCESS = 1
