--- @meta ClientInteractResult

--- @alias ClientInteractResult integer
--- | `CLIENT_INTERACT_RESULT_ANTIQUITY_DIGGING_NO_INVENTORY_SPACE` # 18
--- | `CLIENT_INTERACT_RESULT_CANT_SWIM_AND_FISH` # 7
--- | `CLIENT_INTERACT_RESULT_CANT_WHILE_FALLING` # 25
--- | `CLIENT_INTERACT_RESULT_CANT_WHILE_SWIMMING` # 24
--- | `CLIENT_INTERACT_RESULT_DONT_OWN_HOUSE_BANK` # 17
--- | `CLIENT_INTERACT_RESULT_FAIL_DOOR_REQ` # 8
--- | `CLIENT_INTERACT_RESULT_FEARFUL_VAMPIRE` # 20
--- | `CLIENT_INTERACT_RESULT_FEARFUL_WEREWOLF` # 19
--- | `CLIENT_INTERACT_RESULT_FLAVOR_NPC` # 5
--- | `CLIENT_INTERACT_RESULT_GENERIC_ERROR` # 23
--- | `CLIENT_INTERACT_RESULT_INTERACT_DISABLED` # 16
--- | `CLIENT_INTERACT_RESULT_IN_COMBAT` # 2
--- | `CLIENT_INTERACT_RESULT_LOCK_TOO_DIFFICULT` # 3
--- | `CLIENT_INTERACT_RESULT_NO_LOCKPICKS` # 4
--- | `CLIENT_INTERACT_RESULT_NO_LURE` # 6
--- | `CLIENT_INTERACT_RESULT_PICKPOCKET_NO_INVENTORY_SPACE` # 1
--- | `CLIENT_INTERACT_RESULT_PICKPOCKET_ON_COOLDOWN` # 11
--- | `CLIENT_INTERACT_RESULT_PICKPOCKET_OUT_OF_POSITION` # 10
--- | `CLIENT_INTERACT_RESULT_PICKPOCKET_TOO_FAR` # 9
--- | `CLIENT_INTERACT_RESULT_SCRIBING_DISABLED` # 27
--- | `CLIENT_INTERACT_RESULT_SCRIBING_INTERNAL_ERROR` # 28
--- | `CLIENT_INTERACT_RESULT_SHUNNED` # 13
--- | `CLIENT_INTERACT_RESULT_SHUNNED_FEARFUL_VAMPIRE` # 22
--- | `CLIENT_INTERACT_RESULT_SHUNNED_FEARFUL_WEREWOLF` # 21
--- | `CLIENT_INTERACT_RESULT_STEALING_PLACED_PREVENTED` # 26
--- | `CLIENT_INTERACT_RESULT_SUCCESS` # 0
--- | `CLIENT_INTERACT_RESULT_SUSPICIOUS` # 12
--- | `CLIENT_INTERACT_RESULT_WEREWOLF` # 14
--- | `CLIENT_INTERACT_RESULT_WEREWOLF_UNABLE_TO_CRAFT` # 15

CLIENT_INTERACT_RESULT_ANTIQUITY_DIGGING_NO_INVENTORY_SPACE = 18
CLIENT_INTERACT_RESULT_CANT_SWIM_AND_FISH = 7
CLIENT_INTERACT_RESULT_CANT_WHILE_FALLING = 25
CLIENT_INTERACT_RESULT_CANT_WHILE_SWIMMING = 24
CLIENT_INTERACT_RESULT_DONT_OWN_HOUSE_BANK = 17
CLIENT_INTERACT_RESULT_FAIL_DOOR_REQ = 8
CLIENT_INTERACT_RESULT_FEARFUL_VAMPIRE = 20
CLIENT_INTERACT_RESULT_FEARFUL_WEREWOLF = 19
CLIENT_INTERACT_RESULT_FLAVOR_NPC = 5
CLIENT_INTERACT_RESULT_GENERIC_ERROR = 23
CLIENT_INTERACT_RESULT_INTERACT_DISABLED = 16
CLIENT_INTERACT_RESULT_IN_COMBAT = 2
CLIENT_INTERACT_RESULT_LOCK_TOO_DIFFICULT = 3
CLIENT_INTERACT_RESULT_NO_LOCKPICKS = 4
CLIENT_INTERACT_RESULT_NO_LURE = 6
CLIENT_INTERACT_RESULT_PICKPOCKET_NO_INVENTORY_SPACE = 1
CLIENT_INTERACT_RESULT_PICKPOCKET_ON_COOLDOWN = 11
CLIENT_INTERACT_RESULT_PICKPOCKET_OUT_OF_POSITION = 10
CLIENT_INTERACT_RESULT_PICKPOCKET_TOO_FAR = 9
CLIENT_INTERACT_RESULT_SCRIBING_DISABLED = 27
CLIENT_INTERACT_RESULT_SCRIBING_INTERNAL_ERROR = 28
CLIENT_INTERACT_RESULT_SHUNNED = 13
CLIENT_INTERACT_RESULT_SHUNNED_FEARFUL_VAMPIRE = 22
CLIENT_INTERACT_RESULT_SHUNNED_FEARFUL_WEREWOLF = 21
CLIENT_INTERACT_RESULT_STEALING_PLACED_PREVENTED = 26
CLIENT_INTERACT_RESULT_SUCCESS = 0
CLIENT_INTERACT_RESULT_SUSPICIOUS = 12
CLIENT_INTERACT_RESULT_WEREWOLF = 14
CLIENT_INTERACT_RESULT_WEREWOLF_UNABLE_TO_CRAFT = 15
