--- @meta ClutterQuality

--- @alias ClutterQuality integer
--- | `CLUTTER_QUALITY_HIGH` # 3
--- | `CLUTTER_QUALITY_LOW` # 1
--- | `CLUTTER_QUALITY_MEDIUM` # 2
--- | `CLUTTER_QUALITY_OFF` # 0
--- | `CLUTTER_QUALITY_ULTRA` # 4

CLUTTER_QUALITY_HIGH = 3
CLUTTER_QUALITY_LOW = 1
CLUTTER_QUALITY_MEDIUM = 2
CLUTTER_QUALITY_OFF = 0
CLUTTER_QUALITY_ULTRA = 4
