--- @meta CollectibleCategorySpecialization

--- @alias CollectibleCategorySpecialization integer
--- | `COLLECTIBLE_CATEGORY_SPECIALIZATION_DLC` # 1
--- | `COLLECTIBLE_CATEGORY_SPECIALIZATION_HOUSING` # 2
--- | `COLLECTIBLE_CATEGORY_SPECIALIZATION_NONE` # 0
--- | `COLLECTIBLE_CATEGORY_SPECIALIZATION_OUTFIT_STYLES` # 3
--- | `COLLECTIBLE_CATEGORY_SPECIALIZATION_TRIBUTE_PATRONS` # 4

COLLECTIBLE_CATEGORY_SPECIALIZATION_DLC = 1
COLLECTIBLE_CATEGORY_SPECIALIZATION_HOUSING = 2
COLLECTIBLE_CATEGORY_SPECIALIZATION_NONE = 0
COLLECTIBLE_CATEGORY_SPECIALIZATION_OUTFIT_STYLES = 3
COLLECTIBLE_CATEGORY_SPECIALIZATION_TRIBUTE_PATRONS = 4
