--- @meta CollectibleCategoryType

--- @alias CollectibleCategoryType integer
--- | `COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE` # 30
--- | `COLLECTIBLE_CATEGORY_TYPE_ABILITY_SKIN` # 23
--- | `COLLECTIBLE_CATEGORY_TYPE_ACCOUNT_SERVICE` # 7
--- | `COLLECTIBLE_CATEGORY_TYPE_ACCOUNT_UPGRADE` # 6
--- | `COLLECTIBLE_CATEGORY_TYPE_ASSISTANT` # 8
--- | `COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING` # 18
--- | `COLLECTIBLE_CATEGORY_TYPE_CHAPTER` # 22
--- | `COLLECTIBLE_CATEGORY_TYPE_COMBINATION_FRAGMENT` # 26
--- | `COLLECTIBLE_CATEGORY_TYPE_COMPANION` # 27
--- | `COLLECTIBLE_CATEGORY_TYPE_COSTUME` # 4
--- | `COLLECTIBLE_CATEGORY_TYPE_DLC` # 1
--- | `COLLECTIBLE_CATEGORY_TYPE_EMOTE` # 21
--- | `COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY` # 15
--- | `COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS` # 14
--- | `COLLECTIBLE_CATEGORY_TYPE_FURNITURE` # 20
--- | `COLLECTIBLE_CATEGORY_TYPE_HAIR` # 13
--- | `COLLECTIBLE_CATEGORY_TYPE_HAT` # 10
--- | `COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING` # 17
--- | `COLLECTIBLE_CATEGORY_TYPE_HOUSE` # 19
--- | `COLLECTIBLE_CATEGORY_TYPE_HOUSE_BANK` # 25
--- | `COLLECTIBLE_CATEGORY_TYPE_INVALID` # 0
--- | `COLLECTIBLE_CATEGORY_TYPE_MEMENTO` # 5
--- | `COLLECTIBLE_CATEGORY_TYPE_MOUNT` # 2
--- | `COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE` # 24
--- | `COLLECTIBLE_CATEGORY_TYPE_PERSONALITY` # 9
--- | `COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY` # 16
--- | `COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE` # 29
--- | `COLLECTIBLE_CATEGORY_TYPE_POLYMORPH` # 12
--- | `COLLECTIBLE_CATEGORY_TYPE_SKIN` # 11
--- | `COLLECTIBLE_CATEGORY_TYPE_TRIBUTE_PATRON` # 28
--- | `COLLECTIBLE_CATEGORY_TYPE_VANITY_PET` # 3

COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE = 30
COLLECTIBLE_CATEGORY_TYPE_ABILITY_SKIN = 23
COLLECTIBLE_CATEGORY_TYPE_ACCOUNT_SERVICE = 7
COLLECTIBLE_CATEGORY_TYPE_ACCOUNT_UPGRADE = 6
COLLECTIBLE_CATEGORY_TYPE_ASSISTANT = 8
COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING = 18
COLLECTIBLE_CATEGORY_TYPE_CHAPTER = 22
COLLECTIBLE_CATEGORY_TYPE_COMBINATION_FRAGMENT = 26
COLLECTIBLE_CATEGORY_TYPE_COMPANION = 27
COLLECTIBLE_CATEGORY_TYPE_COSTUME = 4
COLLECTIBLE_CATEGORY_TYPE_DLC = 1
COLLECTIBLE_CATEGORY_TYPE_EMOTE = 21
COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY = 15
COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS = 14
COLLECTIBLE_CATEGORY_TYPE_FURNITURE = 20
COLLECTIBLE_CATEGORY_TYPE_HAIR = 13
COLLECTIBLE_CATEGORY_TYPE_HAT = 10
COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING = 17
COLLECTIBLE_CATEGORY_TYPE_HOUSE = 19
COLLECTIBLE_CATEGORY_TYPE_HOUSE_BANK = 25
COLLECTIBLE_CATEGORY_TYPE_INVALID = 0
COLLECTIBLE_CATEGORY_TYPE_MEMENTO = 5
COLLECTIBLE_CATEGORY_TYPE_MOUNT = 2
COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE = 24
COLLECTIBLE_CATEGORY_TYPE_PERSONALITY = 9
COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY = 16
COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE = 29
COLLECTIBLE_CATEGORY_TYPE_POLYMORPH = 12
COLLECTIBLE_CATEGORY_TYPE_SKIN = 11
COLLECTIBLE_CATEGORY_TYPE_TRIBUTE_PATRON = 28
COLLECTIBLE_CATEGORY_TYPE_VANITY_PET = 3
