--- @meta CollectibleItemType

--- @alias CollectibleItemType integer
--- | `COLLECTIBLE_ITEM_TYPE_FISH` # 1
--- | `COLLECTIBLE_ITEM_TYPE_NONE` # 0
--- | `COLLECTIBLE_ITEM_TYPE_TROPHY` # 2

COLLECTIBLE_ITEM_TYPE_FISH = 1
COLLECTIBLE_ITEM_TYPE_NONE = 0
COLLECTIBLE_ITEM_TYPE_TROPHY = 2
