--- @meta CollectibleAssociatedQuestState

--- @alias CollectibleAssociatedQuestState integer
--- | `COLLECTIBLE_ASSOCIATED_QUEST_STATE_ACCEPTED` # 2
--- | `COLLECTIBLE_ASSOCIATED_QUEST_STATE_COMPLETED` # 3
--- | `COLLECTIBLE_ASSOCIATED_QUEST_STATE_INACTIVE` # 1
--- | `COLLECTIBLE_ASSOCIATED_QUEST_STATE_NO_QUEST` # 0

COLLECTIBLE_ASSOCIATED_QUEST_STATE_ACCEPTED = 2
COLLECTIBLE_ASSOCIATED_QUEST_STATE_COMPLETED = 3
COLLECTIBLE_ASSOCIATED_QUEST_STATE_INACTIVE = 1
COLLECTIBLE_ASSOCIATED_QUEST_STATE_NO_QUEST = 0
