--- @meta CollectibleUnlockState

--- @alias CollectibleUnlockState integer
--- | `COLLECTIBLE_UNLOCK_STATE_LOCKED` # 0
--- | `COLLECTIBLE_UNLOCK_STATE_UNLOCKED_OWNED` # 2
--- | `COLLECTIBLE_UNLOCK_STATE_UNLOCKED_SUBSCRIPTION` # 1
--- | `COLLECTIBLE_UNLOCK_STATE_UNLOCKED_TRIAL` # 3

COLLECTIBLE_UNLOCK_STATE_LOCKED = 0
COLLECTIBLE_UNLOCK_STATE_UNLOCKED_OWNED = 2
COLLECTIBLE_UNLOCK_STATE_UNLOCKED_SUBSCRIPTION = 1
COLLECTIBLE_UNLOCK_STATE_UNLOCKED_TRIAL = 3
