--- @meta CollectibleRestrictionType

--- @alias CollectibleRestrictionType integer
--- | `COLLECTIBLE_RESTRICTION_TYPE_ALLIANCE` # 2
--- | `COLLECTIBLE_RESTRICTION_TYPE_CLASS` # 3
--- | `COLLECTIBLE_RESTRICTION_TYPE_GENDER` # 0
--- | `COLLECTIBLE_RESTRICTION_TYPE_RACE` # 1

COLLECTIBLE_RESTRICTION_TYPE_ALLIANCE = 2
COLLECTIBLE_RESTRICTION_TYPE_CLASS = 3
COLLECTIBLE_RESTRICTION_TYPE_GENDER = 0
COLLECTIBLE_RESTRICTION_TYPE_RACE = 1
