--- @meta CollectibleHideMode

--- @alias CollectibleHideMode integer
--- | `COLLECTIBLE_HIDE_MODE_ALWAYS` # 1
--- | `COLLECTIBLE_HIDE_MODE_NONE` # 0
--- | `COLLECTIBLE_HIDE_MODE_WHEN_LOCKED` # 2
--- | `COLLECTIBLE_HIDE_MODE_WHEN_LOCKED_REQUIREMENT` # 3

COLLECTIBLE_HIDE_MODE_ALWAYS = 1
COLLECTIBLE_HIDE_MODE_NONE = 0
COLLECTIBLE_HIDE_MODE_WHEN_LOCKED = 2
COLLECTIBLE_HIDE_MODE_WHEN_LOCKED_REQUIREMENT = 3
