--- @meta CollectibleUsageBlockReason

--- @alias CollectibleUsageBlockReason integer
--- | `COLLECTIBLE_USAGE_BLOCK_REASON_ACTIVE_DIG_SITE_REQUIRED` # 16
--- | `COLLECTIBLE_USAGE_BLOCK_REASON_BLACKLISTED` # 15
--- | `COLLECTIBLE_USAGE_BLOCK_REASON_BLOCKED_BY_LEADERBOARD_EVENT` # 32
--- | `COLLECTIBLE_USAGE_BLOCK_REASON_BLOCKED_BY_SUBZONE` # 13
--- | `COLLECTIBLE_USAGE_BLOCK_REASON_BLOCKED_BY_ZONE` # 1
--- | `COLLECTIBLE_USAGE_BLOCK_REASON_CATEGORY_REQUIREMENT_FAILED` # 17
--- | `COLLECTIBLE_USAGE_BLOCK_REASON_COLLECTIBLE_ALREADY_QUEUED` # 18
--- | `COLLECTIBLE_USAGE_BLOCK_REASON_COMPANION_INTRO_QUEST` # 26
--- | `COLLECTIBLE_USAGE_BLOCK_REASON_COMPANION_MENU_REQUIRED` # 19
--- | `COLLECTIBLE_USAGE_BLOCK_REASON_DEAD` # 3
--- | `COLLECTIBLE_USAGE_BLOCK_REASON_DEFAULT_ALREADY_ACTIVE` # 31
--- | `COLLECTIBLE_USAGE_BLOCK_REASON_DUELING` # 20
--- | `COLLECTIBLE_USAGE_BLOCK_REASON_GROUP_FULL` # 24
--- | `COLLECTIBLE_USAGE_BLOCK_REASON_HAS_PENDING_COMPANION` # 22
--- | `COLLECTIBLE_USAGE_BLOCK_REASON_INVALID_ALLIANCE` # 7
--- | `COLLECTIBLE_USAGE_BLOCK_REASON_INVALID_CLASS` # 10
--- | `COLLECTIBLE_USAGE_BLOCK_REASON_INVALID_COLLECTIBLE` # 4
--- | `COLLECTIBLE_USAGE_BLOCK_REASON_INVALID_GENDER` # 5
--- | `COLLECTIBLE_USAGE_BLOCK_REASON_INVALID_RACE` # 6
--- | `COLLECTIBLE_USAGE_BLOCK_REASON_IN_AIR` # 14
--- | `COLLECTIBLE_USAGE_BLOCK_REASON_IN_COMBAT` # 25
--- | `COLLECTIBLE_USAGE_BLOCK_REASON_IN_HIDEY_HOLE` # 21
--- | `COLLECTIBLE_USAGE_BLOCK_REASON_IN_WATER` # 2
--- | `COLLECTIBLE_USAGE_BLOCK_REASON_MAX_NUMBER_EQUIPPED` # 33
--- | `COLLECTIBLE_USAGE_BLOCK_REASON_MOUNT_IN_COMBAT` # 34
--- | `COLLECTIBLE_USAGE_BLOCK_REASON_NOT_BLOCKED` # 0
--- | `COLLECTIBLE_USAGE_BLOCK_REASON_ON_COOLDOWN` # 9
--- | `COLLECTIBLE_USAGE_BLOCK_REASON_ON_MOUNT` # 12
--- | `COLLECTIBLE_USAGE_BLOCK_REASON_PLACED_IN_HOUSE` # 8
--- | `COLLECTIBLE_USAGE_BLOCK_REASON_QUEST_FOLLOWER` # 29
--- | `COLLECTIBLE_USAGE_BLOCK_REASON_TARGET_REQUIRED` # 11
--- | `COLLECTIBLE_USAGE_BLOCK_REASON_TEMPORARILY_DISABLED` # 30
--- | `COLLECTIBLE_USAGE_BLOCK_REASON_UNACQUIRED_SKILL` # 35
--- | `COLLECTIBLE_USAGE_BLOCK_REASON_UNUSABLE_BY_COMPANION` # 23
--- | `COLLECTIBLE_USAGE_BLOCK_REASON_WORLD_BOSS` # 28
--- | `COLLECTIBLE_USAGE_BLOCK_REASON_WORLD_EVENT` # 27

COLLECTIBLE_USAGE_BLOCK_REASON_ACTIVE_DIG_SITE_REQUIRED = 16
COLLECTIBLE_USAGE_BLOCK_REASON_BLACKLISTED = 15
COLLECTIBLE_USAGE_BLOCK_REASON_BLOCKED_BY_LEADERBOARD_EVENT = 32
COLLECTIBLE_USAGE_BLOCK_REASON_BLOCKED_BY_SUBZONE = 13
COLLECTIBLE_USAGE_BLOCK_REASON_BLOCKED_BY_ZONE = 1
COLLECTIBLE_USAGE_BLOCK_REASON_CATEGORY_REQUIREMENT_FAILED = 17
COLLECTIBLE_USAGE_BLOCK_REASON_COLLECTIBLE_ALREADY_QUEUED = 18
COLLECTIBLE_USAGE_BLOCK_REASON_COMPANION_INTRO_QUEST = 26
COLLECTIBLE_USAGE_BLOCK_REASON_COMPANION_MENU_REQUIRED = 19
COLLECTIBLE_USAGE_BLOCK_REASON_DEAD = 3
COLLECTIBLE_USAGE_BLOCK_REASON_DEFAULT_ALREADY_ACTIVE = 31
COLLECTIBLE_USAGE_BLOCK_REASON_DUELING = 20
COLLECTIBLE_USAGE_BLOCK_REASON_GROUP_FULL = 24
COLLECTIBLE_USAGE_BLOCK_REASON_HAS_PENDING_COMPANION = 22
COLLECTIBLE_USAGE_BLOCK_REASON_INVALID_ALLIANCE = 7
COLLECTIBLE_USAGE_BLOCK_REASON_INVALID_CLASS = 10
COLLECTIBLE_USAGE_BLOCK_REASON_INVALID_COLLECTIBLE = 4
COLLECTIBLE_USAGE_BLOCK_REASON_INVALID_GENDER = 5
COLLECTIBLE_USAGE_BLOCK_REASON_INVALID_RACE = 6
COLLECTIBLE_USAGE_BLOCK_REASON_IN_AIR = 14
COLLECTIBLE_USAGE_BLOCK_REASON_IN_COMBAT = 25
COLLECTIBLE_USAGE_BLOCK_REASON_IN_HIDEY_HOLE = 21
COLLECTIBLE_USAGE_BLOCK_REASON_IN_WATER = 2
COLLECTIBLE_USAGE_BLOCK_REASON_MAX_NUMBER_EQUIPPED = 33
COLLECTIBLE_USAGE_BLOCK_REASON_MOUNT_IN_COMBAT = 34
COLLECTIBLE_USAGE_BLOCK_REASON_NOT_BLOCKED = 0
COLLECTIBLE_USAGE_BLOCK_REASON_ON_COOLDOWN = 9
COLLECTIBLE_USAGE_BLOCK_REASON_ON_MOUNT = 12
COLLECTIBLE_USAGE_BLOCK_REASON_PLACED_IN_HOUSE = 8
COLLECTIBLE_USAGE_BLOCK_REASON_QUEST_FOLLOWER = 29
COLLECTIBLE_USAGE_BLOCK_REASON_TARGET_REQUIRED = 11
COLLECTIBLE_USAGE_BLOCK_REASON_TEMPORARILY_DISABLED = 30
COLLECTIBLE_USAGE_BLOCK_REASON_UNACQUIRED_SKILL = 35
COLLECTIBLE_USAGE_BLOCK_REASON_UNUSABLE_BY_COMPANION = 23
COLLECTIBLE_USAGE_BLOCK_REASON_WORLD_BOSS = 28
COLLECTIBLE_USAGE_BLOCK_REASON_WORLD_EVENT = 27
