--- @meta CombatMechanicFlags

--- @alias CombatMechanicFlags integer
--- | `COMBAT_MECHANIC_FLAGS_DAEDRIC` # 64
--- | `COMBAT_MECHANIC_FLAGS_HEALTH` # 32
--- | `COMBAT_MECHANIC_FLAGS_MAGICKA` # 1
--- | `COMBAT_MECHANIC_FLAGS_MOUNT_STAMINA` # 16
--- | `COMBAT_MECHANIC_FLAGS_STAMINA` # 4
--- | `COMBAT_MECHANIC_FLAGS_ULTIMATE` # 8
--- | `COMBAT_MECHANIC_FLAGS_WEREWOLF` # 2

COMBAT_MECHANIC_FLAGS_DAEDRIC = 64
COMBAT_MECHANIC_FLAGS_HEALTH = 32
COMBAT_MECHANIC_FLAGS_MAGICKA = 1
COMBAT_MECHANIC_FLAGS_MOUNT_STAMINA = 16
COMBAT_MECHANIC_FLAGS_STAMINA = 4
COMBAT_MECHANIC_FLAGS_ULTIMATE = 8
COMBAT_MECHANIC_FLAGS_WEREWOLF = 2
