--- @meta CombatUnitType

--- @alias CombatUnitType integer
--- | `COMBAT_UNIT_TYPE_GROUP` # 3
--- | `COMBAT_UNIT_TYPE_NONE` # 0
--- | `COMBAT_UNIT_TYPE_OTHER` # 5
--- | `COMBAT_UNIT_TYPE_PLAYER` # 1
--- | `COMBAT_UNIT_TYPE_PLAYER_COMPANION` # 6
--- | `COMBAT_UNIT_TYPE_PLAYER_PET` # 2
--- | `COMBAT_UNIT_TYPE_TARGET_DUMMY` # 4

COMBAT_UNIT_TYPE_GROUP = 3
COMBAT_UNIT_TYPE_NONE = 0
COMBAT_UNIT_TYPE_OTHER = 5
COMBAT_UNIT_TYPE_PLAYER = 1
COMBAT_UNIT_TYPE_PLAYER_COMPANION = 6
COMBAT_UNIT_TYPE_PLAYER_PET = 2
COMBAT_UNIT_TYPE_TARGET_DUMMY = 4
