--- @meta CombatSetting

--- @alias CombatSetting integer
--- | `COMBAT_SETTING_ALLOW_COMPANION_AUTO_ULTIMATE` # 34
--- | `COMBAT_SETTING_CLAMP_GROUND_TARGET_ENABLED` # 25
--- | `COMBAT_SETTING_ENCOUNTER_LOG_APPEAR_ANONYMOUS` # 33
--- | `COMBAT_SETTING_MONSTER_TELLS_COLOR_SWAP_ENABLED` # 28
--- | `COMBAT_SETTING_MONSTER_TELLS_ENABLED` # 21
--- | `COMBAT_SETTING_MONSTER_TELLS_ENEMY_BRIGHTNESS` # 32
--- | `COMBAT_SETTING_MONSTER_TELLS_ENEMY_COLOR` # 31
--- | `COMBAT_SETTING_MONSTER_TELLS_FRIENDLY_BRIGHTNESS` # 30
--- | `COMBAT_SETTING_MONSTER_TELLS_FRIENDLY_COLOR` # 29
--- | `COMBAT_SETTING_PREVENT_ATTACKING_INNOCENTS` # 26
--- | `COMBAT_SETTING_QUICK_CAST_GROUND_ABILITIES` # 27
--- | `COMBAT_SETTING_ROLL_DODGE_DOUBLE_TAP` # 23
--- | `COMBAT_SETTING_ROLL_DODGE_WINDOW` # 22
--- | `COMBAT_SETTING_SCROLLING_COMBAT_TEXT_ENABLED` # 0
--- | `COMBAT_SETTING_SCT_INCOMING_DAMAGE_ENABLED` # 12
--- | `COMBAT_SETTING_SCT_INCOMING_DOT_ENABLED` # 13
--- | `COMBAT_SETTING_SCT_INCOMING_ENABLED` # 11
--- | `COMBAT_SETTING_SCT_INCOMING_HEALING_ENABLED` # 14
--- | `COMBAT_SETTING_SCT_INCOMING_HOT_ENABLED` # 15
--- | `COMBAT_SETTING_SCT_INCOMING_PET_DAMAGE_ENABLED` # 18
--- | `COMBAT_SETTING_SCT_INCOMING_PET_DOT_ENABLED` # 19
--- | `COMBAT_SETTING_SCT_INCOMING_POINT_GAINS_ENABLED` # 17
--- | `COMBAT_SETTING_SCT_INCOMING_STATUS_EFFECTS_ENABLED` # 16
--- | `COMBAT_SETTING_SCT_OUTGOING_DAMAGE_ENABLED` # 2
--- | `COMBAT_SETTING_SCT_OUTGOING_DOT_ENABLED` # 3
--- | `COMBAT_SETTING_SCT_OUTGOING_ENABLED` # 1
--- | `COMBAT_SETTING_SCT_OUTGOING_HEALING_ENABLED` # 4
--- | `COMBAT_SETTING_SCT_OUTGOING_HOT_ENABLED` # 5
--- | `COMBAT_SETTING_SCT_OUTGOING_PET_DAMAGE_ENABLED` # 7
--- | `COMBAT_SETTING_SCT_OUTGOING_PET_DOT_ENABLED` # 8
--- | `COMBAT_SETTING_SCT_OUTGOING_PET_HEALING_ENABLED` # 9
--- | `COMBAT_SETTING_SCT_OUTGOING_PET_HOT_ENABLED` # 10
--- | `COMBAT_SETTING_SCT_OUTGOING_STATUS_EFFECTS_ENABLED` # 6
--- | `COMBAT_SETTING_SCT_SHOW_OVER_HEAL` # 20
--- | `COMBAT_SETTING_USE_BATTLE_LEVEL` # 24

COMBAT_SETTING_ALLOW_COMPANION_AUTO_ULTIMATE = 34
COMBAT_SETTING_CLAMP_GROUND_TARGET_ENABLED = 25
COMBAT_SETTING_ENCOUNTER_LOG_APPEAR_ANONYMOUS = 33
COMBAT_SETTING_MONSTER_TELLS_COLOR_SWAP_ENABLED = 28
COMBAT_SETTING_MONSTER_TELLS_ENABLED = 21
COMBAT_SETTING_MONSTER_TELLS_ENEMY_BRIGHTNESS = 32
COMBAT_SETTING_MONSTER_TELLS_ENEMY_COLOR = 31
COMBAT_SETTING_MONSTER_TELLS_FRIENDLY_BRIGHTNESS = 30
COMBAT_SETTING_MONSTER_TELLS_FRIENDLY_COLOR = 29
COMBAT_SETTING_PREVENT_ATTACKING_INNOCENTS = 26
COMBAT_SETTING_QUICK_CAST_GROUND_ABILITIES = 27
COMBAT_SETTING_ROLL_DODGE_DOUBLE_TAP = 23
COMBAT_SETTING_ROLL_DODGE_WINDOW = 22
COMBAT_SETTING_SCROLLING_COMBAT_TEXT_ENABLED = 0
COMBAT_SETTING_SCT_INCOMING_DAMAGE_ENABLED = 12
COMBAT_SETTING_SCT_INCOMING_DOT_ENABLED = 13
COMBAT_SETTING_SCT_INCOMING_ENABLED = 11
COMBAT_SETTING_SCT_INCOMING_HEALING_ENABLED = 14
COMBAT_SETTING_SCT_INCOMING_HOT_ENABLED = 15
COMBAT_SETTING_SCT_INCOMING_PET_DAMAGE_ENABLED = 18
COMBAT_SETTING_SCT_INCOMING_PET_DOT_ENABLED = 19
COMBAT_SETTING_SCT_INCOMING_POINT_GAINS_ENABLED = 17
COMBAT_SETTING_SCT_INCOMING_STATUS_EFFECTS_ENABLED = 16
COMBAT_SETTING_SCT_OUTGOING_DAMAGE_ENABLED = 2
COMBAT_SETTING_SCT_OUTGOING_DOT_ENABLED = 3
COMBAT_SETTING_SCT_OUTGOING_ENABLED = 1
COMBAT_SETTING_SCT_OUTGOING_HEALING_ENABLED = 4
COMBAT_SETTING_SCT_OUTGOING_HOT_ENABLED = 5
COMBAT_SETTING_SCT_OUTGOING_PET_DAMAGE_ENABLED = 7
COMBAT_SETTING_SCT_OUTGOING_PET_DOT_ENABLED = 8
COMBAT_SETTING_SCT_OUTGOING_PET_HEALING_ENABLED = 9
COMBAT_SETTING_SCT_OUTGOING_PET_HOT_ENABLED = 10
COMBAT_SETTING_SCT_OUTGOING_STATUS_EFFECTS_ENABLED = 6
COMBAT_SETTING_SCT_SHOW_OVER_HEAL = 20
COMBAT_SETTING_USE_BATTLE_LEVEL = 24
