--- @meta CombatMusicModeSetting

--- @alias CombatMusicModeSetting integer
--- | `COMBAT_MUSIC_MODE_SETTING_ALL` # 0
--- | `COMBAT_MUSIC_MODE_SETTING_BOSSES_ONLY` # 2
--- | `COMBAT_MUSIC_MODE_SETTING_NONE` # 1

COMBAT_MUSIC_MODE_SETTING_ALL = 0
COMBAT_MUSIC_MODE_SETTING_BOSSES_ONLY = 2
COMBAT_MUSIC_MODE_SETTING_NONE = 1
