--- @meta CompanionState

--- @alias CompanionState integer
--- | `COMPANION_STATE_ACTIVE` # 7
--- | `COMPANION_STATE_BLOCKED_PERMANENT` # 1
--- | `COMPANION_STATE_BLOCKED_TEMPORARY` # 2
--- | `COMPANION_STATE_HIDDEN` # 6
--- | `COMPANION_STATE_INACTIVE` # 0
--- | `COMPANION_STATE_INITIALIZED_PENDING` # 4
--- | `COMPANION_STATE_INITIALIZING` # 3
--- | `COMPANION_STATE_PENDING` # 5

COMPANION_STATE_ACTIVE = 7
COMPANION_STATE_BLOCKED_PERMANENT = 1
COMPANION_STATE_BLOCKED_TEMPORARY = 2
COMPANION_STATE_HIDDEN = 6
COMPANION_STATE_INACTIVE = 0
COMPANION_STATE_INITIALIZED_PENDING = 4
COMPANION_STATE_INITIALIZING = 3
COMPANION_STATE_PENDING = 5
