--- @meta CompanionUltimateFailureReason

--- @alias CompanionUltimateFailureReason integer
--- | `COMPANION_ULTIMATE_FAILURE_REASON_GENERIC_FAILURE` # 3
--- | `COMPANION_ULTIMATE_FAILURE_REASON_NOT_ENOUGH_RESOURCE` # 2
--- | `COMPANION_ULTIMATE_FAILURE_REASON_NO_ULT` # 1
--- | `COMPANION_ULTIMATE_FAILURE_REASON_ON_COOLDOWN` # 4
--- | `COMPANION_ULTIMATE_FAILURE_REASON_SUCCESS` # 0

COMPANION_ULTIMATE_FAILURE_REASON_GENERIC_FAILURE = 3
COMPANION_ULTIMATE_FAILURE_REASON_NOT_ENOUGH_RESOURCE = 2
COMPANION_ULTIMATE_FAILURE_REASON_NO_ULT = 1
COMPANION_ULTIMATE_FAILURE_REASON_ON_COOLDOWN = 4
COMPANION_ULTIMATE_FAILURE_REASON_SUCCESS = 0
