--- @meta CompanionPassengerPreference

--- @alias CompanionPassengerPreference integer
--- | `COMPANION_PASSENGER_PREFERENCE_ALWAYS` # 0
--- | `COMPANION_PASSENGER_PREFERENCE_NEVER` # 1
--- | `COMPANION_PASSENGER_PREFERENCE_WHEN_PLAYER_NOT_GROUPED` # 2

COMPANION_PASSENGER_PREFERENCE_ALWAYS = 0
COMPANION_PASSENGER_PREFERENCE_NEVER = 1
COMPANION_PASSENGER_PREFERENCE_WHEN_PLAYER_NOT_GROUPED = 2
