--- @meta CompanionSummonResult

--- @alias CompanionSummonResult integer
--- | `COMPANION_SUMMON_RESULT_ADDED_FOR_GROUP_PLAYER` # 3
--- | `COMPANION_SUMMON_RESULT_BLOCKED_BY_ASSISTANT` # 23
--- | `COMPANION_SUMMON_RESULT_BLOCKED_BY_FOLLOWER` # 14
--- | `COMPANION_SUMMON_RESULT_BLOCKED_BY_SUBZONE` # 12
--- | `COMPANION_SUMMON_RESULT_BLOCKED_BY_WORLD_BOSS` # 18
--- | `COMPANION_SUMMON_RESULT_BLOCKED_BY_WORLD_EVENT` # 16
--- | `COMPANION_SUMMON_RESULT_DATA_NOT_LOADED` # 6
--- | `COMPANION_SUMMON_RESULT_DEACTIVATED_VANITY_PET` # 19
--- | `COMPANION_SUMMON_RESULT_EFFECT_LIMIT` # 9
--- | `COMPANION_SUMMON_RESULT_EXPECTED_DIFFERENT_COMPANION` # 5
--- | `COMPANION_SUMMON_RESULT_GROUP_FULL` # 4
--- | `COMPANION_SUMMON_RESULT_REMOVED_FOR_ASSISTANT` # 22
--- | `COMPANION_SUMMON_RESULT_REMOVED_FOR_FOLLOWER` # 13
--- | `COMPANION_SUMMON_RESULT_REMOVED_FOR_GROUP_PLAYER` # 2
--- | `COMPANION_SUMMON_RESULT_REMOVED_FOR_PERF` # 20
--- | `COMPANION_SUMMON_RESULT_REMOVED_FOR_SUBZONE` # 10
--- | `COMPANION_SUMMON_RESULT_REMOVED_FOR_VANITY_PET` # 21
--- | `COMPANION_SUMMON_RESULT_REMOVED_FOR_WORLD_BOSS` # 17
--- | `COMPANION_SUMMON_RESULT_REMOVED_FOR_WORLD_EVENT` # 15
--- | `COMPANION_SUMMON_RESULT_SPAWN_FAILED` # 7
--- | `COMPANION_SUMMON_RESULT_SUMMON_AUTO_REQUESTED` # 11
--- | `COMPANION_SUMMON_RESULT_SUMMON_FAILED` # 1
--- | `COMPANION_SUMMON_RESULT_SUMMON_FAILED_LOW_RAPPORT` # 8
--- | `COMPANION_SUMMON_RESULT_SUMMON_REQUESTED` # 0

COMPANION_SUMMON_RESULT_ADDED_FOR_GROUP_PLAYER = 3
COMPANION_SUMMON_RESULT_BLOCKED_BY_ASSISTANT = 23
COMPANION_SUMMON_RESULT_BLOCKED_BY_FOLLOWER = 14
COMPANION_SUMMON_RESULT_BLOCKED_BY_SUBZONE = 12
COMPANION_SUMMON_RESULT_BLOCKED_BY_WORLD_BOSS = 18
COMPANION_SUMMON_RESULT_BLOCKED_BY_WORLD_EVENT = 16
COMPANION_SUMMON_RESULT_DATA_NOT_LOADED = 6
COMPANION_SUMMON_RESULT_DEACTIVATED_VANITY_PET = 19
COMPANION_SUMMON_RESULT_EFFECT_LIMIT = 9
COMPANION_SUMMON_RESULT_EXPECTED_DIFFERENT_COMPANION = 5
COMPANION_SUMMON_RESULT_GROUP_FULL = 4
COMPANION_SUMMON_RESULT_REMOVED_FOR_ASSISTANT = 22
COMPANION_SUMMON_RESULT_REMOVED_FOR_FOLLOWER = 13
COMPANION_SUMMON_RESULT_REMOVED_FOR_GROUP_PLAYER = 2
COMPANION_SUMMON_RESULT_REMOVED_FOR_PERF = 20
COMPANION_SUMMON_RESULT_REMOVED_FOR_SUBZONE = 10
COMPANION_SUMMON_RESULT_REMOVED_FOR_VANITY_PET = 21
COMPANION_SUMMON_RESULT_REMOVED_FOR_WORLD_BOSS = 17
COMPANION_SUMMON_RESULT_REMOVED_FOR_WORLD_EVENT = 15
COMPANION_SUMMON_RESULT_SPAWN_FAILED = 7
COMPANION_SUMMON_RESULT_SUMMON_AUTO_REQUESTED = 11
COMPANION_SUMMON_RESULT_SUMMON_FAILED = 1
COMPANION_SUMMON_RESULT_SUMMON_FAILED_LOW_RAPPORT = 8
COMPANION_SUMMON_RESULT_SUMMON_REQUESTED = 0
