--- @meta CompanionRapportAdjustmentAmount

--- @alias CompanionRapportAdjustmentAmount integer
--- | `RAPPORT_ADJUSTMENT_AMOUNT_ASTRONOMICAL` # 6
--- | `RAPPORT_ADJUSTMENT_AMOUNT_CUSTOM_A` # 8
--- | `RAPPORT_ADJUSTMENT_AMOUNT_CUSTOM_B` # 9
--- | `RAPPORT_ADJUSTMENT_AMOUNT_LARGE` # 4
--- | `RAPPORT_ADJUSTMENT_AMOUNT_MEDIUM` # 3
--- | `RAPPORT_ADJUSTMENT_AMOUNT_MINISCULE` # 1
--- | `RAPPORT_ADJUSTMENT_AMOUNT_NONE` # 0
--- | `RAPPORT_ADJUSTMENT_AMOUNT_SMALL` # 2
--- | `RAPPORT_ADJUSTMENT_AMOUNT_VERY_ASTRONOMICAL` # 7
--- | `RAPPORT_ADJUSTMENT_AMOUNT_VERY_LARGE` # 5

RAPPORT_ADJUSTMENT_AMOUNT_ASTRONOMICAL = 6
RAPPORT_ADJUSTMENT_AMOUNT_CUSTOM_A = 8
RAPPORT_ADJUSTMENT_AMOUNT_CUSTOM_B = 9
RAPPORT_ADJUSTMENT_AMOUNT_LARGE = 4
RAPPORT_ADJUSTMENT_AMOUNT_MEDIUM = 3
RAPPORT_ADJUSTMENT_AMOUNT_MINISCULE = 1
RAPPORT_ADJUSTMENT_AMOUNT_NONE = 0
RAPPORT_ADJUSTMENT_AMOUNT_SMALL = 2
RAPPORT_ADJUSTMENT_AMOUNT_VERY_ASTRONOMICAL = 7
RAPPORT_ADJUSTMENT_AMOUNT_VERY_LARGE = 5
