--- @meta CompanionRapportLevel

--- @alias CompanionRapportLevel integer
--- | `RAPPORT_LEVEL_HIGH_AFFINITY` # 5
--- | `RAPPORT_LEVEL_HIGH_DISLIKE` # 1
--- | `RAPPORT_LEVEL_MAXIMUM_AFFINITY` # 7
--- | `RAPPORT_LEVEL_MAXIMUM_DISLIKE` # 0
--- | `RAPPORT_LEVEL_MODERATE_AFFINITY` # 4
--- | `RAPPORT_LEVEL_SLIGHT_AFFINITY` # 3
--- | `RAPPORT_LEVEL_SLIGHT_DISLIKE` # 2
--- | `RAPPORT_LEVEL_VERY_HIGH_AFFINITY` # 6

RAPPORT_LEVEL_HIGH_AFFINITY = 5
RAPPORT_LEVEL_HIGH_DISLIKE = 1
RAPPORT_LEVEL_MAXIMUM_AFFINITY = 7
RAPPORT_LEVEL_MAXIMUM_DISLIKE = 0
RAPPORT_LEVEL_MODERATE_AFFINITY = 4
RAPPORT_LEVEL_SLIGHT_AFFINITY = 3
RAPPORT_LEVEL_SLIGHT_DISLIKE = 2
RAPPORT_LEVEL_VERY_HIGH_AFFINITY = 6
