--- @meta CompassActiveQuestsChoice

--- @alias CompassActiveQuestsChoice integer
--- | `COMPASS_ACTIVE_QUESTS_CHOICE_FOCUSED` # 2
--- | `COMPASS_ACTIVE_QUESTS_CHOICE_OFF` # 0
--- | `COMPASS_ACTIVE_QUESTS_CHOICE_ON` # 1

COMPASS_ACTIVE_QUESTS_CHOICE_FOCUSED = 2
COMPASS_ACTIVE_QUESTS_CHOICE_OFF = 0
COMPASS_ACTIVE_QUESTS_CHOICE_ON = 1
