--- @meta CompanionReactionFrequencyRate

--- @alias CompanionReactionFrequencyRate integer
--- | `COMPANION_REACTION_FREQUENCY_RATE_HIGH` # 2
--- | `COMPANION_REACTION_FREQUENCY_RATE_LOW` # 0
--- | `COMPANION_REACTION_FREQUENCY_RATE_NORMAL` # 1
--- | `COMPANION_REACTION_FREQUENCY_RATE_VERY_LOW` # 3

COMPANION_REACTION_FREQUENCY_RATE_HIGH = 2
COMPANION_REACTION_FREQUENCY_RATE_LOW = 0
COMPANION_REACTION_FREQUENCY_RATE_NORMAL = 1
COMPANION_REACTION_FREQUENCY_RATE_VERY_LOW = 3
