--- @meta ConsoleActivityType

--- @alias ConsoleActivityType integer
--- | `CONSOLE_ACTIVITY_TYPE_BATTLEGROUND` # 2
--- | `CONSOLE_ACTIVITY_TYPE_DUNGEON` # 1
--- | `CONSOLE_ACTIVITY_TYPE_NONE` # 0
--- | `CONSOLE_ACTIVITY_TYPE_ZONE_STORY` # 3
--- | `CONSOLE_ACTIVITY_TYPE_ZONE_STORY_TASK` # 4

CONSOLE_ACTIVITY_TYPE_BATTLEGROUND = 2
CONSOLE_ACTIVITY_TYPE_DUNGEON = 1
CONSOLE_ACTIVITY_TYPE_NONE = 0
CONSOLE_ACTIVITY_TYPE_ZONE_STORY = 3
CONSOLE_ACTIVITY_TYPE_ZONE_STORY_TASK = 4
