--- @meta ConsoleEnhancedRenderQuality

--- @alias ConsoleEnhancedRenderQuality integer
--- | `CONSOLE_ENHANCED_RENDER_QUALITY_ENHANCED_1080` # 1
--- | `CONSOLE_ENHANCED_RENDER_QUALITY_FOUR_K` # 0
--- | `CONSOLE_ENHANCED_RENDER_QUALITY_PS5_1440` # 3
--- | `CONSOLE_ENHANCED_RENDER_QUALITY_PS5_4K` # 2
--- | `CONSOLE_ENHANCED_RENDER_QUALITY_XBSS_1080` # 6
--- | `CONSOLE_ENHANCED_RENDER_QUALITY_XBSS_1440` # 7
--- | `CONSOLE_ENHANCED_RENDER_QUALITY_XBSX_1440` # 4
--- | `CONSOLE_ENHANCED_RENDER_QUALITY_XBSX_2160` # 5

CONSOLE_ENHANCED_RENDER_QUALITY_ENHANCED_1080 = 1
CONSOLE_ENHANCED_RENDER_QUALITY_FOUR_K = 0
CONSOLE_ENHANCED_RENDER_QUALITY_PS5_1440 = 3
CONSOLE_ENHANCED_RENDER_QUALITY_PS5_4K = 2
CONSOLE_ENHANCED_RENDER_QUALITY_XBSS_1080 = 6
CONSOLE_ENHANCED_RENDER_QUALITY_XBSS_1440 = 7
CONSOLE_ENHANCED_RENDER_QUALITY_XBSX_1440 = 4
CONSOLE_ENHANCED_RENDER_QUALITY_XBSX_2160 = 5
