--- @meta ControlHandlerOrder

--- @alias ControlHandlerOrder integer
--- | `CONTROL_HANDLER_ORDER_AFTER` # 2
--- | `CONTROL_HANDLER_ORDER_BEFORE` # 1
--- | `CONTROL_HANDLER_ORDER_NONE` # 0

CONTROL_HANDLER_ORDER_AFTER = 2
CONTROL_HANDLER_ORDER_BEFORE = 1
CONTROL_HANDLER_ORDER_NONE = 0
