--- @meta CraftingInteractionMode

--- @alias CraftingInteractionMode integer
--- | `CRAFTING_INTERACTION_MODE_CONSOLIDATED_STATION` # 3
--- | `CRAFTING_INTERACTION_MODE_INVALID` # 0
--- | `CRAFTING_INTERACTION_MODE_STANDARD_STATION` # 1
--- | `CRAFTING_INTERACTION_MODE_UNIVERSAL_DECONSTRUCTION` # 2

CRAFTING_INTERACTION_MODE_CONSOLIDATED_STATION = 3
CRAFTING_INTERACTION_MODE_INVALID = 0
CRAFTING_INTERACTION_MODE_STANDARD_STATION = 1
CRAFTING_INTERACTION_MODE_UNIVERSAL_DECONSTRUCTION = 2
