--- @meta CraftingProcessContext

--- @alias CraftingProcessContext integer
--- | `CRAFTING_PROCESS_CONTEXT_CONSUME_ATTUNABLE_STATIONS` # 1
--- | `CRAFTING_PROCESS_CONTEXT_NONE` # 0

CRAFTING_PROCESS_CONTEXT_CONSUME_ATTUNABLE_STATIONS = 1
CRAFTING_PROCESS_CONTEXT_NONE = 0
