--- @meta CrownCrateEvent

--- @alias CrownCrateEvent integer
--- | `CROWN_CRATE_NPC_ANIMATION_TYPE_ALL_CARDS_REVEALED_HAS_CRATES` # 24
--- | `CROWN_CRATE_NPC_ANIMATION_TYPE_ALL_CARDS_REVEALED_NO_CRATES` # 23
--- | `CROWN_CRATE_NPC_ANIMATION_TYPE_DEAL_BONUS_CARDS` # 11
--- | `CROWN_CRATE_NPC_ANIMATION_TYPE_DEAL_PRIMARY_CARDS` # 10
--- | `CROWN_CRATE_NPC_ANIMATION_TYPE_FAREWELL` # 13
--- | `CROWN_CRATE_NPC_ANIMATION_TYPE_FLOURISH` # 8
--- | `CROWN_CRATE_NPC_ANIMATION_TYPE_GEMS_AWARDED` # 27
--- | `CROWN_CRATE_NPC_ANIMATION_TYPE_GREET_PLAYER` # 7
--- | `CROWN_CRATE_NPC_ANIMATION_TYPE_IDLE_CHATTER` # 19
--- | `CROWN_CRATE_NPC_ANIMATION_TYPE_INVALID` # -1
--- | `CROWN_CRATE_NPC_ANIMATION_TYPE_MANIFEST_ENTER_MULTI_CRATES` # 22
--- | `CROWN_CRATE_NPC_ANIMATION_TYPE_MANIFEST_ENTER_NO_CRATES` # 20
--- | `CROWN_CRATE_NPC_ANIMATION_TYPE_MANIFEST_ENTER_ONE_CRATES` # 21
--- | `CROWN_CRATE_NPC_ANIMATION_TYPE_NO_CRATES_WARNING` # 28
--- | `CROWN_CRATE_NPC_ANIMATION_TYPE_POSTURE_ENTER` # 16
--- | `CROWN_CRATE_NPC_ANIMATION_TYPE_POSTURE_EXIT` # 18
--- | `CROWN_CRATE_NPC_ANIMATION_TYPE_POSTURE_FIDGET` # 14
--- | `CROWN_CRATE_NPC_ANIMATION_TYPE_POSTURE_GROUP_FIDGET` # 15
--- | `CROWN_CRATE_NPC_ANIMATION_TYPE_POSTURE_LOOP` # 17
--- | `CROWN_CRATE_NPC_ANIMATION_TYPE_PRIMARY_CARDS_DEALT` # 25
--- | `CROWN_CRATE_NPC_ANIMATION_TYPE_REVEAL_ALL_CARDS` # 12
--- | `CROWN_CRATE_NPC_ANIMATION_TYPE_SHUFFLE_CARDS` # 9
--- | `CROWN_CRATE_NPC_ANIMATION_TYPE_SWIPE_CARDS_AWAY` # 6
--- | `CROWN_CRATE_NPC_ANIMATION_TYPE_TIER_FIVE_CARD` # 4
--- | `CROWN_CRATE_NPC_ANIMATION_TYPE_TIER_FOUR_CARD` # 3
--- | `CROWN_CRATE_NPC_ANIMATION_TYPE_TIER_ONE_CARD` # 0
--- | `CROWN_CRATE_NPC_ANIMATION_TYPE_TIER_SIX_CARD` # 5
--- | `CROWN_CRATE_NPC_ANIMATION_TYPE_TIER_THREE_CARD` # 2
--- | `CROWN_CRATE_NPC_ANIMATION_TYPE_TIER_TWO_CARD` # 1
--- | `CROWN_CRATE_NPC_ANIMATION_TYPE_UNDER_ATTACK` # 26

CROWN_CRATE_NPC_ANIMATION_TYPE_ALL_CARDS_REVEALED_HAS_CRATES = 24
CROWN_CRATE_NPC_ANIMATION_TYPE_ALL_CARDS_REVEALED_NO_CRATES = 23
CROWN_CRATE_NPC_ANIMATION_TYPE_DEAL_BONUS_CARDS = 11
CROWN_CRATE_NPC_ANIMATION_TYPE_DEAL_PRIMARY_CARDS = 10
CROWN_CRATE_NPC_ANIMATION_TYPE_FAREWELL = 13
CROWN_CRATE_NPC_ANIMATION_TYPE_FLOURISH = 8
CROWN_CRATE_NPC_ANIMATION_TYPE_GEMS_AWARDED = 27
CROWN_CRATE_NPC_ANIMATION_TYPE_GREET_PLAYER = 7
CROWN_CRATE_NPC_ANIMATION_TYPE_IDLE_CHATTER = 19
CROWN_CRATE_NPC_ANIMATION_TYPE_INVALID = -1
CROWN_CRATE_NPC_ANIMATION_TYPE_MANIFEST_ENTER_MULTI_CRATES = 22
CROWN_CRATE_NPC_ANIMATION_TYPE_MANIFEST_ENTER_NO_CRATES = 20
CROWN_CRATE_NPC_ANIMATION_TYPE_MANIFEST_ENTER_ONE_CRATES = 21
CROWN_CRATE_NPC_ANIMATION_TYPE_NO_CRATES_WARNING = 28
CROWN_CRATE_NPC_ANIMATION_TYPE_POSTURE_ENTER = 16
CROWN_CRATE_NPC_ANIMATION_TYPE_POSTURE_EXIT = 18
CROWN_CRATE_NPC_ANIMATION_TYPE_POSTURE_FIDGET = 14
CROWN_CRATE_NPC_ANIMATION_TYPE_POSTURE_GROUP_FIDGET = 15
CROWN_CRATE_NPC_ANIMATION_TYPE_POSTURE_LOOP = 17
CROWN_CRATE_NPC_ANIMATION_TYPE_PRIMARY_CARDS_DEALT = 25
CROWN_CRATE_NPC_ANIMATION_TYPE_REVEAL_ALL_CARDS = 12
CROWN_CRATE_NPC_ANIMATION_TYPE_SHUFFLE_CARDS = 9
CROWN_CRATE_NPC_ANIMATION_TYPE_SWIPE_CARDS_AWAY = 6
CROWN_CRATE_NPC_ANIMATION_TYPE_TIER_FIVE_CARD = 4
CROWN_CRATE_NPC_ANIMATION_TYPE_TIER_FOUR_CARD = 3
CROWN_CRATE_NPC_ANIMATION_TYPE_TIER_ONE_CARD = 0
CROWN_CRATE_NPC_ANIMATION_TYPE_TIER_SIX_CARD = 5
CROWN_CRATE_NPC_ANIMATION_TYPE_TIER_THREE_CARD = 2
CROWN_CRATE_NPC_ANIMATION_TYPE_TIER_TWO_CARD = 1
CROWN_CRATE_NPC_ANIMATION_TYPE_UNDER_ATTACK = 26
