--- @meta CrownCrateTierParticleEffects

--- @alias CrownCrateTierParticleEffects integer
--- | `CROWN_CRATE_TIERED_PARTICLES_MYSTERY` # 0
--- | `CROWN_CRATE_TIERED_PARTICLES_REVEAL` # 1
--- | `CROWN_CRATE_TIERED_PARTICLES_REVEALED` # 2
--- | `CROWN_CRATE_TIERED_PARTICLES_REVEALED_SELECTED` # 3

CROWN_CRATE_TIERED_PARTICLES_MYSTERY = 0
CROWN_CRATE_TIERED_PARTICLES_REVEAL = 1
CROWN_CRATE_TIERED_PARTICLES_REVEALED = 2
CROWN_CRATE_TIERED_PARTICLES_REVEALED_SELECTED = 3
