--- @meta CurrencyLocation

--- @alias CurrencyLocation integer
--- | `CURRENCY_LOCATION_ACCOUNT` # 3
--- | `CURRENCY_LOCATION_BANK` # 1
--- | `CURRENCY_LOCATION_CHARACTER` # 0
--- | `CURRENCY_LOCATION_GUILD_BANK` # 2

CURRENCY_LOCATION_ACCOUNT = 3
CURRENCY_LOCATION_BANK = 1
CURRENCY_LOCATION_CHARACTER = 0
CURRENCY_LOCATION_GUILD_BANK = 2
