--- @meta CurrencyChangeReason

--- @alias CurrencyChangeReason integer
--- | `CURRENCY_CHANGE_REASON_ABILITY_UPGRADE_PURCHASE` # 22
--- | `CURRENCY_CHANGE_REASON_ACHIEVEMENT` # 26
--- | `CURRENCY_CHANGE_REASON_ACTION` # 6
--- | `CURRENCY_CHANGE_REASON_ANTIQUITY_REWARD` # 11
--- | `CURRENCY_CHANGE_REASON_BAGSPACE` # 8
--- | `CURRENCY_CHANGE_REASON_BANKSPACE` # 9
--- | `CURRENCY_CHANGE_REASON_BANK_DEPOSIT` # 42
--- | `CURRENCY_CHANGE_REASON_BANK_FEE` # 66
--- | `CURRENCY_CHANGE_REASON_BANK_WITHDRAWAL` # 43
--- | `CURRENCY_CHANGE_REASON_BATTLEGROUND` # 12
--- | `CURRENCY_CHANGE_REASON_BOUNTY_CONFISCATED` # 57
--- | `CURRENCY_CHANGE_REASON_BOUNTY_PAID_FENCE` # 56
--- | `CURRENCY_CHANGE_REASON_BOUNTY_PAID_GUARD` # 47
--- | `CURRENCY_CHANGE_REASON_BUYBACK` # 64
--- | `CURRENCY_CHANGE_REASON_CASH_ON_DELIVERY` # 20
--- | `CURRENCY_CHANGE_REASON_CHARACTER_UPGRADE` # 77
--- | `CURRENCY_CHANGE_REASON_COMMAND` # 7
--- | `CURRENCY_CHANGE_REASON_CONSUME_FOOD_DRINK` # 37
--- | `CURRENCY_CHANGE_REASON_CONSUME_POTION` # 38
--- | `CURRENCY_CHANGE_REASON_CONVERSATION` # 5
--- | `CURRENCY_CHANGE_REASON_CRAFT` # 24
--- | `CURRENCY_CHANGE_REASON_CROWNS_PURCHASED` # 73
--- | `CURRENCY_CHANGE_REASON_CROWN_CRATE_DUPLICATE` # 69
--- | `CURRENCY_CHANGE_REASON_DEATH` # 67
--- | `CURRENCY_CHANGE_REASON_DECONSTRUCT` # 16
--- | `CURRENCY_CHANGE_REASON_DEFENSIVE_KEEP_REWARD` # 75
--- | `CURRENCY_CHANGE_REASON_DEPRECATED_0` # 14
--- | `CURRENCY_CHANGE_REASON_DEPRECATED_1` # 23
--- | `CURRENCY_CHANGE_REASON_DEPRECATED_2` # 17
--- | `CURRENCY_CHANGE_REASON_DEPRECATED_3` # 53
--- | `CURRENCY_CHANGE_REASON_EDIT_GUILD_HERALDRY` # 49
--- | `CURRENCY_CHANGE_REASON_EXPIRATION` # 81
--- | `CURRENCY_CHANGE_REASON_FEED_MOUNT` # 28
--- | `CURRENCY_CHANGE_REASON_GUILD_BANK_DEPOSIT` # 51
--- | `CURRENCY_CHANGE_REASON_GUILD_BANK_WITHDRAWAL` # 52
--- | `CURRENCY_CHANGE_REASON_GUILD_FORWARD_CAMP` # 58
--- | `CURRENCY_CHANGE_REASON_GUILD_TABARD` # 50
--- | `CURRENCY_CHANGE_REASON_HARVEST_REAGENT` # 39
--- | `CURRENCY_CHANGE_REASON_ITEM_CONVERTED_TO_GEMS` # 70
--- | `CURRENCY_CHANGE_REASON_JUMP_FAILURE_REFUND` # 54
--- | `CURRENCY_CHANGE_REASON_KEEP_REPAIR` # 40
--- | `CURRENCY_CHANGE_REASON_KEEP_UPGRADE` # 15
--- | `CURRENCY_CHANGE_REASON_KILL` # 13
--- | `CURRENCY_CHANGE_REASON_LOOT` # 0
--- | `CURRENCY_CHANGE_REASON_LOOT_CURRENCY_CONTAINER` # 76
--- | `CURRENCY_CHANGE_REASON_LOOT_STOLEN` # 62
--- | `CURRENCY_CHANGE_REASON_MAIL` # 2
--- | `CURRENCY_CHANGE_REASON_MEDAL` # 21
--- | `CURRENCY_CHANGE_REASON_OFFENSIVE_KEEP_REWARD` # 74
--- | `CURRENCY_CHANGE_REASON_PICKPOCKET` # 59
--- | `CURRENCY_CHANGE_REASON_PLAYER_INIT` # 35
--- | `CURRENCY_CHANGE_REASON_PURCHASED_WITH_CROWNS` # 72
--- | `CURRENCY_CHANGE_REASON_PURCHASED_WITH_ENDEAVOR_SEALS` # 79
--- | `CURRENCY_CHANGE_REASON_PURCHASED_WITH_GEMS` # 71
--- | `CURRENCY_CHANGE_REASON_PVP_KILL_TRANSFER` # 65
--- | `CURRENCY_CHANGE_REASON_PVP_RESURRECT` # 41
--- | `CURRENCY_CHANGE_REASON_QUESTREWARD` # 4
--- | `CURRENCY_CHANGE_REASON_RECIPE` # 36
--- | `CURRENCY_CHANGE_REASON_RECONSTRUCTION` # 78
--- | `CURRENCY_CHANGE_REASON_REFORGE` # 34
--- | `CURRENCY_CHANGE_REASON_RESEARCH_TRAIT` # 46
--- | `CURRENCY_CHANGE_REASON_RESPEC_ATTRIBUTES` # 45
--- | `CURRENCY_CHANGE_REASON_RESPEC_CHAMPION` # 61
--- | `CURRENCY_CHANGE_REASON_RESPEC_MORPHS` # 55
--- | `CURRENCY_CHANGE_REASON_RESPEC_SKILLS` # 44
--- | `CURRENCY_CHANGE_REASON_REWARD` # 27
--- | `CURRENCY_CHANGE_REASON_SELL_STOLEN` # 63
--- | `CURRENCY_CHANGE_REASON_SOULWEARY` # 10
--- | `CURRENCY_CHANGE_REASON_SOUL_HEAL` # 18
--- | `CURRENCY_CHANGE_REASON_STABLESPACE` # 25
--- | `CURRENCY_CHANGE_REASON_STUCK` # 48
--- | `CURRENCY_CHANGE_REASON_TRADE` # 3
--- | `CURRENCY_CHANGE_REASON_TRADINGHOUSE_LISTING` # 33
--- | `CURRENCY_CHANGE_REASON_TRADINGHOUSE_PURCHASE` # 31
--- | `CURRENCY_CHANGE_REASON_TRADINGHOUSE_REFUND` # 32
--- | `CURRENCY_CHANGE_REASON_TRAIT_REVEAL` # 30
--- | `CURRENCY_CHANGE_REASON_TRAVEL_GRAVEYARD` # 19
--- | `CURRENCY_CHANGE_REASON_TRIBUTE` # 80
--- | `CURRENCY_CHANGE_REASON_UNKNOWN` # 68
--- | `CURRENCY_CHANGE_REASON_VENDOR` # 1
--- | `CURRENCY_CHANGE_REASON_VENDOR_LAUNDER` # 60
--- | `CURRENCY_CHANGE_REASON_VENDOR_REPAIR` # 29

CURRENCY_CHANGE_REASON_ABILITY_UPGRADE_PURCHASE = 22
CURRENCY_CHANGE_REASON_ACHIEVEMENT = 26
CURRENCY_CHANGE_REASON_ACTION = 6
CURRENCY_CHANGE_REASON_ANTIQUITY_REWARD = 11
CURRENCY_CHANGE_REASON_BAGSPACE = 8
CURRENCY_CHANGE_REASON_BANKSPACE = 9
CURRENCY_CHANGE_REASON_BANK_DEPOSIT = 42
CURRENCY_CHANGE_REASON_BANK_FEE = 66
CURRENCY_CHANGE_REASON_BANK_WITHDRAWAL = 43
CURRENCY_CHANGE_REASON_BATTLEGROUND = 12
CURRENCY_CHANGE_REASON_BOUNTY_CONFISCATED = 57
CURRENCY_CHANGE_REASON_BOUNTY_PAID_FENCE = 56
CURRENCY_CHANGE_REASON_BOUNTY_PAID_GUARD = 47
CURRENCY_CHANGE_REASON_BUYBACK = 64
CURRENCY_CHANGE_REASON_CASH_ON_DELIVERY = 20
CURRENCY_CHANGE_REASON_CHARACTER_UPGRADE = 77
CURRENCY_CHANGE_REASON_COMMAND = 7
CURRENCY_CHANGE_REASON_CONSUME_FOOD_DRINK = 37
CURRENCY_CHANGE_REASON_CONSUME_POTION = 38
CURRENCY_CHANGE_REASON_CONVERSATION = 5
CURRENCY_CHANGE_REASON_CRAFT = 24
CURRENCY_CHANGE_REASON_CROWNS_PURCHASED = 73
CURRENCY_CHANGE_REASON_CROWN_CRATE_DUPLICATE = 69
CURRENCY_CHANGE_REASON_DEATH = 67
CURRENCY_CHANGE_REASON_DECONSTRUCT = 16
CURRENCY_CHANGE_REASON_DEFENSIVE_KEEP_REWARD = 75
CURRENCY_CHANGE_REASON_DEPRECATED_0 = 14
CURRENCY_CHANGE_REASON_DEPRECATED_1 = 23
CURRENCY_CHANGE_REASON_DEPRECATED_2 = 17
CURRENCY_CHANGE_REASON_DEPRECATED_3 = 53
CURRENCY_CHANGE_REASON_EDIT_GUILD_HERALDRY = 49
CURRENCY_CHANGE_REASON_EXPIRATION = 81
CURRENCY_CHANGE_REASON_FEED_MOUNT = 28
CURRENCY_CHANGE_REASON_GUILD_BANK_DEPOSIT = 51
CURRENCY_CHANGE_REASON_GUILD_BANK_WITHDRAWAL = 52
CURRENCY_CHANGE_REASON_GUILD_FORWARD_CAMP = 58
CURRENCY_CHANGE_REASON_GUILD_TABARD = 50
CURRENCY_CHANGE_REASON_HARVEST_REAGENT = 39
CURRENCY_CHANGE_REASON_ITEM_CONVERTED_TO_GEMS = 70
CURRENCY_CHANGE_REASON_JUMP_FAILURE_REFUND = 54
CURRENCY_CHANGE_REASON_KEEP_REPAIR = 40
CURRENCY_CHANGE_REASON_KEEP_UPGRADE = 15
CURRENCY_CHANGE_REASON_KILL = 13
CURRENCY_CHANGE_REASON_LOOT = 0
CURRENCY_CHANGE_REASON_LOOT_CURRENCY_CONTAINER = 76
CURRENCY_CHANGE_REASON_LOOT_STOLEN = 62
CURRENCY_CHANGE_REASON_MAIL = 2
CURRENCY_CHANGE_REASON_MEDAL = 21
CURRENCY_CHANGE_REASON_OFFENSIVE_KEEP_REWARD = 74
CURRENCY_CHANGE_REASON_PICKPOCKET = 59
CURRENCY_CHANGE_REASON_PLAYER_INIT = 35
CURRENCY_CHANGE_REASON_PURCHASED_WITH_CROWNS = 72
CURRENCY_CHANGE_REASON_PURCHASED_WITH_ENDEAVOR_SEALS = 79
CURRENCY_CHANGE_REASON_PURCHASED_WITH_GEMS = 71
CURRENCY_CHANGE_REASON_PVP_KILL_TRANSFER = 65
CURRENCY_CHANGE_REASON_PVP_RESURRECT = 41
CURRENCY_CHANGE_REASON_QUESTREWARD = 4
CURRENCY_CHANGE_REASON_RECIPE = 36
CURRENCY_CHANGE_REASON_RECONSTRUCTION = 78
CURRENCY_CHANGE_REASON_REFORGE = 34
CURRENCY_CHANGE_REASON_RESEARCH_TRAIT = 46
CURRENCY_CHANGE_REASON_RESPEC_ATTRIBUTES = 45
CURRENCY_CHANGE_REASON_RESPEC_CHAMPION = 61
CURRENCY_CHANGE_REASON_RESPEC_MORPHS = 55
CURRENCY_CHANGE_REASON_RESPEC_SKILLS = 44
CURRENCY_CHANGE_REASON_REWARD = 27
CURRENCY_CHANGE_REASON_SELL_STOLEN = 63
CURRENCY_CHANGE_REASON_SOULWEARY = 10
CURRENCY_CHANGE_REASON_SOUL_HEAL = 18
CURRENCY_CHANGE_REASON_STABLESPACE = 25
CURRENCY_CHANGE_REASON_STUCK = 48
CURRENCY_CHANGE_REASON_TRADE = 3
CURRENCY_CHANGE_REASON_TRADINGHOUSE_LISTING = 33
CURRENCY_CHANGE_REASON_TRADINGHOUSE_PURCHASE = 31
CURRENCY_CHANGE_REASON_TRADINGHOUSE_REFUND = 32
CURRENCY_CHANGE_REASON_TRAIT_REVEAL = 30
CURRENCY_CHANGE_REASON_TRAVEL_GRAVEYARD = 19
CURRENCY_CHANGE_REASON_TRIBUTE = 80
CURRENCY_CHANGE_REASON_UNKNOWN = 68
CURRENCY_CHANGE_REASON_VENDOR = 1
CURRENCY_CHANGE_REASON_VENDOR_LAUNDER = 60
CURRENCY_CHANGE_REASON_VENDOR_REPAIR = 29
