--- @meta CurrencyColors

--- @alias CurrencyColors integer
--- | `CURRENCY_COLOR_ALLIANCE_POINTS` # 1
--- | `CURRENCY_COLOR_GOLD` # 0
--- | `CURRENCY_COLOR_INSPIRATION` # 3
--- | `CURRENCY_COLOR_RANK_POINTS` # 4
--- | `CURRENCY_COLOR_TELVAR_STONES` # 2
--- | `CURRENCY_COLOR_WRIT_VOUCHERS` # 5

CURRENCY_COLOR_ALLIANCE_POINTS = 1
CURRENCY_COLOR_GOLD = 0
CURRENCY_COLOR_INSPIRATION = 3
CURRENCY_COLOR_RANK_POINTS = 4
CURRENCY_COLOR_TELVAR_STONES = 2
CURRENCY_COLOR_WRIT_VOUCHERS = 5
