--- @meta CurrencyType

--- @alias CurrencyType integer
--- | `CURT_ALLIANCE_POINTS` # 2
--- | `CURT_ARCHIVAL_FORTUNES` # 12
--- | `CURT_CHAOTIC_CREATIA` # 5
--- | `CURT_CROWNS` # 7
--- | `CURT_CROWN_GEMS` # 6
--- | `CURT_ENDEAVOR_SEALS` # 11
--- | `CURT_EVENT_TICKETS` # 9
--- | `CURT_MONEY` # 1
--- | `CURT_NONE` # 0
--- | `CURT_STYLE_STONES` # 8
--- | `CURT_TELVAR_STONES` # 3
--- | `CURT_UNDAUNTED_KEYS` # 10
--- | `CURT_WRIT_VOUCHERS` # 4

CURT_ALLIANCE_POINTS = 2
CURT_ARCHIVAL_FORTUNES = 12
CURT_CHAOTIC_CREATIA = 5
CURT_CROWNS = 7
CURT_CROWN_GEMS = 6
CURT_ENDEAVOR_SEALS = 11
CURT_EVENT_TICKETS = 9
CURT_MONEY = 1
CURT_NONE = 0
CURT_STYLE_STONES = 8
CURT_TELVAR_STONES = 3
CURT_UNDAUNTED_KEYS = 10
CURT_WRIT_VOUCHERS = 4
