--- @meta CustomerServiceAskForHelpCharacterIssueCategory

--- @alias CustomerServiceAskForHelpCharacterIssueCategory integer
--- | `CUSTOMER_SERVICE_ASK_FOR_HELP_CHARACTER_ISSUE_CATEGORY_CHARACTER_RESTORATION` # 1
--- | `CUSTOMER_SERVICE_ASK_FOR_HELP_CHARACTER_ISSUE_CATEGORY_CHAT_AND_VENDORS` # 3
--- | `CUSTOMER_SERVICE_ASK_FOR_HELP_CHARACTER_ISSUE_CATEGORY_GROUP_ACTIVITIES` # 2
--- | `CUSTOMER_SERVICE_ASK_FOR_HELP_CHARACTER_ISSUE_CATEGORY_NONE` # 0
--- | `CUSTOMER_SERVICE_ASK_FOR_HELP_CHARACTER_ISSUE_CATEGORY_SKILLS_AND_ACHIEVEMENTS` # 4

CUSTOMER_SERVICE_ASK_FOR_HELP_CHARACTER_ISSUE_CATEGORY_CHARACTER_RESTORATION = 1
CUSTOMER_SERVICE_ASK_FOR_HELP_CHARACTER_ISSUE_CATEGORY_CHAT_AND_VENDORS = 3
CUSTOMER_SERVICE_ASK_FOR_HELP_CHARACTER_ISSUE_CATEGORY_GROUP_ACTIVITIES = 2
CUSTOMER_SERVICE_ASK_FOR_HELP_CHARACTER_ISSUE_CATEGORY_NONE = 0
CUSTOMER_SERVICE_ASK_FOR_HELP_CHARACTER_ISSUE_CATEGORY_SKILLS_AND_ACHIEVEMENTS = 4
