--- @meta CustomerServiceAskForHelpImpact

--- @alias CustomerServiceAskForHelpImpact integer
--- | `CUSTOMER_SERVICE_ASK_FOR_HELP_IMPACT_CHARACTER_ISSUE` # 1
--- | `CUSTOMER_SERVICE_ASK_FOR_HELP_IMPACT_NONE` # 0
--- | `CUSTOMER_SERVICE_ASK_FOR_HELP_IMPACT_REPORT_GROUP_FINDER_LISTING` # 4
--- | `CUSTOMER_SERVICE_ASK_FOR_HELP_IMPACT_REPORT_GUILD` # 3
--- | `CUSTOMER_SERVICE_ASK_FOR_HELP_IMPACT_REPORT_PLAYER` # 2

CUSTOMER_SERVICE_ASK_FOR_HELP_IMPACT_CHARACTER_ISSUE = 1
CUSTOMER_SERVICE_ASK_FOR_HELP_IMPACT_NONE = 0
CUSTOMER_SERVICE_ASK_FOR_HELP_IMPACT_REPORT_GROUP_FINDER_LISTING = 4
CUSTOMER_SERVICE_ASK_FOR_HELP_IMPACT_REPORT_GUILD = 3
CUSTOMER_SERVICE_ASK_FOR_HELP_IMPACT_REPORT_PLAYER = 2
