--- @meta CustomerServiceSubmitFeedbackCategories

--- @alias CustomerServiceSubmitFeedbackCategories integer
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_CATEGORY_ALLIANCE_WAR` # 1
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_CATEGORY_AUDIO` # 2
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_CATEGORY_COMBAT` # 4
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_CATEGORY_CRAFTING` # 3
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_CATEGORY_CROWN_STORE` # 6
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_CATEGORY_DUNGEONS` # 10
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_CATEGORY_GRAPHICS` # 7
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_CATEGORY_HOUSING` # 11
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_CATEGORY_ITEMS` # 5
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_CATEGORY_JUSTICE` # 12
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_CATEGORY_NONE` # 0
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_CATEGORY_PERFORMANCE` # 13
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_CATEGORY_QUESTS` # 8
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_CATEGORY_TEXT` # 9
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_CATEGORY_UI` # 14

CUSTOMER_SERVICE_SUBMIT_FEEDBACK_CATEGORY_ALLIANCE_WAR = 1
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_CATEGORY_AUDIO = 2
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_CATEGORY_COMBAT = 4
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_CATEGORY_CRAFTING = 3
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_CATEGORY_CROWN_STORE = 6
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_CATEGORY_DUNGEONS = 10
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_CATEGORY_GRAPHICS = 7
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_CATEGORY_HOUSING = 11
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_CATEGORY_ITEMS = 5
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_CATEGORY_JUSTICE = 12
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_CATEGORY_NONE = 0
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_CATEGORY_PERFORMANCE = 13
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_CATEGORY_QUESTS = 8
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_CATEGORY_TEXT = 9
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_CATEGORY_UI = 14
