--- @meta CustomerServiceItemAssistanceCategories

--- @alias CustomerServiceItemAssistanceCategories integer
--- | `CUSTOMER_SERVICE_ITEM_ASSISTANCE_CATEGORY_CANT_ACQUIRE` # 5
--- | `CUSTOMER_SERVICE_ITEM_ASSISTANCE_CATEGORY_DEPRECATED` # 1
--- | `CUSTOMER_SERVICE_ITEM_ASSISTANCE_CATEGORY_FROM_CROWN_STORE` # 3
--- | `CUSTOMER_SERVICE_ITEM_ASSISTANCE_CATEGORY_LOST` # 4
--- | `CUSTOMER_SERVICE_ITEM_ASSISTANCE_CATEGORY_MISSING_CROWNS` # 2
--- | `CUSTOMER_SERVICE_ITEM_ASSISTANCE_CATEGORY_NONE` # 0

CUSTOMER_SERVICE_ITEM_ASSISTANCE_CATEGORY_CANT_ACQUIRE = 5
CUSTOMER_SERVICE_ITEM_ASSISTANCE_CATEGORY_DEPRECATED = 1
CUSTOMER_SERVICE_ITEM_ASSISTANCE_CATEGORY_FROM_CROWN_STORE = 3
CUSTOMER_SERVICE_ITEM_ASSISTANCE_CATEGORY_LOST = 4
CUSTOMER_SERVICE_ITEM_ASSISTANCE_CATEGORY_MISSING_CROWNS = 2
CUSTOMER_SERVICE_ITEM_ASSISTANCE_CATEGORY_NONE = 0
