--- @meta CustomerServiceQuestAssistanceCategories

--- @alias CustomerServiceQuestAssistanceCategories integer
--- | `CUSTOMER_SERVICE_QUEST_ASSISTANCE_CATEGORY_ITEM_MISSING` # 2
--- | `CUSTOMER_SERVICE_QUEST_ASSISTANCE_CATEGORY_NONE` # 0
--- | `CUSTOMER_SERVICE_QUEST_ASSISTANCE_CATEGORY_NPC_MOBS` # 1

CUSTOMER_SERVICE_QUEST_ASSISTANCE_CATEGORY_ITEM_MISSING = 2
CUSTOMER_SERVICE_QUEST_ASSISTANCE_CATEGORY_NONE = 0
CUSTOMER_SERVICE_QUEST_ASSISTANCE_CATEGORY_NPC_MOBS = 1
