--- @meta CustomerServiceSubmitFeedbackSubcategories

--- @alias CustomerServiceSubmitFeedbackSubcategories integer
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_ALLIANCE_WAR_1` # 1
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_ALLIANCE_WAR_2` # 2
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_ALLIANCE_WAR_3` # 3
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_ALLIANCE_WAR_4` # 4
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_ALLIANCE_WAR_5` # 5
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_ALLIANCE_WAR_END` # 6
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_AUDIO_1` # 101
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_AUDIO_2` # 102
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_AUDIO_3` # 103
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_AUDIO_4` # 104
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_AUDIO_END` # 105
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_COMBAT_1` # 301
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_COMBAT_2` # 302
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_COMBAT_3` # 303
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_COMBAT_END` # 304
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_CRAFTING_1` # 201
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_CRAFTING_10` # 210
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_CRAFTING_11` # 211
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_CRAFTING_12` # 212
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_CRAFTING_2` # 202
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_CRAFTING_3` # 203
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_CRAFTING_4` # 204
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_CRAFTING_5` # 205
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_CRAFTING_6` # 206
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_CRAFTING_7` # 207
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_CRAFTING_8` # 208
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_CRAFTING_9` # 209
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_CRAFTING_END` # 213
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_CROWN_STORE_1` # 901
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_CROWN_STORE_2` # 902
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_CROWN_STORE_END` # 903
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_DUNGEONS_1` # 501
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_DUNGEONS_2` # 502
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_DUNGEONS_3` # 503
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_DUNGEONS_4` # 504
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_DUNGEONS_END` # 505
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_GRAPHICS_1` # 601
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_GRAPHICS_2` # 602
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_GRAPHICS_3` # 603
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_GRAPHICS_4` # 604
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_GRAPHICS_5` # 605
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_GRAPHICS_6` # 606
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_GRAPHICS_END` # 607
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_HOUSING_1` # 1001
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_HOUSING_2` # 1002
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_HOUSING_3` # 1003
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_HOUSING_END` # 1004
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_ITEMS_1` # 401
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_ITEMS_2` # 402
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_ITEMS_3` # 403
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_ITEMS_4` # 404
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_ITEMS_5` # 405
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_ITEMS_6` # 406
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_ITEMS_END` # 407
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_JUSTICE_1` # 1101
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_JUSTICE_2` # 1102
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_JUSTICE_3` # 1103
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_JUSTICE_END` # 1104
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_NONE` # 0
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_OTHER` # 100000
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_PERFORMANCE_1` # 1201
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_PERFORMANCE_2` # 1202
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_PERFORMANCE_3` # 1203
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_PERFORMANCE_END` # 1204
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_QUESTS_1` # 701
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_QUESTS_2` # 702
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_QUESTS_3` # 703
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_QUESTS_4` # 704
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_QUESTS_5` # 705
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_QUESTS_END` # 706
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_TEXT_1` # 801
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_TEXT_2` # 802
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_TEXT_3` # 803
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_TEXT_END` # 804
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_UI_1` # 1301
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_UI_2` # 1302
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_UI_3` # 1303
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_UI_4` # 1304
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_UI_5` # 1305
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_UI_6` # 1306
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_UI_END` # 1307

CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_ALLIANCE_WAR_1 = 1
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_ALLIANCE_WAR_2 = 2
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_ALLIANCE_WAR_3 = 3
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_ALLIANCE_WAR_4 = 4
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_ALLIANCE_WAR_5 = 5
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_ALLIANCE_WAR_END = 6
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_AUDIO_1 = 101
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_AUDIO_2 = 102
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_AUDIO_3 = 103
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_AUDIO_4 = 104
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_AUDIO_END = 105
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_COMBAT_1 = 301
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_COMBAT_2 = 302
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_COMBAT_3 = 303
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_COMBAT_END = 304
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_CRAFTING_1 = 201
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_CRAFTING_10 = 210
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_CRAFTING_11 = 211
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_CRAFTING_12 = 212
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_CRAFTING_2 = 202
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_CRAFTING_3 = 203
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_CRAFTING_4 = 204
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_CRAFTING_5 = 205
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_CRAFTING_6 = 206
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_CRAFTING_7 = 207
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_CRAFTING_8 = 208
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_CRAFTING_9 = 209
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_CRAFTING_END = 213
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_CROWN_STORE_1 = 901
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_CROWN_STORE_2 = 902
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_CROWN_STORE_END = 903
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_DUNGEONS_1 = 501
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_DUNGEONS_2 = 502
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_DUNGEONS_3 = 503
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_DUNGEONS_4 = 504
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_DUNGEONS_END = 505
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_GRAPHICS_1 = 601
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_GRAPHICS_2 = 602
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_GRAPHICS_3 = 603
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_GRAPHICS_4 = 604
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_GRAPHICS_5 = 605
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_GRAPHICS_6 = 606
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_GRAPHICS_END = 607
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_HOUSING_1 = 1001
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_HOUSING_2 = 1002
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_HOUSING_3 = 1003
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_HOUSING_END = 1004
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_ITEMS_1 = 401
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_ITEMS_2 = 402
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_ITEMS_3 = 403
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_ITEMS_4 = 404
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_ITEMS_5 = 405
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_ITEMS_6 = 406
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_ITEMS_END = 407
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_JUSTICE_1 = 1101
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_JUSTICE_2 = 1102
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_JUSTICE_3 = 1103
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_JUSTICE_END = 1104
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_NONE = 0
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_OTHER = 100000
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_PERFORMANCE_1 = 1201
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_PERFORMANCE_2 = 1202
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_PERFORMANCE_3 = 1203
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_PERFORMANCE_END = 1204
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_QUESTS_1 = 701
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_QUESTS_2 = 702
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_QUESTS_3 = 703
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_QUESTS_4 = 704
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_QUESTS_5 = 705
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_QUESTS_END = 706
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_TEXT_1 = 801
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_TEXT_2 = 802
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_TEXT_3 = 803
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_TEXT_END = 804
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_UI_1 = 1301
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_UI_2 = 1302
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_UI_3 = 1303
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_UI_4 = 1304
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_UI_5 = 1305
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_UI_6 = 1306
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_UI_END = 1307
