--- @meta CustomerServiceAskForHelpReportPlayerCategory

--- @alias CustomerServiceAskForHelpReportPlayerCategory integer
--- | `CUSTOMER_SERVICE_ASK_FOR_HELP_REPORT_PLAYER_CATEGORY_BAD_ACTIONS` # 3
--- | `CUSTOMER_SERVICE_ASK_FOR_HELP_REPORT_PLAYER_CATEGORY_BAD_LANGUAGE` # 2
--- | `CUSTOMER_SERVICE_ASK_FOR_HELP_REPORT_PLAYER_CATEGORY_NONE` # 0
--- | `CUSTOMER_SERVICE_ASK_FOR_HELP_REPORT_PLAYER_CATEGORY_REAL_WORLD_THREATS` # 1

CUSTOMER_SERVICE_ASK_FOR_HELP_REPORT_PLAYER_CATEGORY_BAD_ACTIONS = 3
CUSTOMER_SERVICE_ASK_FOR_HELP_REPORT_PLAYER_CATEGORY_BAD_LANGUAGE = 2
CUSTOMER_SERVICE_ASK_FOR_HELP_REPORT_PLAYER_CATEGORY_NONE = 0
CUSTOMER_SERVICE_ASK_FOR_HELP_REPORT_PLAYER_CATEGORY_REAL_WORLD_THREATS = 1
