--- @meta CustomerServiceSubmitFeedbackImpacts

--- @alias CustomerServiceSubmitFeedbackImpacts integer
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_IMPACT_AWESOME` # 7
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_IMPACT_COSMETIC` # 5
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_IMPACT_CRASH` # 1
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_IMPACT_DELAYS_PROGRESS` # 4
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_IMPACT_EXPLOIT` # 2
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_IMPACT_IMPAIR` # 3
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_IMPACT_NONE` # 0
--- | `CUSTOMER_SERVICE_SUBMIT_FEEDBACK_IMPACT_SURPRISE` # 6

CUSTOMER_SERVICE_SUBMIT_FEEDBACK_IMPACT_AWESOME = 7
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_IMPACT_COSMETIC = 5
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_IMPACT_CRASH = 1
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_IMPACT_DELAYS_PROGRESS = 4
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_IMPACT_EXPLOIT = 2
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_IMPACT_IMPAIR = 3
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_IMPACT_NONE = 0
CUSTOMER_SERVICE_SUBMIT_FEEDBACK_IMPACT_SURPRISE = 6
