--- @meta DaedricArtifactVisualType

--- @alias DaedricArtifactVisualType integer
--- | `DAEDRIC_ARTIFACT_VISUAL_TYPE_NONE` # 0
--- | `DAEDRIC_ARTIFACT_VISUAL_TYPE_VOLENDRUNG` # 1

DAEDRIC_ARTIFACT_VISUAL_TYPE_NONE = 0
DAEDRIC_ARTIFACT_VISUAL_TYPE_VOLENDRUNG = 1
