--- @meta DamageType

--- @alias DamageType integer
--- | `DAMAGE_TYPE_BLEED` # 12
--- | `DAMAGE_TYPE_COLD` # 6
--- | `DAMAGE_TYPE_DISEASE` # 10
--- | `DAMAGE_TYPE_DROWN` # 9
--- | `DAMAGE_TYPE_EARTH` # 7
--- | `DAMAGE_TYPE_FIRE` # 3
--- | `DAMAGE_TYPE_GENERIC` # 1
--- | `DAMAGE_TYPE_MAGIC` # 8
--- | `DAMAGE_TYPE_NONE` # 0
--- | `DAMAGE_TYPE_OBLIVION` # 5
--- | `DAMAGE_TYPE_PHYSICAL` # 2
--- | `DAMAGE_TYPE_POISON` # 11
--- | `DAMAGE_TYPE_SHOCK` # 4

DAMAGE_TYPE_BLEED = 12
DAMAGE_TYPE_COLD = 6
DAMAGE_TYPE_DISEASE = 10
DAMAGE_TYPE_DROWN = 9
DAMAGE_TYPE_EARTH = 7
DAMAGE_TYPE_FIRE = 3
DAMAGE_TYPE_GENERIC = 1
DAMAGE_TYPE_MAGIC = 8
DAMAGE_TYPE_NONE = 0
DAMAGE_TYPE_OBLIVION = 5
DAMAGE_TYPE_PHYSICAL = 2
DAMAGE_TYPE_POISON = 11
DAMAGE_TYPE_SHOCK = 4
