--- @meta DeathRecapHintImportance

--- @alias DeathRecapHintImportance integer
--- | `DEATH_RECAP_HINT_IMPORTANCE_ALWAYS_INCLUDE` # 1
--- | `DEATH_RECAP_HINT_IMPORTANCE_EXCLUSIVE` # 2
--- | `DEATH_RECAP_HINT_IMPORTANCE_NORMAL` # 0

DEATH_RECAP_HINT_IMPORTANCE_ALWAYS_INCLUDE = 1
DEATH_RECAP_HINT_IMPORTANCE_EXCLUSIVE = 2
DEATH_RECAP_HINT_IMPORTANCE_NORMAL = 0
