--- @meta DeathInterfaceColors

--- @alias DeathInterfaceColors integer
--- | `DEATH_INTERFACE_COLORS_RESPAWN_COOLDOWN_BAR` # 0
--- | `DEATH_INTERFACE_COLORS_RESPAWN_COOLDOWN_FILL_GAMEPAD` # 1
--- | `DEATH_INTERFACE_COLORS_RESPAWN_COOLDOWN_FILL_KEYBOARD` # 2

DEATH_INTERFACE_COLORS_RESPAWN_COOLDOWN_BAR = 0
DEATH_INTERFACE_COLORS_RESPAWN_COOLDOWN_FILL_GAMEPAD = 1
DEATH_INTERFACE_COLORS_RESPAWN_COOLDOWN_FILL_KEYBOARD = 2
