--- @meta DeconstructActionName

--- @alias DeconstructActionName integer
--- | `DECONSTRUCT_ACTION_NAME_DECONSTRUCT` # 2
--- | `DECONSTRUCT_ACTION_NAME_EXTRACT` # 1
--- | `DECONSTRUCT_ACTION_NAME_FILLET` # 3
--- | `DECONSTRUCT_ACTION_NAME_REFINE` # 0

DECONSTRUCT_ACTION_NAME_DECONSTRUCT = 2
DECONSTRUCT_ACTION_NAME_EXTRACT = 1
DECONSTRUCT_ACTION_NAME_FILLET = 3
DECONSTRUCT_ACTION_NAME_REFINE = 0
