--- @meta DepthOfFieldMode

--- @alias DepthOfFieldMode integer
--- | `DEPTH_OF_FIELD_MODE_CIRCULAR` # 3
--- | `DEPTH_OF_FIELD_MODE_OFF` # 0
--- | `DEPTH_OF_FIELD_MODE_SIMPLE` # 1
--- | `DEPTH_OF_FIELD_MODE_SMOOTH` # 2

DEPTH_OF_FIELD_MODE_CIRCULAR = 3
DEPTH_OF_FIELD_MODE_OFF = 0
DEPTH_OF_FIELD_MODE_SIMPLE = 1
DEPTH_OF_FIELD_MODE_SMOOTH = 2
