--- @meta DerivedStats

--- @alias DerivedStats integer
--- | `STAT_ARMOR_RATING` # 3
--- | `STAT_ATTACK_POWER` # 1
--- | `STAT_BLOCK` # 14
--- | `STAT_CRITICAL_CHANCE` # 28
--- | `STAT_CRITICAL_RESISTANCE` # 24
--- | `STAT_CRITICAL_STRIKE` # 16
--- | `STAT_DAMAGE_RESIST_BLEED` # 15
--- | `STAT_DAMAGE_RESIST_COLD` # 42
--- | `STAT_DAMAGE_RESIST_DISEASE` # 46
--- | `STAT_DAMAGE_RESIST_DROWN` # 45
--- | `STAT_DAMAGE_RESIST_EARTH` # 43
--- | `STAT_DAMAGE_RESIST_FIRE` # 39
--- | `STAT_DAMAGE_RESIST_GENERIC` # 37
--- | `STAT_DAMAGE_RESIST_MAGIC` # 44
--- | `STAT_DAMAGE_RESIST_OBLIVION` # 41
--- | `STAT_DAMAGE_RESIST_PHYSICAL` # 38
--- | `STAT_DAMAGE_RESIST_POISON` # 47
--- | `STAT_DAMAGE_RESIST_SHOCK` # 40
--- | `STAT_DAMAGE_RESIST_START` # 36
--- | `STAT_DODGE` # 11
--- | `STAT_HEALING_DONE` # 12
--- | `STAT_HEALING_TAKEN` # 10
--- | `STAT_HEALTH_MAX` # 7
--- | `STAT_HEALTH_REGEN_COMBAT` # 8
--- | `STAT_HEALTH_REGEN_IDLE` # 9
--- | `STAT_MAGICKA_MAX` # 4
--- | `STAT_MAGICKA_REGEN_COMBAT` # 5
--- | `STAT_MAGICKA_REGEN_IDLE` # 6
--- | `STAT_MISS` # 32
--- | `STAT_MITIGATION` # 20
--- | `STAT_MOUNT_STAMINA_MAX` # 48
--- | `STAT_MOUNT_STAMINA_REGEN_COMBAT` # 49
--- | `STAT_MOUNT_STAMINA_REGEN_MOVING` # 50
--- | `STAT_NONE` # 0
--- | `STAT_OFFENSIVE_PENETRATION` # 27
--- | `STAT_PHYSICAL_PENETRATION` # 33
--- | `STAT_PHYSICAL_RESIST` # 22
--- | `STAT_POWER` # 35
--- | `STAT_SPELL_CRITICAL` # 23
--- | `STAT_SPELL_MITIGATION` # 26
--- | `STAT_SPELL_PENETRATION` # 34
--- | `STAT_SPELL_POWER` # 25
--- | `STAT_SPELL_RESIST` # 13
--- | `STAT_STAMINA_MAX` # 29
--- | `STAT_STAMINA_REGEN_COMBAT` # 30
--- | `STAT_STAMINA_REGEN_IDLE` # 31
--- | `STAT_WEAPON_AND_SPELL_DAMAGE` # 2

STAT_ARMOR_RATING = 3
STAT_ATTACK_POWER = 1
STAT_BLOCK = 14
STAT_CRITICAL_CHANCE = 28
STAT_CRITICAL_RESISTANCE = 24
STAT_CRITICAL_STRIKE = 16
STAT_DAMAGE_RESIST_BLEED = 15
STAT_DAMAGE_RESIST_COLD = 42
STAT_DAMAGE_RESIST_DISEASE = 46
STAT_DAMAGE_RESIST_DROWN = 45
STAT_DAMAGE_RESIST_EARTH = 43
STAT_DAMAGE_RESIST_FIRE = 39
STAT_DAMAGE_RESIST_GENERIC = 37
STAT_DAMAGE_RESIST_MAGIC = 44
STAT_DAMAGE_RESIST_OBLIVION = 41
STAT_DAMAGE_RESIST_PHYSICAL = 38
STAT_DAMAGE_RESIST_POISON = 47
STAT_DAMAGE_RESIST_SHOCK = 40
STAT_DAMAGE_RESIST_START = 36
STAT_DODGE = 11
STAT_HEALING_DONE = 12
STAT_HEALING_TAKEN = 10
STAT_HEALTH_MAX = 7
STAT_HEALTH_REGEN_COMBAT = 8
STAT_HEALTH_REGEN_IDLE = 9
STAT_MAGICKA_MAX = 4
STAT_MAGICKA_REGEN_COMBAT = 5
STAT_MAGICKA_REGEN_IDLE = 6
STAT_MISS = 32
STAT_MITIGATION = 20
STAT_MOUNT_STAMINA_MAX = 48
STAT_MOUNT_STAMINA_REGEN_COMBAT = 49
STAT_MOUNT_STAMINA_REGEN_MOVING = 50
STAT_NONE = 0
STAT_OFFENSIVE_PENETRATION = 27
STAT_PHYSICAL_PENETRATION = 33
STAT_PHYSICAL_RESIST = 22
STAT_POWER = 35
STAT_SPELL_CRITICAL = 23
STAT_SPELL_MITIGATION = 26
STAT_SPELL_PENETRATION = 34
STAT_SPELL_POWER = 25
STAT_SPELL_RESIST = 13
STAT_STAMINA_MAX = 29
STAT_STAMINA_REGEN_COMBAT = 30
STAT_STAMINA_REGEN_IDLE = 31
STAT_WEAPON_AND_SPELL_DAMAGE = 2
