--- @meta DiggingGameOverFlags

--- @alias DiggingGameOverFlags integer
--- | `ANTIQUITY_DIGGING_GAME_OVER_FLAGS_ABORTED` # 4
--- | `ANTIQUITY_DIGGING_GAME_OVER_FLAGS_ANTIQUITY_BROKEN` # 1
--- | `ANTIQUITY_DIGGING_GAME_OVER_FLAGS_ANTIQUITY_BROKEN_AND_OUT_OF_TIME` # 3
--- | `ANTIQUITY_DIGGING_GAME_OVER_FLAGS_OUT_OF_TIME` # 2
--- | `ANTIQUITY_DIGGING_GAME_OVER_FLAGS_VICTORY` # 0

ANTIQUITY_DIGGING_GAME_OVER_FLAGS_ABORTED = 4
ANTIQUITY_DIGGING_GAME_OVER_FLAGS_ANTIQUITY_BROKEN = 1
ANTIQUITY_DIGGING_GAME_OVER_FLAGS_ANTIQUITY_BROKEN_AND_OUT_OF_TIME = 3
ANTIQUITY_DIGGING_GAME_OVER_FLAGS_OUT_OF_TIME = 2
ANTIQUITY_DIGGING_GAME_OVER_FLAGS_VICTORY = 0
