--- @meta DiggingActiveSkillUseResult

--- @alias DiggingActiveSkillUseResult integer
--- | `DIGGING_ACTIVE_SKILL_USE_RESULT_AT_BOTTOM` # 6
--- | `DIGGING_ACTIVE_SKILL_USE_RESULT_CANNOT_RADAR_BONUS_LOOT` # 5
--- | `DIGGING_ACTIVE_SKILL_USE_RESULT_GAME_NOT_ACTIVE` # 1
--- | `DIGGING_ACTIVE_SKILL_USE_RESULT_INVALID_LOCATION` # 2
--- | `DIGGING_ACTIVE_SKILL_USE_RESULT_LOCKED` # 3
--- | `DIGGING_ACTIVE_SKILL_USE_RESULT_NOT_ENOUGH_DIG_POWER` # 4
--- | `DIGGING_ACTIVE_SKILL_USE_RESULT_NO_MORE_RADARS` # 8
--- | `DIGGING_ACTIVE_SKILL_USE_RESULT_RADAR_TOO_DEEP` # 7
--- | `DIGGING_ACTIVE_SKILL_USE_RESULT_SUCCESS` # 0

DIGGING_ACTIVE_SKILL_USE_RESULT_AT_BOTTOM = 6
DIGGING_ACTIVE_SKILL_USE_RESULT_CANNOT_RADAR_BONUS_LOOT = 5
DIGGING_ACTIVE_SKILL_USE_RESULT_GAME_NOT_ACTIVE = 1
DIGGING_ACTIVE_SKILL_USE_RESULT_INVALID_LOCATION = 2
DIGGING_ACTIVE_SKILL_USE_RESULT_LOCKED = 3
DIGGING_ACTIVE_SKILL_USE_RESULT_NOT_ENOUGH_DIG_POWER = 4
DIGGING_ACTIVE_SKILL_USE_RESULT_NO_MORE_RADARS = 8
DIGGING_ACTIVE_SKILL_USE_RESULT_RADAR_TOO_DEEP = 7
DIGGING_ACTIVE_SKILL_USE_RESULT_SUCCESS = 0
