--- @meta DiggingActiveSkills

--- @alias DiggingActiveSkills integer
--- | `DIGGING_ACTIVE_SKILL_BASIC_EXCAVATION` # 0
--- | `DIGGING_ACTIVE_SKILL_CAREFUL_TOUCH` # 3
--- | `DIGGING_ACTIVE_SKILL_HEAVY_SHOVEL` # 2
--- | `DIGGING_ACTIVE_SKILL_RADAR_SENSE` # 1

DIGGING_ACTIVE_SKILL_BASIC_EXCAVATION = 0
DIGGING_ACTIVE_SKILL_CAREFUL_TOUCH = 3
DIGGING_ACTIVE_SKILL_HEAVY_SHOVEL = 2
DIGGING_ACTIVE_SKILL_RADAR_SENSE = 1
