--- @meta DisguiseState

--- @alias DisguiseState integer
--- | `DISGUISE_STATE_DANGER` # 2
--- | `DISGUISE_STATE_DISCOVERED` # 4
--- | `DISGUISE_STATE_DISGUISED` # 1
--- | `DISGUISE_STATE_NONE` # 0
--- | `DISGUISE_STATE_SUSPICIOUS` # 3

DISGUISE_STATE_DANGER = 2
DISGUISE_STATE_DISCOVERED = 4
DISGUISE_STATE_DISGUISED = 1
DISGUISE_STATE_NONE = 0
DISGUISE_STATE_SUSPICIOUS = 3
