--- @meta DuelState

--- @alias DuelState integer
--- | `DUEL_STATE_DUELING` # 3
--- | `DUEL_STATE_DUEL_PENDING` # 4
--- | `DUEL_STATE_DUEL_TERMINATING` # 5
--- | `DUEL_STATE_IDLE` # 0
--- | `DUEL_STATE_INVITE_CONSIDERING` # 2
--- | `DUEL_STATE_INVITE_REQUESTING` # 1

DUEL_STATE_DUELING = 3
DUEL_STATE_DUEL_PENDING = 4
DUEL_STATE_DUEL_TERMINATING = 5
DUEL_STATE_IDLE = 0
DUEL_STATE_INVITE_CONSIDERING = 2
DUEL_STATE_INVITE_REQUESTING = 1
