--- @meta DuelInviteFailReason

--- @alias DuelInviteFailReason integer
--- | `DUEL_INVITE_FAIL_REASON_INELIGIBLE_AREA` # 19
--- | `DUEL_INVITE_FAIL_REASON_NONE` # 0
--- | `DUEL_INVITE_FAIL_REASON_NOT_FULL_HEALTH` # 22
--- | `DUEL_INVITE_FAIL_REASON_RECENTLY_DECLINED` # 20
--- | `DUEL_INVITE_FAIL_REASON_SELF_ACTIVE_DUEL` # 7
--- | `DUEL_INVITE_FAIL_REASON_SELF_CONSIDERING_INVITE` # 6
--- | `DUEL_INVITE_FAIL_REASON_SELF_CRAFTING` # 17
--- | `DUEL_INVITE_FAIL_REASON_SELF_DEAD` # 11
--- | `DUEL_INVITE_FAIL_REASON_SELF_IN_COMBAT` # 15
--- | `DUEL_INVITE_FAIL_REASON_SELF_PENDING_REQUEST` # 5
--- | `DUEL_INVITE_FAIL_REASON_SELF_SWIMMING` # 13
--- | `DUEL_INVITE_FAIL_REASON_TARGET_ACTIVE_DUEL` # 10
--- | `DUEL_INVITE_FAIL_REASON_TARGET_CONSIDERING_INVITE` # 9
--- | `DUEL_INVITE_FAIL_REASON_TARGET_CRAFTING` # 18
--- | `DUEL_INVITE_FAIL_REASON_TARGET_DEAD` # 12
--- | `DUEL_INVITE_FAIL_REASON_TARGET_INVALID` # 2
--- | `DUEL_INVITE_FAIL_REASON_TARGET_IN_COMBAT` # 16
--- | `DUEL_INVITE_FAIL_REASON_TARGET_PENDING_REQUEST` # 8
--- | `DUEL_INVITE_FAIL_REASON_TARGET_SELF` # 3
--- | `DUEL_INVITE_FAIL_REASON_TARGET_SWIMMING` # 14
--- | `DUEL_INVITE_FAIL_REASON_TARGET_UNAVAILABLE` # 1
--- | `DUEL_INVITE_FAIL_REASON_TOO_FAR` # 4
--- | `DUEL_INVITE_FAIL_REASON_TOO_MANY_NEARBY` # 21

DUEL_INVITE_FAIL_REASON_INELIGIBLE_AREA = 19
DUEL_INVITE_FAIL_REASON_NONE = 0
DUEL_INVITE_FAIL_REASON_NOT_FULL_HEALTH = 22
DUEL_INVITE_FAIL_REASON_RECENTLY_DECLINED = 20
DUEL_INVITE_FAIL_REASON_SELF_ACTIVE_DUEL = 7
DUEL_INVITE_FAIL_REASON_SELF_CONSIDERING_INVITE = 6
DUEL_INVITE_FAIL_REASON_SELF_CRAFTING = 17
DUEL_INVITE_FAIL_REASON_SELF_DEAD = 11
DUEL_INVITE_FAIL_REASON_SELF_IN_COMBAT = 15
DUEL_INVITE_FAIL_REASON_SELF_PENDING_REQUEST = 5
DUEL_INVITE_FAIL_REASON_SELF_SWIMMING = 13
DUEL_INVITE_FAIL_REASON_TARGET_ACTIVE_DUEL = 10
DUEL_INVITE_FAIL_REASON_TARGET_CONSIDERING_INVITE = 9
DUEL_INVITE_FAIL_REASON_TARGET_CRAFTING = 18
DUEL_INVITE_FAIL_REASON_TARGET_DEAD = 12
DUEL_INVITE_FAIL_REASON_TARGET_INVALID = 2
DUEL_INVITE_FAIL_REASON_TARGET_IN_COMBAT = 16
DUEL_INVITE_FAIL_REASON_TARGET_PENDING_REQUEST = 8
DUEL_INVITE_FAIL_REASON_TARGET_SELF = 3
DUEL_INVITE_FAIL_REASON_TARGET_SWIMMING = 14
DUEL_INVITE_FAIL_REASON_TARGET_UNAVAILABLE = 1
DUEL_INVITE_FAIL_REASON_TOO_FAR = 4
DUEL_INVITE_FAIL_REASON_TOO_MANY_NEARBY = 21
