--- @meta DungeonDifficulty

--- @alias DungeonDifficulty integer
--- | `DUNGEON_DIFFICULTY_NONE` # 0
--- | `DUNGEON_DIFFICULTY_NORMAL` # 1
--- | `DUNGEON_DIFFICULTY_VETERAN` # 2

DUNGEON_DIFFICULTY_NONE = 0
DUNGEON_DIFFICULTY_NORMAL = 1
DUNGEON_DIFFICULTY_VETERAN = 2
