--- @meta DyeHueCategory

--- @alias DyeHueCategory integer
--- | `DYE_HUE_CATEGORY_BLUE` # 3
--- | `DYE_HUE_CATEGORY_BROWN` # 5
--- | `DYE_HUE_CATEGORY_GREEN` # 2
--- | `DYE_HUE_CATEGORY_GREY` # 6
--- | `DYE_HUE_CATEGORY_IRIDESCENT` # 8
--- | `DYE_HUE_CATEGORY_MIXED` # 7
--- | `DYE_HUE_CATEGORY_PURPLE` # 4
--- | `DYE_HUE_CATEGORY_RED` # 0
--- | `DYE_HUE_CATEGORY_YELLOW` # 1

DYE_HUE_CATEGORY_BLUE = 3
DYE_HUE_CATEGORY_BROWN = 5
DYE_HUE_CATEGORY_GREEN = 2
DYE_HUE_CATEGORY_GREY = 6
DYE_HUE_CATEGORY_IRIDESCENT = 8
DYE_HUE_CATEGORY_MIXED = 7
DYE_HUE_CATEGORY_PURPLE = 4
DYE_HUE_CATEGORY_RED = 0
DYE_HUE_CATEGORY_YELLOW = 1
