--- @meta DyeStampUseResult

--- @alias DyeStampUseResult integer
--- | `DYE_STAMP_USE_RESULT_COLLECTIBLES_HAVE_SAME_DYES` # 3
--- | `DYE_STAMP_USE_RESULT_COLLECTIBLES_NOT_ACTIVE` # 6
--- | `DYE_STAMP_USE_RESULT_ITEMS_HAVE_SAME_DYES` # 1
--- | `DYE_STAMP_USE_RESULT_NONE` # 0
--- | `DYE_STAMP_USE_RESULT_NO_SUCH_DYE_STAMP` # 5
--- | `DYE_STAMP_USE_RESULT_NO_VALID_COLLECTIBLES` # 4
--- | `DYE_STAMP_USE_RESULT_NO_VALID_ITEMS` # 2

DYE_STAMP_USE_RESULT_COLLECTIBLES_HAVE_SAME_DYES = 3
DYE_STAMP_USE_RESULT_COLLECTIBLES_NOT_ACTIVE = 6
DYE_STAMP_USE_RESULT_ITEMS_HAVE_SAME_DYES = 1
DYE_STAMP_USE_RESULT_NONE = 0
DYE_STAMP_USE_RESULT_NO_SUCH_DYE_STAMP = 5
DYE_STAMP_USE_RESULT_NO_VALID_COLLECTIBLES = 4
DYE_STAMP_USE_RESULT_NO_VALID_ITEMS = 2
