--- @meta EffectResult

--- @alias EffectResult integer
--- | `EFFECT_RESULT_FADED` # 2
--- | `EFFECT_RESULT_FULL_REFRESH` # 4
--- | `EFFECT_RESULT_GAINED` # 1
--- | `EFFECT_RESULT_TRANSFER` # 5
--- | `EFFECT_RESULT_UPDATED` # 3

EFFECT_RESULT_FADED = 2
EFFECT_RESULT_FULL_REFRESH = 4
EFFECT_RESULT_GAINED = 1
EFFECT_RESULT_TRANSFER = 5
EFFECT_RESULT_UPDATED = 3
