--- @meta EmoteHidesHelmet

--- @alias EmoteHidesHelmet integer
--- | `EMOTE_HIDES_HELMET_ALL` # 2
--- | `EMOTE_HIDES_HELMET_CLOSE_FACED_ONLY` # 1
--- | `EMOTE_HIDES_HELMET_NONE` # 0

EMOTE_HIDES_HELMET_ALL = 2
EMOTE_HIDES_HELMET_CLOSE_FACED_ONLY = 1
EMOTE_HIDES_HELMET_NONE = 0
