--- @meta EmoteCategory

--- @alias EmoteCategory integer
--- | `EMOTE_CATEGORY_CEREMONIAL` # 1
--- | `EMOTE_CATEGORY_CHEERS_AND_JEERS` # 2
--- | `EMOTE_CATEGORY_COLLECTED` # 14
--- | `EMOTE_CATEGORY_DEPRECATED` # 3
--- | `EMOTE_CATEGORY_EMOTION` # 4
--- | `EMOTE_CATEGORY_ENTERTAINMENT` # 5
--- | `EMOTE_CATEGORY_FOOD_AND_DRINK` # 6
--- | `EMOTE_CATEGORY_GIVE_DIRECTIONS` # 7
--- | `EMOTE_CATEGORY_INVALID` # 0
--- | `EMOTE_CATEGORY_PERPETUAL` # 8
--- | `EMOTE_CATEGORY_PERSONALITY_OVERRIDE` # 13
--- | `EMOTE_CATEGORY_PHYSICAL` # 9
--- | `EMOTE_CATEGORY_POSES_AND_FIDGETS` # 10
--- | `EMOTE_CATEGORY_PROP` # 11
--- | `EMOTE_CATEGORY_SOCIAL` # 12

EMOTE_CATEGORY_CEREMONIAL = 1
EMOTE_CATEGORY_CHEERS_AND_JEERS = 2
EMOTE_CATEGORY_COLLECTED = 14
EMOTE_CATEGORY_DEPRECATED = 3
EMOTE_CATEGORY_EMOTION = 4
EMOTE_CATEGORY_ENTERTAINMENT = 5
EMOTE_CATEGORY_FOOD_AND_DRINK = 6
EMOTE_CATEGORY_GIVE_DIRECTIONS = 7
EMOTE_CATEGORY_INVALID = 0
EMOTE_CATEGORY_PERPETUAL = 8
EMOTE_CATEGORY_PERSONALITY_OVERRIDE = 13
EMOTE_CATEGORY_PHYSICAL = 9
EMOTE_CATEGORY_POSES_AND_FIDGETS = 10
EMOTE_CATEGORY_PROP = 11
EMOTE_CATEGORY_SOCIAL = 12
