--- @meta EnchantmentSearchCategoryType

--- @alias EnchantmentSearchCategoryType integer
--- | `ENCHANTMENT_SEARCH_CATEGORY_ABSORB_HEALTH` # 20
--- | `ENCHANTMENT_SEARCH_CATEGORY_ABSORB_MAGICKA` # 23
--- | `ENCHANTMENT_SEARCH_CATEGORY_ABSORB_STAMINA` # 22
--- | `ENCHANTMENT_SEARCH_CATEGORY_BEFOULED_WEAPON` # 1
--- | `ENCHANTMENT_SEARCH_CATEGORY_BERSERKER` # 2
--- | `ENCHANTMENT_SEARCH_CATEGORY_CHARGED_WEAPON` # 3
--- | `ENCHANTMENT_SEARCH_CATEGORY_DAMAGE_HEALTH` # 24
--- | `ENCHANTMENT_SEARCH_CATEGORY_DAMAGE_SHIELD` # 10
--- | `ENCHANTMENT_SEARCH_CATEGORY_DECREASE_PHYSICAL_DAMAGE` # 33
--- | `ENCHANTMENT_SEARCH_CATEGORY_DECREASE_SPELL_DAMAGE` # 34
--- | `ENCHANTMENT_SEARCH_CATEGORY_DISEASE_RESISTANT` # 5
--- | `ENCHANTMENT_SEARCH_CATEGORY_FIERY_WEAPON` # 6
--- | `ENCHANTMENT_SEARCH_CATEGORY_FIRE_RESISTANT` # 7
--- | `ENCHANTMENT_SEARCH_CATEGORY_FROST_RESISTANT` # 8
--- | `ENCHANTMENT_SEARCH_CATEGORY_FROZEN_WEAPON` # 9
--- | `ENCHANTMENT_SEARCH_CATEGORY_HEALTH` # 11
--- | `ENCHANTMENT_SEARCH_CATEGORY_HEALTH_REGEN` # 12
--- | `ENCHANTMENT_SEARCH_CATEGORY_INCREASE_BASH_DAMAGE` # 27
--- | `ENCHANTMENT_SEARCH_CATEGORY_INCREASE_PHYSICAL_DAMAGE` # 31
--- | `ENCHANTMENT_SEARCH_CATEGORY_INCREASE_POTION_EFFECTIVENESS` # 29
--- | `ENCHANTMENT_SEARCH_CATEGORY_INCREASE_SPELL_DAMAGE` # 32
--- | `ENCHANTMENT_SEARCH_CATEGORY_INVALID` # 1000
--- | `ENCHANTMENT_SEARCH_CATEGORY_MAGICKA` # 13
--- | `ENCHANTMENT_SEARCH_CATEGORY_MAGICKA_REGEN` # 14
--- | `ENCHANTMENT_SEARCH_CATEGORY_NONE` # 0
--- | `ENCHANTMENT_SEARCH_CATEGORY_POISONED_WEAPON` # 16
--- | `ENCHANTMENT_SEARCH_CATEGORY_POISON_RESISTANT` # 15
--- | `ENCHANTMENT_SEARCH_CATEGORY_PRISMATIC_DEFENSE` # 36
--- | `ENCHANTMENT_SEARCH_CATEGORY_PRISMATIC_ONSLAUGHT` # 35
--- | `ENCHANTMENT_SEARCH_CATEGORY_PRISMATIC_REGEN` # 37
--- | `ENCHANTMENT_SEARCH_CATEGORY_REDUCE_ARMOR` # 4
--- | `ENCHANTMENT_SEARCH_CATEGORY_REDUCE_BLOCK_AND_BASH` # 28
--- | `ENCHANTMENT_SEARCH_CATEGORY_REDUCE_FEAT_COST` # 26
--- | `ENCHANTMENT_SEARCH_CATEGORY_REDUCE_POTION_COOLDOWN` # 30
--- | `ENCHANTMENT_SEARCH_CATEGORY_REDUCE_POWER` # 19
--- | `ENCHANTMENT_SEARCH_CATEGORY_REDUCE_SPELL_COST` # 25
--- | `ENCHANTMENT_SEARCH_CATEGORY_SHOCK_RESISTANT` # 21
--- | `ENCHANTMENT_SEARCH_CATEGORY_STAMINA` # 17
--- | `ENCHANTMENT_SEARCH_CATEGORY_STAMINA_REGEN` # 18

ENCHANTMENT_SEARCH_CATEGORY_ABSORB_HEALTH = 20
ENCHANTMENT_SEARCH_CATEGORY_ABSORB_MAGICKA = 23
ENCHANTMENT_SEARCH_CATEGORY_ABSORB_STAMINA = 22
ENCHANTMENT_SEARCH_CATEGORY_BEFOULED_WEAPON = 1
ENCHANTMENT_SEARCH_CATEGORY_BERSERKER = 2
ENCHANTMENT_SEARCH_CATEGORY_CHARGED_WEAPON = 3
ENCHANTMENT_SEARCH_CATEGORY_DAMAGE_HEALTH = 24
ENCHANTMENT_SEARCH_CATEGORY_DAMAGE_SHIELD = 10
ENCHANTMENT_SEARCH_CATEGORY_DECREASE_PHYSICAL_DAMAGE = 33
ENCHANTMENT_SEARCH_CATEGORY_DECREASE_SPELL_DAMAGE = 34
ENCHANTMENT_SEARCH_CATEGORY_DISEASE_RESISTANT = 5
ENCHANTMENT_SEARCH_CATEGORY_FIERY_WEAPON = 6
ENCHANTMENT_SEARCH_CATEGORY_FIRE_RESISTANT = 7
ENCHANTMENT_SEARCH_CATEGORY_FROST_RESISTANT = 8
ENCHANTMENT_SEARCH_CATEGORY_FROZEN_WEAPON = 9
ENCHANTMENT_SEARCH_CATEGORY_HEALTH = 11
ENCHANTMENT_SEARCH_CATEGORY_HEALTH_REGEN = 12
ENCHANTMENT_SEARCH_CATEGORY_INCREASE_BASH_DAMAGE = 27
ENCHANTMENT_SEARCH_CATEGORY_INCREASE_PHYSICAL_DAMAGE = 31
ENCHANTMENT_SEARCH_CATEGORY_INCREASE_POTION_EFFECTIVENESS = 29
ENCHANTMENT_SEARCH_CATEGORY_INCREASE_SPELL_DAMAGE = 32
ENCHANTMENT_SEARCH_CATEGORY_INVALID = 1000
ENCHANTMENT_SEARCH_CATEGORY_MAGICKA = 13
ENCHANTMENT_SEARCH_CATEGORY_MAGICKA_REGEN = 14
ENCHANTMENT_SEARCH_CATEGORY_NONE = 0
ENCHANTMENT_SEARCH_CATEGORY_POISONED_WEAPON = 16
ENCHANTMENT_SEARCH_CATEGORY_POISON_RESISTANT = 15
ENCHANTMENT_SEARCH_CATEGORY_PRISMATIC_DEFENSE = 36
ENCHANTMENT_SEARCH_CATEGORY_PRISMATIC_ONSLAUGHT = 35
ENCHANTMENT_SEARCH_CATEGORY_PRISMATIC_REGEN = 37
ENCHANTMENT_SEARCH_CATEGORY_REDUCE_ARMOR = 4
ENCHANTMENT_SEARCH_CATEGORY_REDUCE_BLOCK_AND_BASH = 28
ENCHANTMENT_SEARCH_CATEGORY_REDUCE_FEAT_COST = 26
ENCHANTMENT_SEARCH_CATEGORY_REDUCE_POTION_COOLDOWN = 30
ENCHANTMENT_SEARCH_CATEGORY_REDUCE_POWER = 19
ENCHANTMENT_SEARCH_CATEGORY_REDUCE_SPELL_COST = 25
ENCHANTMENT_SEARCH_CATEGORY_SHOCK_RESISTANT = 21
ENCHANTMENT_SEARCH_CATEGORY_STAMINA = 17
ENCHANTMENT_SEARCH_CATEGORY_STAMINA_REGEN = 18
