--- @meta EncounterLogLineType

--- @alias EncounterLogLineType integer
--- | `ENCOUNTER_LOG_LINE_TYPE_ABILITY_INFO` # 8
--- | `ENCOUNTER_LOG_LINE_TYPE_BEGIN_CAST` # 14
--- | `ENCOUNTER_LOG_LINE_TYPE_BEGIN_COMBAT` # 2
--- | `ENCOUNTER_LOG_LINE_TYPE_BEGIN_LOG` # 0
--- | `ENCOUNTER_LOG_LINE_TYPE_BEGIN_TRIAL` # 17
--- | `ENCOUNTER_LOG_LINE_TYPE_COMBAT_EVENT` # 4
--- | `ENCOUNTER_LOG_LINE_TYPE_EFFECT_CHANGED` # 9
--- | `ENCOUNTER_LOG_LINE_TYPE_EFFECT_INFO` # 10
--- | `ENCOUNTER_LOG_LINE_TYPE_ENDLESS_DUNGEON_BEGIN` # 21
--- | `ENCOUNTER_LOG_LINE_TYPE_ENDLESS_DUNGEON_BUFF_ADDED` # 24
--- | `ENCOUNTER_LOG_LINE_TYPE_ENDLESS_DUNGEON_BUFF_REMOVED` # 25
--- | `ENCOUNTER_LOG_LINE_TYPE_ENDLESS_DUNGEON_END` # 22
--- | `ENCOUNTER_LOG_LINE_TYPE_ENDLESS_DUNGEON_INIT` # 20
--- | `ENCOUNTER_LOG_LINE_TYPE_ENDLESS_DUNGEON_STAGE_END` # 23
--- | `ENCOUNTER_LOG_LINE_TYPE_END_CAST` # 15
--- | `ENCOUNTER_LOG_LINE_TYPE_END_COMBAT` # 3
--- | `ENCOUNTER_LOG_LINE_TYPE_END_LOG` # 1
--- | `ENCOUNTER_LOG_LINE_TYPE_END_TRIAL` # 18
--- | `ENCOUNTER_LOG_LINE_TYPE_HEALTH_REGEN` # 19
--- | `ENCOUNTER_LOG_LINE_TYPE_MAP_CHANGED` # 11
--- | `ENCOUNTER_LOG_LINE_TYPE_PLAYER_INFO` # 13
--- | `ENCOUNTER_LOG_LINE_TYPE_TRIAL_INIT` # 16
--- | `ENCOUNTER_LOG_LINE_TYPE_UNIT_ADDED` # 5
--- | `ENCOUNTER_LOG_LINE_TYPE_UNIT_CHANGED` # 7
--- | `ENCOUNTER_LOG_LINE_TYPE_UNIT_REMOVED` # 6
--- | `ENCOUNTER_LOG_LINE_TYPE_ZONE_CHANGED` # 12

ENCOUNTER_LOG_LINE_TYPE_ABILITY_INFO = 8
ENCOUNTER_LOG_LINE_TYPE_BEGIN_CAST = 14
ENCOUNTER_LOG_LINE_TYPE_BEGIN_COMBAT = 2
ENCOUNTER_LOG_LINE_TYPE_BEGIN_LOG = 0
ENCOUNTER_LOG_LINE_TYPE_BEGIN_TRIAL = 17
ENCOUNTER_LOG_LINE_TYPE_COMBAT_EVENT = 4
ENCOUNTER_LOG_LINE_TYPE_EFFECT_CHANGED = 9
ENCOUNTER_LOG_LINE_TYPE_EFFECT_INFO = 10
ENCOUNTER_LOG_LINE_TYPE_ENDLESS_DUNGEON_BEGIN = 21
ENCOUNTER_LOG_LINE_TYPE_ENDLESS_DUNGEON_BUFF_ADDED = 24
ENCOUNTER_LOG_LINE_TYPE_ENDLESS_DUNGEON_BUFF_REMOVED = 25
ENCOUNTER_LOG_LINE_TYPE_ENDLESS_DUNGEON_END = 22
ENCOUNTER_LOG_LINE_TYPE_ENDLESS_DUNGEON_INIT = 20
ENCOUNTER_LOG_LINE_TYPE_ENDLESS_DUNGEON_STAGE_END = 23
ENCOUNTER_LOG_LINE_TYPE_END_CAST = 15
ENCOUNTER_LOG_LINE_TYPE_END_COMBAT = 3
ENCOUNTER_LOG_LINE_TYPE_END_LOG = 1
ENCOUNTER_LOG_LINE_TYPE_END_TRIAL = 18
ENCOUNTER_LOG_LINE_TYPE_HEALTH_REGEN = 19
ENCOUNTER_LOG_LINE_TYPE_MAP_CHANGED = 11
ENCOUNTER_LOG_LINE_TYPE_PLAYER_INFO = 13
ENCOUNTER_LOG_LINE_TYPE_TRIAL_INIT = 16
ENCOUNTER_LOG_LINE_TYPE_UNIT_ADDED = 5
ENCOUNTER_LOG_LINE_TYPE_UNIT_CHANGED = 7
ENCOUNTER_LOG_LINE_TYPE_UNIT_REMOVED = 6
ENCOUNTER_LOG_LINE_TYPE_ZONE_CHANGED = 12
