--- @meta EncounterLogUnitType

--- @alias EncounterLogUnitType integer
--- | `ENCOUNTER_LOG_UNIT_TYPE_MONSTER` # 1
--- | `ENCOUNTER_LOG_UNIT_TYPE_OBJECT` # 2
--- | `ENCOUNTER_LOG_UNIT_TYPE_PLAYER` # 0
--- | `ENCOUNTER_LOG_UNIT_TYPE_SIEGE_WEAPON` # 3

ENCOUNTER_LOG_UNIT_TYPE_MONSTER = 1
ENCOUNTER_LOG_UNIT_TYPE_OBJECT = 2
ENCOUNTER_LOG_UNIT_TYPE_PLAYER = 0
ENCOUNTER_LOG_UNIT_TYPE_SIEGE_WEAPON = 3
