--- @meta EndlessDungeonBuffType

--- @alias EndlessDungeonBuffType integer
--- | `ENDLESS_DUNGEON_BUFF_TYPE_NONE` # 0
--- | `ENDLESS_DUNGEON_BUFF_TYPE_VERSE` # 1
--- | `ENDLESS_DUNGEON_BUFF_TYPE_VISION` # 2

ENDLESS_DUNGEON_BUFF_TYPE_NONE = 0
ENDLESS_DUNGEON_BUFF_TYPE_VERSE = 1
ENDLESS_DUNGEON_BUFF_TYPE_VISION = 2
