--- @meta EndlessDungeonPointReason

--- @alias EndlessDungeonPointReason integer
--- | `ENDLESS_DUNGEON_POINT_REASON_ARC` # 17
--- | `ENDLESS_DUNGEON_POINT_REASON_BONUS_ACTIVITY_ED1` # 9
--- | `ENDLESS_DUNGEON_POINT_REASON_BONUS_ACTIVITY_ED2` # 10
--- | `ENDLESS_DUNGEON_POINT_REASON_BONUS_ACTIVITY_HIGH` # 8
--- | `ENDLESS_DUNGEON_POINT_REASON_BONUS_ACTIVITY_LOW` # 6
--- | `ENDLESS_DUNGEON_POINT_REASON_BONUS_ACTIVITY_MEDIUM` # 7
--- | `ENDLESS_DUNGEON_POINT_REASON_BONUS_POINT_ONE` # 12
--- | `ENDLESS_DUNGEON_POINT_REASON_BONUS_POINT_THREE` # 14
--- | `ENDLESS_DUNGEON_POINT_REASON_BONUS_POINT_TWO` # 13
--- | `ENDLESS_DUNGEON_POINT_REASON_CYCLE` # 16
--- | `ENDLESS_DUNGEON_POINT_REASON_KILL_BANNERMEN` # 2
--- | `ENDLESS_DUNGEON_POINT_REASON_KILL_BOSS` # 5
--- | `ENDLESS_DUNGEON_POINT_REASON_KILL_CHAMPION` # 3
--- | `ENDLESS_DUNGEON_POINT_REASON_KILL_MINIBOSS` # 4
--- | `ENDLESS_DUNGEON_POINT_REASON_KILL_NORMAL_MONSTER` # 1
--- | `ENDLESS_DUNGEON_POINT_REASON_KILL_NOXP_MONSTER` # 0
--- | `ENDLESS_DUNGEON_POINT_REASON_LIFE_REMAINING` # 11
--- | `ENDLESS_DUNGEON_POINT_REASON_STAGE` # 15

ENDLESS_DUNGEON_POINT_REASON_ARC = 17
ENDLESS_DUNGEON_POINT_REASON_BONUS_ACTIVITY_ED1 = 9
ENDLESS_DUNGEON_POINT_REASON_BONUS_ACTIVITY_ED2 = 10
ENDLESS_DUNGEON_POINT_REASON_BONUS_ACTIVITY_HIGH = 8
ENDLESS_DUNGEON_POINT_REASON_BONUS_ACTIVITY_LOW = 6
ENDLESS_DUNGEON_POINT_REASON_BONUS_ACTIVITY_MEDIUM = 7
ENDLESS_DUNGEON_POINT_REASON_BONUS_POINT_ONE = 12
ENDLESS_DUNGEON_POINT_REASON_BONUS_POINT_THREE = 14
ENDLESS_DUNGEON_POINT_REASON_BONUS_POINT_TWO = 13
ENDLESS_DUNGEON_POINT_REASON_CYCLE = 16
ENDLESS_DUNGEON_POINT_REASON_KILL_BANNERMEN = 2
ENDLESS_DUNGEON_POINT_REASON_KILL_BOSS = 5
ENDLESS_DUNGEON_POINT_REASON_KILL_CHAMPION = 3
ENDLESS_DUNGEON_POINT_REASON_KILL_MINIBOSS = 4
ENDLESS_DUNGEON_POINT_REASON_KILL_NORMAL_MONSTER = 1
ENDLESS_DUNGEON_POINT_REASON_KILL_NOXP_MONSTER = 0
ENDLESS_DUNGEON_POINT_REASON_LIFE_REMAINING = 11
ENDLESS_DUNGEON_POINT_REASON_STAGE = 15
