--- @meta EndlessDungeonBuffBucketType

--- @alias EndlessDungeonBuffBucketType integer
--- | `ENDLESS_DUNGEON_BUFF_BUCKET_TYPE_DEFENSE` # 1
--- | `ENDLESS_DUNGEON_BUFF_BUCKET_TYPE_OFFENSE` # 0
--- | `ENDLESS_DUNGEON_BUFF_BUCKET_TYPE_UTILITY` # 2

ENDLESS_DUNGEON_BUFF_BUCKET_TYPE_DEFENSE = 1
ENDLESS_DUNGEON_BUFF_BUCKET_TYPE_OFFENSE = 0
ENDLESS_DUNGEON_BUFF_BUCKET_TYPE_UTILITY = 2
