--- @meta EndlessDungeonCounterType

--- @alias EndlessDungeonCounterType integer
--- | `ENDLESS_DUNGEON_COUNTER_TYPE_ARC` # 2
--- | `ENDLESS_DUNGEON_COUNTER_TYPE_CYCLE` # 1
--- | `ENDLESS_DUNGEON_COUNTER_TYPE_STAGE` # 0
--- | `ENDLESS_DUNGEON_COUNTER_TYPE_WIPES_REMAINING` # 3

ENDLESS_DUNGEON_COUNTER_TYPE_ARC = 2
ENDLESS_DUNGEON_COUNTER_TYPE_CYCLE = 1
ENDLESS_DUNGEON_COUNTER_TYPE_STAGE = 0
ENDLESS_DUNGEON_COUNTER_TYPE_WIPES_REMAINING = 3
