--- @meta EquipType

--- @alias EquipType integer
--- | `EQUIP_TYPE_CHEST` # 3
--- | `EQUIP_TYPE_COSTUME` # 11
--- | `EQUIP_TYPE_FEET` # 10
--- | `EQUIP_TYPE_HAND` # 13
--- | `EQUIP_TYPE_HEAD` # 1
--- | `EQUIP_TYPE_INVALID` # 0
--- | `EQUIP_TYPE_LEGS` # 9
--- | `EQUIP_TYPE_MAIN_HAND` # 14
--- | `EQUIP_TYPE_NECK` # 2
--- | `EQUIP_TYPE_OFF_HAND` # 7
--- | `EQUIP_TYPE_ONE_HAND` # 5
--- | `EQUIP_TYPE_POISON` # 15
--- | `EQUIP_TYPE_RING` # 12
--- | `EQUIP_TYPE_SHOULDERS` # 4
--- | `EQUIP_TYPE_TWO_HAND` # 6
--- | `EQUIP_TYPE_WAIST` # 8

EQUIP_TYPE_CHEST = 3
EQUIP_TYPE_COSTUME = 11
EQUIP_TYPE_FEET = 10
EQUIP_TYPE_HAND = 13
EQUIP_TYPE_HEAD = 1
EQUIP_TYPE_INVALID = 0
EQUIP_TYPE_LEGS = 9
EQUIP_TYPE_MAIN_HAND = 14
EQUIP_TYPE_NECK = 2
EQUIP_TYPE_OFF_HAND = 7
EQUIP_TYPE_ONE_HAND = 5
EQUIP_TYPE_POISON = 15
EQUIP_TYPE_RING = 12
EQUIP_TYPE_SHOULDERS = 4
EQUIP_TYPE_TWO_HAND = 6
EQUIP_TYPE_WAIST = 8
