--- @meta EquipmentFilterType

--- @alias EquipmentFilterType integer
--- | `EQUIPMENT_FILTER_TYPE_BOW` # 11
--- | `EQUIPMENT_FILTER_TYPE_DESTRO_STAFF` # 9
--- | `EQUIPMENT_FILTER_TYPE_HEAVY` # 3
--- | `EQUIPMENT_FILTER_TYPE_LIGHT` # 1
--- | `EQUIPMENT_FILTER_TYPE_MEDIUM` # 2
--- | `EQUIPMENT_FILTER_TYPE_NECK` # 4
--- | `EQUIPMENT_FILTER_TYPE_NONE` # 0
--- | `EQUIPMENT_FILTER_TYPE_ONE_HANDED` # 6
--- | `EQUIPMENT_FILTER_TYPE_RESTO_STAFF` # 10
--- | `EQUIPMENT_FILTER_TYPE_RING` # 5
--- | `EQUIPMENT_FILTER_TYPE_SHIELD` # 7
--- | `EQUIPMENT_FILTER_TYPE_TWO_HANDED` # 8

EQUIPMENT_FILTER_TYPE_BOW = 11
EQUIPMENT_FILTER_TYPE_DESTRO_STAFF = 9
EQUIPMENT_FILTER_TYPE_HEAVY = 3
EQUIPMENT_FILTER_TYPE_LIGHT = 1
EQUIPMENT_FILTER_TYPE_MEDIUM = 2
EQUIPMENT_FILTER_TYPE_NECK = 4
EQUIPMENT_FILTER_TYPE_NONE = 0
EQUIPMENT_FILTER_TYPE_ONE_HANDED = 6
EQUIPMENT_FILTER_TYPE_RESTO_STAFF = 10
EQUIPMENT_FILTER_TYPE_RING = 5
EQUIPMENT_FILTER_TYPE_SHIELD = 7
EQUIPMENT_FILTER_TYPE_TWO_HANDED = 8
