--- @meta EquipmentBonus

--- @alias EquipmentBonus integer
--- | `EQUIPMENT_BONUS_AVERAGE` # 1
--- | `EQUIPMENT_BONUS_EXTRAORDINARY` # 5
--- | `EQUIPMENT_BONUS_FAIR` # 2
--- | `EQUIPMENT_BONUS_HIGH` # 3
--- | `EQUIPMENT_BONUS_LOW` # 0
--- | `EQUIPMENT_BONUS_SUPERIOR` # 4

EQUIPMENT_BONUS_AVERAGE = 1
EQUIPMENT_BONUS_EXTRAORDINARY = 5
EQUIPMENT_BONUS_FAIR = 2
EQUIPMENT_BONUS_HIGH = 3
EQUIPMENT_BONUS_LOW = 0
EQUIPMENT_BONUS_SUPERIOR = 4
