--- @meta EquipOutfitResult

--- @alias EquipOutfitResult integer
--- | `EQUIP_OUTFIT_RESULT_OUTFIT_ALREADY_EQUIPPED` # 4
--- | `EQUIP_OUTFIT_RESULT_OUTFIT_INVALID` # 1
--- | `EQUIP_OUTFIT_RESULT_OUTFIT_LOCKED` # 2
--- | `EQUIP_OUTFIT_RESULT_OUTFIT_SWITCHING_UNAVAILABLE` # 3
--- | `EQUIP_OUTFIT_RESULT_SUCCESS` # 0

EQUIP_OUTFIT_RESULT_OUTFIT_ALREADY_EQUIPPED = 4
EQUIP_OUTFIT_RESULT_OUTFIT_INVALID = 1
EQUIP_OUTFIT_RESULT_OUTFIT_LOCKED = 2
EQUIP_OUTFIT_RESULT_OUTFIT_SWITCHING_UNAVAILABLE = 3
EQUIP_OUTFIT_RESULT_SUCCESS = 0
