--- @meta EquipSlot

--- @alias EquipSlot integer
--- | `EQUIP_SLOT_BACKUP_MAIN` # 20
--- | `EQUIP_SLOT_BACKUP_OFF` # 21
--- | `EQUIP_SLOT_BACKUP_POISON` # 14
--- | `EQUIP_SLOT_CHEST` # 2
--- | `EQUIP_SLOT_CLASS1` # 17
--- | `EQUIP_SLOT_CLASS2` # 18
--- | `EQUIP_SLOT_CLASS3` # 19
--- | `EQUIP_SLOT_COSTUME` # 10
--- | `EQUIP_SLOT_FEET` # 9
--- | `EQUIP_SLOT_HAND` # 16
--- | `EQUIP_SLOT_HEAD` # 0
--- | `EQUIP_SLOT_LEGS` # 8
--- | `EQUIP_SLOT_MAIN_HAND` # 4
--- | `EQUIP_SLOT_NECK` # 1
--- | `EQUIP_SLOT_NONE` # -1
--- | `EQUIP_SLOT_OFF_HAND` # 5
--- | `EQUIP_SLOT_POISON` # 13
--- | `EQUIP_SLOT_RANGED` # 15
--- | `EQUIP_SLOT_RING1` # 11
--- | `EQUIP_SLOT_RING2` # 12
--- | `EQUIP_SLOT_SHOULDERS` # 3
--- | `EQUIP_SLOT_WAIST` # 6
--- | `EQUIP_SLOT_WRIST` # 7

EQUIP_SLOT_BACKUP_MAIN = 20
EQUIP_SLOT_BACKUP_OFF = 21
EQUIP_SLOT_BACKUP_POISON = 14
EQUIP_SLOT_CHEST = 2
EQUIP_SLOT_CLASS1 = 17
EQUIP_SLOT_CLASS2 = 18
EQUIP_SLOT_CLASS3 = 19
EQUIP_SLOT_COSTUME = 10
EQUIP_SLOT_FEET = 9
EQUIP_SLOT_HAND = 16
EQUIP_SLOT_HEAD = 0
EQUIP_SLOT_LEGS = 8
EQUIP_SLOT_MAIN_HAND = 4
EQUIP_SLOT_NECK = 1
EQUIP_SLOT_NONE = -1
EQUIP_SLOT_OFF_HAND = 5
EQUIP_SLOT_POISON = 13
EQUIP_SLOT_RANGED = 15
EQUIP_SLOT_RING1 = 11
EQUIP_SLOT_RING2 = 12
EQUIP_SLOT_SHOULDERS = 3
EQUIP_SLOT_WAIST = 6
EQUIP_SLOT_WRIST = 7
