--- @meta EquipSlotVisualCategory

--- @alias EquipSlotVisualCategory integer
--- | `EQUIP_SLOT_VISUAL_CATEGORY_ACCESSORIES` # 3
--- | `EQUIP_SLOT_VISUAL_CATEGORY_APPAREL` # 2
--- | `EQUIP_SLOT_VISUAL_CATEGORY_NONE` # 0
--- | `EQUIP_SLOT_VISUAL_CATEGORY_WEAPONS` # 1

EQUIP_SLOT_VISUAL_CATEGORY_ACCESSORIES = 3
EQUIP_SLOT_VISUAL_CATEGORY_APPAREL = 2
EQUIP_SLOT_VISUAL_CATEGORY_NONE = 0
EQUIP_SLOT_VISUAL_CATEGORY_WEAPONS = 1
