--- @meta EULAType

--- @alias EULAType integer
--- | `EULA_TYPE_ADDON_EULA` # 1
--- | `EULA_TYPE_CODE_OF_CONDUCT` # 4
--- | `EULA_TYPE_NON_DISCLOSURE_AGREEMENT` # 5
--- | `EULA_TYPE_PREGAME_EULA` # 0
--- | `EULA_TYPE_PRIVACY_POLICY` # 3
--- | `EULA_TYPE_TERMS_OF_SERVICE` # 2

EULA_TYPE_ADDON_EULA = 1
EULA_TYPE_CODE_OF_CONDUCT = 4
EULA_TYPE_NON_DISCLOSURE_AGREEMENT = 5
EULA_TYPE_PREGAME_EULA = 0
EULA_TYPE_PRIVACY_POLICY = 3
EULA_TYPE_TERMS_OF_SERVICE = 2
