--- @meta ExpectedInputChangeResult

--- @alias ExpectedInputChangeResult integer
--- | `EXPECTED_INPUT_CHANGE_RESULT_INPUT_MODE_CHANGED` # 2
--- | `EXPECTED_INPUT_CHANGE_RESULT_INPUT_TYPE_CHANGED` # 1
--- | `EXPECTED_INPUT_CHANGE_RESULT_NO_CHANGE` # 0

EXPECTED_INPUT_CHANGE_RESULT_INPUT_MODE_CHANGED = 2
EXPECTED_INPUT_CHANGE_RESULT_INPUT_TYPE_CHANGED = 1
EXPECTED_INPUT_CHANGE_RESULT_NO_CHANGE = 0
