--- @meta ExpiringMarketCurrencyState

--- @alias ExpiringMarketCurrencyState integer
--- | `EXPIRING_MARKET_CURRENCY_STATE_READY` # 2
--- | `EXPIRING_MARKET_CURRENCY_STATE_UNKNOWN` # 0
--- | `EXPIRING_MARKET_CURRENCY_STATE_UPDATING` # 1

EXPIRING_MARKET_CURRENCY_STATE_READY = 2
EXPIRING_MARKET_CURRENCY_STATE_UNKNOWN = 0
EXPIRING_MARKET_CURRENCY_STATE_UPDATING = 1
