--- @meta ExternalGrantRewardResult

--- @alias ExternalGrantRewardResult integer
--- | `EXT_GRANT_RESPONSE_FAILED_SAVE` # 3
--- | `EXT_GRANT_RESPONSE_INTERNAL_ONLY` # 2
--- | `EXT_GRANT_RESPONSE_INVALID_REWARD` # 1
--- | `EXT_GRANT_RESPONSE_SUCCESS` # 0

EXT_GRANT_RESPONSE_FAILED_SAVE = 3
EXT_GRANT_RESPONSE_INTERNAL_ONLY = 2
EXT_GRANT_RESPONSE_INVALID_REWARD = 1
EXT_GRANT_RESPONSE_SUCCESS = 0
