--- @meta FastTravelKeepResult

--- @alias FastTravelKeepResult integer
--- | `FAST_TRAVEL_KEEP_RESULT_FAILED` # 12
--- | `FAST_TRAVEL_KEEP_RESULT_FAILED_CANT_RECALL_FROM_KEEP_SUBZONE` # 16
--- | `FAST_TRAVEL_KEEP_RESULT_FAILED_DESTINATION_KEEP_ALLIANCE` # 5
--- | `FAST_TRAVEL_KEEP_RESULT_FAILED_DESTINATION_KEEP_ALLIED_RESOURCE` # 7
--- | `FAST_TRAVEL_KEEP_RESULT_FAILED_DESTINATION_KEEP_UNDER_ATTACK` # 6
--- | `FAST_TRAVEL_KEEP_RESULT_FAILED_INTERACT_REQUIREMENT` # 10
--- | `FAST_TRAVEL_KEEP_RESULT_FAILED_INVALID_DESTINATION_WAYPOINT` # 9
--- | `FAST_TRAVEL_KEEP_RESULT_FAILED_NO_RECALL_ITEM` # 15
--- | `FAST_TRAVEL_KEEP_RESULT_FAILED_NO_VALID_PATH` # 2
--- | `FAST_TRAVEL_KEEP_RESULT_FAILED_ORIGIN_KEEP_ALLIANCE` # 3
--- | `FAST_TRAVEL_KEEP_RESULT_FAILED_ORIGIN_KEEP_ALLIED_RESOURCE` # 14
--- | `FAST_TRAVEL_KEEP_RESULT_FAILED_ORIGIN_KEEP_UNDER_ATTACK` # 4
--- | `FAST_TRAVEL_KEEP_RESULT_FAILED_PLAYER_CARRYING_ARTIFACT` # 11
--- | `FAST_TRAVEL_KEEP_RESULT_FAILED_PLAYER_IN_COMBAT` # 1
--- | `FAST_TRAVEL_KEEP_RESULT_FAILED_PLAYER_TOO_FAR_AWAY_FROM_ORIGIN_KEEP` # 8
--- | `FAST_TRAVEL_KEEP_RESULT_PENDING_REMOTE_JUMP_RESPONSE` # 13
--- | `FAST_TRAVEL_KEEP_RESULT_PENDING_TRAVEL_QUERY` # 17
--- | `FAST_TRAVEL_KEEP_RESULT_SUCCESS` # 0

FAST_TRAVEL_KEEP_RESULT_FAILED = 12
FAST_TRAVEL_KEEP_RESULT_FAILED_CANT_RECALL_FROM_KEEP_SUBZONE = 16
FAST_TRAVEL_KEEP_RESULT_FAILED_DESTINATION_KEEP_ALLIANCE = 5
FAST_TRAVEL_KEEP_RESULT_FAILED_DESTINATION_KEEP_ALLIED_RESOURCE = 7
FAST_TRAVEL_KEEP_RESULT_FAILED_DESTINATION_KEEP_UNDER_ATTACK = 6
FAST_TRAVEL_KEEP_RESULT_FAILED_INTERACT_REQUIREMENT = 10
FAST_TRAVEL_KEEP_RESULT_FAILED_INVALID_DESTINATION_WAYPOINT = 9
FAST_TRAVEL_KEEP_RESULT_FAILED_NO_RECALL_ITEM = 15
FAST_TRAVEL_KEEP_RESULT_FAILED_NO_VALID_PATH = 2
FAST_TRAVEL_KEEP_RESULT_FAILED_ORIGIN_KEEP_ALLIANCE = 3
FAST_TRAVEL_KEEP_RESULT_FAILED_ORIGIN_KEEP_ALLIED_RESOURCE = 14
FAST_TRAVEL_KEEP_RESULT_FAILED_ORIGIN_KEEP_UNDER_ATTACK = 4
FAST_TRAVEL_KEEP_RESULT_FAILED_PLAYER_CARRYING_ARTIFACT = 11
FAST_TRAVEL_KEEP_RESULT_FAILED_PLAYER_IN_COMBAT = 1
FAST_TRAVEL_KEEP_RESULT_FAILED_PLAYER_TOO_FAR_AWAY_FROM_ORIGIN_KEEP = 8
FAST_TRAVEL_KEEP_RESULT_PENDING_REMOTE_JUMP_RESPONSE = 13
FAST_TRAVEL_KEEP_RESULT_PENDING_TRAVEL_QUERY = 17
FAST_TRAVEL_KEEP_RESULT_SUCCESS = 0
