--- @meta FlexEdge

--- @alias FlexEdge integer
--- | `FLEX_EDGE_ALL` # 8
--- | `FLEX_EDGE_BOTTOM` # 3
--- | `FLEX_EDGE_END` # 5
--- | `FLEX_EDGE_HORIZONTAL` # 6
--- | `FLEX_EDGE_LEFT` # 0
--- | `FLEX_EDGE_RIGHT` # 2
--- | `FLEX_EDGE_START` # 4
--- | `FLEX_EDGE_TOP` # 1
--- | `FLEX_EDGE_VERTICAL` # 7

FLEX_EDGE_ALL = 8
FLEX_EDGE_BOTTOM = 3
FLEX_EDGE_END = 5
FLEX_EDGE_HORIZONTAL = 6
FLEX_EDGE_LEFT = 0
FLEX_EDGE_RIGHT = 2
FLEX_EDGE_START = 4
FLEX_EDGE_TOP = 1
FLEX_EDGE_VERTICAL = 7
