--- @meta FlexJustification

--- @alias FlexJustification integer
--- | `FLEX_JUSTIFICATION_CENTER` # 1
--- | `FLEX_JUSTIFICATION_FLEX_END` # 2
--- | `FLEX_JUSTIFICATION_FLEX_START` # 0
--- | `FLEX_JUSTIFICATION_SPACE_AROUND` # 4
--- | `FLEX_JUSTIFICATION_SPACE_BETWEEN` # 3
--- | `FLEX_JUSTIFICATION_SPACE_EVENLY` # 5

FLEX_JUSTIFICATION_CENTER = 1
FLEX_JUSTIFICATION_FLEX_END = 2
FLEX_JUSTIFICATION_FLEX_START = 0
FLEX_JUSTIFICATION_SPACE_AROUND = 4
FLEX_JUSTIFICATION_SPACE_BETWEEN = 3
FLEX_JUSTIFICATION_SPACE_EVENLY = 5
