--- @meta FlexAlignment

--- @alias FlexAlignment integer
--- | `FLEX_ALIGNMENT_AUTO` # 0
--- | `FLEX_ALIGNMENT_BASELINE` # 5
--- | `FLEX_ALIGNMENT_CENTER` # 2
--- | `FLEX_ALIGNMENT_FLEX_END` # 3
--- | `FLEX_ALIGNMENT_FLEX_START` # 1
--- | `FLEX_ALIGNMENT_SPACE_AROUND` # 7
--- | `FLEX_ALIGNMENT_SPACE_BETWEEN` # 6
--- | `FLEX_ALIGNMENT_STRETCH` # 4

FLEX_ALIGNMENT_AUTO = 0
FLEX_ALIGNMENT_BASELINE = 5
FLEX_ALIGNMENT_CENTER = 2
FLEX_ALIGNMENT_FLEX_END = 3
FLEX_ALIGNMENT_FLEX_START = 1
FLEX_ALIGNMENT_SPACE_AROUND = 7
FLEX_ALIGNMENT_SPACE_BETWEEN = 6
FLEX_ALIGNMENT_STRETCH = 4
