--- @meta FlexDirection

--- @alias FlexDirection integer
--- | `FLEX_DIRECTION_COLUMN` # 0
--- | `FLEX_DIRECTION_COLUMN_REVERSE` # 1
--- | `FLEX_DIRECTION_ROW` # 2
--- | `FLEX_DIRECTION_ROW_REVERSE` # 3

FLEX_DIRECTION_COLUMN = 0
FLEX_DIRECTION_COLUMN_REVERSE = 1
FLEX_DIRECTION_ROW = 2
FLEX_DIRECTION_ROW_REVERSE = 3
