--- @meta FontStyle

--- @alias FontStyle integer
--- | `FONT_STYLE_NORMAL` # 0
--- | `FONT_STYLE_OUTLINE` # 2
--- | `FONT_STYLE_OUTLINE_THICK` # 3
--- | `FONT_STYLE_SHADOW` # 1
--- | `FONT_STYLE_SOFT_SHADOW_THICK` # 5
--- | `FONT_STYLE_SOFT_SHADOW_THIN` # 4

FONT_STYLE_NORMAL = 0
FONT_STYLE_OUTLINE = 2
FONT_STYLE_OUTLINE_THICK = 3
FONT_STYLE_SHADOW = 1
FONT_STYLE_SOFT_SHADOW_THICK = 5
FONT_STYLE_SOFT_SHADOW_THIN = 4
