--- @meta ForcedZoneExitCause

--- @alias ForcedZoneExitCause integer
--- | `INSTANCE_KICK_REASON_INSTANCE_SHUTDOWN` # 3
--- | `INSTANCE_KICK_REASON_NONE` # 0
--- | `INSTANCE_KICK_REASON_NOT_IN_REQUIRED_GROUP` # 1
--- | `INSTANCE_KICK_REASON_WANT_TO_LEAVE` # 2

INSTANCE_KICK_REASON_INSTANCE_SHUTDOWN = 3
INSTANCE_KICK_REASON_NONE = 0
INSTANCE_KICK_REASON_NOT_IN_REQUIRED_GROUP = 1
INSTANCE_KICK_REASON_WANT_TO_LEAVE = 2
