--- @meta FSRMode

--- @alias FSRMode integer
--- | `FSR_MODE_BALANCED` # 2
--- | `FSR_MODE_OFF` # 0
--- | `FSR_MODE_PERFORMANCE` # 1
--- | `FSR_MODE_QUALITY` # 3
--- | `FSR_MODE_ULTRA_QUALITY` # 4

FSR_MODE_BALANCED = 2
FSR_MODE_OFF = 0
FSR_MODE_PERFORMANCE = 1
FSR_MODE_QUALITY = 3
FSR_MODE_ULTRA_QUALITY = 4
