--- @meta FullscreenEffectType

--- @alias FullscreenEffectType integer
--- | `FULLSCREEN_EFFECT_CHARACTER_FRAMING_BLUR` # 1
--- | `FULLSCREEN_EFFECT_NONE` # 0
--- | `FULLSCREEN_EFFECT_UNIFORM_BLUR` # 2

FULLSCREEN_EFFECT_CHARACTER_FRAMING_BLUR = 1
FULLSCREEN_EFFECT_NONE = 0
FULLSCREEN_EFFECT_UNIFORM_BLUR = 2
