--- @meta FullscreenMode

--- @alias FullscreenMode integer
--- | `FULLSCREEN_MODE_FULLSCREEN_EXCLUSIVE` # 2
--- | `FULLSCREEN_MODE_FULLSCREEN_WINDOWED` # 1
--- | `FULLSCREEN_MODE_WINDOWED` # 0

FULLSCREEN_MODE_FULLSCREEN_EXCLUSIVE = 2
FULLSCREEN_MODE_FULLSCREEN_WINDOWED = 1
FULLSCREEN_MODE_WINDOWED = 0
