--- @meta FurnitureThemeType

--- @alias FurnitureThemeType integer
--- | `FURNITURE_THEME_TYPE_ALL` # 0
--- | `FURNITURE_THEME_TYPE_ARGONIAN` # 4
--- | `FURNITURE_THEME_TYPE_AYLEID` # 14
--- | `FURNITURE_THEME_TYPE_BRETON` # 2
--- | `FURNITURE_THEME_TYPE_CLOCKWORK` # 16
--- | `FURNITURE_THEME_TYPE_DAEDRIC` # 13
--- | `FURNITURE_THEME_TYPE_DARK_ELF` # 6
--- | `FURNITURE_THEME_TYPE_DWARVEN` # 12
--- | `FURNITURE_THEME_TYPE_GENERIC` # 1
--- | `FURNITURE_THEME_TYPE_HIGH_ELF` # 3
--- | `FURNITURE_THEME_TYPE_IMPERIAL` # 11
--- | `FURNITURE_THEME_TYPE_KHAJIIT` # 7
--- | `FURNITURE_THEME_TYPE_NORD` # 8
--- | `FURNITURE_THEME_TYPE_ORC` # 9
--- | `FURNITURE_THEME_TYPE_PRIMAL` # 15
--- | `FURNITURE_THEME_TYPE_REDGUARD` # 10
--- | `FURNITURE_THEME_TYPE_VAMPIRIC` # 17
--- | `FURNITURE_THEME_TYPE_WOOD_ELF` # 5

FURNITURE_THEME_TYPE_ALL = 0
FURNITURE_THEME_TYPE_ARGONIAN = 4
FURNITURE_THEME_TYPE_AYLEID = 14
FURNITURE_THEME_TYPE_BRETON = 2
FURNITURE_THEME_TYPE_CLOCKWORK = 16
FURNITURE_THEME_TYPE_DAEDRIC = 13
FURNITURE_THEME_TYPE_DARK_ELF = 6
FURNITURE_THEME_TYPE_DWARVEN = 12
FURNITURE_THEME_TYPE_GENERIC = 1
FURNITURE_THEME_TYPE_HIGH_ELF = 3
FURNITURE_THEME_TYPE_IMPERIAL = 11
FURNITURE_THEME_TYPE_KHAJIIT = 7
FURNITURE_THEME_TYPE_NORD = 8
FURNITURE_THEME_TYPE_ORC = 9
FURNITURE_THEME_TYPE_PRIMAL = 15
FURNITURE_THEME_TYPE_REDGUARD = 10
FURNITURE_THEME_TYPE_VAMPIRIC = 17
FURNITURE_THEME_TYPE_WOOD_ELF = 5
