--- @meta GameCameraFramingScreenType

--- @alias GameCameraFramingScreenType integer
--- | `FRAMING_SCREEN_AVA` # 6
--- | `FRAMING_SCREEN_CHAMPION` # 9
--- | `FRAMING_SCREEN_CROWN_CRATES` # 11
--- | `FRAMING_SCREEN_CROWN_STORE` # 10
--- | `FRAMING_SCREEN_DEFAULT` # 0
--- | `FRAMING_SCREEN_INVENTORY` # 2
--- | `FRAMING_SCREEN_ITEM_SETS_BOOK` # 12
--- | `FRAMING_SCREEN_JOURNAL` # 3
--- | `FRAMING_SCREEN_LOOT` # 8
--- | `FRAMING_SCREEN_MAP` # 4
--- | `FRAMING_SCREEN_REUSE_ME_2` # 13
--- | `FRAMING_SCREEN_SKILLS` # 1
--- | `FRAMING_SCREEN_SOCIAL` # 5
--- | `FRAMING_SCREEN_SYSTEM` # 7

FRAMING_SCREEN_AVA = 6
FRAMING_SCREEN_CHAMPION = 9
FRAMING_SCREEN_CROWN_CRATES = 11
FRAMING_SCREEN_CROWN_STORE = 10
FRAMING_SCREEN_DEFAULT = 0
FRAMING_SCREEN_INVENTORY = 2
FRAMING_SCREEN_ITEM_SETS_BOOK = 12
FRAMING_SCREEN_JOURNAL = 3
FRAMING_SCREEN_LOOT = 8
FRAMING_SCREEN_MAP = 4
FRAMING_SCREEN_REUSE_ME_2 = 13
FRAMING_SCREEN_SKILLS = 1
FRAMING_SCREEN_SOCIAL = 5
FRAMING_SCREEN_SYSTEM = 7
