--- @meta GamepadItemCategory

--- @alias GamepadItemCategory integer
--- | `GAMEPAD_ITEM_CATEGORY_ALCHEMY` # 0
--- | `GAMEPAD_ITEM_CATEGORY_AMULET` # 1
--- | `GAMEPAD_ITEM_CATEGORY_AXE` # 2
--- | `GAMEPAD_ITEM_CATEGORY_BAIT` # 3
--- | `GAMEPAD_ITEM_CATEGORY_BLACKSMITH` # 4
--- | `GAMEPAD_ITEM_CATEGORY_BOW` # 5
--- | `GAMEPAD_ITEM_CATEGORY_CHEST` # 6
--- | `GAMEPAD_ITEM_CATEGORY_CLOTHIER` # 7
--- | `GAMEPAD_ITEM_CATEGORY_COMPANION_AMULET` # 40
--- | `GAMEPAD_ITEM_CATEGORY_COMPANION_AXE` # 41
--- | `GAMEPAD_ITEM_CATEGORY_COMPANION_BOW` # 42
--- | `GAMEPAD_ITEM_CATEGORY_COMPANION_CHEST` # 43
--- | `GAMEPAD_ITEM_CATEGORY_COMPANION_DAGGER` # 44
--- | `GAMEPAD_ITEM_CATEGORY_COMPANION_FEET` # 45
--- | `GAMEPAD_ITEM_CATEGORY_COMPANION_HAMMER` # 46
--- | `GAMEPAD_ITEM_CATEGORY_COMPANION_HANDS` # 47
--- | `GAMEPAD_ITEM_CATEGORY_COMPANION_HEAD` # 48
--- | `GAMEPAD_ITEM_CATEGORY_COMPANION_LEGS` # 49
--- | `GAMEPAD_ITEM_CATEGORY_COMPANION_RING` # 50
--- | `GAMEPAD_ITEM_CATEGORY_COMPANION_SHIELD` # 51
--- | `GAMEPAD_ITEM_CATEGORY_COMPANION_SHOULDERS` # 52
--- | `GAMEPAD_ITEM_CATEGORY_COMPANION_STAFF` # 53
--- | `GAMEPAD_ITEM_CATEGORY_COMPANION_SWORD` # 54
--- | `GAMEPAD_ITEM_CATEGORY_COMPANION_WAIST` # 55
--- | `GAMEPAD_ITEM_CATEGORY_CONSUMABLE` # 8
--- | `GAMEPAD_ITEM_CATEGORY_COSTUME` # 9
--- | `GAMEPAD_ITEM_CATEGORY_DAGGER` # 10
--- | `GAMEPAD_ITEM_CATEGORY_DEPRECATED` # 24
--- | `GAMEPAD_ITEM_CATEGORY_ENCHANTING` # 11
--- | `GAMEPAD_ITEM_CATEGORY_FEET` # 12
--- | `GAMEPAD_ITEM_CATEGORY_GLYPHS` # 13
--- | `GAMEPAD_ITEM_CATEGORY_HAMMER` # 14
--- | `GAMEPAD_ITEM_CATEGORY_HANDS` # 15
--- | `GAMEPAD_ITEM_CATEGORY_HEAD` # 16
--- | `GAMEPAD_ITEM_CATEGORY_HEAVY_ARMOR` # 35
--- | `GAMEPAD_ITEM_CATEGORY_JEWELRY` # 38
--- | `GAMEPAD_ITEM_CATEGORY_JEWELRYCRAFTING` # 39
--- | `GAMEPAD_ITEM_CATEGORY_LEGS` # 17
--- | `GAMEPAD_ITEM_CATEGORY_LIGHT_ARMOR` # 37
--- | `GAMEPAD_ITEM_CATEGORY_MEDIUM_ARMOR` # 36
--- | `GAMEPAD_ITEM_CATEGORY_POTION` # 18
--- | `GAMEPAD_ITEM_CATEGORY_PROVISIONING` # 19
--- | `GAMEPAD_ITEM_CATEGORY_RING` # 20
--- | `GAMEPAD_ITEM_CATEGORY_SHIELD` # 21
--- | `GAMEPAD_ITEM_CATEGORY_SHOULDERS` # 22
--- | `GAMEPAD_ITEM_CATEGORY_SIEGE` # 23
--- | `GAMEPAD_ITEM_CATEGORY_SOUL_GEM` # 27
--- | `GAMEPAD_ITEM_CATEGORY_STAFF` # 25
--- | `GAMEPAD_ITEM_CATEGORY_STYLE_MATERIAL` # 26
--- | `GAMEPAD_ITEM_CATEGORY_SWORD` # 28
--- | `GAMEPAD_ITEM_CATEGORY_TOOL` # 29
--- | `GAMEPAD_ITEM_CATEGORY_TRAIT_ITEM` # 30
--- | `GAMEPAD_ITEM_CATEGORY_TROPHY` # 31
--- | `GAMEPAD_ITEM_CATEGORY_WAIST` # 32
--- | `GAMEPAD_ITEM_CATEGORY_WEAPONS` # 34
--- | `GAMEPAD_ITEM_CATEGORY_WOODWORKING` # 33

GAMEPAD_ITEM_CATEGORY_ALCHEMY = 0
GAMEPAD_ITEM_CATEGORY_AMULET = 1
GAMEPAD_ITEM_CATEGORY_AXE = 2
GAMEPAD_ITEM_CATEGORY_BAIT = 3
GAMEPAD_ITEM_CATEGORY_BLACKSMITH = 4
GAMEPAD_ITEM_CATEGORY_BOW = 5
GAMEPAD_ITEM_CATEGORY_CHEST = 6
GAMEPAD_ITEM_CATEGORY_CLOTHIER = 7
GAMEPAD_ITEM_CATEGORY_COMPANION_AMULET = 40
GAMEPAD_ITEM_CATEGORY_COMPANION_AXE = 41
GAMEPAD_ITEM_CATEGORY_COMPANION_BOW = 42
GAMEPAD_ITEM_CATEGORY_COMPANION_CHEST = 43
GAMEPAD_ITEM_CATEGORY_COMPANION_DAGGER = 44
GAMEPAD_ITEM_CATEGORY_COMPANION_FEET = 45
GAMEPAD_ITEM_CATEGORY_COMPANION_HAMMER = 46
GAMEPAD_ITEM_CATEGORY_COMPANION_HANDS = 47
GAMEPAD_ITEM_CATEGORY_COMPANION_HEAD = 48
GAMEPAD_ITEM_CATEGORY_COMPANION_LEGS = 49
GAMEPAD_ITEM_CATEGORY_COMPANION_RING = 50
GAMEPAD_ITEM_CATEGORY_COMPANION_SHIELD = 51
GAMEPAD_ITEM_CATEGORY_COMPANION_SHOULDERS = 52
GAMEPAD_ITEM_CATEGORY_COMPANION_STAFF = 53
GAMEPAD_ITEM_CATEGORY_COMPANION_SWORD = 54
GAMEPAD_ITEM_CATEGORY_COMPANION_WAIST = 55
GAMEPAD_ITEM_CATEGORY_CONSUMABLE = 8
GAMEPAD_ITEM_CATEGORY_COSTUME = 9
GAMEPAD_ITEM_CATEGORY_DAGGER = 10
GAMEPAD_ITEM_CATEGORY_DEPRECATED = 24
GAMEPAD_ITEM_CATEGORY_ENCHANTING = 11
GAMEPAD_ITEM_CATEGORY_FEET = 12
GAMEPAD_ITEM_CATEGORY_GLYPHS = 13
GAMEPAD_ITEM_CATEGORY_HAMMER = 14
GAMEPAD_ITEM_CATEGORY_HANDS = 15
GAMEPAD_ITEM_CATEGORY_HEAD = 16
GAMEPAD_ITEM_CATEGORY_HEAVY_ARMOR = 35
GAMEPAD_ITEM_CATEGORY_JEWELRY = 38
GAMEPAD_ITEM_CATEGORY_JEWELRYCRAFTING = 39
GAMEPAD_ITEM_CATEGORY_LEGS = 17
GAMEPAD_ITEM_CATEGORY_LIGHT_ARMOR = 37
GAMEPAD_ITEM_CATEGORY_MEDIUM_ARMOR = 36
GAMEPAD_ITEM_CATEGORY_POTION = 18
GAMEPAD_ITEM_CATEGORY_PROVISIONING = 19
GAMEPAD_ITEM_CATEGORY_RING = 20
GAMEPAD_ITEM_CATEGORY_SHIELD = 21
GAMEPAD_ITEM_CATEGORY_SHOULDERS = 22
GAMEPAD_ITEM_CATEGORY_SIEGE = 23
GAMEPAD_ITEM_CATEGORY_SOUL_GEM = 27
GAMEPAD_ITEM_CATEGORY_STAFF = 25
GAMEPAD_ITEM_CATEGORY_STYLE_MATERIAL = 26
GAMEPAD_ITEM_CATEGORY_SWORD = 28
GAMEPAD_ITEM_CATEGORY_TOOL = 29
GAMEPAD_ITEM_CATEGORY_TRAIT_ITEM = 30
GAMEPAD_ITEM_CATEGORY_TROPHY = 31
GAMEPAD_ITEM_CATEGORY_WAIST = 32
GAMEPAD_ITEM_CATEGORY_WEAPONS = 34
GAMEPAD_ITEM_CATEGORY_WOODWORKING = 33
