--- @meta GameCameraAdditionalInfo

--- @alias GameCameraAdditionalInfo integer
--- | `ADDITIONAL_INTERACT_INFO_EMPTY` # 2
--- | `ADDITIONAL_INTERACT_INFO_FISHING_NODE` # 3
--- | `ADDITIONAL_INTERACT_INFO_HOUSE_BANK` # 9
--- | `ADDITIONAL_INTERACT_INFO_HOUSE_INSTANCE_DOOR` # 11
--- | `ADDITIONAL_INTERACT_INFO_INSTANCE_TYPE` # 4
--- | `ADDITIONAL_INTERACT_INFO_IN_HIDEYHOLE` # 8
--- | `ADDITIONAL_INTERACT_INFO_LOCKED` # 1
--- | `ADDITIONAL_INTERACT_INFO_NONE` # 0
--- | `ADDITIONAL_INTERACT_INFO_PICKPOCKET_CHANCE` # 6
--- | `ADDITIONAL_INTERACT_INFO_REQUIRES_KEY` # 5
--- | `ADDITIONAL_INTERACT_INFO_WEREWOLF_ACTIVE_WHILE_ATTEMPTING_TO_CRAFT` # 7
--- | `ADDITIONAL_INTERACT_INFO_WEREWOLF_ACTIVE_WHILE_ATTEMPTING_TO_EXCAVATE` # 10

ADDITIONAL_INTERACT_INFO_EMPTY = 2
ADDITIONAL_INTERACT_INFO_FISHING_NODE = 3
ADDITIONAL_INTERACT_INFO_HOUSE_BANK = 9
ADDITIONAL_INTERACT_INFO_HOUSE_INSTANCE_DOOR = 11
ADDITIONAL_INTERACT_INFO_INSTANCE_TYPE = 4
ADDITIONAL_INTERACT_INFO_IN_HIDEYHOLE = 8
ADDITIONAL_INTERACT_INFO_LOCKED = 1
ADDITIONAL_INTERACT_INFO_NONE = 0
ADDITIONAL_INTERACT_INFO_PICKPOCKET_CHANCE = 6
ADDITIONAL_INTERACT_INFO_REQUIRES_KEY = 5
ADDITIONAL_INTERACT_INFO_WEREWOLF_ACTIVE_WHILE_ATTEMPTING_TO_CRAFT = 7
ADDITIONAL_INTERACT_INFO_WEREWOLF_ACTIVE_WHILE_ATTEMPTING_TO_EXCAVATE = 10
