--- @meta GamepadQuestItemCategory

--- @alias GamepadQuestItemCategory integer
--- | `GAMEPAD_QUEST_ITEM_CATEGORY_NOT_SLOTTABLE` # 0
--- | `GAMEPAD_QUEST_ITEM_CATEGORY_SLOTTABLE` # 1

GAMEPAD_QUEST_ITEM_CATEGORY_NOT_SLOTTABLE = 0
GAMEPAD_QUEST_ITEM_CATEGORY_SLOTTABLE = 1
