--- @meta GamepadSetting

--- @alias GamepadSetting integer
--- | `GAMEPAD_SETTING_CAMERA_SENSITIVITY` # 3
--- | `GAMEPAD_SETTING_GAMEPAD_TEMPLATE` # 4
--- | `GAMEPAD_SETTING_INPUT_PREFERRED_MODE` # 6
--- | `GAMEPAD_SETTING_INVERT_X` # 2
--- | `GAMEPAD_SETTING_INVERT_Y` # 1
--- | `GAMEPAD_SETTING_KEYBIND_DISPLAY_MODE` # 8
--- | `GAMEPAD_SETTING_USE_KEYBOARD_CHAT` # 7
--- | `GAMEPAD_SETTING_USE_KEYBOARD_LOGIN` # 9
--- | `GAMEPAD_SETTING_VIBRATION` # 0
--- | `GAMEPAD_SETTING_WAS_LAST_INPUT_GAMEPAD` # 5

GAMEPAD_SETTING_CAMERA_SENSITIVITY = 3
GAMEPAD_SETTING_GAMEPAD_TEMPLATE = 4
GAMEPAD_SETTING_INPUT_PREFERRED_MODE = 6
GAMEPAD_SETTING_INVERT_X = 2
GAMEPAD_SETTING_INVERT_Y = 1
GAMEPAD_SETTING_KEYBIND_DISPLAY_MODE = 8
GAMEPAD_SETTING_USE_KEYBOARD_CHAT = 7
GAMEPAD_SETTING_USE_KEYBOARD_LOGIN = 9
GAMEPAD_SETTING_VIBRATION = 0
GAMEPAD_SETTING_WAS_LAST_INPUT_GAMEPAD = 5
