--- @meta GamepadType

--- @alias GamepadType integer
--- | `GAMEPAD_TYPE_NONE` # 0
--- | `GAMEPAD_TYPE_PS4` # 2
--- | `GAMEPAD_TYPE_PS4_NO_TOUCHPAD` # 5
--- | `GAMEPAD_TYPE_PS5` # 6
--- | `GAMEPAD_TYPE_STADIA` # 4
--- | `GAMEPAD_TYPE_SWITCH` # 3
--- | `GAMEPAD_TYPE_XBOX` # 1
--- | `GAMEPAD_TYPE_XBSX` # 7

GAMEPAD_TYPE_NONE = 0
GAMEPAD_TYPE_PS4 = 2
GAMEPAD_TYPE_PS4_NO_TOUCHPAD = 5
GAMEPAD_TYPE_PS5 = 6
GAMEPAD_TYPE_STADIA = 4
GAMEPAD_TYPE_SWITCH = 3
GAMEPAD_TYPE_XBOX = 1
GAMEPAD_TYPE_XBSX = 7
