--- @meta GamepadWeaponCategory

--- @alias GamepadWeaponCategory integer
--- | `GAMEPAD_WEAPON_CATEGORY_DESTRUCTION_STAFF` # 4
--- | `GAMEPAD_WEAPON_CATEGORY_ONE_HANDED_MELEE` # 1
--- | `GAMEPAD_WEAPON_CATEGORY_RESTORATION_STAFF` # 5
--- | `GAMEPAD_WEAPON_CATEGORY_TWO_HANDED_BOW` # 3
--- | `GAMEPAD_WEAPON_CATEGORY_TWO_HANDED_MELEE` # 2
--- | `GAMEPAD_WEAPON_CATEGORY_UNCATEGORIZED` # 0

GAMEPAD_WEAPON_CATEGORY_DESTRUCTION_STAFF = 4
GAMEPAD_WEAPON_CATEGORY_ONE_HANDED_MELEE = 1
GAMEPAD_WEAPON_CATEGORY_RESTORATION_STAFF = 5
GAMEPAD_WEAPON_CATEGORY_TWO_HANDED_BOW = 3
GAMEPAD_WEAPON_CATEGORY_TWO_HANDED_MELEE = 2
GAMEPAD_WEAPON_CATEGORY_UNCATEGORIZED = 0
