--- @meta GamepadTemplate

--- @alias GamepadTemplate integer
--- | `GAMEPAD_TEMPLATE_ABILITY_MODIFIERS` # 2
--- | `GAMEPAD_TEMPLATE_ALTERNATE_INTERACT` # 4
--- | `GAMEPAD_TEMPLATE_DEFAULT` # 0
--- | `GAMEPAD_TEMPLATE_MODIFIERS_VARIANT` # 3
--- | `GAMEPAD_TEMPLATE_REUSE_ME1` # 6
--- | `GAMEPAD_TEMPLATE_REUSE_ME2` # 7
--- | `GAMEPAD_TEMPLATE_SOUTHPAW` # 1
--- | `GAMEPAD_TEMPLATE_WEAPON_TRICKS` # 5

GAMEPAD_TEMPLATE_ABILITY_MODIFIERS = 2
GAMEPAD_TEMPLATE_ALTERNATE_INTERACT = 4
GAMEPAD_TEMPLATE_DEFAULT = 0
GAMEPAD_TEMPLATE_MODIFIERS_VARIANT = 3
GAMEPAD_TEMPLATE_REUSE_ME1 = 6
GAMEPAD_TEMPLATE_REUSE_ME2 = 7
GAMEPAD_TEMPLATE_SOUTHPAW = 1
GAMEPAD_TEMPLATE_WEAPON_TRICKS = 5
