--- @meta GameCreditsEntryType

--- @alias GameCreditsEntryType integer
--- | `GAME_CREDITS_ENTRY_TYPE_BACKGROUND_SWITCH` # 5
--- | `GAME_CREDITS_ENTRY_TYPE_COMPANY_LOGO` # 4
--- | `GAME_CREDITS_ENTRY_TYPE_DEPARTMENT_HEADER` # 0
--- | `GAME_CREDITS_ENTRY_TYPE_PADDING_SECTION` # 6
--- | `GAME_CREDITS_ENTRY_TYPE_SECTION_HEADER` # 1
--- | `GAME_CREDITS_ENTRY_TYPE_SECTION_TEXT` # 2
--- | `GAME_CREDITS_ENTRY_TYPE_SECTION_TEXT_BLOCK` # 3

GAME_CREDITS_ENTRY_TYPE_BACKGROUND_SWITCH = 5
GAME_CREDITS_ENTRY_TYPE_COMPANY_LOGO = 4
GAME_CREDITS_ENTRY_TYPE_DEPARTMENT_HEADER = 0
GAME_CREDITS_ENTRY_TYPE_PADDING_SECTION = 6
GAME_CREDITS_ENTRY_TYPE_SECTION_HEADER = 1
GAME_CREDITS_ENTRY_TYPE_SECTION_TEXT = 2
GAME_CREDITS_ENTRY_TYPE_SECTION_TEXT_BLOCK = 3
