--- @meta GamepadChatTextSizeSetting

--- @alias GamepadChatTextSizeSetting integer
--- | `GAMEPAD_CHAT_TEXT_SIZE_SETTING_LARGE` # 34
--- | `GAMEPAD_CHAT_TEXT_SIZE_SETTING_MEDIUM` # 27
--- | `GAMEPAD_CHAT_TEXT_SIZE_SETTING_SMALL` # 22

GAMEPAD_CHAT_TEXT_SIZE_SETTING_LARGE = 34
GAMEPAD_CHAT_TEXT_SIZE_SETTING_MEDIUM = 27
GAMEPAD_CHAT_TEXT_SIZE_SETTING_SMALL = 22
