--- @meta GamepadTooltipColors

--- @alias GamepadTooltipColors integer
--- | `GAMEPAD_TOOLTIP_COLOR_ABILITY_UPGRADE` # 6
--- | `GAMEPAD_TOOLTIP_COLOR_ACTIVE` # 4
--- | `GAMEPAD_TOOLTIP_COLOR_FAILED` # 3
--- | `GAMEPAD_TOOLTIP_COLOR_GENERAL_COLOR_1` # 0
--- | `GAMEPAD_TOOLTIP_COLOR_GENERAL_COLOR_2` # 1
--- | `GAMEPAD_TOOLTIP_COLOR_GENERAL_COLOR_3` # 7
--- | `GAMEPAD_TOOLTIP_COLOR_INACTIVE` # 5
--- | `GAMEPAD_TOOLTIP_COLOR_SUCCEEDED` # 2

GAMEPAD_TOOLTIP_COLOR_ABILITY_UPGRADE = 6
GAMEPAD_TOOLTIP_COLOR_ACTIVE = 4
GAMEPAD_TOOLTIP_COLOR_FAILED = 3
GAMEPAD_TOOLTIP_COLOR_GENERAL_COLOR_1 = 0
GAMEPAD_TOOLTIP_COLOR_GENERAL_COLOR_2 = 1
GAMEPAD_TOOLTIP_COLOR_GENERAL_COLOR_3 = 7
GAMEPAD_TOOLTIP_COLOR_INACTIVE = 5
GAMEPAD_TOOLTIP_COLOR_SUCCEEDED = 2
