--- @meta GamepadVibrationTrigger

--- @alias GamepadVibrationTrigger integer
--- | `GAMEPAD_VIBRATION_TRIGGER_DIED` # 1
--- | `GAMEPAD_VIBRATION_TRIGGER_FALL_DAMAGE_HIGH` # 6
--- | `GAMEPAD_VIBRATION_TRIGGER_FALL_DAMAGE_LOW` # 5
--- | `GAMEPAD_VIBRATION_TRIGGER_KILLED` # 0
--- | `GAMEPAD_VIBRATION_TRIGGER_KNOCKED_BACK` # 3
--- | `GAMEPAD_VIBRATION_TRIGGER_STAGGERED` # 4
--- | `GAMEPAD_VIBRATION_TRIGGER_STUNNED` # 2

GAMEPAD_VIBRATION_TRIGGER_DIED = 1
GAMEPAD_VIBRATION_TRIGGER_FALL_DAMAGE_HIGH = 6
GAMEPAD_VIBRATION_TRIGGER_FALL_DAMAGE_LOW = 5
GAMEPAD_VIBRATION_TRIGGER_KILLED = 0
GAMEPAD_VIBRATION_TRIGGER_KNOCKED_BACK = 3
GAMEPAD_VIBRATION_TRIGGER_STAGGERED = 4
GAMEPAD_VIBRATION_TRIGGER_STUNNED = 2
