--- @meta GiftBoxActionResult

--- @alias GiftBoxActionResult integer
--- | `GIFT_ACTION_RESULT_CANNOT_GIFT_TO_PLAYER` # 2
--- | `GIFT_ACTION_RESULT_COLLECTIBLE_ALREADY_OWNED` # 8
--- | `GIFT_ACTION_RESULT_COLLECTIBLE_PARTIALLY_OWNED` # 9
--- | `GIFT_ACTION_RESULT_ERROR` # 1
--- | `GIFT_ACTION_RESULT_FINISHED` # 3
--- | `GIFT_ACTION_RESULT_GIFTING_SYSTEM_LOCKED` # 11
--- | `GIFT_ACTION_RESULT_RECIPIENT_EMPTY` # 5
--- | `GIFT_ACTION_RESULT_RECIPIENT_IGNORED` # 4
--- | `GIFT_ACTION_RESULT_RECIPIENT_NOT_DECORATED_DISPLAY_NAME` # 6
--- | `GIFT_ACTION_RESULT_RECIPIENT_NOT_FOUND` # 7
--- | `GIFT_ACTION_RESULT_SUCCESS` # 0
--- | `GIFT_ACTION_RESULT_WAITING_CONFIRM_GIVE_GIFT` # 10

GIFT_ACTION_RESULT_CANNOT_GIFT_TO_PLAYER = 2
GIFT_ACTION_RESULT_COLLECTIBLE_ALREADY_OWNED = 8
GIFT_ACTION_RESULT_COLLECTIBLE_PARTIALLY_OWNED = 9
GIFT_ACTION_RESULT_ERROR = 1
GIFT_ACTION_RESULT_FINISHED = 3
GIFT_ACTION_RESULT_GIFTING_SYSTEM_LOCKED = 11
GIFT_ACTION_RESULT_RECIPIENT_EMPTY = 5
GIFT_ACTION_RESULT_RECIPIENT_IGNORED = 4
GIFT_ACTION_RESULT_RECIPIENT_NOT_DECORATED_DISPLAY_NAME = 6
GIFT_ACTION_RESULT_RECIPIENT_NOT_FOUND = 7
GIFT_ACTION_RESULT_SUCCESS = 0
GIFT_ACTION_RESULT_WAITING_CONFIRM_GIVE_GIFT = 10
