--- @meta Globals

--- @alias Globals integer
--- | `ACCOUNT_NAME_MAX_LENGTH` # 20
--- | `ACCOUNT_NAME_MIN_LENGTH` # 3
--- | `ACTION_BAR_FIRST_NORMAL_SLOT_INDEX` # 2
--- | `ACTION_BAR_LAST_WEAPON_SLOT_INDEX` # 1
--- | `ACTION_BAR_NUM_SLOTS` # 32
--- | `ACTION_BAR_SLOTS_PER_PAGE` # 6
--- | `ACTION_BAR_ULTIMATE_SLOT_INDEX` # 7
--- | `ACTION_BAR_UTILITY_BAR_SIZE` # 8
--- | `CHARNAME_MIN_LENGTH` # 3
--- | `COLLECTIBLE_NAME_MIN_LENGTH` # 0
--- | `COMPASS_PIN_INHERIT_MAX_DISTANCE` # -1
--- | `COMPASS_PIN_NO_MAX_DISTANCE` # -1
--- | `DEFAULT_ARMORY_OPERATION_COOLDOWN_DURATION_MS` # 5000
--- | `DEFAULT_ENDLESS_DUNGEON_ID` # 1
--- | `DISPLAY_NAME_PREFIX_BYTE` # 64
--- | `EXPIRING_MARKET_CURRENCY_WARNING_THRESHOLD_SECONDS` # 432000
--- | `GAMEPAD_CUSTOM_UI_SCALE_LOWER_BOUND` # 0
--- | `GAMEPAD_CUSTOM_UI_SCALE_UPPER_BOUND` # 1
--- | `GROUP_FINDER_MAX_APPLIED_TO_GROUP_LISTING_ATTEMPTS` # 15
--- | `GROUP_FINDER_MAX_SEARCHABLE_SELECTIONS` # 5
--- | `GROUP_FINDER_UNLOCK_LEVEL` # 10
--- | `HOUSING_MAX_FURNITURE_CHILDREN` # 50
--- | `HOUSING_MAX_FURNITURE_PATH_NODES` # 30
--- | `HOUSING_MAX_GUILD_USER_GROUP_ENTRIES` # 20
--- | `HOUSING_MAX_INDIVIDUAL_USER_GROUP_ENTRIES` # 200
--- | `HOUSING_MAX_PATHS` # 10
--- | `HOUSING_MAX_PATH_NODE_WAIT_TIME` # 300000
--- | `HOUSING_MAX_UNDO_REDO_COMMANDS` # 200
--- | `HOUSING_MIN_PATH_NODE_WAIT_TIME` # 2000
--- | `IME_UNDERLINE_THICKNESS_PIXELS` # 3
--- | `INVALID_DYE_ID` # 0
--- | `INVALID_EXPLORATION_INDEX` # 294967290
--- | `INVALID_TRACKER_INDEX` # 100
--- | `KEYBOARD_CUSTOM_UI_SCALE_LOWER_BOUND` # 0
--- | `KEYBOARD_CUSTOM_UI_SCALE_UPPER_BOUND` # 1
--- | `LARGE_GROUP_SIZE_THRESHOLD` # 12
--- | `LOOP_INDEFINITELY` # 255
--- | `MAIL_EXPIRATION_IMMINENT_THRESHOLD_DAYS` # 3
--- | `MAIL_MAX_ATTACHED_ITEMS` # 6
--- | `MAXIMUM_CHAMPION_RANK` # 50
--- | `MAX_ACHIEVEMENTS` # 3850
--- | `MAX_ACTION_BAR_ABILITY_SLOTS` # 6
--- | `MAX_ANCHORS` # 2
--- | `MAX_ANTIQUITY_DIG_SITES` # 6
--- | `MAX_CHATTER_OPTIONS` # 10
--- | `MAX_COMPANION_OUTFITS` # 1
--- | `MAX_CROWN_CRATE_REWARD_SLOTS` # 5
--- | `MAX_DEVICE_ID_LENGTH` # 1024
--- | `MAX_EMAIL_LENGTH` # 256
--- | `MAX_GROUP_SIZE_THRESHOLD` # 12
--- | `MAX_GUILDS` # 5
--- | `MAX_GUILD_APPLICATION_TIME_IN_DAYS` # 15
--- | `MAX_GUILD_BLACKLISTED_PLAYERS` # 500
--- | `MAX_GUILD_ENTRIES_PER_MESSAGE` # 10
--- | `MAX_GUILD_FINDER_APPLICATIONS_PER_ACCOUNT` # 5
--- | `MAX_GUILD_MEMBERS` # 500
--- | `MAX_GUILD_RANKS` # 10
--- | `MAX_HOUSES_FOR_PERMISSIONS` # 250
--- | `MAX_INDIVIDUAL_COLLECTIBLE_UPDATES` # 4
--- | `MAX_IN_PROGRESS_ANTIQUITIES` # 5
--- | `MAX_ITEM_MATERIALS_PER_OUTFIT_STYLE` # 25
--- | `MAX_ITEM_SLOTS_PER_DECONSTRUCTION` # 100
--- | `MAX_ITERATIONS_PER_DECONSTRUCTION` # 1000
--- | `MAX_JOURNAL_QUESTS` # 25
--- | `MAX_MAILS_PER_CATEGORY` # 50
--- | `MAX_MARKET_PURCHASE_QUANTITY` # 99
--- | `MAX_NUM_ARMORY_BUILDS` # 10
--- | `MAX_OUTFIT_UNLOCKS` # 10
--- | `MAX_PASSWORD_LENGTH` # 256
--- | `MAX_PENDING_APPLICATIONS_PER_GUILD` # 500
--- | `MAX_PET_UNIT_TAGS` # 7
--- | `MAX_PLAYER_CURRENCY` # 2100000000
--- | `MAX_PROMO_CODE_LENGTH` # 20
--- | `MAX_RANKS_PER_ABILITY` # 4
--- | `MAX_STORE_WINDOW_STACK_QUANTITY` # 999
--- | `MAX_WORLD_EVENT_UNITS` # 8
--- | `MIN_REQUIRED_LEVEL_TO_CREATE_GUILD` # 10
--- | `MIN_TRADING_HOUSE_POST_PRICE` # 1
--- | `NO_POWER_INDEX` # 998
--- | `NUM_ALCHEMY_TRAITS_PER_REAGENT` # 4
--- | `NUM_ALLIANCES` # 3
--- | `NUM_ASSIGNABLE_HOTBARS` # 11
--- | `NUM_BACKPACK_SLOTS_PER_UPGRADE` # 10
--- | `NUM_BANK_SLOTS_PER_UPGRADE` # 10
--- | `NUM_BUG_CATEGORIES` # 11
--- | `NUM_COMBAT_RELATED_EQUIP_SLOTS` # 12
--- | `NUM_LOCKPICK_CHAMBERS` # 5
--- | `NUM_LOCKPICK_CHAMBER_STATES` # 4
--- | `NUM_OUTFITS_PER_UPGRADE` # 1
--- | `NUM_PARTIAL_SKILL_POINTS_FOR_FULL` # 3
--- | `NUM_SKILL_LINE_COLUMNS_PER_LINE` # 11
--- | `RANDOM_ROLL_MAX_NUM_ROLLS` # 255
--- | `RANDOM_ROLL_MAX_RESULT` # 2147483647
--- | `RANDOM_ROLL_MIN_RESULT` # -2147483647
--- | `SMALL_GROUP_SIZE_THRESHOLD` # 4
--- | `STANDARD_GROUP_SIZE_THRESHOLD` # 4
--- | `TELEPORT_WAYPOINT_INDEX_DEFAULT` # 255
--- | `TRACKER_MAX_TRACKED` # 25
--- | `TRADE_DELAY_TIME` # 2000
--- | `TRADE_NUM_SLOTS` # 5
--- | `TRIBUTE_CHAPTER_ZONE_ID` # 1318
--- | `TRIBUTE_DEFAULT_PATRON_USAGE_COUNT` # 1
--- | `TRIBUTE_PATRON_SELECTION_DELAY_SECONDS` # 4
--- | `TUTORIAL_ENABLED_SETTING_ID` # 32
--- | `VOICE_CHAT_OFFICERS_ROOM_NUMBER` # 0
--- | `VOICE_CHAT_REQUEST_DELAY` # 6000
--- | `WESTERN_SKYRIM_ZONE_ID` # 1160

ACCOUNT_NAME_MAX_LENGTH = 20
ACCOUNT_NAME_MIN_LENGTH = 3
ACTION_BAR_FIRST_NORMAL_SLOT_INDEX = 2
ACTION_BAR_LAST_WEAPON_SLOT_INDEX = 1
ACTION_BAR_NUM_SLOTS = 32
ACTION_BAR_SLOTS_PER_PAGE = 6
ACTION_BAR_ULTIMATE_SLOT_INDEX = 7
ACTION_BAR_UTILITY_BAR_SIZE = 8
CHARNAME_MIN_LENGTH = 3
COLLECTIBLE_NAME_MIN_LENGTH = 0
COMPASS_PIN_INHERIT_MAX_DISTANCE = -1
COMPASS_PIN_NO_MAX_DISTANCE = -1
DEFAULT_ARMORY_OPERATION_COOLDOWN_DURATION_MS = 5000
DEFAULT_ENDLESS_DUNGEON_ID = 1
DISPLAY_NAME_PREFIX_BYTE = 64
EXPIRING_MARKET_CURRENCY_WARNING_THRESHOLD_SECONDS = 432000
GAMEPAD_CUSTOM_UI_SCALE_LOWER_BOUND = 0
GAMEPAD_CUSTOM_UI_SCALE_UPPER_BOUND = 1
GROUP_FINDER_MAX_APPLIED_TO_GROUP_LISTING_ATTEMPTS = 15
GROUP_FINDER_MAX_SEARCHABLE_SELECTIONS = 5
GROUP_FINDER_UNLOCK_LEVEL = 10
HOUSING_MAX_FURNITURE_CHILDREN = 50
HOUSING_MAX_FURNITURE_PATH_NODES = 30
HOUSING_MAX_GUILD_USER_GROUP_ENTRIES = 20
HOUSING_MAX_INDIVIDUAL_USER_GROUP_ENTRIES = 200
HOUSING_MAX_PATHS = 10
HOUSING_MAX_PATH_NODE_WAIT_TIME = 300000
HOUSING_MAX_UNDO_REDO_COMMANDS = 200
HOUSING_MIN_PATH_NODE_WAIT_TIME = 2000
IME_UNDERLINE_THICKNESS_PIXELS = 3
INVALID_DYE_ID = 0
INVALID_EXPLORATION_INDEX = 294967290
INVALID_TRACKER_INDEX = 100
KEYBOARD_CUSTOM_UI_SCALE_LOWER_BOUND = 0
KEYBOARD_CUSTOM_UI_SCALE_UPPER_BOUND = 1
LARGE_GROUP_SIZE_THRESHOLD = 12
LOOP_INDEFINITELY = 255
MAIL_EXPIRATION_IMMINENT_THRESHOLD_DAYS = 3
MAIL_MAX_ATTACHED_ITEMS = 6
MAXIMUM_CHAMPION_RANK = 50
MAX_ACHIEVEMENTS = 3850
MAX_ACTION_BAR_ABILITY_SLOTS = 6
MAX_ANCHORS = 2
MAX_ANTIQUITY_DIG_SITES = 6
MAX_CHATTER_OPTIONS = 10
MAX_COMPANION_OUTFITS = 1
MAX_CROWN_CRATE_REWARD_SLOTS = 5
MAX_DEVICE_ID_LENGTH = 1024
MAX_EMAIL_LENGTH = 256
MAX_GROUP_SIZE_THRESHOLD = 12
MAX_GUILDS = 5
MAX_GUILD_APPLICATION_TIME_IN_DAYS = 15
MAX_GUILD_BLACKLISTED_PLAYERS = 500
MAX_GUILD_ENTRIES_PER_MESSAGE = 10
MAX_GUILD_FINDER_APPLICATIONS_PER_ACCOUNT = 5
MAX_GUILD_MEMBERS = 500
MAX_GUILD_RANKS = 10
MAX_HOUSES_FOR_PERMISSIONS = 250
MAX_INDIVIDUAL_COLLECTIBLE_UPDATES = 4
MAX_IN_PROGRESS_ANTIQUITIES = 5
MAX_ITEM_MATERIALS_PER_OUTFIT_STYLE = 25
MAX_ITEM_SLOTS_PER_DECONSTRUCTION = 100
MAX_ITERATIONS_PER_DECONSTRUCTION = 1000
MAX_JOURNAL_QUESTS = 25
MAX_MAILS_PER_CATEGORY = 50
MAX_MARKET_PURCHASE_QUANTITY = 99
MAX_NUM_ARMORY_BUILDS = 10
MAX_OUTFIT_UNLOCKS = 10
MAX_PASSWORD_LENGTH = 256
MAX_PENDING_APPLICATIONS_PER_GUILD = 500
MAX_PET_UNIT_TAGS = 7
MAX_PLAYER_CURRENCY = 2100000000
MAX_PROMO_CODE_LENGTH = 20
MAX_RANKS_PER_ABILITY = 4
MAX_STORE_WINDOW_STACK_QUANTITY = 999
MAX_WORLD_EVENT_UNITS = 8
MIN_REQUIRED_LEVEL_TO_CREATE_GUILD = 10
MIN_TRADING_HOUSE_POST_PRICE = 1
NO_POWER_INDEX = 998
NUM_ALCHEMY_TRAITS_PER_REAGENT = 4
NUM_ALLIANCES = 3
NUM_ASSIGNABLE_HOTBARS = 11
NUM_BACKPACK_SLOTS_PER_UPGRADE = 10
NUM_BANK_SLOTS_PER_UPGRADE = 10
NUM_BUG_CATEGORIES = 11
NUM_COMBAT_RELATED_EQUIP_SLOTS = 12
NUM_LOCKPICK_CHAMBERS = 5
NUM_LOCKPICK_CHAMBER_STATES = 4
NUM_OUTFITS_PER_UPGRADE = 1
NUM_PARTIAL_SKILL_POINTS_FOR_FULL = 3
NUM_SKILL_LINE_COLUMNS_PER_LINE = 11
RANDOM_ROLL_MAX_NUM_ROLLS = 255
RANDOM_ROLL_MAX_RESULT = 2147483647
RANDOM_ROLL_MIN_RESULT = -2147483647
SMALL_GROUP_SIZE_THRESHOLD = 4
STANDARD_GROUP_SIZE_THRESHOLD = 4
TELEPORT_WAYPOINT_INDEX_DEFAULT = 255
TRACKER_MAX_TRACKED = 25
TRADE_DELAY_TIME = 2000
TRADE_NUM_SLOTS = 5
TRIBUTE_CHAPTER_ZONE_ID = 1318
TRIBUTE_DEFAULT_PATRON_USAGE_COUNT = 1
TRIBUTE_PATRON_SELECTION_DELAY_SECONDS = 4
TUTORIAL_ENABLED_SETTING_ID = 32
VOICE_CHAT_OFFICERS_ROOM_NUMBER = 0
VOICE_CHAT_REQUEST_DELAY = 6000
WESTERN_SKYRIM_ZONE_ID = 1160
