--- @meta GraphicsPresets

--- @alias GraphicsPresets integer
--- | `GRAPHICS_PRESETS_CUSTOM` # 7
--- | `GRAPHICS_PRESETS_HIGH` # 3
--- | `GRAPHICS_PRESETS_LOW` # 1
--- | `GRAPHICS_PRESETS_MAXIMUM` # 16
--- | `GRAPHICS_PRESETS_MEDIUM` # 2
--- | `GRAPHICS_PRESETS_MINIMUM` # 0
--- | `GRAPHICS_PRESETS_PS4` # 5
--- | `GRAPHICS_PRESETS_PS4PLUS1080P` # 8
--- | `GRAPHICS_PRESETS_PS4PLUS4K` # 9
--- | `GRAPHICS_PRESETS_PS5` # 12
--- | `GRAPHICS_PRESETS_REUSE_ME` # 11
--- | `GRAPHICS_PRESETS_SCORPIO` # 10
--- | `GRAPHICS_PRESETS_ULTRA` # 4
--- | `GRAPHICS_PRESETS_XB1` # 6
--- | `GRAPHICS_PRESETS_XBSS` # 14
--- | `GRAPHICS_PRESETS_XBSS_PERF` # 15
--- | `GRAPHICS_PRESETS_XBSX` # 13

GRAPHICS_PRESETS_CUSTOM = 7
GRAPHICS_PRESETS_HIGH = 3
GRAPHICS_PRESETS_LOW = 1
GRAPHICS_PRESETS_MAXIMUM = 16
GRAPHICS_PRESETS_MEDIUM = 2
GRAPHICS_PRESETS_MINIMUM = 0
GRAPHICS_PRESETS_PS4 = 5
GRAPHICS_PRESETS_PS4PLUS1080P = 8
GRAPHICS_PRESETS_PS4PLUS4K = 9
GRAPHICS_PRESETS_PS5 = 12
GRAPHICS_PRESETS_REUSE_ME = 11
GRAPHICS_PRESETS_SCORPIO = 10
GRAPHICS_PRESETS_ULTRA = 4
GRAPHICS_PRESETS_XB1 = 6
GRAPHICS_PRESETS_XBSS = 14
GRAPHICS_PRESETS_XBSS_PERF = 15
GRAPHICS_PRESETS_XBSX = 13
