--- @meta GregorianCalendarMonths

--- @alias GregorianCalendarMonths integer
--- | `GREGORIAN_CALENDAR_MONTHS_MONTH_EIGHT` # 8
--- | `GREGORIAN_CALENDAR_MONTHS_MONTH_ELEVEN` # 11
--- | `GREGORIAN_CALENDAR_MONTHS_MONTH_FIVE` # 5
--- | `GREGORIAN_CALENDAR_MONTHS_MONTH_FOUR` # 4
--- | `GREGORIAN_CALENDAR_MONTHS_MONTH_NINE` # 9
--- | `GREGORIAN_CALENDAR_MONTHS_MONTH_ONE` # 1
--- | `GREGORIAN_CALENDAR_MONTHS_MONTH_SEVEN` # 7
--- | `GREGORIAN_CALENDAR_MONTHS_MONTH_SIX` # 6
--- | `GREGORIAN_CALENDAR_MONTHS_MONTH_TEN` # 10
--- | `GREGORIAN_CALENDAR_MONTHS_MONTH_THREE` # 3
--- | `GREGORIAN_CALENDAR_MONTHS_MONTH_TWELVE` # 12
--- | `GREGORIAN_CALENDAR_MONTHS_MONTH_TWO` # 2

GREGORIAN_CALENDAR_MONTHS_MONTH_EIGHT = 8
GREGORIAN_CALENDAR_MONTHS_MONTH_ELEVEN = 11
GREGORIAN_CALENDAR_MONTHS_MONTH_FIVE = 5
GREGORIAN_CALENDAR_MONTHS_MONTH_FOUR = 4
GREGORIAN_CALENDAR_MONTHS_MONTH_NINE = 9
GREGORIAN_CALENDAR_MONTHS_MONTH_ONE = 1
GREGORIAN_CALENDAR_MONTHS_MONTH_SEVEN = 7
GREGORIAN_CALENDAR_MONTHS_MONTH_SIX = 6
GREGORIAN_CALENDAR_MONTHS_MONTH_TEN = 10
GREGORIAN_CALENDAR_MONTHS_MONTH_THREE = 3
GREGORIAN_CALENDAR_MONTHS_MONTH_TWELVE = 12
GREGORIAN_CALENDAR_MONTHS_MONTH_TWO = 2
