--- @meta GroupOperationResult

--- @alias GroupOperationResult integer
--- | `GROUP_OPERATION_RESULT_BLOCKED_BY_ACTIVE_READY_CHECK` # 1
--- | `GROUP_OPERATION_RESULT_NONE` # 0

GROUP_OPERATION_RESULT_BLOCKED_BY_ACTIVE_READY_CHECK = 1
GROUP_OPERATION_RESULT_NONE = 0
