--- @meta GroupFinderGroupListingUserType

--- @alias GroupFinderGroupListingUserType integer
--- | `GROUP_FINDER_GROUP_LISTING_USER_TYPE_APPLIED_TO_GROUP_LISTING` # 2
--- | `GROUP_FINDER_GROUP_LISTING_USER_TYPE_CREATED_GROUP_LISTING` # 1
--- | `GROUP_FINDER_GROUP_LISTING_USER_TYPE_GROUP_LISTING_DRAFT` # 0

GROUP_FINDER_GROUP_LISTING_USER_TYPE_APPLIED_TO_GROUP_LISTING = 2
GROUP_FINDER_GROUP_LISTING_USER_TYPE_CREATED_GROUP_LISTING = 1
GROUP_FINDER_GROUP_LISTING_USER_TYPE_GROUP_LISTING_DRAFT = 0
