--- @meta GroupElectionFlags

--- @alias GroupElectionFlags integer
--- | `GROUP_ELECTION_FLAGS_IGNORE_OFFLINE_MEMBERS` # 2
--- | `GROUP_ELECTION_FLAGS_REQUIRE_ALL_VOTES` # 1

GROUP_ELECTION_FLAGS_IGNORE_OFFLINE_MEMBERS = 2
GROUP_ELECTION_FLAGS_REQUIRE_ALL_VOTES = 1
