--- @meta GroupFinderGroupSize

--- @alias GroupFinderGroupSize integer
--- | `GROUP_FINDER_SIZE_LARGE` # 4
--- | `GROUP_FINDER_SIZE_SMALL` # 1
--- | `GROUP_FINDER_SIZE_STANDARD` # 2

GROUP_FINDER_SIZE_LARGE = 4
GROUP_FINDER_SIZE_SMALL = 1
GROUP_FINDER_SIZE_STANDARD = 2
