--- @meta GroupLeaveReason

--- @alias GroupLeaveReason integer
--- | `GROUP_LEAVE_REASON_DESTROYED` # 3
--- | `GROUP_LEAVE_REASON_DISBAND` # 2
--- | `GROUP_LEAVE_REASON_KICKED` # 1
--- | `GROUP_LEAVE_REASON_LEFT_BATTLEGROUND` # 4
--- | `GROUP_LEAVE_REASON_VOLUNTARY` # 0

GROUP_LEAVE_REASON_DESTROYED = 3
GROUP_LEAVE_REASON_DISBAND = 2
GROUP_LEAVE_REASON_KICKED = 1
GROUP_LEAVE_REASON_LEFT_BATTLEGROUND = 4
GROUP_LEAVE_REASON_VOLUNTARY = 0
