--- @meta GroupElectionResult

--- @alias GroupElectionResult integer
--- | `GROUP_ELECTION_RESULT_ABANDONED` # 3
--- | `GROUP_ELECTION_RESULT_ELECTION_LOST` # 5
--- | `GROUP_ELECTION_RESULT_ELECTION_WON` # 4
--- | `GROUP_ELECTION_RESULT_IN_PROGRESS` # 6
--- | `GROUP_ELECTION_RESULT_NOT_APPLICABLE` # 0
--- | `GROUP_ELECTION_RESULT_TIED` # 2
--- | `GROUP_ELECTION_RESULT_TIMED_OUT` # 1

GROUP_ELECTION_RESULT_ABANDONED = 3
GROUP_ELECTION_RESULT_ELECTION_LOST = 5
GROUP_ELECTION_RESULT_ELECTION_WON = 4
GROUP_ELECTION_RESULT_IN_PROGRESS = 6
GROUP_ELECTION_RESULT_NOT_APPLICABLE = 0
GROUP_ELECTION_RESULT_TIED = 2
GROUP_ELECTION_RESULT_TIMED_OUT = 1
