--- @meta GroupFinderStatus

--- @alias GroupFinderStatus integer
--- | `GROUP_FINDER_STATUS_AVAILABLE` # 0
--- | `GROUP_FINDER_STATUS_DISABLED` # 1
--- | `GROUP_FINDER_STATUS_DOWN` # 2

GROUP_FINDER_STATUS_AVAILABLE = 0
GROUP_FINDER_STATUS_DISABLED = 1
GROUP_FINDER_STATUS_DOWN = 2
