--- @meta GroupFinderCategory

--- @alias GroupFinderCategory integer
--- | `GROUP_FINDER_CATEGORY_ARENA` # 1
--- | `GROUP_FINDER_CATEGORY_CUSTOM` # 6
--- | `GROUP_FINDER_CATEGORY_DUNGEON` # 0
--- | `GROUP_FINDER_CATEGORY_ENDLESS_DUNGEON` # 3
--- | `GROUP_FINDER_CATEGORY_PVP` # 4
--- | `GROUP_FINDER_CATEGORY_TRIAL` # 2
--- | `GROUP_FINDER_CATEGORY_ZONE` # 5

GROUP_FINDER_CATEGORY_ARENA = 1
GROUP_FINDER_CATEGORY_CUSTOM = 6
GROUP_FINDER_CATEGORY_DUNGEON = 0
GROUP_FINDER_CATEGORY_ENDLESS_DUNGEON = 3
GROUP_FINDER_CATEGORY_PVP = 4
GROUP_FINDER_CATEGORY_TRIAL = 2
GROUP_FINDER_CATEGORY_ZONE = 5
