--- @meta GroupElectionFailure

--- @alias GroupElectionFailure integer
--- | `GROUP_ELECTION_FAILURE_ALREADY_VOTED` # 11
--- | `GROUP_ELECTION_FAILURE_ANOTHER_IN_PROGRESS` # 5
--- | `GROUP_ELECTION_FAILURE_INITIATOR_CANNOT_VOTE` # 10
--- | `GROUP_ELECTION_FAILURE_INITIATOR_NOT_FOUND` # 2
--- | `GROUP_ELECTION_FAILURE_IN_BATTLEGROUND` # 13
--- | `GROUP_ELECTION_FAILURE_NONE` # 0
--- | `GROUP_ELECTION_FAILURE_NOT_GROUPED` # 8
--- | `GROUP_ELECTION_FAILURE_NO_CURRENT_ELECTION` # 9
--- | `GROUP_ELECTION_FAILURE_SAME_INITIATOR_AND_TARGET` # 6
--- | `GROUP_ELECTION_FAILURE_SERVER_ERROR` # 1
--- | `GROUP_ELECTION_FAILURE_TARGET_NOT_FOUND` # 3
--- | `GROUP_ELECTION_FAILURE_TOO_FEW_MEMBERS` # 7
--- | `GROUP_ELECTION_FAILURE_TOO_SOON` # 12
--- | `GROUP_ELECTION_FAILURE_UNKNOWN_CHOICE` # 4

GROUP_ELECTION_FAILURE_ALREADY_VOTED = 11
GROUP_ELECTION_FAILURE_ANOTHER_IN_PROGRESS = 5
GROUP_ELECTION_FAILURE_INITIATOR_CANNOT_VOTE = 10
GROUP_ELECTION_FAILURE_INITIATOR_NOT_FOUND = 2
GROUP_ELECTION_FAILURE_IN_BATTLEGROUND = 13
GROUP_ELECTION_FAILURE_NONE = 0
GROUP_ELECTION_FAILURE_NOT_GROUPED = 8
GROUP_ELECTION_FAILURE_NO_CURRENT_ELECTION = 9
GROUP_ELECTION_FAILURE_SAME_INITIATOR_AND_TARGET = 6
GROUP_ELECTION_FAILURE_SERVER_ERROR = 1
GROUP_ELECTION_FAILURE_TARGET_NOT_FOUND = 3
GROUP_ELECTION_FAILURE_TOO_FEW_MEMBERS = 7
GROUP_ELECTION_FAILURE_TOO_SOON = 12
GROUP_ELECTION_FAILURE_UNKNOWN_CHOICE = 4
