--- @meta GroupElectionType

--- @alias GroupElectionType integer
--- | `GROUP_ELECTION_TYPE_GENERIC_SIMPLEMAJORITY` # 0
--- | `GROUP_ELECTION_TYPE_GENERIC_SUPERMAJORITY` # 1
--- | `GROUP_ELECTION_TYPE_GENERIC_UNANIMOUS` # 2
--- | `GROUP_ELECTION_TYPE_KICK_MEMBER` # 3
--- | `GROUP_ELECTION_TYPE_NEW_LEADER` # 4

GROUP_ELECTION_TYPE_GENERIC_SIMPLEMAJORITY = 0
GROUP_ELECTION_TYPE_GENERIC_SUPERMAJORITY = 1
GROUP_ELECTION_TYPE_GENERIC_UNANIMOUS = 2
GROUP_ELECTION_TYPE_KICK_MEMBER = 3
GROUP_ELECTION_TYPE_NEW_LEADER = 4
