--- @meta GroupFinderMemberAlert

--- @alias GroupFinderMemberAlert integer
--- | `GROUP_FINDER_MEMBER_ALERT_LISTING_CREATED` # 0
--- | `GROUP_FINDER_MEMBER_ALERT_LISTING_REMOVED_BY_LEADER` # 1
--- | `GROUP_FINDER_MEMBER_ALERT_LISTING_REMOVED_DISABLED_IN_ZONE` # 3
--- | `GROUP_FINDER_MEMBER_ALERT_LISTING_REMOVED_JOINED_QUEUE` # 4
--- | `GROUP_FINDER_MEMBER_ALERT_LISTING_REMOVED_LEADER_CHANGED` # 6
--- | `GROUP_FINDER_MEMBER_ALERT_LISTING_REMOVED_LEADER_DISCONNECTED` # 5
--- | `GROUP_FINDER_MEMBER_ALERT_LISTING_REMOVED_SERVER_ERROR` # 2

GROUP_FINDER_MEMBER_ALERT_LISTING_CREATED = 0
GROUP_FINDER_MEMBER_ALERT_LISTING_REMOVED_BY_LEADER = 1
GROUP_FINDER_MEMBER_ALERT_LISTING_REMOVED_DISABLED_IN_ZONE = 3
GROUP_FINDER_MEMBER_ALERT_LISTING_REMOVED_JOINED_QUEUE = 4
GROUP_FINDER_MEMBER_ALERT_LISTING_REMOVED_LEADER_CHANGED = 6
GROUP_FINDER_MEMBER_ALERT_LISTING_REMOVED_LEADER_DISCONNECTED = 5
GROUP_FINDER_MEMBER_ALERT_LISTING_REMOVED_SERVER_ERROR = 2
