--- @meta GroupVoteChoice

--- @alias GroupVoteChoice integer
--- | `GROUP_VOTE_CHOICE_ABSTAIN` # 0
--- | `GROUP_VOTE_CHOICE_AGAINST` # 2
--- | `GROUP_VOTE_CHOICE_FOR` # 1
--- | `GROUP_VOTE_CHOICE_INVALID` # 3

GROUP_VOTE_CHOICE_ABSTAIN = 0
GROUP_VOTE_CHOICE_AGAINST = 2
GROUP_VOTE_CHOICE_FOR = 1
GROUP_VOTE_CHOICE_INVALID = 3
