--- @meta GroupInviteResponse

--- @alias GroupInviteResponse integer
--- | `GROUP_INVITE_RESPONSE_ACCEPTED` # 1
--- | `GROUP_INVITE_RESPONSE_ALREADY_GROUPED` # 5
--- | `GROUP_INVITE_RESPONSE_ALREADY_GROUPED_CANT_JOIN` # 16
--- | `GROUP_INVITE_RESPONSE_CANNOT_CREATE_GROUPS` # 11
--- | `GROUP_INVITE_RESPONSE_CONSIDERING_OTHER` # 4
--- | `GROUP_INVITE_RESPONSE_DECLINED` # 2
--- | `GROUP_INVITE_RESPONSE_FAIL_JOIN_ON_LOAD` # 17
--- | `GROUP_INVITE_RESPONSE_GENERIC_JOIN_FAILURE` # 12
--- | `GROUP_INVITE_RESPONSE_GROUP_FULL` # 6
--- | `GROUP_INVITE_RESPONSE_HAS_GROUP_FINDER_APPLICATION` # 20
--- | `GROUP_INVITE_RESPONSE_HAS_GROUP_FINDER_LISTING` # 21
--- | `GROUP_INVITE_RESPONSE_IGNORED` # 3
--- | `GROUP_INVITE_RESPONSE_INVITED` # 10
--- | `GROUP_INVITE_RESPONSE_IN_BATTLEGROUND` # 15
--- | `GROUP_INVITE_RESPONSE_ONLY_LEADER_CAN_INVITE` # 8
--- | `GROUP_INVITE_RESPONSE_OTHER_ALLIANCE` # 9
--- | `GROUP_INVITE_RESPONSE_PLATFORM_INVITE_NOT_SENT` # 19
--- | `GROUP_INVITE_RESPONSE_PLAYER_NOT_FOUND` # 0
--- | `GROUP_INVITE_RESPONSE_REQUEST_FAIL_ALREADY_GROUPED` # 14
--- | `GROUP_INVITE_RESPONSE_REQUEST_FAIL_ALREADY_GROUPED_GENERIC` # 18
--- | `GROUP_INVITE_RESPONSE_REQUEST_FAIL_GROUP_FULL` # 13
--- | `GROUP_INVITE_RESPONSE_SELF_INVITE` # 7

GROUP_INVITE_RESPONSE_ACCEPTED = 1
GROUP_INVITE_RESPONSE_ALREADY_GROUPED = 5
GROUP_INVITE_RESPONSE_ALREADY_GROUPED_CANT_JOIN = 16
GROUP_INVITE_RESPONSE_CANNOT_CREATE_GROUPS = 11
GROUP_INVITE_RESPONSE_CONSIDERING_OTHER = 4
GROUP_INVITE_RESPONSE_DECLINED = 2
GROUP_INVITE_RESPONSE_FAIL_JOIN_ON_LOAD = 17
GROUP_INVITE_RESPONSE_GENERIC_JOIN_FAILURE = 12
GROUP_INVITE_RESPONSE_GROUP_FULL = 6
GROUP_INVITE_RESPONSE_HAS_GROUP_FINDER_APPLICATION = 20
GROUP_INVITE_RESPONSE_HAS_GROUP_FINDER_LISTING = 21
GROUP_INVITE_RESPONSE_IGNORED = 3
GROUP_INVITE_RESPONSE_INVITED = 10
GROUP_INVITE_RESPONSE_IN_BATTLEGROUND = 15
GROUP_INVITE_RESPONSE_ONLY_LEADER_CAN_INVITE = 8
GROUP_INVITE_RESPONSE_OTHER_ALLIANCE = 9
GROUP_INVITE_RESPONSE_PLATFORM_INVITE_NOT_SENT = 19
GROUP_INVITE_RESPONSE_PLAYER_NOT_FOUND = 0
GROUP_INVITE_RESPONSE_REQUEST_FAIL_ALREADY_GROUPED = 14
GROUP_INVITE_RESPONSE_REQUEST_FAIL_ALREADY_GROUPED_GENERIC = 18
GROUP_INVITE_RESPONSE_REQUEST_FAIL_GROUP_FULL = 13
GROUP_INVITE_RESPONSE_SELF_INVITE = 7
