--- @meta GroupDifficultyChangeReason

--- @alias GroupDifficultyChangeReason integer
--- | `GROUP_DIFFICULTY_CHANGE_REASON_ACTIVE_GROUP_LISTING` # 6
--- | `GROUP_DIFFICULTY_CHANGE_REASON_IN_DUNGEON` # 3
--- | `GROUP_DIFFICULTY_CHANGE_REASON_IN_LFG_GROUP` # 4
--- | `GROUP_DIFFICULTY_CHANGE_REASON_NOT_GROUP_LEADER` # 2
--- | `GROUP_DIFFICULTY_CHANGE_REASON_NOT_UNLOCKED` # 1
--- | `GROUP_DIFFICULTY_CHANGE_REASON_NO_UNIT` # 5
--- | `GROUP_DIFFICULTY_CHANGE_REASON_SUCCESS` # 0

GROUP_DIFFICULTY_CHANGE_REASON_ACTIVE_GROUP_LISTING = 6
GROUP_DIFFICULTY_CHANGE_REASON_IN_DUNGEON = 3
GROUP_DIFFICULTY_CHANGE_REASON_IN_LFG_GROUP = 4
GROUP_DIFFICULTY_CHANGE_REASON_NOT_GROUP_LEADER = 2
GROUP_DIFFICULTY_CHANGE_REASON_NOT_UNLOCKED = 1
GROUP_DIFFICULTY_CHANGE_REASON_NO_UNIT = 5
GROUP_DIFFICULTY_CHANGE_REASON_SUCCESS = 0
