--- @meta GroupFinderActionResult

--- @alias GroupFinderActionResult integer
--- | `GROUP_FINDER_ACTION_RESULT_FAILED` # 1
--- | `GROUP_FINDER_ACTION_RESULT_FAILED_ACCOUNT_TYPE_BLOCKS_APPLICATION` # 26
--- | `GROUP_FINDER_ACTION_RESULT_FAILED_ACCOUNT_TYPE_BLOCKS_CREATION` # 25
--- | `GROUP_FINDER_ACTION_RESULT_FAILED_ALLIANCE_REQUIREMENT` # 19
--- | `GROUP_FINDER_ACTION_RESULT_FAILED_ALREADY_APPLIED_TO_LISTING` # 5
--- | `GROUP_FINDER_ACTION_RESULT_FAILED_ALREADY_JOINED_GROUP` # 4
--- | `GROUP_FINDER_ACTION_RESULT_FAILED_APPLICATION_DECLINED` # 27
--- | `GROUP_FINDER_ACTION_RESULT_FAILED_APPLICATION_PENDING` # 28
--- | `GROUP_FINDER_ACTION_RESULT_FAILED_CP_REQUIREMENT` # 10
--- | `GROUP_FINDER_ACTION_RESULT_FAILED_DISABLED_IN_ZONE` # 20
--- | `GROUP_FINDER_ACTION_RESULT_FAILED_ENTITLEMENT_REQUIREMENT` # 12
--- | `GROUP_FINDER_ACTION_RESULT_FAILED_GROUP_SIZE_MISMATCH` # 9
--- | `GROUP_FINDER_ACTION_RESULT_FAILED_HAS_EXISTING_GROUP_LISTING` # 7
--- | `GROUP_FINDER_ACTION_RESULT_FAILED_HAS_PENDING_GROUP_INVITE` # 23
--- | `GROUP_FINDER_ACTION_RESULT_FAILED_INCORRECT_INVITE_CODE` # 3
--- | `GROUP_FINDER_ACTION_RESULT_FAILED_LEADER_BUSY` # 21
--- | `GROUP_FINDER_ACTION_RESULT_FAILED_LEVEL_REQUIREMENT` # 11
--- | `GROUP_FINDER_ACTION_RESULT_FAILED_LISTING_NOT_AVAILABLE` # 2
--- | `GROUP_FINDER_ACTION_RESULT_FAILED_MAXIMUM_ATTEMPTS` # 18
--- | `GROUP_FINDER_ACTION_RESULT_FAILED_NOT_ENABLED` # 15
--- | `GROUP_FINDER_ACTION_RESULT_FAILED_NOT_LEADER` # 6
--- | `GROUP_FINDER_ACTION_RESULT_FAILED_NOT_QUALIFIED_FOR_LFG_SET` # 14
--- | `GROUP_FINDER_ACTION_RESULT_FAILED_PLATFORM_RESTRICTIONS` # 29
--- | `GROUP_FINDER_ACTION_RESULT_FAILED_QUEUED` # 22
--- | `GROUP_FINDER_ACTION_RESULT_FAILED_REQUEST_PENDING` # 17
--- | `GROUP_FINDER_ACTION_RESULT_FAILED_REQUEST_TIMEOUT` # 16
--- | `GROUP_FINDER_ACTION_RESULT_FAILED_ROLE_MISMATCH` # 8
--- | `GROUP_FINDER_ACTION_RESULT_FAILED_ROLE_REQUIREMENT` # 13
--- | `GROUP_FINDER_ACTION_RESULT_FAILED_SOLO_REQUIREMENT` # 24
--- | `GROUP_FINDER_ACTION_RESULT_SUCCESS` # 0

GROUP_FINDER_ACTION_RESULT_FAILED = 1
GROUP_FINDER_ACTION_RESULT_FAILED_ACCOUNT_TYPE_BLOCKS_APPLICATION = 26
GROUP_FINDER_ACTION_RESULT_FAILED_ACCOUNT_TYPE_BLOCKS_CREATION = 25
GROUP_FINDER_ACTION_RESULT_FAILED_ALLIANCE_REQUIREMENT = 19
GROUP_FINDER_ACTION_RESULT_FAILED_ALREADY_APPLIED_TO_LISTING = 5
GROUP_FINDER_ACTION_RESULT_FAILED_ALREADY_JOINED_GROUP = 4
GROUP_FINDER_ACTION_RESULT_FAILED_APPLICATION_DECLINED = 27
GROUP_FINDER_ACTION_RESULT_FAILED_APPLICATION_PENDING = 28
GROUP_FINDER_ACTION_RESULT_FAILED_CP_REQUIREMENT = 10
GROUP_FINDER_ACTION_RESULT_FAILED_DISABLED_IN_ZONE = 20
GROUP_FINDER_ACTION_RESULT_FAILED_ENTITLEMENT_REQUIREMENT = 12
GROUP_FINDER_ACTION_RESULT_FAILED_GROUP_SIZE_MISMATCH = 9
GROUP_FINDER_ACTION_RESULT_FAILED_HAS_EXISTING_GROUP_LISTING = 7
GROUP_FINDER_ACTION_RESULT_FAILED_HAS_PENDING_GROUP_INVITE = 23
GROUP_FINDER_ACTION_RESULT_FAILED_INCORRECT_INVITE_CODE = 3
GROUP_FINDER_ACTION_RESULT_FAILED_LEADER_BUSY = 21
GROUP_FINDER_ACTION_RESULT_FAILED_LEVEL_REQUIREMENT = 11
GROUP_FINDER_ACTION_RESULT_FAILED_LISTING_NOT_AVAILABLE = 2
GROUP_FINDER_ACTION_RESULT_FAILED_MAXIMUM_ATTEMPTS = 18
GROUP_FINDER_ACTION_RESULT_FAILED_NOT_ENABLED = 15
GROUP_FINDER_ACTION_RESULT_FAILED_NOT_LEADER = 6
GROUP_FINDER_ACTION_RESULT_FAILED_NOT_QUALIFIED_FOR_LFG_SET = 14
GROUP_FINDER_ACTION_RESULT_FAILED_PLATFORM_RESTRICTIONS = 29
GROUP_FINDER_ACTION_RESULT_FAILED_QUEUED = 22
GROUP_FINDER_ACTION_RESULT_FAILED_REQUEST_PENDING = 17
GROUP_FINDER_ACTION_RESULT_FAILED_REQUEST_TIMEOUT = 16
GROUP_FINDER_ACTION_RESULT_FAILED_ROLE_MISMATCH = 8
GROUP_FINDER_ACTION_RESULT_FAILED_ROLE_REQUIREMENT = 13
GROUP_FINDER_ACTION_RESULT_FAILED_SOLO_REQUIREMENT = 24
GROUP_FINDER_ACTION_RESULT_SUCCESS = 0
