--- @meta GroupFinderPlaystyle

--- @alias GroupFinderPlaystyle integer
--- | `GROUP_FINDER_PLAYSTYLE_ACHIEVEMENT` # 8
--- | `GROUP_FINDER_PLAYSTYLE_EDUCATIONAL` # 2
--- | `GROUP_FINDER_PLAYSTYLE_ROLE_PLAY` # 16
--- | `GROUP_FINDER_PLAYSTYLE_SPEED` # 4
--- | `GROUP_FINDER_PLAYSTYLE_STANDARD` # 1
--- | `GROUP_FINDER_PLAYSTYLE_STORY` # 32

GROUP_FINDER_PLAYSTYLE_ACHIEVEMENT = 8
GROUP_FINDER_PLAYSTYLE_EDUCATIONAL = 2
GROUP_FINDER_PLAYSTYLE_ROLE_PLAY = 16
GROUP_FINDER_PLAYSTYLE_SPEED = 4
GROUP_FINDER_PLAYSTYLE_STANDARD = 1
GROUP_FINDER_PLAYSTYLE_STORY = 32
