--- @meta GroupNotificationMessage

--- @alias GroupNotificationMessage integer
--- | `GROUP_MSG_CANT_KICK_YOURSELF` # 3
--- | `GROUP_MSG_CANT_PROMOTE_MEMBER_IS_OFFLINE` # 5
--- | `GROUP_MSG_CANT_PROMOTE_YOURSELF` # 4
--- | `GROUP_MSG_INVALID_MEMBER` # 2
--- | `GROUP_MSG_YOU_ARE_NOT_IN_A_GROUP` # 0
--- | `GROUP_MSG_YOU_ARE_NOT_THE_LEADER` # 1

GROUP_MSG_CANT_KICK_YOURSELF = 3
GROUP_MSG_CANT_PROMOTE_MEMBER_IS_OFFLINE = 5
GROUP_MSG_CANT_PROMOTE_YOURSELF = 4
GROUP_MSG_INVALID_MEMBER = 2
GROUP_MSG_YOU_ARE_NOT_IN_A_GROUP = 0
GROUP_MSG_YOU_ARE_NOT_THE_LEADER = 1
