--- @meta GuildKioskGuildInfoResult

--- @alias GuildKioskGuildInfoResult integer
--- | `GUILD_KIOSK_GUILD_INFO_RESULT_NO_GUILD` # 2
--- | `GUILD_KIOSK_GUILD_INFO_RESULT_NO_INFO` # 1
--- | `GUILD_KIOSK_GUILD_INFO_RESULT_NO_INFO_FOR_ANY_GUILD` # 4
--- | `GUILD_KIOSK_GUILD_INFO_RESULT_NO_INFO_FOR_GUILD` # 3
--- | `GUILD_KIOSK_GUILD_INFO_RESULT_SUCCESS` # 0

GUILD_KIOSK_GUILD_INFO_RESULT_NO_GUILD = 2
GUILD_KIOSK_GUILD_INFO_RESULT_NO_INFO = 1
GUILD_KIOSK_GUILD_INFO_RESULT_NO_INFO_FOR_ANY_GUILD = 4
GUILD_KIOSK_GUILD_INFO_RESULT_NO_INFO_FOR_GUILD = 3
GUILD_KIOSK_GUILD_INFO_RESULT_SUCCESS = 0
