--- @meta GuildHistoryMilestoneEvent

--- @alias GuildHistoryMilestoneEvent integer
--- | `GUILD_HISTORY_MILESTONE_EVENT_BANK_LOCKED` # 3
--- | `GUILD_HISTORY_MILESTONE_EVENT_BANK_UNLOCKED` # 2
--- | `GUILD_HISTORY_MILESTONE_EVENT_KIOSK_LOCKED` # 7
--- | `GUILD_HISTORY_MILESTONE_EVENT_KIOSK_UNLOCKED` # 6
--- | `GUILD_HISTORY_MILESTONE_EVENT_STORE_LOCKED` # 1
--- | `GUILD_HISTORY_MILESTONE_EVENT_STORE_UNLOCKED` # 0
--- | `GUILD_HISTORY_MILESTONE_EVENT_TABARD_LOCKED` # 5
--- | `GUILD_HISTORY_MILESTONE_EVENT_TABARD_UNLOCKED` # 4

GUILD_HISTORY_MILESTONE_EVENT_BANK_LOCKED = 3
GUILD_HISTORY_MILESTONE_EVENT_BANK_UNLOCKED = 2
GUILD_HISTORY_MILESTONE_EVENT_KIOSK_LOCKED = 7
GUILD_HISTORY_MILESTONE_EVENT_KIOSK_UNLOCKED = 6
GUILD_HISTORY_MILESTONE_EVENT_STORE_LOCKED = 1
GUILD_HISTORY_MILESTONE_EVENT_STORE_UNLOCKED = 0
GUILD_HISTORY_MILESTONE_EVENT_TABARD_LOCKED = 5
GUILD_HISTORY_MILESTONE_EVENT_TABARD_UNLOCKED = 4
