--- @meta GuildActivityAttributeValue

--- @alias GuildActivityAttributeValue integer
--- | `GUILD_ACTIVITY_ATTRIBUTE_VALUE_ANTIQUITIES` # 11
--- | `GUILD_ACTIVITY_ATTRIBUTE_VALUE_CRAFTING` # 8
--- | `GUILD_ACTIVITY_ATTRIBUTE_VALUE_DUNGEONS` # 3
--- | `GUILD_ACTIVITY_ATTRIBUTE_VALUE_FISHING` # 9
--- | `GUILD_ACTIVITY_ATTRIBUTE_VALUE_HOUSING` # 5
--- | `GUILD_ACTIVITY_ATTRIBUTE_VALUE_JUSTICE` # 10
--- | `GUILD_ACTIVITY_ATTRIBUTE_VALUE_PVP` # 2
--- | `GUILD_ACTIVITY_ATTRIBUTE_VALUE_QUESTING` # 6
--- | `GUILD_ACTIVITY_ATTRIBUTE_VALUE_ROLEPLAYING` # 7
--- | `GUILD_ACTIVITY_ATTRIBUTE_VALUE_TRADING` # 1
--- | `GUILD_ACTIVITY_ATTRIBUTE_VALUE_TRIALS` # 4

GUILD_ACTIVITY_ATTRIBUTE_VALUE_ANTIQUITIES = 11
GUILD_ACTIVITY_ATTRIBUTE_VALUE_CRAFTING = 8
GUILD_ACTIVITY_ATTRIBUTE_VALUE_DUNGEONS = 3
GUILD_ACTIVITY_ATTRIBUTE_VALUE_FISHING = 9
GUILD_ACTIVITY_ATTRIBUTE_VALUE_HOUSING = 5
GUILD_ACTIVITY_ATTRIBUTE_VALUE_JUSTICE = 10
GUILD_ACTIVITY_ATTRIBUTE_VALUE_PVP = 2
GUILD_ACTIVITY_ATTRIBUTE_VALUE_QUESTING = 6
GUILD_ACTIVITY_ATTRIBUTE_VALUE_ROLEPLAYING = 7
GUILD_ACTIVITY_ATTRIBUTE_VALUE_TRADING = 1
GUILD_ACTIVITY_ATTRIBUTE_VALUE_TRIALS = 4
