--- @meta GuildHistoryBankedCurrencyEvent

--- @alias GuildHistoryBankedCurrencyEvent integer
--- | `GUILD_HISTORY_BANKED_CURRENCY_EVENT_DEPOSITED` # 0
--- | `GUILD_HISTORY_BANKED_CURRENCY_EVENT_HERALDRY_EDITED` # 7
--- | `GUILD_HISTORY_BANKED_CURRENCY_EVENT_KIOSK_BID` # 2
--- | `GUILD_HISTORY_BANKED_CURRENCY_EVENT_KIOSK_BID_REFUND` # 3
--- | `GUILD_HISTORY_BANKED_CURRENCY_EVENT_KIOSK_PURCHASED` # 4
--- | `GUILD_HISTORY_BANKED_CURRENCY_EVENT_WITHDRAWN` # 1

GUILD_HISTORY_BANKED_CURRENCY_EVENT_DEPOSITED = 0
GUILD_HISTORY_BANKED_CURRENCY_EVENT_HERALDRY_EDITED = 7
GUILD_HISTORY_BANKED_CURRENCY_EVENT_KIOSK_BID = 2
GUILD_HISTORY_BANKED_CURRENCY_EVENT_KIOSK_BID_REFUND = 3
GUILD_HISTORY_BANKED_CURRENCY_EVENT_KIOSK_PURCHASED = 4
GUILD_HISTORY_BANKED_CURRENCY_EVENT_WITHDRAWN = 1
