--- @meta GuildRanks

--- @alias GuildRanks integer
--- | `DEFAULT_GUILD_LEADER_RANK` # 255
--- | `DEFAULT_INVITED_RANK` # 0
--- | `DEFAULT_MEMBER_RANK` # 2
--- | `DEFAULT_OFFICER_RANK` # 254
--- | `DEFAULT_RECRUIT_RANK` # 1

DEFAULT_GUILD_LEADER_RANK = 255
DEFAULT_INVITED_RANK = 0
DEFAULT_MEMBER_RANK = 2
DEFAULT_OFFICER_RANK = 254
DEFAULT_RECRUIT_RANK = 1
