--- @meta GuildHistoryEventCategory

--- @alias GuildHistoryEventCategory integer
--- | `GUILD_HISTORY_EVENT_CATEGORY_ACTIVITY` # 5
--- | `GUILD_HISTORY_EVENT_CATEGORY_AVA_ACTIVITY` # 6
--- | `GUILD_HISTORY_EVENT_CATEGORY_BANKED_CURRENCY` # 2
--- | `GUILD_HISTORY_EVENT_CATEGORY_BANKED_ITEM` # 1
--- | `GUILD_HISTORY_EVENT_CATEGORY_MILESTONE` # 4
--- | `GUILD_HISTORY_EVENT_CATEGORY_ROSTER` # 0
--- | `GUILD_HISTORY_EVENT_CATEGORY_TRADER` # 3

GUILD_HISTORY_EVENT_CATEGORY_ACTIVITY = 5
GUILD_HISTORY_EVENT_CATEGORY_AVA_ACTIVITY = 6
GUILD_HISTORY_EVENT_CATEGORY_BANKED_CURRENCY = 2
GUILD_HISTORY_EVENT_CATEGORY_BANKED_ITEM = 1
GUILD_HISTORY_EVENT_CATEGORY_MILESTONE = 4
GUILD_HISTORY_EVENT_CATEGORY_ROSTER = 0
GUILD_HISTORY_EVENT_CATEGORY_TRADER = 3
