--- @meta GuildBlacklistResponse

--- @alias GuildBlacklistResponse integer
--- | `GUILD_BLACKLIST_RESPONSE_ALREADY_BLACKLISTED` # 6
--- | `GUILD_BLACKLIST_RESPONSE_BLACKLIST_ENTRY_NOT_FOUND` # 7
--- | `GUILD_BLACKLIST_RESPONSE_BLACKLIST_ERROR` # 1
--- | `GUILD_BLACKLIST_RESPONSE_BLACKLIST_FULL` # 10
--- | `GUILD_BLACKLIST_RESPONSE_BLACKLIST_MESSAGE_TOO_LONG` # 14
--- | `GUILD_BLACKLIST_RESPONSE_BLACKLIST_SUCCESSFULLY_ADDED` # 0
--- | `GUILD_BLACKLIST_RESPONSE_BLACKLIST_SUCCESSFULLY_EDITTED` # 13
--- | `GUILD_BLACKLIST_RESPONSE_BLACKLIST_SUCCESSFULLY_REMOVED` # 12
--- | `GUILD_BLACKLIST_RESPONSE_CANNOT_BLACKLIST_GUILD_LEADER` # 3
--- | `GUILD_BLACKLIST_RESPONSE_CANNOT_BLACKLIST_SELF` # 4
--- | `GUILD_BLACKLIST_RESPONSE_DISPLAY_NAME_EMPTY` # 9
--- | `GUILD_BLACKLIST_RESPONSE_MEMBER_RANK_CHECK_FAILED` # 11
--- | `GUILD_BLACKLIST_RESPONSE_NOT_DECORATED_DISPLAY_NAME` # 8
--- | `GUILD_BLACKLIST_RESPONSE_NO_BLACKLIST_PERMISSION` # 2
--- | `GUILD_BLACKLIST_RESPONSE_PLAYER_NOT_FOUND` # 5

GUILD_BLACKLIST_RESPONSE_ALREADY_BLACKLISTED = 6
GUILD_BLACKLIST_RESPONSE_BLACKLIST_ENTRY_NOT_FOUND = 7
GUILD_BLACKLIST_RESPONSE_BLACKLIST_ERROR = 1
GUILD_BLACKLIST_RESPONSE_BLACKLIST_FULL = 10
GUILD_BLACKLIST_RESPONSE_BLACKLIST_MESSAGE_TOO_LONG = 14
GUILD_BLACKLIST_RESPONSE_BLACKLIST_SUCCESSFULLY_ADDED = 0
GUILD_BLACKLIST_RESPONSE_BLACKLIST_SUCCESSFULLY_EDITTED = 13
GUILD_BLACKLIST_RESPONSE_BLACKLIST_SUCCESSFULLY_REMOVED = 12
GUILD_BLACKLIST_RESPONSE_CANNOT_BLACKLIST_GUILD_LEADER = 3
GUILD_BLACKLIST_RESPONSE_CANNOT_BLACKLIST_SELF = 4
GUILD_BLACKLIST_RESPONSE_DISPLAY_NAME_EMPTY = 9
GUILD_BLACKLIST_RESPONSE_MEMBER_RANK_CHECK_FAILED = 11
GUILD_BLACKLIST_RESPONSE_NOT_DECORATED_DISPLAY_NAME = 8
GUILD_BLACKLIST_RESPONSE_NO_BLACKLIST_PERMISSION = 2
GUILD_BLACKLIST_RESPONSE_PLAYER_NOT_FOUND = 5
