--- @meta GuildListApplicationsReason

--- @alias GuildListApplicationsReason integer
--- | `GUILD_LIST_APPLICATIONS_REASON_APPLICATION_APPROVED` # 4
--- | `GUILD_LIST_APPLICATIONS_REASON_APPLICATION_DECLINED` # 3
--- | `GUILD_LIST_APPLICATIONS_REASON_APPLICATION_RESCINDED` # 2
--- | `GUILD_LIST_APPLICATIONS_REASON_INITIALIZE_LIST` # 0
--- | `GUILD_LIST_APPLICATIONS_REASON_NEW_APPLICATION_PENDING` # 1

GUILD_LIST_APPLICATIONS_REASON_APPLICATION_APPROVED = 4
GUILD_LIST_APPLICATIONS_REASON_APPLICATION_DECLINED = 3
GUILD_LIST_APPLICATIONS_REASON_APPLICATION_RESCINDED = 2
GUILD_LIST_APPLICATIONS_REASON_INITIALIZE_LIST = 0
GUILD_LIST_APPLICATIONS_REASON_NEW_APPLICATION_PENDING = 1
