--- @meta GuildPlayerSetRankResponse

--- @alias GuildPlayerSetRankResponse integer
--- | `GUILD_PLAYER_SET_RANK_RESPONSE_FAILED` # 1
--- | `GUILD_PLAYER_SET_RANK_RESPONSE_SUCCEEDED` # 0

GUILD_PLAYER_SET_RANK_RESPONSE_FAILED = 1
GUILD_PLAYER_SET_RANK_RESPONSE_SUCCEEDED = 0
