--- @meta GuildLanguageAttributeValue

--- @alias GuildLanguageAttributeValue integer
--- | `GUILD_LANGUAGE_ATTRIBUTE_VALUE_CHINESE_S` # 7
--- | `GUILD_LANGUAGE_ATTRIBUTE_VALUE_ENGLISH` # 1
--- | `GUILD_LANGUAGE_ATTRIBUTE_VALUE_FRENCH` # 2
--- | `GUILD_LANGUAGE_ATTRIBUTE_VALUE_GERMAN` # 3
--- | `GUILD_LANGUAGE_ATTRIBUTE_VALUE_JAPANESE` # 4
--- | `GUILD_LANGUAGE_ATTRIBUTE_VALUE_NONE` # 0
--- | `GUILD_LANGUAGE_ATTRIBUTE_VALUE_OTHER` # 32
--- | `GUILD_LANGUAGE_ATTRIBUTE_VALUE_RUSSIAN` # 5
--- | `GUILD_LANGUAGE_ATTRIBUTE_VALUE_SPANISH` # 6

GUILD_LANGUAGE_ATTRIBUTE_VALUE_CHINESE_S = 7
GUILD_LANGUAGE_ATTRIBUTE_VALUE_ENGLISH = 1
GUILD_LANGUAGE_ATTRIBUTE_VALUE_FRENCH = 2
GUILD_LANGUAGE_ATTRIBUTE_VALUE_GERMAN = 3
GUILD_LANGUAGE_ATTRIBUTE_VALUE_JAPANESE = 4
GUILD_LANGUAGE_ATTRIBUTE_VALUE_NONE = 0
GUILD_LANGUAGE_ATTRIBUTE_VALUE_OTHER = 32
GUILD_LANGUAGE_ATTRIBUTE_VALUE_RUSSIAN = 5
GUILD_LANGUAGE_ATTRIBUTE_VALUE_SPANISH = 6
