--- @meta GuildPersonalityAttributeValue

--- @alias GuildPersonalityAttributeValue integer
--- | `GUILD_PERSONALITY_ATTRIBUTE_VALUE_BALANCED` # 2
--- | `GUILD_PERSONALITY_ATTRIBUTE_VALUE_CASUAL` # 1
--- | `GUILD_PERSONALITY_ATTRIBUTE_VALUE_HARDCORE` # 3
--- | `GUILD_PERSONALITY_ATTRIBUTE_VALUE_NONE` # 0

GUILD_PERSONALITY_ATTRIBUTE_VALUE_BALANCED = 2
GUILD_PERSONALITY_ATTRIBUTE_VALUE_CASUAL = 1
GUILD_PERSONALITY_ATTRIBUTE_VALUE_HARDCORE = 3
GUILD_PERSONALITY_ATTRIBUTE_VALUE_NONE = 0
