--- @meta GuildPermission

--- @alias GuildPermission integer
--- | `GUILD_PERMISSION_BANK_DEPOSIT` # 15
--- | `GUILD_PERMISSION_BANK_VIEW_DEPOSIT_HISTORY` # 26
--- | `GUILD_PERMISSION_BANK_VIEW_GOLD` # 24
--- | `GUILD_PERMISSION_BANK_VIEW_WITHDRAW_HISTORY` # 25
--- | `GUILD_PERMISSION_BANK_WITHDRAW` # 16
--- | `GUILD_PERMISSION_BANK_WITHDRAW_GOLD` # 23
--- | `GUILD_PERMISSION_CHAT` # 1
--- | `GUILD_PERMISSION_CLAIM_AVA_RESOURCE` # 9
--- | `GUILD_PERMISSION_DEMOTE` # 5
--- | `GUILD_PERMISSION_DESCRIPTION_EDIT` # 13
--- | `GUILD_PERMISSION_EDIT_HERALDRY` # 22
--- | `GUILD_PERMISSION_GUILD_KIOSK_BID` # 21
--- | `GUILD_PERMISSION_INVITE` # 2
--- | `GUILD_PERMISSION_MANAGE_APPLICATIONS` # 27
--- | `GUILD_PERMISSION_MANAGE_BLACKLIST` # 28
--- | `GUILD_PERMISSION_NONE` # 0
--- | `GUILD_PERMISSION_NOTE_EDIT` # 8
--- | `GUILD_PERMISSION_NOTE_READ` # 7
--- | `GUILD_PERMISSION_OFFICER_CHAT_READ` # 11
--- | `GUILD_PERMISSION_OFFICER_CHAT_WRITE` # 12
--- | `GUILD_PERMISSION_PERMISSION_EDIT` # 19
--- | `GUILD_PERMISSION_PROMOTE` # 4
--- | `GUILD_PERMISSION_RECRUITMENT_EDIT` # 14
--- | `GUILD_PERMISSION_RELEASE_AVA_RESOURCE` # 10
--- | `GUILD_PERMISSION_REMOVE` # 3
--- | `GUILD_PERMISSION_REUSE_ME1` # 20
--- | `GUILD_PERMISSION_SET_MOTD` # 6
--- | `GUILD_PERMISSION_STORE_BUY` # 17
--- | `GUILD_PERMISSION_STORE_SELL` # 18

GUILD_PERMISSION_BANK_DEPOSIT = 15
GUILD_PERMISSION_BANK_VIEW_DEPOSIT_HISTORY = 26
GUILD_PERMISSION_BANK_VIEW_GOLD = 24
GUILD_PERMISSION_BANK_VIEW_WITHDRAW_HISTORY = 25
GUILD_PERMISSION_BANK_WITHDRAW = 16
GUILD_PERMISSION_BANK_WITHDRAW_GOLD = 23
GUILD_PERMISSION_CHAT = 1
GUILD_PERMISSION_CLAIM_AVA_RESOURCE = 9
GUILD_PERMISSION_DEMOTE = 5
GUILD_PERMISSION_DESCRIPTION_EDIT = 13
GUILD_PERMISSION_EDIT_HERALDRY = 22
GUILD_PERMISSION_GUILD_KIOSK_BID = 21
GUILD_PERMISSION_INVITE = 2
GUILD_PERMISSION_MANAGE_APPLICATIONS = 27
GUILD_PERMISSION_MANAGE_BLACKLIST = 28
GUILD_PERMISSION_NONE = 0
GUILD_PERMISSION_NOTE_EDIT = 8
GUILD_PERMISSION_NOTE_READ = 7
GUILD_PERMISSION_OFFICER_CHAT_READ = 11
GUILD_PERMISSION_OFFICER_CHAT_WRITE = 12
GUILD_PERMISSION_PERMISSION_EDIT = 19
GUILD_PERMISSION_PROMOTE = 4
GUILD_PERMISSION_RECRUITMENT_EDIT = 14
GUILD_PERMISSION_RELEASE_AVA_RESOURCE = 10
GUILD_PERMISSION_REMOVE = 3
GUILD_PERMISSION_REUSE_ME1 = 20
GUILD_PERMISSION_SET_MOTD = 6
GUILD_PERMISSION_STORE_BUY = 17
GUILD_PERMISSION_STORE_SELL = 18
