--- @meta GuildHistoryRequestFlags

--- @alias GuildHistoryRequestFlags integer
--- | `GUILD_HISTORY_REQUEST_FLAG_CHUNKS_DIRTY` # 4
--- | `GUILD_HISTORY_REQUEST_FLAG_COMPLETE` # 2
--- | `GUILD_HISTORY_REQUEST_FLAG_CREATED_FROM_ADDON` # 1
--- | `GUILD_HISTORY_REQUEST_FLAG_QUEUED` # 32
--- | `GUILD_HISTORY_REQUEST_FLAG_QUEUED_FROM_ADDON` # 64
--- | `GUILD_HISTORY_REQUEST_FLAG_RESPONSE_PENDING` # 8
--- | `GUILD_HISTORY_REQUEST_FLAG_RESPONSE_PENDING_FROM_ADDON` # 16

GUILD_HISTORY_REQUEST_FLAG_CHUNKS_DIRTY = 4
GUILD_HISTORY_REQUEST_FLAG_COMPLETE = 2
GUILD_HISTORY_REQUEST_FLAG_CREATED_FROM_ADDON = 1
GUILD_HISTORY_REQUEST_FLAG_QUEUED = 32
GUILD_HISTORY_REQUEST_FLAG_QUEUED_FROM_ADDON = 64
GUILD_HISTORY_REQUEST_FLAG_RESPONSE_PENDING = 8
GUILD_HISTORY_REQUEST_FLAG_RESPONSE_PENDING_FROM_ADDON = 16
