--- @meta GuildProcessApplicationResponse

--- @alias GuildProcessApplicationResponse integer
--- | `GUILD_PROCESS_APP_RESPONSE_APPLICANT_IN_MAX_GUILDS` # 5
--- | `GUILD_PROCESS_APP_RESPONSE_APPLICATION_ACTION_PROCESSING` # 9
--- | `GUILD_PROCESS_APP_RESPONSE_APPLICATION_DECLINE_MESSAGE_TOO_LONG` # 6
--- | `GUILD_PROCESS_APP_RESPONSE_APPLICATION_PROCESSED_ACCEPT` # 0
--- | `GUILD_PROCESS_APP_RESPONSE_APPLICATION_PROCESSED_DECLINE` # 1
--- | `GUILD_PROCESS_APP_RESPONSE_APPLICATION_PROCESSED_RESCIND` # 2
--- | `GUILD_PROCESS_APP_RESPONSE_APPLICATION_UNPROCESSED` # 8
--- | `GUILD_PROCESS_APP_RESPONSE_GUILD_FULL` # 4
--- | `GUILD_PROCESS_APP_RESPONSE_NO_APPLICATION_PERMISSION` # 7
--- | `GUILD_PROCESS_APP_RESPONSE_PROCESS_APPLICATION_ERROR` # 3

GUILD_PROCESS_APP_RESPONSE_APPLICANT_IN_MAX_GUILDS = 5
GUILD_PROCESS_APP_RESPONSE_APPLICATION_ACTION_PROCESSING = 9
GUILD_PROCESS_APP_RESPONSE_APPLICATION_DECLINE_MESSAGE_TOO_LONG = 6
GUILD_PROCESS_APP_RESPONSE_APPLICATION_PROCESSED_ACCEPT = 0
GUILD_PROCESS_APP_RESPONSE_APPLICATION_PROCESSED_DECLINE = 1
GUILD_PROCESS_APP_RESPONSE_APPLICATION_PROCESSED_RESCIND = 2
GUILD_PROCESS_APP_RESPONSE_APPLICATION_UNPROCESSED = 8
GUILD_PROCESS_APP_RESPONSE_GUILD_FULL = 4
GUILD_PROCESS_APP_RESPONSE_NO_APPLICATION_PERMISSION = 7
GUILD_PROCESS_APP_RESPONSE_PROCESS_APPLICATION_ERROR = 3
