--- @meta GuildKioskResult

--- @alias GuildKioskResult integer
--- | `GUILD_KIOSK_BID_INSUFFICIENT` # 6
--- | `GUILD_KIOSK_BID_SUCCESSFUL` # 2
--- | `GUILD_KIOSK_BID_WINDOW_CLOSED` # 9
--- | `GUILD_KIOSK_GUILD_OWNS_OTHER_KIOSK` # 14
--- | `GUILD_KIOSK_GUILD_TOO_SMALL` # 13
--- | `GUILD_KIOSK_INFO_REQUEST_SUCCESSFUL` # 1
--- | `GUILD_KIOSK_KIOSK_OWNED` # 11
--- | `GUILD_KIOSK_NOT_A_MEMBER` # 3
--- | `GUILD_KIOSK_NOT_ENOUGH_GOLD_IN_BANK` # 4
--- | `GUILD_KIOSK_NOT_IN_A_GUILD` # 8
--- | `GUILD_KIOSK_NO_BID_PERMISSION` # 7
--- | `GUILD_KIOSK_PURCHASE_SUCCESSFUL` # 12
--- | `GUILD_KIOSK_TOO_MANY_BIDS` # 5
--- | `GUILD_KIOSK_UNAVAILABLE` # 10

GUILD_KIOSK_BID_INSUFFICIENT = 6
GUILD_KIOSK_BID_SUCCESSFUL = 2
GUILD_KIOSK_BID_WINDOW_CLOSED = 9
GUILD_KIOSK_GUILD_OWNS_OTHER_KIOSK = 14
GUILD_KIOSK_GUILD_TOO_SMALL = 13
GUILD_KIOSK_INFO_REQUEST_SUCCESSFUL = 1
GUILD_KIOSK_KIOSK_OWNED = 11
GUILD_KIOSK_NOT_A_MEMBER = 3
GUILD_KIOSK_NOT_ENOUGH_GOLD_IN_BANK = 4
GUILD_KIOSK_NOT_IN_A_GUILD = 8
GUILD_KIOSK_NO_BID_PERMISSION = 7
GUILD_KIOSK_PURCHASE_SUCCESSFUL = 12
GUILD_KIOSK_TOO_MANY_BIDS = 5
GUILD_KIOSK_UNAVAILABLE = 10
