--- @meta GuildHistoryCategoryUpdateFlags

--- @alias GuildHistoryCategoryUpdateFlags integer
--- | `GUILD_HISTORY_CATEGORY_UPDATE_FLAG_NEW_INFO` # 2
--- | `GUILD_HISTORY_CATEGORY_UPDATE_FLAG_REFRESHED` # 4
--- | `GUILD_HISTORY_CATEGORY_UPDATE_FLAG_RESPONSE_RECEIVED` # 1

GUILD_HISTORY_CATEGORY_UPDATE_FLAG_NEW_INFO = 2
GUILD_HISTORY_CATEGORY_UPDATE_FLAG_REFRESHED = 4
GUILD_HISTORY_CATEGORY_UPDATE_FLAG_RESPONSE_RECEIVED = 1
