--- @meta GuildHistoryAvAActivityEvent

--- @alias GuildHistoryAvAActivityEvent integer
--- | `GUILD_HISTORY_AVA_ACTIVITY_EVENT_KEEP_CLAIMED` # 0
--- | `GUILD_HISTORY_AVA_ACTIVITY_EVENT_KEEP_LOST` # 1
--- | `GUILD_HISTORY_AVA_ACTIVITY_EVENT_KEEP_RELEASED` # 2

GUILD_HISTORY_AVA_ACTIVITY_EVENT_KEEP_CLAIMED = 0
GUILD_HISTORY_AVA_ACTIVITY_EVENT_KEEP_LOST = 1
GUILD_HISTORY_AVA_ACTIVITY_EVENT_KEEP_RELEASED = 2
