--- @meta GuildPrivilege

--- @alias GuildPrivilege integer
--- | `GUILD_PRIVILEGE_BANK_DEPOSIT` # 1
--- | `GUILD_PRIVILEGE_HERALDRY` # 3
--- | `GUILD_PRIVILEGE_TRADING_HOUSE` # 2

GUILD_PRIVILEGE_BANK_DEPOSIT = 1
GUILD_PRIVILEGE_HERALDRY = 3
GUILD_PRIVILEGE_TRADING_HOUSE = 2
