--- @meta GuildHistoryRosterEvent

--- @alias GuildHistoryRosterEvent integer
--- | `GUILD_HISTORY_ROSTER_EVENT_ADDED_TO_BLACKLIST` # 7
--- | `GUILD_HISTORY_ROSTER_EVENT_APPLICATION_ACCEPTED` # 10
--- | `GUILD_HISTORY_ROSTER_EVENT_APPLICATION_DECLINED` # 11
--- | `GUILD_HISTORY_ROSTER_EVENT_DEMOTE` # 4
--- | `GUILD_HISTORY_ROSTER_EVENT_EDIT_BLACKLIST_NOTE` # 9
--- | `GUILD_HISTORY_ROSTER_EVENT_INVITE` # 0
--- | `GUILD_HISTORY_ROSTER_EVENT_JOIN` # 2
--- | `GUILD_HISTORY_ROSTER_EVENT_KICKED` # 6
--- | `GUILD_HISTORY_ROSTER_EVENT_LEAVE` # 5
--- | `GUILD_HISTORY_ROSTER_EVENT_PROMOTE` # 3
--- | `GUILD_HISTORY_ROSTER_EVENT_REMOVED_FROM_BLACKLIST` # 8

GUILD_HISTORY_ROSTER_EVENT_ADDED_TO_BLACKLIST = 7
GUILD_HISTORY_ROSTER_EVENT_APPLICATION_ACCEPTED = 10
GUILD_HISTORY_ROSTER_EVENT_APPLICATION_DECLINED = 11
GUILD_HISTORY_ROSTER_EVENT_DEMOTE = 4
GUILD_HISTORY_ROSTER_EVENT_EDIT_BLACKLIST_NOTE = 9
GUILD_HISTORY_ROSTER_EVENT_INVITE = 0
GUILD_HISTORY_ROSTER_EVENT_JOIN = 2
GUILD_HISTORY_ROSTER_EVENT_KICKED = 6
GUILD_HISTORY_ROSTER_EVENT_LEAVE = 5
GUILD_HISTORY_ROSTER_EVENT_PROMOTE = 3
GUILD_HISTORY_ROSTER_EVENT_REMOVED_FROM_BLACKLIST = 8
