--- @meta GuildApplicationStatus

--- @alias GuildApplicationStatus integer
--- | `GUILD_APPLICATION_STATUS_ACCEPTED` # 2
--- | `GUILD_APPLICATION_STATUS_DECLINED` # 3
--- | `GUILD_APPLICATION_STATUS_EXPIRED` # 5
--- | `GUILD_APPLICATION_STATUS_NONE` # 0
--- | `GUILD_APPLICATION_STATUS_PENDING` # 1
--- | `GUILD_APPLICATION_STATUS_RESCINDED` # 4

GUILD_APPLICATION_STATUS_ACCEPTED = 2
GUILD_APPLICATION_STATUS_DECLINED = 3
GUILD_APPLICATION_STATUS_EXPIRED = 5
GUILD_APPLICATION_STATUS_NONE = 0
GUILD_APPLICATION_STATUS_PENDING = 1
GUILD_APPLICATION_STATUS_RESCINDED = 4
