--- @meta GuildFocusAttributeValue

--- @alias GuildFocusAttributeValue integer
--- | `GUILD_FOCUS_ATTRIBUTE_VALUE_CRAFTING` # 7
--- | `GUILD_FOCUS_ATTRIBUTE_VALUE_GROUP_PVE` # 2
--- | `GUILD_FOCUS_ATTRIBUTE_VALUE_NONE` # 0
--- | `GUILD_FOCUS_ATTRIBUTE_VALUE_PVP` # 5
--- | `GUILD_FOCUS_ATTRIBUTE_VALUE_QUESTING` # 6
--- | `GUILD_FOCUS_ATTRIBUTE_VALUE_ROLEPLAYING` # 3
--- | `GUILD_FOCUS_ATTRIBUTE_VALUE_SOCIAL` # 4
--- | `GUILD_FOCUS_ATTRIBUTE_VALUE_TRADING` # 1

GUILD_FOCUS_ATTRIBUTE_VALUE_CRAFTING = 7
GUILD_FOCUS_ATTRIBUTE_VALUE_GROUP_PVE = 2
GUILD_FOCUS_ATTRIBUTE_VALUE_NONE = 0
GUILD_FOCUS_ATTRIBUTE_VALUE_PVP = 5
GUILD_FOCUS_ATTRIBUTE_VALUE_QUESTING = 6
GUILD_FOCUS_ATTRIBUTE_VALUE_ROLEPLAYING = 3
GUILD_FOCUS_ATTRIBUTE_VALUE_SOCIAL = 4
GUILD_FOCUS_ATTRIBUTE_VALUE_TRADING = 1
