--- @meta GuildMetaDataAttribute

--- @alias GuildMetaDataAttribute integer
--- | `GUILD_META_DATA_ATTRIBUTE_ACTIVITIES` # 4
--- | `GUILD_META_DATA_ATTRIBUTE_ALLIANCE` # 6
--- | `GUILD_META_DATA_ATTRIBUTE_END_TIME` # 16
--- | `GUILD_META_DATA_ATTRIBUTE_FOUNDED_DATE` # 10
--- | `GUILD_META_DATA_ATTRIBUTE_HEADER_MESSAGE` # 17
--- | `GUILD_META_DATA_ATTRIBUTE_HERALDRY` # 9
--- | `GUILD_META_DATA_ATTRIBUTE_KIOSK` # 8
--- | `GUILD_META_DATA_ATTRIBUTE_LANGUAGES` # 3
--- | `GUILD_META_DATA_ATTRIBUTE_MINIMUM_CP` # 13
--- | `GUILD_META_DATA_ATTRIBUTE_NAME` # 1
--- | `GUILD_META_DATA_ATTRIBUTE_PERSONALITIES` # 5
--- | `GUILD_META_DATA_ATTRIBUTE_PRIMARY_FOCUS` # 11
--- | `GUILD_META_DATA_ATTRIBUTE_RECRUITMENT_MESSAGE` # 2
--- | `GUILD_META_DATA_ATTRIBUTE_RECRUITMENT_STATUS` # 18
--- | `GUILD_META_DATA_ATTRIBUTE_ROLES` # 14
--- | `GUILD_META_DATA_ATTRIBUTE_SECONDARY_FOCUS` # 12
--- | `GUILD_META_DATA_ATTRIBUTE_SIZE` # 7
--- | `GUILD_META_DATA_ATTRIBUTE_START_TIME` # 15

GUILD_META_DATA_ATTRIBUTE_ACTIVITIES = 4
GUILD_META_DATA_ATTRIBUTE_ALLIANCE = 6
GUILD_META_DATA_ATTRIBUTE_END_TIME = 16
GUILD_META_DATA_ATTRIBUTE_FOUNDED_DATE = 10
GUILD_META_DATA_ATTRIBUTE_HEADER_MESSAGE = 17
GUILD_META_DATA_ATTRIBUTE_HERALDRY = 9
GUILD_META_DATA_ATTRIBUTE_KIOSK = 8
GUILD_META_DATA_ATTRIBUTE_LANGUAGES = 3
GUILD_META_DATA_ATTRIBUTE_MINIMUM_CP = 13
GUILD_META_DATA_ATTRIBUTE_NAME = 1
GUILD_META_DATA_ATTRIBUTE_PERSONALITIES = 5
GUILD_META_DATA_ATTRIBUTE_PRIMARY_FOCUS = 11
GUILD_META_DATA_ATTRIBUTE_RECRUITMENT_MESSAGE = 2
GUILD_META_DATA_ATTRIBUTE_RECRUITMENT_STATUS = 18
GUILD_META_DATA_ATTRIBUTE_ROLES = 14
GUILD_META_DATA_ATTRIBUTE_SECONDARY_FOCUS = 12
GUILD_META_DATA_ATTRIBUTE_SIZE = 7
GUILD_META_DATA_ATTRIBUTE_START_TIME = 15
