--- @meta GuildHistoryEventSubcategory

--- @alias GuildHistoryEventSubcategory integer
--- | `GUILD_HISTORY_EVENT_SUBCATEGORY_ALL` # 0
--- | `GUILD_HISTORY_EVENT_SUBCATEGORY_DEPOSITS` # 1
--- | `GUILD_HISTORY_EVENT_SUBCATEGORY_HIRED_TRADER` # 3
--- | `GUILD_HISTORY_EVENT_SUBCATEGORY_OWNERSHIP` # 5
--- | `GUILD_HISTORY_EVENT_SUBCATEGORY_PURCHASES` # 4
--- | `GUILD_HISTORY_EVENT_SUBCATEGORY_WITHDRAWALS` # 2

GUILD_HISTORY_EVENT_SUBCATEGORY_ALL = 0
GUILD_HISTORY_EVENT_SUBCATEGORY_DEPOSITS = 1
GUILD_HISTORY_EVENT_SUBCATEGORY_HIRED_TRADER = 3
GUILD_HISTORY_EVENT_SUBCATEGORY_OWNERSHIP = 5
GUILD_HISTORY_EVENT_SUBCATEGORY_PURCHASES = 4
GUILD_HISTORY_EVENT_SUBCATEGORY_WITHDRAWALS = 2
