--- @meta GuildSizeAttributeValue

--- @alias GuildSizeAttributeValue integer
--- | `GUILD_SIZE_ATTRIBUTE_VALUE_GIGANTIC` # 4
--- | `GUILD_SIZE_ATTRIBUTE_VALUE_LARGE` # 3
--- | `GUILD_SIZE_ATTRIBUTE_VALUE_MEDIUM` # 2
--- | `GUILD_SIZE_ATTRIBUTE_VALUE_SMALL` # 1

GUILD_SIZE_ATTRIBUTE_VALUE_GIGANTIC = 4
GUILD_SIZE_ATTRIBUTE_VALUE_LARGE = 3
GUILD_SIZE_ATTRIBUTE_VALUE_MEDIUM = 2
GUILD_SIZE_ATTRIBUTE_VALUE_SMALL = 1
