--- @meta GuildApplicationResponse

--- @alias GuildApplicationResponse integer
--- | `GUILD_APP_RESPONSE_ALREADY_MEMBER` # 2
--- | `GUILD_APP_RESPONSE_APPLICATION_ERROR` # 1
--- | `GUILD_APP_RESPONSE_APPLICATION_MESSAGE_TOO_LONG` # 8
--- | `GUILD_APP_RESPONSE_APPLICATION_SENT` # 0
--- | `GUILD_APP_RESPONSE_GUILD_DATA_OUT_OF_DATE` # 10
--- | `GUILD_APP_RESPONSE_GUILD_FULL` # 6
--- | `GUILD_APP_RESPONSE_GUILD_MAX_APPLICATIONS_PENDING` # 9
--- | `GUILD_APP_RESPONSE_IN_MAX_GUILDS` # 7
--- | `GUILD_APP_RESPONSE_MAX_APPLICATIONS_PENDING` # 5
--- | `GUILD_APP_RESPONSE_NOT_ACCEPTING_APPLICATIONS` # 3
--- | `GUILD_APP_RESPONSE_OUTSTANDING_APPLICATION` # 4

GUILD_APP_RESPONSE_ALREADY_MEMBER = 2
GUILD_APP_RESPONSE_APPLICATION_ERROR = 1
GUILD_APP_RESPONSE_APPLICATION_MESSAGE_TOO_LONG = 8
GUILD_APP_RESPONSE_APPLICATION_SENT = 0
GUILD_APP_RESPONSE_GUILD_DATA_OUT_OF_DATE = 10
GUILD_APP_RESPONSE_GUILD_FULL = 6
GUILD_APP_RESPONSE_GUILD_MAX_APPLICATIONS_PENDING = 9
GUILD_APP_RESPONSE_IN_MAX_GUILDS = 7
GUILD_APP_RESPONSE_MAX_APPLICATIONS_PENDING = 5
GUILD_APP_RESPONSE_NOT_ACCEPTING_APPLICATIONS = 3
GUILD_APP_RESPONSE_OUTSTANDING_APPLICATION = 4
