--- @meta GuildFinderSearchState

--- @alias GuildFinderSearchState integer
--- | `GUILD_FINDER_SEARCH_STATE_COMPLETE` # 3
--- | `GUILD_FINDER_SEARCH_STATE_NONE` # 0
--- | `GUILD_FINDER_SEARCH_STATE_QUEUED` # 1
--- | `GUILD_FINDER_SEARCH_STATE_WAITING` # 2

GUILD_FINDER_SEARCH_STATE_COMPLETE = 3
GUILD_FINDER_SEARCH_STATE_NONE = 0
GUILD_FINDER_SEARCH_STATE_QUEUED = 1
GUILD_FINDER_SEARCH_STATE_WAITING = 2
