--- @meta GuildHistoryDataReadyState

--- @alias GuildHistoryDataReadyState integer
--- | `GUILD_HISTORY_DATA_READY_STATE_INVALID_REQUEST` # 0
--- | `GUILD_HISTORY_DATA_READY_STATE_ON_COOLDOWN` # 1
--- | `GUILD_HISTORY_DATA_READY_STATE_READY` # 3
--- | `GUILD_HISTORY_DATA_READY_STATE_RESPONSE_PENDING` # 2

GUILD_HISTORY_DATA_READY_STATE_INVALID_REQUEST = 0
GUILD_HISTORY_DATA_READY_STATE_ON_COOLDOWN = 1
GUILD_HISTORY_DATA_READY_STATE_READY = 3
GUILD_HISTORY_DATA_READY_STATE_RESPONSE_PENDING = 2
