--- @meta GuildKeepNoticesSettingChoice

--- @alias GuildKeepNoticesSettingChoice integer
--- | `GUILD_KEEP_NOTICES_SETTING_CHOICE_ALERT` # 2
--- | `GUILD_KEEP_NOTICES_SETTING_CHOICE_CHAT` # 1
--- | `GUILD_KEEP_NOTICES_SETTING_CHOICE_DONT_SHOW` # 0

GUILD_KEEP_NOTICES_SETTING_CHOICE_ALERT = 2
GUILD_KEEP_NOTICES_SETTING_CHOICE_CHAT = 1
GUILD_KEEP_NOTICES_SETTING_CHOICE_DONT_SHOW = 0
