--- @meta GuildBankResult

--- @alias GuildBankResult integer
--- | `GUILD_BANK_BAD_ITEM` # 8
--- | `GUILD_BANK_CANT_BE_STORED` # 4
--- | `GUILD_BANK_GUILD_TOO_SMALL` # 11
--- | `GUILD_BANK_INVENTORY_FULL` # 20
--- | `GUILD_BANK_ITEM_NOT_FOUND` # 3
--- | `GUILD_BANK_NOT_A_MEMBER` # 2
--- | `GUILD_BANK_NOT_ENOUGH_BANK_SPACE_FOR_GOLD` # 16
--- | `GUILD_BANK_NOT_ENOUGH_GOLD` # 15
--- | `GUILD_BANK_NOT_ENOUGH_GOLD_IN_BANK` # 17
--- | `GUILD_BANK_NOT_IN_A_GUILD` # 9
--- | `GUILD_BANK_NOT_OPEN` # 7
--- | `GUILD_BANK_NO_DEPOSIT_PERMISSION` # 14
--- | `GUILD_BANK_NO_DEPOSIT_STOLEN_ITEM` # 18
--- | `GUILD_BANK_NO_SPACE_LEFT` # 5
--- | `GUILD_BANK_NO_WITHDRAW_PERMISSION` # 13
--- | `GUILD_BANK_PARTIAL_SUCCESS` # 12
--- | `GUILD_BANK_QUEUED_DEPOSIT` # 19
--- | `GUILD_BANK_SUCCESS` # 1
--- | `GUILD_BANK_TRANSFER_PENDING` # 10
--- | `GUILD_BANK_UNAVAILABLE` # 6

GUILD_BANK_BAD_ITEM = 8
GUILD_BANK_CANT_BE_STORED = 4
GUILD_BANK_GUILD_TOO_SMALL = 11
GUILD_BANK_INVENTORY_FULL = 20
GUILD_BANK_ITEM_NOT_FOUND = 3
GUILD_BANK_NOT_A_MEMBER = 2
GUILD_BANK_NOT_ENOUGH_BANK_SPACE_FOR_GOLD = 16
GUILD_BANK_NOT_ENOUGH_GOLD = 15
GUILD_BANK_NOT_ENOUGH_GOLD_IN_BANK = 17
GUILD_BANK_NOT_IN_A_GUILD = 9
GUILD_BANK_NOT_OPEN = 7
GUILD_BANK_NO_DEPOSIT_PERMISSION = 14
GUILD_BANK_NO_DEPOSIT_STOLEN_ITEM = 18
GUILD_BANK_NO_SPACE_LEFT = 5
GUILD_BANK_NO_WITHDRAW_PERMISSION = 13
GUILD_BANK_PARTIAL_SUCCESS = 12
GUILD_BANK_QUEUED_DEPOSIT = 19
GUILD_BANK_SUCCESS = 1
GUILD_BANK_TRANSFER_PENDING = 10
GUILD_BANK_UNAVAILABLE = 6
