--- @meta GuildHistoryBankedItemEvent

--- @alias GuildHistoryBankedItemEvent integer
--- | `GUILD_HISTORY_BANKED_ITEM_EVENT_ADDED` # 0
--- | `GUILD_HISTORY_BANKED_ITEM_EVENT_REMOVED` # 1

GUILD_HISTORY_BANKED_ITEM_EVENT_ADDED = 0
GUILD_HISTORY_BANKED_ITEM_EVENT_REMOVED = 1
