--- @meta GuildRecruitmentStatusAttributeValue

--- @alias GuildRecruitmentStatusAttributeValue integer
--- | `GUILD_RECRUITMENT_STATUS_ATTRIBUTE_VALUE_LISTED` # 1
--- | `GUILD_RECRUITMENT_STATUS_ATTRIBUTE_VALUE_NOT_LISTED` # 0

GUILD_RECRUITMENT_STATUS_ATTRIBUTE_VALUE_LISTED = 1
GUILD_RECRUITMENT_STATUS_ATTRIBUTE_VALUE_NOT_LISTED = 0
