--- @meta GuildHistoryActivityEvent

--- @alias GuildHistoryActivityEvent integer
--- | `GUILD_HISTORY_ACTIVITY_EVENT_ABOUT_US_EDITED` # 1
--- | `GUILD_HISTORY_ACTIVITY_EVENT_MOTD_EDITED` # 0
--- | `GUILD_HISTORY_ACTIVITY_EVENT_RECRUITMENT_LISTED` # 2
--- | `GUILD_HISTORY_ACTIVITY_EVENT_RECRUITMENT_UNLISTED` # 3

GUILD_HISTORY_ACTIVITY_EVENT_ABOUT_US_EDITED = 1
GUILD_HISTORY_ACTIVITY_EVENT_MOTD_EDITED = 0
GUILD_HISTORY_ACTIVITY_EVENT_RECRUITMENT_LISTED = 2
GUILD_HISTORY_ACTIVITY_EVENT_RECRUITMENT_UNLISTED = 3
