--- @meta HealthWarningStage

--- @alias HealthWarningStage integer
--- | `HEALTH_WARNING_FLASH_1` # 3
--- | `HEALTH_WARNING_FLASH_2` # 4
--- | `HEALTH_WARNING_NONE` # -1
--- | `HEALTH_WARNING_STAGE_1` # 0
--- | `HEALTH_WARNING_STAGE_2` # 1
--- | `HEALTH_WARNING_STAGE_3` # 2

HEALTH_WARNING_FLASH_1 = 3
HEALTH_WARNING_FLASH_2 = 4
HEALTH_WARNING_NONE = -1
HEALTH_WARNING_STAGE_1 = 0
HEALTH_WARNING_STAGE_2 = 1
HEALTH_WARNING_STAGE_3 = 2
