--- @meta HelpShowOptions

--- @alias HelpShowOptions integer
--- | `HELP_SHOW_OPTIONS_ALL` # 2
--- | `HELP_SHOW_OPTIONS_CONSOLE_AND_PC_GAMEPAD` # 1
--- | `HELP_SHOW_OPTIONS_CONSOLE_GAMEPAD` # 5
--- | `HELP_SHOW_OPTIONS_KEYBOARD` # 0
--- | `HELP_SHOW_OPTIONS_KEYBOARD_AND_CONSOLE_GAMEPAD` # 6
--- | `HELP_SHOW_OPTIONS_KEYBOARD_AND_PC_GAMEPAD` # 4
--- | `HELP_SHOW_OPTIONS_PC_GAMEPAD` # 3

HELP_SHOW_OPTIONS_ALL = 2
HELP_SHOW_OPTIONS_CONSOLE_AND_PC_GAMEPAD = 1
HELP_SHOW_OPTIONS_CONSOLE_GAMEPAD = 5
HELP_SHOW_OPTIONS_KEYBOARD = 0
HELP_SHOW_OPTIONS_KEYBOARD_AND_CONSOLE_GAMEPAD = 6
HELP_SHOW_OPTIONS_KEYBOARD_AND_PC_GAMEPAD = 4
HELP_SHOW_OPTIONS_PC_GAMEPAD = 3
