--- @meta HiddenItemValues

--- @alias HiddenItemValues integer
--- | `HIDDEN_ITEM_LOIN_CLOTH` # 5
--- | `HIDDEN_ITEM_MOUNT_INVENTORY_UPGRADE` # 4
--- | `HIDDEN_ITEM_MOUNT_SPEED_UPGRADE` # 3
--- | `HIDDEN_ITEM_MOUNT_STAMINA_UPGRADE` # 2
--- | `HIDDEN_ITEM_POLYMORPH_HELM` # 1
--- | `HIDDEN_ITEM_TASSETS` # 6

HIDDEN_ITEM_LOIN_CLOTH = 5
HIDDEN_ITEM_MOUNT_INVENTORY_UPGRADE = 4
HIDDEN_ITEM_MOUNT_SPEED_UPGRADE = 3
HIDDEN_ITEM_MOUNT_STAMINA_UPGRADE = 2
HIDDEN_ITEM_POLYMORPH_HELM = 1
HIDDEN_ITEM_TASSETS = 6
