--- @meta HirelingType

--- @alias HirelingType integer
--- | `HIRELING_TYPE_BLACKSMITHING` # 2
--- | `HIRELING_TYPE_CLOTHIER` # 4
--- | `HIRELING_TYPE_ENCHANTING` # 0
--- | `HIRELING_TYPE_JEWELRYCRAFTING` # 5
--- | `HIRELING_TYPE_PROVISIONING` # 1
--- | `HIRELING_TYPE_WOODWORKING` # 3

HIRELING_TYPE_BLACKSMITHING = 2
HIRELING_TYPE_CLOTHIER = 4
HIRELING_TYPE_ENCHANTING = 0
HIRELING_TYPE_JEWELRYCRAFTING = 5
HIRELING_TYPE_PROVISIONING = 1
HIRELING_TYPE_WOODWORKING = 3
