--- @meta HitTestingDesiredHandlers

--- @alias HitTestingDesiredHandlers integer
--- | `HIT_TESTING_DESIRED_HANDLERS_ANY` # 0
--- | `HIT_TESTING_DESIRED_HANDLERS_MOUSE_WHEEL_ONLY` # 2
--- | `HIT_TESTING_DESIRED_HANDLERS_RECEIVE_DRAG_ONLY` # 1

HIT_TESTING_DESIRED_HANDLERS_ANY = 0
HIT_TESTING_DESIRED_HANDLERS_MOUSE_WHEEL_ONLY = 2
HIT_TESTING_DESIRED_HANDLERS_RECEIVE_DRAG_ONLY = 1
