--- @meta HotBarResult

--- @alias HotBarResult integer
--- | `HOT_BAR_RESULT_ABILITY_NOT_ACTIVE` # 7
--- | `HOT_BAR_RESULT_ABILITY_NOT_KNOWN` # 3
--- | `HOT_BAR_RESULT_BAD_SLOT` # 4
--- | `HOT_BAR_RESULT_CANNOT_EDIT_HOTBAR` # 10
--- | `HOT_BAR_RESULT_CANNOT_EDIT_SLOT` # 13
--- | `HOT_BAR_RESULT_CANNOT_USE_WHILE_WEREWOLF` # 9
--- | `HOT_BAR_RESULT_COLLECTIBLE_NOT_UNLOCKED` # 8
--- | `HOT_BAR_RESULT_INVALID_SLOT_NUMBER` # 1
--- | `HOT_BAR_RESULT_IS_NOT_NORMAL` # 12
--- | `HOT_BAR_RESULT_IS_NOT_ULTIMATE` # 11
--- | `HOT_BAR_RESULT_ITEM_IN_WEAPON_SLOT` # 2
--- | `HOT_BAR_RESULT_ITEM_NOT_FOUND` # 5
--- | `HOT_BAR_RESULT_NO_COMBAT_SWAP` # 6
--- | `HOT_BAR_RESULT_SLOT_LOCKED` # 14
--- | `HOT_BAR_RESULT_SUCCESS` # 0

HOT_BAR_RESULT_ABILITY_NOT_ACTIVE = 7
HOT_BAR_RESULT_ABILITY_NOT_KNOWN = 3
HOT_BAR_RESULT_BAD_SLOT = 4
HOT_BAR_RESULT_CANNOT_EDIT_HOTBAR = 10
HOT_BAR_RESULT_CANNOT_EDIT_SLOT = 13
HOT_BAR_RESULT_CANNOT_USE_WHILE_WEREWOLF = 9
HOT_BAR_RESULT_COLLECTIBLE_NOT_UNLOCKED = 8
HOT_BAR_RESULT_INVALID_SLOT_NUMBER = 1
HOT_BAR_RESULT_IS_NOT_NORMAL = 12
HOT_BAR_RESULT_IS_NOT_ULTIMATE = 11
HOT_BAR_RESULT_ITEM_IN_WEAPON_SLOT = 2
HOT_BAR_RESULT_ITEM_NOT_FOUND = 5
HOT_BAR_RESULT_NO_COMBAT_SWAP = 6
HOT_BAR_RESULT_SLOT_LOCKED = 14
HOT_BAR_RESULT_SUCCESS = 0
