--- @meta HotBarCategory

--- @alias HotBarCategory integer
--- | `HOTBAR_CATEGORY_ALLY_WHEEL` # 13
--- | `HOTBAR_CATEGORY_BACKUP` # 1
--- | `HOTBAR_CATEGORY_CHAMPION` # 5
--- | `HOTBAR_CATEGORY_COMPANION` # 4
--- | `HOTBAR_CATEGORY_DAEDRIC_ARTIFACT` # 6
--- | `HOTBAR_CATEGORY_EMOTE_WHEEL` # 11
--- | `HOTBAR_CATEGORY_MEMENTO_WHEEL` # 12
--- | `HOTBAR_CATEGORY_OVERLOAD` # 7
--- | `HOTBAR_CATEGORY_PRIMARY` # 0
--- | `HOTBAR_CATEGORY_QUICKSLOT_WHEEL` # 10
--- | `HOTBAR_CATEGORY_TEMPORARY` # 9
--- | `HOTBAR_CATEGORY_TOOL_WHEEL` # 14
--- | `HOTBAR_CATEGORY_WEREWOLF` # 8

HOTBAR_CATEGORY_ALLY_WHEEL = 13
HOTBAR_CATEGORY_BACKUP = 1
HOTBAR_CATEGORY_CHAMPION = 5
HOTBAR_CATEGORY_COMPANION = 4
HOTBAR_CATEGORY_DAEDRIC_ARTIFACT = 6
HOTBAR_CATEGORY_EMOTE_WHEEL = 11
HOTBAR_CATEGORY_MEMENTO_WHEEL = 12
HOTBAR_CATEGORY_OVERLOAD = 7
HOTBAR_CATEGORY_PRIMARY = 0
HOTBAR_CATEGORY_QUICKSLOT_WHEEL = 10
HOTBAR_CATEGORY_TEMPORARY = 9
HOTBAR_CATEGORY_TOOL_WHEEL = 14
HOTBAR_CATEGORY_WEREWOLF = 8
