--- @meta HousingFurnitureBoundFilter

--- @alias HousingFurnitureBoundFilter integer
--- | `HOUSING_FURNITURE_BOUND_FILTER_ALL` # 0
--- | `HOUSING_FURNITURE_BOUND_FILTER_BOUND` # 1
--- | `HOUSING_FURNITURE_BOUND_FILTER_UNBOUND` # 2

HOUSING_FURNITURE_BOUND_FILTER_ALL = 0
HOUSING_FURNITURE_BOUND_FILTER_BOUND = 1
HOUSING_FURNITURE_BOUND_FILTER_UNBOUND = 2
