--- @meta HousingEditorPlacementType

--- @alias HousingEditorPlacementType integer
--- | `HOUSING_EDITOR_PLACEMENT_TYPE_PICKUP` # 0
--- | `HOUSING_EDITOR_PLACEMENT_TYPE_PRECISION` # 1

HOUSING_EDITOR_PLACEMENT_TYPE_PICKUP = 0
HOUSING_EDITOR_PLACEMENT_TYPE_PRECISION = 1
