--- @meta HousePermissionOptionsCategories

--- @alias HousePermissionOptionsCategories integer
--- | `HOUSE_PERMISSION_OPTIONS_CATEGORIES_BANLIST` # 3
--- | `HOUSE_PERMISSION_OPTIONS_CATEGORIES_GENERAL` # 1
--- | `HOUSE_PERMISSION_OPTIONS_CATEGORIES_GUILD_BANLIST` # 5
--- | `HOUSE_PERMISSION_OPTIONS_CATEGORIES_GUILD_VISITORS` # 4
--- | `HOUSE_PERMISSION_OPTIONS_CATEGORIES_OCCUPANTS` # 7
--- | `HOUSE_PERMISSION_OPTIONS_CATEGORIES_SOCIAL_OPTIONS` # 0
--- | `HOUSE_PERMISSION_OPTIONS_CATEGORIES_TEMPLATES` # 6
--- | `HOUSE_PERMISSION_OPTIONS_CATEGORIES_VISITORS` # 2

HOUSE_PERMISSION_OPTIONS_CATEGORIES_BANLIST = 3
HOUSE_PERMISSION_OPTIONS_CATEGORIES_GENERAL = 1
HOUSE_PERMISSION_OPTIONS_CATEGORIES_GUILD_BANLIST = 5
HOUSE_PERMISSION_OPTIONS_CATEGORIES_GUILD_VISITORS = 4
HOUSE_PERMISSION_OPTIONS_CATEGORIES_OCCUPANTS = 7
HOUSE_PERMISSION_OPTIONS_CATEGORIES_SOCIAL_OPTIONS = 0
HOUSE_PERMISSION_OPTIONS_CATEGORIES_TEMPLATES = 6
HOUSE_PERMISSION_OPTIONS_CATEGORIES_VISITORS = 2
