--- @meta HousingEditorCommandType

--- @alias HousingEditorCommandType integer
--- | `HOUSING_EDITOR_COMMAND_TYPE_CHANGE_PATH_STATE` # 7
--- | `HOUSING_EDITOR_COMMAND_TYPE_INSERT_PATH_NODE` # 8
--- | `HOUSING_EDITOR_COMMAND_TYPE_LINK` # 4
--- | `HOUSING_EDITOR_COMMAND_TYPE_MODIFY_PATH_NODE` # 9
--- | `HOUSING_EDITOR_COMMAND_TYPE_MOVE` # 1
--- | `HOUSING_EDITOR_COMMAND_TYPE_NONE` # 0
--- | `HOUSING_EDITOR_COMMAND_TYPE_PLACE` # 2
--- | `HOUSING_EDITOR_COMMAND_TYPE_REMOVE` # 3
--- | `HOUSING_EDITOR_COMMAND_TYPE_REMOVE_PATH_NODE` # 10
--- | `HOUSING_EDITOR_COMMAND_TYPE_REPLACE_PATH_COLLECTIBLE` # 11
--- | `HOUSING_EDITOR_COMMAND_TYPE_UNLINK` # 5
--- | `HOUSING_EDITOR_COMMAND_TYPE_UNLINK_ALL` # 6

HOUSING_EDITOR_COMMAND_TYPE_CHANGE_PATH_STATE = 7
HOUSING_EDITOR_COMMAND_TYPE_INSERT_PATH_NODE = 8
HOUSING_EDITOR_COMMAND_TYPE_LINK = 4
HOUSING_EDITOR_COMMAND_TYPE_MODIFY_PATH_NODE = 9
HOUSING_EDITOR_COMMAND_TYPE_MOVE = 1
HOUSING_EDITOR_COMMAND_TYPE_NONE = 0
HOUSING_EDITOR_COMMAND_TYPE_PLACE = 2
HOUSING_EDITOR_COMMAND_TYPE_REMOVE = 3
HOUSING_EDITOR_COMMAND_TYPE_REMOVE_PATH_NODE = 10
HOUSING_EDITOR_COMMAND_TYPE_REPLACE_PATH_COLLECTIBLE = 11
HOUSING_EDITOR_COMMAND_TYPE_UNLINK = 5
HOUSING_EDITOR_COMMAND_TYPE_UNLINK_ALL = 6
