--- @meta HousingEditorMode

--- @alias HousingEditorMode integer
--- | `HOUSING_EDITOR_MODE_BROWSE` # 3
--- | `HOUSING_EDITOR_MODE_DISABLED` # 0
--- | `HOUSING_EDITOR_MODE_LINK` # 4
--- | `HOUSING_EDITOR_MODE_NODE_PLACEMENT` # 6
--- | `HOUSING_EDITOR_MODE_PATH` # 5
--- | `HOUSING_EDITOR_MODE_PLACEMENT` # 1
--- | `HOUSING_EDITOR_MODE_SELECTION` # 2

HOUSING_EDITOR_MODE_BROWSE = 3
HOUSING_EDITOR_MODE_DISABLED = 0
HOUSING_EDITOR_MODE_LINK = 4
HOUSING_EDITOR_MODE_NODE_PLACEMENT = 6
HOUSING_EDITOR_MODE_PATH = 5
HOUSING_EDITOR_MODE_PLACEMENT = 1
HOUSING_EDITOR_MODE_SELECTION = 2
