--- @meta HousingEditorCommandResult

--- @alias HousingEditorCommandResult integer
--- | `HOUSING_EDITOR_COMMAND_RESULT_COLLECTIBLE_BLACKLISTED` # 10
--- | `HOUSING_EDITOR_COMMAND_RESULT_COLLECTIBLE_LOCKED` # 9
--- | `HOUSING_EDITOR_COMMAND_RESULT_COMMAND_FAILED` # 1
--- | `HOUSING_EDITOR_COMMAND_RESULT_CURRENTLY_INVALID` # 11
--- | `HOUSING_EDITOR_COMMAND_RESULT_FURNITURE_BEING_MOVED` # 2
--- | `HOUSING_EDITOR_COMMAND_RESULT_FURNITURE_LIMIT_REACHED` # 8
--- | `HOUSING_EDITOR_COMMAND_RESULT_INVALID_ITEM` # 3
--- | `HOUSING_EDITOR_COMMAND_RESULT_ITEM_IS_UNIQUE` # 5
--- | `HOUSING_EDITOR_COMMAND_RESULT_LINK_INVALID` # 7
--- | `HOUSING_EDITOR_COMMAND_RESULT_METRICS_CRITICAL` # 6
--- | `HOUSING_EDITOR_COMMAND_RESULT_NOT_ENOUGH_INVENTORY_SPACE` # 4
--- | `HOUSING_EDITOR_COMMAND_RESULT_PATH_OPERATION_INVALID` # 12
--- | `HOUSING_EDITOR_COMMAND_RESULT_SUCCESS` # 0

HOUSING_EDITOR_COMMAND_RESULT_COLLECTIBLE_BLACKLISTED = 10
HOUSING_EDITOR_COMMAND_RESULT_COLLECTIBLE_LOCKED = 9
HOUSING_EDITOR_COMMAND_RESULT_COMMAND_FAILED = 1
HOUSING_EDITOR_COMMAND_RESULT_CURRENTLY_INVALID = 11
HOUSING_EDITOR_COMMAND_RESULT_FURNITURE_BEING_MOVED = 2
HOUSING_EDITOR_COMMAND_RESULT_FURNITURE_LIMIT_REACHED = 8
HOUSING_EDITOR_COMMAND_RESULT_INVALID_ITEM = 3
HOUSING_EDITOR_COMMAND_RESULT_ITEM_IS_UNIQUE = 5
HOUSING_EDITOR_COMMAND_RESULT_LINK_INVALID = 7
HOUSING_EDITOR_COMMAND_RESULT_METRICS_CRITICAL = 6
HOUSING_EDITOR_COMMAND_RESULT_NOT_ENOUGH_INVENTORY_SPACE = 4
HOUSING_EDITOR_COMMAND_RESULT_PATH_OPERATION_INVALID = 12
HOUSING_EDITOR_COMMAND_RESULT_SUCCESS = 0
