--- @meta HousePathSettingCategories

--- @alias HousePathSettingCategories integer
--- | `HOUSE_PATH_SETTING_CATEGORIES_EDIT_PATH` # 0
--- | `HOUSE_PATH_SETTING_CATEGORIES_NODE_SETTINGS` # 2
--- | `HOUSE_PATH_SETTING_CATEGORIES_PATH_SETTINGS` # 1

HOUSE_PATH_SETTING_CATEGORIES_EDIT_PATH = 0
HOUSE_PATH_SETTING_CATEGORIES_NODE_SETTINGS = 2
HOUSE_PATH_SETTING_CATEGORIES_PATH_SETTINGS = 1
