--- @meta HousingPendingLinkRelationship

--- @alias HousingPendingLinkRelationship integer
--- | `HOUSING_EDITOR_PENDING_LINK_RELATIONSHIP_BAD_LINK` # 4
--- | `HOUSING_EDITOR_PENDING_LINK_RELATIONSHIP_INVALID` # 0
--- | `HOUSING_EDITOR_PENDING_LINK_RELATIONSHIP_LINKED_AS_CHILD` # 2
--- | `HOUSING_EDITOR_PENDING_LINK_RELATIONSHIP_LINKED_TO_PARENT` # 1
--- | `HOUSING_EDITOR_PENDING_LINK_RELATIONSHIP_NO_LINK` # 3

HOUSING_EDITOR_PENDING_LINK_RELATIONSHIP_BAD_LINK = 4
HOUSING_EDITOR_PENDING_LINK_RELATIONSHIP_INVALID = 0
HOUSING_EDITOR_PENDING_LINK_RELATIONSHIP_LINKED_AS_CHILD = 2
HOUSING_EDITOR_PENDING_LINK_RELATIONSHIP_LINKED_TO_PARENT = 1
HOUSING_EDITOR_PENDING_LINK_RELATIONSHIP_NO_LINK = 3
