--- @meta HousingVisitorRole

--- @alias HousingVisitorRole integer
--- | `HOUSING_VISITOR_ROLE_EDITOR` # 0
--- | `HOUSING_VISITOR_ROLE_HOME_SHOW` # 2
--- | `HOUSING_VISITOR_ROLE_PREVIEW` # 1

HOUSING_VISITOR_ROLE_EDITOR = 0
HOUSING_VISITOR_ROLE_HOME_SHOW = 2
HOUSING_VISITOR_ROLE_PREVIEW = 1
