--- @meta HousingPathDelayTime

--- @alias HousingPathDelayTime integer
--- | `HOUSING_PATH_DELAY_TIME_CUSTOM` # 6
--- | `HOUSING_PATH_DELAY_TIME_EXTREMELY_LONG` # 5
--- | `HOUSING_PATH_DELAY_TIME_LONG` # 3
--- | `HOUSING_PATH_DELAY_TIME_MEDIUM` # 2
--- | `HOUSING_PATH_DELAY_TIME_NONE` # 0
--- | `HOUSING_PATH_DELAY_TIME_SHORT` # 1
--- | `HOUSING_PATH_DELAY_TIME_VERY_LONG` # 4

HOUSING_PATH_DELAY_TIME_CUSTOM = 6
HOUSING_PATH_DELAY_TIME_EXTREMELY_LONG = 5
HOUSING_PATH_DELAY_TIME_LONG = 3
HOUSING_PATH_DELAY_TIME_MEDIUM = 2
HOUSING_PATH_DELAY_TIME_NONE = 0
HOUSING_PATH_DELAY_TIME_SHORT = 1
HOUSING_PATH_DELAY_TIME_VERY_LONG = 4
