--- @meta HousingFurnitureLocationFilter

--- @alias HousingFurnitureLocationFilter integer
--- | `HOUSING_FURNITURE_LOCATION_FILTER_ALL` # 1
--- | `HOUSING_FURNITURE_LOCATION_FILTER_BACKPACK` # 2
--- | `HOUSING_FURNITURE_LOCATION_FILTER_BANK` # 4
--- | `HOUSING_FURNITURE_LOCATION_FILTER_COLLECTIBLES` # 16
--- | `HOUSING_FURNITURE_LOCATION_FILTER_STORAGE` # 8

HOUSING_FURNITURE_LOCATION_FILTER_ALL = 1
HOUSING_FURNITURE_LOCATION_FILTER_BACKPACK = 2
HOUSING_FURNITURE_LOCATION_FILTER_BANK = 4
HOUSING_FURNITURE_LOCATION_FILTER_COLLECTIBLES = 16
HOUSING_FURNITURE_LOCATION_FILTER_STORAGE = 8
