--- @meta HousingPathMovementSpeed

--- @alias HousingPathMovementSpeed integer
--- | `HOUSING_PATH_MOVEMENT_SPEED_JOG` # 1
--- | `HOUSING_PATH_MOVEMENT_SPEED_RUN` # 2
--- | `HOUSING_PATH_MOVEMENT_SPEED_SPRINT` # 3
--- | `HOUSING_PATH_MOVEMENT_SPEED_WALK` # 0

HOUSING_PATH_MOVEMENT_SPEED_JOG = 1
HOUSING_PATH_MOVEMENT_SPEED_RUN = 2
HOUSING_PATH_MOVEMENT_SPEED_SPRINT = 3
HOUSING_PATH_MOVEMENT_SPEED_WALK = 0
