--- @meta HousingFurnishingLimitType

--- @alias HousingFurnishingLimitType integer
--- | `HOUSING_FURNISHING_LIMIT_TYPE_HIGH_IMPACT_COLLECTIBLE` # 3
--- | `HOUSING_FURNISHING_LIMIT_TYPE_HIGH_IMPACT_ITEM` # 1
--- | `HOUSING_FURNISHING_LIMIT_TYPE_LOW_IMPACT_COLLECTIBLE` # 2
--- | `HOUSING_FURNISHING_LIMIT_TYPE_LOW_IMPACT_ITEM` # 0

HOUSING_FURNISHING_LIMIT_TYPE_HIGH_IMPACT_COLLECTIBLE = 3
HOUSING_FURNISHING_LIMIT_TYPE_HIGH_IMPACT_ITEM = 1
HOUSING_FURNISHING_LIMIT_TYPE_LOW_IMPACT_COLLECTIBLE = 2
HOUSING_FURNISHING_LIMIT_TYPE_LOW_IMPACT_ITEM = 0
