--- @meta HousingLoadPermissionsResult

--- @alias HousingLoadPermissionsResult integer
--- | `HOUSING_LOAD_PERMISSIONS_RESULT_NO_CHANGE` # 0
--- | `HOUSING_LOAD_PERMISSIONS_RESULT_SUCCESS` # 1

HOUSING_LOAD_PERMISSIONS_RESULT_NO_CHANGE = 0
HOUSING_LOAD_PERMISSIONS_RESULT_SUCCESS = 1
