--- @meta HouseCategoryType

--- @alias HouseCategoryType integer
--- | `HOUSE_CATEGORY_TYPE_CLASSIC` # 2
--- | `HOUSE_CATEGORY_TYPE_NONE` # 0
--- | `HOUSE_CATEGORY_TYPE_NOTABLE` # 3
--- | `HOUSE_CATEGORY_TYPE_STAPLE` # 1

HOUSE_CATEGORY_TYPE_CLASSIC = 2
HOUSE_CATEGORY_TYPE_NONE = 0
HOUSE_CATEGORY_TYPE_NOTABLE = 3
HOUSE_CATEGORY_TYPE_STAPLE = 1
