--- @meta HousingSetStateReason

--- @alias HousingSetStateReason integer
--- | `HOUSING_SET_STATE_REASON_INITIALIZE` # 1
--- | `HOUSING_SET_STATE_REASON_MUTUAL_EXCLUSION` # 2
--- | `HOUSING_SET_STATE_REASON_USER_REQUEST` # 0

HOUSING_SET_STATE_REASON_INITIALIZE = 1
HOUSING_SET_STATE_REASON_MUTUAL_EXCLUSION = 2
HOUSING_SET_STATE_REASON_USER_REQUEST = 0
