--- @meta HousingMetricsState

--- @alias HousingMetricsState integer
--- | `HOUSING_METRICS_STATE_CAUTION` # 1
--- | `HOUSING_METRICS_STATE_CRITICAL` # 2
--- | `HOUSING_METRICS_STATE_SAFE` # 0

HOUSING_METRICS_STATE_CAUTION = 1
HOUSING_METRICS_STATE_CRITICAL = 2
HOUSING_METRICS_STATE_SAFE = 0
