--- @meta HousePermissionResult

--- @alias HousePermissionResult integer
--- | `HOUSE_PERMISSION_RESULT_FAILED_TO_ADD` # 2
--- | `HOUSE_PERMISSION_RESULT_FAILED_TO_MODIFY` # 4
--- | `HOUSE_PERMISSION_RESULT_FAILED_TO_REMOVE` # 3
--- | `HOUSE_PERMISSION_RESULT_INIT` # 0
--- | `HOUSE_PERMISSION_RESULT_SUCCESS` # 1

HOUSE_PERMISSION_RESULT_FAILED_TO_ADD = 2
HOUSE_PERMISSION_RESULT_FAILED_TO_MODIFY = 4
HOUSE_PERMISSION_RESULT_FAILED_TO_REMOVE = 3
HOUSE_PERMISSION_RESULT_INIT = 0
HOUSE_PERMISSION_RESULT_SUCCESS = 1
