--- @meta HousePermissionPresetSetting

--- @alias HousePermissionPresetSetting integer
--- | `HOUSE_PERMISSION_PRESET_SETTING_DECORATOR` # 1
--- | `HOUSE_PERMISSION_PRESET_SETTING_INVALID` # 0
--- | `HOUSE_PERMISSION_PRESET_SETTING_LIMITED_VISITOR` # 3
--- | `HOUSE_PERMISSION_PRESET_SETTING_VISITOR` # 2

HOUSE_PERMISSION_PRESET_SETTING_DECORATOR = 1
HOUSE_PERMISSION_PRESET_SETTING_INVALID = 0
HOUSE_PERMISSION_PRESET_SETTING_LIMITED_VISITOR = 3
HOUSE_PERMISSION_PRESET_SETTING_VISITOR = 2
