--- @meta HousePermissionSetting

--- @alias HousePermissionSetting integer
--- | `HOUSE_PERMISSION_SETTING_BOOL_SECTION_END` # 8
--- | `HOUSE_PERMISSION_SETTING_LINK_FURNITURE` # 6
--- | `HOUSE_PERMISSION_SETTING_MOVE_FURNITURE` # 4
--- | `HOUSE_PERMISSION_SETTING_PATH_FURNITURE` # 7
--- | `HOUSE_PERMISSION_SETTING_PLACE_TEMP_ITEMS` # 5
--- | `HOUSE_PERMISSION_SETTING_USE_ASSISTANTS` # 2
--- | `HOUSE_PERMISSION_SETTING_USE_INTERACTABLE_FIXTURES` # 3
--- | `HOUSE_PERMISSION_SETTING_USE_OBJECTS` # 1

HOUSE_PERMISSION_SETTING_BOOL_SECTION_END = 8
HOUSE_PERMISSION_SETTING_LINK_FURNITURE = 6
HOUSE_PERMISSION_SETTING_MOVE_FURNITURE = 4
HOUSE_PERMISSION_SETTING_PATH_FURNITURE = 7
HOUSE_PERMISSION_SETTING_PLACE_TEMP_ITEMS = 5
HOUSE_PERMISSION_SETTING_USE_ASSISTANTS = 2
HOUSE_PERMISSION_SETTING_USE_INTERACTABLE_FIXTURES = 3
HOUSE_PERMISSION_SETTING_USE_OBJECTS = 1
