--- @meta HousePermissionUserGroup

--- @alias HousePermissionUserGroup integer
--- | `HOUSE_PERMISSION_USER_GROUP_GENERAL` # 0
--- | `HOUSE_PERMISSION_USER_GROUP_GUILD` # 1
--- | `HOUSE_PERMISSION_USER_GROUP_INDIVIDUAL` # 2

HOUSE_PERMISSION_USER_GROUP_GENERAL = 0
HOUSE_PERMISSION_USER_GROUP_GUILD = 1
HOUSE_PERMISSION_USER_GROUP_INDIVIDUAL = 2
