--- @meta HousePermissionDefaultAccessSetting

--- @alias HousePermissionDefaultAccessSetting integer
--- | `HOUSE_PERMISSION_DEFAULT_ACCESS_SETTING_DECORATOR` # 3
--- | `HOUSE_PERMISSION_DEFAULT_ACCESS_SETTING_LIMITED_VISITOR` # 1
--- | `HOUSE_PERMISSION_DEFAULT_ACCESS_SETTING_NO_ACCESS` # 0
--- | `HOUSE_PERMISSION_DEFAULT_ACCESS_SETTING_VISITOR` # 2

HOUSE_PERMISSION_DEFAULT_ACCESS_SETTING_DECORATOR = 3
HOUSE_PERMISSION_DEFAULT_ACCESS_SETTING_LIMITED_VISITOR = 1
HOUSE_PERMISSION_DEFAULT_ACCESS_SETTING_NO_ACCESS = 0
HOUSE_PERMISSION_DEFAULT_ACCESS_SETTING_VISITOR = 2
