--- @meta HousingEditorPrecisionPlacementMode

--- @alias HousingEditorPrecisionPlacementMode integer
--- | `HOUSING_EDITOR_PRECISION_PLACEMENT_MODE_MOVE` # 0
--- | `HOUSING_EDITOR_PRECISION_PLACEMENT_MODE_ROTATE` # 1

HOUSING_EDITOR_PRECISION_PLACEMENT_MODE_MOVE = 0
HOUSING_EDITOR_PRECISION_PLACEMENT_MODE_ROTATE = 1
