--- @meta ImperialCityAccessRulesType

--- @alias ImperialCityAccessRulesType integer
--- | `IMPERIAL_CITY_ACCESS_RULE_TYPE_EVERYONE` # 3
--- | `IMPERIAL_CITY_ACCESS_RULE_TYPE_MAJORITY_KEEPS` # 0
--- | `IMPERIAL_CITY_ACCESS_RULE_TYPE_NATIVE_KEEPS` # 1
--- | `IMPERIAL_CITY_ACCESS_RULE_TYPE_NATIVE_KEEPS_PLUS_ONE` # 2

IMPERIAL_CITY_ACCESS_RULE_TYPE_EVERYONE = 3
IMPERIAL_CITY_ACCESS_RULE_TYPE_MAJORITY_KEEPS = 0
IMPERIAL_CITY_ACCESS_RULE_TYPE_NATIVE_KEEPS = 1
IMPERIAL_CITY_ACCESS_RULE_TYPE_NATIVE_KEEPS_PLUS_ONE = 2
