--- @meta InfamyThresholdsType

--- @alias InfamyThresholdsType integer
--- | `INFAMY_THRESHOLD_DISREPUTABLE` # 1
--- | `INFAMY_THRESHOLD_FUGITIVE` # 3
--- | `INFAMY_THRESHOLD_NOTORIOUS` # 2
--- | `INFAMY_THRESHOLD_UPSTANDING` # 0

INFAMY_THRESHOLD_DISREPUTABLE = 1
INFAMY_THRESHOLD_FUGITIVE = 3
INFAMY_THRESHOLD_NOTORIOUS = 2
INFAMY_THRESHOLD_UPSTANDING = 0
