--- @meta InputPreferredMode

--- @alias InputPreferredMode integer
--- | `INPUT_PREFERRED_MODE_ALWAYS_GAMEPAD` # 1
--- | `INPUT_PREFERRED_MODE_ALWAYS_KEYBOARD` # 0
--- | `INPUT_PREFERRED_MODE_AUTOMATIC` # 2

INPUT_PREFERRED_MODE_ALWAYS_GAMEPAD = 1
INPUT_PREFERRED_MODE_ALWAYS_KEYBOARD = 0
INPUT_PREFERRED_MODE_AUTOMATIC = 2
