--- @meta InstanceType

--- @alias InstanceType integer
--- | `INSTANCE_TYPE_BATTLEGROUND` # 4
--- | `INSTANCE_TYPE_GRADUATION_MOMENT` # 5
--- | `INSTANCE_TYPE_GROUP` # 2
--- | `INSTANCE_TYPE_HOUSING` # 7
--- | `INSTANCE_TYPE_NONE` # 0
--- | `INSTANCE_TYPE_PUBLIC_DUNGEON` # 6
--- | `INSTANCE_TYPE_RAID` # 3
--- | `INSTANCE_TYPE_SOLO` # 1

INSTANCE_TYPE_BATTLEGROUND = 4
INSTANCE_TYPE_GRADUATION_MOMENT = 5
INSTANCE_TYPE_GROUP = 2
INSTANCE_TYPE_HOUSING = 7
INSTANCE_TYPE_NONE = 0
INSTANCE_TYPE_PUBLIC_DUNGEON = 6
INSTANCE_TYPE_RAID = 3
INSTANCE_TYPE_SOLO = 1
