--- @meta InstantUnlockRewardCategory

--- @alias InstantUnlockRewardCategory integer
--- | `INSTANT_UNLOCK_REWARD_CATEGORY_NONE` # 0
--- | `INSTANT_UNLOCK_REWARD_CATEGORY_QUEST_STARTER` # 3
--- | `INSTANT_UNLOCK_REWARD_CATEGORY_SERVICE_TOKEN` # 2
--- | `INSTANT_UNLOCK_REWARD_CATEGORY_UPGRADE` # 1

INSTANT_UNLOCK_REWARD_CATEGORY_NONE = 0
INSTANT_UNLOCK_REWARD_CATEGORY_QUEST_STARTER = 3
INSTANT_UNLOCK_REWARD_CATEGORY_SERVICE_TOKEN = 2
INSTANT_UNLOCK_REWARD_CATEGORY_UPGRADE = 1
