--- @meta InstantUnlockRewardType

--- @alias InstantUnlockRewardType integer
--- | `INSTANT_UNLOCK_ACCOUNT_MINOR_BACKPACK` # 15
--- | `INSTANT_UNLOCK_ALLIANCE_CHANGE_TOKEN` # 16
--- | `INSTANT_UNLOCK_APPEARANCE_CHANGE_TOKEN` # 9
--- | `INSTANT_UNLOCK_ARMORY_BUILD_SLOT` # 17
--- | `INSTANT_UNLOCK_BITE_CURE` # 5
--- | `INSTANT_UNLOCK_CHARACTER_SLOT` # 6
--- | `INSTANT_UNLOCK_ESO_PLUS` # 10
--- | `INSTANT_UNLOCK_NONE` # 0
--- | `INSTANT_UNLOCK_OUTFIT` # 11
--- | `INSTANT_UNLOCK_PLAYER_BACKPACK` # 1
--- | `INSTANT_UNLOCK_PLAYER_BANK` # 2
--- | `INSTANT_UNLOCK_QUEST_GRANT` # 14
--- | `INSTANT_UNLOCK_RACE_CHANGE_TOKEN` # 8
--- | `INSTANT_UNLOCK_RENAME_TOKEN` # 7
--- | `INSTANT_UNLOCK_SKILL_LINE` # 13
--- | `INSTANT_UNLOCK_SKYSHARD_ZONE` # 12
--- | `INSTANT_UNLOCK_VAMPIRE_BITE` # 4
--- | `INSTANT_UNLOCK_WEREWOLF_BITE` # 3

INSTANT_UNLOCK_ACCOUNT_MINOR_BACKPACK = 15
INSTANT_UNLOCK_ALLIANCE_CHANGE_TOKEN = 16
INSTANT_UNLOCK_APPEARANCE_CHANGE_TOKEN = 9
INSTANT_UNLOCK_ARMORY_BUILD_SLOT = 17
INSTANT_UNLOCK_BITE_CURE = 5
INSTANT_UNLOCK_CHARACTER_SLOT = 6
INSTANT_UNLOCK_ESO_PLUS = 10
INSTANT_UNLOCK_NONE = 0
INSTANT_UNLOCK_OUTFIT = 11
INSTANT_UNLOCK_PLAYER_BACKPACK = 1
INSTANT_UNLOCK_PLAYER_BANK = 2
INSTANT_UNLOCK_QUEST_GRANT = 14
INSTANT_UNLOCK_RACE_CHANGE_TOKEN = 8
INSTANT_UNLOCK_RENAME_TOKEN = 7
INSTANT_UNLOCK_SKILL_LINE = 13
INSTANT_UNLOCK_SKYSHARD_ZONE = 12
INSTANT_UNLOCK_VAMPIRE_BITE = 4
INSTANT_UNLOCK_WEREWOLF_BITE = 3
