--- @meta InterfaceGeneralColors

--- @alias InterfaceGeneralColors integer
--- | `INTERFACE_GENERAL_COLOR_ALERT` # 3
--- | `INTERFACE_GENERAL_COLOR_BLACK` # 7
--- | `INTERFACE_GENERAL_COLOR_DISABLED` # 1
--- | `INTERFACE_GENERAL_COLOR_ENABLED` # 0
--- | `INTERFACE_GENERAL_COLOR_ERROR` # 2
--- | `INTERFACE_GENERAL_COLOR_STATUS_BAR_END` # 6
--- | `INTERFACE_GENERAL_COLOR_STATUS_BAR_START` # 5
--- | `INTERFACE_GENERAL_COLOR_WARNING` # 4

INTERFACE_GENERAL_COLOR_ALERT = 3
INTERFACE_GENERAL_COLOR_BLACK = 7
INTERFACE_GENERAL_COLOR_DISABLED = 1
INTERFACE_GENERAL_COLOR_ENABLED = 0
INTERFACE_GENERAL_COLOR_ERROR = 2
INTERFACE_GENERAL_COLOR_STATUS_BAR_END = 6
INTERFACE_GENERAL_COLOR_STATUS_BAR_START = 5
INTERFACE_GENERAL_COLOR_WARNING = 4
