--- @meta InteractTargetType

--- @alias InteractTargetType integer
--- | `INTERACT_TARGET_TYPE_AOE_LOOT` # 6
--- | `INTERACT_TARGET_TYPE_CLIENT_CHARACTER` # 3
--- | `INTERACT_TARGET_TYPE_COLLECTIBLE` # 7
--- | `INTERACT_TARGET_TYPE_FIXTURE` # 5
--- | `INTERACT_TARGET_TYPE_ITEM` # 2
--- | `INTERACT_TARGET_TYPE_NONE` # 0
--- | `INTERACT_TARGET_TYPE_OBJECT` # 1
--- | `INTERACT_TARGET_TYPE_QUEST_ITEM` # 4
--- | `INTERACT_TARGET_TYPE_TRIBUTE` # 8

INTERACT_TARGET_TYPE_AOE_LOOT = 6
INTERACT_TARGET_TYPE_CLIENT_CHARACTER = 3
INTERACT_TARGET_TYPE_COLLECTIBLE = 7
INTERACT_TARGET_TYPE_FIXTURE = 5
INTERACT_TARGET_TYPE_ITEM = 2
INTERACT_TARGET_TYPE_NONE = 0
INTERACT_TARGET_TYPE_OBJECT = 1
INTERACT_TARGET_TYPE_QUEST_ITEM = 4
INTERACT_TARGET_TYPE_TRIBUTE = 8
