--- @meta InteractionType

--- @alias InteractionType integer
--- | `INTERACTION_ANTIQUITY_DIG_SPOT` # 40
--- | `INTERACTION_ANTIQUITY_SCRYING` # 41
--- | `INTERACTION_ARMORY` # 43
--- | `INTERACTION_ATTRIBUTE_RESPEC` # 38
--- | `INTERACTION_AVA_HOOK_POINT` # 16
--- | `INTERACTION_BANK` # 6
--- | `INTERACTION_BOOK` # 12
--- | `INTERACTION_BUY_BAG_SPACE` # 19
--- | `INTERACTION_COMPANION_MENU` # 42
--- | `INTERACTION_CONVERSATION` # 14
--- | `INTERACTION_CRAFT` # 23
--- | `INTERACTION_DEPRECATED_1` # 17
--- | `INTERACTION_DYE_STATION` # 31
--- | `INTERACTION_ENDLESS_DUNGEON_BUFF_SELECTOR` # 46
--- | `INTERACTION_FAST_TRAVEL` # 11
--- | `INTERACTION_FAST_TRAVEL_KEEP` # 8
--- | `INTERACTION_FISH` # 24
--- | `INTERACTION_FURNITURE` # 35
--- | `INTERACTION_GUILDBANK` # 25
--- | `INTERACTION_GUILDKIOSK_BID` # 18
--- | `INTERACTION_GUILDKIOSK_PURCHASE` # 32
--- | `INTERACTION_HARVEST` # 28
--- | `INTERACTION_HIDEYHOLE` # 34
--- | `INTERACTION_KEEP_GUILD_CLAIM` # 5
--- | `INTERACTION_KEEP_GUILD_RELEASE` # 29
--- | `INTERACTION_KEEP_INSPECT` # 4
--- | `INTERACTION_KEEP_PIECE` # 21
--- | `INTERACTION_LOCKPICK` # 20
--- | `INTERACTION_LOOT` # 2
--- | `INTERACTION_MAIL` # 7
--- | `INTERACTION_NONE` # 0
--- | `INTERACTION_PAY_BOUNTY` # 30
--- | `INTERACTION_PICKPOCKET` # 33
--- | `INTERACTION_QUEST` # 3
--- | `INTERACTION_RETRAIT` # 36
--- | `INTERACTION_SIEGE` # 22
--- | `INTERACTION_SKILL_RESPEC` # 37
--- | `INTERACTION_STABLE` # 27
--- | `INTERACTION_STORE` # 1
--- | `INTERACTION_THEATER_INTERACTABLE` # 44
--- | `INTERACTION_TRADINGHOUSE` # 26
--- | `INTERACTION_TREASURE_MAP` # 39
--- | `INTERACTION_TRIBUTE` # 45
--- | `INTERACTION_VENDOR` # 15

INTERACTION_ANTIQUITY_DIG_SPOT = 40
INTERACTION_ANTIQUITY_SCRYING = 41
INTERACTION_ARMORY = 43
INTERACTION_ATTRIBUTE_RESPEC = 38
INTERACTION_AVA_HOOK_POINT = 16
INTERACTION_BANK = 6
INTERACTION_BOOK = 12
INTERACTION_BUY_BAG_SPACE = 19
INTERACTION_COMPANION_MENU = 42
INTERACTION_CONVERSATION = 14
INTERACTION_CRAFT = 23
INTERACTION_DEPRECATED_1 = 17
INTERACTION_DYE_STATION = 31
INTERACTION_ENDLESS_DUNGEON_BUFF_SELECTOR = 46
INTERACTION_FAST_TRAVEL = 11
INTERACTION_FAST_TRAVEL_KEEP = 8
INTERACTION_FISH = 24
INTERACTION_FURNITURE = 35
INTERACTION_GUILDBANK = 25
INTERACTION_GUILDKIOSK_BID = 18
INTERACTION_GUILDKIOSK_PURCHASE = 32
INTERACTION_HARVEST = 28
INTERACTION_HIDEYHOLE = 34
INTERACTION_KEEP_GUILD_CLAIM = 5
INTERACTION_KEEP_GUILD_RELEASE = 29
INTERACTION_KEEP_INSPECT = 4
INTERACTION_KEEP_PIECE = 21
INTERACTION_LOCKPICK = 20
INTERACTION_LOOT = 2
INTERACTION_MAIL = 7
INTERACTION_NONE = 0
INTERACTION_PAY_BOUNTY = 30
INTERACTION_PICKPOCKET = 33
INTERACTION_QUEST = 3
INTERACTION_RETRAIT = 36
INTERACTION_SIEGE = 22
INTERACTION_SKILL_RESPEC = 37
INTERACTION_STABLE = 27
INTERACTION_STORE = 1
INTERACTION_THEATER_INTERACTABLE = 44
INTERACTION_TRADINGHOUSE = 26
INTERACTION_TREASURE_MAP = 39
INTERACTION_TRIBUTE = 45
INTERACTION_VENDOR = 15
