--- @meta InteractType

--- @alias InteractType integer
--- | `CHATTER_ACCEPT_QUEST_BESTOWAL` # 202
--- | `CHATTER_ADVANCE_COMPLETABLE_QUEST_CONDITIONS_COMPLETE` # 4001
--- | `CHATTER_BEGIN` # 1
--- | `CHATTER_BEGIN_INTERACT_NODE` # 4
--- | `CHATTER_COMPLETE_ANTIQUITY_DIGGING` # 4751
--- | `CHATTER_COMPLETE_ANTIQUITY_SCRYING` # 4761
--- | `CHATTER_COMPLETE_QUEST_CONFIRM` # 302
--- | `CHATTER_COMPLETE_QUEST_DIALOG` # 301
--- | `CHATTER_CONFIRM_BUY_BAG_SPACE` # 1602
--- | `CHATTER_CONFIRM_BUY_BANK_SPACE` # 1201
--- | `CHATTER_CONTROL_SIEGE` # 1103
--- | `CHATTER_CRAFT_ITEM` # 2902
--- | `CHATTER_DECONSTRUCT_ITEM` # 2903
--- | `CHATTER_DESTROY_SIEGE` # 1101
--- | `CHATTER_DO_KEEP_GUILD_CLAIM` # 2602
--- | `CHATTER_DO_KEEP_GUILD_RELEASE` # 3502
--- | `CHATTER_ENDLESS_DUNGEON_BUFF_SELECTOR_CHOICE` # 4801
--- | `CHATTER_END_ADVANCE_COMPLETABLE_QUEST_CONDITIONS` # 4099
--- | `CHATTER_END_ANTIQUITY_DIG_SPOT` # 4759
--- | `CHATTER_END_ANTIQUITY_SCRYING` # 4769
--- | `CHATTER_END_ARMORY` # 4789
--- | `CHATTER_END_ATTRIBUTE_RESPEC` # 4739
--- | `CHATTER_END_BANK` # 1299
--- | `CHATTER_END_BOOK` # 2599
--- | `CHATTER_END_BUY_BAG_SPACE` # 1699
--- | `CHATTER_END_COMPANION_MENU` # 4779
--- | `CHATTER_END_COMPLETE_QUEST` # 399
--- | `CHATTER_END_CRAFT` # 2999
--- | `CHATTER_END_DOOR` # 2799
--- | `CHATTER_END_DYE_STATION` # 899
--- | `CHATTER_END_ENDLESS_DUNGEON_BUFF_SELECTOR` # 4809
--- | `CHATTER_END_FISH` # 3299
--- | `CHATTER_END_GIVE_ITEM` # 499
--- | `CHATTER_END_GRAVEYARD_TRAVEL` # 2499
--- | `CHATTER_END_GUILDBANK` # 3399
--- | `CHATTER_END_GUILDKIOSK_BID` # 3899
--- | `CHATTER_END_GUILDKIOSK_PURCHASE` # 3999
--- | `CHATTER_END_HARVEST` # 3099
--- | `CHATTER_END_HIDEYHOLE` # 4399
--- | `CHATTER_END_KEEP` # 2099
--- | `CHATTER_END_KEEP_GUILD_CLAIM` # 2699
--- | `CHATTER_END_KEEP_GUILD_RELEASE` # 3599
--- | `CHATTER_END_KEEP_PIECE` # 1099
--- | `CHATTER_END_KEEP_TRAVEL` # 2199
--- | `CHATTER_END_LOCK` # 2899
--- | `CHATTER_END_LOOT` # 799
--- | `CHATTER_END_MAIL` # 999
--- | `CHATTER_END_NEW_QUEST_BESTOWAL` # 299
--- | `CHATTER_END_PAY_BOUNTY` # 599
--- | `CHATTER_END_PICKPOCKET` # 4199
--- | `CHATTER_END_REPAIR_ALL` # 4299
--- | `CHATTER_END_RETRAIT` # 4719
--- | `CHATTER_END_SHOP` # 699
--- | `CHATTER_END_SIEGE` # 1199
--- | `CHATTER_END_SKILL_RESPEC` # 4729
--- | `CHATTER_END_STABLE` # 3199
--- | `CHATTER_END_TALK` # 199
--- | `CHATTER_END_TRADINGHOUSE` # 3499
--- | `CHATTER_END_TREASURE_MAP` # 4749
--- | `CHATTER_END_TRIBUTE` # 4799
--- | `CHATTER_END_USE_CLEMENCY` # 4499
--- | `CHATTER_END_USE_FURNITURE` # 4609
--- | `CHATTER_END_USE_SHADOWY_CONNECTIONS` # 4509
--- | `CHATTER_EXIT_HIDEYHOLE` # 4301
--- | `CHATTER_FEED_MOUNT` # 3102
--- | `CHATTER_FISH_BITE` # 3202
--- | `CHATTER_FISH_NIBBLE` # 3203
--- | `CHATTER_FISH_REEL_IN` # 3201
--- | `CHATTER_FORCE_LOCK` # 2802
--- | `CHATTER_GIVE_ITEM_COMPLETE` # 401
--- | `CHATTER_GOODBYE` # 10000
--- | `CHATTER_GUILDKIOSK_IN_TRANSITION` # 3902
--- | `CHATTER_IMPROVE_ITEM` # 2905
--- | `CHATTER_INVALID` # 0
--- | `CHATTER_LOCK_PICK_BROKEN` # 2804
--- | `CHATTER_LOOT_ADD_RADIUS_TARGET` # 704
--- | `CHATTER_LOOT_ALL` # 701
--- | `CHATTER_LOOT_ALL_NON_STOLEN` # 702
--- | `CHATTER_LOOT_ITEM` # 703
--- | `CHATTER_LOOT_REMOVE_RADIUS_TARGET` # 705
--- | `CHATTER_LOOT_UPDATE` # 707
--- | `CHATTER_OFFER_QUEST_BESTOWAL` # 201
--- | `CHATTER_OPEN_GUILDBANK` # 3301
--- | `CHATTER_OPEN_MAIL` # 901
--- | `CHATTER_OPEN_SKILL_RESPEC` # 4721
--- | `CHATTER_OPEN_TRADINGHOUSE` # 3401
--- | `CHATTER_PACKUP_SIEGE` # 1104
--- | `CHATTER_PICK_LOCK` # 2803
--- | `CHATTER_PLACE_GUILDKIOSK_BID` # 3801
--- | `CHATTER_PROMPT_BUY_BAG_SPACE` # 1601
--- | `CHATTER_PROMPT_CRAFT` # 2901
--- | `CHATTER_PROMPT_DYE_STATION` # 801
--- | `CHATTER_PROMPT_LOCK` # 2801
--- | `CHATTER_PROMPT_RETRAIT` # 4701
--- | `CHATTER_PURCHASE_GUILDKIOSK` # 3901
--- | `CHATTER_REPAIR_SIEGE` # 1102
--- | `CHATTER_RESEARCH_ITEM` # 2904
--- | `CHATTER_RESET` # 2
--- | `CHATTER_RESET_DURATION` # 3
--- | `CHATTER_SHOW_BOOK` # 2501
--- | `CHATTER_SHOW_GRAVEYARD_TRAVEL` # 2401
--- | `CHATTER_SHOW_KEEP_GUILD_CLAIM` # 2601
--- | `CHATTER_SHOW_KEEP_GUILD_RELEASE` # 3501
--- | `CHATTER_SHOW_KEEP_TRAVEL` # 2101
--- | `CHATTER_SHOW_TREASURE_MAP` # 4741
--- | `CHATTER_START_ADVANCE_COMPLETABLE_QUEST_CONDITIONS` # 4000
--- | `CHATTER_START_ANTIQUITY_DIG_SPOT` # 4750
--- | `CHATTER_START_ANTIQUITY_SCRYING` # 4760
--- | `CHATTER_START_ARMORY` # 4780
--- | `CHATTER_START_ATTRIBUTE_RESPEC` # 4730
--- | `CHATTER_START_BANK` # 1200
--- | `CHATTER_START_BOOK` # 2500
--- | `CHATTER_START_BUY_BAG_SPACE` # 1600
--- | `CHATTER_START_COMPANION_MENU` # 4770
--- | `CHATTER_START_COMPLETE_QUEST` # 300
--- | `CHATTER_START_CRAFT` # 2900
--- | `CHATTER_START_DOOR` # 2700
--- | `CHATTER_START_DYE_STATION` # 800
--- | `CHATTER_START_ENDLESS_DUNGEON_BUFF_SELECTOR` # 4800
--- | `CHATTER_START_FISH` # 3200
--- | `CHATTER_START_GIVE_ITEM` # 400
--- | `CHATTER_START_GRAVEYARD_TRAVEL` # 2400
--- | `CHATTER_START_GUILDBANK` # 3300
--- | `CHATTER_START_GUILDKIOSK_BID` # 3800
--- | `CHATTER_START_GUILDKIOSK_PURCHASE` # 3900
--- | `CHATTER_START_HARVEST` # 3000
--- | `CHATTER_START_HIDEYHOLE` # 4300
--- | `CHATTER_START_KEEP` # 2000
--- | `CHATTER_START_KEEP_GUILD_CLAIM` # 2600
--- | `CHATTER_START_KEEP_GUILD_RELEASE` # 3500
--- | `CHATTER_START_KEEP_PIECE` # 1000
--- | `CHATTER_START_KEEP_TRAVEL` # 2100
--- | `CHATTER_START_LOCK` # 2800
--- | `CHATTER_START_LOOT` # 700
--- | `CHATTER_START_MAIL` # 900
--- | `CHATTER_START_NEW_QUEST_BESTOWAL` # 200
--- | `CHATTER_START_PAY_BOUNTY` # 500
--- | `CHATTER_START_PICKPOCKET` # 4100
--- | `CHATTER_START_REPAIR_ALL` # 4200
--- | `CHATTER_START_RETRAIT` # 4700
--- | `CHATTER_START_SHOP` # 600
--- | `CHATTER_START_SIEGE` # 1100
--- | `CHATTER_START_SKILL_RESPEC` # 4720
--- | `CHATTER_START_STABLE` # 3100
--- | `CHATTER_START_TALK` # 100
--- | `CHATTER_START_TRADINGHOUSE` # 3400
--- | `CHATTER_START_TREASURE_MAP` # 4740
--- | `CHATTER_START_TRIBUTE` # 4790
--- | `CHATTER_START_USE_CLEMENCY` # 4400
--- | `CHATTER_START_USE_FURNITURE` # 4600
--- | `CHATTER_START_USE_SHADOWY_CONNECTIONS` # 4500
--- | `CHATTER_TALK_CHOICE` # 101
--- | `CHATTER_TALK_CHOICE_ATTRIBUTE_RESPEC` # 112
--- | `CHATTER_TALK_CHOICE_BEGIN_SKILL_RESPEC` # 111
--- | `CHATTER_TALK_CHOICE_CLEMENCY_COOLDOWN` # 108
--- | `CHATTER_TALK_CHOICE_CLEMENCY_DISABLED` # 107
--- | `CHATTER_TALK_CHOICE_INTIMIDATE_DISABLED` # 103
--- | `CHATTER_TALK_CHOICE_MONEY` # 102
--- | `CHATTER_TALK_CHOICE_PAY_BOUNTY` # 105
--- | `CHATTER_TALK_CHOICE_PERSUADE_DISABLED` # 104
--- | `CHATTER_TALK_CHOICE_SHADOWY_CONNECTIONS_UNAVAILABLE` # 110
--- | `CHATTER_TALK_CHOICE_USE_CLEMENCY` # 106
--- | `CHATTER_TALK_CHOICE_USE_SHADOWY_CONNECTIONS` # 109
--- | `CHATTER_USE_COLLECTIBLE_ON_COMPANION` # 4771

CHATTER_ACCEPT_QUEST_BESTOWAL = 202
CHATTER_ADVANCE_COMPLETABLE_QUEST_CONDITIONS_COMPLETE = 4001
CHATTER_BEGIN = 1
CHATTER_BEGIN_INTERACT_NODE = 4
CHATTER_COMPLETE_ANTIQUITY_DIGGING = 4751
CHATTER_COMPLETE_ANTIQUITY_SCRYING = 4761
CHATTER_COMPLETE_QUEST_CONFIRM = 302
CHATTER_COMPLETE_QUEST_DIALOG = 301
CHATTER_CONFIRM_BUY_BAG_SPACE = 1602
CHATTER_CONFIRM_BUY_BANK_SPACE = 1201
CHATTER_CONTROL_SIEGE = 1103
CHATTER_CRAFT_ITEM = 2902
CHATTER_DECONSTRUCT_ITEM = 2903
CHATTER_DESTROY_SIEGE = 1101
CHATTER_DO_KEEP_GUILD_CLAIM = 2602
CHATTER_DO_KEEP_GUILD_RELEASE = 3502
CHATTER_ENDLESS_DUNGEON_BUFF_SELECTOR_CHOICE = 4801
CHATTER_END_ADVANCE_COMPLETABLE_QUEST_CONDITIONS = 4099
CHATTER_END_ANTIQUITY_DIG_SPOT = 4759
CHATTER_END_ANTIQUITY_SCRYING = 4769
CHATTER_END_ARMORY = 4789
CHATTER_END_ATTRIBUTE_RESPEC = 4739
CHATTER_END_BANK = 1299
CHATTER_END_BOOK = 2599
CHATTER_END_BUY_BAG_SPACE = 1699
CHATTER_END_COMPANION_MENU = 4779
CHATTER_END_COMPLETE_QUEST = 399
CHATTER_END_CRAFT = 2999
CHATTER_END_DOOR = 2799
CHATTER_END_DYE_STATION = 899
CHATTER_END_ENDLESS_DUNGEON_BUFF_SELECTOR = 4809
CHATTER_END_FISH = 3299
CHATTER_END_GIVE_ITEM = 499
CHATTER_END_GRAVEYARD_TRAVEL = 2499
CHATTER_END_GUILDBANK = 3399
CHATTER_END_GUILDKIOSK_BID = 3899
CHATTER_END_GUILDKIOSK_PURCHASE = 3999
CHATTER_END_HARVEST = 3099
CHATTER_END_HIDEYHOLE = 4399
CHATTER_END_KEEP = 2099
CHATTER_END_KEEP_GUILD_CLAIM = 2699
CHATTER_END_KEEP_GUILD_RELEASE = 3599
CHATTER_END_KEEP_PIECE = 1099
CHATTER_END_KEEP_TRAVEL = 2199
CHATTER_END_LOCK = 2899
CHATTER_END_LOOT = 799
CHATTER_END_MAIL = 999
CHATTER_END_NEW_QUEST_BESTOWAL = 299
CHATTER_END_PAY_BOUNTY = 599
CHATTER_END_PICKPOCKET = 4199
CHATTER_END_REPAIR_ALL = 4299
CHATTER_END_RETRAIT = 4719
CHATTER_END_SHOP = 699
CHATTER_END_SIEGE = 1199
CHATTER_END_SKILL_RESPEC = 4729
CHATTER_END_STABLE = 3199
CHATTER_END_TALK = 199
CHATTER_END_TRADINGHOUSE = 3499
CHATTER_END_TREASURE_MAP = 4749
CHATTER_END_TRIBUTE = 4799
CHATTER_END_USE_CLEMENCY = 4499
CHATTER_END_USE_FURNITURE = 4609
CHATTER_END_USE_SHADOWY_CONNECTIONS = 4509
CHATTER_EXIT_HIDEYHOLE = 4301
CHATTER_FEED_MOUNT = 3102
CHATTER_FISH_BITE = 3202
CHATTER_FISH_NIBBLE = 3203
CHATTER_FISH_REEL_IN = 3201
CHATTER_FORCE_LOCK = 2802
CHATTER_GIVE_ITEM_COMPLETE = 401
CHATTER_GOODBYE = 10000
CHATTER_GUILDKIOSK_IN_TRANSITION = 3902
CHATTER_IMPROVE_ITEM = 2905
CHATTER_INVALID = 0
CHATTER_LOCK_PICK_BROKEN = 2804
CHATTER_LOOT_ADD_RADIUS_TARGET = 704
CHATTER_LOOT_ALL = 701
CHATTER_LOOT_ALL_NON_STOLEN = 702
CHATTER_LOOT_ITEM = 703
CHATTER_LOOT_REMOVE_RADIUS_TARGET = 705
CHATTER_LOOT_UPDATE = 707
CHATTER_OFFER_QUEST_BESTOWAL = 201
CHATTER_OPEN_GUILDBANK = 3301
CHATTER_OPEN_MAIL = 901
CHATTER_OPEN_SKILL_RESPEC = 4721
CHATTER_OPEN_TRADINGHOUSE = 3401
CHATTER_PACKUP_SIEGE = 1104
CHATTER_PICK_LOCK = 2803
CHATTER_PLACE_GUILDKIOSK_BID = 3801
CHATTER_PROMPT_BUY_BAG_SPACE = 1601
CHATTER_PROMPT_CRAFT = 2901
CHATTER_PROMPT_DYE_STATION = 801
CHATTER_PROMPT_LOCK = 2801
CHATTER_PROMPT_RETRAIT = 4701
CHATTER_PURCHASE_GUILDKIOSK = 3901
CHATTER_REPAIR_SIEGE = 1102
CHATTER_RESEARCH_ITEM = 2904
CHATTER_RESET = 2
CHATTER_RESET_DURATION = 3
CHATTER_SHOW_BOOK = 2501
CHATTER_SHOW_GRAVEYARD_TRAVEL = 2401
CHATTER_SHOW_KEEP_GUILD_CLAIM = 2601
CHATTER_SHOW_KEEP_GUILD_RELEASE = 3501
CHATTER_SHOW_KEEP_TRAVEL = 2101
CHATTER_SHOW_TREASURE_MAP = 4741
CHATTER_START_ADVANCE_COMPLETABLE_QUEST_CONDITIONS = 4000
CHATTER_START_ANTIQUITY_DIG_SPOT = 4750
CHATTER_START_ANTIQUITY_SCRYING = 4760
CHATTER_START_ARMORY = 4780
CHATTER_START_ATTRIBUTE_RESPEC = 4730
CHATTER_START_BANK = 1200
CHATTER_START_BOOK = 2500
CHATTER_START_BUY_BAG_SPACE = 1600
CHATTER_START_COMPANION_MENU = 4770
CHATTER_START_COMPLETE_QUEST = 300
CHATTER_START_CRAFT = 2900
CHATTER_START_DOOR = 2700
CHATTER_START_DYE_STATION = 800
CHATTER_START_ENDLESS_DUNGEON_BUFF_SELECTOR = 4800
CHATTER_START_FISH = 3200
CHATTER_START_GIVE_ITEM = 400
CHATTER_START_GRAVEYARD_TRAVEL = 2400
CHATTER_START_GUILDBANK = 3300
CHATTER_START_GUILDKIOSK_BID = 3800
CHATTER_START_GUILDKIOSK_PURCHASE = 3900
CHATTER_START_HARVEST = 3000
CHATTER_START_HIDEYHOLE = 4300
CHATTER_START_KEEP = 2000
CHATTER_START_KEEP_GUILD_CLAIM = 2600
CHATTER_START_KEEP_GUILD_RELEASE = 3500
CHATTER_START_KEEP_PIECE = 1000
CHATTER_START_KEEP_TRAVEL = 2100
CHATTER_START_LOCK = 2800
CHATTER_START_LOOT = 700
CHATTER_START_MAIL = 900
CHATTER_START_NEW_QUEST_BESTOWAL = 200
CHATTER_START_PAY_BOUNTY = 500
CHATTER_START_PICKPOCKET = 4100
CHATTER_START_REPAIR_ALL = 4200
CHATTER_START_RETRAIT = 4700
CHATTER_START_SHOP = 600
CHATTER_START_SIEGE = 1100
CHATTER_START_SKILL_RESPEC = 4720
CHATTER_START_STABLE = 3100
CHATTER_START_TALK = 100
CHATTER_START_TRADINGHOUSE = 3400
CHATTER_START_TREASURE_MAP = 4740
CHATTER_START_TRIBUTE = 4790
CHATTER_START_USE_CLEMENCY = 4400
CHATTER_START_USE_FURNITURE = 4600
CHATTER_START_USE_SHADOWY_CONNECTIONS = 4500
CHATTER_TALK_CHOICE = 101
CHATTER_TALK_CHOICE_ATTRIBUTE_RESPEC = 112
CHATTER_TALK_CHOICE_BEGIN_SKILL_RESPEC = 111
CHATTER_TALK_CHOICE_CLEMENCY_COOLDOWN = 108
CHATTER_TALK_CHOICE_CLEMENCY_DISABLED = 107
CHATTER_TALK_CHOICE_INTIMIDATE_DISABLED = 103
CHATTER_TALK_CHOICE_MONEY = 102
CHATTER_TALK_CHOICE_PAY_BOUNTY = 105
CHATTER_TALK_CHOICE_PERSUADE_DISABLED = 104
CHATTER_TALK_CHOICE_SHADOWY_CONNECTIONS_UNAVAILABLE = 110
CHATTER_TALK_CHOICE_USE_CLEMENCY = 106
CHATTER_TALK_CHOICE_USE_SHADOWY_CONNECTIONS = 109
CHATTER_USE_COLLECTIBLE_ON_COMPANION = 4771
