--- @meta InterActiveWheelType

--- @alias InterActiveWheelType integer
--- | `ZO_INTERACTIVE_WHEEL_TYPE_UTILITY` # 1
--- | `ZO_INTERACTIVE_WHEEL_TYPE_FISHING` # 2
--- | `ZO_INTERACTIVE_WHEEL_TYPE_TARGET_MARKER` # 3

ZO_INTERACTIVE_WHEEL_TYPE_UTILITY = 1
ZO_INTERACTIVE_WHEEL_TYPE_FISHING = 2
ZO_INTERACTIVE_WHEEL_TYPE_TARGET_MARKER = 3
