--- @meta InterfaceColorType

--- @alias InterfaceColorType integer
--- | `INTERFACE_COLOR_TYPE_ABILITY_TOOLTIP` # 3
--- | `INTERFACE_COLOR_TYPE_ACTIVE_COMBAT_TIP` # 36
--- | `INTERFACE_COLOR_TYPE_ALLIANCE` # 25
--- | `INTERFACE_COLOR_TYPE_ANTIQUITY_DIGGING` # 54
--- | `INTERFACE_COLOR_TYPE_ANTIQUITY_QUALITY_COLORS` # 52
--- | `INTERFACE_COLOR_TYPE_ATTRIBUTE_TOOLTIP` # 23
--- | `INTERFACE_COLOR_TYPE_ATTRIBUTE_UPGRADE_PROJECTED` # 34
--- | `INTERFACE_COLOR_TYPE_BATTLEGROUND_TEAM` # 49
--- | `INTERFACE_COLOR_TYPE_BOOK_MEDIUM` # 28
--- | `INTERFACE_COLOR_TYPE_BUFF_TYPE` # 19
--- | `INTERFACE_COLOR_TYPE_CAST_BAR_END` # 8
--- | `INTERFACE_COLOR_TYPE_CAST_BAR_START` # 7
--- | `INTERFACE_COLOR_TYPE_CHAT_CHANNEL_CATEGORY_DEFAULTS` # 24
--- | `INTERFACE_COLOR_TYPE_CON_COLORS` # 12
--- | `INTERFACE_COLOR_TYPE_CURRENCY` # 21
--- | `INTERFACE_COLOR_TYPE_DEATH_INTERFACE_COLORS` # 47
--- | `INTERFACE_COLOR_TYPE_DEFAULT_COLOR` # 0
--- | `INTERFACE_COLOR_TYPE_FINESSE` # 38
--- | `INTERFACE_COLOR_TYPE_GAMEPAD_TOOLTIP` # 14
--- | `INTERFACE_COLOR_TYPE_GENERAL` # 9
--- | `INTERFACE_COLOR_TYPE_ITEM_QUALITY_COLORS` # 1
--- | `INTERFACE_COLOR_TYPE_ITEM_TOOLTIP` # 2
--- | `INTERFACE_COLOR_TYPE_KEEP_TOOLTIP` # 26
--- | `INTERFACE_COLOR_TYPE_LEADERBOARD_COLORS` # 44
--- | `INTERFACE_COLOR_TYPE_LEVEL_UP` # 37
--- | `INTERFACE_COLOR_TYPE_LINK` # 22
--- | `INTERFACE_COLOR_TYPE_LOADING_SCREEN` # 29
--- | `INTERFACE_COLOR_TYPE_MAPPIN_TOOLTIP` # 4
--- | `INTERFACE_COLOR_TYPE_MAP_PIN` # 53
--- | `INTERFACE_COLOR_TYPE_MARKET_COLORS` # 46
--- | `INTERFACE_COLOR_TYPE_NAME_PLATE` # 6
--- | `INTERFACE_COLOR_TYPE_NAME_PLATE_EFFECT_VISUAL_END` # 58
--- | `INTERFACE_COLOR_TYPE_NAME_PLATE_EFFECT_VISUAL_START` # 57
--- | `INTERFACE_COLOR_TYPE_NAME_PLATE_HEALTH_END` # 42
--- | `INTERFACE_COLOR_TYPE_NAME_PLATE_HEALTH_START` # 41
--- | `INTERFACE_COLOR_TYPE_NAME_PLATE_HIT_INDICATOR` # 43
--- | `INTERFACE_COLOR_TYPE_OBJECT_NOTIFICATION` # 16
--- | `INTERFACE_COLOR_TYPE_POWER` # 48
--- | `INTERFACE_COLOR_TYPE_POWER_END` # 31
--- | `INTERFACE_COLOR_TYPE_POWER_FADE_IN` # 32
--- | `INTERFACE_COLOR_TYPE_POWER_FADE_OUT` # 33
--- | `INTERFACE_COLOR_TYPE_POWER_START` # 30
--- | `INTERFACE_COLOR_TYPE_PROGRESSION` # 39
--- | `INTERFACE_COLOR_TYPE_SHARED_TOOLTIP` # 18
--- | `INTERFACE_COLOR_TYPE_SKILLS_ADVISOR` # 51
--- | `INTERFACE_COLOR_TYPE_SKILL_LINE_TOOLTIP` # 17
--- | `INTERFACE_COLOR_TYPE_STATUS_EFFECT` # 27
--- | `INTERFACE_COLOR_TYPE_STAT_VALUE` # 20
--- | `INTERFACE_COLOR_TYPE_TEXT_COLORS` # 13
--- | `INTERFACE_COLOR_TYPE_TRIBUTE_RESOURCE` # 55
--- | `INTERFACE_COLOR_TYPE_TRIBUTE_TIER` # 56
--- | `INTERFACE_COLOR_TYPE_ULTIMATE_BAR` # 35
--- | `INTERFACE_COLOR_TYPE_UNIT_CLASS` # 11
--- | `INTERFACE_COLOR_TYPE_UNIT_HIGHLIGHT_OVERRIDE` # 50
--- | `INTERFACE_COLOR_TYPE_UNIT_REACTION_COLOR` # 5
--- | `INTERFACE_COLOR_TYPE_VOICE_CHAT_COLORS` # 45

INTERFACE_COLOR_TYPE_ABILITY_TOOLTIP = 3
INTERFACE_COLOR_TYPE_ACTIVE_COMBAT_TIP = 36
INTERFACE_COLOR_TYPE_ALLIANCE = 25
INTERFACE_COLOR_TYPE_ANTIQUITY_DIGGING = 54
INTERFACE_COLOR_TYPE_ANTIQUITY_QUALITY_COLORS = 52
INTERFACE_COLOR_TYPE_ATTRIBUTE_TOOLTIP = 23
INTERFACE_COLOR_TYPE_ATTRIBUTE_UPGRADE_PROJECTED = 34
INTERFACE_COLOR_TYPE_BATTLEGROUND_TEAM = 49
INTERFACE_COLOR_TYPE_BOOK_MEDIUM = 28
INTERFACE_COLOR_TYPE_BUFF_TYPE = 19
INTERFACE_COLOR_TYPE_CAST_BAR_END = 8
INTERFACE_COLOR_TYPE_CAST_BAR_START = 7
INTERFACE_COLOR_TYPE_CHAT_CHANNEL_CATEGORY_DEFAULTS = 24
INTERFACE_COLOR_TYPE_CON_COLORS = 12
INTERFACE_COLOR_TYPE_CURRENCY = 21
INTERFACE_COLOR_TYPE_DEATH_INTERFACE_COLORS = 47
INTERFACE_COLOR_TYPE_DEFAULT_COLOR = 0
INTERFACE_COLOR_TYPE_FINESSE = 38
INTERFACE_COLOR_TYPE_GAMEPAD_TOOLTIP = 14
INTERFACE_COLOR_TYPE_GENERAL = 9
INTERFACE_COLOR_TYPE_ITEM_QUALITY_COLORS = 1
INTERFACE_COLOR_TYPE_ITEM_TOOLTIP = 2
INTERFACE_COLOR_TYPE_KEEP_TOOLTIP = 26
INTERFACE_COLOR_TYPE_LEADERBOARD_COLORS = 44
INTERFACE_COLOR_TYPE_LEVEL_UP = 37
INTERFACE_COLOR_TYPE_LINK = 22
INTERFACE_COLOR_TYPE_LOADING_SCREEN = 29
INTERFACE_COLOR_TYPE_MAPPIN_TOOLTIP = 4
INTERFACE_COLOR_TYPE_MAP_PIN = 53
INTERFACE_COLOR_TYPE_MARKET_COLORS = 46
INTERFACE_COLOR_TYPE_NAME_PLATE = 6
INTERFACE_COLOR_TYPE_NAME_PLATE_EFFECT_VISUAL_END = 58
INTERFACE_COLOR_TYPE_NAME_PLATE_EFFECT_VISUAL_START = 57
INTERFACE_COLOR_TYPE_NAME_PLATE_HEALTH_END = 42
INTERFACE_COLOR_TYPE_NAME_PLATE_HEALTH_START = 41
INTERFACE_COLOR_TYPE_NAME_PLATE_HIT_INDICATOR = 43
INTERFACE_COLOR_TYPE_OBJECT_NOTIFICATION = 16
INTERFACE_COLOR_TYPE_POWER = 48
INTERFACE_COLOR_TYPE_POWER_END = 31
INTERFACE_COLOR_TYPE_POWER_FADE_IN = 32
INTERFACE_COLOR_TYPE_POWER_FADE_OUT = 33
INTERFACE_COLOR_TYPE_POWER_START = 30
INTERFACE_COLOR_TYPE_PROGRESSION = 39
INTERFACE_COLOR_TYPE_SHARED_TOOLTIP = 18
INTERFACE_COLOR_TYPE_SKILLS_ADVISOR = 51
INTERFACE_COLOR_TYPE_SKILL_LINE_TOOLTIP = 17
INTERFACE_COLOR_TYPE_STATUS_EFFECT = 27
INTERFACE_COLOR_TYPE_STAT_VALUE = 20
INTERFACE_COLOR_TYPE_TEXT_COLORS = 13
INTERFACE_COLOR_TYPE_TRIBUTE_RESOURCE = 55
INTERFACE_COLOR_TYPE_TRIBUTE_TIER = 56
INTERFACE_COLOR_TYPE_ULTIMATE_BAR = 35
INTERFACE_COLOR_TYPE_UNIT_CLASS = 11
INTERFACE_COLOR_TYPE_UNIT_HIGHLIGHT_OVERRIDE = 50
INTERFACE_COLOR_TYPE_UNIT_REACTION_COLOR = 5
INTERFACE_COLOR_TYPE_VOICE_CHAT_COLORS = 45
