--- @meta InterfaceTextColor

--- @alias InterfaceTextColor integer
--- | `INTERFACE_TEXT_COLOR_ANNOUNCEMENTS` # 26
--- | `INTERFACE_TEXT_COLOR_BATTLEGROUND_WINNER` # 25
--- | `INTERFACE_TEXT_COLOR_BLADE` # 5
--- | `INTERFACE_TEXT_COLOR_BLADE_HIGHLIGHT` # 6
--- | `INTERFACE_TEXT_COLOR_BODY` # 4
--- | `INTERFACE_TEXT_COLOR_CHATTER_NPC` # 13
--- | `INTERFACE_TEXT_COLOR_CHATTER_PLAYER_OPTION` # 14
--- | `INTERFACE_TEXT_COLOR_CONTEXT_HIGHLIGHT` # 9
--- | `INTERFACE_TEXT_COLOR_CONTRAST` # 15
--- | `INTERFACE_TEXT_COLOR_CURRENCY_HIGHLIGHT` # 23
--- | `INTERFACE_TEXT_COLOR_DEFAULT_TEXT` # 19
--- | `INTERFACE_TEXT_COLOR_DISABLED` # 2
--- | `INTERFACE_TEXT_COLOR_FAILED` # 11
--- | `INTERFACE_TEXT_COLOR_GAMEPAD_CATEGORY_HEADER` # 21
--- | `INTERFACE_TEXT_COLOR_GAMEPAD_TERTIARY` # 22
--- | `INTERFACE_TEXT_COLOR_GAME_REPRESENTATIVE` # 20
--- | `INTERFACE_TEXT_COLOR_HIGHLIGHT` # 0
--- | `INTERFACE_TEXT_COLOR_HINT` # 12
--- | `INTERFACE_TEXT_COLOR_NORMAL` # 1
--- | `INTERFACE_TEXT_COLOR_PERSONALITY_EMOTES` # 24
--- | `INTERFACE_TEXT_COLOR_SECOND_CONTRAST` # 16
--- | `INTERFACE_TEXT_COLOR_SECOND_NORMAL` # 28
--- | `INTERFACE_TEXT_COLOR_SECOND_SELECTED` # 27
--- | `INTERFACE_TEXT_COLOR_SELECTED` # 3
--- | `INTERFACE_TEXT_COLOR_SUBTLE` # 17
--- | `INTERFACE_TEXT_COLOR_SUCCEEDED` # 10
--- | `INTERFACE_TEXT_COLOR_TOOLTIP_DEFAULT` # 7
--- | `INTERFACE_TEXT_COLOR_TOOLTIP_INSTRUCTIONAL` # 8
--- | `INTERFACE_TEXT_COLOR_VALUE` # 18

INTERFACE_TEXT_COLOR_ANNOUNCEMENTS = 26
INTERFACE_TEXT_COLOR_BATTLEGROUND_WINNER = 25
INTERFACE_TEXT_COLOR_BLADE = 5
INTERFACE_TEXT_COLOR_BLADE_HIGHLIGHT = 6
INTERFACE_TEXT_COLOR_BODY = 4
INTERFACE_TEXT_COLOR_CHATTER_NPC = 13
INTERFACE_TEXT_COLOR_CHATTER_PLAYER_OPTION = 14
INTERFACE_TEXT_COLOR_CONTEXT_HIGHLIGHT = 9
INTERFACE_TEXT_COLOR_CONTRAST = 15
INTERFACE_TEXT_COLOR_CURRENCY_HIGHLIGHT = 23
INTERFACE_TEXT_COLOR_DEFAULT_TEXT = 19
INTERFACE_TEXT_COLOR_DISABLED = 2
INTERFACE_TEXT_COLOR_FAILED = 11
INTERFACE_TEXT_COLOR_GAMEPAD_CATEGORY_HEADER = 21
INTERFACE_TEXT_COLOR_GAMEPAD_TERTIARY = 22
INTERFACE_TEXT_COLOR_GAME_REPRESENTATIVE = 20
INTERFACE_TEXT_COLOR_HIGHLIGHT = 0
INTERFACE_TEXT_COLOR_HINT = 12
INTERFACE_TEXT_COLOR_NORMAL = 1
INTERFACE_TEXT_COLOR_PERSONALITY_EMOTES = 24
INTERFACE_TEXT_COLOR_SECOND_CONTRAST = 16
INTERFACE_TEXT_COLOR_SECOND_NORMAL = 28
INTERFACE_TEXT_COLOR_SECOND_SELECTED = 27
INTERFACE_TEXT_COLOR_SELECTED = 3
INTERFACE_TEXT_COLOR_SUBTLE = 17
INTERFACE_TEXT_COLOR_SUCCEEDED = 10
INTERFACE_TEXT_COLOR_TOOLTIP_DEFAULT = 7
INTERFACE_TEXT_COLOR_TOOLTIP_INSTRUCTIONAL = 8
INTERFACE_TEXT_COLOR_VALUE = 18
