--- @meta InventoryCountBagOption

--- @alias InventoryCountBagOption integer
--- | `INVENTORY_COUNT_BAG_OPTION_BACKPACK` # 1
--- | `INVENTORY_COUNT_BAG_OPTION_BACKPACK_AND_BANK` # 5
--- | `INVENTORY_COUNT_BAG_OPTION_BACKPACK_AND_BANK_AND_CRAFT_BAG` # 21
--- | `INVENTORY_COUNT_BAG_OPTION_BACKPACK_AND_CRAFT_BAG` # 17
--- | `INVENTORY_COUNT_BAG_OPTION_BACKPACK_AND_WORN` # 3
--- | `INVENTORY_COUNT_BAG_OPTION_BANK` # 4
--- | `INVENTORY_COUNT_BAG_OPTION_CRAFT_BAG` # 16
--- | `INVENTORY_COUNT_BAG_OPTION_GUILD_BANK` # 8
--- | `INVENTORY_COUNT_BAG_OPTION_HOUSE_BANKS` # 32736
--- | `INVENTORY_COUNT_BAG_OPTION_HOUSE_BANK_EIGHT` # 4096
--- | `INVENTORY_COUNT_BAG_OPTION_HOUSE_BANK_FIVE` # 512
--- | `INVENTORY_COUNT_BAG_OPTION_HOUSE_BANK_FOUR` # 256
--- | `INVENTORY_COUNT_BAG_OPTION_HOUSE_BANK_NINE` # 8192
--- | `INVENTORY_COUNT_BAG_OPTION_HOUSE_BANK_ONE` # 32
--- | `INVENTORY_COUNT_BAG_OPTION_HOUSE_BANK_SEVEN` # 2048
--- | `INVENTORY_COUNT_BAG_OPTION_HOUSE_BANK_SIX` # 1024
--- | `INVENTORY_COUNT_BAG_OPTION_HOUSE_BANK_TEN` # 16384
--- | `INVENTORY_COUNT_BAG_OPTION_HOUSE_BANK_THREE` # 128
--- | `INVENTORY_COUNT_BAG_OPTION_HOUSE_BANK_TWO` # 64
--- | `INVENTORY_COUNT_BAG_OPTION_WORN` # 2

INVENTORY_COUNT_BAG_OPTION_BACKPACK = 1
INVENTORY_COUNT_BAG_OPTION_BACKPACK_AND_BANK = 5
INVENTORY_COUNT_BAG_OPTION_BACKPACK_AND_BANK_AND_CRAFT_BAG = 21
INVENTORY_COUNT_BAG_OPTION_BACKPACK_AND_CRAFT_BAG = 17
INVENTORY_COUNT_BAG_OPTION_BACKPACK_AND_WORN = 3
INVENTORY_COUNT_BAG_OPTION_BANK = 4
INVENTORY_COUNT_BAG_OPTION_CRAFT_BAG = 16
INVENTORY_COUNT_BAG_OPTION_GUILD_BANK = 8
INVENTORY_COUNT_BAG_OPTION_HOUSE_BANKS = 32736
INVENTORY_COUNT_BAG_OPTION_HOUSE_BANK_EIGHT = 4096
INVENTORY_COUNT_BAG_OPTION_HOUSE_BANK_FIVE = 512
INVENTORY_COUNT_BAG_OPTION_HOUSE_BANK_FOUR = 256
INVENTORY_COUNT_BAG_OPTION_HOUSE_BANK_NINE = 8192
INVENTORY_COUNT_BAG_OPTION_HOUSE_BANK_ONE = 32
INVENTORY_COUNT_BAG_OPTION_HOUSE_BANK_SEVEN = 2048
INVENTORY_COUNT_BAG_OPTION_HOUSE_BANK_SIX = 1024
INVENTORY_COUNT_BAG_OPTION_HOUSE_BANK_TEN = 16384
INVENTORY_COUNT_BAG_OPTION_HOUSE_BANK_THREE = 128
INVENTORY_COUNT_BAG_OPTION_HOUSE_BANK_TWO = 64
INVENTORY_COUNT_BAG_OPTION_WORN = 2
