--- @meta InventoryUpdateReason

--- @alias InventoryUpdateReason integer
--- | `INVENTORY_UPDATE_REASON_ARMORY_BUILD_CHANGED` # 5
--- | `INVENTORY_UPDATE_REASON_DEFAULT` # 0
--- | `INVENTORY_UPDATE_REASON_DURABILITY_CHANGE` # 1
--- | `INVENTORY_UPDATE_REASON_DYE_CHANGE` # 2
--- | `INVENTORY_UPDATE_REASON_ITEM_CHARGE` # 3
--- | `INVENTORY_UPDATE_REASON_PLAYER_LOCKED` # 4

INVENTORY_UPDATE_REASON_ARMORY_BUILD_CHANGED = 5
INVENTORY_UPDATE_REASON_DEFAULT = 0
INVENTORY_UPDATE_REASON_DURABILITY_CHANGE = 1
INVENTORY_UPDATE_REASON_DYE_CHANGE = 2
INVENTORY_UPDATE_REASON_ITEM_CHARGE = 3
INVENTORY_UPDATE_REASON_PLAYER_LOCKED = 4
