--- @meta InWorldUISetting

--- @alias InWorldUISetting integer
--- | `IN_WORLD_UI_SETTING_COMPANION_PASSENGER_PREFERENCE` # 14
--- | `IN_WORLD_UI_SETTING_COMPANION_REACTION_FREQUENCY` # 13
--- | `IN_WORLD_UI_SETTING_DEFAULT_SOUL_GEM` # 6
--- | `IN_WORLD_UI_SETTING_FOOT_INVERSE_KINEMATICS` # 12
--- | `IN_WORLD_UI_SETTING_GLOW_THICKNESS` # 4
--- | `IN_WORLD_UI_SETTING_HIDE_LOIN_CLOTH` # 10
--- | `IN_WORLD_UI_SETTING_HIDE_MOUNT_INVENTORY_UPGRADE` # 9
--- | `IN_WORLD_UI_SETTING_HIDE_MOUNT_SPEED_UPGRADE` # 8
--- | `IN_WORLD_UI_SETTING_HIDE_MOUNT_STAMINA_UPGRADE` # 7
--- | `IN_WORLD_UI_SETTING_HIDE_POLYMORPH_HELM` # 5
--- | `IN_WORLD_UI_SETTING_HIDE_TASSETS` # 11
--- | `IN_WORLD_UI_SETTING_INTERACTABLE_GLOW_ENABLED` # 2
--- | `IN_WORLD_UI_SETTING_INTERACTABLE_GLOW_INTENSITY` # 3
--- | `IN_WORLD_UI_SETTING_LIMIT_FOLLOWERS_IN_TOWNS` # 15
--- | `IN_WORLD_UI_SETTING_TARGET_GLOW_ENABLED` # 0
--- | `IN_WORLD_UI_SETTING_TARGET_GLOW_INTENSITY` # 1
--- | `IN_WORLD_UI_SETTING_TARGET_MARKER_SIZE` # 16

IN_WORLD_UI_SETTING_COMPANION_PASSENGER_PREFERENCE = 14
IN_WORLD_UI_SETTING_COMPANION_REACTION_FREQUENCY = 13
IN_WORLD_UI_SETTING_DEFAULT_SOUL_GEM = 6
IN_WORLD_UI_SETTING_FOOT_INVERSE_KINEMATICS = 12
IN_WORLD_UI_SETTING_GLOW_THICKNESS = 4
IN_WORLD_UI_SETTING_HIDE_LOIN_CLOTH = 10
IN_WORLD_UI_SETTING_HIDE_MOUNT_INVENTORY_UPGRADE = 9
IN_WORLD_UI_SETTING_HIDE_MOUNT_SPEED_UPGRADE = 8
IN_WORLD_UI_SETTING_HIDE_MOUNT_STAMINA_UPGRADE = 7
IN_WORLD_UI_SETTING_HIDE_POLYMORPH_HELM = 5
IN_WORLD_UI_SETTING_HIDE_TASSETS = 11
IN_WORLD_UI_SETTING_INTERACTABLE_GLOW_ENABLED = 2
IN_WORLD_UI_SETTING_INTERACTABLE_GLOW_INTENSITY = 3
IN_WORLD_UI_SETTING_LIMIT_FOLLOWERS_IN_TOWNS = 15
IN_WORLD_UI_SETTING_TARGET_GLOW_ENABLED = 0
IN_WORLD_UI_SETTING_TARGET_GLOW_INTENSITY = 1
IN_WORLD_UI_SETTING_TARGET_MARKER_SIZE = 16
