--- @meta ItemSetBonusRules

--- @alias ItemSetBonusRules integer
--- | `ITEM_SET_BONUS_RULES_DISABLED` # 2
--- | `ITEM_SET_BONUS_RULES_ENABLED` # 0
--- | `ITEM_SET_BONUS_RULES_NO_PROC` # 1

ITEM_SET_BONUS_RULES_DISABLED = 2
ITEM_SET_BONUS_RULES_ENABLED = 0
ITEM_SET_BONUS_RULES_NO_PROC = 1
