--- @meta ItemVisualDamage

--- @alias ItemVisualDamage integer
--- | `ITEMVISUALDAMAGE_BROKEN` # 2
--- | `ITEMVISUALDAMAGE_DAMAGED` # 1
--- | `ITEMVISUALDAMAGE_NONE` # 0

ITEMVISUALDAMAGE_BROKEN = 2
ITEMVISUALDAMAGE_DAMAGED = 1
ITEMVISUALDAMAGE_NONE = 0
