--- @meta ItemUISoundAction

--- @alias ItemUISoundAction integer
--- | `ITEM_SOUND_ACTION_ACQUIRE` # 0
--- | `ITEM_SOUND_ACTION_CRAFTED` # 7
--- | `ITEM_SOUND_ACTION_DESTROY` # 3
--- | `ITEM_SOUND_ACTION_EQUIP` # 1
--- | `ITEM_SOUND_ACTION_PICKUP` # 6
--- | `ITEM_SOUND_ACTION_SLOT` # 1
--- | `ITEM_SOUND_ACTION_UNEQUIP` # 4
--- | `ITEM_SOUND_ACTION_USE` # 5

ITEM_SOUND_ACTION_ACQUIRE = 0
ITEM_SOUND_ACTION_CRAFTED = 7
ITEM_SOUND_ACTION_DESTROY = 3
ITEM_SOUND_ACTION_EQUIP = 1
ITEM_SOUND_ACTION_PICKUP = 6
ITEM_SOUND_ACTION_SLOT = 1
ITEM_SOUND_ACTION_UNEQUIP = 4
ITEM_SOUND_ACTION_USE = 5
