--- @meta ItemTraitType

--- @alias ItemTraitType integer
--- | `ITEM_TRAIT_TYPE_ARMOR_AGGRESSIVE` # 47
--- | `ITEM_TRAIT_TYPE_ARMOR_AUGMENTED` # 49
--- | `ITEM_TRAIT_TYPE_ARMOR_BOLSTERED` # 50
--- | `ITEM_TRAIT_TYPE_ARMOR_DIVINES` # 18
--- | `ITEM_TRAIT_TYPE_ARMOR_FOCUSED` # 45
--- | `ITEM_TRAIT_TYPE_ARMOR_IMPENETRABLE` # 12
--- | `ITEM_TRAIT_TYPE_ARMOR_INFUSED` # 16
--- | `ITEM_TRAIT_TYPE_ARMOR_INTRICATE` # 20
--- | `ITEM_TRAIT_TYPE_ARMOR_NIRNHONED` # 25
--- | `ITEM_TRAIT_TYPE_ARMOR_ORNATE` # 19
--- | `ITEM_TRAIT_TYPE_ARMOR_PROLIFIC` # 44
--- | `ITEM_TRAIT_TYPE_ARMOR_PROSPEROUS` # 17
--- | `ITEM_TRAIT_TYPE_ARMOR_QUICKENED` # 43
--- | `ITEM_TRAIT_TYPE_ARMOR_REINFORCED` # 13
--- | `ITEM_TRAIT_TYPE_ARMOR_SHATTERING` # 46
--- | `ITEM_TRAIT_TYPE_ARMOR_SOOTHING` # 48
--- | `ITEM_TRAIT_TYPE_ARMOR_STURDY` # 11
--- | `ITEM_TRAIT_TYPE_ARMOR_TRAINING` # 15
--- | `ITEM_TRAIT_TYPE_ARMOR_VIGOROUS` # 51
--- | `ITEM_TRAIT_TYPE_ARMOR_WELL_FITTED` # 14
--- | `ITEM_TRAIT_TYPE_JEWELRY_AGGRESSIVE` # 56
--- | `ITEM_TRAIT_TYPE_JEWELRY_ARCANE` # 22
--- | `ITEM_TRAIT_TYPE_JEWELRY_AUGMENTED` # 58
--- | `ITEM_TRAIT_TYPE_JEWELRY_BLOODTHIRSTY` # 31
--- | `ITEM_TRAIT_TYPE_JEWELRY_BOLSTERED` # 59
--- | `ITEM_TRAIT_TYPE_JEWELRY_FOCUSED` # 54
--- | `ITEM_TRAIT_TYPE_JEWELRY_HARMONY` # 29
--- | `ITEM_TRAIT_TYPE_JEWELRY_HEALTHY` # 21
--- | `ITEM_TRAIT_TYPE_JEWELRY_INFUSED` # 33
--- | `ITEM_TRAIT_TYPE_JEWELRY_INTRICATE` # 27
--- | `ITEM_TRAIT_TYPE_JEWELRY_ORNATE` # 24
--- | `ITEM_TRAIT_TYPE_JEWELRY_PROLIFIC` # 53
--- | `ITEM_TRAIT_TYPE_JEWELRY_PROTECTIVE` # 32
--- | `ITEM_TRAIT_TYPE_JEWELRY_QUICKENED` # 52
--- | `ITEM_TRAIT_TYPE_JEWELRY_ROBUST` # 23
--- | `ITEM_TRAIT_TYPE_JEWELRY_SHATTERING` # 55
--- | `ITEM_TRAIT_TYPE_JEWELRY_SOOTHING` # 57
--- | `ITEM_TRAIT_TYPE_JEWELRY_SWIFT` # 28
--- | `ITEM_TRAIT_TYPE_JEWELRY_TRIUNE` # 30
--- | `ITEM_TRAIT_TYPE_JEWELRY_VIGOROUS` # 60
--- | `ITEM_TRAIT_TYPE_NONE` # 0
--- | `ITEM_TRAIT_TYPE_WEAPON_AGGRESSIVE` # 38
--- | `ITEM_TRAIT_TYPE_WEAPON_AUGMENTED` # 40
--- | `ITEM_TRAIT_TYPE_WEAPON_BOLSTERED` # 41
--- | `ITEM_TRAIT_TYPE_WEAPON_CHARGED` # 2
--- | `ITEM_TRAIT_TYPE_WEAPON_DECISIVE` # 8
--- | `ITEM_TRAIT_TYPE_WEAPON_DEFENDING` # 5
--- | `ITEM_TRAIT_TYPE_WEAPON_FOCUSED` # 36
--- | `ITEM_TRAIT_TYPE_WEAPON_INFUSED` # 4
--- | `ITEM_TRAIT_TYPE_WEAPON_INTRICATE` # 9
--- | `ITEM_TRAIT_TYPE_WEAPON_NIRNHONED` # 26
--- | `ITEM_TRAIT_TYPE_WEAPON_ORNATE` # 10
--- | `ITEM_TRAIT_TYPE_WEAPON_POWERED` # 1
--- | `ITEM_TRAIT_TYPE_WEAPON_PRECISE` # 3
--- | `ITEM_TRAIT_TYPE_WEAPON_PROLIFIC` # 35
--- | `ITEM_TRAIT_TYPE_WEAPON_QUICKENED` # 34
--- | `ITEM_TRAIT_TYPE_WEAPON_SHARPENED` # 7
--- | `ITEM_TRAIT_TYPE_WEAPON_SHATTERING` # 37
--- | `ITEM_TRAIT_TYPE_WEAPON_SOOTHING` # 39
--- | `ITEM_TRAIT_TYPE_WEAPON_TRAINING` # 6
--- | `ITEM_TRAIT_TYPE_WEAPON_VIGOROUS` # 42

ITEM_TRAIT_TYPE_ARMOR_AGGRESSIVE = 47
ITEM_TRAIT_TYPE_ARMOR_AUGMENTED = 49
ITEM_TRAIT_TYPE_ARMOR_BOLSTERED = 50
ITEM_TRAIT_TYPE_ARMOR_DIVINES = 18
ITEM_TRAIT_TYPE_ARMOR_FOCUSED = 45
ITEM_TRAIT_TYPE_ARMOR_IMPENETRABLE = 12
ITEM_TRAIT_TYPE_ARMOR_INFUSED = 16
ITEM_TRAIT_TYPE_ARMOR_INTRICATE = 20
ITEM_TRAIT_TYPE_ARMOR_NIRNHONED = 25
ITEM_TRAIT_TYPE_ARMOR_ORNATE = 19
ITEM_TRAIT_TYPE_ARMOR_PROLIFIC = 44
ITEM_TRAIT_TYPE_ARMOR_PROSPEROUS = 17
ITEM_TRAIT_TYPE_ARMOR_QUICKENED = 43
ITEM_TRAIT_TYPE_ARMOR_REINFORCED = 13
ITEM_TRAIT_TYPE_ARMOR_SHATTERING = 46
ITEM_TRAIT_TYPE_ARMOR_SOOTHING = 48
ITEM_TRAIT_TYPE_ARMOR_STURDY = 11
ITEM_TRAIT_TYPE_ARMOR_TRAINING = 15
ITEM_TRAIT_TYPE_ARMOR_VIGOROUS = 51
ITEM_TRAIT_TYPE_ARMOR_WELL_FITTED = 14
ITEM_TRAIT_TYPE_JEWELRY_AGGRESSIVE = 56
ITEM_TRAIT_TYPE_JEWELRY_ARCANE = 22
ITEM_TRAIT_TYPE_JEWELRY_AUGMENTED = 58
ITEM_TRAIT_TYPE_JEWELRY_BLOODTHIRSTY = 31
ITEM_TRAIT_TYPE_JEWELRY_BOLSTERED = 59
ITEM_TRAIT_TYPE_JEWELRY_FOCUSED = 54
ITEM_TRAIT_TYPE_JEWELRY_HARMONY = 29
ITEM_TRAIT_TYPE_JEWELRY_HEALTHY = 21
ITEM_TRAIT_TYPE_JEWELRY_INFUSED = 33
ITEM_TRAIT_TYPE_JEWELRY_INTRICATE = 27
ITEM_TRAIT_TYPE_JEWELRY_ORNATE = 24
ITEM_TRAIT_TYPE_JEWELRY_PROLIFIC = 53
ITEM_TRAIT_TYPE_JEWELRY_PROTECTIVE = 32
ITEM_TRAIT_TYPE_JEWELRY_QUICKENED = 52
ITEM_TRAIT_TYPE_JEWELRY_ROBUST = 23
ITEM_TRAIT_TYPE_JEWELRY_SHATTERING = 55
ITEM_TRAIT_TYPE_JEWELRY_SOOTHING = 57
ITEM_TRAIT_TYPE_JEWELRY_SWIFT = 28
ITEM_TRAIT_TYPE_JEWELRY_TRIUNE = 30
ITEM_TRAIT_TYPE_JEWELRY_VIGOROUS = 60
ITEM_TRAIT_TYPE_NONE = 0
ITEM_TRAIT_TYPE_WEAPON_AGGRESSIVE = 38
ITEM_TRAIT_TYPE_WEAPON_AUGMENTED = 40
ITEM_TRAIT_TYPE_WEAPON_BOLSTERED = 41
ITEM_TRAIT_TYPE_WEAPON_CHARGED = 2
ITEM_TRAIT_TYPE_WEAPON_DECISIVE = 8
ITEM_TRAIT_TYPE_WEAPON_DEFENDING = 5
ITEM_TRAIT_TYPE_WEAPON_FOCUSED = 36
ITEM_TRAIT_TYPE_WEAPON_INFUSED = 4
ITEM_TRAIT_TYPE_WEAPON_INTRICATE = 9
ITEM_TRAIT_TYPE_WEAPON_NIRNHONED = 26
ITEM_TRAIT_TYPE_WEAPON_ORNATE = 10
ITEM_TRAIT_TYPE_WEAPON_POWERED = 1
ITEM_TRAIT_TYPE_WEAPON_PRECISE = 3
ITEM_TRAIT_TYPE_WEAPON_PROLIFIC = 35
ITEM_TRAIT_TYPE_WEAPON_QUICKENED = 34
ITEM_TRAIT_TYPE_WEAPON_SHARPENED = 7
ITEM_TRAIT_TYPE_WEAPON_SHATTERING = 37
ITEM_TRAIT_TYPE_WEAPON_SOOTHING = 39
ITEM_TRAIT_TYPE_WEAPON_TRAINING = 6
ITEM_TRAIT_TYPE_WEAPON_VIGOROUS = 42
