--- @meta ItemTagCategory

--- @alias ItemTagCategory integer
--- | `TAG_CATEGORY_FURNITURE_BEHAVIOR` # 2
--- | `TAG_CATEGORY_NONE` # 0
--- | `TAG_CATEGORY_SOURCES` # 3
--- | `TAG_CATEGORY_TREASURE_TYPE` # 1

TAG_CATEGORY_FURNITURE_BEHAVIOR = 2
TAG_CATEGORY_NONE = 0
TAG_CATEGORY_SOURCES = 3
TAG_CATEGORY_TREASURE_TYPE = 1
