--- @meta ItemTraitTypeCategory

--- @alias ItemTraitTypeCategory integer
--- | `ITEM_TRAIT_TYPE_CATEGORY_ARMOR` # 2
--- | `ITEM_TRAIT_TYPE_CATEGORY_INVALID` # -1
--- | `ITEM_TRAIT_TYPE_CATEGORY_JEWELRY` # 3
--- | `ITEM_TRAIT_TYPE_CATEGORY_NONE` # 0
--- | `ITEM_TRAIT_TYPE_CATEGORY_WEAPON` # 1

ITEM_TRAIT_TYPE_CATEGORY_ARMOR = 2
ITEM_TRAIT_TYPE_CATEGORY_INVALID = -1
ITEM_TRAIT_TYPE_CATEGORY_JEWELRY = 3
ITEM_TRAIT_TYPE_CATEGORY_NONE = 0
ITEM_TRAIT_TYPE_CATEGORY_WEAPON = 1
