--- @meta ItemTypeDisplayCategory

--- @alias ItemTypeDisplayCategory integer
--- | `ITEM_TYPE_DISPLAY_CATEGORY_ALCHEMY` # 14
--- | `ITEM_TYPE_DISPLAY_CATEGORY_ALL` # 0
--- | `ITEM_TYPE_DISPLAY_CATEGORY_APPEARANCE` # 29
--- | `ITEM_TYPE_DISPLAY_CATEGORY_ARMOR` # 2
--- | `ITEM_TYPE_DISPLAY_CATEGORY_BLACKSMITHING` # 10
--- | `ITEM_TYPE_DISPLAY_CATEGORY_CLOTHING` # 11
--- | `ITEM_TYPE_DISPLAY_CATEGORY_COMPANION` # 41
--- | `ITEM_TYPE_DISPLAY_CATEGORY_CONSUMABLE` # 4
--- | `ITEM_TYPE_DISPLAY_CATEGORY_CONTAINER` # 26
--- | `ITEM_TYPE_DISPLAY_CATEGORY_CRAFTING` # 5
--- | `ITEM_TYPE_DISPLAY_CATEGORY_CROWN_ITEM` # 28
--- | `ITEM_TYPE_DISPLAY_CATEGORY_DRINK` # 20
--- | `ITEM_TYPE_DISPLAY_CATEGORY_DRINK_INGREDIENT` # 38
--- | `ITEM_TYPE_DISPLAY_CATEGORY_ENCHANTING` # 15
--- | `ITEM_TYPE_DISPLAY_CATEGORY_FOOD` # 19
--- | `ITEM_TYPE_DISPLAY_CATEGORY_FOOD_INGREDIENT` # 37
--- | `ITEM_TYPE_DISPLAY_CATEGORY_FURNISHING` # 6
--- | `ITEM_TYPE_DISPLAY_CATEGORY_FURNISHING_MATERIAL` # 40
--- | `ITEM_TYPE_DISPLAY_CATEGORY_GLYPH` # 30
--- | `ITEM_TYPE_DISPLAY_CATEGORY_JEWELRY` # 3
--- | `ITEM_TYPE_DISPLAY_CATEGORY_JEWELRYCRAFTING` # 13
--- | `ITEM_TYPE_DISPLAY_CATEGORY_JUNK` # 9
--- | `ITEM_TYPE_DISPLAY_CATEGORY_LURE` # 35
--- | `ITEM_TYPE_DISPLAY_CATEGORY_MASTER_WRIT` # 25
--- | `ITEM_TYPE_DISPLAY_CATEGORY_MISCELLANEOUS` # 7
--- | `ITEM_TYPE_DISPLAY_CATEGORY_POISON` # 23
--- | `ITEM_TYPE_DISPLAY_CATEGORY_POTION` # 22
--- | `ITEM_TYPE_DISPLAY_CATEGORY_PROVISIONING` # 16
--- | `ITEM_TYPE_DISPLAY_CATEGORY_QUEST` # 8
--- | `ITEM_TYPE_DISPLAY_CATEGORY_RARE_INGREDIENT` # 39
--- | `ITEM_TYPE_DISPLAY_CATEGORY_RECIPE` # 21
--- | `ITEM_TYPE_DISPLAY_CATEGORY_REPAIR_ITEM` # 27
--- | `ITEM_TYPE_DISPLAY_CATEGORY_SIEGE` # 32
--- | `ITEM_TYPE_DISPLAY_CATEGORY_SOUL_GEM` # 31
--- | `ITEM_TYPE_DISPLAY_CATEGORY_STYLE_MATERIAL` # 17
--- | `ITEM_TYPE_DISPLAY_CATEGORY_STYLE_MOTIF` # 24
--- | `ITEM_TYPE_DISPLAY_CATEGORY_TOOL` # 33
--- | `ITEM_TYPE_DISPLAY_CATEGORY_TRAIT_ITEM` # 18
--- | `ITEM_TYPE_DISPLAY_CATEGORY_TRASH` # 36
--- | `ITEM_TYPE_DISPLAY_CATEGORY_TROPHY` # 34
--- | `ITEM_TYPE_DISPLAY_CATEGORY_WEAPONS` # 1
--- | `ITEM_TYPE_DISPLAY_CATEGORY_WOODWORKING` # 12

ITEM_TYPE_DISPLAY_CATEGORY_ALCHEMY = 14
ITEM_TYPE_DISPLAY_CATEGORY_ALL = 0
ITEM_TYPE_DISPLAY_CATEGORY_APPEARANCE = 29
ITEM_TYPE_DISPLAY_CATEGORY_ARMOR = 2
ITEM_TYPE_DISPLAY_CATEGORY_BLACKSMITHING = 10
ITEM_TYPE_DISPLAY_CATEGORY_CLOTHING = 11
ITEM_TYPE_DISPLAY_CATEGORY_COMPANION = 41
ITEM_TYPE_DISPLAY_CATEGORY_CONSUMABLE = 4
ITEM_TYPE_DISPLAY_CATEGORY_CONTAINER = 26
ITEM_TYPE_DISPLAY_CATEGORY_CRAFTING = 5
ITEM_TYPE_DISPLAY_CATEGORY_CROWN_ITEM = 28
ITEM_TYPE_DISPLAY_CATEGORY_DRINK = 20
ITEM_TYPE_DISPLAY_CATEGORY_DRINK_INGREDIENT = 38
ITEM_TYPE_DISPLAY_CATEGORY_ENCHANTING = 15
ITEM_TYPE_DISPLAY_CATEGORY_FOOD = 19
ITEM_TYPE_DISPLAY_CATEGORY_FOOD_INGREDIENT = 37
ITEM_TYPE_DISPLAY_CATEGORY_FURNISHING = 6
ITEM_TYPE_DISPLAY_CATEGORY_FURNISHING_MATERIAL = 40
ITEM_TYPE_DISPLAY_CATEGORY_GLYPH = 30
ITEM_TYPE_DISPLAY_CATEGORY_JEWELRY = 3
ITEM_TYPE_DISPLAY_CATEGORY_JEWELRYCRAFTING = 13
ITEM_TYPE_DISPLAY_CATEGORY_JUNK = 9
ITEM_TYPE_DISPLAY_CATEGORY_LURE = 35
ITEM_TYPE_DISPLAY_CATEGORY_MASTER_WRIT = 25
ITEM_TYPE_DISPLAY_CATEGORY_MISCELLANEOUS = 7
ITEM_TYPE_DISPLAY_CATEGORY_POISON = 23
ITEM_TYPE_DISPLAY_CATEGORY_POTION = 22
ITEM_TYPE_DISPLAY_CATEGORY_PROVISIONING = 16
ITEM_TYPE_DISPLAY_CATEGORY_QUEST = 8
ITEM_TYPE_DISPLAY_CATEGORY_RARE_INGREDIENT = 39
ITEM_TYPE_DISPLAY_CATEGORY_RECIPE = 21
ITEM_TYPE_DISPLAY_CATEGORY_REPAIR_ITEM = 27
ITEM_TYPE_DISPLAY_CATEGORY_SIEGE = 32
ITEM_TYPE_DISPLAY_CATEGORY_SOUL_GEM = 31
ITEM_TYPE_DISPLAY_CATEGORY_STYLE_MATERIAL = 17
ITEM_TYPE_DISPLAY_CATEGORY_STYLE_MOTIF = 24
ITEM_TYPE_DISPLAY_CATEGORY_TOOL = 33
ITEM_TYPE_DISPLAY_CATEGORY_TRAIT_ITEM = 18
ITEM_TYPE_DISPLAY_CATEGORY_TRASH = 36
ITEM_TYPE_DISPLAY_CATEGORY_TROPHY = 34
ITEM_TYPE_DISPLAY_CATEGORY_WEAPONS = 1
ITEM_TYPE_DISPLAY_CATEGORY_WOODWORKING = 12
