--- @meta ItemSetSuppressionType

--- @alias ItemSetSuppressionType integer
--- | `ITEM_SET_SUPPRESSION_TYPE_ABILITY` # 3
--- | `ITEM_SET_SUPPRESSION_TYPE_BATTLE_GROUND` # 2
--- | `ITEM_SET_SUPPRESSION_TYPE_CAMPAIGN` # 1
--- | `ITEM_SET_SUPPRESSION_TYPE_ITEMSET` # 4
--- | `ITEM_SET_SUPPRESSION_TYPE_NONE` # 0

ITEM_SET_SUPPRESSION_TYPE_ABILITY = 3
ITEM_SET_SUPPRESSION_TYPE_BATTLE_GROUND = 2
ITEM_SET_SUPPRESSION_TYPE_CAMPAIGN = 1
ITEM_SET_SUPPRESSION_TYPE_ITEMSET = 4
ITEM_SET_SUPPRESSION_TYPE_NONE = 0
