--- @meta ItemType

--- @alias ItemType integer
--- | `ITEMTYPE_ADDITIVE` # 11
--- | `ITEMTYPE_ARMOR` # 2
--- | `ITEMTYPE_ARMOR_BOOSTER` # 24
--- | `ITEMTYPE_ARMOR_TRAIT` # 45
--- | `ITEMTYPE_AVA_REPAIR` # 47
--- | `ITEMTYPE_BLACKSMITHING_BOOSTER` # 41
--- | `ITEMTYPE_BLACKSMITHING_MATERIAL` # 36
--- | `ITEMTYPE_BLACKSMITHING_RAW_MATERIAL` # 35
--- | `ITEMTYPE_CLOTHIER_BOOSTER` # 43
--- | `ITEMTYPE_CLOTHIER_MATERIAL` # 40
--- | `ITEMTYPE_CLOTHIER_RAW_MATERIAL` # 39
--- | `ITEMTYPE_COLLECTIBLE` # 34
--- | `ITEMTYPE_CONTAINER` # 18
--- | `ITEMTYPE_CONTAINER_CURRENCY` # 70
--- | `ITEMTYPE_COSTUME` # 13
--- | `ITEMTYPE_CRAFTED_ABILITY` # 72
--- | `ITEMTYPE_CRAFTED_ABILITY_SCRIPT` # 73
--- | `ITEMTYPE_CROWN_ITEM` # 57
--- | `ITEMTYPE_CROWN_REPAIR` # 55
--- | `ITEMTYPE_DEPRECATED` # 32
--- | `ITEMTYPE_DEPRECATED_2` # 49
--- | `ITEMTYPE_DISGUISE` # 14
--- | `ITEMTYPE_DRINK` # 12
--- | `ITEMTYPE_DYE_STAMP` # 59
--- | `ITEMTYPE_ENCHANTING_RUNE_ASPECT` # 52
--- | `ITEMTYPE_ENCHANTING_RUNE_ESSENCE` # 53
--- | `ITEMTYPE_ENCHANTING_RUNE_POTENCY` # 51
--- | `ITEMTYPE_ENCHANTMENT_BOOSTER` # 25
--- | `ITEMTYPE_FISH` # 54
--- | `ITEMTYPE_FLAVORING` # 28
--- | `ITEMTYPE_FOOD` # 4
--- | `ITEMTYPE_FURNISHING` # 61
--- | `ITEMTYPE_FURNISHING_MATERIAL` # 62
--- | `ITEMTYPE_GLYPH_ARMOR` # 21
--- | `ITEMTYPE_GLYPH_JEWELRY` # 26
--- | `ITEMTYPE_GLYPH_WEAPON` # 20
--- | `ITEMTYPE_GROUP_REPAIR` # 71
--- | `ITEMTYPE_INGREDIENT` # 10
--- | `ITEMTYPE_JEWELRYCRAFTING_BOOSTER` # 65
--- | `ITEMTYPE_JEWELRYCRAFTING_MATERIAL` # 64
--- | `ITEMTYPE_JEWELRYCRAFTING_RAW_BOOSTER` # 67
--- | `ITEMTYPE_JEWELRYCRAFTING_RAW_MATERIAL` # 63
--- | `ITEMTYPE_JEWELRY_RAW_TRAIT` # 68
--- | `ITEMTYPE_JEWELRY_TRAIT` # 66
--- | `ITEMTYPE_LOCKPICK` # 22
--- | `ITEMTYPE_LURE` # 16
--- | `ITEMTYPE_MASTER_WRIT` # 60
--- | `ITEMTYPE_MOUNT` # 50
--- | `ITEMTYPE_NONE` # 0
--- | `ITEMTYPE_PLUG` # 3
--- | `ITEMTYPE_POISON` # 30
--- | `ITEMTYPE_POISON_BASE` # 58
--- | `ITEMTYPE_POTION` # 7
--- | `ITEMTYPE_POTION_BASE` # 33
--- | `ITEMTYPE_RACIAL_STYLE_MOTIF` # 8
--- | `ITEMTYPE_RAW_MATERIAL` # 17
--- | `ITEMTYPE_REAGENT` # 31
--- | `ITEMTYPE_RECALL_STONE` # 69
--- | `ITEMTYPE_RECIPE` # 29
--- | `ITEMTYPE_SCRIBING_INK` # 74
--- | `ITEMTYPE_SIEGE` # 6
--- | `ITEMTYPE_SOUL_GEM` # 19
--- | `ITEMTYPE_SPICE` # 27
--- | `ITEMTYPE_STYLE_MATERIAL` # 44
--- | `ITEMTYPE_TABARD` # 15
--- | `ITEMTYPE_TOOL` # 9
--- | `ITEMTYPE_TRASH` # 48
--- | `ITEMTYPE_TREASURE` # 56
--- | `ITEMTYPE_TROPHY` # 5
--- | `ITEMTYPE_WEAPON` # 1
--- | `ITEMTYPE_WEAPON_BOOSTER` # 23
--- | `ITEMTYPE_WEAPON_TRAIT` # 46
--- | `ITEMTYPE_WOODWORKING_BOOSTER` # 42
--- | `ITEMTYPE_WOODWORKING_MATERIAL` # 38
--- | `ITEMTYPE_WOODWORKING_RAW_MATERIAL` # 37

ITEMTYPE_ADDITIVE = 11
ITEMTYPE_ARMOR = 2
ITEMTYPE_ARMOR_BOOSTER = 24
ITEMTYPE_ARMOR_TRAIT = 45
ITEMTYPE_AVA_REPAIR = 47
ITEMTYPE_BLACKSMITHING_BOOSTER = 41
ITEMTYPE_BLACKSMITHING_MATERIAL = 36
ITEMTYPE_BLACKSMITHING_RAW_MATERIAL = 35
ITEMTYPE_CLOTHIER_BOOSTER = 43
ITEMTYPE_CLOTHIER_MATERIAL = 40
ITEMTYPE_CLOTHIER_RAW_MATERIAL = 39
ITEMTYPE_COLLECTIBLE = 34
ITEMTYPE_CONTAINER = 18
ITEMTYPE_CONTAINER_CURRENCY = 70
ITEMTYPE_COSTUME = 13
ITEMTYPE_CRAFTED_ABILITY = 72
ITEMTYPE_CRAFTED_ABILITY_SCRIPT = 73
ITEMTYPE_CROWN_ITEM = 57
ITEMTYPE_CROWN_REPAIR = 55
ITEMTYPE_DEPRECATED = 32
ITEMTYPE_DEPRECATED_2 = 49
ITEMTYPE_DISGUISE = 14
ITEMTYPE_DRINK = 12
ITEMTYPE_DYE_STAMP = 59
ITEMTYPE_ENCHANTING_RUNE_ASPECT = 52
ITEMTYPE_ENCHANTING_RUNE_ESSENCE = 53
ITEMTYPE_ENCHANTING_RUNE_POTENCY = 51
ITEMTYPE_ENCHANTMENT_BOOSTER = 25
ITEMTYPE_FISH = 54
ITEMTYPE_FLAVORING = 28
ITEMTYPE_FOOD = 4
ITEMTYPE_FURNISHING = 61
ITEMTYPE_FURNISHING_MATERIAL = 62
ITEMTYPE_GLYPH_ARMOR = 21
ITEMTYPE_GLYPH_JEWELRY = 26
ITEMTYPE_GLYPH_WEAPON = 20
ITEMTYPE_GROUP_REPAIR = 71
ITEMTYPE_INGREDIENT = 10
ITEMTYPE_JEWELRYCRAFTING_BOOSTER = 65
ITEMTYPE_JEWELRYCRAFTING_MATERIAL = 64
ITEMTYPE_JEWELRYCRAFTING_RAW_BOOSTER = 67
ITEMTYPE_JEWELRYCRAFTING_RAW_MATERIAL = 63
ITEMTYPE_JEWELRY_RAW_TRAIT = 68
ITEMTYPE_JEWELRY_TRAIT = 66
ITEMTYPE_LOCKPICK = 22
ITEMTYPE_LURE = 16
ITEMTYPE_MASTER_WRIT = 60
ITEMTYPE_MOUNT = 50
ITEMTYPE_NONE = 0
ITEMTYPE_PLUG = 3
ITEMTYPE_POISON = 30
ITEMTYPE_POISON_BASE = 58
ITEMTYPE_POTION = 7
ITEMTYPE_POTION_BASE = 33
ITEMTYPE_RACIAL_STYLE_MOTIF = 8
ITEMTYPE_RAW_MATERIAL = 17
ITEMTYPE_REAGENT = 31
ITEMTYPE_RECALL_STONE = 69
ITEMTYPE_RECIPE = 29
ITEMTYPE_SCRIBING_INK = 74
ITEMTYPE_SIEGE = 6
ITEMTYPE_SOUL_GEM = 19
ITEMTYPE_SPICE = 27
ITEMTYPE_STYLE_MATERIAL = 44
ITEMTYPE_TABARD = 15
ITEMTYPE_TOOL = 9
ITEMTYPE_TRASH = 48
ITEMTYPE_TREASURE = 56
ITEMTYPE_TROPHY = 5
ITEMTYPE_WEAPON = 1
ITEMTYPE_WEAPON_BOOSTER = 23
ITEMTYPE_WEAPON_TRAIT = 46
ITEMTYPE_WOODWORKING_BOOSTER = 42
ITEMTYPE_WOODWORKING_MATERIAL = 38
ITEMTYPE_WOODWORKING_RAW_MATERIAL = 37
