--- @meta ItemDisplayQuality

--- @alias ItemDisplayQuality integer
--- | `ITEM_DISPLAY_QUALITY_ARCANE` # 3
--- | `ITEM_DISPLAY_QUALITY_ARTIFACT` # 4
--- | `ITEM_DISPLAY_QUALITY_LEGENDARY` # 5
--- | `ITEM_DISPLAY_QUALITY_MAGIC` # 2
--- | `ITEM_DISPLAY_QUALITY_MYTHIC_OVERRIDE` # 6
--- | `ITEM_DISPLAY_QUALITY_NORMAL` # 1
--- | `ITEM_DISPLAY_QUALITY_TRASH` # 0

ITEM_DISPLAY_QUALITY_ARCANE = 3
ITEM_DISPLAY_QUALITY_ARTIFACT = 4
ITEM_DISPLAY_QUALITY_LEGENDARY = 5
ITEM_DISPLAY_QUALITY_MAGIC = 2
ITEM_DISPLAY_QUALITY_MYTHIC_OVERRIDE = 6
ITEM_DISPLAY_QUALITY_NORMAL = 1
ITEM_DISPLAY_QUALITY_TRASH = 0
