--- @meta ItemListSortType

--- @alias ItemListSortType integer
--- | `ITEM_LIST_SORT_TYPE_CATEGORY` # 1
--- | `ITEM_LIST_SORT_TYPE_ITEM_NAME` # 2
--- | `ITEM_LIST_SORT_TYPE_ITEM_QUALITY` # 3
--- | `ITEM_LIST_SORT_TYPE_STACK_COUNT` # 4
--- | `ITEM_LIST_SORT_TYPE_VALUE` # 5

ITEM_LIST_SORT_TYPE_CATEGORY = 1
ITEM_LIST_SORT_TYPE_ITEM_NAME = 2
ITEM_LIST_SORT_TYPE_ITEM_QUALITY = 3
ITEM_LIST_SORT_TYPE_STACK_COUNT = 4
ITEM_LIST_SORT_TYPE_VALUE = 5
