--- @meta ItemLaunderResult

--- @alias ItemLaunderResult integer
--- | `ITEM_LAUNDER_RESULT_AT_LIMIT` # 7
--- | `ITEM_LAUNDER_RESULT_CANT_AFFORD_LAUNDER` # 4
--- | `ITEM_LAUNDER_RESULT_INVALID` # 2
--- | `ITEM_LAUNDER_RESULT_INVENTORY_FULL` # 5
--- | `ITEM_LAUNDER_RESULT_ITEM_NOT_LAUNDERABLE` # 6
--- | `ITEM_LAUNDER_RESULT_NONE` # 0
--- | `ITEM_LAUNDER_RESULT_NOT_STOLEN` # 3
--- | `ITEM_LAUNDER_RESULT_SUCCESS` # 1

ITEM_LAUNDER_RESULT_AT_LIMIT = 7
ITEM_LAUNDER_RESULT_CANT_AFFORD_LAUNDER = 4
ITEM_LAUNDER_RESULT_INVALID = 2
ITEM_LAUNDER_RESULT_INVENTORY_FULL = 5
ITEM_LAUNDER_RESULT_ITEM_NOT_LAUNDERABLE = 6
ITEM_LAUNDER_RESULT_NONE = 0
ITEM_LAUNDER_RESULT_NOT_STOLEN = 3
ITEM_LAUNDER_RESULT_SUCCESS = 1
