--- @meta ItemStyleChapter

--- @alias ItemStyleChapter integer
--- | `ITEM_STYLE_CHAPTER_ALL` # 0
--- | `ITEM_STYLE_CHAPTER_AXES` # 10
--- | `ITEM_STYLE_CHAPTER_BELTS` # 6
--- | `ITEM_STYLE_CHAPTER_BOOTS` # 3
--- | `ITEM_STYLE_CHAPTER_BOWS` # 14
--- | `ITEM_STYLE_CHAPTER_CHESTS` # 5
--- | `ITEM_STYLE_CHAPTER_DAGGERS` # 11
--- | `ITEM_STYLE_CHAPTER_GLOVES` # 2
--- | `ITEM_STYLE_CHAPTER_HELMETS` # 1
--- | `ITEM_STYLE_CHAPTER_LEGS` # 4
--- | `ITEM_STYLE_CHAPTER_MACES` # 9
--- | `ITEM_STYLE_CHAPTER_SHIELDS` # 13
--- | `ITEM_STYLE_CHAPTER_SHOULDERS` # 7
--- | `ITEM_STYLE_CHAPTER_STAVES` # 12
--- | `ITEM_STYLE_CHAPTER_SWORDS` # 8

ITEM_STYLE_CHAPTER_ALL = 0
ITEM_STYLE_CHAPTER_AXES = 10
ITEM_STYLE_CHAPTER_BELTS = 6
ITEM_STYLE_CHAPTER_BOOTS = 3
ITEM_STYLE_CHAPTER_BOWS = 14
ITEM_STYLE_CHAPTER_CHESTS = 5
ITEM_STYLE_CHAPTER_DAGGERS = 11
ITEM_STYLE_CHAPTER_GLOVES = 2
ITEM_STYLE_CHAPTER_HELMETS = 1
ITEM_STYLE_CHAPTER_LEGS = 4
ITEM_STYLE_CHAPTER_MACES = 9
ITEM_STYLE_CHAPTER_SHIELDS = 13
ITEM_STYLE_CHAPTER_SHOULDERS = 7
ITEM_STYLE_CHAPTER_STAVES = 12
ITEM_STYLE_CHAPTER_SWORDS = 8
