--- @meta ItemTraitInformation

--- @alias ItemTraitInformation integer
--- | `ITEM_TRAIT_INFORMATION_CAN_BE_RESEARCHED` # 3
--- | `ITEM_TRAIT_INFORMATION_INTRICATE` # 1
--- | `ITEM_TRAIT_INFORMATION_NONE` # 0
--- | `ITEM_TRAIT_INFORMATION_ORNATE` # 2
--- | `ITEM_TRAIT_INFORMATION_RECONSTRUCTED` # 5
--- | `ITEM_TRAIT_INFORMATION_RETRAITED` # 4

ITEM_TRAIT_INFORMATION_CAN_BE_RESEARCHED = 3
ITEM_TRAIT_INFORMATION_INTRICATE = 1
ITEM_TRAIT_INFORMATION_NONE = 0
ITEM_TRAIT_INFORMATION_ORNATE = 2
ITEM_TRAIT_INFORMATION_RECONSTRUCTED = 5
ITEM_TRAIT_INFORMATION_RETRAITED = 4
