--- @meta ItemUseType

--- @alias ItemUseType integer
--- | `ITEM_USE_TYPE_ATTRIBUTE_RESPEC` # 14
--- | `ITEM_USE_TYPE_BOOK` # 13
--- | `ITEM_USE_TYPE_COLLECTIBLE_GRANT` # 10
--- | `ITEM_USE_TYPE_COMBINATION` # 11
--- | `ITEM_USE_TYPE_COSTUME_DYE_STAMP` # 6
--- | `ITEM_USE_TYPE_CRAFTED_ABILITY` # 16
--- | `ITEM_USE_TYPE_CRAFTED_ABILITY_SCRIPT` # 17
--- | `ITEM_USE_TYPE_FILLET_FISH` # 15
--- | `ITEM_USE_TYPE_ITEM_DYE_STAMP` # 5
--- | `ITEM_USE_TYPE_KEEP_RECALL_STONE` # 7
--- | `ITEM_USE_TYPE_MORPH_RESPEC` # 9
--- | `ITEM_USE_TYPE_NONE` # 0
--- | `ITEM_USE_TYPE_PLEDGE_OF_MARA` # 3
--- | `ITEM_USE_TYPE_RECIPE` # 1
--- | `ITEM_USE_TYPE_RECIPE_LIST` # 12
--- | `ITEM_USE_TYPE_SKILL_RESPEC` # 8
--- | `ITEM_USE_TYPE_TREASURE_MAP` # 4
--- | `ITEM_USE_TYPE_VANITY_PET` # 2

ITEM_USE_TYPE_ATTRIBUTE_RESPEC = 14
ITEM_USE_TYPE_BOOK = 13
ITEM_USE_TYPE_COLLECTIBLE_GRANT = 10
ITEM_USE_TYPE_COMBINATION = 11
ITEM_USE_TYPE_COSTUME_DYE_STAMP = 6
ITEM_USE_TYPE_CRAFTED_ABILITY = 16
ITEM_USE_TYPE_CRAFTED_ABILITY_SCRIPT = 17
ITEM_USE_TYPE_FILLET_FISH = 15
ITEM_USE_TYPE_ITEM_DYE_STAMP = 5
ITEM_USE_TYPE_KEEP_RECALL_STONE = 7
ITEM_USE_TYPE_MORPH_RESPEC = 9
ITEM_USE_TYPE_NONE = 0
ITEM_USE_TYPE_PLEDGE_OF_MARA = 3
ITEM_USE_TYPE_RECIPE = 1
ITEM_USE_TYPE_RECIPE_LIST = 12
ITEM_USE_TYPE_SKILL_RESPEC = 8
ITEM_USE_TYPE_TREASURE_MAP = 4
ITEM_USE_TYPE_VANITY_PET = 2
