--- @meta ItemSetType

--- @alias ItemSetType integer
--- | `ITEM_SET_TYPE_CRAFTED` # 1
--- | `ITEM_SET_TYPE_DUNGEON` # 2
--- | `ITEM_SET_TYPE_MONSTER` # 5
--- | `ITEM_SET_TYPE_NONE` # 0
--- | `ITEM_SET_TYPE_WEAPON` # 4
--- | `ITEM_SET_TYPE_WORLD` # 3

ITEM_SET_TYPE_CRAFTED = 1
ITEM_SET_TYPE_DUNGEON = 2
ITEM_SET_TYPE_MONSTER = 5
ITEM_SET_TYPE_NONE = 0
ITEM_SET_TYPE_WEAPON = 4
ITEM_SET_TYPE_WORLD = 3
