--- @meta ItemSellInformation

--- @alias ItemSellInformation integer
--- | `ITEM_SELL_INFORMATION_CANNOT_SELL` # 4
--- | `ITEM_SELL_INFORMATION_CAN_BE_RESEARCHED` # 3
--- | `ITEM_SELL_INFORMATION_INTRICATE` # 2
--- | `ITEM_SELL_INFORMATION_NONE` # 0
--- | `ITEM_SELL_INFORMATION_PRIORITY_SELL` # 1
--- | `ITEM_SELL_INFORMATION_RECONSTRUCTED` # 5

ITEM_SELL_INFORMATION_CANNOT_SELL = 4
ITEM_SELL_INFORMATION_CAN_BE_RESEARCHED = 3
ITEM_SELL_INFORMATION_INTRICATE = 2
ITEM_SELL_INFORMATION_NONE = 0
ITEM_SELL_INFORMATION_PRIORITY_SELL = 1
ITEM_SELL_INFORMATION_RECONSTRUCTED = 5
