--- @meta ItemRepairReason

--- @alias ItemRepairReason integer
--- | `ITEM_REPAIR_ALREADY_REPAIRED` # 1
--- | `ITEM_REPAIR_CANT_AFFORD_REPAIR` # 2
--- | `ITEM_REPAIR_NO_REPAIR_KIT` # 0

ITEM_REPAIR_ALREADY_REPAIRED = 1
ITEM_REPAIR_CANT_AFFORD_REPAIR = 2
ITEM_REPAIR_NO_REPAIR_KIT = 0
