--- @meta ItemCombinationResult

--- @alias ItemCombinationResult integer
--- | `ITEM_COMBINATION_RESULT_ALREADY_OWNS_GRANTED_COLLECTIBLES` # 2
--- | `ITEM_COMBINATION_RESULT_COLLECTIBLE_BLACKLISTED` # 11
--- | `ITEM_COMBINATION_RESULT_INVALID_COMBINATION` # 1
--- | `ITEM_COMBINATION_RESULT_IS_IN_COMBAT` # 4
--- | `ITEM_COMBINATION_RESULT_IS_IN_HIDEY_HOLE` # 10
--- | `ITEM_COMBINATION_RESULT_IS_IN_PVP_AREA` # 5
--- | `ITEM_COMBINATION_RESULT_IS_MOUNTED` # 6
--- | `ITEM_COMBINATION_RESULT_IS_MOVING` # 7
--- | `ITEM_COMBINATION_RESULT_IS_SWIMMING` # 9
--- | `ITEM_COMBINATION_RESULT_MISSING_COLLECTIBLES` # 8
--- | `ITEM_COMBINATION_RESULT_MISSING_ITEMS` # 3
--- | `ITEM_COMBINATION_RESULT_SUCCESS` # 0

ITEM_COMBINATION_RESULT_ALREADY_OWNS_GRANTED_COLLECTIBLES = 2
ITEM_COMBINATION_RESULT_COLLECTIBLE_BLACKLISTED = 11
ITEM_COMBINATION_RESULT_INVALID_COMBINATION = 1
ITEM_COMBINATION_RESULT_IS_IN_COMBAT = 4
ITEM_COMBINATION_RESULT_IS_IN_HIDEY_HOLE = 10
ITEM_COMBINATION_RESULT_IS_IN_PVP_AREA = 5
ITEM_COMBINATION_RESULT_IS_MOUNTED = 6
ITEM_COMBINATION_RESULT_IS_MOVING = 7
ITEM_COMBINATION_RESULT_IS_SWIMMING = 9
ITEM_COMBINATION_RESULT_MISSING_COLLECTIBLES = 8
ITEM_COMBINATION_RESULT_MISSING_ITEMS = 3
ITEM_COMBINATION_RESULT_SUCCESS = 0
