--- @meta ItemQuality

--- @alias ItemQuality integer
--- | `ITEM_FUNCTIONAL_QUALITY_ARCANE` # 3
--- | `ITEM_FUNCTIONAL_QUALITY_ARTIFACT` # 4
--- | `ITEM_FUNCTIONAL_QUALITY_LEGENDARY` # 5
--- | `ITEM_FUNCTIONAL_QUALITY_MAGIC` # 2
--- | `ITEM_FUNCTIONAL_QUALITY_NORMAL` # 1
--- | `ITEM_FUNCTIONAL_QUALITY_TRASH` # 0

ITEM_FUNCTIONAL_QUALITY_ARCANE = 3
ITEM_FUNCTIONAL_QUALITY_ARTIFACT = 4
ITEM_FUNCTIONAL_QUALITY_LEGENDARY = 5
ITEM_FUNCTIONAL_QUALITY_MAGIC = 2
ITEM_FUNCTIONAL_QUALITY_NORMAL = 1
ITEM_FUNCTIONAL_QUALITY_TRASH = 0
