--- @meta ItemFilterType

--- @alias ItemFilterType integer
--- | `ITEMFILTERTYPE_ALCHEMY` # 16
--- | `ITEMFILTERTYPE_ALL` # 0
--- | `ITEMFILTERTYPE_ARMOR` # 2
--- | `ITEMFILTERTYPE_BLACKSMITHING` # 13
--- | `ITEMFILTERTYPE_BUYBACK` # 8
--- | `ITEMFILTERTYPE_CLOTHING` # 14
--- | `ITEMFILTERTYPE_COLLECTIBLE` # 12
--- | `ITEMFILTERTYPE_COMPANION` # 27
--- | `ITEMFILTERTYPE_CONSUMABLE` # 3
--- | `ITEMFILTERTYPE_CRAFTING` # 4
--- | `ITEMFILTERTYPE_DAMAGED` # 11
--- | `ITEMFILTERTYPE_ENCHANTING` # 17
--- | `ITEMFILTERTYPE_FURNISHING` # 21
--- | `ITEMFILTERTYPE_HOUSE_WITH_TEMPLATE` # 22
--- | `ITEMFILTERTYPE_JEWELRY` # 25
--- | `ITEMFILTERTYPE_JEWELRYCRAFTING` # 24
--- | `ITEMFILTERTYPE_JUNK` # 9
--- | `ITEMFILTERTYPE_MISCELLANEOUS` # 5
--- | `ITEMFILTERTYPE_PROVISIONING` # 18
--- | `ITEMFILTERTYPE_QUEST` # 7
--- | `ITEMFILTERTYPE_QUEST_QUICKSLOT` # 26
--- | `ITEMFILTERTYPE_QUICKSLOT` # 6
--- | `ITEMFILTERTYPE_STYLE_MATERIALS` # 19
--- | `ITEMFILTERTYPE_TRAIT_ITEMS` # 20
--- | `ITEMFILTERTYPE_UNUSED` # 10
--- | `ITEMFILTERTYPE_UNUSED2` # 23
--- | `ITEMFILTERTYPE_WEAPONS` # 1
--- | `ITEMFILTERTYPE_WOODWORKING` # 15

ITEMFILTERTYPE_ALCHEMY = 16
ITEMFILTERTYPE_ALL = 0
ITEMFILTERTYPE_ARMOR = 2
ITEMFILTERTYPE_BLACKSMITHING = 13
ITEMFILTERTYPE_BUYBACK = 8
ITEMFILTERTYPE_CLOTHING = 14
ITEMFILTERTYPE_COLLECTIBLE = 12
ITEMFILTERTYPE_COMPANION = 27
ITEMFILTERTYPE_CONSUMABLE = 3
ITEMFILTERTYPE_CRAFTING = 4
ITEMFILTERTYPE_DAMAGED = 11
ITEMFILTERTYPE_ENCHANTING = 17
ITEMFILTERTYPE_FURNISHING = 21
ITEMFILTERTYPE_HOUSE_WITH_TEMPLATE = 22
ITEMFILTERTYPE_JEWELRY = 25
ITEMFILTERTYPE_JEWELRYCRAFTING = 24
ITEMFILTERTYPE_JUNK = 9
ITEMFILTERTYPE_MISCELLANEOUS = 5
ITEMFILTERTYPE_PROVISIONING = 18
ITEMFILTERTYPE_QUEST = 7
ITEMFILTERTYPE_QUEST_QUICKSLOT = 26
ITEMFILTERTYPE_QUICKSLOT = 6
ITEMFILTERTYPE_STYLE_MATERIALS = 19
ITEMFILTERTYPE_TRAIT_ITEMS = 20
ITEMFILTERTYPE_UNUSED = 10
ITEMFILTERTYPE_UNUSED2 = 23
ITEMFILTERTYPE_WEAPONS = 1
ITEMFILTERTYPE_WOODWORKING = 15
