--- @meta ItemUISoundCategory

--- @alias ItemUISoundCategory integer
--- | `ITEM_SOUND_CATEGORY_ANIMAL_COMPONENT` # 25
--- | `ITEM_SOUND_CATEGORY_BATTLEFLAG` # 28
--- | `ITEM_SOUND_CATEGORY_BOOK` # 36
--- | `ITEM_SOUND_CATEGORY_BOOSTER` # 44
--- | `ITEM_SOUND_CATEGORY_BOW` # 13
--- | `ITEM_SOUND_CATEGORY_BREAD` # 33
--- | `ITEM_SOUND_CATEGORY_CLOTH_COMPONENT` # 40
--- | `ITEM_SOUND_CATEGORY_CRAFTED_ABILITY` # 46
--- | `ITEM_SOUND_CATEGORY_CRAFTED_ABILITY_SCRIPT` # 47
--- | `ITEM_SOUND_CATEGORY_CUSTOM_SOUND` # 29
--- | `ITEM_SOUND_CATEGORY_DAGGER` # 8
--- | `ITEM_SOUND_CATEGORY_DEFAULT` # 0
--- | `ITEM_SOUND_CATEGORY_DRINK` # 19
--- | `ITEM_SOUND_CATEGORY_ENCHANTED_MEDALLION` # 48
--- | `ITEM_SOUND_CATEGORY_ENCHANTMENT` # 30
--- | `ITEM_SOUND_CATEGORY_FISH` # 43
--- | `ITEM_SOUND_CATEGORY_FOOD` # 18
--- | `ITEM_SOUND_CATEGORY_FOOTLOCKER` # 27
--- | `ITEM_SOUND_CATEGORY_HEAVY_ARMOR` # 10
--- | `ITEM_SOUND_CATEGORY_INGREDIENT` # 38
--- | `ITEM_SOUND_CATEGORY_LIGHT_ARMOR` # 12
--- | `ITEM_SOUND_CATEGORY_LURE` # 39
--- | `ITEM_SOUND_CATEGORY_MEAT` # 32
--- | `ITEM_SOUND_CATEGORY_MEDIUM_ARMOR` # 11
--- | `ITEM_SOUND_CATEGORY_METAL_COMPONENT` # 26
--- | `ITEM_SOUND_CATEGORY_MINERAL_COMPONENT` # 24
--- | `ITEM_SOUND_CATEGORY_NECKLACE` # 14
--- | `ITEM_SOUND_CATEGORY_NONE` # 31
--- | `ITEM_SOUND_CATEGORY_ONE_HAND_AX` # 1
--- | `ITEM_SOUND_CATEGORY_ONE_HAND_HAMMER` # 2
--- | `ITEM_SOUND_CATEGORY_ONE_HAND_SWORD` # 3
--- | `ITEM_SOUND_CATEGORY_PLANT_COMPONENT` # 23
--- | `ITEM_SOUND_CATEGORY_POTION` # 20
--- | `ITEM_SOUND_CATEGORY_REPAIR_KIT` # 42
--- | `ITEM_SOUND_CATEGORY_RING` # 9
--- | `ITEM_SOUND_CATEGORY_RUNE` # 15
--- | `ITEM_SOUND_CATEGORY_SCROLL` # 21
--- | `ITEM_SOUND_CATEGORY_SHIELD` # 16
--- | `ITEM_SOUND_CATEGORY_SIEGE` # 35
--- | `ITEM_SOUND_CATEGORY_SOUL_GEM` # 41
--- | `ITEM_SOUND_CATEGORY_STAFF` # 17
--- | `ITEM_SOUND_CATEGORY_STEW` # 34
--- | `ITEM_SOUND_CATEGORY_TABARD` # 45
--- | `ITEM_SOUND_CATEGORY_TRASH_LOOT` # 22
--- | `ITEM_SOUND_CATEGORY_TWO_HAND_AX` # 4
--- | `ITEM_SOUND_CATEGORY_TWO_HAND_HAMMER` # 5
--- | `ITEM_SOUND_CATEGORY_TWO_HAND_SWORD` # 6
--- | `ITEM_SOUND_CATEGORY_UNUSED` # 7
--- | `ITEM_SOUND_CATEGORY_WOOD_COMPONENT` # 37

ITEM_SOUND_CATEGORY_ANIMAL_COMPONENT = 25
ITEM_SOUND_CATEGORY_BATTLEFLAG = 28
ITEM_SOUND_CATEGORY_BOOK = 36
ITEM_SOUND_CATEGORY_BOOSTER = 44
ITEM_SOUND_CATEGORY_BOW = 13
ITEM_SOUND_CATEGORY_BREAD = 33
ITEM_SOUND_CATEGORY_CLOTH_COMPONENT = 40
ITEM_SOUND_CATEGORY_CRAFTED_ABILITY = 46
ITEM_SOUND_CATEGORY_CRAFTED_ABILITY_SCRIPT = 47
ITEM_SOUND_CATEGORY_CUSTOM_SOUND = 29
ITEM_SOUND_CATEGORY_DAGGER = 8
ITEM_SOUND_CATEGORY_DEFAULT = 0
ITEM_SOUND_CATEGORY_DRINK = 19
ITEM_SOUND_CATEGORY_ENCHANTED_MEDALLION = 48
ITEM_SOUND_CATEGORY_ENCHANTMENT = 30
ITEM_SOUND_CATEGORY_FISH = 43
ITEM_SOUND_CATEGORY_FOOD = 18
ITEM_SOUND_CATEGORY_FOOTLOCKER = 27
ITEM_SOUND_CATEGORY_HEAVY_ARMOR = 10
ITEM_SOUND_CATEGORY_INGREDIENT = 38
ITEM_SOUND_CATEGORY_LIGHT_ARMOR = 12
ITEM_SOUND_CATEGORY_LURE = 39
ITEM_SOUND_CATEGORY_MEAT = 32
ITEM_SOUND_CATEGORY_MEDIUM_ARMOR = 11
ITEM_SOUND_CATEGORY_METAL_COMPONENT = 26
ITEM_SOUND_CATEGORY_MINERAL_COMPONENT = 24
ITEM_SOUND_CATEGORY_NECKLACE = 14
ITEM_SOUND_CATEGORY_NONE = 31
ITEM_SOUND_CATEGORY_ONE_HAND_AX = 1
ITEM_SOUND_CATEGORY_ONE_HAND_HAMMER = 2
ITEM_SOUND_CATEGORY_ONE_HAND_SWORD = 3
ITEM_SOUND_CATEGORY_PLANT_COMPONENT = 23
ITEM_SOUND_CATEGORY_POTION = 20
ITEM_SOUND_CATEGORY_REPAIR_KIT = 42
ITEM_SOUND_CATEGORY_RING = 9
ITEM_SOUND_CATEGORY_RUNE = 15
ITEM_SOUND_CATEGORY_SCROLL = 21
ITEM_SOUND_CATEGORY_SHIELD = 16
ITEM_SOUND_CATEGORY_SIEGE = 35
ITEM_SOUND_CATEGORY_SOUL_GEM = 41
ITEM_SOUND_CATEGORY_STAFF = 17
ITEM_SOUND_CATEGORY_STEW = 34
ITEM_SOUND_CATEGORY_TABARD = 45
ITEM_SOUND_CATEGORY_TRASH_LOOT = 22
ITEM_SOUND_CATEGORY_TWO_HAND_AX = 4
ITEM_SOUND_CATEGORY_TWO_HAND_HAMMER = 5
ITEM_SOUND_CATEGORY_TWO_HAND_SWORD = 6
ITEM_SOUND_CATEGORY_UNUSED = 7
ITEM_SOUND_CATEGORY_WOOD_COMPONENT = 37
