--- @meta ItemTooltipColors

--- @alias ItemTooltipColors integer
--- | `ITEM_TOOLTIP_COLOR_ACCENT` # 3
--- | `ITEM_TOOLTIP_COLOR_CHARGE_BAR_GRADIENT_END` # 22
--- | `ITEM_TOOLTIP_COLOR_CHARGE_BAR_GRADIENT_START` # 21
--- | `ITEM_TOOLTIP_COLOR_CLICK_TO_UPGRADE` # 6
--- | `ITEM_TOOLTIP_COLOR_CONDITION_BAR_GRADIENT_END` # 24
--- | `ITEM_TOOLTIP_COLOR_CONDITION_BAR_GRADIENT_START` # 23
--- | `ITEM_TOOLTIP_COLOR_CREATOR` # 12
--- | `ITEM_TOOLTIP_COLOR_DECONSTRUCTABLE` # 14
--- | `ITEM_TOOLTIP_COLOR_EQUIPPED` # 17
--- | `ITEM_TOOLTIP_COLOR_FAIL_CHECK` # 1
--- | `ITEM_TOOLTIP_COLOR_FLAVOR_TEXT` # 11
--- | `ITEM_TOOLTIP_COLOR_GENERAL` # 2
--- | `ITEM_TOOLTIP_COLOR_INACTIVE_BONUS` # 20
--- | `ITEM_TOOLTIP_COLOR_ITEM_LEVEL` # 18
--- | `ITEM_TOOLTIP_COLOR_MISC` # 16
--- | `ITEM_TOOLTIP_COLOR_MYTHIC` # 26
--- | `ITEM_TOOLTIP_COLOR_ON_EQUIP` # 4
--- | `ITEM_TOOLTIP_COLOR_ON_USE` # 5
--- | `ITEM_TOOLTIP_COLOR_PASS_CHECK` # 0
--- | `ITEM_TOOLTIP_COLOR_QUEST_ITEM_NAME` # 15
--- | `ITEM_TOOLTIP_COLOR_SELLS_FOR` # 10
--- | `ITEM_TOOLTIP_COLOR_SHOWING_EQUIPPED_ITEM` # 13
--- | `ITEM_TOOLTIP_COLOR_SOCKET_EMPTY` # 8
--- | `ITEM_TOOLTIP_COLOR_SOCKET_FULL` # 9
--- | `ITEM_TOOLTIP_COLOR_SOCKET_PASS_CHECK` # 7
--- | `ITEM_TOOLTIP_COLOR_STYLE` # 19
--- | `ITEM_TOOLTIP_COLOR_TRADE_BOP` # 25

ITEM_TOOLTIP_COLOR_ACCENT = 3
ITEM_TOOLTIP_COLOR_CHARGE_BAR_GRADIENT_END = 22
ITEM_TOOLTIP_COLOR_CHARGE_BAR_GRADIENT_START = 21
ITEM_TOOLTIP_COLOR_CLICK_TO_UPGRADE = 6
ITEM_TOOLTIP_COLOR_CONDITION_BAR_GRADIENT_END = 24
ITEM_TOOLTIP_COLOR_CONDITION_BAR_GRADIENT_START = 23
ITEM_TOOLTIP_COLOR_CREATOR = 12
ITEM_TOOLTIP_COLOR_DECONSTRUCTABLE = 14
ITEM_TOOLTIP_COLOR_EQUIPPED = 17
ITEM_TOOLTIP_COLOR_FAIL_CHECK = 1
ITEM_TOOLTIP_COLOR_FLAVOR_TEXT = 11
ITEM_TOOLTIP_COLOR_GENERAL = 2
ITEM_TOOLTIP_COLOR_INACTIVE_BONUS = 20
ITEM_TOOLTIP_COLOR_ITEM_LEVEL = 18
ITEM_TOOLTIP_COLOR_MISC = 16
ITEM_TOOLTIP_COLOR_MYTHIC = 26
ITEM_TOOLTIP_COLOR_ON_EQUIP = 4
ITEM_TOOLTIP_COLOR_ON_USE = 5
ITEM_TOOLTIP_COLOR_PASS_CHECK = 0
ITEM_TOOLTIP_COLOR_QUEST_ITEM_NAME = 15
ITEM_TOOLTIP_COLOR_SELLS_FOR = 10
ITEM_TOOLTIP_COLOR_SHOWING_EQUIPPED_ITEM = 13
ITEM_TOOLTIP_COLOR_SOCKET_EMPTY = 8
ITEM_TOOLTIP_COLOR_SOCKET_FULL = 9
ITEM_TOOLTIP_COLOR_SOCKET_PASS_CHECK = 7
ITEM_TOOLTIP_COLOR_STYLE = 19
ITEM_TOOLTIP_COLOR_TRADE_BOP = 25
