--- @meta JumpToPlayerResult

--- @alias JumpToPlayerResult integer
--- | `JUMP_TO_PLAYER_RESULT_CROSS_ALLIANCE_LOCKED` # 6
--- | `JUMP_TO_PLAYER_RESULT_GENERIC_FAILURE` # 1
--- | `JUMP_TO_PLAYER_RESULT_PLAYER_DIFFICULTY_LOCKED` # 5
--- | `JUMP_TO_PLAYER_RESULT_PLAYER_OFFLINE` # 2
--- | `JUMP_TO_PLAYER_RESULT_SOLO_ZONE` # 3
--- | `JUMP_TO_PLAYER_RESULT_SUCCESS` # 0
--- | `JUMP_TO_PLAYER_RESULT_ZONE_COLLECTIBLE_LOCKED` # 4

JUMP_TO_PLAYER_RESULT_CROSS_ALLIANCE_LOCKED = 6
JUMP_TO_PLAYER_RESULT_GENERIC_FAILURE = 1
JUMP_TO_PLAYER_RESULT_PLAYER_DIFFICULTY_LOCKED = 5
JUMP_TO_PLAYER_RESULT_PLAYER_OFFLINE = 2
JUMP_TO_PLAYER_RESULT_SOLO_ZONE = 3
JUMP_TO_PLAYER_RESULT_SUCCESS = 0
JUMP_TO_PLAYER_RESULT_ZONE_COLLECTIBLE_LOCKED = 4
