--- @meta JumpResult

--- @alias JumpResult integer
--- | `JUMP_RESULT_JUMP_FAILED` # 3
--- | `JUMP_RESULT_JUMP_FAILED_ALREADY_JUMPING` # 11
--- | `JUMP_RESULT_JUMP_FAILED_BATTLEGROUND_ENTRY` # 22
--- | `JUMP_RESULT_JUMP_FAILED_CHAMPION_RANK` # 8
--- | `JUMP_RESULT_JUMP_FAILED_DEAD_ON_CAMPAIGN_SWITCH` # 23
--- | `JUMP_RESULT_JUMP_FAILED_DISABLED_CAMPAIGN` # 5
--- | `JUMP_RESULT_JUMP_FAILED_DONT_OWN_HOUSE` # 17
--- | `JUMP_RESULT_JUMP_FAILED_HEROIC_INSTANCE` # 16
--- | `JUMP_RESULT_JUMP_FAILED_INSTANCE_CAP_REACHED` # 12
--- | `JUMP_RESULT_JUMP_FAILED_INSTANCE_FULL` # 10
--- | `JUMP_RESULT_JUMP_FAILED_INVALID_HOUSE` # 19
--- | `JUMP_RESULT_JUMP_FAILED_INVALID_WORLD` # 20
--- | `JUMP_RESULT_JUMP_FAILED_NO_CAMPAIGN` # 4
--- | `JUMP_RESULT_JUMP_FAILED_NO_DETECTION_CELL` # 21
--- | `JUMP_RESULT_JUMP_FAILED_NO_HOUSE_PERMISSION` # 18
--- | `JUMP_RESULT_JUMP_FAILED_NO_SOCIAL` # 9
--- | `JUMP_RESULT_JUMP_FAILED_QUEUING` # 7
--- | `JUMP_RESULT_JUMP_FAILED_READY_CHECK` # 25
--- | `JUMP_RESULT_JUMP_FAILED_RECALL_BLOCKED` # 15
--- | `JUMP_RESULT_JUMP_FAILED_SOCIAL_TARGET_ZONE_COLLECTIBLE_LOCKED` # 24
--- | `JUMP_RESULT_JUMP_FAILED_TOO_DIFFICULT` # 6
--- | `JUMP_RESULT_JUMP_FAILED_ZONE_COLLECTIBLE` # 14
--- | `JUMP_RESULT_JUMP_FAILED_ZONE_REQUIREMENT` # 13
--- | `JUMP_RESULT_LOCAL_JUMP_SUCCESSFUL` # 0
--- | `JUMP_RESULT_NO_JUMP_PERMISSION` # 2
--- | `JUMP_RESULT_REMOTE_JUMP_INITIATED` # 1

JUMP_RESULT_JUMP_FAILED = 3
JUMP_RESULT_JUMP_FAILED_ALREADY_JUMPING = 11
JUMP_RESULT_JUMP_FAILED_BATTLEGROUND_ENTRY = 22
JUMP_RESULT_JUMP_FAILED_CHAMPION_RANK = 8
JUMP_RESULT_JUMP_FAILED_DEAD_ON_CAMPAIGN_SWITCH = 23
JUMP_RESULT_JUMP_FAILED_DISABLED_CAMPAIGN = 5
JUMP_RESULT_JUMP_FAILED_DONT_OWN_HOUSE = 17
JUMP_RESULT_JUMP_FAILED_HEROIC_INSTANCE = 16
JUMP_RESULT_JUMP_FAILED_INSTANCE_CAP_REACHED = 12
JUMP_RESULT_JUMP_FAILED_INSTANCE_FULL = 10
JUMP_RESULT_JUMP_FAILED_INVALID_HOUSE = 19
JUMP_RESULT_JUMP_FAILED_INVALID_WORLD = 20
JUMP_RESULT_JUMP_FAILED_NO_CAMPAIGN = 4
JUMP_RESULT_JUMP_FAILED_NO_DETECTION_CELL = 21
JUMP_RESULT_JUMP_FAILED_NO_HOUSE_PERMISSION = 18
JUMP_RESULT_JUMP_FAILED_NO_SOCIAL = 9
JUMP_RESULT_JUMP_FAILED_QUEUING = 7
JUMP_RESULT_JUMP_FAILED_READY_CHECK = 25
JUMP_RESULT_JUMP_FAILED_RECALL_BLOCKED = 15
JUMP_RESULT_JUMP_FAILED_SOCIAL_TARGET_ZONE_COLLECTIBLE_LOCKED = 24
JUMP_RESULT_JUMP_FAILED_TOO_DIFFICULT = 6
JUMP_RESULT_JUMP_FAILED_ZONE_COLLECTIBLE = 14
JUMP_RESULT_JUMP_FAILED_ZONE_REQUIREMENT = 13
JUMP_RESULT_LOCAL_JUMP_SUCCESSFUL = 0
JUMP_RESULT_NO_JUMP_PERMISSION = 2
JUMP_RESULT_REMOTE_JUMP_INITIATED = 1
