--- @meta JusticeSkillEvent

--- @alias JusticeSkillEvent integer
--- | `JUSTICE_SKILL_FENCE` # 3
--- | `JUSTICE_SKILL_LOCKPICK` # 2
--- | `JUSTICE_SKILL_NONE` # 0
--- | `JUSTICE_SKILL_PICKPOCKET` # 1

JUSTICE_SKILL_FENCE = 3
JUSTICE_SKILL_LOCKPICK = 2
JUSTICE_SKILL_NONE = 0
JUSTICE_SKILL_PICKPOCKET = 1
