--- @meta KeepType

--- @alias KeepType integer
--- | `KEEPTYPE_ARTIFACT_GATE` # 4
--- | `KEEPTYPE_ARTIFACT_KEEP` # 3
--- | `KEEPTYPE_BORDER_KEEP` # 2
--- | `KEEPTYPE_BRIDGE` # 8
--- | `KEEPTYPE_IMPERIAL_CITY_DISTRICT` # 6
--- | `KEEPTYPE_KEEP` # 0
--- | `KEEPTYPE_MILEGATE` # 9
--- | `KEEPTYPE_OUTPOST` # 5
--- | `KEEPTYPE_RESOURCE` # 1
--- | `KEEPTYPE_TOWN` # 7

KEEPTYPE_ARTIFACT_GATE = 4
KEEPTYPE_ARTIFACT_KEEP = 3
KEEPTYPE_BORDER_KEEP = 2
KEEPTYPE_BRIDGE = 8
KEEPTYPE_IMPERIAL_CITY_DISTRICT = 6
KEEPTYPE_KEEP = 0
KEEPTYPE_MILEGATE = 9
KEEPTYPE_OUTPOST = 5
KEEPTYPE_RESOURCE = 1
KEEPTYPE_TOWN = 7
