--- @meta KeepRecallStoneUseResult

--- @alias KeepRecallStoneUseResult integer
--- | `KEEP_RECALL_STONE_USE_RESULT_ALREADY_RECALLING` # 8
--- | `KEEP_RECALL_STONE_USE_RESULT_CARRYING_SCROLL` # 7
--- | `KEEP_RECALL_STONE_USE_RESULT_DEAD` # 6
--- | `KEEP_RECALL_STONE_USE_RESULT_FAILURE` # 1
--- | `KEEP_RECALL_STONE_USE_RESULT_INVALID_ZONE` # 2
--- | `KEEP_RECALL_STONE_USE_RESULT_IN_COMBAT` # 4
--- | `KEEP_RECALL_STONE_USE_RESULT_NEAR_KEEP` # 3
--- | `KEEP_RECALL_STONE_USE_RESULT_REQUIRES_ITEM` # 5
--- | `KEEP_RECALL_STONE_USE_RESULT_SUCCESS` # 0

KEEP_RECALL_STONE_USE_RESULT_ALREADY_RECALLING = 8
KEEP_RECALL_STONE_USE_RESULT_CARRYING_SCROLL = 7
KEEP_RECALL_STONE_USE_RESULT_DEAD = 6
KEEP_RECALL_STONE_USE_RESULT_FAILURE = 1
KEEP_RECALL_STONE_USE_RESULT_INVALID_ZONE = 2
KEEP_RECALL_STONE_USE_RESULT_IN_COMBAT = 4
KEEP_RECALL_STONE_USE_RESULT_NEAR_KEEP = 3
KEEP_RECALL_STONE_USE_RESULT_REQUIRES_ITEM = 5
KEEP_RECALL_STONE_USE_RESULT_SUCCESS = 0
