--- @meta KeepTooltipColors

--- @alias KeepTooltipColors integer
--- | `KEEP_TOOLTIP_COLOR_ACCESSIBLE` # 3
--- | `KEEP_TOOLTIP_COLOR_ATTACK_LINE` # 1
--- | `KEEP_TOOLTIP_COLOR_AT_KEEP` # 5
--- | `KEEP_TOOLTIP_COLOR_NAME` # 0
--- | `KEEP_TOOLTIP_COLOR_NORMAL_LINE` # 2
--- | `KEEP_TOOLTIP_COLOR_NOT_ACCESSIBLE` # 4
--- | `KEEP_TOOLTIP_COLOR_OWNER` # 6
--- | `KEEP_TOOLTIP_COLOR_UNCLAIMED` # 7
--- | `KEEP_TOOLTIP_COLOR_UNIDIRECTIONALLY_ACCESSIBLE` # 8

KEEP_TOOLTIP_COLOR_ACCESSIBLE = 3
KEEP_TOOLTIP_COLOR_ATTACK_LINE = 1
KEEP_TOOLTIP_COLOR_AT_KEEP = 5
KEEP_TOOLTIP_COLOR_NAME = 0
KEEP_TOOLTIP_COLOR_NORMAL_LINE = 2
KEEP_TOOLTIP_COLOR_NOT_ACCESSIBLE = 4
KEEP_TOOLTIP_COLOR_OWNER = 6
KEEP_TOOLTIP_COLOR_UNCLAIMED = 7
KEEP_TOOLTIP_COLOR_UNIDIRECTIONALLY_ACCESSIBLE = 8
