--- @meta KeepPieceDirectionalAccess

--- @alias KeepPieceDirectionalAccess integer
--- | `KEEP_PIECE_DIRECTIONAL_ACCESS_BIDIRECTIONAL` # 3
--- | `KEEP_PIECE_DIRECTIONAL_ACCESS_BLOCKED` # 1
--- | `KEEP_PIECE_DIRECTIONAL_ACCESS_IGNORE` # 0
--- | `KEEP_PIECE_DIRECTIONAL_ACCESS_UNIDIRECTIONAL` # 2

KEEP_PIECE_DIRECTIONAL_ACCESS_BIDIRECTIONAL = 3
KEEP_PIECE_DIRECTIONAL_ACCESS_BLOCKED = 1
KEEP_PIECE_DIRECTIONAL_ACCESS_IGNORE = 0
KEEP_PIECE_DIRECTIONAL_ACCESS_UNIDIRECTIONAL = 2
