--- @meta KeepUpgradeLine

--- @alias KeepUpgradeLine integer
--- | `KEEP_UPGRADE_LINE_DEFENSIVE` # 5
--- | `KEEP_UPGRADE_LINE_FOOD` # 2
--- | `KEEP_UPGRADE_LINE_NONE` # 0
--- | `KEEP_UPGRADE_LINE_ORE` # 3
--- | `KEEP_UPGRADE_LINE_PRODUCTION` # 4
--- | `KEEP_UPGRADE_LINE_WOOD` # 1

KEEP_UPGRADE_LINE_DEFENSIVE = 5
KEEP_UPGRADE_LINE_FOOD = 2
KEEP_UPGRADE_LINE_NONE = 0
KEEP_UPGRADE_LINE_ORE = 3
KEEP_UPGRADE_LINE_PRODUCTION = 4
KEEP_UPGRADE_LINE_WOOD = 1
