--- @meta KeybindDisplayMode

--- @alias KeybindDisplayMode integer
--- | `KEYBIND_DISPLAY_MODE_ALWAYS_GAMEPAD` # 1
--- | `KEYBIND_DISPLAY_MODE_ALWAYS_KEYBOARD` # 0
--- | `KEYBIND_DISPLAY_MODE_AUTOMATIC` # 2

KEYBIND_DISPLAY_MODE_ALWAYS_GAMEPAD = 1
KEYBIND_DISPLAY_MODE_ALWAYS_KEYBOARD = 0
KEYBIND_DISPLAY_MODE_AUTOMATIC = 2
