--- @meta LeaderboardColors

--- @alias LeaderboardColors integer
--- | `LEADERBOARD_COLORS_NAME` # 4
--- | `LEADERBOARD_COLORS_PLAYER_NAME` # 3
--- | `LEADERBOARD_COLORS_TOP_100_BANNER_TEXT` # 2
--- | `LEADERBOARD_COLORS_TOP_20_BANNER_TEXT` # 0
--- | `LEADERBOARD_COLORS_TOP_50_BANNER_TEXT` # 1

LEADERBOARD_COLORS_NAME = 4
LEADERBOARD_COLORS_PLAYER_NAME = 3
LEADERBOARD_COLORS_TOP_100_BANNER_TEXT = 2
LEADERBOARD_COLORS_TOP_20_BANNER_TEXT = 0
LEADERBOARD_COLORS_TOP_50_BANNER_TEXT = 1
