--- @meta LeaderboardType

--- @alias LeaderboardType integer
--- | `LEADERBOARD_TYPE_ALLIANCE` # 2
--- | `LEADERBOARD_TYPE_BATTLEGROUND` # 4
--- | `LEADERBOARD_TYPE_CLASS` # 1
--- | `LEADERBOARD_TYPE_ENDLESS_DUNGEON_CLASS` # 7
--- | `LEADERBOARD_TYPE_ENDLESS_DUNGEON_OVERALL` # 6
--- | `LEADERBOARD_TYPE_HOUSE` # 3
--- | `LEADERBOARD_TYPE_OVERALL` # 0
--- | `LEADERBOARD_TYPE_TRIBUTE` # 5

LEADERBOARD_TYPE_ALLIANCE = 2
LEADERBOARD_TYPE_BATTLEGROUND = 4
LEADERBOARD_TYPE_CLASS = 1
LEADERBOARD_TYPE_ENDLESS_DUNGEON_CLASS = 7
LEADERBOARD_TYPE_ENDLESS_DUNGEON_OVERALL = 6
LEADERBOARD_TYPE_HOUSE = 3
LEADERBOARD_TYPE_OVERALL = 0
LEADERBOARD_TYPE_TRIBUTE = 5
