--- @meta LeaderboardScoreNotificationType

--- @alias LeaderboardScoreNotificationType integer
--- | `LEADERBOARD_SCORE_NOTIFICATION_TYPE_ENDLESS_DUNGEON` # 1
--- | `LEADERBOARD_SCORE_NOTIFICATION_TYPE_RAID` # 0

LEADERBOARD_SCORE_NOTIFICATION_TYPE_ENDLESS_DUNGEON = 1
LEADERBOARD_SCORE_NOTIFICATION_TYPE_RAID = 0
