--- @meta LeaveCampaignQueueResponseType

--- @alias LeaveCampaignQueueResponseType integer
--- | `LEAVE_CAMPAIGN_QUEUE_ERROR_INTERNAL_ERROR` # 2
--- | `LEAVE_CAMPAIGN_QUEUE_ERROR_INVALID_CAMPAIGN` # 4
--- | `LEAVE_CAMPAIGN_QUEUE_ERROR_NONE` # 0
--- | `LEAVE_CAMPAIGN_QUEUE_ERROR_NOT_GROUP_LEADER` # 5
--- | `LEAVE_CAMPAIGN_QUEUE_ERROR_NOT_QUEUED_FOR_ANYTHING` # 3
--- | `LEAVE_CAMPAIGN_QUEUE_ERROR_NOT_QUEUED_FOR_CAMPAIGN` # 1

LEAVE_CAMPAIGN_QUEUE_ERROR_INTERNAL_ERROR = 2
LEAVE_CAMPAIGN_QUEUE_ERROR_INVALID_CAMPAIGN = 4
LEAVE_CAMPAIGN_QUEUE_ERROR_NONE = 0
LEAVE_CAMPAIGN_QUEUE_ERROR_NOT_GROUP_LEADER = 5
LEAVE_CAMPAIGN_QUEUE_ERROR_NOT_QUEUED_FOR_ANYTHING = 3
LEAVE_CAMPAIGN_QUEUE_ERROR_NOT_QUEUED_FOR_CAMPAIGN = 1
