--- @meta LFGActivity

--- @alias LFGActivity integer
--- | `LFG_ACTIVITY_ARENA` # 12
--- | `LFG_ACTIVITY_AVA` # 1
--- | `LFG_ACTIVITY_BATTLE_GROUND_CHAMPION` # 5
--- | `LFG_ACTIVITY_BATTLE_GROUND_LOW_LEVEL` # 8
--- | `LFG_ACTIVITY_BATTLE_GROUND_NON_CHAMPION` # 7
--- | `LFG_ACTIVITY_DUNGEON` # 2
--- | `LFG_ACTIVITY_ENDLESS_DUNGEON` # 13
--- | `LFG_ACTIVITY_EXPLORATION` # 11
--- | `LFG_ACTIVITY_HOME_SHOW` # 6
--- | `LFG_ACTIVITY_INVALID` # 0
--- | `LFG_ACTIVITY_MASTER_DUNGEON` # 3
--- | `LFG_ACTIVITY_TRIAL` # 4
--- | `LFG_ACTIVITY_TRIBUTE_CASUAL` # 10
--- | `LFG_ACTIVITY_TRIBUTE_COMPETITIVE` # 9

LFG_ACTIVITY_ARENA = 12
LFG_ACTIVITY_AVA = 1
LFG_ACTIVITY_BATTLE_GROUND_CHAMPION = 5
LFG_ACTIVITY_BATTLE_GROUND_LOW_LEVEL = 8
LFG_ACTIVITY_BATTLE_GROUND_NON_CHAMPION = 7
LFG_ACTIVITY_DUNGEON = 2
LFG_ACTIVITY_ENDLESS_DUNGEON = 13
LFG_ACTIVITY_EXPLORATION = 11
LFG_ACTIVITY_HOME_SHOW = 6
LFG_ACTIVITY_INVALID = 0
LFG_ACTIVITY_MASTER_DUNGEON = 3
LFG_ACTIVITY_TRIAL = 4
LFG_ACTIVITY_TRIBUTE_CASUAL = 10
LFG_ACTIVITY_TRIBUTE_COMPETITIVE = 9
