--- @meta LFGCooldownType

--- @alias LFGCooldownType integer
--- | `LFG_COOLDOWN_ACTIVITY_STARTED` # 5
--- | `LFG_COOLDOWN_BATTLEGROUND_DESERTED` # 6
--- | `LFG_COOLDOWN_BATTLEGROUND_REWARD_GRANTED` # 7
--- | `LFG_COOLDOWN_DUNGEON_LEFT` # 2
--- | `LFG_COOLDOWN_DUNGEON_REWARD_GRANTED` # 4
--- | `LFG_COOLDOWN_INVALID` # 0
--- | `LFG_COOLDOWN_QUEUE_LEFT` # 1
--- | `LFG_COOLDOWN_TRIAL_LEFT` # 3
--- | `LFG_COOLDOWN_TRIBUTE_DESERTED` # 9
--- | `LFG_COOLDOWN_TRIBUTE_REWARD_GRANTED` # 8

LFG_COOLDOWN_ACTIVITY_STARTED = 5
LFG_COOLDOWN_BATTLEGROUND_DESERTED = 6
LFG_COOLDOWN_BATTLEGROUND_REWARD_GRANTED = 7
LFG_COOLDOWN_DUNGEON_LEFT = 2
LFG_COOLDOWN_DUNGEON_REWARD_GRANTED = 4
LFG_COOLDOWN_INVALID = 0
LFG_COOLDOWN_QUEUE_LEFT = 1
LFG_COOLDOWN_TRIAL_LEFT = 3
LFG_COOLDOWN_TRIBUTE_DESERTED = 9
LFG_COOLDOWN_TRIBUTE_REWARD_GRANTED = 8
