--- @meta LFGGroupType

--- @alias LFGGroupType integer
--- | `LFG_GROUP_TYPE_LARGE` # 2
--- | `LFG_GROUP_TYPE_MEDIUM` # 1
--- | `LFG_GROUP_TYPE_NONE` # 3
--- | `LFG_GROUP_TYPE_REGULAR` # 0

LFG_GROUP_TYPE_LARGE = 2
LFG_GROUP_TYPE_MEDIUM = 1
LFG_GROUP_TYPE_NONE = 3
LFG_GROUP_TYPE_REGULAR = 0
