--- @meta LFGItemRewardType

--- @alias LFGItemRewardType integer
--- | `LFG_ITEM_REWARD_TYPE_DAILY` # 2
--- | `LFG_ITEM_REWARD_TYPE_NONE` # 0
--- | `LFG_ITEM_REWARD_TYPE_STANDARD` # 1

LFG_ITEM_REWARD_TYPE_DAILY = 2
LFG_ITEM_REWARD_TYPE_NONE = 0
LFG_ITEM_REWARD_TYPE_STANDARD = 1
