--- @meta LFGReadyCheckCancelReason

--- @alias LFGReadyCheckCancelReason integer
--- | `LFG_READY_CHECK_CANCEL_REASON_ACTIVITY_NO_LONGER_VALID` # 5
--- | `LFG_READY_CHECK_CANCEL_REASON_GROUP_FORMED_SUCCESSFULLY` # 4
--- | `LFG_READY_CHECK_CANCEL_REASON_GROUP_MEMBER_CANCELED` # 3
--- | `LFG_READY_CHECK_CANCEL_REASON_GROUP_NOT_VIABLE` # 2
--- | `LFG_READY_CHECK_CANCEL_REASON_GROUP_REPLACED_IN_QUEUE` # 1
--- | `LFG_READY_CHECK_CANCEL_REASON_NOT_IN_READY_CHECK` # 0

LFG_READY_CHECK_CANCEL_REASON_ACTIVITY_NO_LONGER_VALID = 5
LFG_READY_CHECK_CANCEL_REASON_GROUP_FORMED_SUCCESSFULLY = 4
LFG_READY_CHECK_CANCEL_REASON_GROUP_MEMBER_CANCELED = 3
LFG_READY_CHECK_CANCEL_REASON_GROUP_NOT_VIABLE = 2
LFG_READY_CHECK_CANCEL_REASON_GROUP_REPLACED_IN_QUEUE = 1
LFG_READY_CHECK_CANCEL_REASON_NOT_IN_READY_CHECK = 0
