--- @meta LFGReadyCheckState

--- @alias LFGReadyCheckState integer
--- | `LFG_READY_CHECK_STATE_FORM_GROUP` # 4
--- | `LFG_READY_CHECK_STATE_IN_READY_CHECK` # 1
--- | `LFG_READY_CHECK_STATE_IN_READY_CHECK_BATTLEGROUND_TEST` # 9
--- | `LFG_READY_CHECK_STATE_IN_TRANSIT_TO_BATTLEGROUND` # 10
--- | `LFG_READY_CHECK_STATE_LAUNCHING_BATTLEGROUND_INSTANCE` # 6
--- | `LFG_READY_CHECK_STATE_NOT_IN_READY_CHECK` # 0
--- | `LFG_READY_CHECK_STATE_PLAYER_ACCEPTED` # 3
--- | `LFG_READY_CHECK_STATE_PLAYER_DECLINED` # 2
--- | `LFG_READY_CHECK_STATE_QUEUEDTEST_BATTLEGROUND_LAUNCH` # 8
--- | `LFG_READY_CHECK_STATE_QUEUE_CANCELED` # 11
--- | `LFG_READY_CHECK_STATE_TIMEOUT_CANCEL` # 5
--- | `LFG_READY_CHECK_STATE_TRANSFER_TO_BATTLEGROUND_INSTANCE` # 7

LFG_READY_CHECK_STATE_FORM_GROUP = 4
LFG_READY_CHECK_STATE_IN_READY_CHECK = 1
LFG_READY_CHECK_STATE_IN_READY_CHECK_BATTLEGROUND_TEST = 9
LFG_READY_CHECK_STATE_IN_TRANSIT_TO_BATTLEGROUND = 10
LFG_READY_CHECK_STATE_LAUNCHING_BATTLEGROUND_INSTANCE = 6
LFG_READY_CHECK_STATE_NOT_IN_READY_CHECK = 0
LFG_READY_CHECK_STATE_PLAYER_ACCEPTED = 3
LFG_READY_CHECK_STATE_PLAYER_DECLINED = 2
LFG_READY_CHECK_STATE_QUEUEDTEST_BATTLEGROUND_LAUNCH = 8
LFG_READY_CHECK_STATE_QUEUE_CANCELED = 11
LFG_READY_CHECK_STATE_TIMEOUT_CANCEL = 5
LFG_READY_CHECK_STATE_TRANSFER_TO_BATTLEGROUND_INSTANCE = 7
