--- @meta LinkType

--- @alias LinkType integer
--- | `LINK_TYPE_ABILITY` # 9
--- | `LINK_TYPE_ACHIEVEMENT` # 2
--- | `LINK_TYPE_BOOK` # 3
--- | `LINK_TYPE_COLLECTIBLE` # 4
--- | `LINK_TYPE_CRAFTED_ABILITY` # 10
--- | `LINK_TYPE_GUILD` # 6
--- | `LINK_TYPE_HELP` # 7
--- | `LINK_TYPE_HOUSING` # 8
--- | `LINK_TYPE_INVALID` # 0
--- | `LINK_TYPE_ITEM` # 1
--- | `LINK_TYPE_QUEST_ITEM` # 5

LINK_TYPE_ABILITY = 9
LINK_TYPE_ACHIEVEMENT = 2
LINK_TYPE_BOOK = 3
LINK_TYPE_COLLECTIBLE = 4
LINK_TYPE_CRAFTED_ABILITY = 10
LINK_TYPE_GUILD = 6
LINK_TYPE_HELP = 7
LINK_TYPE_HOUSING = 8
LINK_TYPE_INVALID = 0
LINK_TYPE_ITEM = 1
LINK_TYPE_QUEST_ITEM = 5
