--- @meta LoadingSystem

--- @alias LoadingSystem integer
--- | `LOADING_SYSTEM_CHARACTER_ACTIVATED` # 10
--- | `LOADING_SYSTEM_CHARACTER_GEOMETRY` # 1
--- | `LOADING_SYSTEM_DYNAMIC_OBJECTS` # 5
--- | `LOADING_SYSTEM_FIXTURE_ASSETS` # 4
--- | `LOADING_SYSTEM_FIXTURE_PHYSICS` # 13
--- | `LOADING_SYSTEM_GAME_DATA` # 8
--- | `LOADING_SYSTEM_KEEPS` # 3
--- | `LOADING_SYSTEM_PLAYER` # 0
--- | `LOADING_SYSTEM_RENDERER` # 7
--- | `LOADING_SYSTEM_RESUME_FROM_SUSPEND` # 12
--- | `LOADING_SYSTEM_SHARED_CHARACTER_OBJECT` # 11
--- | `LOADING_SYSTEM_TERRAIN_GEOMETRY` # 2
--- | `LOADING_SYSTEM_TEXTURES` # 9
--- | `LOADING_SYSTEM_USER_INTERFACE` # 6

LOADING_SYSTEM_CHARACTER_ACTIVATED = 10
LOADING_SYSTEM_CHARACTER_GEOMETRY = 1
LOADING_SYSTEM_DYNAMIC_OBJECTS = 5
LOADING_SYSTEM_FIXTURE_ASSETS = 4
LOADING_SYSTEM_FIXTURE_PHYSICS = 13
LOADING_SYSTEM_GAME_DATA = 8
LOADING_SYSTEM_KEEPS = 3
LOADING_SYSTEM_PLAYER = 0
LOADING_SYSTEM_RENDERER = 7
LOADING_SYSTEM_RESUME_FROM_SUSPEND = 12
LOADING_SYSTEM_SHARED_CHARACTER_OBJECT = 11
LOADING_SYSTEM_TERRAIN_GEOMETRY = 2
LOADING_SYSTEM_TEXTURES = 9
LOADING_SYSTEM_USER_INTERFACE = 6
