--- @meta LockQuality

--- @alias LockQuality integer
--- | `LOCK_QUALITY_ADVANCED` # 3
--- | `LOCK_QUALITY_IMPOSSIBLE` # 5
--- | `LOCK_QUALITY_INTERMEDIATE` # 2
--- | `LOCK_QUALITY_MASTER` # 4
--- | `LOCK_QUALITY_NONE` # 0
--- | `LOCK_QUALITY_PRACTICE` # 7
--- | `LOCK_QUALITY_SIMPLE` # 1
--- | `LOCK_QUALITY_TRIVIAL` # 6

LOCK_QUALITY_ADVANCED = 3
LOCK_QUALITY_IMPOSSIBLE = 5
LOCK_QUALITY_INTERMEDIATE = 2
LOCK_QUALITY_MASTER = 4
LOCK_QUALITY_NONE = 0
LOCK_QUALITY_PRACTICE = 7
LOCK_QUALITY_SIMPLE = 1
LOCK_QUALITY_TRIVIAL = 6
