--- @meta LoginStatus

--- @alias LoginStatus integer
--- | `LOGIN_STATUS_AUTH_FAILURE` # 3
--- | `LOGIN_STATUS_AUTH_LOCKED` # 14
--- | `LOGIN_STATUS_AUTH_SUCCESS` # 2
--- | `LOGIN_STATUS_AUTH_WAITING` # 1
--- | `LOGIN_STATUS_CANCELLED` # 7
--- | `LOGIN_STATUS_CONNECTED` # 8
--- | `LOGIN_STATUS_DISCONNECTED` # 9
--- | `LOGIN_STATUS_INVALID_STATE` # 0
--- | `LOGIN_STATUS_LEGAL_DOC_ACCEPTANCE_FAILED` # 24
--- | `LOGIN_STATUS_LEGAL_DOC_ACCEPTANCE_PENDING` # 22
--- | `LOGIN_STATUS_LEGAL_DOC_ACCEPTANCE_SUCCESS` # 23
--- | `LOGIN_STATUS_LEGAL_DOC_NOT_ACCEPTED` # 21
--- | `LOGIN_STATUS_LINK_ACCOUNT_FAILED` # 27
--- | `LOGIN_STATUS_LINK_ACCOUNT_PENDING` # 25
--- | `LOGIN_STATUS_LINK_ACCOUNT_SUCCESS` # 26
--- | `LOGIN_STATUS_MASTER_ACCOUNT_CREATE_FAILED` # 20
--- | `LOGIN_STATUS_MASTER_ACCOUNT_CREATE_PENDING` # 18
--- | `LOGIN_STATUS_MASTER_ACCOUNT_CREATE_SUCCESS` # 19
--- | `LOGIN_STATUS_MASTER_ACCOUNT_NOT_CREATED` # 17
--- | `LOGIN_STATUS_OTP_FAILED` # 11
--- | `LOGIN_STATUS_OTP_LOCKED` # 12
--- | `LOGIN_STATUS_OTP_PENDING` # 10
--- | `LOGIN_STATUS_OTP_SUCCESS` # 13
--- | `LOGIN_STATUS_OVERFLOW_KICK_WAITING` # 16
--- | `LOGIN_STATUS_OVERFLOW_WAITING` # 15
--- | `LOGIN_STATUS_RESERVATION_FAILURE` # 6
--- | `LOGIN_STATUS_RESERVATION_SUCCESS` # 5
--- | `LOGIN_STATUS_RESERVATION_WAITING` # 4

LOGIN_STATUS_AUTH_FAILURE = 3
LOGIN_STATUS_AUTH_LOCKED = 14
LOGIN_STATUS_AUTH_SUCCESS = 2
LOGIN_STATUS_AUTH_WAITING = 1
LOGIN_STATUS_CANCELLED = 7
LOGIN_STATUS_CONNECTED = 8
LOGIN_STATUS_DISCONNECTED = 9
LOGIN_STATUS_INVALID_STATE = 0
LOGIN_STATUS_LEGAL_DOC_ACCEPTANCE_FAILED = 24
LOGIN_STATUS_LEGAL_DOC_ACCEPTANCE_PENDING = 22
LOGIN_STATUS_LEGAL_DOC_ACCEPTANCE_SUCCESS = 23
LOGIN_STATUS_LEGAL_DOC_NOT_ACCEPTED = 21
LOGIN_STATUS_LINK_ACCOUNT_FAILED = 27
LOGIN_STATUS_LINK_ACCOUNT_PENDING = 25
LOGIN_STATUS_LINK_ACCOUNT_SUCCESS = 26
LOGIN_STATUS_MASTER_ACCOUNT_CREATE_FAILED = 20
LOGIN_STATUS_MASTER_ACCOUNT_CREATE_PENDING = 18
LOGIN_STATUS_MASTER_ACCOUNT_CREATE_SUCCESS = 19
LOGIN_STATUS_MASTER_ACCOUNT_NOT_CREATED = 17
LOGIN_STATUS_OTP_FAILED = 11
LOGIN_STATUS_OTP_LOCKED = 12
LOGIN_STATUS_OTP_PENDING = 10
LOGIN_STATUS_OTP_SUCCESS = 13
LOGIN_STATUS_OVERFLOW_KICK_WAITING = 16
LOGIN_STATUS_OVERFLOW_WAITING = 15
LOGIN_STATUS_RESERVATION_FAILURE = 6
LOGIN_STATUS_RESERVATION_SUCCESS = 5
LOGIN_STATUS_RESERVATION_WAITING = 4
