--- @meta LootItemType

--- @alias LootItemType integer
--- | `LOOT_TYPE_ANTIQUITY_LEAD` # 12
--- | `LOOT_TYPE_ANY` # 0
--- | `LOOT_TYPE_ARCHIVAL_FORTUNES` # 14
--- | `LOOT_TYPE_CHAOTIC_CREATIA` # 7
--- | `LOOT_TYPE_COLLECTIBLE` # 4
--- | `LOOT_TYPE_EVENT_TICKET` # 10
--- | `LOOT_TYPE_ITEM` # 1
--- | `LOOT_TYPE_MONEY` # 3
--- | `LOOT_TYPE_QUEST_ITEM` # 2
--- | `LOOT_TYPE_STYLE_STONES` # 8
--- | `LOOT_TYPE_TELVAR_STONES` # 5
--- | `LOOT_TYPE_TRIBUTE_CARD_UPGRADE` # 13
--- | `LOOT_TYPE_UNDAUNTED_KEYS` # 11
--- | `LOOT_TYPE_WRIT_VOUCHERS` # 6

LOOT_TYPE_ANTIQUITY_LEAD = 12
LOOT_TYPE_ANY = 0
LOOT_TYPE_ARCHIVAL_FORTUNES = 14
LOOT_TYPE_CHAOTIC_CREATIA = 7
LOOT_TYPE_COLLECTIBLE = 4
LOOT_TYPE_EVENT_TICKET = 10
LOOT_TYPE_ITEM = 1
LOOT_TYPE_MONEY = 3
LOOT_TYPE_QUEST_ITEM = 2
LOOT_TYPE_STYLE_STONES = 8
LOOT_TYPE_TELVAR_STONES = 5
LOOT_TYPE_TRIBUTE_CARD_UPGRADE = 13
LOOT_TYPE_UNDAUNTED_KEYS = 11
LOOT_TYPE_WRIT_VOUCHERS = 6
