--- @meta LootSetting

--- @alias LootSetting integer
--- | `LOOT_SETTING_AOE_LOOT` # 1
--- | `LOOT_SETTING_AUTO_ADD_TO_CRAFT_BAG` # 4
--- | `LOOT_SETTING_AUTO_LOOT` # 0
--- | `LOOT_SETTING_AUTO_LOOT_STOLEN` # 2
--- | `LOOT_SETTING_LOOT_HISTORY` # 3
--- | `LOOT_SETTING_PREVENT_STEALING_PLACED` # 5

LOOT_SETTING_AOE_LOOT = 1
LOOT_SETTING_AUTO_ADD_TO_CRAFT_BAG = 4
LOOT_SETTING_AUTO_LOOT = 0
LOOT_SETTING_AUTO_LOOT_STOLEN = 2
LOOT_SETTING_LOOT_HISTORY = 3
LOOT_SETTING_PREVENT_STEALING_PLACED = 5
