--- @meta LootCrateOpenResponse

--- @alias LootCrateOpenResponse integer
--- | `LOOT_CRATE_OPEN_RESPONSE_FAIL_NO_INVENTORY_SPACE` # 1
--- | `LOOT_CRATE_OPEN_RESPONSE_INVALID_LOOT_CRATE` # 4
--- | `LOOT_CRATE_OPEN_RESPONSE_INVALID_LOOT_CRATE_TIER` # 5
--- | `LOOT_CRATE_OPEN_RESPONSE_INVALID_MARKET_PRODUCT` # 2
--- | `LOOT_CRATE_OPEN_RESPONSE_NO_PRODUCT_SELECTED` # 3
--- | `LOOT_CRATE_OPEN_RESPONSE_OUT_OF_ALL_LOOT_CRATES` # 8
--- | `LOOT_CRATE_OPEN_RESPONSE_OUT_OF_LOOT_CRATE` # 6
--- | `LOOT_CRATE_OPEN_RESPONSE_SUCCESS` # 0
--- | `LOOT_CRATE_OPEN_RESPONSE_SYSTEM_UNAVAILABLE` # 7

LOOT_CRATE_OPEN_RESPONSE_FAIL_NO_INVENTORY_SPACE = 1
LOOT_CRATE_OPEN_RESPONSE_INVALID_LOOT_CRATE = 4
LOOT_CRATE_OPEN_RESPONSE_INVALID_LOOT_CRATE_TIER = 5
LOOT_CRATE_OPEN_RESPONSE_INVALID_MARKET_PRODUCT = 2
LOOT_CRATE_OPEN_RESPONSE_NO_PRODUCT_SELECTED = 3
LOOT_CRATE_OPEN_RESPONSE_OUT_OF_ALL_LOOT_CRATES = 8
LOOT_CRATE_OPEN_RESPONSE_OUT_OF_LOOT_CRATE = 6
LOOT_CRATE_OPEN_RESPONSE_SUCCESS = 0
LOOT_CRATE_OPEN_RESPONSE_SYSTEM_UNAVAILABLE = 7
