--- @meta LootItemResult

--- @alias LootItemResult integer
--- | `LOOT_ITEM_RESULT_ALREADY_OBTAINED` # 10
--- | `LOOT_ITEM_RESULT_INVENTORY_FULL` # 2
--- | `LOOT_ITEM_RESULT_INVENTORY_FULL_LOOT_ALL` # 3
--- | `LOOT_ITEM_RESULT_IS_UNIQUE` # 8
--- | `LOOT_ITEM_RESULT_IS_UNIQUE_LOOT_ALL` # 9
--- | `LOOT_ITEM_RESULT_NOT_AVAILABLE` # 6
--- | `LOOT_ITEM_RESULT_QUEST_RESTRICTED` # 1
--- | `LOOT_ITEM_RESULT_SUCCESS` # 0

LOOT_ITEM_RESULT_ALREADY_OBTAINED = 10
LOOT_ITEM_RESULT_INVENTORY_FULL = 2
LOOT_ITEM_RESULT_INVENTORY_FULL_LOOT_ALL = 3
LOOT_ITEM_RESULT_IS_UNIQUE = 8
LOOT_ITEM_RESULT_IS_UNIQUE_LOOT_ALL = 9
LOOT_ITEM_RESULT_NOT_AVAILABLE = 6
LOOT_ITEM_RESULT_QUEST_RESTRICTED = 1
LOOT_ITEM_RESULT_SUCCESS = 0
