--- @meta LootCratesSystemState

--- @alias LootCratesSystemState integer
--- | `LOOT_CRATES_SYSTEM_STATE_OFFLINE` # 0
--- | `LOOT_CRATES_SYSTEM_STATE_ONLINE` # 2
--- | `LOOT_CRATES_SYSTEM_STATE_OPEN_ONLY` # 1

LOOT_CRATES_SYSTEM_STATE_OFFLINE = 0
LOOT_CRATES_SYSTEM_STATE_ONLINE = 2
LOOT_CRATES_SYSTEM_STATE_OPEN_ONLY = 1
