--- @meta LootTableDropEntryType

--- @alias LootTableDropEntryType integer
--- | `LOOT_TABLE_ENTRY_TYPE_ANTIQUITY_LEAD` # 5
--- | `LOOT_TABLE_ENTRY_TYPE_COLLECTIBLE` # 2
--- | `LOOT_TABLE_ENTRY_TYPE_CURRENCY` # 3
--- | `LOOT_TABLE_ENTRY_TYPE_ITEM` # 0
--- | `LOOT_TABLE_ENTRY_TYPE_LOOT_CRATE` # 4
--- | `LOOT_TABLE_ENTRY_TYPE_LOOT_TABLE` # 1
--- | `LOOT_TABLE_ENTRY_TYPE_TRIBUTE_CARD_UPGRADE` # 6

LOOT_TABLE_ENTRY_TYPE_ANTIQUITY_LEAD = 5
LOOT_TABLE_ENTRY_TYPE_COLLECTIBLE = 2
LOOT_TABLE_ENTRY_TYPE_CURRENCY = 3
LOOT_TABLE_ENTRY_TYPE_ITEM = 0
LOOT_TABLE_ENTRY_TYPE_LOOT_CRATE = 4
LOOT_TABLE_ENTRY_TYPE_LOOT_TABLE = 1
LOOT_TABLE_ENTRY_TYPE_TRIBUTE_CARD_UPGRADE = 6
