--- @meta MacroEditorNodeType

--- @alias MacroEditorNodeType integer
--- | `MACRO_EDITOR_NODE_TYPE_COMMAND_MACRO` # 1
--- | `MACRO_EDITOR_NODE_TYPE_FOLDER` # 0
--- | `MACRO_EDITOR_NODE_TYPE_INFO` # 3
--- | `MACRO_EDITOR_NODE_TYPE_LUA_MACRO` # 2

MACRO_EDITOR_NODE_TYPE_COMMAND_MACRO = 1
MACRO_EDITOR_NODE_TYPE_FOLDER = 0
MACRO_EDITOR_NODE_TYPE_INFO = 3
MACRO_EDITOR_NODE_TYPE_LUA_MACRO = 2
