--- @meta MailExpirationType

--- @alias MailExpirationType integer
--- | `MAIL_EXPIRE_TYPE_DEFAULT` # 2
--- | `MAIL_EXPIRE_TYPE_EXTREMELY_LONG` # 5
--- | `MAIL_EXPIRE_TYPE_LONG` # 3
--- | `MAIL_EXPIRE_TYPE_SHORT` # 1
--- | `MAIL_EXPIRE_TYPE_VERY_LONG` # 4
--- | `MAIL_EXPIRE_TYPE_VERY_SHORT` # 0

MAIL_EXPIRE_TYPE_DEFAULT = 2
MAIL_EXPIRE_TYPE_EXTREMELY_LONG = 5
MAIL_EXPIRE_TYPE_LONG = 3
MAIL_EXPIRE_TYPE_SHORT = 1
MAIL_EXPIRE_TYPE_VERY_LONG = 4
MAIL_EXPIRE_TYPE_VERY_SHORT = 0
