--- @meta MailCategory

--- @alias MailCategory integer
--- | `MAIL_CATEGORY_INFO_ONLY_SYSTEM_MAIL` # 2
--- | `MAIL_CATEGORY_PLAYER_MAIL` # 0
--- | `MAIL_CATEGORY_SYSTEM_MAIL` # 1

MAIL_CATEGORY_INFO_ONLY_SYSTEM_MAIL = 2
MAIL_CATEGORY_PLAYER_MAIL = 0
MAIL_CATEGORY_SYSTEM_MAIL = 1
