--- @meta MailTakeAttachmentResult

--- @alias MailTakeAttachmentResult integer
--- | `MAIL_TAKE_ATTACHMENT_RESULT_FAIL_ALREADY_HAS_UNIQUE_ITEM` # 2
--- | `MAIL_TAKE_ATTACHMENT_RESULT_FAIL_NOTHING_TO_CLAIM` # 3
--- | `MAIL_TAKE_ATTACHMENT_RESULT_FAIL_NO_INVENTORY_SPACE` # 1
--- | `MAIL_TAKE_ATTACHMENT_RESULT_FAIL_SERVER_ERROR` # 4
--- | `MAIL_TAKE_ATTACHMENT_RESULT_SUCCESS` # 0

MAIL_TAKE_ATTACHMENT_RESULT_FAIL_ALREADY_HAS_UNIQUE_ITEM = 2
MAIL_TAKE_ATTACHMENT_RESULT_FAIL_NOTHING_TO_CLAIM = 3
MAIL_TAKE_ATTACHMENT_RESULT_FAIL_NO_INVENTORY_SPACE = 1
MAIL_TAKE_ATTACHMENT_RESULT_FAIL_SERVER_ERROR = 4
MAIL_TAKE_ATTACHMENT_RESULT_SUCCESS = 0
