--- @meta MailAttachmentResult

--- @alias MailAttachmentResult integer
--- | `MAIL_ATTACHMENT_RESULT_ALREADY_ATTACHED` # 1
--- | `MAIL_ATTACHMENT_RESULT_BOUND` # 2
--- | `MAIL_ATTACHMENT_RESULT_ITEM_NOT_FOUND` # 4
--- | `MAIL_ATTACHMENT_RESULT_LOCKED` # 3
--- | `MAIL_ATTACHMENT_RESULT_PLAYER_LOCKED` # 6
--- | `MAIL_ATTACHMENT_RESULT_STOLEN` # 5
--- | `MAIL_ATTACHMENT_RESULT_SUCCESS` # 0

MAIL_ATTACHMENT_RESULT_ALREADY_ATTACHED = 1
MAIL_ATTACHMENT_RESULT_BOUND = 2
MAIL_ATTACHMENT_RESULT_ITEM_NOT_FOUND = 4
MAIL_ATTACHMENT_RESULT_LOCKED = 3
MAIL_ATTACHMENT_RESULT_PLAYER_LOCKED = 6
MAIL_ATTACHMENT_RESULT_STOLEN = 5
MAIL_ATTACHMENT_RESULT_SUCCESS = 0
