--- @meta MapDisplayPinType

--- @alias MapDisplayPinType integer
--- | `MAP_PIN_TYPE_ACTIVE_COMPANION` # 226
--- | `MAP_PIN_TYPE_AGGRO` # 218
--- | `MAP_PIN_TYPE_ALDMERI_VS_DAGGERFALL_LARGE` # 197
--- | `MAP_PIN_TYPE_ALDMERI_VS_DAGGERFALL_MEDIUM` # 196
--- | `MAP_PIN_TYPE_ALDMERI_VS_DAGGERFALL_SMALL` # 195
--- | `MAP_PIN_TYPE_ALDMERI_VS_EBONHEART_LARGE` # 194
--- | `MAP_PIN_TYPE_ALDMERI_VS_EBONHEART_MEDIUM` # 193
--- | `MAP_PIN_TYPE_ALDMERI_VS_EBONHEART_SMALL` # 192
--- | `MAP_PIN_TYPE_ANTIQUITY_DIG_SITE` # 44
--- | `MAP_PIN_TYPE_ANTIQUITY_DIG_SITE_PING` # 188
--- | `MAP_PIN_TYPE_ARTIFACT_ALDMERI_DEFENSIVE` # 123
--- | `MAP_PIN_TYPE_ARTIFACT_ALDMERI_OFFENSIVE` # 122
--- | `MAP_PIN_TYPE_ARTIFACT_DAGGERFALL_DEFENSIVE` # 127
--- | `MAP_PIN_TYPE_ARTIFACT_DAGGERFALL_OFFENSIVE` # 126
--- | `MAP_PIN_TYPE_ARTIFACT_EBONHEART_DEFENSIVE` # 125
--- | `MAP_PIN_TYPE_ARTIFACT_EBONHEART_OFFENSIVE` # 124
--- | `MAP_PIN_TYPE_ARTIFACT_GATE_CLOSED_ALDMERI_DOMINION` # 160
--- | `MAP_PIN_TYPE_ARTIFACT_GATE_CLOSED_DAGGERFALL_COVENANT` # 162
--- | `MAP_PIN_TYPE_ARTIFACT_GATE_CLOSED_EBONHEART_PACT` # 161
--- | `MAP_PIN_TYPE_ARTIFACT_GATE_OPEN_ALDMERI_DOMINION` # 157
--- | `MAP_PIN_TYPE_ARTIFACT_GATE_OPEN_DAGGERFALL_COVENANT` # 159
--- | `MAP_PIN_TYPE_ARTIFACT_GATE_OPEN_EBONHEART_PACT` # 158
--- | `MAP_PIN_TYPE_ARTIFACT_KEEP_ALDMERI_DOMINION` # 154
--- | `MAP_PIN_TYPE_ARTIFACT_KEEP_DAGGERFALL_COVENANT` # 156
--- | `MAP_PIN_TYPE_ARTIFACT_KEEP_EBONHEART_PACT` # 155
--- | `MAP_PIN_TYPE_ARTIFACT_RETURN_ALDMERI` # 128
--- | `MAP_PIN_TYPE_ARTIFACT_RETURN_DAGGERFALL` # 129
--- | `MAP_PIN_TYPE_ARTIFACT_RETURN_EBONHEART` # 130
--- | `MAP_PIN_TYPE_ASSISTED_QUEST_CONDITION` # 10
--- | `MAP_PIN_TYPE_ASSISTED_QUEST_ENDING` # 12
--- | `MAP_PIN_TYPE_ASSISTED_QUEST_OPTIONAL_CONDITION` # 11
--- | `MAP_PIN_TYPE_ASSISTED_QUEST_REPEATABLE_CONDITION` # 13
--- | `MAP_PIN_TYPE_ASSISTED_QUEST_REPEATABLE_ENDING` # 15
--- | `MAP_PIN_TYPE_ASSISTED_QUEST_REPEATABLE_OPTIONAL_CONDITION` # 14
--- | `MAP_PIN_TYPE_ASSISTED_QUEST_ZONE_STORY_CONDITION` # 16
--- | `MAP_PIN_TYPE_ASSISTED_QUEST_ZONE_STORY_ENDING` # 18
--- | `MAP_PIN_TYPE_ASSISTED_QUEST_ZONE_STORY_OPTIONAL_CONDITION` # 17
--- | `MAP_PIN_TYPE_AUTO_MAP_NAVIGATION_PING` # 186
--- | `MAP_PIN_TYPE_AVA_CAPTURE_AREA_ALDMERI` # 52
--- | `MAP_PIN_TYPE_AVA_CAPTURE_AREA_AURA` # 111
--- | `MAP_PIN_TYPE_AVA_CAPTURE_AREA_DAGGERFALL` # 54
--- | `MAP_PIN_TYPE_AVA_CAPTURE_AREA_EBONHEART` # 53
--- | `MAP_PIN_TYPE_AVA_CAPTURE_AREA_NEUTRAL` # 51
--- | `MAP_PIN_TYPE_AVA_DAEDRIC_ARTIFACT_VOLENDRUNG_ALDMERI` # 119
--- | `MAP_PIN_TYPE_AVA_DAEDRIC_ARTIFACT_VOLENDRUNG_DAGGERFALL` # 121
--- | `MAP_PIN_TYPE_AVA_DAEDRIC_ARTIFACT_VOLENDRUNG_EBONHEART` # 120
--- | `MAP_PIN_TYPE_AVA_DAEDRIC_ARTIFACT_VOLENDRUNG_NEUTRAL` # 118
--- | `MAP_PIN_TYPE_AVA_TOWN_ALDMERI_DOMINION` # 168
--- | `MAP_PIN_TYPE_AVA_TOWN_DAGGERFALL_COVENANT` # 170
--- | `MAP_PIN_TYPE_AVA_TOWN_EBONHEART_PACT` # 169
--- | `MAP_PIN_TYPE_AVA_TOWN_GRAVEYARD_ACCESSIBLE` # 213
--- | `MAP_PIN_TYPE_AVA_TOWN_NEUTRAL` # 167
--- | `MAP_PIN_TYPE_BGPIN_CAPTURE_AREA_AURA` # 112
--- | `MAP_PIN_TYPE_BGPIN_CAPTURE_AREA_A_FIRE_DRAKES` # 60
--- | `MAP_PIN_TYPE_BGPIN_CAPTURE_AREA_A_NEUTRAL` # 59
--- | `MAP_PIN_TYPE_BGPIN_CAPTURE_AREA_A_PIT_DAEMONS` # 61
--- | `MAP_PIN_TYPE_BGPIN_CAPTURE_AREA_A_STORM_LORDS` # 62
--- | `MAP_PIN_TYPE_BGPIN_CAPTURE_AREA_B_FIRE_DRAKES` # 64
--- | `MAP_PIN_TYPE_BGPIN_CAPTURE_AREA_B_NEUTRAL` # 63
--- | `MAP_PIN_TYPE_BGPIN_CAPTURE_AREA_B_PIT_DAEMONS` # 65
--- | `MAP_PIN_TYPE_BGPIN_CAPTURE_AREA_B_STORM_LORDS` # 66
--- | `MAP_PIN_TYPE_BGPIN_CAPTURE_AREA_C_FIRE_DRAKES` # 68
--- | `MAP_PIN_TYPE_BGPIN_CAPTURE_AREA_C_NEUTRAL` # 67
--- | `MAP_PIN_TYPE_BGPIN_CAPTURE_AREA_C_PIT_DAEMONS` # 69
--- | `MAP_PIN_TYPE_BGPIN_CAPTURE_AREA_C_STORM_LORDS` # 70
--- | `MAP_PIN_TYPE_BGPIN_CAPTURE_AREA_D_FIRE_DRAKES` # 72
--- | `MAP_PIN_TYPE_BGPIN_CAPTURE_AREA_D_NEUTRAL` # 71
--- | `MAP_PIN_TYPE_BGPIN_CAPTURE_AREA_D_PIT_DAEMONS` # 73
--- | `MAP_PIN_TYPE_BGPIN_CAPTURE_AREA_D_STORM_LORDS` # 74
--- | `MAP_PIN_TYPE_BGPIN_CAPTURE_AREA_FIRE_DRAKES` # 56
--- | `MAP_PIN_TYPE_BGPIN_CAPTURE_AREA_NEUTRAL` # 55
--- | `MAP_PIN_TYPE_BGPIN_CAPTURE_AREA_PIT_DAEMONS` # 57
--- | `MAP_PIN_TYPE_BGPIN_CAPTURE_AREA_STORM_LORDS` # 58
--- | `MAP_PIN_TYPE_BGPIN_FLAG_FIRE_DRAKES` # 96
--- | `MAP_PIN_TYPE_BGPIN_FLAG_FIRE_DRAKES_AURA` # 115
--- | `MAP_PIN_TYPE_BGPIN_FLAG_NEUTRAL` # 95
--- | `MAP_PIN_TYPE_BGPIN_FLAG_NEUTRAL_AURA` # 114
--- | `MAP_PIN_TYPE_BGPIN_FLAG_PIT_DAEMONS` # 97
--- | `MAP_PIN_TYPE_BGPIN_FLAG_PIT_DAEMONS_AURA` # 116
--- | `MAP_PIN_TYPE_BGPIN_FLAG_RETURN_FIRE_DRAKES` # 103
--- | `MAP_PIN_TYPE_BGPIN_FLAG_RETURN_PIT_DAEMONS` # 104
--- | `MAP_PIN_TYPE_BGPIN_FLAG_RETURN_STORM_LORDS` # 105
--- | `MAP_PIN_TYPE_BGPIN_FLAG_SPAWN_FIRE_DRAKES` # 100
--- | `MAP_PIN_TYPE_BGPIN_FLAG_SPAWN_NEUTRAL` # 99
--- | `MAP_PIN_TYPE_BGPIN_FLAG_SPAWN_PIT_DAEMONS` # 101
--- | `MAP_PIN_TYPE_BGPIN_FLAG_SPAWN_STORM_LORDS` # 102
--- | `MAP_PIN_TYPE_BGPIN_FLAG_STORM_LORDS` # 98
--- | `MAP_PIN_TYPE_BGPIN_FLAG_STORM_LORDS_AURA` # 117
--- | `MAP_PIN_TYPE_BGPIN_MOBILE_CAPTURE_AREA_AURA` # 113
--- | `MAP_PIN_TYPE_BGPIN_MOBILE_CAPTURE_AREA_A_FIRE_DRAKES` # 80
--- | `MAP_PIN_TYPE_BGPIN_MOBILE_CAPTURE_AREA_A_NEUTRAL` # 79
--- | `MAP_PIN_TYPE_BGPIN_MOBILE_CAPTURE_AREA_A_PIT_DAEMONS` # 81
--- | `MAP_PIN_TYPE_BGPIN_MOBILE_CAPTURE_AREA_A_STORM_LORDS` # 82
--- | `MAP_PIN_TYPE_BGPIN_MOBILE_CAPTURE_AREA_B_FIRE_DRAKES` # 84
--- | `MAP_PIN_TYPE_BGPIN_MOBILE_CAPTURE_AREA_B_NEUTRAL` # 83
--- | `MAP_PIN_TYPE_BGPIN_MOBILE_CAPTURE_AREA_B_PIT_DAEMONS` # 85
--- | `MAP_PIN_TYPE_BGPIN_MOBILE_CAPTURE_AREA_B_STORM_LORDS` # 86
--- | `MAP_PIN_TYPE_BGPIN_MOBILE_CAPTURE_AREA_C_FIRE_DRAKES` # 88
--- | `MAP_PIN_TYPE_BGPIN_MOBILE_CAPTURE_AREA_C_NEUTRAL` # 87
--- | `MAP_PIN_TYPE_BGPIN_MOBILE_CAPTURE_AREA_C_PIT_DAEMONS` # 89
--- | `MAP_PIN_TYPE_BGPIN_MOBILE_CAPTURE_AREA_C_STORM_LORDS` # 90
--- | `MAP_PIN_TYPE_BGPIN_MOBILE_CAPTURE_AREA_D_FIRE_DRAKES` # 92
--- | `MAP_PIN_TYPE_BGPIN_MOBILE_CAPTURE_AREA_D_NEUTRAL` # 91
--- | `MAP_PIN_TYPE_BGPIN_MOBILE_CAPTURE_AREA_D_PIT_DAEMONS` # 93
--- | `MAP_PIN_TYPE_BGPIN_MOBILE_CAPTURE_AREA_D_STORM_LORDS` # 94
--- | `MAP_PIN_TYPE_BGPIN_MOBILE_CAPTURE_AREA_FIRE_DRAKES` # 76
--- | `MAP_PIN_TYPE_BGPIN_MOBILE_CAPTURE_AREA_NEUTRAL` # 75
--- | `MAP_PIN_TYPE_BGPIN_MOBILE_CAPTURE_AREA_PIT_DAEMONS` # 77
--- | `MAP_PIN_TYPE_BGPIN_MOBILE_CAPTURE_AREA_STORM_LORDS` # 78
--- | `MAP_PIN_TYPE_BGPIN_MURDERBALL_FIRE_DRAKES` # 108
--- | `MAP_PIN_TYPE_BGPIN_MURDERBALL_NEUTRAL` # 107
--- | `MAP_PIN_TYPE_BGPIN_MURDERBALL_PIT_DAEMONS` # 109
--- | `MAP_PIN_TYPE_BGPIN_MURDERBALL_SPAWN_NEUTRAL` # 106
--- | `MAP_PIN_TYPE_BGPIN_MURDERBALL_STORM_LORDS` # 110
--- | `MAP_PIN_TYPE_BORDER_KEEP_ALDMERI_DOMINION` # 151
--- | `MAP_PIN_TYPE_BORDER_KEEP_DAGGERFALL_COVENANT` # 153
--- | `MAP_PIN_TYPE_BORDER_KEEP_EBONHEART_PACT` # 152
--- | `MAP_PIN_TYPE_DARK_BROTHERHOOD_TARGET` # 220
--- | `MAP_PIN_TYPE_EBONHEART_VS_DAGGERFALL_LARGE` # 200
--- | `MAP_PIN_TYPE_EBONHEART_VS_DAGGERFALL_MEDIUM` # 199
--- | `MAP_PIN_TYPE_EBONHEART_VS_DAGGERFALL_SMALL` # 198
--- | `MAP_PIN_TYPE_FARM_ALDMERI_DOMINION` # 140
--- | `MAP_PIN_TYPE_FARM_DAGGERFALL_COVENANT` # 142
--- | `MAP_PIN_TYPE_FARM_EBONHEART_PACT` # 141
--- | `MAP_PIN_TYPE_FARM_NEUTRAL` # 139
--- | `MAP_PIN_TYPE_FAST_TRAVEL_BORDER_KEEP_ACCESSIBLE` # 202
--- | `MAP_PIN_TYPE_FAST_TRAVEL_KEEP_ACCESSIBLE` # 201
--- | `MAP_PIN_TYPE_FAST_TRAVEL_OUTPOST_ACCESSIBLE` # 203
--- | `MAP_PIN_TYPE_FAST_TRAVEL_WAYSHRINE` # 204
--- | `MAP_PIN_TYPE_FAST_TRAVEL_WAYSHRINE_CURRENT_LOC` # 205
--- | `MAP_PIN_TYPE_FORWARD_CAMP_ACCESSIBLE` # 209
--- | `MAP_PIN_TYPE_FORWARD_CAMP_ALDMERI_DOMINION` # 206
--- | `MAP_PIN_TYPE_FORWARD_CAMP_DAGGERFALL_COVENANT` # 208
--- | `MAP_PIN_TYPE_FORWARD_CAMP_EBONHEART_PACT` # 207
--- | `MAP_PIN_TYPE_GROUP` # 1
--- | `MAP_PIN_TYPE_GROUP_LEADER` # 2
--- | `MAP_PIN_TYPE_HARVEST_NODE` # 179
--- | `MAP_PIN_TYPE_IMPERIAL_DISTRICT_ALDMERI_DOMINION` # 164
--- | `MAP_PIN_TYPE_IMPERIAL_DISTRICT_DAGGERFALL_COVENANT` # 166
--- | `MAP_PIN_TYPE_IMPERIAL_DISTRICT_EBONHEART_PACT` # 165
--- | `MAP_PIN_TYPE_IMPERIAL_DISTRICT_GRAVEYARD_ACCESSIBLE` # 212
--- | `MAP_PIN_TYPE_IMPERIAL_DISTRICT_NEUTRAL` # 163
--- | `MAP_PIN_TYPE_INVALID` # 237
--- | `MAP_PIN_TYPE_KEEP_ALDMERI_DOMINION` # 132
--- | `MAP_PIN_TYPE_KEEP_ATTACKED_LARGE` # 176
--- | `MAP_PIN_TYPE_KEEP_ATTACKED_SMALL` # 177
--- | `MAP_PIN_TYPE_KEEP_BRIDGE` # 171
--- | `MAP_PIN_TYPE_KEEP_BRIDGE_IMPASSABLE` # 172
--- | `MAP_PIN_TYPE_KEEP_DAGGERFALL_COVENANT` # 134
--- | `MAP_PIN_TYPE_KEEP_EBONHEART_PACT` # 133
--- | `MAP_PIN_TYPE_KEEP_GRAVEYARD_ACCESSIBLE` # 210
--- | `MAP_PIN_TYPE_KEEP_MILEGATE` # 173
--- | `MAP_PIN_TYPE_KEEP_MILEGATE_CENTER_DESTROYED` # 174
--- | `MAP_PIN_TYPE_KEEP_MILEGATE_IMPASSABLE` # 175
--- | `MAP_PIN_TYPE_KEEP_NEUTRAL` # 131
--- | `MAP_PIN_TYPE_LOCATION` # 178
--- | `MAP_PIN_TYPE_MILL_ALDMERI_DOMINION` # 148
--- | `MAP_PIN_TYPE_MILL_DAGGERFALL_COVENANT` # 150
--- | `MAP_PIN_TYPE_MILL_EBONHEART_PACT` # 149
--- | `MAP_PIN_TYPE_MILL_NEUTRAL` # 147
--- | `MAP_PIN_TYPE_MINE_ALDMERI_DOMINION` # 144
--- | `MAP_PIN_TYPE_MINE_DAGGERFALL_COVENANT` # 146
--- | `MAP_PIN_TYPE_MINE_EBONHEART_PACT` # 145
--- | `MAP_PIN_TYPE_MINE_NEUTRAL` # 143
--- | `MAP_PIN_TYPE_NPC_FOLLOWER` # 182
--- | `MAP_PIN_TYPE_OUTPOST_ALDMERI_DOMINION` # 136
--- | `MAP_PIN_TYPE_OUTPOST_DAGGERFALL_COVENANT` # 138
--- | `MAP_PIN_TYPE_OUTPOST_EBONHEART_PACT` # 137
--- | `MAP_PIN_TYPE_OUTPOST_GRAVEYARD_ACCESSIBLE` # 214
--- | `MAP_PIN_TYPE_OUTPOST_NEUTRAL` # 135
--- | `MAP_PIN_TYPE_PING` # 183
--- | `MAP_PIN_TYPE_PLAYER` # 0
--- | `MAP_PIN_TYPE_PLAYER_CAMERA` # 235
--- | `MAP_PIN_TYPE_PLAYER_WAYPOINT` # 185
--- | `MAP_PIN_TYPE_POI_COMPLETE` # 40
--- | `MAP_PIN_TYPE_POI_SEEN` # 39
--- | `MAP_PIN_TYPE_POI_SUGGESTED` # 38
--- | `MAP_PIN_TYPE_QUEST_COMPLETE` # 6
--- | `MAP_PIN_TYPE_QUEST_CONDITION` # 28
--- | `MAP_PIN_TYPE_QUEST_ENDING` # 30
--- | `MAP_PIN_TYPE_QUEST_GIVE_ITEM` # 9
--- | `MAP_PIN_TYPE_QUEST_INTERACT` # 8
--- | `MAP_PIN_TYPE_QUEST_OFFER` # 3
--- | `MAP_PIN_TYPE_QUEST_OFFER_REPEATABLE` # 4
--- | `MAP_PIN_TYPE_QUEST_OFFER_ZONE_STORY` # 5
--- | `MAP_PIN_TYPE_QUEST_OPTIONAL_CONDITION` # 29
--- | `MAP_PIN_TYPE_QUEST_PING` # 187
--- | `MAP_PIN_TYPE_QUEST_REPEATABLE_CONDITION` # 31
--- | `MAP_PIN_TYPE_QUEST_REPEATABLE_ENDING` # 33
--- | `MAP_PIN_TYPE_QUEST_REPEATABLE_OPTIONAL_CONDITION` # 32
--- | `MAP_PIN_TYPE_QUEST_TALK_TO` # 7
--- | `MAP_PIN_TYPE_QUEST_ZONE_STORY_CONDITION` # 34
--- | `MAP_PIN_TYPE_QUEST_ZONE_STORY_ENDING` # 36
--- | `MAP_PIN_TYPE_QUEST_ZONE_STORY_OPTIONAL_CONDITION` # 35
--- | `MAP_PIN_TYPE_RALLY_POINT` # 184
--- | `MAP_PIN_TYPE_RESPAWN_BORDER_KEEP_ACCESSIBLE` # 211
--- | `MAP_PIN_TYPE_RESTRICTED_LINK_ALDMERI_DOMINION` # 215
--- | `MAP_PIN_TYPE_RESTRICTED_LINK_DAGGERFALL_COVENANT` # 217
--- | `MAP_PIN_TYPE_RESTRICTED_LINK_EBONHEART_PACT` # 216
--- | `MAP_PIN_TYPE_RETURN_ALDMERI_DOMINION` # 47
--- | `MAP_PIN_TYPE_RETURN_DAGGERFALL_COVENANT` # 49
--- | `MAP_PIN_TYPE_RETURN_EBONHEART_PACT` # 48
--- | `MAP_PIN_TYPE_RETURN_NEUTRAL` # 50
--- | `MAP_PIN_TYPE_SKYSHARD_COMPLETE` # 43
--- | `MAP_PIN_TYPE_SKYSHARD_SEEN` # 42
--- | `MAP_PIN_TYPE_SKYSHARD_SUGGESTED` # 41
--- | `MAP_PIN_TYPE_TARGET_MARKER_TYPE_EIGHT` # 234
--- | `MAP_PIN_TYPE_TARGET_MARKER_TYPE_FIVE` # 231
--- | `MAP_PIN_TYPE_TARGET_MARKER_TYPE_FOUR` # 230
--- | `MAP_PIN_TYPE_TARGET_MARKER_TYPE_ONE` # 227
--- | `MAP_PIN_TYPE_TARGET_MARKER_TYPE_SEVEN` # 233
--- | `MAP_PIN_TYPE_TARGET_MARKER_TYPE_SIX` # 232
--- | `MAP_PIN_TYPE_TARGET_MARKER_TYPE_THREE` # 229
--- | `MAP_PIN_TYPE_TARGET_MARKER_TYPE_TWO` # 228
--- | `MAP_PIN_TYPE_TIMELY_ESCAPE_NPC` # 219
--- | `MAP_PIN_TYPE_TRACKED_ANTIQUITY_DIG_SITE` # 45
--- | `MAP_PIN_TYPE_TRACKED_QUEST_CONDITION` # 19
--- | `MAP_PIN_TYPE_TRACKED_QUEST_ENDING` # 21
--- | `MAP_PIN_TYPE_TRACKED_QUEST_OFFER_ZONE_STORY` # 37
--- | `MAP_PIN_TYPE_TRACKED_QUEST_OPTIONAL_CONDITION` # 20
--- | `MAP_PIN_TYPE_TRACKED_QUEST_REPEATABLE_CONDITION` # 22
--- | `MAP_PIN_TYPE_TRACKED_QUEST_REPEATABLE_ENDING` # 24
--- | `MAP_PIN_TYPE_TRACKED_QUEST_REPEATABLE_OPTIONAL_CONDITION` # 23
--- | `MAP_PIN_TYPE_TRACKED_QUEST_ZONE_STORY_CONDITION` # 25
--- | `MAP_PIN_TYPE_TRACKED_QUEST_ZONE_STORY_ENDING` # 27
--- | `MAP_PIN_TYPE_TRACKED_QUEST_ZONE_STORY_OPTIONAL_CONDITION` # 26
--- | `MAP_PIN_TYPE_TRAINER` # 181
--- | `MAP_PIN_TYPE_TRI_BATTLE_LARGE` # 191
--- | `MAP_PIN_TYPE_TRI_BATTLE_MEDIUM` # 190
--- | `MAP_PIN_TYPE_TRI_BATTLE_SMALL` # 189
--- | `MAP_PIN_TYPE_UNIT_COMBAT_HEALTHY` # 223
--- | `MAP_PIN_TYPE_UNIT_COMBAT_WEAK` # 224
--- | `MAP_PIN_TYPE_UNIT_IDLE_HEALTHY` # 221
--- | `MAP_PIN_TYPE_UNIT_IDLE_WEAK` # 222
--- | `MAP_PIN_TYPE_VENDOR` # 180
--- | `MAP_PIN_TYPE_WORLD_EVENT_POI_ACTIVE` # 225
--- | `MAP_PIN_TYPE_ZONE_STORY_SUGGESTED_AREA` # 46

MAP_PIN_TYPE_ACTIVE_COMPANION = 226
MAP_PIN_TYPE_AGGRO = 218
MAP_PIN_TYPE_ALDMERI_VS_DAGGERFALL_LARGE = 197
MAP_PIN_TYPE_ALDMERI_VS_DAGGERFALL_MEDIUM = 196
MAP_PIN_TYPE_ALDMERI_VS_DAGGERFALL_SMALL = 195
MAP_PIN_TYPE_ALDMERI_VS_EBONHEART_LARGE = 194
MAP_PIN_TYPE_ALDMERI_VS_EBONHEART_MEDIUM = 193
MAP_PIN_TYPE_ALDMERI_VS_EBONHEART_SMALL = 192
MAP_PIN_TYPE_ANTIQUITY_DIG_SITE = 44
MAP_PIN_TYPE_ANTIQUITY_DIG_SITE_PING = 188
MAP_PIN_TYPE_ARTIFACT_ALDMERI_DEFENSIVE = 123
MAP_PIN_TYPE_ARTIFACT_ALDMERI_OFFENSIVE = 122
MAP_PIN_TYPE_ARTIFACT_DAGGERFALL_DEFENSIVE = 127
MAP_PIN_TYPE_ARTIFACT_DAGGERFALL_OFFENSIVE = 126
MAP_PIN_TYPE_ARTIFACT_EBONHEART_DEFENSIVE = 125
MAP_PIN_TYPE_ARTIFACT_EBONHEART_OFFENSIVE = 124
MAP_PIN_TYPE_ARTIFACT_GATE_CLOSED_ALDMERI_DOMINION = 160
MAP_PIN_TYPE_ARTIFACT_GATE_CLOSED_DAGGERFALL_COVENANT = 162
MAP_PIN_TYPE_ARTIFACT_GATE_CLOSED_EBONHEART_PACT = 161
MAP_PIN_TYPE_ARTIFACT_GATE_OPEN_ALDMERI_DOMINION = 157
MAP_PIN_TYPE_ARTIFACT_GATE_OPEN_DAGGERFALL_COVENANT = 159
MAP_PIN_TYPE_ARTIFACT_GATE_OPEN_EBONHEART_PACT = 158
MAP_PIN_TYPE_ARTIFACT_KEEP_ALDMERI_DOMINION = 154
MAP_PIN_TYPE_ARTIFACT_KEEP_DAGGERFALL_COVENANT = 156
MAP_PIN_TYPE_ARTIFACT_KEEP_EBONHEART_PACT = 155
MAP_PIN_TYPE_ARTIFACT_RETURN_ALDMERI = 128
MAP_PIN_TYPE_ARTIFACT_RETURN_DAGGERFALL = 129
MAP_PIN_TYPE_ARTIFACT_RETURN_EBONHEART = 130
MAP_PIN_TYPE_ASSISTED_QUEST_CONDITION = 10
MAP_PIN_TYPE_ASSISTED_QUEST_ENDING = 12
MAP_PIN_TYPE_ASSISTED_QUEST_OPTIONAL_CONDITION = 11
MAP_PIN_TYPE_ASSISTED_QUEST_REPEATABLE_CONDITION = 13
MAP_PIN_TYPE_ASSISTED_QUEST_REPEATABLE_ENDING = 15
MAP_PIN_TYPE_ASSISTED_QUEST_REPEATABLE_OPTIONAL_CONDITION = 14
MAP_PIN_TYPE_ASSISTED_QUEST_ZONE_STORY_CONDITION = 16
MAP_PIN_TYPE_ASSISTED_QUEST_ZONE_STORY_ENDING = 18
MAP_PIN_TYPE_ASSISTED_QUEST_ZONE_STORY_OPTIONAL_CONDITION = 17
MAP_PIN_TYPE_AUTO_MAP_NAVIGATION_PING = 186
MAP_PIN_TYPE_AVA_CAPTURE_AREA_ALDMERI = 52
MAP_PIN_TYPE_AVA_CAPTURE_AREA_AURA = 111
MAP_PIN_TYPE_AVA_CAPTURE_AREA_DAGGERFALL = 54
MAP_PIN_TYPE_AVA_CAPTURE_AREA_EBONHEART = 53
MAP_PIN_TYPE_AVA_CAPTURE_AREA_NEUTRAL = 51
MAP_PIN_TYPE_AVA_DAEDRIC_ARTIFACT_VOLENDRUNG_ALDMERI = 119
MAP_PIN_TYPE_AVA_DAEDRIC_ARTIFACT_VOLENDRUNG_DAGGERFALL = 121
MAP_PIN_TYPE_AVA_DAEDRIC_ARTIFACT_VOLENDRUNG_EBONHEART = 120
MAP_PIN_TYPE_AVA_DAEDRIC_ARTIFACT_VOLENDRUNG_NEUTRAL = 118
MAP_PIN_TYPE_AVA_TOWN_ALDMERI_DOMINION = 168
MAP_PIN_TYPE_AVA_TOWN_DAGGERFALL_COVENANT = 170
MAP_PIN_TYPE_AVA_TOWN_EBONHEART_PACT = 169
MAP_PIN_TYPE_AVA_TOWN_GRAVEYARD_ACCESSIBLE = 213
MAP_PIN_TYPE_AVA_TOWN_NEUTRAL = 167
MAP_PIN_TYPE_BGPIN_CAPTURE_AREA_AURA = 112
MAP_PIN_TYPE_BGPIN_CAPTURE_AREA_A_FIRE_DRAKES = 60
MAP_PIN_TYPE_BGPIN_CAPTURE_AREA_A_NEUTRAL = 59
MAP_PIN_TYPE_BGPIN_CAPTURE_AREA_A_PIT_DAEMONS = 61
MAP_PIN_TYPE_BGPIN_CAPTURE_AREA_A_STORM_LORDS = 62
MAP_PIN_TYPE_BGPIN_CAPTURE_AREA_B_FIRE_DRAKES = 64
MAP_PIN_TYPE_BGPIN_CAPTURE_AREA_B_NEUTRAL = 63
MAP_PIN_TYPE_BGPIN_CAPTURE_AREA_B_PIT_DAEMONS = 65
MAP_PIN_TYPE_BGPIN_CAPTURE_AREA_B_STORM_LORDS = 66
MAP_PIN_TYPE_BGPIN_CAPTURE_AREA_C_FIRE_DRAKES = 68
MAP_PIN_TYPE_BGPIN_CAPTURE_AREA_C_NEUTRAL = 67
MAP_PIN_TYPE_BGPIN_CAPTURE_AREA_C_PIT_DAEMONS = 69
MAP_PIN_TYPE_BGPIN_CAPTURE_AREA_C_STORM_LORDS = 70
MAP_PIN_TYPE_BGPIN_CAPTURE_AREA_D_FIRE_DRAKES = 72
MAP_PIN_TYPE_BGPIN_CAPTURE_AREA_D_NEUTRAL = 71
MAP_PIN_TYPE_BGPIN_CAPTURE_AREA_D_PIT_DAEMONS = 73
MAP_PIN_TYPE_BGPIN_CAPTURE_AREA_D_STORM_LORDS = 74
MAP_PIN_TYPE_BGPIN_CAPTURE_AREA_FIRE_DRAKES = 56
MAP_PIN_TYPE_BGPIN_CAPTURE_AREA_NEUTRAL = 55
MAP_PIN_TYPE_BGPIN_CAPTURE_AREA_PIT_DAEMONS = 57
MAP_PIN_TYPE_BGPIN_CAPTURE_AREA_STORM_LORDS = 58
MAP_PIN_TYPE_BGPIN_FLAG_FIRE_DRAKES = 96
MAP_PIN_TYPE_BGPIN_FLAG_FIRE_DRAKES_AURA = 115
MAP_PIN_TYPE_BGPIN_FLAG_NEUTRAL = 95
MAP_PIN_TYPE_BGPIN_FLAG_NEUTRAL_AURA = 114
MAP_PIN_TYPE_BGPIN_FLAG_PIT_DAEMONS = 97
MAP_PIN_TYPE_BGPIN_FLAG_PIT_DAEMONS_AURA = 116
MAP_PIN_TYPE_BGPIN_FLAG_RETURN_FIRE_DRAKES = 103
MAP_PIN_TYPE_BGPIN_FLAG_RETURN_PIT_DAEMONS = 104
MAP_PIN_TYPE_BGPIN_FLAG_RETURN_STORM_LORDS = 105
MAP_PIN_TYPE_BGPIN_FLAG_SPAWN_FIRE_DRAKES = 100
MAP_PIN_TYPE_BGPIN_FLAG_SPAWN_NEUTRAL = 99
MAP_PIN_TYPE_BGPIN_FLAG_SPAWN_PIT_DAEMONS = 101
MAP_PIN_TYPE_BGPIN_FLAG_SPAWN_STORM_LORDS = 102
MAP_PIN_TYPE_BGPIN_FLAG_STORM_LORDS = 98
MAP_PIN_TYPE_BGPIN_FLAG_STORM_LORDS_AURA = 117
MAP_PIN_TYPE_BGPIN_MOBILE_CAPTURE_AREA_AURA = 113
MAP_PIN_TYPE_BGPIN_MOBILE_CAPTURE_AREA_A_FIRE_DRAKES = 80
MAP_PIN_TYPE_BGPIN_MOBILE_CAPTURE_AREA_A_NEUTRAL = 79
MAP_PIN_TYPE_BGPIN_MOBILE_CAPTURE_AREA_A_PIT_DAEMONS = 81
MAP_PIN_TYPE_BGPIN_MOBILE_CAPTURE_AREA_A_STORM_LORDS = 82
MAP_PIN_TYPE_BGPIN_MOBILE_CAPTURE_AREA_B_FIRE_DRAKES = 84
MAP_PIN_TYPE_BGPIN_MOBILE_CAPTURE_AREA_B_NEUTRAL = 83
MAP_PIN_TYPE_BGPIN_MOBILE_CAPTURE_AREA_B_PIT_DAEMONS = 85
MAP_PIN_TYPE_BGPIN_MOBILE_CAPTURE_AREA_B_STORM_LORDS = 86
MAP_PIN_TYPE_BGPIN_MOBILE_CAPTURE_AREA_C_FIRE_DRAKES = 88
MAP_PIN_TYPE_BGPIN_MOBILE_CAPTURE_AREA_C_NEUTRAL = 87
MAP_PIN_TYPE_BGPIN_MOBILE_CAPTURE_AREA_C_PIT_DAEMONS = 89
MAP_PIN_TYPE_BGPIN_MOBILE_CAPTURE_AREA_C_STORM_LORDS = 90
MAP_PIN_TYPE_BGPIN_MOBILE_CAPTURE_AREA_D_FIRE_DRAKES = 92
MAP_PIN_TYPE_BGPIN_MOBILE_CAPTURE_AREA_D_NEUTRAL = 91
MAP_PIN_TYPE_BGPIN_MOBILE_CAPTURE_AREA_D_PIT_DAEMONS = 93
MAP_PIN_TYPE_BGPIN_MOBILE_CAPTURE_AREA_D_STORM_LORDS = 94
MAP_PIN_TYPE_BGPIN_MOBILE_CAPTURE_AREA_FIRE_DRAKES = 76
MAP_PIN_TYPE_BGPIN_MOBILE_CAPTURE_AREA_NEUTRAL = 75
MAP_PIN_TYPE_BGPIN_MOBILE_CAPTURE_AREA_PIT_DAEMONS = 77
MAP_PIN_TYPE_BGPIN_MOBILE_CAPTURE_AREA_STORM_LORDS = 78
MAP_PIN_TYPE_BGPIN_MURDERBALL_FIRE_DRAKES = 108
MAP_PIN_TYPE_BGPIN_MURDERBALL_NEUTRAL = 107
MAP_PIN_TYPE_BGPIN_MURDERBALL_PIT_DAEMONS = 109
MAP_PIN_TYPE_BGPIN_MURDERBALL_SPAWN_NEUTRAL = 106
MAP_PIN_TYPE_BGPIN_MURDERBALL_STORM_LORDS = 110
MAP_PIN_TYPE_BORDER_KEEP_ALDMERI_DOMINION = 151
MAP_PIN_TYPE_BORDER_KEEP_DAGGERFALL_COVENANT = 153
MAP_PIN_TYPE_BORDER_KEEP_EBONHEART_PACT = 152
MAP_PIN_TYPE_DARK_BROTHERHOOD_TARGET = 220
MAP_PIN_TYPE_EBONHEART_VS_DAGGERFALL_LARGE = 200
MAP_PIN_TYPE_EBONHEART_VS_DAGGERFALL_MEDIUM = 199
MAP_PIN_TYPE_EBONHEART_VS_DAGGERFALL_SMALL = 198
MAP_PIN_TYPE_FARM_ALDMERI_DOMINION = 140
MAP_PIN_TYPE_FARM_DAGGERFALL_COVENANT = 142
MAP_PIN_TYPE_FARM_EBONHEART_PACT = 141
MAP_PIN_TYPE_FARM_NEUTRAL = 139
MAP_PIN_TYPE_FAST_TRAVEL_BORDER_KEEP_ACCESSIBLE = 202
MAP_PIN_TYPE_FAST_TRAVEL_KEEP_ACCESSIBLE = 201
MAP_PIN_TYPE_FAST_TRAVEL_OUTPOST_ACCESSIBLE = 203
MAP_PIN_TYPE_FAST_TRAVEL_WAYSHRINE = 204
MAP_PIN_TYPE_FAST_TRAVEL_WAYSHRINE_CURRENT_LOC = 205
MAP_PIN_TYPE_FORWARD_CAMP_ACCESSIBLE = 209
MAP_PIN_TYPE_FORWARD_CAMP_ALDMERI_DOMINION = 206
MAP_PIN_TYPE_FORWARD_CAMP_DAGGERFALL_COVENANT = 208
MAP_PIN_TYPE_FORWARD_CAMP_EBONHEART_PACT = 207
MAP_PIN_TYPE_GROUP = 1
MAP_PIN_TYPE_GROUP_LEADER = 2
MAP_PIN_TYPE_HARVEST_NODE = 179
MAP_PIN_TYPE_IMPERIAL_DISTRICT_ALDMERI_DOMINION = 164
MAP_PIN_TYPE_IMPERIAL_DISTRICT_DAGGERFALL_COVENANT = 166
MAP_PIN_TYPE_IMPERIAL_DISTRICT_EBONHEART_PACT = 165
MAP_PIN_TYPE_IMPERIAL_DISTRICT_GRAVEYARD_ACCESSIBLE = 212
MAP_PIN_TYPE_IMPERIAL_DISTRICT_NEUTRAL = 163
MAP_PIN_TYPE_INVALID = 237
MAP_PIN_TYPE_KEEP_ALDMERI_DOMINION = 132
MAP_PIN_TYPE_KEEP_ATTACKED_LARGE = 176
MAP_PIN_TYPE_KEEP_ATTACKED_SMALL = 177
MAP_PIN_TYPE_KEEP_BRIDGE = 171
MAP_PIN_TYPE_KEEP_BRIDGE_IMPASSABLE = 172
MAP_PIN_TYPE_KEEP_DAGGERFALL_COVENANT = 134
MAP_PIN_TYPE_KEEP_EBONHEART_PACT = 133
MAP_PIN_TYPE_KEEP_GRAVEYARD_ACCESSIBLE = 210
MAP_PIN_TYPE_KEEP_MILEGATE = 173
MAP_PIN_TYPE_KEEP_MILEGATE_CENTER_DESTROYED = 174
MAP_PIN_TYPE_KEEP_MILEGATE_IMPASSABLE = 175
MAP_PIN_TYPE_KEEP_NEUTRAL = 131
MAP_PIN_TYPE_LOCATION = 178
MAP_PIN_TYPE_MILL_ALDMERI_DOMINION = 148
MAP_PIN_TYPE_MILL_DAGGERFALL_COVENANT = 150
MAP_PIN_TYPE_MILL_EBONHEART_PACT = 149
MAP_PIN_TYPE_MILL_NEUTRAL = 147
MAP_PIN_TYPE_MINE_ALDMERI_DOMINION = 144
MAP_PIN_TYPE_MINE_DAGGERFALL_COVENANT = 146
MAP_PIN_TYPE_MINE_EBONHEART_PACT = 145
MAP_PIN_TYPE_MINE_NEUTRAL = 143
MAP_PIN_TYPE_NPC_FOLLOWER = 182
MAP_PIN_TYPE_OUTPOST_ALDMERI_DOMINION = 136
MAP_PIN_TYPE_OUTPOST_DAGGERFALL_COVENANT = 138
MAP_PIN_TYPE_OUTPOST_EBONHEART_PACT = 137
MAP_PIN_TYPE_OUTPOST_GRAVEYARD_ACCESSIBLE = 214
MAP_PIN_TYPE_OUTPOST_NEUTRAL = 135
MAP_PIN_TYPE_PING = 183
MAP_PIN_TYPE_PLAYER = 0
MAP_PIN_TYPE_PLAYER_CAMERA = 235
MAP_PIN_TYPE_PLAYER_WAYPOINT = 185
MAP_PIN_TYPE_POI_COMPLETE = 40
MAP_PIN_TYPE_POI_SEEN = 39
MAP_PIN_TYPE_POI_SUGGESTED = 38
MAP_PIN_TYPE_QUEST_COMPLETE = 6
MAP_PIN_TYPE_QUEST_CONDITION = 28
MAP_PIN_TYPE_QUEST_ENDING = 30
MAP_PIN_TYPE_QUEST_GIVE_ITEM = 9
MAP_PIN_TYPE_QUEST_INTERACT = 8
MAP_PIN_TYPE_QUEST_OFFER = 3
MAP_PIN_TYPE_QUEST_OFFER_REPEATABLE = 4
MAP_PIN_TYPE_QUEST_OFFER_ZONE_STORY = 5
MAP_PIN_TYPE_QUEST_OPTIONAL_CONDITION = 29
MAP_PIN_TYPE_QUEST_PING = 187
MAP_PIN_TYPE_QUEST_REPEATABLE_CONDITION = 31
MAP_PIN_TYPE_QUEST_REPEATABLE_ENDING = 33
MAP_PIN_TYPE_QUEST_REPEATABLE_OPTIONAL_CONDITION = 32
MAP_PIN_TYPE_QUEST_TALK_TO = 7
MAP_PIN_TYPE_QUEST_ZONE_STORY_CONDITION = 34
MAP_PIN_TYPE_QUEST_ZONE_STORY_ENDING = 36
MAP_PIN_TYPE_QUEST_ZONE_STORY_OPTIONAL_CONDITION = 35
MAP_PIN_TYPE_RALLY_POINT = 184
MAP_PIN_TYPE_RESPAWN_BORDER_KEEP_ACCESSIBLE = 211
MAP_PIN_TYPE_RESTRICTED_LINK_ALDMERI_DOMINION = 215
MAP_PIN_TYPE_RESTRICTED_LINK_DAGGERFALL_COVENANT = 217
MAP_PIN_TYPE_RESTRICTED_LINK_EBONHEART_PACT = 216
MAP_PIN_TYPE_RETURN_ALDMERI_DOMINION = 47
MAP_PIN_TYPE_RETURN_DAGGERFALL_COVENANT = 49
MAP_PIN_TYPE_RETURN_EBONHEART_PACT = 48
MAP_PIN_TYPE_RETURN_NEUTRAL = 50
MAP_PIN_TYPE_SKYSHARD_COMPLETE = 43
MAP_PIN_TYPE_SKYSHARD_SEEN = 42
MAP_PIN_TYPE_SKYSHARD_SUGGESTED = 41
MAP_PIN_TYPE_TARGET_MARKER_TYPE_EIGHT = 234
MAP_PIN_TYPE_TARGET_MARKER_TYPE_FIVE = 231
MAP_PIN_TYPE_TARGET_MARKER_TYPE_FOUR = 230
MAP_PIN_TYPE_TARGET_MARKER_TYPE_ONE = 227
MAP_PIN_TYPE_TARGET_MARKER_TYPE_SEVEN = 233
MAP_PIN_TYPE_TARGET_MARKER_TYPE_SIX = 232
MAP_PIN_TYPE_TARGET_MARKER_TYPE_THREE = 229
MAP_PIN_TYPE_TARGET_MARKER_TYPE_TWO = 228
MAP_PIN_TYPE_TIMELY_ESCAPE_NPC = 219
MAP_PIN_TYPE_TRACKED_ANTIQUITY_DIG_SITE = 45
MAP_PIN_TYPE_TRACKED_QUEST_CONDITION = 19
MAP_PIN_TYPE_TRACKED_QUEST_ENDING = 21
MAP_PIN_TYPE_TRACKED_QUEST_OFFER_ZONE_STORY = 37
MAP_PIN_TYPE_TRACKED_QUEST_OPTIONAL_CONDITION = 20
MAP_PIN_TYPE_TRACKED_QUEST_REPEATABLE_CONDITION = 22
MAP_PIN_TYPE_TRACKED_QUEST_REPEATABLE_ENDING = 24
MAP_PIN_TYPE_TRACKED_QUEST_REPEATABLE_OPTIONAL_CONDITION = 23
MAP_PIN_TYPE_TRACKED_QUEST_ZONE_STORY_CONDITION = 25
MAP_PIN_TYPE_TRACKED_QUEST_ZONE_STORY_ENDING = 27
MAP_PIN_TYPE_TRACKED_QUEST_ZONE_STORY_OPTIONAL_CONDITION = 26
MAP_PIN_TYPE_TRAINER = 181
MAP_PIN_TYPE_TRI_BATTLE_LARGE = 191
MAP_PIN_TYPE_TRI_BATTLE_MEDIUM = 190
MAP_PIN_TYPE_TRI_BATTLE_SMALL = 189
MAP_PIN_TYPE_UNIT_COMBAT_HEALTHY = 223
MAP_PIN_TYPE_UNIT_COMBAT_WEAK = 224
MAP_PIN_TYPE_UNIT_IDLE_HEALTHY = 221
MAP_PIN_TYPE_UNIT_IDLE_WEAK = 222
MAP_PIN_TYPE_VENDOR = 180
MAP_PIN_TYPE_WORLD_EVENT_POI_ACTIVE = 225
MAP_PIN_TYPE_ZONE_STORY_SUGGESTED_AREA = 46
