--- @meta MapDisplayType

--- @alias MapDisplayType integer
--- | `MAP_TYPE_COUNT` # 2
--- | `MAP_TYPE_LOCATION_CENTERED` # 1
--- | `MAP_TYPE_PLAYER_CENTERED` # 0

MAP_TYPE_COUNT = 2
MAP_TYPE_LOCATION_CENTERED = 1
MAP_TYPE_PLAYER_CENTERED = 0
