--- @meta MapFilterType

--- @alias MapFilterType integer
--- | `MAP_FILTER_TYPE_AVA_CYRODIIL` # 2
--- | `MAP_FILTER_TYPE_AVA_IMPERIAL` # 3
--- | `MAP_FILTER_TYPE_BATTLEGROUND` # 4
--- | `MAP_FILTER_TYPE_STANDARD` # 1

MAP_FILTER_TYPE_AVA_CYRODIIL = 2
MAP_FILTER_TYPE_AVA_IMPERIAL = 3
MAP_FILTER_TYPE_BATTLEGROUND = 4
MAP_FILTER_TYPE_STANDARD = 1
