--- @meta MapFilter

--- @alias MapFilter integer
--- | `MAP_FILTER_ACQUIRED_SKYSHARDS` # 15
--- | `MAP_FILTER_AVA_GRAVEYARDS` # 7
--- | `MAP_FILTER_AVA_GRAVEYARD_AREAS` # 6
--- | `MAP_FILTER_AVA_OBJECTIVES` # 2
--- | `MAP_FILTER_COMPANIONS` # 14
--- | `MAP_FILTER_DEPRECATED` # 12
--- | `MAP_FILTER_DIG_SITES` # 13
--- | `MAP_FILTER_GROUP_MEMBERS` # 9
--- | `MAP_FILTER_KILL_LOCATIONS` # 3
--- | `MAP_FILTER_OBJECTIVES` # 1
--- | `MAP_FILTER_QUESTS` # 4
--- | `MAP_FILTER_RESOURCE_KEEPS` # 5
--- | `MAP_FILTER_TRANSIT_LINES` # 10
--- | `MAP_FILTER_TRANSIT_LINES_ALLIANCE` # 11
--- | `MAP_FILTER_WAYSHRINES` # 8

MAP_FILTER_ACQUIRED_SKYSHARDS = 15
MAP_FILTER_AVA_GRAVEYARDS = 7
MAP_FILTER_AVA_GRAVEYARD_AREAS = 6
MAP_FILTER_AVA_OBJECTIVES = 2
MAP_FILTER_COMPANIONS = 14
MAP_FILTER_DEPRECATED = 12
MAP_FILTER_DIG_SITES = 13
MAP_FILTER_GROUP_MEMBERS = 9
MAP_FILTER_KILL_LOCATIONS = 3
MAP_FILTER_OBJECTIVES = 1
MAP_FILTER_QUESTS = 4
MAP_FILTER_RESOURCE_KEEPS = 5
MAP_FILTER_TRANSIT_LINES = 10
MAP_FILTER_TRANSIT_LINES_ALLIANCE = 11
MAP_FILTER_WAYSHRINES = 8
