--- @meta MapPinTooltipColors

--- @alias MapPinTooltipColors integer
--- | `MAP_PIN_TOOLTIP_COLOR_AVA_OBJECTIVE` # 3
--- | `MAP_PIN_TOOLTIP_COLOR_INTERACTABLE` # 2
--- | `MAP_PIN_TOOLTIP_COLOR_MAP_PING` # 4
--- | `MAP_PIN_TOOLTIP_COLOR_POI` # 1
--- | `MAP_PIN_TOOLTIP_COLOR_QUEST_ENDING` # 0
--- | `MAP_PIN_TOOLTIP_COLOR_RALLY_POINT` # 5

MAP_PIN_TOOLTIP_COLOR_AVA_OBJECTIVE = 3
MAP_PIN_TOOLTIP_COLOR_INTERACTABLE = 2
MAP_PIN_TOOLTIP_COLOR_MAP_PING = 4
MAP_PIN_TOOLTIP_COLOR_POI = 1
MAP_PIN_TOOLTIP_COLOR_QUEST_ENDING = 0
MAP_PIN_TOOLTIP_COLOR_RALLY_POINT = 5
