--- @meta MapPinColors

--- @alias MapPinColors integer
--- | `MAP_PIN_COLOR_ASSISTED` # 1
--- | `MAP_PIN_COLOR_DIG_SITE` # 2
--- | `MAP_PIN_COLOR_DIG_SITE_BORDER` # 4
--- | `MAP_PIN_COLOR_NORMAL` # 0
--- | `MAP_PIN_COLOR_TRACKED_DIG_SITE` # 3

MAP_PIN_COLOR_ASSISTED = 1
MAP_PIN_COLOR_DIG_SITE = 2
MAP_PIN_COLOR_DIG_SITE_BORDER = 4
MAP_PIN_COLOR_NORMAL = 0
MAP_PIN_COLOR_TRACKED_DIG_SITE = 3
