--- @meta MarketDisplayGroup

--- @alias MarketDisplayGroup integer
--- | `MARKET_DISPLAY_GROUP_CHAPTER_UPGRADE` # 3
--- | `MARKET_DISPLAY_GROUP_CROWN_STORE` # 0
--- | `MARKET_DISPLAY_GROUP_HOUSE_EDITOR` # 1
--- | `MARKET_DISPLAY_GROUP_HOUSE_PREVIEW` # 2

MARKET_DISPLAY_GROUP_CHAPTER_UPGRADE = 3
MARKET_DISPLAY_GROUP_CROWN_STORE = 0
MARKET_DISPLAY_GROUP_HOUSE_EDITOR = 1
MARKET_DISPLAY_GROUP_HOUSE_PREVIEW = 2
