--- @meta MarketProductType

--- @alias MarketProductType integer
--- | `MARKET_PRODUCT_TYPE_BUNDLE` # 4
--- | `MARKET_PRODUCT_TYPE_CHAPTER` # 9
--- | `MARKET_PRODUCT_TYPE_COLLECTIBLE` # 2
--- | `MARKET_PRODUCT_TYPE_CROWN_CRATE` # 5
--- | `MARKET_PRODUCT_TYPE_CURRENCY` # 8
--- | `MARKET_PRODUCT_TYPE_HOUSING` # 6
--- | `MARKET_PRODUCT_TYPE_INSTANT_UNLOCK` # 3
--- | `MARKET_PRODUCT_TYPE_ITEM` # 1
--- | `MARKET_PRODUCT_TYPE_NONE` # 0
--- | `MARKET_PRODUCT_TYPE_PROMO` # 7

MARKET_PRODUCT_TYPE_BUNDLE = 4
MARKET_PRODUCT_TYPE_CHAPTER = 9
MARKET_PRODUCT_TYPE_COLLECTIBLE = 2
MARKET_PRODUCT_TYPE_CROWN_CRATE = 5
MARKET_PRODUCT_TYPE_CURRENCY = 8
MARKET_PRODUCT_TYPE_HOUSING = 6
MARKET_PRODUCT_TYPE_INSTANT_UNLOCK = 3
MARKET_PRODUCT_TYPE_ITEM = 1
MARKET_PRODUCT_TYPE_NONE = 0
MARKET_PRODUCT_TYPE_PROMO = 7
