--- @meta MarketPurchasableResult

--- @alias MarketPurchasableResult integer
--- | `MARKET_PURCHASE_RESULT_ALREADY_COMPLETED_INSTANT_UNLOCK` # 11
--- | `MARKET_PURCHASE_RESULT_ALREADY_COMPLETED_QUEST` # 33
--- | `MARKET_PURCHASE_RESULT_ALREADY_HAVE_QUEST` # 32
--- | `MARKET_PURCHASE_RESULT_CANNOT_GIFT_ENDEAVOR_SEAL_PRODUCTS` # 38
--- | `MARKET_PURCHASE_RESULT_CANNOT_GIFT_GEM_PRODUCTS` # 21
--- | `MARKET_PURCHASE_RESULT_CANNOT_GIFT_PRODUCT` # 18
--- | `MARKET_PURCHASE_RESULT_CANNOT_GIFT_RECIPIENT_NOT_FOUND` # 24
--- | `MARKET_PURCHASE_RESULT_CANNOT_GIFT_TO_PLAYER` # 19
--- | `MARKET_PURCHASE_RESULT_CANNOT_GRANT_QUEST` # 34
--- | `MARKET_PURCHASE_RESULT_COLLECTIBLE_ALREADY` # 8
--- | `MARKET_PURCHASE_RESULT_COLLECTIBLE_ENTITLEMENT_RESTRICTED` # 20
--- | `MARKET_PURCHASE_RESULT_COLLECTIONS_DISABLED` # 9
--- | `MARKET_PURCHASE_RESULT_COMING_SOON` # 12
--- | `MARKET_PURCHASE_RESULT_EXCEEDS_CURRENCY_CAP` # 28
--- | `MARKET_PURCHASE_RESULT_EXCEEDS_MAX_QUANTITY` # 40
--- | `MARKET_PURCHASE_RESULT_FAIL_INSTANT_UNLOCK_REQ_LIST` # 10
--- | `MARKET_PURCHASE_RESULT_FAIL_PURCHASE_REQ_LIST` # 29
--- | `MARKET_PURCHASE_RESULT_FAIL_SEE_REQ_LIST` # 41
--- | `MARKET_PURCHASE_RESULT_GIFTING_GRACE_PERIOD_ACTIVE` # 23
--- | `MARKET_PURCHASE_RESULT_GIFTING_LOCKED` # 25
--- | `MARKET_PURCHASE_RESULT_GIFTING_NOT_ALLOWED` # 17
--- | `MARKET_PURCHASE_RESULT_GIFT_COLLECTIBLE_ALREADY_OWNED` # 26
--- | `MARKET_PURCHASE_RESULT_GIFT_COLLECTIBLE_PARTIALLY_OWNED` # 35
--- | `MARKET_PURCHASE_RESULT_HOUSING_ALREADY_OWNED` # 15
--- | `MARKET_PURCHASE_RESULT_INVALID_MARKET_COLLECTIBLE` # 7
--- | `MARKET_PURCHASE_RESULT_INVALID_MARKET_HOUSING` # 14
--- | `MARKET_PURCHASE_RESULT_INVALID_PRODUCT` # 3
--- | `MARKET_PURCHASE_RESULT_INVALID_QUANTITY` # 39
--- | `MARKET_PURCHASE_RESULT_INVALID_STACK_SIZE` # 5
--- | `MARKET_PURCHASE_RESULT_MARKET_LOCKED` # 6
--- | `MARKET_PURCHASE_RESULT_NOT_ENOUGH_CROWN_GEMS` # 13
--- | `MARKET_PURCHASE_RESULT_NOT_ENOUGH_ENDEAVOR_SEALS` # 37
--- | `MARKET_PURCHASE_RESULT_NOT_ENOUGH_ROOM` # 2
--- | `MARKET_PURCHASE_RESULT_NOT_ENOUGH_VC` # 1
--- | `MARKET_PURCHASE_RESULT_PRODUCT_ALREADY_IN_GIFT_INVENTORY` # 22
--- | `MARKET_PURCHASE_RESULT_QUEST_JOURNAL_FULL` # 31
--- | `MARKET_PURCHASE_RESULT_REQUIRES_ESO_PLUS` # 27
--- | `MARKET_PURCHASE_RESULT_SUCCESS` # 0
--- | `MARKET_PURCHASE_RESULT_TEMPORARY_HOTBAR_PROHIBITION` # 30
--- | `MARKET_PURCHASE_RESULT_TOO_MANY_PENDING_GIFTS` # 42
--- | `MARKET_PURCHASE_RESULT_UNAVAILABLE_PRODUCT` # 16
--- | `MARKET_PURCHASE_RESULT_UNIQUE_ITEM_ALREADY` # 4
--- | `MARKET_PURCHASE_RESULT_WAITING_CONFIRM_GIVE_GIFT` # 36

MARKET_PURCHASE_RESULT_ALREADY_COMPLETED_INSTANT_UNLOCK = 11
MARKET_PURCHASE_RESULT_ALREADY_COMPLETED_QUEST = 33
MARKET_PURCHASE_RESULT_ALREADY_HAVE_QUEST = 32
MARKET_PURCHASE_RESULT_CANNOT_GIFT_ENDEAVOR_SEAL_PRODUCTS = 38
MARKET_PURCHASE_RESULT_CANNOT_GIFT_GEM_PRODUCTS = 21
MARKET_PURCHASE_RESULT_CANNOT_GIFT_PRODUCT = 18
MARKET_PURCHASE_RESULT_CANNOT_GIFT_RECIPIENT_NOT_FOUND = 24
MARKET_PURCHASE_RESULT_CANNOT_GIFT_TO_PLAYER = 19
MARKET_PURCHASE_RESULT_CANNOT_GRANT_QUEST = 34
MARKET_PURCHASE_RESULT_COLLECTIBLE_ALREADY = 8
MARKET_PURCHASE_RESULT_COLLECTIBLE_ENTITLEMENT_RESTRICTED = 20
MARKET_PURCHASE_RESULT_COLLECTIONS_DISABLED = 9
MARKET_PURCHASE_RESULT_COMING_SOON = 12
MARKET_PURCHASE_RESULT_EXCEEDS_CURRENCY_CAP = 28
MARKET_PURCHASE_RESULT_EXCEEDS_MAX_QUANTITY = 40
MARKET_PURCHASE_RESULT_FAIL_INSTANT_UNLOCK_REQ_LIST = 10
MARKET_PURCHASE_RESULT_FAIL_PURCHASE_REQ_LIST = 29
MARKET_PURCHASE_RESULT_FAIL_SEE_REQ_LIST = 41
MARKET_PURCHASE_RESULT_GIFTING_GRACE_PERIOD_ACTIVE = 23
MARKET_PURCHASE_RESULT_GIFTING_LOCKED = 25
MARKET_PURCHASE_RESULT_GIFTING_NOT_ALLOWED = 17
MARKET_PURCHASE_RESULT_GIFT_COLLECTIBLE_ALREADY_OWNED = 26
MARKET_PURCHASE_RESULT_GIFT_COLLECTIBLE_PARTIALLY_OWNED = 35
MARKET_PURCHASE_RESULT_HOUSING_ALREADY_OWNED = 15
MARKET_PURCHASE_RESULT_INVALID_MARKET_COLLECTIBLE = 7
MARKET_PURCHASE_RESULT_INVALID_MARKET_HOUSING = 14
MARKET_PURCHASE_RESULT_INVALID_PRODUCT = 3
MARKET_PURCHASE_RESULT_INVALID_QUANTITY = 39
MARKET_PURCHASE_RESULT_INVALID_STACK_SIZE = 5
MARKET_PURCHASE_RESULT_MARKET_LOCKED = 6
MARKET_PURCHASE_RESULT_NOT_ENOUGH_CROWN_GEMS = 13
MARKET_PURCHASE_RESULT_NOT_ENOUGH_ENDEAVOR_SEALS = 37
MARKET_PURCHASE_RESULT_NOT_ENOUGH_ROOM = 2
MARKET_PURCHASE_RESULT_NOT_ENOUGH_VC = 1
MARKET_PURCHASE_RESULT_PRODUCT_ALREADY_IN_GIFT_INVENTORY = 22
MARKET_PURCHASE_RESULT_QUEST_JOURNAL_FULL = 31
MARKET_PURCHASE_RESULT_REQUIRES_ESO_PLUS = 27
MARKET_PURCHASE_RESULT_SUCCESS = 0
MARKET_PURCHASE_RESULT_TEMPORARY_HOTBAR_PROHIBITION = 30
MARKET_PURCHASE_RESULT_TOO_MANY_PENDING_GIFTS = 42
MARKET_PURCHASE_RESULT_UNAVAILABLE_PRODUCT = 16
MARKET_PURCHASE_RESULT_UNIQUE_ITEM_ALREADY = 4
MARKET_PURCHASE_RESULT_WAITING_CONFIRM_GIVE_GIFT = 36
