--- @meta MarketFilterView

--- @alias MarketFilterView integer
--- | `MARKET_FILTER_VIEW_ALL` # 1
--- | `MARKET_FILTER_VIEW_NOT_PURCHASED` # 3
--- | `MARKET_FILTER_VIEW_PURCHASED` # 2

MARKET_FILTER_VIEW_ALL = 1
MARKET_FILTER_VIEW_NOT_PURCHASED = 3
MARKET_FILTER_VIEW_PURCHASED = 2
