--- @meta MarketColors

--- @alias MarketColors integer
--- | `MARKET_COLORS_CALLOUT_BACKGROUND` # 10
--- | `MARKET_COLORS_CALLOUT_BACKGROUND_DIMMED` # 9
--- | `MARKET_COLORS_COLLECTORS_EDITION` # 15
--- | `MARKET_COLORS_COLLECTORS_EDITION_HIGHLIGHT` # 16
--- | `MARKET_COLORS_DIMMED` # 1
--- | `MARKET_COLORS_ESO_PLUS` # 18
--- | `MARKET_COLORS_ESO_PLUS_DIMMED` # 17
--- | `MARKET_COLORS_ESO_PLUS_PURCHASED` # 20
--- | `MARKET_COLORS_ESO_PLUS_PURCHASED_DIMMED` # 19
--- | `MARKET_COLORS_INELIGIBLE` # 12
--- | `MARKET_COLORS_INELIGIBLE_DIMMED` # 11
--- | `MARKET_COLORS_NEW` # 7
--- | `MARKET_COLORS_NEW_DIMMED` # 6
--- | `MARKET_COLORS_ON_SALE` # 5
--- | `MARKET_COLORS_ON_SALE_DIMMED` # 4
--- | `MARKET_COLORS_PRODUCT_BACKGROUND_BRIGHTNESS` # 8
--- | `MARKET_COLORS_PURCHASED` # 3
--- | `MARKET_COLORS_PURCHASED_DIMMED` # 2
--- | `MARKET_COLORS_SELECTED` # 0
--- | `MARKET_COLORS_UNIVERSAL_ITEM` # 13
--- | `MARKET_COLORS_UNIVERSAL_ITEM_SELECTED` # 14

MARKET_COLORS_CALLOUT_BACKGROUND = 10
MARKET_COLORS_CALLOUT_BACKGROUND_DIMMED = 9
MARKET_COLORS_COLLECTORS_EDITION = 15
MARKET_COLORS_COLLECTORS_EDITION_HIGHLIGHT = 16
MARKET_COLORS_DIMMED = 1
MARKET_COLORS_ESO_PLUS = 18
MARKET_COLORS_ESO_PLUS_DIMMED = 17
MARKET_COLORS_ESO_PLUS_PURCHASED = 20
MARKET_COLORS_ESO_PLUS_PURCHASED_DIMMED = 19
MARKET_COLORS_INELIGIBLE = 12
MARKET_COLORS_INELIGIBLE_DIMMED = 11
MARKET_COLORS_NEW = 7
MARKET_COLORS_NEW_DIMMED = 6
MARKET_COLORS_ON_SALE = 5
MARKET_COLORS_ON_SALE_DIMMED = 4
MARKET_COLORS_PRODUCT_BACKGROUND_BRIGHTNESS = 8
MARKET_COLORS_PURCHASED = 3
MARKET_COLORS_PURCHASED_DIMMED = 2
MARKET_COLORS_SELECTED = 0
MARKET_COLORS_UNIVERSAL_ITEM = 13
MARKET_COLORS_UNIVERSAL_ITEM_SELECTED = 14
