--- @meta MarketProductFilterType

--- @alias MarketProductFilterType integer
--- | `MARKET_PRODUCT_FILTER_TYPE_COST_CROWNS` # 2
--- | `MARKET_PRODUCT_FILTER_TYPE_COST_CROWN_GEMS` # 4
--- | `MARKET_PRODUCT_FILTER_TYPE_COST_ENDEAVOR_SEALS` # 8
--- | `MARKET_PRODUCT_FILTER_TYPE_ESO_PLUS_OFFERS` # 16
--- | `MARKET_PRODUCT_FILTER_TYPE_FEATURED` # 32
--- | `MARKET_PRODUCT_FILTER_TYPE_NEW` # 1

MARKET_PRODUCT_FILTER_TYPE_COST_CROWNS = 2
MARKET_PRODUCT_FILTER_TYPE_COST_CROWN_GEMS = 4
MARKET_PRODUCT_FILTER_TYPE_COST_ENDEAVOR_SEALS = 8
MARKET_PRODUCT_FILTER_TYPE_ESO_PLUS_OFFERS = 16
MARKET_PRODUCT_FILTER_TYPE_FEATURED = 32
MARKET_PRODUCT_FILTER_TYPE_NEW = 1
