--- @meta MarketOpenOperation

--- @alias MarketOpenOperation integer
--- | `MARKET_OPEN_OPERATION_ACTIVITY_FINDER` # 17
--- | `MARKET_OPEN_OPERATION_ANNOUNCEMENT` # 1
--- | `MARKET_OPEN_OPERATION_ANTIQUITY_JOURNAL` # 18
--- | `MARKET_OPEN_OPERATION_COLLECTIBLE_FAILURE` # 12
--- | `MARKET_OPEN_OPERATION_COLLECTIONS_DLC` # 3
--- | `MARKET_OPEN_OPERATION_COLLECTIONS_OUTFITS` # 9
--- | `MARKET_OPEN_OPERATION_CROWN_CRATES` # 7
--- | `MARKET_OPEN_OPERATION_DIRECT` # 0
--- | `MARKET_OPEN_OPERATION_DLC_FAILURE_CAMPAIGN_QUEUE` # 15
--- | `MARKET_OPEN_OPERATION_DLC_FAILURE_TELEPORT_TO_GROUP` # 5
--- | `MARKET_OPEN_OPERATION_DLC_FAILURE_TELEPORT_TO_ZONE` # 6
--- | `MARKET_OPEN_OPERATION_DLC_FAILURE_WORLD_MAP` # 4
--- | `MARKET_OPEN_OPERATION_GROUP_FINDER` # 19
--- | `MARKET_OPEN_OPERATION_NOTIFICATION` # 8
--- | `MARKET_OPEN_OPERATION_OUTFIT_CURRENCY` # 11
--- | `MARKET_OPEN_OPERATION_RESEARCH_SCROLLS` # 13
--- | `MARKET_OPEN_OPERATION_UNIVERSAL_STYLE_ITEM` # 2
--- | `MARKET_OPEN_OPERATION_UNLOCK_ARMORY_BUILD_SLOT` # 16
--- | `MARKET_OPEN_OPERATION_UNLOCK_NEW_OUTFIT` # 10
--- | `MARKET_OPEN_OPERATION_ZONE_STORIES` # 14

MARKET_OPEN_OPERATION_ACTIVITY_FINDER = 17
MARKET_OPEN_OPERATION_ANNOUNCEMENT = 1
MARKET_OPEN_OPERATION_ANTIQUITY_JOURNAL = 18
MARKET_OPEN_OPERATION_COLLECTIBLE_FAILURE = 12
MARKET_OPEN_OPERATION_COLLECTIONS_DLC = 3
MARKET_OPEN_OPERATION_COLLECTIONS_OUTFITS = 9
MARKET_OPEN_OPERATION_CROWN_CRATES = 7
MARKET_OPEN_OPERATION_DIRECT = 0
MARKET_OPEN_OPERATION_DLC_FAILURE_CAMPAIGN_QUEUE = 15
MARKET_OPEN_OPERATION_DLC_FAILURE_TELEPORT_TO_GROUP = 5
MARKET_OPEN_OPERATION_DLC_FAILURE_TELEPORT_TO_ZONE = 6
MARKET_OPEN_OPERATION_DLC_FAILURE_WORLD_MAP = 4
MARKET_OPEN_OPERATION_GROUP_FINDER = 19
MARKET_OPEN_OPERATION_NOTIFICATION = 8
MARKET_OPEN_OPERATION_OUTFIT_CURRENCY = 11
MARKET_OPEN_OPERATION_RESEARCH_SCROLLS = 13
MARKET_OPEN_OPERATION_UNIVERSAL_STYLE_ITEM = 2
MARKET_OPEN_OPERATION_UNLOCK_ARMORY_BUILD_SLOT = 16
MARKET_OPEN_OPERATION_UNLOCK_NEW_OUTFIT = 10
MARKET_OPEN_OPERATION_ZONE_STORIES = 14
