--- @meta MarketingPreferencesRequestResult

--- @alias MarketingPreferencesRequestResult integer
--- | `MARKETING_PREFERENCES_REQUEST_RESULT_ACCOUNT_ACCESS_ERROR` # 2
--- | `MARKETING_PREFERENCES_REQUEST_RESULT_ERROR` # 1
--- | `MARKETING_PREFERENCES_REQUEST_RESULT_SUCCESS` # 0
--- | `MARKETING_PREFERENCES_REQUEST_RESULT_TIMEOUT` # 3

MARKETING_PREFERENCES_REQUEST_RESULT_ACCOUNT_ACCESS_ERROR = 2
MARKETING_PREFERENCES_REQUEST_RESULT_ERROR = 1
MARKETING_PREFERENCES_REQUEST_RESULT_SUCCESS = 0
MARKETING_PREFERENCES_REQUEST_RESULT_TIMEOUT = 3
