--- @meta MonsterSocialClass

--- @alias MonsterSocialClass integer
--- | `MONSTER_SOCIAL_CLASS_ALCHEMIST` # 2
--- | `MONSTER_SOCIAL_CLASS_ARTISAN` # 3
--- | `MONSTER_SOCIAL_CLASS_ASSASSIN` # 4
--- | `MONSTER_SOCIAL_CLASS_BARD` # 5
--- | `MONSTER_SOCIAL_CLASS_BEGGAR` # 6
--- | `MONSTER_SOCIAL_CLASS_CHEF` # 7
--- | `MONSTER_SOCIAL_CLASS_CIVIL_SERVANT` # 8
--- | `MONSTER_SOCIAL_CLASS_CLOTHIER` # 9
--- | `MONSTER_SOCIAL_CLASS_COMMONER` # 10
--- | `MONSTER_SOCIAL_CLASS_CRAFTER` # 11
--- | `MONSTER_SOCIAL_CLASS_CULTIST` # 12
--- | `MONSTER_SOCIAL_CLASS_DAEDRA` # 47
--- | `MONSTER_SOCIAL_CLASS_DRUNKARD` # 13
--- | `MONSTER_SOCIAL_CLASS_FARMER` # 14
--- | `MONSTER_SOCIAL_CLASS_FIGHTER` # 15
--- | `MONSTER_SOCIAL_CLASS_FISHER` # 16
--- | `MONSTER_SOCIAL_CLASS_GATHERER` # 17
--- | `MONSTER_SOCIAL_CLASS_GHOST` # 18
--- | `MONSTER_SOCIAL_CLASS_GUARD` # 19
--- | `MONSTER_SOCIAL_CLASS_HEALER` # 20
--- | `MONSTER_SOCIAL_CLASS_HUNTER` # 21
--- | `MONSTER_SOCIAL_CLASS_LABORER` # 22
--- | `MONSTER_SOCIAL_CLASS_MAGE` # 23
--- | `MONSTER_SOCIAL_CLASS_MERCHANT` # 24
--- | `MONSTER_SOCIAL_CLASS_NOBLE` # 25
--- | `MONSTER_SOCIAL_CLASS_NOT_APPLICABLE` # 1
--- | `MONSTER_SOCIAL_CLASS_NUDE` # 26
--- | `MONSTER_SOCIAL_CLASS_ORDINATOR` # 27
--- | `MONSTER_SOCIAL_CLASS_OUTLAW` # 28
--- | `MONSTER_SOCIAL_CLASS_PILGRIM` # 29
--- | `MONSTER_SOCIAL_CLASS_PRIEST` # 30
--- | `MONSTER_SOCIAL_CLASS_PRISONER` # 31
--- | `MONSTER_SOCIAL_CLASS_PROVISIONER` # 32
--- | `MONSTER_SOCIAL_CLASS_SAILOR` # 33
--- | `MONSTER_SOCIAL_CLASS_SCHOLAR` # 34
--- | `MONSTER_SOCIAL_CLASS_SERVANT` # 35
--- | `MONSTER_SOCIAL_CLASS_SKELETON` # 36
--- | `MONSTER_SOCIAL_CLASS_SLAVE` # 37
--- | `MONSTER_SOCIAL_CLASS_SMITH` # 38
--- | `MONSTER_SOCIAL_CLASS_SOLDIER` # 39
--- | `MONSTER_SOCIAL_CLASS_STUDENT` # 40
--- | `MONSTER_SOCIAL_CLASS_THIEF` # 41
--- | `MONSTER_SOCIAL_CLASS_UNDEFINED` # 0
--- | `MONSTER_SOCIAL_CLASS_VAMPIRE` # 42
--- | `MONSTER_SOCIAL_CLASS_WARRIOR` # 43
--- | `MONSTER_SOCIAL_CLASS_WATCHMEN` # 44
--- | `MONSTER_SOCIAL_CLASS_WEREWOLF` # 45
--- | `MONSTER_SOCIAL_CLASS_WOODWORKER` # 46

MONSTER_SOCIAL_CLASS_ALCHEMIST = 2
MONSTER_SOCIAL_CLASS_ARTISAN = 3
MONSTER_SOCIAL_CLASS_ASSASSIN = 4
MONSTER_SOCIAL_CLASS_BARD = 5
MONSTER_SOCIAL_CLASS_BEGGAR = 6
MONSTER_SOCIAL_CLASS_CHEF = 7
MONSTER_SOCIAL_CLASS_CIVIL_SERVANT = 8
MONSTER_SOCIAL_CLASS_CLOTHIER = 9
MONSTER_SOCIAL_CLASS_COMMONER = 10
MONSTER_SOCIAL_CLASS_CRAFTER = 11
MONSTER_SOCIAL_CLASS_CULTIST = 12
MONSTER_SOCIAL_CLASS_DAEDRA = 47
MONSTER_SOCIAL_CLASS_DRUNKARD = 13
MONSTER_SOCIAL_CLASS_FARMER = 14
MONSTER_SOCIAL_CLASS_FIGHTER = 15
MONSTER_SOCIAL_CLASS_FISHER = 16
MONSTER_SOCIAL_CLASS_GATHERER = 17
MONSTER_SOCIAL_CLASS_GHOST = 18
MONSTER_SOCIAL_CLASS_GUARD = 19
MONSTER_SOCIAL_CLASS_HEALER = 20
MONSTER_SOCIAL_CLASS_HUNTER = 21
MONSTER_SOCIAL_CLASS_LABORER = 22
MONSTER_SOCIAL_CLASS_MAGE = 23
MONSTER_SOCIAL_CLASS_MERCHANT = 24
MONSTER_SOCIAL_CLASS_NOBLE = 25
MONSTER_SOCIAL_CLASS_NOT_APPLICABLE = 1
MONSTER_SOCIAL_CLASS_NUDE = 26
MONSTER_SOCIAL_CLASS_ORDINATOR = 27
MONSTER_SOCIAL_CLASS_OUTLAW = 28
MONSTER_SOCIAL_CLASS_PILGRIM = 29
MONSTER_SOCIAL_CLASS_PRIEST = 30
MONSTER_SOCIAL_CLASS_PRISONER = 31
MONSTER_SOCIAL_CLASS_PROVISIONER = 32
MONSTER_SOCIAL_CLASS_SAILOR = 33
MONSTER_SOCIAL_CLASS_SCHOLAR = 34
MONSTER_SOCIAL_CLASS_SERVANT = 35
MONSTER_SOCIAL_CLASS_SKELETON = 36
MONSTER_SOCIAL_CLASS_SLAVE = 37
MONSTER_SOCIAL_CLASS_SMITH = 38
MONSTER_SOCIAL_CLASS_SOLDIER = 39
MONSTER_SOCIAL_CLASS_STUDENT = 40
MONSTER_SOCIAL_CLASS_THIEF = 41
MONSTER_SOCIAL_CLASS_UNDEFINED = 0
MONSTER_SOCIAL_CLASS_VAMPIRE = 42
MONSTER_SOCIAL_CLASS_WARRIOR = 43
MONSTER_SOCIAL_CLASS_WATCHMEN = 44
MONSTER_SOCIAL_CLASS_WEREWOLF = 45
MONSTER_SOCIAL_CLASS_WOODWORKER = 46
