--- @meta MountFailureReason

--- @alias MountFailureReason integer
--- | `MOUNT_FAILURE_REASON_BUSY` # 0
--- | `MOUNT_FAILURE_REASON_CARRYING_OBJECTIVE` # 8
--- | `MOUNT_FAILURE_REASON_COLLECTIBLE_BLACKLISTED` # 9
--- | `MOUNT_FAILURE_REASON_CROUCHING` # 15
--- | `MOUNT_FAILURE_REASON_GROUP_MOUNT_ALREADY_MOUNTED` # 17
--- | `MOUNT_FAILURE_REASON_GROUP_MOUNT_INVALID_TARGET` # 10
--- | `MOUNT_FAILURE_REASON_GROUP_MOUNT_NOT_IN_GROUP` # 11
--- | `MOUNT_FAILURE_REASON_GROUP_MOUNT_NO_FREE_SLOTS` # 12
--- | `MOUNT_FAILURE_REASON_GROUP_MOUNT_TARGET_MOVING` # 14
--- | `MOUNT_FAILURE_REASON_GROUP_MOUNT_TOO_FAR` # 13
--- | `MOUNT_FAILURE_REASON_INVALID_LOCATION` # 1
--- | `MOUNT_FAILURE_REASON_INVENTORY_BUSY` # 3
--- | `MOUNT_FAILURE_REASON_INVENTORY_TOO_FULL` # 2
--- | `MOUNT_FAILURE_REASON_IN_COMBAT` # 5
--- | `MOUNT_FAILURE_REASON_IS_BLOCKING` # 7
--- | `MOUNT_FAILURE_REASON_IS_WEREWOLF` # 6
--- | `MOUNT_FAILURE_REASON_MOUNT_IN_COMBAT` # 18
--- | `MOUNT_FAILURE_REASON_NOT_GROUP_MOUNT` # 16
--- | `MOUNT_FAILURE_REASON_NO_ACTIVE_MOUNT` # 4

MOUNT_FAILURE_REASON_BUSY = 0
MOUNT_FAILURE_REASON_CARRYING_OBJECTIVE = 8
MOUNT_FAILURE_REASON_COLLECTIBLE_BLACKLISTED = 9
MOUNT_FAILURE_REASON_CROUCHING = 15
MOUNT_FAILURE_REASON_GROUP_MOUNT_ALREADY_MOUNTED = 17
MOUNT_FAILURE_REASON_GROUP_MOUNT_INVALID_TARGET = 10
MOUNT_FAILURE_REASON_GROUP_MOUNT_NOT_IN_GROUP = 11
MOUNT_FAILURE_REASON_GROUP_MOUNT_NO_FREE_SLOTS = 12
MOUNT_FAILURE_REASON_GROUP_MOUNT_TARGET_MOVING = 14
MOUNT_FAILURE_REASON_GROUP_MOUNT_TOO_FAR = 13
MOUNT_FAILURE_REASON_INVALID_LOCATION = 1
MOUNT_FAILURE_REASON_INVENTORY_BUSY = 3
MOUNT_FAILURE_REASON_INVENTORY_TOO_FULL = 2
MOUNT_FAILURE_REASON_IN_COMBAT = 5
MOUNT_FAILURE_REASON_IS_BLOCKING = 7
MOUNT_FAILURE_REASON_IS_WEREWOLF = 6
MOUNT_FAILURE_REASON_MOUNT_IN_COMBAT = 18
MOUNT_FAILURE_REASON_NOT_GROUP_MOUNT = 16
MOUNT_FAILURE_REASON_NO_ACTIVE_MOUNT = 4
