--- @meta MountedState

--- @alias MountedState integer
--- | `MOUNTED_STATE_MOUNT_PASSENGER` # 2
--- | `MOUNTED_STATE_MOUNT_RIDER` # 1
--- | `MOUNTED_STATE_NOT_MOUNTED` # 0

MOUNTED_STATE_MOUNT_PASSENGER = 2
MOUNTED_STATE_MOUNT_RIDER = 1
MOUNTED_STATE_NOT_MOUNTED = 0
