--- @meta MouseDestroyItemFailedReason

--- @alias MouseDestroyItemFailedReason integer
--- | `MOUSE_DESTROY_ITEM_FAIL_REASON_CRAFTING` # 1
--- | `MOUSE_DESTROY_ITEM_FAIL_REASON_NONE` # 0
--- | `MOUSE_DESTROY_ITEM_FAIL_REASON_PLAYER_LOCKED` # 2

MOUSE_DESTROY_ITEM_FAIL_REASON_CRAFTING = 1
MOUSE_DESTROY_ITEM_FAIL_REASON_NONE = 0
MOUSE_DESTROY_ITEM_FAIL_REASON_PLAYER_LOCKED = 2
