--- @meta MouseContentType

--- @alias MouseContentType integer
--- | `MOUSE_CONTENT_ACTION` # 1
--- | `MOUSE_CONTENT_COLLECTIBLE` # 9
--- | `MOUSE_CONTENT_CRAFTED_ABILITY` # 12
--- | `MOUSE_CONTENT_CRAFTED_ABILITY_SCRIPT` # 13
--- | `MOUSE_CONTENT_EMOTE` # 10
--- | `MOUSE_CONTENT_EMPTY` # 0
--- | `MOUSE_CONTENT_EQUIPPED_ITEM` # 4
--- | `MOUSE_CONTENT_INVENTORY_ITEM` # 2
--- | `MOUSE_CONTENT_QUEST_ITEM` # 6
--- | `MOUSE_CONTENT_QUICK_CHAT` # 11
--- | `MOUSE_CONTENT_STORE_BUYBACK_ITEM` # 5
--- | `MOUSE_CONTENT_STORE_ITEM` # 8
--- | `MOUSE_CONTENT_TRADE_ITEM` # 3

MOUSE_CONTENT_ACTION = 1
MOUSE_CONTENT_COLLECTIBLE = 9
MOUSE_CONTENT_CRAFTED_ABILITY = 12
MOUSE_CONTENT_CRAFTED_ABILITY_SCRIPT = 13
MOUSE_CONTENT_EMOTE = 10
MOUSE_CONTENT_EMPTY = 0
MOUSE_CONTENT_EQUIPPED_ITEM = 4
MOUSE_CONTENT_INVENTORY_ITEM = 2
MOUSE_CONTENT_QUEST_ITEM = 6
MOUSE_CONTENT_QUICK_CHAT = 11
MOUSE_CONTENT_STORE_BUYBACK_ITEM = 5
MOUSE_CONTENT_STORE_ITEM = 8
MOUSE_CONTENT_TRADE_ITEM = 3
