--- @meta MouseButtonIndex

--- @alias MouseButtonIndex integer
--- | `MOUSE_BUTTON_INDEX_BUTTON_4` # 4
--- | `MOUSE_BUTTON_INDEX_BUTTON_5` # 5
--- | `MOUSE_BUTTON_INDEX_INVALID` # 0
--- | `MOUSE_BUTTON_INDEX_LEFT` # 1
--- | `MOUSE_BUTTON_INDEX_LEFT_AND_RIGHT` # 6
--- | `MOUSE_BUTTON_INDEX_MIDDLE` # 3
--- | `MOUSE_BUTTON_INDEX_RIGHT` # 2

MOUSE_BUTTON_INDEX_BUTTON_4 = 4
MOUSE_BUTTON_INDEX_BUTTON_5 = 5
MOUSE_BUTTON_INDEX_INVALID = 0
MOUSE_BUTTON_INDEX_LEFT = 1
MOUSE_BUTTON_INDEX_LEFT_AND_RIGHT = 6
MOUSE_BUTTON_INDEX_MIDDLE = 3
MOUSE_BUTTON_INDEX_RIGHT = 2
