--- @meta MouseCursorType

--- @alias MouseCursorType integer
--- | `MOUSE_CURSOR_CHAMPION_COMBAT_STAR` # 18
--- | `MOUSE_CURSOR_CHAMPION_CONDITIONING_STAR` # 19
--- | `MOUSE_CURSOR_CHAMPION_WORLD_STAR` # 17
--- | `MOUSE_CURSOR_DEFAULT_CURSOR` # 0
--- | `MOUSE_CURSOR_DO_NOT_CARE` # 666
--- | `MOUSE_CURSOR_ERASE` # 7
--- | `MOUSE_CURSOR_FILL` # 8
--- | `MOUSE_CURSOR_FILL_MULTIPLE` # 9
--- | `MOUSE_CURSOR_ICON` # 5
--- | `MOUSE_CURSOR_NEXT_LEFT` # 14
--- | `MOUSE_CURSOR_NEXT_RIGHT` # 15
--- | `MOUSE_CURSOR_PAINT` # 10
--- | `MOUSE_CURSOR_PAN` # 12
--- | `MOUSE_CURSOR_PREVIEW` # 16
--- | `MOUSE_CURSOR_RESIZE_EW` # 1
--- | `MOUSE_CURSOR_RESIZE_NESW` # 3
--- | `MOUSE_CURSOR_RESIZE_NS` # 2
--- | `MOUSE_CURSOR_RESIZE_NWSE` # 4
--- | `MOUSE_CURSOR_ROTATE` # 13
--- | `MOUSE_CURSOR_SAMPLE` # 11
--- | `MOUSE_CURSOR_UI_HAND` # 6

MOUSE_CURSOR_CHAMPION_COMBAT_STAR = 18
MOUSE_CURSOR_CHAMPION_CONDITIONING_STAR = 19
MOUSE_CURSOR_CHAMPION_WORLD_STAR = 17
MOUSE_CURSOR_DEFAULT_CURSOR = 0
MOUSE_CURSOR_DO_NOT_CARE = 666
MOUSE_CURSOR_ERASE = 7
MOUSE_CURSOR_FILL = 8
MOUSE_CURSOR_FILL_MULTIPLE = 9
MOUSE_CURSOR_ICON = 5
MOUSE_CURSOR_NEXT_LEFT = 14
MOUSE_CURSOR_NEXT_RIGHT = 15
MOUSE_CURSOR_PAINT = 10
MOUSE_CURSOR_PAN = 12
MOUSE_CURSOR_PREVIEW = 16
MOUSE_CURSOR_RESIZE_EW = 1
MOUSE_CURSOR_RESIZE_NESW = 3
MOUSE_CURSOR_RESIZE_NS = 2
MOUSE_CURSOR_RESIZE_NWSE = 4
MOUSE_CURSOR_ROTATE = 13
MOUSE_CURSOR_SAMPLE = 11
MOUSE_CURSOR_UI_HAND = 6
