--- @meta MundusStone

--- @alias MundusStone integer
--- | `MUNDUS_STONE_APPRENTICE` # 12
--- | `MUNDUS_STONE_ATRONACH` # 6
--- | `MUNDUS_STONE_INVALID` # 0
--- | `MUNDUS_STONE_LADY` # 1
--- | `MUNDUS_STONE_LORD` # 3
--- | `MUNDUS_STONE_LOVER` # 2
--- | `MUNDUS_STONE_MAGE` # 4
--- | `MUNDUS_STONE_RITUAL` # 9
--- | `MUNDUS_STONE_SERPENT` # 7
--- | `MUNDUS_STONE_SHADOW` # 8
--- | `MUNDUS_STONE_STEED` # 13
--- | `MUNDUS_STONE_THIEF` # 10
--- | `MUNDUS_STONE_TOWER` # 5
--- | `MUNDUS_STONE_WARRIOR` # 11

MUNDUS_STONE_APPRENTICE = 12
MUNDUS_STONE_ATRONACH = 6
MUNDUS_STONE_INVALID = 0
MUNDUS_STONE_LADY = 1
MUNDUS_STONE_LORD = 3
MUNDUS_STONE_LOVER = 2
MUNDUS_STONE_MAGE = 4
MUNDUS_STONE_RITUAL = 9
MUNDUS_STONE_SERPENT = 7
MUNDUS_STONE_SHADOW = 8
MUNDUS_STONE_STEED = 13
MUNDUS_STONE_THIEF = 10
MUNDUS_STONE_TOWER = 5
MUNDUS_STONE_WARRIOR = 11
