--- @meta NameplateDisplayChoice

--- @alias NameplateDisplayChoice integer
--- | `NAMEPLATE_CHOICE_ALL` # 4
--- | `NAMEPLATE_CHOICE_ALLY` # 7
--- | `NAMEPLATE_CHOICE_ALWAYS` # 2
--- | `NAMEPLATE_CHOICE_CENTER` # 11
--- | `NAMEPLATE_CHOICE_ENEMY` # 6
--- | `NAMEPLATE_CHOICE_INJURED` # 3
--- | `NAMEPLATE_CHOICE_INJURED_OR_TARGETED` # 9
--- | `NAMEPLATE_CHOICE_INVALID` # 0
--- | `NAMEPLATE_CHOICE_LEFT` # 10
--- | `NAMEPLATE_CHOICE_NEVER` # 1
--- | `NAMEPLATE_CHOICE_NONE` # 5
--- | `NAMEPLATE_CHOICE_TARGETED` # 8

NAMEPLATE_CHOICE_ALL = 4
NAMEPLATE_CHOICE_ALLY = 7
NAMEPLATE_CHOICE_ALWAYS = 2
NAMEPLATE_CHOICE_CENTER = 11
NAMEPLATE_CHOICE_ENEMY = 6
NAMEPLATE_CHOICE_INJURED = 3
NAMEPLATE_CHOICE_INJURED_OR_TARGETED = 9
NAMEPLATE_CHOICE_INVALID = 0
NAMEPLATE_CHOICE_LEFT = 10
NAMEPLATE_CHOICE_NEVER = 1
NAMEPLATE_CHOICE_NONE = 5
NAMEPLATE_CHOICE_TARGETED = 8
