--- @meta NameplateDisplayType

--- @alias NameplateDisplayType integer
--- | `NAMEPLATE_TYPE_ALLIANCE_INDICATORS` # 14
--- | `NAMEPLATE_TYPE_ALL_HEALTHBARS` # 9
--- | `NAMEPLATE_TYPE_ALL_NAMEPLATES` # 8
--- | `NAMEPLATE_TYPE_DEFUNCT_DONT_REMOVE_1` # 12
--- | `NAMEPLATE_TYPE_DEFUNCT_DONT_REMOVE_2` # 13
--- | `NAMEPLATE_TYPE_ENEMY_NPC_HEALTHBARS` # 5
--- | `NAMEPLATE_TYPE_ENEMY_NPC_HEALTHBARS_HIGHLIGHT` # 27
--- | `NAMEPLATE_TYPE_ENEMY_NPC_NAMEPLATES` # 4
--- | `NAMEPLATE_TYPE_ENEMY_NPC_NAMEPLATES_HIGHLIGHT` # 26
--- | `NAMEPLATE_TYPE_ENEMY_PLAYER_HEALTHBARS` # 7
--- | `NAMEPLATE_TYPE_ENEMY_PLAYER_HEALTHBARS_HIGHLIGHT` # 29
--- | `NAMEPLATE_TYPE_ENEMY_PLAYER_NAMEPLATES` # 6
--- | `NAMEPLATE_TYPE_ENEMY_PLAYER_NAMEPLATES_HIGHLIGHT` # 28
--- | `NAMEPLATE_TYPE_FOLLOWER_INDICATORS` # 17
--- | `NAMEPLATE_TYPE_FRIENDLY_NPC_HEALTHBARS` # 1
--- | `NAMEPLATE_TYPE_FRIENDLY_NPC_HEALTHBARS_HIGHLIGHT` # 23
--- | `NAMEPLATE_TYPE_FRIENDLY_NPC_NAMEPLATES` # 0
--- | `NAMEPLATE_TYPE_FRIENDLY_NPC_NAMEPLATES_HIGHLIGHT` # 22
--- | `NAMEPLATE_TYPE_FRIENDLY_PLAYER_HEALTHBARS` # 3
--- | `NAMEPLATE_TYPE_FRIENDLY_PLAYER_HEALTHBARS_HIGHLIGHT` # 25
--- | `NAMEPLATE_TYPE_FRIENDLY_PLAYER_NAMEPLATES` # 2
--- | `NAMEPLATE_TYPE_FRIENDLY_PLAYER_NAMEPLATES_HIGHLIGHT` # 24
--- | `NAMEPLATE_TYPE_GROUP_INDICATORS` # 15
--- | `NAMEPLATE_TYPE_GROUP_MEMBER_HEALTHBARS` # 19
--- | `NAMEPLATE_TYPE_GROUP_MEMBER_HEALTHBARS_HIGHLIGHT` # 21
--- | `NAMEPLATE_TYPE_GROUP_MEMBER_NAMEPLATES` # 18
--- | `NAMEPLATE_TYPE_GROUP_MEMBER_NAMEPLATES_HIGHLIGHT` # 20
--- | `NAMEPLATE_TYPE_HEALTHBAR_ALIGNMENT` # 34
--- | `NAMEPLATE_TYPE_HEALTHBAR_CHASE_BAR` # 35
--- | `NAMEPLATE_TYPE_HEALTHBAR_FRAME_BORDER` # 40
--- | `NAMEPLATE_TYPE_NEUTRAL_NPC_HEALTHBARS` # 37
--- | `NAMEPLATE_TYPE_NEUTRAL_NPC_HEALTHBARS_HIGHLIGHT` # 39
--- | `NAMEPLATE_TYPE_NEUTRAL_NPC_NAMEPLATES` # 36
--- | `NAMEPLATE_TYPE_NEUTRAL_NPC_NAMEPLATES_HIGHLIGHT` # 38
--- | `NAMEPLATE_TYPE_PLAYER_HEALTHBAR` # 11
--- | `NAMEPLATE_TYPE_PLAYER_HEALTHBAR_HIGHLIGHT` # 31
--- | `NAMEPLATE_TYPE_PLAYER_NAMEPLATE` # 10
--- | `NAMEPLATE_TYPE_PLAYER_NAMEPLATE_HIGHLIGHT` # 30
--- | `NAMEPLATE_TYPE_RESURRECT_INDICATORS` # 16
--- | `NAMEPLATE_TYPE_SHOW_PLAYER_GUILDS` # 33
--- | `NAMEPLATE_TYPE_SHOW_PLAYER_TITLES` # 32
--- | `NAMEPLATE_TYPE_TARGET_MARKERS` # 41

NAMEPLATE_TYPE_ALLIANCE_INDICATORS = 14
NAMEPLATE_TYPE_ALL_HEALTHBARS = 9
NAMEPLATE_TYPE_ALL_NAMEPLATES = 8
NAMEPLATE_TYPE_DEFUNCT_DONT_REMOVE_1 = 12
NAMEPLATE_TYPE_DEFUNCT_DONT_REMOVE_2 = 13
NAMEPLATE_TYPE_ENEMY_NPC_HEALTHBARS = 5
NAMEPLATE_TYPE_ENEMY_NPC_HEALTHBARS_HIGHLIGHT = 27
NAMEPLATE_TYPE_ENEMY_NPC_NAMEPLATES = 4
NAMEPLATE_TYPE_ENEMY_NPC_NAMEPLATES_HIGHLIGHT = 26
NAMEPLATE_TYPE_ENEMY_PLAYER_HEALTHBARS = 7
NAMEPLATE_TYPE_ENEMY_PLAYER_HEALTHBARS_HIGHLIGHT = 29
NAMEPLATE_TYPE_ENEMY_PLAYER_NAMEPLATES = 6
NAMEPLATE_TYPE_ENEMY_PLAYER_NAMEPLATES_HIGHLIGHT = 28
NAMEPLATE_TYPE_FOLLOWER_INDICATORS = 17
NAMEPLATE_TYPE_FRIENDLY_NPC_HEALTHBARS = 1
NAMEPLATE_TYPE_FRIENDLY_NPC_HEALTHBARS_HIGHLIGHT = 23
NAMEPLATE_TYPE_FRIENDLY_NPC_NAMEPLATES = 0
NAMEPLATE_TYPE_FRIENDLY_NPC_NAMEPLATES_HIGHLIGHT = 22
NAMEPLATE_TYPE_FRIENDLY_PLAYER_HEALTHBARS = 3
NAMEPLATE_TYPE_FRIENDLY_PLAYER_HEALTHBARS_HIGHLIGHT = 25
NAMEPLATE_TYPE_FRIENDLY_PLAYER_NAMEPLATES = 2
NAMEPLATE_TYPE_FRIENDLY_PLAYER_NAMEPLATES_HIGHLIGHT = 24
NAMEPLATE_TYPE_GROUP_INDICATORS = 15
NAMEPLATE_TYPE_GROUP_MEMBER_HEALTHBARS = 19
NAMEPLATE_TYPE_GROUP_MEMBER_HEALTHBARS_HIGHLIGHT = 21
NAMEPLATE_TYPE_GROUP_MEMBER_NAMEPLATES = 18
NAMEPLATE_TYPE_GROUP_MEMBER_NAMEPLATES_HIGHLIGHT = 20
NAMEPLATE_TYPE_HEALTHBAR_ALIGNMENT = 34
NAMEPLATE_TYPE_HEALTHBAR_CHASE_BAR = 35
NAMEPLATE_TYPE_HEALTHBAR_FRAME_BORDER = 40
NAMEPLATE_TYPE_NEUTRAL_NPC_HEALTHBARS = 37
NAMEPLATE_TYPE_NEUTRAL_NPC_HEALTHBARS_HIGHLIGHT = 39
NAMEPLATE_TYPE_NEUTRAL_NPC_NAMEPLATES = 36
NAMEPLATE_TYPE_NEUTRAL_NPC_NAMEPLATES_HIGHLIGHT = 38
NAMEPLATE_TYPE_PLAYER_HEALTHBAR = 11
NAMEPLATE_TYPE_PLAYER_HEALTHBAR_HIGHLIGHT = 31
NAMEPLATE_TYPE_PLAYER_NAMEPLATE = 10
NAMEPLATE_TYPE_PLAYER_NAMEPLATE_HIGHLIGHT = 30
NAMEPLATE_TYPE_RESURRECT_INDICATORS = 16
NAMEPLATE_TYPE_SHOW_PLAYER_GUILDS = 33
NAMEPLATE_TYPE_SHOW_PLAYER_TITLES = 32
NAMEPLATE_TYPE_TARGET_MARKERS = 41
