--- @meta NamingError

--- @alias NamingError integer
--- | `NAME_RULE_CANNOT_RENAME` # 11
--- | `NAME_RULE_CANNOT_START_WITH_SPACE` # 9
--- | `NAME_RULE_DUPLICATE_NAME` # 2
--- | `NAME_RULE_INVALID_CHARACTERS` # 13
--- | `NAME_RULE_INVALID_NAME` # 1
--- | `NAME_RULE_MUST_END_WITH_LETTER` # 6
--- | `NAME_RULE_NO_ADJACENT_PUNCTUATION_CHARACTERS` # 5
--- | `NAME_RULE_NO_ERROR` # 0
--- | `NAME_RULE_NO_NUMBERS` # 12
--- | `NAME_RULE_SYSTEM_ERROR` # 10
--- | `NAME_RULE_TOO_FEW_ALPHA_CHARACTERS` # 14
--- | `NAME_RULE_TOO_LONG` # 4
--- | `NAME_RULE_TOO_MANY_IDENTICAL_ADJACENT_CHARACTERS` # 7
--- | `NAME_RULE_TOO_MANY_PUNCTUATION_CHARACTERS` # 8
--- | `NAME_RULE_TOO_SHORT` # 3

NAME_RULE_CANNOT_RENAME = 11
NAME_RULE_CANNOT_START_WITH_SPACE = 9
NAME_RULE_DUPLICATE_NAME = 2
NAME_RULE_INVALID_CHARACTERS = 13
NAME_RULE_INVALID_NAME = 1
NAME_RULE_MUST_END_WITH_LETTER = 6
NAME_RULE_NO_ADJACENT_PUNCTUATION_CHARACTERS = 5
NAME_RULE_NO_ERROR = 0
NAME_RULE_NO_NUMBERS = 12
NAME_RULE_SYSTEM_ERROR = 10
NAME_RULE_TOO_FEW_ALPHA_CHARACTERS = 14
NAME_RULE_TOO_LONG = 4
NAME_RULE_TOO_MANY_IDENTICAL_ADJACENT_CHARACTERS = 7
NAME_RULE_TOO_MANY_PUNCTUATION_CHARACTERS = 8
NAME_RULE_TOO_SHORT = 3
