--- @meta NarrationVoiceSpeed

--- @alias NarrationVoiceSpeed integer
--- | `NARRATION_VOICE_SPEED_EXTRA_FAST` # 2
--- | `NARRATION_VOICE_SPEED_FAST` # 1
--- | `NARRATION_VOICE_SPEED_NORMAL` # 0

NARRATION_VOICE_SPEED_EXTRA_FAST = 2
NARRATION_VOICE_SPEED_FAST = 1
NARRATION_VOICE_SPEED_NORMAL = 0
