--- @meta NonCombatBonusType

--- @alias NonCombatBonusType integer
--- | `NON_COMBAT_BONUS_ALCHEMY_CREATE_EXTRA` # 11
--- | `NON_COMBAT_BONUS_ALCHEMY_CREATE_PERCENT_DISCOUNT` # 13
--- | `NON_COMBAT_BONUS_ALCHEMY_LEVEL` # 2
--- | `NON_COMBAT_BONUS_ALCHEMY_NEGATIVE_DURATION` # 43
--- | `NON_COMBAT_BONUS_ALCHEMY_POTION_DURATION` # 14
--- | `NON_COMBAT_BONUS_ALCHEMY_SHOW_NODES` # 41
--- | `NON_COMBAT_BONUS_ALCHEMY_THIRD_SLOT` # 10
--- | `NON_COMBAT_BONUS_ALLIANCE_POINT_GAIN` # 87
--- | `NON_COMBAT_BONUS_ARCHIVAL_FORTUNES_GAIN` # 44
--- | `NON_COMBAT_BONUS_ARMOR_KNOWLEDGE` # 54
--- | `NON_COMBAT_BONUS_ASSAULT_BOUNTY_REDUCTION` # 74
--- | `NON_COMBAT_BONUS_AVA_REACH` # 88
--- | `NON_COMBAT_BONUS_AVOID_BLADE_OF_WOE_WITNESS_CHANCE` # 78
--- | `NON_COMBAT_BONUS_BLACKSMITHING_BOOSTER_BONUS` # 20
--- | `NON_COMBAT_BONUS_BLACKSMITHING_CRAFT_PERCENT_DISCOUNT` # 22
--- | `NON_COMBAT_BONUS_BLACKSMITHING_EXTRACT_LEVEL` # 21
--- | `NON_COMBAT_BONUS_BLACKSMITHING_HIRELING_LEVEL` # 24
--- | `NON_COMBAT_BONUS_BLACKSMITHING_LEVEL` # 18
--- | `NON_COMBAT_BONUS_BLACKSMITHING_RESEARCH_LEVEL` # 23
--- | `NON_COMBAT_BONUS_BLACKSMITHING_SHOW_NODES` # 19
--- | `NON_COMBAT_BONUS_BOUNTY_DECAY` # 64
--- | `NON_COMBAT_BONUS_CLEMENCY` # 70
--- | `NON_COMBAT_BONUS_CLEMENCY_ARREST_IMMUNITY` # 72
--- | `NON_COMBAT_BONUS_CLOTHIER_BOOSTER_BONUS` # 34
--- | `NON_COMBAT_BONUS_CLOTHIER_CRAFT_PERCENT_DISCOUNT` # 36
--- | `NON_COMBAT_BONUS_CLOTHIER_EXTRACT_LEVEL` # 35
--- | `NON_COMBAT_BONUS_CLOTHIER_HIRELING_LEVEL` # 38
--- | `NON_COMBAT_BONUS_CLOTHIER_LEVEL` # 32
--- | `NON_COMBAT_BONUS_CLOTHIER_RESEARCH_LEVEL` # 37
--- | `NON_COMBAT_BONUS_CLOTHIER_SHOW_NODES` # 33
--- | `NON_COMBAT_BONUS_DIG_SITE_SHOW_NODES` # 90
--- | `NON_COMBAT_BONUS_DOUBLE_DECONSTRUCTION_REWARDS_CHANCE` # 95
--- | `NON_COMBAT_BONUS_ENCHANTING_CRAFT_PERCENT_DISCOUNT` # 17
--- | `NON_COMBAT_BONUS_ENCHANTING_DECONSTRUCTION_UPGRADE` # 15
--- | `NON_COMBAT_BONUS_ENCHANTING_HIRELING_LEVEL` # 16
--- | `NON_COMBAT_BONUS_ENCHANTING_LEVEL` # 1
--- | `NON_COMBAT_BONUS_ENCHANTING_RARITY_LEVEL` # 12
--- | `NON_COMBAT_BONUS_ENCHANTING_SHOW_NODES` # 40
--- | `NON_COMBAT_BONUS_ENCHANTING_SLOT_IMPROVEMENT` # 39
--- | `NON_COMBAT_BONUS_ENLIGHTENED` # 58
--- | `NON_COMBAT_BONUS_EXTRACTION` # 60
--- | `NON_COMBAT_BONUS_FAST_TRAVEL_COST_REDUCTION` # 93
--- | `NON_COMBAT_BONUS_FENCE_HAGGLING` # 66
--- | `NON_COMBAT_BONUS_FENCE_SALESMAN` # 62
--- | `NON_COMBAT_BONUS_FISHING_TIME_REDUCTION_PERCENT` # 96
--- | `NON_COMBAT_BONUS_FORTUNE_SEEKER` # 52
--- | `NON_COMBAT_BONUS_FREE_POTION_OR_POISON_USE_PERCENT` # 98
--- | `NON_COMBAT_BONUS_GROOM` # 57
--- | `NON_COMBAT_BONUS_GUARD_KILL` # 75
--- | `NON_COMBAT_BONUS_GUARD_PURSUIT_DISTANCE_REDUCTION` # 69
--- | `NON_COMBAT_BONUS_HEAT_DECAY` # 65
--- | `NON_COMBAT_BONUS_IMPATIENCE` # 56
--- | `NON_COMBAT_BONUS_INVALID` # 0
--- | `NON_COMBAT_BONUS_JEWELRYCRAFTING_BOOSTER_BONUS` # 82
--- | `NON_COMBAT_BONUS_JEWELRYCRAFTING_CRAFT_PERCENT_DISCOUNT` # 84
--- | `NON_COMBAT_BONUS_JEWELRYCRAFTING_EXTRACT_LEVEL` # 83
--- | `NON_COMBAT_BONUS_JEWELRYCRAFTING_HIRELING_LEVEL` # 86
--- | `NON_COMBAT_BONUS_JEWELRYCRAFTING_LEVEL` # 80
--- | `NON_COMBAT_BONUS_JEWELRYCRAFTING_RESEARCH_LEVEL` # 85
--- | `NON_COMBAT_BONUS_JEWELRYCRAFTING_SHOW_NODES` # 81
--- | `NON_COMBAT_BONUS_MASTER_GATHERER` # 53
--- | `NON_COMBAT_BONUS_MERCHANT_HAGGLING` # 94
--- | `NON_COMBAT_BONUS_MOUNTED_AGGRO_RADIUS_REDUCTION` # 77
--- | `NON_COMBAT_BONUS_MURDER_BOUNTY_REDUCTION` # 73
--- | `NON_COMBAT_BONUS_PICKPOCKET_CHANCE` # 61
--- | `NON_COMBAT_BONUS_PROVISIONING_CREATE_EXTRA_DRINK` # 6
--- | `NON_COMBAT_BONUS_PROVISIONING_CREATE_EXTRA_FOOD` # 5
--- | `NON_COMBAT_BONUS_PROVISIONING_DRINK_DURATION` # 8
--- | `NON_COMBAT_BONUS_PROVISIONING_FOOD_DURATION` # 7
--- | `NON_COMBAT_BONUS_PROVISIONING_HIRELING_LEVEL` # 9
--- | `NON_COMBAT_BONUS_PROVISIONING_LEVEL` # 3
--- | `NON_COMBAT_BONUS_PROVISIONING_RARITY_LEVEL` # 4
--- | `NON_COMBAT_BONUS_PROVISIONING_SHOW_NODES` # 42
--- | `NON_COMBAT_BONUS_PVP_EXP` # 91
--- | `NON_COMBAT_BONUS_SECONDARY_WITNESS_RANGE_REDUCTION` # 68
--- | `NON_COMBAT_BONUS_SHADOWY_CONNECTIONS` # 79
--- | `NON_COMBAT_BONUS_SLY` # 63
--- | `NON_COMBAT_BONUS_SOUL_GEM_FREE_RESURRECT_PERCENT_CHANCE` # 97
--- | `NON_COMBAT_BONUS_TELVAR_MULTIPLIER` # 76
--- | `NON_COMBAT_BONUS_TIMELY_ESCAPE` # 71
--- | `NON_COMBAT_BONUS_TRAIT_IDENTIFIER` # 55
--- | `NON_COMBAT_BONUS_TREASURE_SHOW_NODES` # 89
--- | `NON_COMBAT_BONUS_UNUSED` # 59
--- | `NON_COMBAT_BONUS_WEAPON_ENCHANT_DECAY_RATE` # 92
--- | `NON_COMBAT_BONUS_WITNESS_RANGE_REDUCTION` # 67
--- | `NON_COMBAT_BONUS_WOODWORKING_BOOSTER_BONUS` # 27
--- | `NON_COMBAT_BONUS_WOODWORKING_CRAFT_PERCENT_DISCOUNT` # 29
--- | `NON_COMBAT_BONUS_WOODWORKING_EXTRACT_LEVEL` # 28
--- | `NON_COMBAT_BONUS_WOODWORKING_HIRELING_LEVEL` # 31
--- | `NON_COMBAT_BONUS_WOODWORKING_LEVEL` # 25
--- | `NON_COMBAT_BONUS_WOODWORKING_RESEARCH_LEVEL` # 30
--- | `NON_COMBAT_BONUS_WOODWORKING_SHOW_NODES` # 26

NON_COMBAT_BONUS_ALCHEMY_CREATE_EXTRA = 11
NON_COMBAT_BONUS_ALCHEMY_CREATE_PERCENT_DISCOUNT = 13
NON_COMBAT_BONUS_ALCHEMY_LEVEL = 2
NON_COMBAT_BONUS_ALCHEMY_NEGATIVE_DURATION = 43
NON_COMBAT_BONUS_ALCHEMY_POTION_DURATION = 14
NON_COMBAT_BONUS_ALCHEMY_SHOW_NODES = 41
NON_COMBAT_BONUS_ALCHEMY_THIRD_SLOT = 10
NON_COMBAT_BONUS_ALLIANCE_POINT_GAIN = 87
NON_COMBAT_BONUS_ARCHIVAL_FORTUNES_GAIN = 44
NON_COMBAT_BONUS_ARMOR_KNOWLEDGE = 54
NON_COMBAT_BONUS_ASSAULT_BOUNTY_REDUCTION = 74
NON_COMBAT_BONUS_AVA_REACH = 88
NON_COMBAT_BONUS_AVOID_BLADE_OF_WOE_WITNESS_CHANCE = 78
NON_COMBAT_BONUS_BLACKSMITHING_BOOSTER_BONUS = 20
NON_COMBAT_BONUS_BLACKSMITHING_CRAFT_PERCENT_DISCOUNT = 22
NON_COMBAT_BONUS_BLACKSMITHING_EXTRACT_LEVEL = 21
NON_COMBAT_BONUS_BLACKSMITHING_HIRELING_LEVEL = 24
NON_COMBAT_BONUS_BLACKSMITHING_LEVEL = 18
NON_COMBAT_BONUS_BLACKSMITHING_RESEARCH_LEVEL = 23
NON_COMBAT_BONUS_BLACKSMITHING_SHOW_NODES = 19
NON_COMBAT_BONUS_BOUNTY_DECAY = 64
NON_COMBAT_BONUS_CLEMENCY = 70
NON_COMBAT_BONUS_CLEMENCY_ARREST_IMMUNITY = 72
NON_COMBAT_BONUS_CLOTHIER_BOOSTER_BONUS = 34
NON_COMBAT_BONUS_CLOTHIER_CRAFT_PERCENT_DISCOUNT = 36
NON_COMBAT_BONUS_CLOTHIER_EXTRACT_LEVEL = 35
NON_COMBAT_BONUS_CLOTHIER_HIRELING_LEVEL = 38
NON_COMBAT_BONUS_CLOTHIER_LEVEL = 32
NON_COMBAT_BONUS_CLOTHIER_RESEARCH_LEVEL = 37
NON_COMBAT_BONUS_CLOTHIER_SHOW_NODES = 33
NON_COMBAT_BONUS_DIG_SITE_SHOW_NODES = 90
NON_COMBAT_BONUS_DOUBLE_DECONSTRUCTION_REWARDS_CHANCE = 95
NON_COMBAT_BONUS_ENCHANTING_CRAFT_PERCENT_DISCOUNT = 17
NON_COMBAT_BONUS_ENCHANTING_DECONSTRUCTION_UPGRADE = 15
NON_COMBAT_BONUS_ENCHANTING_HIRELING_LEVEL = 16
NON_COMBAT_BONUS_ENCHANTING_LEVEL = 1
NON_COMBAT_BONUS_ENCHANTING_RARITY_LEVEL = 12
NON_COMBAT_BONUS_ENCHANTING_SHOW_NODES = 40
NON_COMBAT_BONUS_ENCHANTING_SLOT_IMPROVEMENT = 39
NON_COMBAT_BONUS_ENLIGHTENED = 58
NON_COMBAT_BONUS_EXTRACTION = 60
NON_COMBAT_BONUS_FAST_TRAVEL_COST_REDUCTION = 93
NON_COMBAT_BONUS_FENCE_HAGGLING = 66
NON_COMBAT_BONUS_FENCE_SALESMAN = 62
NON_COMBAT_BONUS_FISHING_TIME_REDUCTION_PERCENT = 96
NON_COMBAT_BONUS_FORTUNE_SEEKER = 52
NON_COMBAT_BONUS_FREE_POTION_OR_POISON_USE_PERCENT = 98
NON_COMBAT_BONUS_GROOM = 57
NON_COMBAT_BONUS_GUARD_KILL = 75
NON_COMBAT_BONUS_GUARD_PURSUIT_DISTANCE_REDUCTION = 69
NON_COMBAT_BONUS_HEAT_DECAY = 65
NON_COMBAT_BONUS_IMPATIENCE = 56
NON_COMBAT_BONUS_INVALID = 0
NON_COMBAT_BONUS_JEWELRYCRAFTING_BOOSTER_BONUS = 82
NON_COMBAT_BONUS_JEWELRYCRAFTING_CRAFT_PERCENT_DISCOUNT = 84
NON_COMBAT_BONUS_JEWELRYCRAFTING_EXTRACT_LEVEL = 83
NON_COMBAT_BONUS_JEWELRYCRAFTING_HIRELING_LEVEL = 86
NON_COMBAT_BONUS_JEWELRYCRAFTING_LEVEL = 80
NON_COMBAT_BONUS_JEWELRYCRAFTING_RESEARCH_LEVEL = 85
NON_COMBAT_BONUS_JEWELRYCRAFTING_SHOW_NODES = 81
NON_COMBAT_BONUS_MASTER_GATHERER = 53
NON_COMBAT_BONUS_MERCHANT_HAGGLING = 94
NON_COMBAT_BONUS_MOUNTED_AGGRO_RADIUS_REDUCTION = 77
NON_COMBAT_BONUS_MURDER_BOUNTY_REDUCTION = 73
NON_COMBAT_BONUS_PICKPOCKET_CHANCE = 61
NON_COMBAT_BONUS_PROVISIONING_CREATE_EXTRA_DRINK = 6
NON_COMBAT_BONUS_PROVISIONING_CREATE_EXTRA_FOOD = 5
NON_COMBAT_BONUS_PROVISIONING_DRINK_DURATION = 8
NON_COMBAT_BONUS_PROVISIONING_FOOD_DURATION = 7
NON_COMBAT_BONUS_PROVISIONING_HIRELING_LEVEL = 9
NON_COMBAT_BONUS_PROVISIONING_LEVEL = 3
NON_COMBAT_BONUS_PROVISIONING_RARITY_LEVEL = 4
NON_COMBAT_BONUS_PROVISIONING_SHOW_NODES = 42
NON_COMBAT_BONUS_PVP_EXP = 91
NON_COMBAT_BONUS_SECONDARY_WITNESS_RANGE_REDUCTION = 68
NON_COMBAT_BONUS_SHADOWY_CONNECTIONS = 79
NON_COMBAT_BONUS_SLY = 63
NON_COMBAT_BONUS_SOUL_GEM_FREE_RESURRECT_PERCENT_CHANCE = 97
NON_COMBAT_BONUS_TELVAR_MULTIPLIER = 76
NON_COMBAT_BONUS_TIMELY_ESCAPE = 71
NON_COMBAT_BONUS_TRAIT_IDENTIFIER = 55
NON_COMBAT_BONUS_TREASURE_SHOW_NODES = 89
NON_COMBAT_BONUS_UNUSED = 59
NON_COMBAT_BONUS_WEAPON_ENCHANT_DECAY_RATE = 92
NON_COMBAT_BONUS_WITNESS_RANGE_REDUCTION = 67
NON_COMBAT_BONUS_WOODWORKING_BOOSTER_BONUS = 27
NON_COMBAT_BONUS_WOODWORKING_CRAFT_PERCENT_DISCOUNT = 29
NON_COMBAT_BONUS_WOODWORKING_EXTRACT_LEVEL = 28
NON_COMBAT_BONUS_WOODWORKING_HIRELING_LEVEL = 31
NON_COMBAT_BONUS_WOODWORKING_LEVEL = 25
NON_COMBAT_BONUS_WOODWORKING_RESEARCH_LEVEL = 30
NON_COMBAT_BONUS_WOODWORKING_SHOW_NODES = 26
