--- @meta NotificationType

--- @alias NotificationType integer
--- | `NOTIFICATION_TYPE_CAMPAIGN_QUEUE` # 3
--- | `NOTIFICATION_TYPE_COLLECTIONS` # 12
--- | `NOTIFICATION_TYPE_CRAFTED_ABILITY_RESET` # 20
--- | `NOTIFICATION_TYPE_CRAFT_BAG_AUTO_TRANSFER` # 15
--- | `NOTIFICATION_TYPE_CUSTOMER_SERVICE` # 9
--- | `NOTIFICATION_TYPE_DISABLED_ADDON` # 31
--- | `NOTIFICATION_TYPE_DUEL` # 17
--- | `NOTIFICATION_TYPE_ESO_PLUS_SUBSCRIPTION` # 18
--- | `NOTIFICATION_TYPE_EXPIRING_MARKET_CURRENCY` # 32
--- | `NOTIFICATION_TYPE_FRIEND` # 1
--- | `NOTIFICATION_TYPE_GIFT_CLAIMED` # 23
--- | `NOTIFICATION_TYPE_GIFT_RECEIVED` # 22
--- | `NOTIFICATION_TYPE_GIFT_RETURNED` # 24
--- | `NOTIFICATION_TYPE_GROUP` # 5
--- | `NOTIFICATION_TYPE_GROUP_ELECTION` # 16
--- | `NOTIFICATION_TYPE_GUILD` # 2
--- | `NOTIFICATION_TYPE_GUILD_MOTD` # 11
--- | `NOTIFICATION_TYPE_GUILD_NEW_APPLICATIONS` # 26
--- | `NOTIFICATION_TYPE_LEADERBOARD` # 10
--- | `NOTIFICATION_TYPE_LFG` # 13
--- | `NOTIFICATION_TYPE_MARKET_PRODUCT_AVAILABLE` # 28
--- | `NOTIFICATION_TYPE_NEW_DAILY_LOGIN_REWARD` # 21
--- | `NOTIFICATION_TYPE_OUT_OF_DATE_ADDONS` # 29
--- | `NOTIFICATION_TYPE_PLAYER_APPLICATIONS` # 27
--- | `NOTIFICATION_TYPE_PLEDGE_OF_MARA` # 8
--- | `NOTIFICATION_TYPE_POINTS_RESET` # 14
--- | `NOTIFICATION_TYPE_QUEST_SHARE` # 7
--- | `NOTIFICATION_TYPE_RESURRECT` # 4
--- | `NOTIFICATION_TYPE_SCRIPTED_WORLD_EVENT` # 19
--- | `NOTIFICATION_TYPE_TRADE` # 6
--- | `NOTIFICATION_TYPE_TRIBUTE_INVITE` # 30

NOTIFICATION_TYPE_CAMPAIGN_QUEUE = 3
NOTIFICATION_TYPE_COLLECTIONS = 12
NOTIFICATION_TYPE_CRAFTED_ABILITY_RESET = 20
NOTIFICATION_TYPE_CRAFT_BAG_AUTO_TRANSFER = 15
NOTIFICATION_TYPE_CUSTOMER_SERVICE = 9
NOTIFICATION_TYPE_DISABLED_ADDON = 31
NOTIFICATION_TYPE_DUEL = 17
NOTIFICATION_TYPE_ESO_PLUS_SUBSCRIPTION = 18
NOTIFICATION_TYPE_EXPIRING_MARKET_CURRENCY = 32
NOTIFICATION_TYPE_FRIEND = 1
NOTIFICATION_TYPE_GIFT_CLAIMED = 23
NOTIFICATION_TYPE_GIFT_RECEIVED = 22
NOTIFICATION_TYPE_GIFT_RETURNED = 24
NOTIFICATION_TYPE_GROUP = 5
NOTIFICATION_TYPE_GROUP_ELECTION = 16
NOTIFICATION_TYPE_GUILD = 2
NOTIFICATION_TYPE_GUILD_MOTD = 11
NOTIFICATION_TYPE_GUILD_NEW_APPLICATIONS = 26
NOTIFICATION_TYPE_LEADERBOARD = 10
NOTIFICATION_TYPE_LFG = 13
NOTIFICATION_TYPE_MARKET_PRODUCT_AVAILABLE = 28
NOTIFICATION_TYPE_NEW_DAILY_LOGIN_REWARD = 21
NOTIFICATION_TYPE_OUT_OF_DATE_ADDONS = 29
NOTIFICATION_TYPE_PLAYER_APPLICATIONS = 27
NOTIFICATION_TYPE_PLEDGE_OF_MARA = 8
NOTIFICATION_TYPE_POINTS_RESET = 14
NOTIFICATION_TYPE_QUEST_SHARE = 7
NOTIFICATION_TYPE_RESURRECT = 4
NOTIFICATION_TYPE_SCRIPTED_WORLD_EVENT = 19
NOTIFICATION_TYPE_TRADE = 6
NOTIFICATION_TYPE_TRIBUTE_INVITE = 30
