--- @meta NumberAbbreviationPrecision

--- @alias NumberAbbreviationPrecision integer
--- | `NUMBER_ABBREVIATION_PRECISION_HUNDREDTHS` # 2
--- | `NUMBER_ABBREVIATION_PRECISION_LARGEST_UNIT` # 0
--- | `NUMBER_ABBREVIATION_PRECISION_TENTHS` # 1

NUMBER_ABBREVIATION_PRECISION_HUNDREDTHS = 2
NUMBER_ABBREVIATION_PRECISION_LARGEST_UNIT = 0
NUMBER_ABBREVIATION_PRECISION_TENTHS = 1
