--- @meta ObjectiveDesignation

--- @alias ObjectiveDesignation integer
--- | `OBJECTIVE_DESIGNATION_A` # 1
--- | `OBJECTIVE_DESIGNATION_B` # 2
--- | `OBJECTIVE_DESIGNATION_C` # 3
--- | `OBJECTIVE_DESIGNATION_D` # 4
--- | `OBJECTIVE_DESIGNATION_NONE` # 0

OBJECTIVE_DESIGNATION_A = 1
OBJECTIVE_DESIGNATION_B = 2
OBJECTIVE_DESIGNATION_C = 3
OBJECTIVE_DESIGNATION_D = 4
OBJECTIVE_DESIGNATION_NONE = 0
