--- @meta ObjectiveControlEvent

--- @alias ObjectiveControlEvent integer
--- | `OBJECTIVE_CONTROL_EVENT_AREA_INFLUENCE_CHANGED` # 11
--- | `OBJECTIVE_CONTROL_EVENT_AREA_NEUTRAL` # 6
--- | `OBJECTIVE_CONTROL_EVENT_ASSAULTED` # 4
--- | `OBJECTIVE_CONTROL_EVENT_CAPTURED` # 2
--- | `OBJECTIVE_CONTROL_EVENT_DEACTIVATED` # 14
--- | `OBJECTIVE_CONTROL_EVENT_DEACTIVATE_PENDING` # 15
--- | `OBJECTIVE_CONTROL_EVENT_FLAG_DROPPED` # 9
--- | `OBJECTIVE_CONTROL_EVENT_FLAG_RETURNED` # 8
--- | `OBJECTIVE_CONTROL_EVENT_FLAG_RETURNED_BY_TIMER` # 10
--- | `OBJECTIVE_CONTROL_EVENT_FLAG_SPAWNED` # 13
--- | `OBJECTIVE_CONTROL_EVENT_FLAG_TAKEN` # 7
--- | `OBJECTIVE_CONTROL_EVENT_FULLY_HELD` # 5
--- | `OBJECTIVE_CONTROL_EVENT_HIDDEN` # 16
--- | `OBJECTIVE_CONTROL_EVENT_LOST` # 1
--- | `OBJECTIVE_CONTROL_EVENT_NONE` # 12
--- | `OBJECTIVE_CONTROL_EVENT_RECAPTURED` # 3
--- | `OBJECTIVE_CONTROL_EVENT_UNDER_ATTACK` # 0

OBJECTIVE_CONTROL_EVENT_AREA_INFLUENCE_CHANGED = 11
OBJECTIVE_CONTROL_EVENT_AREA_NEUTRAL = 6
OBJECTIVE_CONTROL_EVENT_ASSAULTED = 4
OBJECTIVE_CONTROL_EVENT_CAPTURED = 2
OBJECTIVE_CONTROL_EVENT_DEACTIVATED = 14
OBJECTIVE_CONTROL_EVENT_DEACTIVATE_PENDING = 15
OBJECTIVE_CONTROL_EVENT_FLAG_DROPPED = 9
OBJECTIVE_CONTROL_EVENT_FLAG_RETURNED = 8
OBJECTIVE_CONTROL_EVENT_FLAG_RETURNED_BY_TIMER = 10
OBJECTIVE_CONTROL_EVENT_FLAG_SPAWNED = 13
OBJECTIVE_CONTROL_EVENT_FLAG_TAKEN = 7
OBJECTIVE_CONTROL_EVENT_FULLY_HELD = 5
OBJECTIVE_CONTROL_EVENT_HIDDEN = 16
OBJECTIVE_CONTROL_EVENT_LOST = 1
OBJECTIVE_CONTROL_EVENT_NONE = 12
OBJECTIVE_CONTROL_EVENT_RECAPTURED = 3
OBJECTIVE_CONTROL_EVENT_UNDER_ATTACK = 0
