--- @meta ObjectivePinTier

--- @alias ObjectivePinTier integer
--- | `OBJECTIVE_PIN_TIER_PRIMARY` # 0
--- | `OBJECTIVE_PIN_TIER_RETURN` # 2
--- | `OBJECTIVE_PIN_TIER_SPAWN` # 1

OBJECTIVE_PIN_TIER_PRIMARY = 0
OBJECTIVE_PIN_TIER_RETURN = 2
OBJECTIVE_PIN_TIER_SPAWN = 1
