--- @meta ObjectiveControlState

--- @alias ObjectiveControlState integer
--- | `OBJECTIVE_CONTROL_STATE_AREA_ABOVE_CONTROL_THRESHOLD` # 6
--- | `OBJECTIVE_CONTROL_STATE_AREA_BELOW_CONTROL_THRESHOLD` # 5
--- | `OBJECTIVE_CONTROL_STATE_AREA_INACTIVE` # 11
--- | `OBJECTIVE_CONTROL_STATE_AREA_MAX_CONTROL` # 7
--- | `OBJECTIVE_CONTROL_STATE_AREA_NO_CONTROL` # 4
--- | `OBJECTIVE_CONTROL_STATE_FLAG_AT_BASE` # 0
--- | `OBJECTIVE_CONTROL_STATE_FLAG_AT_ENEMY_BASE` # 3
--- | `OBJECTIVE_CONTROL_STATE_FLAG_DROPPED` # 1
--- | `OBJECTIVE_CONTROL_STATE_FLAG_HELD` # 2
--- | `OBJECTIVE_CONTROL_STATE_POINT_CONTROLLED` # 9
--- | `OBJECTIVE_CONTROL_STATE_POINT_TRANSITIONING` # 8
--- | `OBJECTIVE_CONTROL_STATE_UNKNOWN` # 10

OBJECTIVE_CONTROL_STATE_AREA_ABOVE_CONTROL_THRESHOLD = 6
OBJECTIVE_CONTROL_STATE_AREA_BELOW_CONTROL_THRESHOLD = 5
OBJECTIVE_CONTROL_STATE_AREA_INACTIVE = 11
OBJECTIVE_CONTROL_STATE_AREA_MAX_CONTROL = 7
OBJECTIVE_CONTROL_STATE_AREA_NO_CONTROL = 4
OBJECTIVE_CONTROL_STATE_FLAG_AT_BASE = 0
OBJECTIVE_CONTROL_STATE_FLAG_AT_ENEMY_BASE = 3
OBJECTIVE_CONTROL_STATE_FLAG_DROPPED = 1
OBJECTIVE_CONTROL_STATE_FLAG_HELD = 2
OBJECTIVE_CONTROL_STATE_POINT_CONTROLLED = 9
OBJECTIVE_CONTROL_STATE_POINT_TRANSITIONING = 8
OBJECTIVE_CONTROL_STATE_UNKNOWN = 10
