--- @meta ObjectiveType

--- @alias ObjectiveType integer
--- | `OBJECTIVE_ARTIFACT_DEFENSIVE` # 9
--- | `OBJECTIVE_ARTIFACT_OFFENSIVE` # 8
--- | `OBJECTIVE_ARTIFACT_RETURN` # 10
--- | `OBJECTIVE_ASSAULT` # 5
--- | `OBJECTIVE_BALL` # 7
--- | `OBJECTIVE_CAPTURE_AREA` # 4
--- | `OBJECTIVE_CAPTURE_POINT` # 3
--- | `OBJECTIVE_DAEDRIC_WEAPON` # 11
--- | `OBJECTIVE_FLAG_CAPTURE` # 1
--- | `OBJECTIVE_NONE` # 0
--- | `OBJECTIVE_RETURN` # 6

OBJECTIVE_ARTIFACT_DEFENSIVE = 9
OBJECTIVE_ARTIFACT_OFFENSIVE = 8
OBJECTIVE_ARTIFACT_RETURN = 10
OBJECTIVE_ASSAULT = 5
OBJECTIVE_BALL = 7
OBJECTIVE_CAPTURE_AREA = 4
OBJECTIVE_CAPTURE_POINT = 3
OBJECTIVE_DAEDRIC_WEAPON = 11
OBJECTIVE_FLAG_CAPTURE = 1
OBJECTIVE_NONE = 0
OBJECTIVE_RETURN = 6
