--- @meta OfficialLanguage

--- @alias OfficialLanguage integer
--- | `OFFICIAL_LANGUAGE_CHINESE_S` # 6
--- | `OFFICIAL_LANGUAGE_ENGLISH` # 0
--- | `OFFICIAL_LANGUAGE_FRENCH` # 1
--- | `OFFICIAL_LANGUAGE_GERMAN` # 2
--- | `OFFICIAL_LANGUAGE_JAPANESE` # 3
--- | `OFFICIAL_LANGUAGE_RUSSIAN` # 4
--- | `OFFICIAL_LANGUAGE_SPANISH` # 5

OFFICIAL_LANGUAGE_CHINESE_S = 6
OFFICIAL_LANGUAGE_ENGLISH = 0
OFFICIAL_LANGUAGE_FRENCH = 1
OFFICIAL_LANGUAGE_GERMAN = 2
OFFICIAL_LANGUAGE_JAPANESE = 3
OFFICIAL_LANGUAGE_RUSSIAN = 4
OFFICIAL_LANGUAGE_SPANISH = 5
