--- @meta OpenMarketBehavior

--- @alias OpenMarketBehavior integer
--- | `OPEN_MARKET_BEHAVIOR_NAVIGATE_TO_OTHER_PRODUCT` # 3
--- | `OPEN_MARKET_BEHAVIOR_NAVIGATE_TO_PRODUCT` # 0
--- | `OPEN_MARKET_BEHAVIOR_SHOW_CHAPTER_UPGRADE` # 4
--- | `OPEN_MARKET_BEHAVIOR_SHOW_ESO_PLUS_CATEGORY` # 2
--- | `OPEN_MARKET_BEHAVIOR_SHOW_FEATURED_CATEGORY` # 1
--- | `OPEN_MARKET_BEHAVIOR_SHOW_MARKET_PRODUCT_CATEGORY` # 5

OPEN_MARKET_BEHAVIOR_NAVIGATE_TO_OTHER_PRODUCT = 3
OPEN_MARKET_BEHAVIOR_NAVIGATE_TO_PRODUCT = 0
OPEN_MARKET_BEHAVIOR_SHOW_CHAPTER_UPGRADE = 4
OPEN_MARKET_BEHAVIOR_SHOW_ESO_PLUS_CATEGORY = 2
OPEN_MARKET_BEHAVIOR_SHOW_FEATURED_CATEGORY = 1
OPEN_MARKET_BEHAVIOR_SHOW_MARKET_PRODUCT_CATEGORY = 5
