--- @meta OptionsCustomSetting

--- @alias OptionsCustomSetting integer
--- | `OPTIONS_CUSTOM_SETTING_CHAT_BUBBLE_EMOTE_ENABLED` # 4
--- | `OPTIONS_CUSTOM_SETTING_CHAT_BUBBLE_GROUP_ENABLED` # 3
--- | `OPTIONS_CUSTOM_SETTING_CHAT_BUBBLE_SAY_ENABLED` # 0
--- | `OPTIONS_CUSTOM_SETTING_CHAT_BUBBLE_WHISPER_ENABLED` # 2
--- | `OPTIONS_CUSTOM_SETTING_CHAT_BUBBLE_YELL_ENABLED` # 1
--- | `OPTIONS_CUSTOM_SETTING_FRAMERATE_LATENCY_RESET_POSITION` # 46
--- | `OPTIONS_CUSTOM_SETTING_GAMEPAD_PREGAME_PLAY_CINEMATIC` # 35
--- | `OPTIONS_CUSTOM_SETTING_GAMEPAD_PREGAME_SERVER_SELECT` # 36
--- | `OPTIONS_CUSTOM_SETTING_GAMEPAD_PREGAME_VIEW_CREDITS` # 34
--- | `OPTIONS_CUSTOM_SETTING_GAMMA_ADJUST` # 38
--- | `OPTIONS_CUSTOM_SETTING_MONSTER_TELLS_ENEMY_TEST` # 43
--- | `OPTIONS_CUSTOM_SETTING_MONSTER_TELLS_FRIENDLY_TEST` # 42
--- | `OPTIONS_CUSTOM_SETTING_RESEND_EMAIL_ACTIVATION` # 45
--- | `OPTIONS_CUSTOM_SETTING_RESET_GAMEPAD_CONTROLS` # 48
--- | `OPTIONS_CUSTOM_SETTING_RESET_TUTORIALS` # 39
--- | `OPTIONS_CUSTOM_SETTING_SCREENSHOT_MODE` # 44
--- | `OPTIONS_CUSTOM_SETTING_SCREEN_ADJUST` # 37
--- | `OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_EMOTE` # 17
--- | `OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_GROUP` # 11
--- | `OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_GUILD1` # 20
--- | `OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_GUILD2` # 23
--- | `OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_GUILD3` # 26
--- | `OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_GUILD4` # 29
--- | `OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_GUILD5` # 32
--- | `OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_NPC` # 16
--- | `OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_OFFICER1` # 21
--- | `OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_OFFICER2` # 24
--- | `OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_OFFICER3` # 27
--- | `OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_OFFICER4` # 30
--- | `OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_OFFICER5` # 33
--- | `OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_SAY` # 7
--- | `OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_SYSTEM` # 18
--- | `OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_WHISPER_INC` # 9
--- | `OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_WHISPER_OUT` # 10
--- | `OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_YELL` # 8
--- | `OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_ZONE` # 12
--- | `OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_ZONE_ENG` # 13
--- | `OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_ZONE_FRA` # 14
--- | `OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_ZONE_GER` # 15
--- | `OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_ZONE_JPN` # 40
--- | `OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_ZONE_RUS` # 47
--- | `OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_ZONE_SCN` # 50
--- | `OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_ZONE_SPA` # 49
--- | `OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_TITLE_GUILD1` # 19
--- | `OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_TITLE_GUILD2` # 22
--- | `OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_TITLE_GUILD3` # 25
--- | `OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_TITLE_GUILD4` # 28
--- | `OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_TITLE_GUILD5` # 31
--- | `OPTIONS_CUSTOM_SETTING_SOCIAL_GAMEPAD_TEXT_SIZE` # 41
--- | `OPTIONS_CUSTOM_SETTING_SOCIAL_MIN_ALPHA` # 6
--- | `OPTIONS_CUSTOM_SETTING_SOCIAL_TEXT_SIZE` # 5

OPTIONS_CUSTOM_SETTING_CHAT_BUBBLE_EMOTE_ENABLED = 4
OPTIONS_CUSTOM_SETTING_CHAT_BUBBLE_GROUP_ENABLED = 3
OPTIONS_CUSTOM_SETTING_CHAT_BUBBLE_SAY_ENABLED = 0
OPTIONS_CUSTOM_SETTING_CHAT_BUBBLE_WHISPER_ENABLED = 2
OPTIONS_CUSTOM_SETTING_CHAT_BUBBLE_YELL_ENABLED = 1
OPTIONS_CUSTOM_SETTING_FRAMERATE_LATENCY_RESET_POSITION = 46
OPTIONS_CUSTOM_SETTING_GAMEPAD_PREGAME_PLAY_CINEMATIC = 35
OPTIONS_CUSTOM_SETTING_GAMEPAD_PREGAME_SERVER_SELECT = 36
OPTIONS_CUSTOM_SETTING_GAMEPAD_PREGAME_VIEW_CREDITS = 34
OPTIONS_CUSTOM_SETTING_GAMMA_ADJUST = 38
OPTIONS_CUSTOM_SETTING_MONSTER_TELLS_ENEMY_TEST = 43
OPTIONS_CUSTOM_SETTING_MONSTER_TELLS_FRIENDLY_TEST = 42
OPTIONS_CUSTOM_SETTING_RESEND_EMAIL_ACTIVATION = 45
OPTIONS_CUSTOM_SETTING_RESET_GAMEPAD_CONTROLS = 48
OPTIONS_CUSTOM_SETTING_RESET_TUTORIALS = 39
OPTIONS_CUSTOM_SETTING_SCREENSHOT_MODE = 44
OPTIONS_CUSTOM_SETTING_SCREEN_ADJUST = 37
OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_EMOTE = 17
OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_GROUP = 11
OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_GUILD1 = 20
OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_GUILD2 = 23
OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_GUILD3 = 26
OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_GUILD4 = 29
OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_GUILD5 = 32
OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_NPC = 16
OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_OFFICER1 = 21
OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_OFFICER2 = 24
OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_OFFICER3 = 27
OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_OFFICER4 = 30
OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_OFFICER5 = 33
OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_SAY = 7
OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_SYSTEM = 18
OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_WHISPER_INC = 9
OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_WHISPER_OUT = 10
OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_YELL = 8
OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_ZONE = 12
OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_ZONE_ENG = 13
OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_ZONE_FRA = 14
OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_ZONE_GER = 15
OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_ZONE_JPN = 40
OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_ZONE_RUS = 47
OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_ZONE_SCN = 50
OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_COLOR_ZONE_SPA = 49
OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_TITLE_GUILD1 = 19
OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_TITLE_GUILD2 = 22
OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_TITLE_GUILD3 = 25
OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_TITLE_GUILD4 = 28
OPTIONS_CUSTOM_SETTING_SOCIAL_CHAT_TITLE_GUILD5 = 31
OPTIONS_CUSTOM_SETTING_SOCIAL_GAMEPAD_TEXT_SIZE = 41
OPTIONS_CUSTOM_SETTING_SOCIAL_MIN_ALPHA = 6
OPTIONS_CUSTOM_SETTING_SOCIAL_TEXT_SIZE = 5
