--- @meta OutfitSlot

--- @alias OutfitSlot integer
--- | `OUTFIT_SLOT_BODY_MARKING` # 23
--- | `OUTFIT_SLOT_CHEST` # 1
--- | `OUTFIT_SLOT_COSTUME` # 13
--- | `OUTFIT_SLOT_FACIAL_ACCESSORY` # 20
--- | `OUTFIT_SLOT_FACIAL_HAIR_HORNS` # 19
--- | `OUTFIT_SLOT_FEET` # 6
--- | `OUTFIT_SLOT_HAIR` # 18
--- | `OUTFIT_SLOT_HANDS` # 3
--- | `OUTFIT_SLOT_HAT` # 14
--- | `OUTFIT_SLOT_HEAD` # 0
--- | `OUTFIT_SLOT_HEAD_MARKING` # 22
--- | `OUTFIT_SLOT_LEGS` # 5
--- | `OUTFIT_SLOT_MOUNT` # 16
--- | `OUTFIT_SLOT_PERSONALITY` # 17
--- | `OUTFIT_SLOT_PIERCING_JEWELRY` # 21
--- | `OUTFIT_SLOT_POLYMORPH` # 31
--- | `OUTFIT_SLOT_SHIELD` # 12
--- | `OUTFIT_SLOT_SHIELD_BACKUP` # 29
--- | `OUTFIT_SLOT_SHOULDERS` # 2
--- | `OUTFIT_SLOT_SKIN` # 15
--- | `OUTFIT_SLOT_VANITY_PET` # 30
--- | `OUTFIT_SLOT_WAIST` # 4
--- | `OUTFIT_SLOT_WEAPON_BOW` # 11
--- | `OUTFIT_SLOT_WEAPON_BOW_BACKUP` # 28
--- | `OUTFIT_SLOT_WEAPON_MAIN_HAND` # 7
--- | `OUTFIT_SLOT_WEAPON_MAIN_HAND_BACKUP` # 24
--- | `OUTFIT_SLOT_WEAPON_OFF_HAND` # 8
--- | `OUTFIT_SLOT_WEAPON_OFF_HAND_BACKUP` # 25
--- | `OUTFIT_SLOT_WEAPON_STAFF` # 10
--- | `OUTFIT_SLOT_WEAPON_STAFF_BACKUP` # 27
--- | `OUTFIT_SLOT_WEAPON_TWO_HANDED` # 9
--- | `OUTFIT_SLOT_WEAPON_TWO_HANDED_BACKUP` # 26

OUTFIT_SLOT_BODY_MARKING = 23
OUTFIT_SLOT_CHEST = 1
OUTFIT_SLOT_COSTUME = 13
OUTFIT_SLOT_FACIAL_ACCESSORY = 20
OUTFIT_SLOT_FACIAL_HAIR_HORNS = 19
OUTFIT_SLOT_FEET = 6
OUTFIT_SLOT_HAIR = 18
OUTFIT_SLOT_HANDS = 3
OUTFIT_SLOT_HAT = 14
OUTFIT_SLOT_HEAD = 0
OUTFIT_SLOT_HEAD_MARKING = 22
OUTFIT_SLOT_LEGS = 5
OUTFIT_SLOT_MOUNT = 16
OUTFIT_SLOT_PERSONALITY = 17
OUTFIT_SLOT_PIERCING_JEWELRY = 21
OUTFIT_SLOT_POLYMORPH = 31
OUTFIT_SLOT_SHIELD = 12
OUTFIT_SLOT_SHIELD_BACKUP = 29
OUTFIT_SLOT_SHOULDERS = 2
OUTFIT_SLOT_SKIN = 15
OUTFIT_SLOT_VANITY_PET = 30
OUTFIT_SLOT_WAIST = 4
OUTFIT_SLOT_WEAPON_BOW = 11
OUTFIT_SLOT_WEAPON_BOW_BACKUP = 28
OUTFIT_SLOT_WEAPON_MAIN_HAND = 7
OUTFIT_SLOT_WEAPON_MAIN_HAND_BACKUP = 24
OUTFIT_SLOT_WEAPON_OFF_HAND = 8
OUTFIT_SLOT_WEAPON_OFF_HAND_BACKUP = 25
OUTFIT_SLOT_WEAPON_STAFF = 10
OUTFIT_SLOT_WEAPON_STAFF_BACKUP = 27
OUTFIT_SLOT_WEAPON_TWO_HANDED = 9
OUTFIT_SLOT_WEAPON_TWO_HANDED_BACKUP = 26
