--- @meta OverrideMusicMode

--- @alias OverrideMusicMode integer
--- | `OVERRIDE_MUSIC_MODE_CHAMPION` # 2
--- | `OVERRIDE_MUSIC_MODE_CREDITS` # 1
--- | `OVERRIDE_MUSIC_MODE_DUELING` # 3
--- | `OVERRIDE_MUSIC_MODE_NONE` # 0
--- | `OVERRIDE_MUSIC_MODE_TRIBUTE` # 4

OVERRIDE_MUSIC_MODE_CHAMPION = 2
OVERRIDE_MUSIC_MODE_CREDITS = 1
OVERRIDE_MUSIC_MODE_DUELING = 3
OVERRIDE_MUSIC_MODE_NONE = 0
OVERRIDE_MUSIC_MODE_TRIBUTE = 4
