--- @meta ParticleDensity

--- @alias ParticleDensity integer
--- | `PARTICLE_DENSITY_HIGH` # 2
--- | `PARTICLE_DENSITY_LOW` # 0
--- | `PARTICLE_DENSITY_MEDIUM` # 1
--- | `PARTICLE_DENSITY_ULTRA` # 3

PARTICLE_DENSITY_HIGH = 2
PARTICLE_DENSITY_LOW = 0
PARTICLE_DENSITY_MEDIUM = 1
PARTICLE_DENSITY_ULTRA = 3
