--- @meta PathFollowType

--- @alias PathFollowType integer
--- | `PATH_FOLLOW_TYPE_LOOP` # 1
--- | `PATH_FOLLOW_TYPE_ONE_WAY` # 3
--- | `PATH_FOLLOW_TYPE_PINGPONG` # 0
--- | `PATH_FOLLOW_TYPE_RANDOM` # 2

PATH_FOLLOW_TYPE_LOOP = 1
PATH_FOLLOW_TYPE_ONE_WAY = 3
PATH_FOLLOW_TYPE_PINGPONG = 0
PATH_FOLLOW_TYPE_RANDOM = 2
