--- @meta PickpocketDifficultyType

--- @alias PickpocketDifficultyType integer
--- | `PICKPOCKET_DIFFICULTY_EASY` # 1
--- | `PICKPOCKET_DIFFICULTY_HARD` # 3
--- | `PICKPOCKET_DIFFICULTY_INVALID` # 0
--- | `PICKPOCKET_DIFFICULTY_MEDIUM` # 2

PICKPOCKET_DIFFICULTY_EASY = 1
PICKPOCKET_DIFFICULTY_HARD = 3
PICKPOCKET_DIFFICULTY_INVALID = 0
PICKPOCKET_DIFFICULTY_MEDIUM = 2
