--- @meta PlanarWaterReflectionQuality

--- @alias PlanarWaterReflectionQuality integer
--- | `PLANAR_WATER_REFLECTION_QUALITY_HIGH` # 3
--- | `PLANAR_WATER_REFLECTION_QUALITY_LOW_DEPRECATED` # 1
--- | `PLANAR_WATER_REFLECTION_QUALITY_MEDIUM` # 2
--- | `PLANAR_WATER_REFLECTION_QUALITY_OFF` # 0
--- | `PLANAR_WATER_REFLECTION_QUALITY_SCORPIO` # 4

PLANAR_WATER_REFLECTION_QUALITY_HIGH = 3
PLANAR_WATER_REFLECTION_QUALITY_LOW_DEPRECATED = 1
PLANAR_WATER_REFLECTION_QUALITY_MEDIUM = 2
PLANAR_WATER_REFLECTION_QUALITY_OFF = 0
PLANAR_WATER_REFLECTION_QUALITY_SCORPIO = 4
