--- @meta PlatformStoreLabel

--- @alias PlatformStoreLabel integer
--- | `PLATFORM_STORE_LABEL_DMM` # 3
--- | `PLATFORM_STORE_LABEL_EPIC` # 6
--- | `PLATFORM_STORE_LABEL_PSN` # 1
--- | `PLATFORM_STORE_LABEL_REUSE_ME` # 5
--- | `PLATFORM_STORE_LABEL_STEAM` # 4
--- | `PLATFORM_STORE_LABEL_XBL` # 2
--- | `PLATFORM_STORE_LABEL_ZOS` # 0

PLATFORM_STORE_LABEL_DMM = 3
PLATFORM_STORE_LABEL_EPIC = 6
PLATFORM_STORE_LABEL_PSN = 1
PLATFORM_STORE_LABEL_REUSE_ME = 5
PLATFORM_STORE_LABEL_STEAM = 4
PLATFORM_STORE_LABEL_XBL = 2
PLATFORM_STORE_LABEL_ZOS = 0
