--- @meta PlatformServiceType

--- @alias PlatformServiceType integer
--- | `PLATFORM_SERVICE_TYPE_DMM` # 3
--- | `PLATFORM_SERVICE_TYPE_EPIC` # 6
--- | `PLATFORM_SERVICE_TYPE_PSN` # 1
--- | `PLATFORM_SERVICE_TYPE_STEAM` # 4
--- | `PLATFORM_SERVICE_TYPE_XBL` # 2
--- | `PLATFORM_SERVICE_TYPE_ZOS` # 0

PLATFORM_SERVICE_TYPE_DMM = 3
PLATFORM_SERVICE_TYPE_EPIC = 6
PLATFORM_SERVICE_TYPE_PSN = 1
PLATFORM_SERVICE_TYPE_STEAM = 4
PLATFORM_SERVICE_TYPE_XBL = 2
PLATFORM_SERVICE_TYPE_ZOS = 0
