--- @meta PlayerStatus

--- @alias PlayerStatus integer
--- | `PLAYER_STATUS_AWAY` # 2
--- | `PLAYER_STATUS_DO_NOT_DISTURB` # 3
--- | `PLAYER_STATUS_OFFLINE` # 4
--- | `PLAYER_STATUS_ONLINE` # 1

PLAYER_STATUS_AWAY = 2
PLAYER_STATUS_DO_NOT_DISTURB = 3
PLAYER_STATUS_OFFLINE = 4
PLAYER_STATUS_ONLINE = 1
