--- @meta PlayerFxWhileHarvestingType

--- @alias PlayerFxWhileHarvestingType integer
--- | `PLAYER_FX_WHILE_HARVESTING_TYPE_CHOPPING_WOOD` # 2
--- | `PLAYER_FX_WHILE_HARVESTING_TYPE_GATHERING_LEATHER` # 6
--- | `PLAYER_FX_WHILE_HARVESTING_TYPE_GATHERING_RUNE` # 5
--- | `PLAYER_FX_WHILE_HARVESTING_TYPE_GATHERING_WATER` # 4
--- | `PLAYER_FX_WHILE_HARVESTING_TYPE_LOOTING_HERBALIST_SATCHEL` # 7
--- | `PLAYER_FX_WHILE_HARVESTING_TYPE_MINING_ORE` # 3
--- | `PLAYER_FX_WHILE_HARVESTING_TYPE_NONE` # 0
--- | `PLAYER_FX_WHILE_HARVESTING_TYPE_PICKING_FLORA` # 1
--- | `PLAYER_FX_WHILE_HARVESTING_TYPE_TEMP_VALUE_1` # 8
--- | `PLAYER_FX_WHILE_HARVESTING_TYPE_TEMP_VALUE_2` # 9
--- | `PLAYER_FX_WHILE_HARVESTING_TYPE_TEMP_VALUE_3` # 10

PLAYER_FX_WHILE_HARVESTING_TYPE_CHOPPING_WOOD = 2
PLAYER_FX_WHILE_HARVESTING_TYPE_GATHERING_LEATHER = 6
PLAYER_FX_WHILE_HARVESTING_TYPE_GATHERING_RUNE = 5
PLAYER_FX_WHILE_HARVESTING_TYPE_GATHERING_WATER = 4
PLAYER_FX_WHILE_HARVESTING_TYPE_LOOTING_HERBALIST_SATCHEL = 7
PLAYER_FX_WHILE_HARVESTING_TYPE_MINING_ORE = 3
PLAYER_FX_WHILE_HARVESTING_TYPE_NONE = 0
PLAYER_FX_WHILE_HARVESTING_TYPE_PICKING_FLORA = 1
PLAYER_FX_WHILE_HARVESTING_TYPE_TEMP_VALUE_1 = 8
PLAYER_FX_WHILE_HARVESTING_TYPE_TEMP_VALUE_2 = 9
PLAYER_FX_WHILE_HARVESTING_TYPE_TEMP_VALUE_3 = 10
