--- @meta PlayerEmotePlayFailure

--- @alias PlayerEmotePlayFailure integer
--- | `PLAYER_EMOTE_PLAY_FAILURE_BLACKLISTED` # 2
--- | `PLAYER_EMOTE_PLAY_FAILURE_GENERIC` # 0
--- | `PLAYER_EMOTE_PLAY_FAILURE_LOCKED` # 1

PLAYER_EMOTE_PLAY_FAILURE_BLACKLISTED = 2
PLAYER_EMOTE_PLAY_FAILURE_GENERIC = 0
PLAYER_EMOTE_PLAY_FAILURE_LOCKED = 1
