--- @meta PlayerPlatformType

--- @alias PlayerPlatformType integer
--- | `PLAYER_PLATFORM_DMM` # 5
--- | `PLAYER_PLATFORM_EPIC` # 6
--- | `PLAYER_PLATFORM_PC` # 0
--- | `PLAYER_PLATFORM_PLAYSTATION` # 2
--- | `PLAYER_PLATFORM_STEAM` # 3
--- | `PLAYER_PLATFORM_XBOX` # 1

PLAYER_PLATFORM_DMM = 5
PLAYER_PLATFORM_EPIC = 6
PLAYER_PLATFORM_PC = 0
PLAYER_PLATFORM_PLAYSTATION = 2
PLAYER_PLATFORM_STEAM = 3
PLAYER_PLATFORM_XBOX = 1
