--- @meta PledgeOfMaraResult

--- @alias PledgeOfMaraResult integer
--- | `PLEDGE_OF_MARA_RESULT_BEGIN_PLEDGE` # 2
--- | `PLEDGE_OF_MARA_RESULT_DEAD` # 1
--- | `PLEDGE_OF_MARA_RESULT_OUT_OF_RANGE` # 7
--- | `PLEDGE_OF_MARA_RESULT_PLEDGED` # 3
--- | `PLEDGE_OF_MARA_RESULT_PLEDGE_CANCELLED` # 5
--- | `PLEDGE_OF_MARA_RESULT_PLEDGE_DECLINED` # 4
--- | `PLEDGE_OF_MARA_RESULT_PLEDGE_INELIGIBLE` # 6
--- | `PLEDGE_OF_MARA_RESULT_TOO_BUSY` # 0

PLEDGE_OF_MARA_RESULT_BEGIN_PLEDGE = 2
PLEDGE_OF_MARA_RESULT_DEAD = 1
PLEDGE_OF_MARA_RESULT_OUT_OF_RANGE = 7
PLEDGE_OF_MARA_RESULT_PLEDGED = 3
PLEDGE_OF_MARA_RESULT_PLEDGE_CANCELLED = 5
PLEDGE_OF_MARA_RESULT_PLEDGE_DECLINED = 4
PLEDGE_OF_MARA_RESULT_PLEDGE_INELIGIBLE = 6
PLEDGE_OF_MARA_RESULT_TOO_BUSY = 0
