--- @meta PointOfInterestType

--- @alias PointOfInterestType integer
--- | `POI_TYPE_ACHIEVEMENT` # 3
--- | `POI_TYPE_ACHIEVEMENT_COMPONENT` # 4
--- | `POI_TYPE_GROUP_DUNGEON` # 6
--- | `POI_TYPE_HOUSE` # 7
--- | `POI_TYPE_OBJECTIVE` # 0
--- | `POI_TYPE_PUBLIC_DUNGEON` # 5
--- | `POI_TYPE_STANDARD` # 2
--- | `POI_TYPE_WAYSHRINE` # 1

POI_TYPE_ACHIEVEMENT = 3
POI_TYPE_ACHIEVEMENT_COMPONENT = 4
POI_TYPE_GROUP_DUNGEON = 6
POI_TYPE_HOUSE = 7
POI_TYPE_OBJECTIVE = 0
POI_TYPE_PUBLIC_DUNGEON = 5
POI_TYPE_STANDARD = 2
POI_TYPE_WAYSHRINE = 1
