--- @meta PolygonPointLayout

--- @alias PolygonPointLayout integer
--- | `POLYGON_POINT_LAYOUT_CLOCKWISE` # 0
--- | `POLYGON_POINT_LAYOUT_COUNTER_CLOCKWISE` # 1

POLYGON_POINT_LAYOUT_CLOCKWISE = 0
POLYGON_POINT_LAYOUT_COUNTER_CLOCKWISE = 1
