--- @meta PreferredInputDeviceType

--- @alias PreferredInputDeviceType integer
--- | `PREFERRED_INPUT_DEVICE_TYPE_GAMEPAD` # 2
--- | `PREFERRED_INPUT_DEVICE_TYPE_KEYBOARD` # 0
--- | `PREFERRED_INPUT_DEVICE_TYPE_KEYBOARD_OR_MOUSE` # 3
--- | `PREFERRED_INPUT_DEVICE_TYPE_MOUSE` # 1

PREFERRED_INPUT_DEVICE_TYPE_GAMEPAD = 2
PREFERRED_INPUT_DEVICE_TYPE_KEYBOARD = 0
PREFERRED_INPUT_DEVICE_TYPE_KEYBOARD_OR_MOUSE = 3
PREFERRED_INPUT_DEVICE_TYPE_MOUSE = 1
