--- @meta PrimaryPlayerNameSetting

--- @alias PrimaryPlayerNameSetting integer
--- | `PRIMARY_PLAYER_NAME_SETTING_PREFER_CHARACTER` # 1
--- | `PRIMARY_PLAYER_NAME_SETTING_PREFER_USERID` # 0

PRIMARY_PLAYER_NAME_SETTING_PREFER_CHARACTER = 1
PRIMARY_PLAYER_NAME_SETTING_PREFER_USERID = 0
