--- @meta ProgressionColors

--- @alias ProgressionColors integer
--- | `PROGRESSION_COLOR_AVA_RANK_END` # 14
--- | `PROGRESSION_COLOR_AVA_RANK_START` # 13
--- | `PROGRESSION_COLOR_CP_HEALTH_END` # 21
--- | `PROGRESSION_COLOR_CP_HEALTH_START` # 20
--- | `PROGRESSION_COLOR_CP_MAGICKA_END` # 23
--- | `PROGRESSION_COLOR_CP_MAGICKA_START` # 22
--- | `PROGRESSION_COLOR_CP_STAMINA_END` # 25
--- | `PROGRESSION_COLOR_CP_STAMINA_START` # 24
--- | `PROGRESSION_COLOR_EARNED` # 0
--- | `PROGRESSION_COLOR_LOCKED` # 12
--- | `PROGRESSION_COLOR_PURCHASED` # 10
--- | `PROGRESSION_COLOR_PURCHASED_UNSELECTED` # 26
--- | `PROGRESSION_COLOR_SKILL_XP_END` # 9
--- | `PROGRESSION_COLOR_SKILL_XP_GLOW` # 19
--- | `PROGRESSION_COLOR_SKILL_XP_START` # 8
--- | `PROGRESSION_COLOR_UNEARNED` # 1
--- | `PROGRESSION_COLOR_UNPURCHASED` # 11
--- | `PROGRESSION_COLOR_VP_END` # 16
--- | `PROGRESSION_COLOR_VP_GLOW` # 18
--- | `PROGRESSION_COLOR_VP_START` # 15
--- | `PROGRESSION_COLOR_XP_END` # 3
--- | `PROGRESSION_COLOR_XP_FULL_END` # 5
--- | `PROGRESSION_COLOR_XP_FULL_START` # 4
--- | `PROGRESSION_COLOR_XP_GLOW` # 17
--- | `PROGRESSION_COLOR_XP_MORPH_END` # 7
--- | `PROGRESSION_COLOR_XP_MORPH_START` # 6
--- | `PROGRESSION_COLOR_XP_START` # 2

PROGRESSION_COLOR_AVA_RANK_END = 14
PROGRESSION_COLOR_AVA_RANK_START = 13
PROGRESSION_COLOR_CP_HEALTH_END = 21
PROGRESSION_COLOR_CP_HEALTH_START = 20
PROGRESSION_COLOR_CP_MAGICKA_END = 23
PROGRESSION_COLOR_CP_MAGICKA_START = 22
PROGRESSION_COLOR_CP_STAMINA_END = 25
PROGRESSION_COLOR_CP_STAMINA_START = 24
PROGRESSION_COLOR_EARNED = 0
PROGRESSION_COLOR_LOCKED = 12
PROGRESSION_COLOR_PURCHASED = 10
PROGRESSION_COLOR_PURCHASED_UNSELECTED = 26
PROGRESSION_COLOR_SKILL_XP_END = 9
PROGRESSION_COLOR_SKILL_XP_GLOW = 19
PROGRESSION_COLOR_SKILL_XP_START = 8
PROGRESSION_COLOR_UNEARNED = 1
PROGRESSION_COLOR_UNPURCHASED = 11
PROGRESSION_COLOR_VP_END = 16
PROGRESSION_COLOR_VP_GLOW = 18
PROGRESSION_COLOR_VP_START = 15
PROGRESSION_COLOR_XP_END = 3
PROGRESSION_COLOR_XP_FULL_END = 5
PROGRESSION_COLOR_XP_FULL_START = 4
PROGRESSION_COLOR_XP_GLOW = 17
PROGRESSION_COLOR_XP_MORPH_END = 7
PROGRESSION_COLOR_XP_MORPH_START = 6
PROGRESSION_COLOR_XP_START = 2
