--- @meta ProgressReason

--- @alias ProgressReason integer
--- | `PROGRESS_REASON_ACHIEVEMENT` # 25
--- | `PROGRESS_REASON_ACTION` # 13
--- | `PROGRESS_REASON_ALLIANCE_POINTS` # 33
--- | `PROGRESS_REASON_ANTIQUITY_COMPLETED_DIGGING` # 42
--- | `PROGRESS_REASON_ANTIQUITY_COMPLETED_SCRYING` # 41
--- | `PROGRESS_REASON_AVA` # 15
--- | `PROGRESS_REASON_BATTLEGROUND` # 6
--- | `PROGRESS_REASON_BOOK_COLLECTION_COMPLETE` # 12
--- | `PROGRESS_REASON_BOSS_KILL` # 26
--- | `PROGRESS_REASON_COLLECT_BOOK` # 11
--- | `PROGRESS_REASON_COMMAND` # 4
--- | `PROGRESS_REASON_COMPLETE_POI` # 2
--- | `PROGRESS_REASON_DARK_ANCHOR_CLOSED` # 28
--- | `PROGRESS_REASON_DARK_FISSURE_CLOSED` # 29
--- | `PROGRESS_REASON_DISCOVER_POI` # 3
--- | `PROGRESS_REASON_DRAGON_KILL` # 39
--- | `PROGRESS_REASON_DUNGEON_CHALLENGE` # 35
--- | `PROGRESS_REASON_EVENT` # 27
--- | `PROGRESS_REASON_FINESSE` # 9
--- | `PROGRESS_REASON_FISSURE_COMPLETED` # 45
--- | `PROGRESS_REASON_GEYSER_COMPLETED` # 44
--- | `PROGRESS_REASON_GRANT_REPUTATION` # 32
--- | `PROGRESS_REASON_GUILD_REP` # 14
--- | `PROGRESS_REASON_HARROWSTORM_COMPLETED` # 40
--- | `PROGRESS_REASON_JUSTICE_SKILL_EVENT` # 36
--- | `PROGRESS_REASON_KEEP_REWARD` # 5
--- | `PROGRESS_REASON_KILL` # 0
--- | `PROGRESS_REASON_LFG_REWARD` # 37
--- | `PROGRESS_REASON_LOCK_PICK` # 10
--- | `PROGRESS_REASON_MEDAL` # 8
--- | `PROGRESS_REASON_MIRRORMOOR_COMPLETED` # 48
--- | `PROGRESS_REASON_NONE` # -1
--- | `PROGRESS_REASON_OBLIVION_PORTAL_COMPLETED` # 43
--- | `PROGRESS_REASON_OTHER` # 31
--- | `PROGRESS_REASON_OVERLAND_BOSS_KILL` # 24
--- | `PROGRESS_REASON_PVP_EMPEROR` # 34
--- | `PROGRESS_REASON_QUEST` # 1
--- | `PROGRESS_REASON_REWARD` # 17
--- | `PROGRESS_REASON_SCRIPTED_EVENT` # 7
--- | `PROGRESS_REASON_SKILL_BOOK` # 30
--- | `PROGRESS_REASON_TRADESKILL` # 16
--- | `PROGRESS_REASON_TRADESKILL_ACHIEVEMENT` # 18
--- | `PROGRESS_REASON_TRADESKILL_CONSUME` # 20
--- | `PROGRESS_REASON_TRADESKILL_HARVEST` # 21
--- | `PROGRESS_REASON_TRADESKILL_QUEST` # 19
--- | `PROGRESS_REASON_TRADESKILL_RECIPE` # 22
--- | `PROGRESS_REASON_TRADESKILL_TRAIT` # 23
--- | `PROGRESS_REASON_TRIBUTE_CAMPAIGN` # 47
--- | `PROGRESS_REASON_TRIBUTE_CLUB` # 46
--- | `PROGRESS_REASON_WORLD_EVENT_COMPLETED` # 38

PROGRESS_REASON_ACHIEVEMENT = 25
PROGRESS_REASON_ACTION = 13
PROGRESS_REASON_ALLIANCE_POINTS = 33
PROGRESS_REASON_ANTIQUITY_COMPLETED_DIGGING = 42
PROGRESS_REASON_ANTIQUITY_COMPLETED_SCRYING = 41
PROGRESS_REASON_AVA = 15
PROGRESS_REASON_BATTLEGROUND = 6
PROGRESS_REASON_BOOK_COLLECTION_COMPLETE = 12
PROGRESS_REASON_BOSS_KILL = 26
PROGRESS_REASON_COLLECT_BOOK = 11
PROGRESS_REASON_COMMAND = 4
PROGRESS_REASON_COMPLETE_POI = 2
PROGRESS_REASON_DARK_ANCHOR_CLOSED = 28
PROGRESS_REASON_DARK_FISSURE_CLOSED = 29
PROGRESS_REASON_DISCOVER_POI = 3
PROGRESS_REASON_DRAGON_KILL = 39
PROGRESS_REASON_DUNGEON_CHALLENGE = 35
PROGRESS_REASON_EVENT = 27
PROGRESS_REASON_FINESSE = 9
PROGRESS_REASON_FISSURE_COMPLETED = 45
PROGRESS_REASON_GEYSER_COMPLETED = 44
PROGRESS_REASON_GRANT_REPUTATION = 32
PROGRESS_REASON_GUILD_REP = 14
PROGRESS_REASON_HARROWSTORM_COMPLETED = 40
PROGRESS_REASON_JUSTICE_SKILL_EVENT = 36
PROGRESS_REASON_KEEP_REWARD = 5
PROGRESS_REASON_KILL = 0
PROGRESS_REASON_LFG_REWARD = 37
PROGRESS_REASON_LOCK_PICK = 10
PROGRESS_REASON_MEDAL = 8
PROGRESS_REASON_MIRRORMOOR_COMPLETED = 48
PROGRESS_REASON_NONE = -1
PROGRESS_REASON_OBLIVION_PORTAL_COMPLETED = 43
PROGRESS_REASON_OTHER = 31
PROGRESS_REASON_OVERLAND_BOSS_KILL = 24
PROGRESS_REASON_PVP_EMPEROR = 34
PROGRESS_REASON_QUEST = 1
PROGRESS_REASON_REWARD = 17
PROGRESS_REASON_SCRIPTED_EVENT = 7
PROGRESS_REASON_SKILL_BOOK = 30
PROGRESS_REASON_TRADESKILL = 16
PROGRESS_REASON_TRADESKILL_ACHIEVEMENT = 18
PROGRESS_REASON_TRADESKILL_CONSUME = 20
PROGRESS_REASON_TRADESKILL_HARVEST = 21
PROGRESS_REASON_TRADESKILL_QUEST = 19
PROGRESS_REASON_TRADESKILL_RECIPE = 22
PROGRESS_REASON_TRADESKILL_TRAIT = 23
PROGRESS_REASON_TRIBUTE_CAMPAIGN = 47
PROGRESS_REASON_TRIBUTE_CLUB = 46
PROGRESS_REASON_WORLD_EVENT_COMPLETED = 38
