--- @meta ProspectiveAlchemyResult

--- @alias ProspectiveAlchemyResult integer
--- | `PROSPECTIVE_ALCHEMY_RESULT_KNOWN` # 2
--- | `PROSPECTIVE_ALCHEMY_RESULT_UNCRAFTABLE` # 0
--- | `PROSPECTIVE_ALCHEMY_RESULT_UNKNOWN` # 1

PROSPECTIVE_ALCHEMY_RESULT_KNOWN = 2
PROSPECTIVE_ALCHEMY_RESULT_UNCRAFTABLE = 0
PROSPECTIVE_ALCHEMY_RESULT_UNKNOWN = 1
