--- @meta ProspectivePickpocketResult

--- @alias ProspectivePickpocketResult integer
--- | `PROSPECTIVE_PICKPOCKET_RESULT_CAN_ATTEMPT` # 0
--- | `PROSPECTIVE_PICKPOCKET_RESULT_COOLDOWN` # 1
--- | `PROSPECTIVE_PICKPOCKET_RESULT_INVENTORY_FULL` # 4
--- | `PROSPECTIVE_PICKPOCKET_RESULT_OUT_OF_POSITION` # 3
--- | `PROSPECTIVE_PICKPOCKET_RESULT_OUT_OF_RANGE` # 2

PROSPECTIVE_PICKPOCKET_RESULT_CAN_ATTEMPT = 0
PROSPECTIVE_PICKPOCKET_RESULT_COOLDOWN = 1
PROSPECTIVE_PICKPOCKET_RESULT_INVENTORY_FULL = 4
PROSPECTIVE_PICKPOCKET_RESULT_OUT_OF_POSITION = 3
PROSPECTIVE_PICKPOCKET_RESULT_OUT_OF_RANGE = 2
