--- @meta ProvisionerSpecialIngredientType

--- @alias ProvisionerSpecialIngredientType integer
--- | `PROVISIONER_SPECIAL_INGREDIENT_TYPE_FILLET` # 4
--- | `PROVISIONER_SPECIAL_INGREDIENT_TYPE_FLAVORING` # 2
--- | `PROVISIONER_SPECIAL_INGREDIENT_TYPE_FURNISHING` # 3
--- | `PROVISIONER_SPECIAL_INGREDIENT_TYPE_NONE` # 0
--- | `PROVISIONER_SPECIAL_INGREDIENT_TYPE_SPICES` # 1

PROVISIONER_SPECIAL_INGREDIENT_TYPE_FILLET = 4
PROVISIONER_SPECIAL_INGREDIENT_TYPE_FLAVORING = 2
PROVISIONER_SPECIAL_INGREDIENT_TYPE_FURNISHING = 3
PROVISIONER_SPECIAL_INGREDIENT_TYPE_NONE = 0
PROVISIONER_SPECIAL_INGREDIENT_TYPE_SPICES = 1
