--- @meta QuestConditionType

--- @alias QuestConditionType integer
--- | `QUEST_CONDITION_TYPE_ABILITY_TYPE_USED_ON_NPC` # 19
--- | `QUEST_CONDITION_TYPE_ABILITY_TYPE_USED_ON_TABLE` # 23
--- | `QUEST_CONDITION_TYPE_ABILITY_USED_ON_NPC` # 18
--- | `QUEST_CONDITION_TYPE_ABILITY_USED_ON_TABLE` # 22
--- | `QUEST_CONDITION_TYPE_ADVANCE_COMPLETABLE_SIBLINGS` # 45
--- | `QUEST_CONDITION_TYPE_ARTIFACT_CAPTURED` # 40
--- | `QUEST_CONDITION_TYPE_ARTIFACT_RETURNED` # 41
--- | `QUEST_CONDITION_TYPE_BATTLEGROUND_EARNED_POINTS` # 52
--- | `QUEST_CONDITION_TYPE_BATTLEGROUND_PARTICIPATION` # 50
--- | `QUEST_CONDITION_TYPE_BATTLEGROUND_VICTORY` # 51
--- | `QUEST_CONDITION_TYPE_CAPTURE_KEEP_TYPE_UNIQUE_KEEPS` # 54
--- | `QUEST_CONDITION_TYPE_CAPTURE_KEEP_TYPE` # 28
--- | `QUEST_CONDITION_TYPE_CAPTURE_SPECIFIC_KEEP` # 29
--- | `QUEST_CONDITION_TYPE_COLLECT_ITEM` # 6
--- | `QUEST_CONDITION_TYPE_CRAFT_ITEM` # 31
--- | `QUEST_CONDITION_TYPE_CRAFT_RANDOM_WRIT_ITEM` # 48
--- | `QUEST_CONDITION_TYPE_DECONSTRUCT_ITEM` # 25
--- | `QUEST_CONDITION_TYPE_DEPRECATED_0` # 59
--- | `QUEST_CONDITION_TYPE_DISMISSED_COMPANION` # 56
--- | `QUEST_CONDITION_TYPE_EARN_CHAMPION_POINT` # 58
--- | `QUEST_CONDITION_TYPE_ENTER_SUBZONE` # 20
--- | `QUEST_CONDITION_TYPE_ENTER_ZONE` # 64
--- | `QUEST_CONDITION_TYPE_EQUIP_ITEM` # 33
--- | `QUEST_CONDITION_TYPE_EVENT_FAIL` # 36
--- | `QUEST_CONDITION_TYPE_EVENT_SUCCESS` # 35
--- | `QUEST_CONDITION_TYPE_EXIT_SUBZONE` # 21
--- | `QUEST_CONDITION_TYPE_FOLLOWER_GAINED` # 37
--- | `QUEST_CONDITION_TYPE_FOLLOWER_LOST` # 13
--- | `QUEST_CONDITION_TYPE_GATHER_ITEM_TRAIT` # 53
--- | `QUEST_CONDITION_TYPE_GATHER_ITEM_TYPE` # 49
--- | `QUEST_CONDITION_TYPE_GATHER_ITEM` # 44
--- | `QUEST_CONDITION_TYPE_GIVE_ITEM` # 7
--- | `QUEST_CONDITION_TYPE_GOTO_POINT` # 5
--- | `QUEST_CONDITION_TYPE_GUILD_TRADER_GOLD_TRANSACTION` # 63
--- | `QUEST_CONDITION_TYPE_HAS_ITEM` # 30
--- | `QUEST_CONDITION_TYPE_INTERACT_MONSTER` # 2
--- | `QUEST_CONDITION_TYPE_INTERACT_OBJECT_IN_STATE` # 14
--- | `QUEST_CONDITION_TYPE_INTERACT_OBJECT` # 8
--- | `QUEST_CONDITION_TYPE_INTERACT_SIMPLE_OBJECT_IN_STATE` # 39
--- | `QUEST_CONDITION_TYPE_INTERACT_SIMPLE_OBJECT` # 38
--- | `QUEST_CONDITION_TYPE_ITERATION_BEGIN` # 1
--- | `QUEST_CONDITION_TYPE_ITERATION_END` # 71
--- | `QUEST_CONDITION_TYPE_KILL_BOUNTY_CLASSIFICATION_TYPE` # 47
--- | `QUEST_CONDITION_TYPE_KILL_ENEMY_GUARDS` # 27
--- | `QUEST_CONDITION_TYPE_KILL_ENEMY_PLAYERS_OF_CLASS` # 42
--- | `QUEST_CONDITION_TYPE_KILL_ENEMY_PLAYERS_WHILE_DEFENDING_KEEP` # 43
--- | `QUEST_CONDITION_TYPE_KILL_ENEMY_PLAYERS` # 26
--- | `QUEST_CONDITION_TYPE_KILL_MONSTER_TABLE` # 24
--- | `QUEST_CONDITION_TYPE_KILL_MONSTER_TYPE` # 70
--- | `QUEST_CONDITION_TYPE_KILL_MONSTER` # 1
--- | `QUEST_CONDITION_TYPE_LEAVE_REVIVE_COUNTER_LIST` # 34
--- | `QUEST_CONDITION_TYPE_LEVEL_UP` # 57
--- | `QUEST_CONDITION_TYPE_LOOT_TREASURE_CHEST` # 61
--- | `QUEST_CONDITION_TYPE_MAX_VALUE` # 71
--- | `QUEST_CONDITION_TYPE_MIN_VALUE` # 1
--- | `QUEST_CONDITION_TYPE_NPC_GOAL_FAIL` # 12
--- | `QUEST_CONDITION_TYPE_NPC_GOAL` # 10
--- | `QUEST_CONDITION_TYPE_PICKPOCKET_ITEM` # 32
--- | `QUEST_CONDITION_TYPE_PLAYER_DEATH` # 3
--- | `QUEST_CONDITION_TYPE_PLAYER_LOGOUT` # 16
--- | `QUEST_CONDITION_TYPE_READ_BOOK` # 69
--- | `QUEST_CONDITION_TYPE_SCRIBE_ABILITY` # 71
--- | `QUEST_CONDITION_TYPE_SCRIPT_ACTION` # 17
--- | `QUEST_CONDITION_TYPE_SELL_LAUNDER_ITEM` # 46
--- | `QUEST_CONDITION_TYPE_SUMMONED_COMPANION` # 55
--- | `QUEST_CONDITION_TYPE_TALK_TO` # 9
--- | `QUEST_CONDITION_TYPE_TIMER` # 4
--- | `QUEST_CONDITION_TYPE_TRANSITION_INTERACT_OBJECT` # 15
--- | `QUEST_CONDITION_TYPE_TRIBUTE_LOST_MATCH_MONSTER` # 66
--- | `QUEST_CONDITION_TYPE_TRIBUTE_LOST_MATCH_PLAYER` # 68
--- | `QUEST_CONDITION_TYPE_TRIBUTE_WON_MATCH_MONSTER` # 65
--- | `QUEST_CONDITION_TYPE_TRIBUTE_WON_MATCH_PLAYER` # 67
--- | `QUEST_CONDITION_TYPE_UNEARTH_ANTIQUITY` # 60
--- | `QUEST_CONDITION_TYPE_USE_QUEST_ITEM` # 11
--- | `QUEST_CONDITION_TYPE_VENDOR_GOLD_TRANSACTION` # 62

QUEST_CONDITION_TYPE_ABILITY_TYPE_USED_ON_NPC = 19
QUEST_CONDITION_TYPE_ABILITY_TYPE_USED_ON_TABLE = 23
QUEST_CONDITION_TYPE_ABILITY_USED_ON_NPC = 18
QUEST_CONDITION_TYPE_ABILITY_USED_ON_TABLE = 22
QUEST_CONDITION_TYPE_ADVANCE_COMPLETABLE_SIBLINGS = 45
QUEST_CONDITION_TYPE_ARTIFACT_CAPTURED = 40
QUEST_CONDITION_TYPE_ARTIFACT_RETURNED = 41
QUEST_CONDITION_TYPE_BATTLEGROUND_EARNED_POINTS = 52
QUEST_CONDITION_TYPE_BATTLEGROUND_PARTICIPATION = 50
QUEST_CONDITION_TYPE_BATTLEGROUND_VICTORY = 51
QUEST_CONDITION_TYPE_CAPTURE_KEEP_TYPE_UNIQUE_KEEPS = 54
QUEST_CONDITION_TYPE_CAPTURE_KEEP_TYPE = 28
QUEST_CONDITION_TYPE_CAPTURE_SPECIFIC_KEEP = 29
QUEST_CONDITION_TYPE_COLLECT_ITEM = 6
QUEST_CONDITION_TYPE_CRAFT_ITEM = 31
QUEST_CONDITION_TYPE_CRAFT_RANDOM_WRIT_ITEM = 48
QUEST_CONDITION_TYPE_DECONSTRUCT_ITEM = 25
QUEST_CONDITION_TYPE_DEPRECATED_0 = 59
QUEST_CONDITION_TYPE_DISMISSED_COMPANION = 56
QUEST_CONDITION_TYPE_EARN_CHAMPION_POINT = 58
QUEST_CONDITION_TYPE_ENTER_SUBZONE = 20
QUEST_CONDITION_TYPE_ENTER_ZONE = 64
QUEST_CONDITION_TYPE_EQUIP_ITEM = 33
QUEST_CONDITION_TYPE_EVENT_FAIL = 36
QUEST_CONDITION_TYPE_EVENT_SUCCESS = 35
QUEST_CONDITION_TYPE_EXIT_SUBZONE = 21
QUEST_CONDITION_TYPE_FOLLOWER_GAINED = 37
QUEST_CONDITION_TYPE_FOLLOWER_LOST = 13
QUEST_CONDITION_TYPE_GATHER_ITEM_TRAIT = 53
QUEST_CONDITION_TYPE_GATHER_ITEM_TYPE = 49
QUEST_CONDITION_TYPE_GATHER_ITEM = 44
QUEST_CONDITION_TYPE_GIVE_ITEM = 7
QUEST_CONDITION_TYPE_GOTO_POINT = 5
QUEST_CONDITION_TYPE_GUILD_TRADER_GOLD_TRANSACTION = 63
QUEST_CONDITION_TYPE_HAS_ITEM = 30
QUEST_CONDITION_TYPE_INTERACT_MONSTER = 2
QUEST_CONDITION_TYPE_INTERACT_OBJECT_IN_STATE = 14
QUEST_CONDITION_TYPE_INTERACT_OBJECT = 8
QUEST_CONDITION_TYPE_INTERACT_SIMPLE_OBJECT_IN_STATE = 39
QUEST_CONDITION_TYPE_INTERACT_SIMPLE_OBJECT = 38
QUEST_CONDITION_TYPE_ITERATION_BEGIN = 1
QUEST_CONDITION_TYPE_ITERATION_END = 71
QUEST_CONDITION_TYPE_KILL_BOUNTY_CLASSIFICATION_TYPE = 47
QUEST_CONDITION_TYPE_KILL_ENEMY_GUARDS = 27
QUEST_CONDITION_TYPE_KILL_ENEMY_PLAYERS_OF_CLASS = 42
QUEST_CONDITION_TYPE_KILL_ENEMY_PLAYERS_WHILE_DEFENDING_KEEP = 43
QUEST_CONDITION_TYPE_KILL_ENEMY_PLAYERS = 26
QUEST_CONDITION_TYPE_KILL_MONSTER_TABLE = 24
QUEST_CONDITION_TYPE_KILL_MONSTER_TYPE = 70
QUEST_CONDITION_TYPE_KILL_MONSTER = 1
QUEST_CONDITION_TYPE_LEAVE_REVIVE_COUNTER_LIST = 34
QUEST_CONDITION_TYPE_LEVEL_UP = 57
QUEST_CONDITION_TYPE_LOOT_TREASURE_CHEST = 61
QUEST_CONDITION_TYPE_MAX_VALUE = 71
QUEST_CONDITION_TYPE_MIN_VALUE = 1
QUEST_CONDITION_TYPE_NPC_GOAL_FAIL = 12
QUEST_CONDITION_TYPE_NPC_GOAL = 10
QUEST_CONDITION_TYPE_PICKPOCKET_ITEM = 32
QUEST_CONDITION_TYPE_PLAYER_DEATH = 3
QUEST_CONDITION_TYPE_PLAYER_LOGOUT = 16
QUEST_CONDITION_TYPE_READ_BOOK = 69
QUEST_CONDITION_TYPE_SCRIBE_ABILITY = 71
QUEST_CONDITION_TYPE_SCRIPT_ACTION = 17
QUEST_CONDITION_TYPE_SELL_LAUNDER_ITEM = 46
QUEST_CONDITION_TYPE_SUMMONED_COMPANION = 55
QUEST_CONDITION_TYPE_TALK_TO = 9
QUEST_CONDITION_TYPE_TIMER = 4
QUEST_CONDITION_TYPE_TRANSITION_INTERACT_OBJECT = 15
QUEST_CONDITION_TYPE_TRIBUTE_LOST_MATCH_MONSTER = 66
QUEST_CONDITION_TYPE_TRIBUTE_LOST_MATCH_PLAYER = 68
QUEST_CONDITION_TYPE_TRIBUTE_WON_MATCH_MONSTER = 65
QUEST_CONDITION_TYPE_TRIBUTE_WON_MATCH_PLAYER = 67
QUEST_CONDITION_TYPE_UNEARTH_ANTIQUITY = 60
QUEST_CONDITION_TYPE_USE_QUEST_ITEM = 11
QUEST_CONDITION_TYPE_VENDOR_GOLD_TRANSACTION = 62
