--- @meta QuestShareResult

--- @alias QuestShareResult integer
--- | `QUEST_SHARE_RESULT_ACCEPTED` # 1
--- | `QUEST_SHARE_RESULT_DECLINED` # 2
--- | `QUEST_SHARE_RESULT_FAILED_TO_SHARE` # 0

QUEST_SHARE_RESULT_ACCEPTED = 1
QUEST_SHARE_RESULT_DECLINED = 2
QUEST_SHARE_RESULT_FAILED_TO_SHARE = 0
