--- @meta QuestType

--- @alias QuestType integer
--- | `QUEST_TYPE_AVA` # 7
--- | `QUEST_TYPE_AVA_GRAND` # 11
--- | `QUEST_TYPE_AVA_GROUP` # 10
--- | `QUEST_TYPE_BATTLEGROUND` # 13
--- | `QUEST_TYPE_CLASS` # 8
--- | `QUEST_TYPE_COMPANION` # 16
--- | `QUEST_TYPE_CRAFTING` # 4
--- | `QUEST_TYPE_DUNGEON` # 5
--- | `QUEST_TYPE_GROUP` # 1
--- | `QUEST_TYPE_GUILD` # 3
--- | `QUEST_TYPE_HOLIDAY_EVENT` # 12
--- | `QUEST_TYPE_MAIN_STORY` # 2
--- | `QUEST_TYPE_NONE` # 0
--- | `QUEST_TYPE_PROLOGUE` # 14
--- | `QUEST_TYPE_RAID` # 6
--- | `QUEST_TYPE_SCRIBING` # 18
--- | `QUEST_TYPE_TRIBUTE` # 17
--- | `QUEST_TYPE_UNDAUNTED_PLEDGE` # 15

QUEST_TYPE_AVA = 7
QUEST_TYPE_AVA_GRAND = 11
QUEST_TYPE_AVA_GROUP = 10
QUEST_TYPE_BATTLEGROUND = 13
QUEST_TYPE_CLASS = 8
QUEST_TYPE_COMPANION = 16
QUEST_TYPE_CRAFTING = 4
QUEST_TYPE_DUNGEON = 5
QUEST_TYPE_GROUP = 1
QUEST_TYPE_GUILD = 3
QUEST_TYPE_HOLIDAY_EVENT = 12
QUEST_TYPE_MAIN_STORY = 2
QUEST_TYPE_NONE = 0
QUEST_TYPE_PROLOGUE = 14
QUEST_TYPE_RAID = 6
QUEST_TYPE_SCRIBING = 18
QUEST_TYPE_TRIBUTE = 17
QUEST_TYPE_UNDAUNTED_PLEDGE = 15
