--- @meta QuestRepeatableType

--- @alias QuestRepeatableType integer
--- | `QUEST_REPEAT_DAILY` # 2
--- | `QUEST_REPEAT_EVENT_RESET` # 4
--- | `QUEST_REPEAT_MONTHLY` # 6
--- | `QUEST_REPEAT_NOT_REPEATABLE` # 0
--- | `QUEST_REPEAT_REPEATABLE` # 1
--- | `QUEST_REPEAT_REPEATABLE_PER_DURATION` # 3
--- | `QUEST_REPEAT_WEEKLY` # 5

QUEST_REPEAT_DAILY = 2
QUEST_REPEAT_EVENT_RESET = 4
QUEST_REPEAT_MONTHLY = 6
QUEST_REPEAT_NOT_REPEATABLE = 0
QUEST_REPEAT_REPEATABLE = 1
QUEST_REPEAT_REPEATABLE_PER_DURATION = 3
QUEST_REPEAT_WEEKLY = 5
