--- @meta QuestStepVisibility

--- @alias QuestStepVisibility integer
--- | `QUEST_STEP_VISIBILITY_HIDDEN` # 2
--- | `QUEST_STEP_VISIBILITY_HINT` # 0
--- | `QUEST_STEP_VISIBILITY_OPTIONAL` # 1

QUEST_STEP_VISIBILITY_HIDDEN = 2
QUEST_STEP_VISIBILITY_HINT = 0
QUEST_STEP_VISIBILITY_OPTIONAL = 1
