--- @meta QueueForCampaignResponseType

--- @alias QueueForCampaignResponseType integer
--- | `QUEUE_FOR_CAMPAIGN_RESULT_ALREADY_IN_CAMPAIGN` # 4
--- | `QUEUE_FOR_CAMPAIGN_RESULT_ALREADY_QUEUED` # 1
--- | `QUEUE_FOR_CAMPAIGN_RESULT_CAMPAIGNS_DISABLED` # 17
--- | `QUEUE_FOR_CAMPAIGN_RESULT_CAMPAIGN_ALLIANCE_LOCKED` # 23
--- | `QUEUE_FOR_CAMPAIGN_RESULT_CAMPAIGN_FULL` # 14
--- | `QUEUE_FOR_CAMPAIGN_RESULT_CAMPAIGN_IN_CONFLICT` # 22
--- | `QUEUE_FOR_CAMPAIGN_RESULT_CANNOT_QUEUE_FROM_BATTLEGROUND` # 20
--- | `QUEUE_FOR_CAMPAIGN_RESULT_CANNOT_QUEUE_FROM_LOCATION` # 21
--- | `QUEUE_FOR_CAMPAIGN_RESULT_DESTINATION_NOT_UP` # 16
--- | `QUEUE_FOR_CAMPAIGN_RESULT_DESTINATION_WORLD_FULL` # 12
--- | `QUEUE_FOR_CAMPAIGN_RESULT_GROUP_ALREADY_IN_CAMPAIGN` # 7
--- | `QUEUE_FOR_CAMPAIGN_RESULT_GROUP_CROSS_ALLIANCE` # 25
--- | `QUEUE_FOR_CAMPAIGN_RESULT_GROUP_MEMBER_WITH_INSUFFICIENT_LEVEL` # 19
--- | `QUEUE_FOR_CAMPAIGN_RESULT_GROUP_NOT_ASSIGNED_TO_CAMPAIGN` # 6
--- | `QUEUE_FOR_CAMPAIGN_RESULT_GROUP_TOO_LARGE` # 29
--- | `QUEUE_FOR_CAMPAIGN_RESULT_IMPERIAL_CITY_NOT_CONTROLLED` # 15
--- | `QUEUE_FOR_CAMPAIGN_RESULT_INSUFFICIENT_LEVEL` # 18
--- | `QUEUE_FOR_CAMPAIGN_RESULT_INTERNAL_ERROR` # 3
--- | `QUEUE_FOR_CAMPAIGN_RESULT_INVALID_CAMPAIGN` # 8
--- | `QUEUE_FOR_CAMPAIGN_RESULT_INVALID_GROUP` # 5
--- | `QUEUE_FOR_CAMPAIGN_RESULT_INVALID_LOGIN_STATE` # 10
--- | `QUEUE_FOR_CAMPAIGN_RESULT_INVALID_WORLD` # 11
--- | `QUEUE_FOR_CAMPAIGN_RESULT_IN_LFG_GROUP` # 24
--- | `QUEUE_FOR_CAMPAIGN_RESULT_IS_DEAD` # 27
--- | `QUEUE_FOR_CAMPAIGN_RESULT_LOGIN_WOULD_LOCK` # 28
--- | `QUEUE_FOR_CAMPAIGN_RESULT_NOT_GROUP_LEADER` # 9
--- | `QUEUE_FOR_CAMPAIGN_RESULT_NOT_ONLINE` # 13
--- | `QUEUE_FOR_CAMPAIGN_RESULT_NO_PERMISSION` # 2
--- | `QUEUE_FOR_CAMPAIGN_RESULT_REQUIREMENT_NOT_MET` # 26
--- | `QUEUE_FOR_CAMPAIGN_RESULT_SUCCESS` # 0

QUEUE_FOR_CAMPAIGN_RESULT_ALREADY_IN_CAMPAIGN = 4
QUEUE_FOR_CAMPAIGN_RESULT_ALREADY_QUEUED = 1
QUEUE_FOR_CAMPAIGN_RESULT_CAMPAIGNS_DISABLED = 17
QUEUE_FOR_CAMPAIGN_RESULT_CAMPAIGN_ALLIANCE_LOCKED = 23
QUEUE_FOR_CAMPAIGN_RESULT_CAMPAIGN_FULL = 14
QUEUE_FOR_CAMPAIGN_RESULT_CAMPAIGN_IN_CONFLICT = 22
QUEUE_FOR_CAMPAIGN_RESULT_CANNOT_QUEUE_FROM_BATTLEGROUND = 20
QUEUE_FOR_CAMPAIGN_RESULT_CANNOT_QUEUE_FROM_LOCATION = 21
QUEUE_FOR_CAMPAIGN_RESULT_DESTINATION_NOT_UP = 16
QUEUE_FOR_CAMPAIGN_RESULT_DESTINATION_WORLD_FULL = 12
QUEUE_FOR_CAMPAIGN_RESULT_GROUP_ALREADY_IN_CAMPAIGN = 7
QUEUE_FOR_CAMPAIGN_RESULT_GROUP_CROSS_ALLIANCE = 25
QUEUE_FOR_CAMPAIGN_RESULT_GROUP_MEMBER_WITH_INSUFFICIENT_LEVEL = 19
QUEUE_FOR_CAMPAIGN_RESULT_GROUP_NOT_ASSIGNED_TO_CAMPAIGN = 6
QUEUE_FOR_CAMPAIGN_RESULT_GROUP_TOO_LARGE = 29
QUEUE_FOR_CAMPAIGN_RESULT_IMPERIAL_CITY_NOT_CONTROLLED = 15
QUEUE_FOR_CAMPAIGN_RESULT_INSUFFICIENT_LEVEL = 18
QUEUE_FOR_CAMPAIGN_RESULT_INTERNAL_ERROR = 3
QUEUE_FOR_CAMPAIGN_RESULT_INVALID_CAMPAIGN = 8
QUEUE_FOR_CAMPAIGN_RESULT_INVALID_GROUP = 5
QUEUE_FOR_CAMPAIGN_RESULT_INVALID_LOGIN_STATE = 10
QUEUE_FOR_CAMPAIGN_RESULT_INVALID_WORLD = 11
QUEUE_FOR_CAMPAIGN_RESULT_IN_LFG_GROUP = 24
QUEUE_FOR_CAMPAIGN_RESULT_IS_DEAD = 27
QUEUE_FOR_CAMPAIGN_RESULT_LOGIN_WOULD_LOCK = 28
QUEUE_FOR_CAMPAIGN_RESULT_NOT_GROUP_LEADER = 9
QUEUE_FOR_CAMPAIGN_RESULT_NOT_ONLINE = 13
QUEUE_FOR_CAMPAIGN_RESULT_NO_PERMISSION = 2
QUEUE_FOR_CAMPAIGN_RESULT_REQUIREMENT_NOT_MET = 26
QUEUE_FOR_CAMPAIGN_RESULT_SUCCESS = 0
