--- @meta QuickCastGroundAbilitiesChoice

--- @alias QuickCastGroundAbilitiesChoice integer
--- | `QUICK_CAST_GROUND_ABILITIES_CHOICE_AUTOMATIC` # 2
--- | `QUICK_CAST_GROUND_ABILITIES_CHOICE_OFF` # 0
--- | `QUICK_CAST_GROUND_ABILITIES_CHOICE_ON` # 1

QUICK_CAST_GROUND_ABILITIES_CHOICE_AUTOMATIC = 2
QUICK_CAST_GROUND_ABILITIES_CHOICE_OFF = 0
QUICK_CAST_GROUND_ABILITIES_CHOICE_ON = 1
