--- @meta RaidPointReason

--- @alias RaidPointReason integer
--- | `RAID_POINT_REASON_BONUS_ACTIVITY_HIGH` # 8
--- | `RAID_POINT_REASON_BONUS_ACTIVITY_LOW` # 6
--- | `RAID_POINT_REASON_BONUS_ACTIVITY_MEDIUM` # 7
--- | `RAID_POINT_REASON_BONUS_POINT_ONE` # 10
--- | `RAID_POINT_REASON_BONUS_POINT_THREE` # 12
--- | `RAID_POINT_REASON_BONUS_POINT_TWO` # 11
--- | `RAID_POINT_REASON_KILL_BANNERMEN` # 2
--- | `RAID_POINT_REASON_KILL_BOSS` # 5
--- | `RAID_POINT_REASON_KILL_CHAMPION` # 3
--- | `RAID_POINT_REASON_KILL_MINIBOSS` # 4
--- | `RAID_POINT_REASON_KILL_NORMAL_MONSTER` # 1
--- | `RAID_POINT_REASON_KILL_NOXP_MONSTER` # 0
--- | `RAID_POINT_REASON_LIFE_REMAINING` # 9
--- | `RAID_POINT_REASON_SOLO_ARENA_COMPLETE` # 17
--- | `RAID_POINT_REASON_SOLO_ARENA_PICKUP_FOUR` # 16
--- | `RAID_POINT_REASON_SOLO_ARENA_PICKUP_ONE` # 13
--- | `RAID_POINT_REASON_SOLO_ARENA_PICKUP_THREE` # 15
--- | `RAID_POINT_REASON_SOLO_ARENA_PICKUP_TWO` # 14

RAID_POINT_REASON_BONUS_ACTIVITY_HIGH = 8
RAID_POINT_REASON_BONUS_ACTIVITY_LOW = 6
RAID_POINT_REASON_BONUS_ACTIVITY_MEDIUM = 7
RAID_POINT_REASON_BONUS_POINT_ONE = 10
RAID_POINT_REASON_BONUS_POINT_THREE = 12
RAID_POINT_REASON_BONUS_POINT_TWO = 11
RAID_POINT_REASON_KILL_BANNERMEN = 2
RAID_POINT_REASON_KILL_BOSS = 5
RAID_POINT_REASON_KILL_CHAMPION = 3
RAID_POINT_REASON_KILL_MINIBOSS = 4
RAID_POINT_REASON_KILL_NORMAL_MONSTER = 1
RAID_POINT_REASON_KILL_NOXP_MONSTER = 0
RAID_POINT_REASON_LIFE_REMAINING = 9
RAID_POINT_REASON_SOLO_ARENA_COMPLETE = 17
RAID_POINT_REASON_SOLO_ARENA_PICKUP_FOUR = 16
RAID_POINT_REASON_SOLO_ARENA_PICKUP_ONE = 13
RAID_POINT_REASON_SOLO_ARENA_PICKUP_THREE = 15
RAID_POINT_REASON_SOLO_ARENA_PICKUP_TWO = 14
