--- @meta RaidLifeVisibilityChoice

--- @alias RaidLifeVisibilityChoice integer
--- | `RAID_LIFE_VISIBILITY_CHOICE_AUTOMATIC` # 2
--- | `RAID_LIFE_VISIBILITY_CHOICE_OFF` # 0
--- | `RAID_LIFE_VISIBILITY_CHOICE_ON` # 1

RAID_LIFE_VISIBILITY_CHOICE_AUTOMATIC = 2
RAID_LIFE_VISIBILITY_CHOICE_OFF = 0
RAID_LIFE_VISIBILITY_CHOICE_ON = 1
