--- @meta RandomRollResult

--- @alias RandomRollResult integer
--- | `RANDOM_ROLL_RESULT_FAILED` # 1
--- | `RANDOM_ROLL_RESULT_INVALID_NUM_ROLLS` # 2
--- | `RANDOM_ROLL_RESULT_INVALID_RESULT` # 3
--- | `RANDOM_ROLL_RESULT_SUCCESS` # 0

RANDOM_ROLL_RESULT_FAILED = 1
RANDOM_ROLL_RESULT_INVALID_NUM_ROLLS = 2
RANDOM_ROLL_RESULT_INVALID_RESULT = 3
RANDOM_ROLL_RESULT_SUCCESS = 0
