--- @meta RatingsBoard

--- @alias RatingsBoard integer
--- | `RATINGS_BOARD_BR` # 3
--- | `RATINGS_BOARD_ESRB` # 1
--- | `RATINGS_BOARD_FPB` # 7
--- | `RATINGS_BOARD_NONE` # 0
--- | `RATINGS_BOARD_OFLC` # 4
--- | `RATINGS_BOARD_PEGI` # 2
--- | `RATINGS_BOARD_RR` # 6
--- | `RATINGS_BOARD_USK` # 5

RATINGS_BOARD_BR = 3
RATINGS_BOARD_ESRB = 1
RATINGS_BOARD_FPB = 7
RATINGS_BOARD_NONE = 0
RATINGS_BOARD_OFLC = 4
RATINGS_BOARD_PEGI = 2
RATINGS_BOARD_RR = 6
RATINGS_BOARD_USK = 5
