--- @meta RealmSelectMethod

--- @alias RealmSelectMethod integer
--- | `REALM_SELECT_METHOD_DEFAULT_REALM` # 0
--- | `REALM_SELECT_METHOD_LAST_REALM` # 2
--- | `REALM_SELECT_METHOD_USER_SELECTS` # 1

REALM_SELECT_METHOD_DEFAULT_REALM = 0
REALM_SELECT_METHOD_LAST_REALM = 2
REALM_SELECT_METHOD_USER_SELECTS = 1
