--- @meta RecipeCraftingSystem

--- @alias RecipeCraftingSystem integer
--- | `RECIPE_CRAFTING_SYSTEM_ALCHEMY_FORMULAE` # 4
--- | `RECIPE_CRAFTING_SYSTEM_BLACKSMITHING_DIAGRAMS` # 1
--- | `RECIPE_CRAFTING_SYSTEM_CLOTHIER_PATTERNS` # 2
--- | `RECIPE_CRAFTING_SYSTEM_ENCHANTING_SCHEMATICS` # 3
--- | `RECIPE_CRAFTING_SYSTEM_INVALID` # 0
--- | `RECIPE_CRAFTING_SYSTEM_JEWELRYCRAFTING_SKETCHES` # 7
--- | `RECIPE_CRAFTING_SYSTEM_PROVISIONING_DESIGNS` # 5
--- | `RECIPE_CRAFTING_SYSTEM_WOODWORKING_BLUEPRINTS` # 6

RECIPE_CRAFTING_SYSTEM_ALCHEMY_FORMULAE = 4
RECIPE_CRAFTING_SYSTEM_BLACKSMITHING_DIAGRAMS = 1
RECIPE_CRAFTING_SYSTEM_CLOTHIER_PATTERNS = 2
RECIPE_CRAFTING_SYSTEM_ENCHANTING_SCHEMATICS = 3
RECIPE_CRAFTING_SYSTEM_INVALID = 0
RECIPE_CRAFTING_SYSTEM_JEWELRYCRAFTING_SKETCHES = 7
RECIPE_CRAFTING_SYSTEM_PROVISIONING_DESIGNS = 5
RECIPE_CRAFTING_SYSTEM_WOODWORKING_BLUEPRINTS = 6
