--- @meta ReconstructResponse

--- @alias ReconstructResponse integer
--- | `RECONSTRUCT_RESPONSE_BAD_INTERACT_MODE` # 5
--- | `RECONSTRUCT_RESPONSE_INSUFFICIENT_FUNDS` # 6
--- | `RECONSTRUCT_RESPONSE_INSUFFICIENT_INVENTORY_SPACE` # 7
--- | `RECONSTRUCT_RESPONSE_INSUFFICIENT_UPGRADE_MATERIALS` # 8
--- | `RECONSTRUCT_RESPONSE_INVALID_CURRENCY` # 11
--- | `RECONSTRUCT_RESPONSE_INVALID_ITEM` # 2
--- | `RECONSTRUCT_RESPONSE_INVALID_QUALITY` # 10
--- | `RECONSTRUCT_RESPONSE_INVALID_TRAIT_FOR_ITEM` # 4
--- | `RECONSTRUCT_RESPONSE_ITEM_LOCKED` # 9
--- | `RECONSTRUCT_RESPONSE_SUCCESS` # 0
--- | `RECONSTRUCT_RESPONSE_TRAIT_NOT_RESEARCHED` # 3
--- | `RECONSTRUCT_RESPONSE_UNKNOWN_FAILURE` # 1

RECONSTRUCT_RESPONSE_BAD_INTERACT_MODE = 5
RECONSTRUCT_RESPONSE_INSUFFICIENT_FUNDS = 6
RECONSTRUCT_RESPONSE_INSUFFICIENT_INVENTORY_SPACE = 7
RECONSTRUCT_RESPONSE_INSUFFICIENT_UPGRADE_MATERIALS = 8
RECONSTRUCT_RESPONSE_INVALID_CURRENCY = 11
RECONSTRUCT_RESPONSE_INVALID_ITEM = 2
RECONSTRUCT_RESPONSE_INVALID_QUALITY = 10
RECONSTRUCT_RESPONSE_INVALID_TRAIT_FOR_ITEM = 4
RECONSTRUCT_RESPONSE_ITEM_LOCKED = 9
RECONSTRUCT_RESPONSE_SUCCESS = 0
RECONSTRUCT_RESPONSE_TRAIT_NOT_RESEARCHED = 3
RECONSTRUCT_RESPONSE_UNKNOWN_FAILURE = 1
