--- @meta RedeemCodeResult

--- @alias RedeemCodeResult integer
--- | `REDEEM_CODE_RESULT_ACCOUNT_NOT_FOUND` # 6
--- | `REDEEM_CODE_RESULT_CODE_NOT_FOUND` # 10
--- | `REDEEM_CODE_RESULT_CODE_REDEMPTION_FAILED` # 8
--- | `REDEEM_CODE_RESULT_ERROR` # 1
--- | `REDEEM_CODE_RESULT_INVALID_CODE` # 5
--- | `REDEEM_CODE_RESULT_MISSING_ACCOUNT_OR_NO_PROMO` # 9
--- | `REDEEM_CODE_RESULT_NOT_AVAILABLE_ON_PLATFORM` # 4
--- | `REDEEM_CODE_RESULT_SUCCESS` # 0
--- | `REDEEM_CODE_RESULT_TIMEOUT` # 3
--- | `REDEEM_CODE_RESULT_TOO_MANY_REQUESTS` # 2
--- | `REDEEM_CODE_RESULT_USER_CANNOT_REDEEM_CODE` # 7

REDEEM_CODE_RESULT_ACCOUNT_NOT_FOUND = 6
REDEEM_CODE_RESULT_CODE_NOT_FOUND = 10
REDEEM_CODE_RESULT_CODE_REDEMPTION_FAILED = 8
REDEEM_CODE_RESULT_ERROR = 1
REDEEM_CODE_RESULT_INVALID_CODE = 5
REDEEM_CODE_RESULT_MISSING_ACCOUNT_OR_NO_PROMO = 9
REDEEM_CODE_RESULT_NOT_AVAILABLE_ON_PLATFORM = 4
REDEEM_CODE_RESULT_SUCCESS = 0
REDEEM_CODE_RESULT_TIMEOUT = 3
REDEEM_CODE_RESULT_TOO_MANY_REQUESTS = 2
REDEEM_CODE_RESULT_USER_CANNOT_REDEEM_CODE = 7
