--- @meta ReflectionQuality

--- @alias ReflectionQuality integer
--- | `REFLECTION_QUALITY_HIGH` # 3
--- | `REFLECTION_QUALITY_LOW` # 1
--- | `REFLECTION_QUALITY_MEDIUM` # 2
--- | `REFLECTION_QUALITY_OFF` # 0
--- | `REFLECTION_QUALITY_SCORPIO` # 4

REFLECTION_QUALITY_HIGH = 3
REFLECTION_QUALITY_LOW = 1
REFLECTION_QUALITY_MEDIUM = 2
REFLECTION_QUALITY_OFF = 0
REFLECTION_QUALITY_SCORPIO = 4
