--- @meta RegisterForEventFilterType

--- @alias RegisterForEventFilterType integer
--- | `REGISTER_FILTER_ABILITY_ID` # 5
--- | `REGISTER_FILTER_BAG_ID` # 8
--- | `REGISTER_FILTER_COMBAT_RESULT` # 2
--- | `REGISTER_FILTER_INVALID` # -1
--- | `REGISTER_FILTER_INVENTORY_UPDATE_REASON` # 10
--- | `REGISTER_FILTER_IS_ERROR` # 4
--- | `REGISTER_FILTER_IS_IN_GAMEPAD_PREFERRED_MODE` # 6
--- | `REGISTER_FILTER_IS_NEW_ITEM` # 9
--- | `REGISTER_FILTER_PATRON_DRAFT_ID` # 14
--- | `REGISTER_FILTER_POWER_TYPE` # 0
--- | `REGISTER_FILTER_SETTING_SYSTEM_TYPE` # 11
--- | `REGISTER_FILTER_SOURCE_COMBAT_UNIT_TYPE` # 12
--- | `REGISTER_FILTER_TARGET_COMBAT_UNIT_TYPE` # 13
--- | `REGISTER_FILTER_UNIT_TAG` # 1
--- | `REGISTER_FILTER_UNIT_TAG_PREFIX` # 7
--- | `REGISTER_FILTER_VIBRATION_FILTER` # 3

REGISTER_FILTER_ABILITY_ID = 5
REGISTER_FILTER_BAG_ID = 8
REGISTER_FILTER_COMBAT_RESULT = 2
REGISTER_FILTER_INVALID = -1
REGISTER_FILTER_INVENTORY_UPDATE_REASON = 10
REGISTER_FILTER_IS_ERROR = 4
REGISTER_FILTER_IS_IN_GAMEPAD_PREFERRED_MODE = 6
REGISTER_FILTER_IS_NEW_ITEM = 9
REGISTER_FILTER_PATRON_DRAFT_ID = 14
REGISTER_FILTER_POWER_TYPE = 0
REGISTER_FILTER_SETTING_SYSTEM_TYPE = 11
REGISTER_FILTER_SOURCE_COMBAT_UNIT_TYPE = 12
REGISTER_FILTER_TARGET_COMBAT_UNIT_TYPE = 13
REGISTER_FILTER_UNIT_TAG = 1
REGISTER_FILTER_UNIT_TAG_PREFIX = 7
REGISTER_FILTER_VIBRATION_FILTER = 3
