--- @meta ReleaseKeepResultType

--- @alias ReleaseKeepResultType integer
--- | `RELEASE_KEEP_RESULT_TYPE_GUILD_DOES_NOT_HAVE_A_KEEP` # 8
--- | `RELEASE_KEEP_RESULT_TYPE_GUILD_DOES_NOT_OWN_KEEP` # 9
--- | `RELEASE_KEEP_RESULT_TYPE_INSUFFICIENT_PERMISSION` # 3
--- | `RELEASE_KEEP_RESULT_TYPE_INTERNAL_ERROR` # 4
--- | `RELEASE_KEEP_RESULT_TYPE_INVALID_DATA` # 7
--- | `RELEASE_KEEP_RESULT_TYPE_KEEP_DOES_NOT_EXIST` # 10
--- | `RELEASE_KEEP_RESULT_TYPE_NOT_IN_GUILD` # 2
--- | `RELEASE_KEEP_RESULT_TYPE_SOCIAL_DISABLED` # 5
--- | `RELEASE_KEEP_RESULT_TYPE_STILL_ON_COOLDOWN` # 6
--- | `RELEASE_KEEP_RESULT_TYPE_SUCCESS` # 1

RELEASE_KEEP_RESULT_TYPE_GUILD_DOES_NOT_HAVE_A_KEEP = 8
RELEASE_KEEP_RESULT_TYPE_GUILD_DOES_NOT_OWN_KEEP = 9
RELEASE_KEEP_RESULT_TYPE_INSUFFICIENT_PERMISSION = 3
RELEASE_KEEP_RESULT_TYPE_INTERNAL_ERROR = 4
RELEASE_KEEP_RESULT_TYPE_INVALID_DATA = 7
RELEASE_KEEP_RESULT_TYPE_KEEP_DOES_NOT_EXIST = 10
RELEASE_KEEP_RESULT_TYPE_NOT_IN_GUILD = 2
RELEASE_KEEP_RESULT_TYPE_SOCIAL_DISABLED = 5
RELEASE_KEEP_RESULT_TYPE_STILL_ON_COOLDOWN = 6
RELEASE_KEEP_RESULT_TYPE_SUCCESS = 1
