--- @meta RemoteSceneRequestType

--- @alias RemoteSceneRequestType integer
--- | `REMOTE_SCENE_REQUEST_TYPE_HIDE` # 1
--- | `REMOTE_SCENE_REQUEST_TYPE_POP` # 3
--- | `REMOTE_SCENE_REQUEST_TYPE_PUSH` # 2
--- | `REMOTE_SCENE_REQUEST_TYPE_SHOW` # 0
--- | `REMOTE_SCENE_REQUEST_TYPE_SHOW_BASE_SCENE` # 5
--- | `REMOTE_SCENE_REQUEST_TYPE_SWAP` # 4

REMOTE_SCENE_REQUEST_TYPE_HIDE = 1
REMOTE_SCENE_REQUEST_TYPE_POP = 3
REMOTE_SCENE_REQUEST_TYPE_PUSH = 2
REMOTE_SCENE_REQUEST_TYPE_SHOW = 0
REMOTE_SCENE_REQUEST_TYPE_SHOW_BASE_SCENE = 5
REMOTE_SCENE_REQUEST_TYPE_SWAP = 4
