--- @meta RemoteSceneSyncType

--- @alias RemoteSceneSyncType integer
--- | `REMOTE_SCENE_SYNC_TYPE_CHANGE_NEXT_SCENE` # 2
--- | `REMOTE_SCENE_SYNC_TYPE_HIDE_SCENE` # 1
--- | `REMOTE_SCENE_SYNC_TYPE_SHOW_SCENE` # 0

REMOTE_SCENE_SYNC_TYPE_CHANGE_NEXT_SCENE = 2
REMOTE_SCENE_SYNC_TYPE_HIDE_SCENE = 1
REMOTE_SCENE_SYNC_TYPE_SHOW_SCENE = 0
