--- @meta RemoveGroupListingReason

--- @alias RemoveGroupListingReason integer
--- | `REMOVE_GROUP_LISTING_REASON_REMOVED_BECAUSE_DISABLED_IN_ZONE` # 3
--- | `REMOVE_GROUP_LISTING_REASON_REMOVED_BECAUSE_LEADER_CHANGED` # 5
--- | `REMOVE_GROUP_LISTING_REASON_REMOVED_BECAUSE_LISTING_FULLFILLED` # 2
--- | `REMOVE_GROUP_LISTING_REASON_REMOVED_BY_LEADER` # 0
--- | `REMOVE_GROUP_LISTING_REASON_REMOVED_BY_QUEUE` # 4
--- | `REMOVE_GROUP_LISTING_REASON_REMOVED_BY_SERVER` # 1

REMOVE_GROUP_LISTING_REASON_REMOVED_BECAUSE_DISABLED_IN_ZONE = 3
REMOVE_GROUP_LISTING_REASON_REMOVED_BECAUSE_LEADER_CHANGED = 5
REMOVE_GROUP_LISTING_REASON_REMOVED_BECAUSE_LISTING_FULLFILLED = 2
REMOVE_GROUP_LISTING_REASON_REMOVED_BY_LEADER = 0
REMOVE_GROUP_LISTING_REASON_REMOVED_BY_QUEUE = 4
REMOVE_GROUP_LISTING_REASON_REMOVED_BY_SERVER = 1
