--- @meta ReportPlayerReason

--- @alias ReportPlayerReason integer
--- | `REPORT_PLAYER_REASON_BEHAVIOR` # 0
--- | `REPORT_PLAYER_REASON_BOTTING` # 5
--- | `REPORT_PLAYER_REASON_CHAT_SPAM` # 4
--- | `REPORT_PLAYER_REASON_FRIEND_REQUEST_SPAM` # 2
--- | `REPORT_PLAYER_REASON_GUILD_REQUEST_SPAM` # 3
--- | `REPORT_PLAYER_REASON_MAIL_SPAM` # 1

REPORT_PLAYER_REASON_BEHAVIOR = 0
REPORT_PLAYER_REASON_BOTTING = 5
REPORT_PLAYER_REASON_CHAT_SPAM = 4
REPORT_PLAYER_REASON_FRIEND_REQUEST_SPAM = 2
REPORT_PLAYER_REASON_GUILD_REQUEST_SPAM = 3
REPORT_PLAYER_REASON_MAIL_SPAM = 1
