--- @meta RequestReadMailResult

--- @alias RequestReadMailResult integer
--- | `REQUEST_READ_MAIL_RESULT_ALREADY_REQUESTED` # 4
--- | `REQUEST_READ_MAIL_RESULT_ANOTHER_REQUEST_PENDING` # 5
--- | `REQUEST_READ_MAIL_RESULT_NOT_IN_MAIL_INTERACTION` # 2
--- | `REQUEST_READ_MAIL_RESULT_NO_SUCH_MAIL` # 3
--- | `REQUEST_READ_MAIL_RESULT_SUCCESS_CACHED` # 0
--- | `REQUEST_READ_MAIL_RESULT_SUCCESS_SERVER_REQUESTED` # 1

REQUEST_READ_MAIL_RESULT_ALREADY_REQUESTED = 4
REQUEST_READ_MAIL_RESULT_ANOTHER_REQUEST_PENDING = 5
REQUEST_READ_MAIL_RESULT_NOT_IN_MAIL_INTERACTION = 2
REQUEST_READ_MAIL_RESULT_NO_SUCH_MAIL = 3
REQUEST_READ_MAIL_RESULT_SUCCESS_CACHED = 0
REQUEST_READ_MAIL_RESULT_SUCCESS_SERVER_REQUESTED = 1
