--- @meta ResourceNumbersSetting

--- @alias ResourceNumbersSetting integer
--- | `RESOURCE_NUMBERS_SETTING_NUMBER_AND_PERCENT` # 3
--- | `RESOURCE_NUMBERS_SETTING_NUMBER_ONLY` # 1
--- | `RESOURCE_NUMBERS_SETTING_OFF` # 0
--- | `RESOURCE_NUMBERS_SETTING_PERCENT_ONLY` # 2

RESOURCE_NUMBERS_SETTING_NUMBER_AND_PERCENT = 3
RESOURCE_NUMBERS_SETTING_NUMBER_ONLY = 1
RESOURCE_NUMBERS_SETTING_OFF = 0
RESOURCE_NUMBERS_SETTING_PERCENT_ONLY = 2
