--- @meta ResolveGroupListingApplicationRequest

--- @alias ResolveGroupListingApplicationRequest integer
--- | `RESOLVE_GROUP_LISTING_APPLICATION_REQUEST_APPROVE` # 0
--- | `RESOLVE_GROUP_LISTING_APPLICATION_REQUEST_REJECT` # 1
--- | `RESOLVE_GROUP_LISTING_APPLICATION_REQUEST_REJECTED_IGNORE` # 3
--- | `RESOLVE_GROUP_LISTING_APPLICATION_REQUEST_REJECTED_LEADER_BUSY` # 4
--- | `RESOLVE_GROUP_LISTING_APPLICATION_REQUEST_REJECTED_LISTING_NOT_AVAILABLE` # 5
--- | `RESOLVE_GROUP_LISTING_APPLICATION_REQUEST_RESCIND` # 2

RESOLVE_GROUP_LISTING_APPLICATION_REQUEST_APPROVE = 0
RESOLVE_GROUP_LISTING_APPLICATION_REQUEST_REJECT = 1
RESOLVE_GROUP_LISTING_APPLICATION_REQUEST_REJECTED_IGNORE = 3
RESOLVE_GROUP_LISTING_APPLICATION_REQUEST_REJECTED_LEADER_BUSY = 4
RESOLVE_GROUP_LISTING_APPLICATION_REQUEST_REJECTED_LISTING_NOT_AVAILABLE = 5
RESOLVE_GROUP_LISTING_APPLICATION_REQUEST_RESCIND = 2
