--- @meta ResolveGroupListingApplicationResponse

--- @alias ResolveGroupListingApplicationResponse integer
--- | `RESOLVE_GROUP_LISTING_APPLICATION_RESPONSE_FAILED_ACCEPTED_APPLICATION_TIMED_OUT` # 5
--- | `RESOLVE_GROUP_LISTING_APPLICATION_RESPONSE_REJECTED_BY_QUEUE` # 8
--- | `RESOLVE_GROUP_LISTING_APPLICATION_RESPONSE_REJECTED_DISABLED_IN_ZONE` # 7
--- | `RESOLVE_GROUP_LISTING_APPLICATION_RESPONSE_REJECTED_LEADER_BUSY` # 6
--- | `RESOLVE_GROUP_LISTING_APPLICATION_RESPONSE_REJECTED_LISTING_NOT_AVAILABLE` # 2
--- | `RESOLVE_GROUP_LISTING_APPLICATION_RESPONSE_REJECTED_MANUAL` # 1
--- | `RESOLVE_GROUP_LISTING_APPLICATION_RESPONSE_REJECTED_ROLE_NOT_AVAILABLE` # 3
--- | `RESOLVE_GROUP_LISTING_APPLICATION_RESPONSE_REJECTED_TIME_OUT` # 4
--- | `RESOLVE_GROUP_LISTING_APPLICATION_RESPONSE_RESCINDED` # 0

RESOLVE_GROUP_LISTING_APPLICATION_RESPONSE_FAILED_ACCEPTED_APPLICATION_TIMED_OUT = 5
RESOLVE_GROUP_LISTING_APPLICATION_RESPONSE_REJECTED_BY_QUEUE = 8
RESOLVE_GROUP_LISTING_APPLICATION_RESPONSE_REJECTED_DISABLED_IN_ZONE = 7
RESOLVE_GROUP_LISTING_APPLICATION_RESPONSE_REJECTED_LEADER_BUSY = 6
RESOLVE_GROUP_LISTING_APPLICATION_RESPONSE_REJECTED_LISTING_NOT_AVAILABLE = 2
RESOLVE_GROUP_LISTING_APPLICATION_RESPONSE_REJECTED_MANUAL = 1
RESOLVE_GROUP_LISTING_APPLICATION_RESPONSE_REJECTED_ROLE_NOT_AVAILABLE = 3
RESOLVE_GROUP_LISTING_APPLICATION_RESPONSE_REJECTED_TIME_OUT = 4
RESOLVE_GROUP_LISTING_APPLICATION_RESPONSE_RESCINDED = 0
