--- @meta ResourceBarsSettingChoice

--- @alias ResourceBarsSettingChoice integer
--- | `RESOURCE_BARS_SETTING_CHOICE_ALWAYS_SHOW` # 1
--- | `RESOURCE_BARS_SETTING_CHOICE_AUTOMATIC` # 2
--- | `RESOURCE_BARS_SETTING_CHOICE_DONT_SHOW` # 0

RESOURCE_BARS_SETTING_CHOICE_ALWAYS_SHOW = 1
RESOURCE_BARS_SETTING_CHOICE_AUTOMATIC = 2
RESOURCE_BARS_SETTING_CHOICE_DONT_SHOW = 0
