--- @meta RespecResult

--- @alias RespecResult integer
--- | `RESPEC_RESULT_ABILITY_DISABLED` # 42
--- | `RESPEC_RESULT_ACTIVE_ABILITY_IS_AUTOGRANT` # 27
--- | `RESPEC_RESULT_ACTIVE_ABILITY_NOT_FOUND` # 3
--- | `RESPEC_RESULT_ACTIVE_ABILITY_NOT_PURCHASED` # 26
--- | `RESPEC_RESULT_ACTIVE_ABILITY_PREREQS_UNMET` # 10
--- | `RESPEC_RESULT_ACTIVE_HOTBAR_NOT_RESPECCABLE` # 31
--- | `RESPEC_RESULT_CRAFTED_ABILITY_SCRIPT_DISABLED` # 44
--- | `RESPEC_RESULT_HAS_NO_CHANGES` # 16
--- | `RESPEC_RESULT_HOTBAR_ABILITY_ILLEGAL_SLOT` # 21
--- | `RESPEC_RESULT_HOTBAR_ABILITY_NOT_FOUND` # 17
--- | `RESPEC_RESULT_HOTBAR_ABILITY_NOT_PURCHASED` # 19
--- | `RESPEC_RESULT_HOTBAR_ABILITY_NOT_USABLE` # 20
--- | `RESPEC_RESULT_HOTBAR_ABILITY_REMOVED` # 18
--- | `RESPEC_RESULT_HOTBAR_ABILITY_SLOT_NOT_RESPECCABLE` # 13
--- | `RESPEC_RESULT_HOTBAR_INVALID_ABILITY` # 38
--- | `RESPEC_RESULT_HOTBAR_NOT_AN_ABILITY` # 12
--- | `RESPEC_RESULT_HOTBAR_NOT_COMPANION_BAR` # 36
--- | `RESPEC_RESULT_HOTBAR_NOT_COMPANION_SKILL` # 35
--- | `RESPEC_RESULT_HOTBAR_NOT_FOUND` # 11
--- | `RESPEC_RESULT_HOTBAR_NOT_RESPECCABLE` # 30
--- | `RESPEC_RESULT_HOTBAR_NO_COMPANION` # 37
--- | `RESPEC_RESULT_HOTBAR_SLOT_NOT_AVAILABLE` # 34
--- | `RESPEC_RESULT_INVALID_PROGRESSION_LINE` # 6
--- | `RESPEC_RESULT_INVALID_SKILL_LINE` # 4
--- | `RESPEC_RESULT_IS_IN_COMBAT` # 15
--- | `RESPEC_RESULT_IS_IN_COMBAT_ATTRIBUTE` # 40
--- | `RESPEC_RESULT_NOT_AT_SKILL_RESPEC_SHRINE` # 14
--- | `RESPEC_RESULT_NOT_ENOUGH_ATTRIBUTE_POINTS` # 39
--- | `RESPEC_RESULT_NOT_ENOUGH_GOLD` # 1
--- | `RESPEC_RESULT_NOT_ENOUGH_GOLD_FOR_MORPHS` # 29
--- | `RESPEC_RESULT_NOT_ENOUGH_MORPH_XP` # 7
--- | `RESPEC_RESULT_NOT_ENOUGH_SKILL_POINTS` # 2
--- | `RESPEC_RESULT_NO_FULL_RESPEC_SCROLL` # 8
--- | `RESPEC_RESULT_NO_MORPH_RESPEC_SCROLL` # 9
--- | `RESPEC_RESULT_PASSIVE_ABILITY_IS_AUTOGRANT` # 24
--- | `RESPEC_RESULT_PASSIVE_ABILITY_NOT_FOUND` # 22
--- | `RESPEC_RESULT_PASSIVE_ABILITY_NOT_PURCHASED` # 23
--- | `RESPEC_RESULT_PASSIVE_ABILITY_PREREQS_UNMET` # 25
--- | `RESPEC_RESULT_REMOVED_ABILITIES_DURING_PURCHASE_MODE` # 28
--- | `RESPEC_RESULT_REMOVED_NON_MORPH_DURING_MORPH_MODE` # 5
--- | `RESPEC_RESULT_SCRIBING_DISABLED` # 43
--- | `RESPEC_RESULT_SUCCESS` # 0
--- | `RESPEC_RESULT_UNKNOWN_REPEC_REQUEST_TYPE` # 41

RESPEC_RESULT_ABILITY_DISABLED = 42
RESPEC_RESULT_ACTIVE_ABILITY_IS_AUTOGRANT = 27
RESPEC_RESULT_ACTIVE_ABILITY_NOT_FOUND = 3
RESPEC_RESULT_ACTIVE_ABILITY_NOT_PURCHASED = 26
RESPEC_RESULT_ACTIVE_ABILITY_PREREQS_UNMET = 10
RESPEC_RESULT_ACTIVE_HOTBAR_NOT_RESPECCABLE = 31
RESPEC_RESULT_CRAFTED_ABILITY_SCRIPT_DISABLED = 44
RESPEC_RESULT_HAS_NO_CHANGES = 16
RESPEC_RESULT_HOTBAR_ABILITY_ILLEGAL_SLOT = 21
RESPEC_RESULT_HOTBAR_ABILITY_NOT_FOUND = 17
RESPEC_RESULT_HOTBAR_ABILITY_NOT_PURCHASED = 19
RESPEC_RESULT_HOTBAR_ABILITY_NOT_USABLE = 20
RESPEC_RESULT_HOTBAR_ABILITY_REMOVED = 18
RESPEC_RESULT_HOTBAR_ABILITY_SLOT_NOT_RESPECCABLE = 13
RESPEC_RESULT_HOTBAR_INVALID_ABILITY = 38
RESPEC_RESULT_HOTBAR_NOT_AN_ABILITY = 12
RESPEC_RESULT_HOTBAR_NOT_COMPANION_BAR = 36
RESPEC_RESULT_HOTBAR_NOT_COMPANION_SKILL = 35
RESPEC_RESULT_HOTBAR_NOT_FOUND = 11
RESPEC_RESULT_HOTBAR_NOT_RESPECCABLE = 30
RESPEC_RESULT_HOTBAR_NO_COMPANION = 37
RESPEC_RESULT_HOTBAR_SLOT_NOT_AVAILABLE = 34
RESPEC_RESULT_INVALID_PROGRESSION_LINE = 6
RESPEC_RESULT_INVALID_SKILL_LINE = 4
RESPEC_RESULT_IS_IN_COMBAT = 15
RESPEC_RESULT_IS_IN_COMBAT_ATTRIBUTE = 40
RESPEC_RESULT_NOT_AT_SKILL_RESPEC_SHRINE = 14
RESPEC_RESULT_NOT_ENOUGH_ATTRIBUTE_POINTS = 39
RESPEC_RESULT_NOT_ENOUGH_GOLD = 1
RESPEC_RESULT_NOT_ENOUGH_GOLD_FOR_MORPHS = 29
RESPEC_RESULT_NOT_ENOUGH_MORPH_XP = 7
RESPEC_RESULT_NOT_ENOUGH_SKILL_POINTS = 2
RESPEC_RESULT_NO_FULL_RESPEC_SCROLL = 8
RESPEC_RESULT_NO_MORPH_RESPEC_SCROLL = 9
RESPEC_RESULT_PASSIVE_ABILITY_IS_AUTOGRANT = 24
RESPEC_RESULT_PASSIVE_ABILITY_NOT_FOUND = 22
RESPEC_RESULT_PASSIVE_ABILITY_NOT_PURCHASED = 23
RESPEC_RESULT_PASSIVE_ABILITY_PREREQS_UNMET = 25
RESPEC_RESULT_REMOVED_ABILITIES_DURING_PURCHASE_MODE = 28
RESPEC_RESULT_REMOVED_NON_MORPH_DURING_MORPH_MODE = 5
RESPEC_RESULT_SCRIBING_DISABLED = 43
RESPEC_RESULT_SUCCESS = 0
RESPEC_RESULT_UNKNOWN_REPEC_REQUEST_TYPE = 41
