--- @meta RestyleMode

--- @alias RestyleMode integer
--- | `RESTYLE_MODE_COLLECTIBLE` # 3
--- | `RESTYLE_MODE_COMPANION_COLLECTIBLE` # 7
--- | `RESTYLE_MODE_COMPANION_EQUIPMENT` # 5
--- | `RESTYLE_MODE_COMPANION_OUTFIT` # 6
--- | `RESTYLE_MODE_EQUIPMENT` # 2
--- | `RESTYLE_MODE_NONE` # 0
--- | `RESTYLE_MODE_OUTFIT` # 4
--- | `RESTYLE_MODE_SELECTION` # 1

RESTYLE_MODE_COLLECTIBLE = 3
RESTYLE_MODE_COMPANION_COLLECTIBLE = 7
RESTYLE_MODE_COMPANION_EQUIPMENT = 5
RESTYLE_MODE_COMPANION_OUTFIT = 6
RESTYLE_MODE_EQUIPMENT = 2
RESTYLE_MODE_NONE = 0
RESTYLE_MODE_OUTFIT = 4
RESTYLE_MODE_SELECTION = 1
