--- @meta ResurrectResult

--- @alias ResurrectResult integer
--- | `RESURRECT_RESULT_ALREADY_CONSIDERING` # 1
--- | `RESURRECT_RESULT_DECLINED` # 0
--- | `RESURRECT_RESULT_IN_KILLZONE` # 4
--- | `RESURRECT_RESULT_NO_SOUL_GEM` # 3
--- | `RESURRECT_RESULT_SOUL_GEM_IN_USE` # 2
--- | `RESURRECT_RESULT_SUCCESS` # 5

RESURRECT_RESULT_ALREADY_CONSIDERING = 1
RESURRECT_RESULT_DECLINED = 0
RESURRECT_RESULT_IN_KILLZONE = 4
RESURRECT_RESULT_NO_SOUL_GEM = 3
RESURRECT_RESULT_SOUL_GEM_IN_USE = 2
RESURRECT_RESULT_SUCCESS = 5
