--- @meta RetraitResponse

--- @alias RetraitResponse integer
--- | `RETRAIT_RESPONSE_BAD_INTERACT_MODE` # 2
--- | `RETRAIT_RESPONSE_BAD_TRAIT_FOR_ITEM` # 3
--- | `RETRAIT_RESPONSE_HAVENT_RESEARCHED_TRAIT_FOR_ITEM` # 7
--- | `RETRAIT_RESPONSE_INSUFFICIENT_FUNDS` # 4
--- | `RETRAIT_RESPONSE_INVALID_ITEM_FOR_RETRAIT` # 6
--- | `RETRAIT_RESPONSE_ITEM_ALREADY_HAS_TRAIT` # 5
--- | `RETRAIT_RESPONSE_ITEM_NOT_FOUND` # 1
--- | `RETRAIT_RESPONSE_SUCCESS` # 0

RETRAIT_RESPONSE_BAD_INTERACT_MODE = 2
RETRAIT_RESPONSE_BAD_TRAIT_FOR_ITEM = 3
RETRAIT_RESPONSE_HAVENT_RESEARCHED_TRAIT_FOR_ITEM = 7
RETRAIT_RESPONSE_INSUFFICIENT_FUNDS = 4
RETRAIT_RESPONSE_INVALID_ITEM_FOR_RETRAIT = 6
RETRAIT_RESPONSE_ITEM_ALREADY_HAS_TRAIT = 5
RETRAIT_RESPONSE_ITEM_NOT_FOUND = 1
RETRAIT_RESPONSE_SUCCESS = 0
