--- @meta RewardType

--- @alias RewardType integer
--- | `REWARD_TYPE_ALLIANCE_POINTS` # 2
--- | `REWARD_TYPE_ARCHIVAL_FORTUNES` # 14
--- | `REWARD_TYPE_AUTO_ITEM` # 7
--- | `REWARD_TYPE_CHAOTIC_CREATIA` # 8
--- | `REWARD_TYPE_EVENT_TICKETS` # 11
--- | `REWARD_TYPE_INSPIRATION` # 5
--- | `REWARD_TYPE_MONEY` # 1
--- | `REWARD_TYPE_NONE` # 0
--- | `REWARD_TYPE_PARTIAL_SKILL_POINTS` # 9
--- | `REWARD_TYPE_SKILL_LINE` # 10
--- | `REWARD_TYPE_STYLE_STONES` # 12
--- | `REWARD_TYPE_TELVAR_STONES` # 4
--- | `REWARD_TYPE_TRIBUTE_CLUB_EXPERIENCE` # 13
--- | `REWARD_TYPE_UNDAUNTED_KEYS` # 6
--- | `REWARD_TYPE_WRIT_VOUCHERS` # 3

REWARD_TYPE_ALLIANCE_POINTS = 2
REWARD_TYPE_ARCHIVAL_FORTUNES = 14
REWARD_TYPE_AUTO_ITEM = 7
REWARD_TYPE_CHAOTIC_CREATIA = 8
REWARD_TYPE_EVENT_TICKETS = 11
REWARD_TYPE_INSPIRATION = 5
REWARD_TYPE_MONEY = 1
REWARD_TYPE_NONE = 0
REWARD_TYPE_PARTIAL_SKILL_POINTS = 9
REWARD_TYPE_SKILL_LINE = 10
REWARD_TYPE_STYLE_STONES = 12
REWARD_TYPE_TELVAR_STONES = 4
REWARD_TYPE_TRIBUTE_CLUB_EXPERIENCE = 13
REWARD_TYPE_UNDAUNTED_KEYS = 6
REWARD_TYPE_WRIT_VOUCHERS = 3
