--- @meta RewardItemType

--- @alias RewardItemType integer
--- | `REWARD_ITEM_TYPE_COLLECTIBLE` # 1
--- | `REWARD_ITEM_TYPE_ITEM` # 0
--- | `REWARD_ITEM_TYPE_TRIBUTE_CARD_UPGRADE` # 2

REWARD_ITEM_TYPE_COLLECTIBLE = 1
REWARD_ITEM_TYPE_ITEM = 0
REWARD_ITEM_TYPE_TRIBUTE_CARD_UPGRADE = 2
