--- @meta RewardEntryType

--- @alias RewardEntryType integer
--- | `REWARD_ENTRY_TYPE_ACTIVE_COMPANION_EXPERIENCE` # 11
--- | `REWARD_ENTRY_TYPE_ADD_CURRENCY` # 1
--- | `REWARD_ENTRY_TYPE_ADD_EFFECT` # 7
--- | `REWARD_ENTRY_TYPE_ADD_SKILL_LINE` # 5
--- | `REWARD_ENTRY_TYPE_ADD_TITLE` # 2
--- | `REWARD_ENTRY_TYPE_ADVANCE_ACHIEVEMENT` # 4
--- | `REWARD_ENTRY_TYPE_CHOICE` # 13
--- | `REWARD_ENTRY_TYPE_COLLECTIBLE` # 9
--- | `REWARD_ENTRY_TYPE_EXPERIENCE` # 16
--- | `REWARD_ENTRY_TYPE_INSTANT_UNLOCK` # 14
--- | `REWARD_ENTRY_TYPE_ITEM` # 12
--- | `REWARD_ENTRY_TYPE_LOOT_CRATE` # 10
--- | `REWARD_ENTRY_TYPE_MAIL_ITEM` # 0
--- | `REWARD_ENTRY_TYPE_REMOVE_EFFECT` # 8
--- | `REWARD_ENTRY_TYPE_REMOVE_SKILL_LINE` # 6
--- | `REWARD_ENTRY_TYPE_REMOVE_TITLE` # 3
--- | `REWARD_ENTRY_TYPE_REWARD_LIST` # 15
--- | `REWARD_ENTRY_TYPE_SKILL_LINE_EXPERIENCE` # 17
--- | `REWARD_ENTRY_TYPE_TRIBUTE_CARD_UPGRADE` # 18
--- | `REWARD_ENTRY_TYPE_TRIBUTE_CLUB_EXPERIENCE` # 19

REWARD_ENTRY_TYPE_ACTIVE_COMPANION_EXPERIENCE = 11
REWARD_ENTRY_TYPE_ADD_CURRENCY = 1
REWARD_ENTRY_TYPE_ADD_EFFECT = 7
REWARD_ENTRY_TYPE_ADD_SKILL_LINE = 5
REWARD_ENTRY_TYPE_ADD_TITLE = 2
REWARD_ENTRY_TYPE_ADVANCE_ACHIEVEMENT = 4
REWARD_ENTRY_TYPE_CHOICE = 13
REWARD_ENTRY_TYPE_COLLECTIBLE = 9
REWARD_ENTRY_TYPE_EXPERIENCE = 16
REWARD_ENTRY_TYPE_INSTANT_UNLOCK = 14
REWARD_ENTRY_TYPE_ITEM = 12
REWARD_ENTRY_TYPE_LOOT_CRATE = 10
REWARD_ENTRY_TYPE_MAIL_ITEM = 0
REWARD_ENTRY_TYPE_REMOVE_EFFECT = 8
REWARD_ENTRY_TYPE_REMOVE_SKILL_LINE = 6
REWARD_ENTRY_TYPE_REMOVE_TITLE = 3
REWARD_ENTRY_TYPE_REWARD_LIST = 15
REWARD_ENTRY_TYPE_SKILL_LINE_EXPERIENCE = 17
REWARD_ENTRY_TYPE_TRIBUTE_CARD_UPGRADE = 18
REWARD_ENTRY_TYPE_TRIBUTE_CLUB_EXPERIENCE = 19
