--- @meta RewardDisplayFlags

--- @alias RewardDisplayFlags integer
--- | `REWARD_DISPLAY_FLAGS_FROM_CONTAINER` # 2
--- | `REWARD_DISPLAY_FLAGS_FROM_CROWN_STORE` # 1
--- | `REWARD_DISPLAY_FLAGS_FROM_CROWN_STORE_CONTAINER` # 3

REWARD_DISPLAY_FLAGS_FROM_CONTAINER = 2
REWARD_DISPLAY_FLAGS_FROM_CROWN_STORE = 1
REWARD_DISPLAY_FLAGS_FROM_CROWN_STORE_CONTAINER = 3
