--- @meta RidingTrainType

--- @alias RidingTrainType integer
--- | `RIDING_TRAIN_CARRYING_CAPACITY` # 2
--- | `RIDING_TRAIN_INVALID` # 0
--- | `RIDING_TRAIN_SPEED` # 1
--- | `RIDING_TRAIN_STAMINA` # 3

RIDING_TRAIN_CARRYING_CAPACITY = 2
RIDING_TRAIN_INVALID = 0
RIDING_TRAIN_SPEED = 1
RIDING_TRAIN_STAMINA = 3
