--- @meta RidingTrainSource

--- @alias RidingTrainSource integer
--- | `RIDING_TRAIN_SOURCE_INITIALIZE` # 0
--- | `RIDING_TRAIN_SOURCE_ITEM` # 2
--- | `RIDING_TRAIN_SOURCE_STABLES` # 1

RIDING_TRAIN_SOURCE_INITIALIZE = 0
RIDING_TRAIN_SOURCE_ITEM = 2
RIDING_TRAIN_SOURCE_STABLES = 1
