--- @meta SaveLoadDialogError

--- @alias SaveLoadDialogError integer
--- | `SLD_ERROR_ALLOW_OVERWRITE` # 7
--- | `SLD_ERROR_FAILED_LOAD` # 2
--- | `SLD_ERROR_FAILED_SAVE` # 3
--- | `SLD_ERROR_FILE_CORRUPT` # 1
--- | `SLD_ERROR_NO_SAVE_CREATED` # 5
--- | `SLD_ERROR_NO_SAVE_DEVICE_SELECTED` # 6
--- | `SLD_ERROR_OUT_OF_SPACE` # 0
--- | `SLD_ERROR_SAVE_DEST_REMOVED` # 4

SLD_ERROR_ALLOW_OVERWRITE = 7
SLD_ERROR_FAILED_LOAD = 2
SLD_ERROR_FAILED_SAVE = 3
SLD_ERROR_FILE_CORRUPT = 1
SLD_ERROR_NO_SAVE_CREATED = 5
SLD_ERROR_NO_SAVE_DEVICE_SELECTED = 6
SLD_ERROR_OUT_OF_SPACE = 0
SLD_ERROR_SAVE_DEST_REMOVED = 4
