--- @meta ScaleLevelConstraintType

--- @alias ScaleLevelConstraintType integer
--- | `SCALE_LEVEL_CONSTRAINT_CHAMPION_RANK_MIN_CHAMPION_RANK_MAX` # 2
--- | `SCALE_LEVEL_CONSTRAINT_NORMAL_MIN_CHAMPION_RANK_MAX` # 1
--- | `SCALE_LEVEL_CONSTRAINT_NORMAL_MIN_NORMAL_MAX` # 0

SCALE_LEVEL_CONSTRAINT_CHAMPION_RANK_MIN_CHAMPION_RANK_MAX = 2
SCALE_LEVEL_CONSTRAINT_NORMAL_MIN_CHAMPION_RANK_MAX = 1
SCALE_LEVEL_CONSTRAINT_NORMAL_MIN_NORMAL_MAX = 0
