--- @meta SceneManagerMessageOrigin

--- @alias SceneManagerMessageOrigin integer
--- | `SCENE_MANAGER_MESSAGE_ORIGIN_INGAME` # 1
--- | `SCENE_MANAGER_MESSAGE_ORIGIN_INTERNAL` # 2
--- | `SCENE_MANAGER_MESSAGE_ORIGIN_PREGAME` # 0

SCENE_MANAGER_MESSAGE_ORIGIN_INGAME = 1
SCENE_MANAGER_MESSAGE_ORIGIN_INTERNAL = 2
SCENE_MANAGER_MESSAGE_ORIGIN_PREGAME = 0
