--- @meta ScoreTrackerEntryType

--- @alias ScoreTrackerEntryType integer
--- | `SCORE_TRACKER_TYPE_ASSISTS` # 6
--- | `SCORE_TRACKER_TYPE_CAPTURE_DEFENSE_POINTS` # 9
--- | `SCORE_TRACKER_TYPE_CAPTURE_KILLED_ATTACKER` # 11
--- | `SCORE_TRACKER_TYPE_CAPTURE_KILLED_DEFENDER` # 10
--- | `SCORE_TRACKER_TYPE_DAMAGED_FLAG_CARRIER` # 15
--- | `SCORE_TRACKER_TYPE_DAMAGE_DONE` # 1
--- | `SCORE_TRACKER_TYPE_DAMAGE_TAKEN` # 13
--- | `SCORE_TRACKER_TYPE_DEATH` # 4
--- | `SCORE_TRACKER_TYPE_FLAG_CAPTURED` # 5
--- | `SCORE_TRACKER_TYPE_FLAG_CARRIED_TIME` # 17
--- | `SCORE_TRACKER_TYPE_HEALED_FLAG_CARRIER` # 16
--- | `SCORE_TRACKER_TYPE_HEALING_DEFENDERS` # 14
--- | `SCORE_TRACKER_TYPE_HEALING_DONE` # 2
--- | `SCORE_TRACKER_TYPE_KILL` # 3
--- | `SCORE_TRACKER_TYPE_KILLED_FLAG_CARRIER` # 8
--- | `SCORE_TRACKER_TYPE_KILL_STREAK` # 12
--- | `SCORE_TRACKER_TYPE_NONE` # 0
--- | `SCORE_TRACKER_TYPE_SCORE` # 7

SCORE_TRACKER_TYPE_ASSISTS = 6
SCORE_TRACKER_TYPE_CAPTURE_DEFENSE_POINTS = 9
SCORE_TRACKER_TYPE_CAPTURE_KILLED_ATTACKER = 11
SCORE_TRACKER_TYPE_CAPTURE_KILLED_DEFENDER = 10
SCORE_TRACKER_TYPE_DAMAGED_FLAG_CARRIER = 15
SCORE_TRACKER_TYPE_DAMAGE_DONE = 1
SCORE_TRACKER_TYPE_DAMAGE_TAKEN = 13
SCORE_TRACKER_TYPE_DEATH = 4
SCORE_TRACKER_TYPE_FLAG_CAPTURED = 5
SCORE_TRACKER_TYPE_FLAG_CARRIED_TIME = 17
SCORE_TRACKER_TYPE_HEALED_FLAG_CARRIER = 16
SCORE_TRACKER_TYPE_HEALING_DEFENDERS = 14
SCORE_TRACKER_TYPE_HEALING_DONE = 2
SCORE_TRACKER_TYPE_KILL = 3
SCORE_TRACKER_TYPE_KILLED_FLAG_CARRIER = 8
SCORE_TRACKER_TYPE_KILL_STREAK = 12
SCORE_TRACKER_TYPE_NONE = 0
SCORE_TRACKER_TYPE_SCORE = 7
