--- @meta ScreenReaderNarrationType

--- @alias ScreenReaderNarrationType integer
--- | `NARRATION_TYPE_ALERT` # 1
--- | `NARRATION_TYPE_CENTER_SCREEN_ANNOUNCEMENT` # 4
--- | `NARRATION_TYPE_EDIT_BOX` # 0
--- | `NARRATION_TYPE_HUD` # 3
--- | `NARRATION_TYPE_TEXT_CHAT` # 5
--- | `NARRATION_TYPE_UI_SCREEN` # 2

NARRATION_TYPE_ALERT = 1
NARRATION_TYPE_CENTER_SCREEN_ANNOUNCEMENT = 4
NARRATION_TYPE_EDIT_BOX = 0
NARRATION_TYPE_HUD = 3
NARRATION_TYPE_TEXT_CHAT = 5
NARRATION_TYPE_UI_SCREEN = 2
