--- @meta ScreenspaceWaterReflectionQuality

--- @alias ScreenspaceWaterReflectionQuality integer
--- | `SCREENSPACE_WATER_REFLECTION_QUALITY_HIGH` # 3
--- | `SCREENSPACE_WATER_REFLECTION_QUALITY_LOW` # 1
--- | `SCREENSPACE_WATER_REFLECTION_QUALITY_MEDIUM` # 2
--- | `SCREENSPACE_WATER_REFLECTION_QUALITY_OFF` # 0
--- | `SCREENSPACE_WATER_REFLECTION_QUALITY_ULTRA` # 4

SCREENSPACE_WATER_REFLECTION_QUALITY_HIGH = 3
SCREENSPACE_WATER_REFLECTION_QUALITY_LOW = 1
SCREENSPACE_WATER_REFLECTION_QUALITY_MEDIUM = 2
SCREENSPACE_WATER_REFLECTION_QUALITY_OFF = 0
SCREENSPACE_WATER_REFLECTION_QUALITY_ULTRA = 4
