--- @meta ScribingErrorResult

--- @alias ScribingErrorResult integer
--- | `SCRIBING_ERROR_RESULT_CANNOT_OVERWRITE_CRAFTED_ABILITY` # 3
--- | `SCRIBING_ERROR_RESULT_CRAFTED_ABILITY_ALREADY_UNLOCKED` # 20
--- | `SCRIBING_ERROR_RESULT_CRAFTED_ABILITY_NOT_UNLOCKED` # 16
--- | `SCRIBING_ERROR_RESULT_CRAFTED_ABILITY_SCRIPT_NOT_LOCKED` # 14
--- | `SCRIBING_ERROR_RESULT_CRAFTED_ABILITY_SCRIPT_NOT_UNLOCKED` # 13
--- | `SCRIBING_ERROR_RESULT_DUPLICATE_CRAFTED_ABILITY` # 10
--- | `SCRIBING_ERROR_RESULT_FAILED_SKILL_TRANSITION` # 12
--- | `SCRIBING_ERROR_RESULT_FAILED_TO_REMOVE_CRAFTED_ABILITY` # 4
--- | `SCRIBING_ERROR_RESULT_FAILURE_TO_LOCK_CRAFTED_ABILITY_SCRIPT` # 6
--- | `SCRIBING_ERROR_RESULT_FAILURE_TO_UNLOCK_CRAFTED_ABILITY_SCRIPT` # 7
--- | `SCRIBING_ERROR_RESULT_INVALID_CRAFTED_ABILITY_DEF` # 1
--- | `SCRIBING_ERROR_RESULT_INVALID_CRAFTED_ABILITY_SCRIPT_DEF` # 2
--- | `SCRIBING_ERROR_RESULT_INVALID_CRAFTED_ABILITY_TYPE` # 5
--- | `SCRIBING_ERROR_RESULT_INVALID_ENTRY_POINT` # 8
--- | `SCRIBING_ERROR_RESULT_INVALID_LINKED_SKILL` # 11
--- | `SCRIBING_ERROR_RESULT_MARKED_FOR_DELETE` # 9
--- | `SCRIBING_ERROR_RESULT_NONE` # 0
--- | `SCRIBING_ERROR_RESULT_NO_SCRIPTS_UPDATED` # 15
--- | `SCRIBING_ERROR_RESULT_PRIMARY_CRAFTED_ABILITY_SCRIPT_DISABLED` # 21
--- | `SCRIBING_ERROR_RESULT_PRIMARY_CRAFTED_ABILITY_SCRIPT_NOT_UNLOCKED` # 17
--- | `SCRIBING_ERROR_RESULT_SECONDARY_CRAFTED_ABILITY_SCRIPT_DISABLED` # 22
--- | `SCRIBING_ERROR_RESULT_SECONDARY_CRAFTED_ABILITY_SCRIPT_NOT_UNLOCKED` # 18
--- | `SCRIBING_ERROR_RESULT_TERTIARY_CRAFTED_ABILITY_SCRIPT_DISABLED` # 23
--- | `SCRIBING_ERROR_RESULT_TERTIARY_CRAFTED_ABILITY_SCRIPT_NOT_UNLOCKED` # 19

SCRIBING_ERROR_RESULT_CANNOT_OVERWRITE_CRAFTED_ABILITY = 3
SCRIBING_ERROR_RESULT_CRAFTED_ABILITY_ALREADY_UNLOCKED = 20
SCRIBING_ERROR_RESULT_CRAFTED_ABILITY_NOT_UNLOCKED = 16
SCRIBING_ERROR_RESULT_CRAFTED_ABILITY_SCRIPT_NOT_LOCKED = 14
SCRIBING_ERROR_RESULT_CRAFTED_ABILITY_SCRIPT_NOT_UNLOCKED = 13
SCRIBING_ERROR_RESULT_DUPLICATE_CRAFTED_ABILITY = 10
SCRIBING_ERROR_RESULT_FAILED_SKILL_TRANSITION = 12
SCRIBING_ERROR_RESULT_FAILED_TO_REMOVE_CRAFTED_ABILITY = 4
SCRIBING_ERROR_RESULT_FAILURE_TO_LOCK_CRAFTED_ABILITY_SCRIPT = 6
SCRIBING_ERROR_RESULT_FAILURE_TO_UNLOCK_CRAFTED_ABILITY_SCRIPT = 7
SCRIBING_ERROR_RESULT_INVALID_CRAFTED_ABILITY_DEF = 1
SCRIBING_ERROR_RESULT_INVALID_CRAFTED_ABILITY_SCRIPT_DEF = 2
SCRIBING_ERROR_RESULT_INVALID_CRAFTED_ABILITY_TYPE = 5
SCRIBING_ERROR_RESULT_INVALID_ENTRY_POINT = 8
SCRIBING_ERROR_RESULT_INVALID_LINKED_SKILL = 11
SCRIBING_ERROR_RESULT_MARKED_FOR_DELETE = 9
SCRIBING_ERROR_RESULT_NONE = 0
SCRIBING_ERROR_RESULT_NO_SCRIPTS_UPDATED = 15
SCRIBING_ERROR_RESULT_PRIMARY_CRAFTED_ABILITY_SCRIPT_DISABLED = 21
SCRIBING_ERROR_RESULT_PRIMARY_CRAFTED_ABILITY_SCRIPT_NOT_UNLOCKED = 17
SCRIBING_ERROR_RESULT_SECONDARY_CRAFTED_ABILITY_SCRIPT_DISABLED = 22
SCRIBING_ERROR_RESULT_SECONDARY_CRAFTED_ABILITY_SCRIPT_NOT_UNLOCKED = 18
SCRIBING_ERROR_RESULT_TERTIARY_CRAFTED_ABILITY_SCRIPT_DISABLED = 23
SCRIBING_ERROR_RESULT_TERTIARY_CRAFTED_ABILITY_SCRIPT_NOT_UNLOCKED = 19
