--- @meta ScribingTooltipDisplayFlags

--- @alias ScribingTooltipDisplayFlags integer
--- | `SCRIBING_TOOLTIP_DISPLAY_FLAGS_SCRIPT_COMPATIBILITY_ERROR` # 4
--- | `SCRIBING_TOOLTIP_DISPLAY_FLAGS_SCRIPT_LOCKED_ERROR` # 2
--- | `SCRIBING_TOOLTIP_DISPLAY_FLAGS_SHOW_ACQUIRE_HINT` # 16
--- | `SCRIBING_TOOLTIP_DISPLAY_FLAGS_SHOW_ERRORS` # 1
--- | `SCRIBING_TOOLTIP_DISPLAY_FLAGS_SHOW_SELECTED_SCRIPTS` # 8

SCRIBING_TOOLTIP_DISPLAY_FLAGS_SCRIPT_COMPATIBILITY_ERROR = 4
SCRIBING_TOOLTIP_DISPLAY_FLAGS_SCRIPT_LOCKED_ERROR = 2
SCRIBING_TOOLTIP_DISPLAY_FLAGS_SHOW_ACQUIRE_HINT = 16
SCRIBING_TOOLTIP_DISPLAY_FLAGS_SHOW_ERRORS = 1
SCRIBING_TOOLTIP_DISPLAY_FLAGS_SHOW_SELECTED_SCRIPTS = 8
