--- @meta ScriptProfilerGarbageCollectionType

--- @alias ScriptProfilerGarbageCollectionType integer
--- | `SCRIPT_PROFILER_GARBAGE_COLLECTION_TYPE_AUTOMATIC` # 0
--- | `SCRIPT_PROFILER_GARBAGE_COLLECTION_TYPE_MANUAL` # 1

SCRIPT_PROFILER_GARBAGE_COLLECTION_TYPE_AUTOMATIC = 0
SCRIPT_PROFILER_GARBAGE_COLLECTION_TYPE_MANUAL = 1
