--- @meta ScribingSlot

--- @alias ScribingSlot integer
--- | `SCRIBING_SLOT_NONE` # 0
--- | `SCRIBING_SLOT_PRIMARY` # 1
--- | `SCRIBING_SLOT_SECONDARY` # 2
--- | `SCRIBING_SLOT_TERTIARY` # 3

SCRIBING_SLOT_NONE = 0
SCRIBING_SLOT_PRIMARY = 1
SCRIBING_SLOT_SECONDARY = 2
SCRIBING_SLOT_TERTIARY = 3
