--- @meta ScriptProfilerRecordDataType

--- @alias ScriptProfilerRecordDataType integer
--- | `SCRIPT_PROFILER_RECORD_DATA_TYPE_CFUNCTION` # 2
--- | `SCRIPT_PROFILER_RECORD_DATA_TYPE_CLOSURE` # 1
--- | `SCRIPT_PROFILER_RECORD_DATA_TYPE_GARBAGE_COLLECTION` # 3
--- | `SCRIPT_PROFILER_RECORD_DATA_TYPE_INVALID` # 0
--- | `SCRIPT_PROFILER_RECORD_DATA_TYPE_USER_EVENT` # 4

SCRIPT_PROFILER_RECORD_DATA_TYPE_CFUNCTION = 2
SCRIPT_PROFILER_RECORD_DATA_TYPE_CLOSURE = 1
SCRIPT_PROFILER_RECORD_DATA_TYPE_GARBAGE_COLLECTION = 3
SCRIPT_PROFILER_RECORD_DATA_TYPE_INVALID = 0
SCRIPT_PROFILER_RECORD_DATA_TYPE_USER_EVENT = 4
