--- @meta ScribingItemUseResult

--- @alias ScribingItemUseResult integer
--- | `SCRIBING_ITEM_USE_RESULT_CRAFTED_ABILITY_ALREADY_UNLOCKED` # 1
--- | `SCRIBING_ITEM_USE_RESULT_CRAFTED_ABILITY_SCRIPT_ALREADY_UNLOCKED` # 2
--- | `SCRIBING_ITEM_USE_RESULT_NONE` # 0

SCRIBING_ITEM_USE_RESULT_CRAFTED_ABILITY_ALREADY_UNLOCKED = 1
SCRIBING_ITEM_USE_RESULT_CRAFTED_ABILITY_SCRIPT_ALREADY_UNLOCKED = 2
SCRIBING_ITEM_USE_RESULT_NONE = 0
