--- @meta ScrollBounding

--- @alias ScrollBounding integer
--- | `SCROLL_BOUNDING_BOUND` # 1
--- | `SCROLL_BOUNDING_CONTAINED` # 3
--- | `SCROLL_BOUNDING_DEFAULT` # 0
--- | `SCROLL_BOUNDING_UNBOUND` # 2

SCROLL_BOUNDING_BOUND = 1
SCROLL_BOUNDING_CONTAINED = 3
SCROLL_BOUNDING_DEFAULT = 0
SCROLL_BOUNDING_UNBOUND = 2
