--- @meta ScryingActiveSkillUseResult

--- @alias ScryingActiveSkillUseResult integer
--- | `SCRYING_ACTIVE_SKILL_USE_RESULT_CANNOT_BOMB_WILDCARD` # 6
--- | `SCRYING_ACTIVE_SKILL_USE_RESULT_CANNOT_CAPTURE_WILDCARD` # 5
--- | `SCRYING_ACTIVE_SKILL_USE_RESULT_CANNOT_SELECT_OWNED` # 13
--- | `SCRYING_ACTIVE_SKILL_USE_RESULT_GAME_OVER` # 1
--- | `SCRYING_ACTIVE_SKILL_USE_RESULT_HEX_MUST_BE_ADJACENT` # 3
--- | `SCRYING_ACTIVE_SKILL_USE_RESULT_HEX_MUST_BE_REACHABLE` # 4
--- | `SCRYING_ACTIVE_SKILL_USE_RESULT_INVALID_SKILL` # 10
--- | `SCRYING_ACTIVE_SKILL_USE_RESULT_INVALID_TARGET_HEX` # 2
--- | `SCRYING_ACTIVE_SKILL_USE_RESULT_MISSING_SECOND_TARGET` # 7
--- | `SCRYING_ACTIVE_SKILL_USE_RESULT_NO_AFFECTED_HEXES` # 12
--- | `SCRYING_ACTIVE_SKILL_USE_RESULT_OUT_OF_NORMAL_ACTIONS` # 8
--- | `SCRYING_ACTIVE_SKILL_USE_RESULT_OUT_OF_SPECIAL_ACTIONS` # 9
--- | `SCRYING_ACTIVE_SKILL_USE_RESULT_SKILL_NOT_UNLOCKED` # 11
--- | `SCRYING_ACTIVE_SKILL_USE_RESULT_SUCCESS` # 0

SCRYING_ACTIVE_SKILL_USE_RESULT_CANNOT_BOMB_WILDCARD = 6
SCRYING_ACTIVE_SKILL_USE_RESULT_CANNOT_CAPTURE_WILDCARD = 5
SCRYING_ACTIVE_SKILL_USE_RESULT_CANNOT_SELECT_OWNED = 13
SCRYING_ACTIVE_SKILL_USE_RESULT_GAME_OVER = 1
SCRYING_ACTIVE_SKILL_USE_RESULT_HEX_MUST_BE_ADJACENT = 3
SCRYING_ACTIVE_SKILL_USE_RESULT_HEX_MUST_BE_REACHABLE = 4
SCRYING_ACTIVE_SKILL_USE_RESULT_INVALID_SKILL = 10
SCRYING_ACTIVE_SKILL_USE_RESULT_INVALID_TARGET_HEX = 2
SCRYING_ACTIVE_SKILL_USE_RESULT_MISSING_SECOND_TARGET = 7
SCRYING_ACTIVE_SKILL_USE_RESULT_NO_AFFECTED_HEXES = 12
SCRYING_ACTIVE_SKILL_USE_RESULT_OUT_OF_NORMAL_ACTIONS = 8
SCRYING_ACTIVE_SKILL_USE_RESULT_OUT_OF_SPECIAL_ACTIONS = 9
SCRYING_ACTIVE_SKILL_USE_RESULT_SKILL_NOT_UNLOCKED = 11
SCRYING_ACTIVE_SKILL_USE_RESULT_SUCCESS = 0
