--- @meta ScryingGridDirection

--- @alias ScryingGridDirection integer
--- | `SCRYING_GRID_DIRECTION_DOWN` # 3
--- | `SCRYING_GRID_DIRECTION_DOWN_LEFT` # 4
--- | `SCRYING_GRID_DIRECTION_DOWN_RIGHT` # 2
--- | `SCRYING_GRID_DIRECTION_INVALID` # -1
--- | `SCRYING_GRID_DIRECTION_UP` # 0
--- | `SCRYING_GRID_DIRECTION_UP_LEFT` # 5
--- | `SCRYING_GRID_DIRECTION_UP_RIGHT` # 1

SCRYING_GRID_DIRECTION_DOWN = 3
SCRYING_GRID_DIRECTION_DOWN_LEFT = 4
SCRYING_GRID_DIRECTION_DOWN_RIGHT = 2
SCRYING_GRID_DIRECTION_INVALID = -1
SCRYING_GRID_DIRECTION_UP = 0
SCRYING_GRID_DIRECTION_UP_LEFT = 5
SCRYING_GRID_DIRECTION_UP_RIGHT = 1
