--- @meta ScryingPassiveSkill

--- @alias ScryingPassiveSkill integer
--- | `SCRYING_PASSIVE_SKILL_ANTIQUARIAN_INSIGHT` # 0
--- | `SCRYING_PASSIVE_SKILL_AUGURIST_PATIENCE` # 1
--- | `SCRYING_PASSIVE_SKILL_FUTURE_FOCUS` # 2
--- | `SCRYING_PASSIVE_SKILL_PREEMPTIVE_POWER` # 3

SCRYING_PASSIVE_SKILL_ANTIQUARIAN_INSIGHT = 0
SCRYING_PASSIVE_SKILL_AUGURIST_PATIENCE = 1
SCRYING_PASSIVE_SKILL_FUTURE_FOCUS = 2
SCRYING_PASSIVE_SKILL_PREEMPTIVE_POWER = 3
