--- @meta ScryingHexagonType

--- @alias ScryingHexagonType integer
--- | `SCRYING_HEX_TYPE_EIGHT` # 8
--- | `SCRYING_HEX_TYPE_FIVE` # 5
--- | `SCRYING_HEX_TYPE_FOUR` # 4
--- | `SCRYING_HEX_TYPE_GOAL` # 101
--- | `SCRYING_HEX_TYPE_INVALID` # 0
--- | `SCRYING_HEX_TYPE_ONE` # 1
--- | `SCRYING_HEX_TYPE_OWNED` # 100
--- | `SCRYING_HEX_TYPE_SEVEN` # 7
--- | `SCRYING_HEX_TYPE_SIX` # 6
--- | `SCRYING_HEX_TYPE_SPECIAL` # 99
--- | `SCRYING_HEX_TYPE_THREE` # 3
--- | `SCRYING_HEX_TYPE_TWO` # 2

SCRYING_HEX_TYPE_EIGHT = 8
SCRYING_HEX_TYPE_FIVE = 5
SCRYING_HEX_TYPE_FOUR = 4
SCRYING_HEX_TYPE_GOAL = 101
SCRYING_HEX_TYPE_INVALID = 0
SCRYING_HEX_TYPE_ONE = 1
SCRYING_HEX_TYPE_OWNED = 100
SCRYING_HEX_TYPE_SEVEN = 7
SCRYING_HEX_TYPE_SIX = 6
SCRYING_HEX_TYPE_SPECIAL = 99
SCRYING_HEX_TYPE_THREE = 3
SCRYING_HEX_TYPE_TWO = 2
