--- @meta ScryingHexagonState

--- @alias ScryingHexagonState integer
--- | `SCRYING_HEX_STATE_ADJACENT` # 1
--- | `SCRYING_HEX_STATE_OWNED` # 0
--- | `SCRYING_HEX_STATE_REACHABLE` # 2
--- | `SCRYING_HEX_STATE_UNREACHABLE` # 3

SCRYING_HEX_STATE_ADJACENT = 1
SCRYING_HEX_STATE_OWNED = 0
SCRYING_HEX_STATE_REACHABLE = 2
SCRYING_HEX_STATE_UNREACHABLE = 3
