--- @meta ScryingActiveSkill

--- @alias ScryingActiveSkill integer
--- | `SCRYING_ACTIVE_SKILL_BOMB` # 1
--- | `SCRYING_ACTIVE_SKILL_CO_OPT` # 2
--- | `SCRYING_ACTIVE_SKILL_INVALID` # -1
--- | `SCRYING_ACTIVE_SKILL_LINE` # 3
--- | `SCRYING_ACTIVE_SKILL_NORMAL` # 0

SCRYING_ACTIVE_SKILL_BOMB = 1
SCRYING_ACTIVE_SKILL_CO_OPT = 2
SCRYING_ACTIVE_SKILL_INVALID = -1
SCRYING_ACTIVE_SKILL_LINE = 3
SCRYING_ACTIVE_SKILL_NORMAL = 0
