--- @meta SCTEventType

--- @alias SCTEventType integer
--- | `SCT_EVENT_TYPE_ABSORBED` # 2
--- | `SCT_EVENT_TYPE_ALLIANCE_POINTS` # 39
--- | `SCT_EVENT_TYPE_BLADETURN` # 24
--- | `SCT_EVENT_TYPE_BLOCKED` # 6
--- | `SCT_EVENT_TYPE_BLOCKED_DAMAGE` # 12
--- | `SCT_EVENT_TYPE_CHARMED` # 50
--- | `SCT_EVENT_TYPE_DAMAGE` # 10
--- | `SCT_EVENT_TYPE_DAMAGE_CRIT` # 11
--- | `SCT_EVENT_TYPE_DAMAGE_IMMUNE` # 46
--- | `SCT_EVENT_TYPE_DAMAGE_SHIELDED` # 17
--- | `SCT_EVENT_TYPE_DAMAGE_SHIELDED_BY_LOCAL_PLAYER_CAST_SHIELD` # 49
--- | `SCT_EVENT_TYPE_DEBUG_MESSAGE` # 40
--- | `SCT_EVENT_TYPE_DEFENDED` # 13
--- | `SCT_EVENT_TYPE_DISARMED` # 31
--- | `SCT_EVENT_TYPE_DISORIENTED` # 28
--- | `SCT_EVENT_TYPE_DODGED` # 5
--- | `SCT_EVENT_TYPE_DOT_IMMUNE` # 47
--- | `SCT_EVENT_TYPE_DOT_TICK` # 18
--- | `SCT_EVENT_TYPE_DOT_TICK_CRIT` # 19
--- | `SCT_EVENT_TYPE_EXPERIENCE_POINTS` # 38
--- | `SCT_EVENT_TYPE_FALL_DAMAGE` # 9
--- | `SCT_EVENT_TYPE_FEARED` # 27
--- | `SCT_EVENT_TYPE_HEAL` # 20
--- | `SCT_EVENT_TYPE_HEAL_ABSORBED` # 48
--- | `SCT_EVENT_TYPE_HEAL_CRIT` # 21
--- | `SCT_EVENT_TYPE_HOT_TICK` # 22
--- | `SCT_EVENT_TYPE_HOT_TICK_CRIT` # 23
--- | `SCT_EVENT_TYPE_IMMUNE` # 34
--- | `SCT_EVENT_TYPE_INTERCEPTED` # 15
--- | `SCT_EVENT_TYPE_INTERRUPT` # 14
--- | `SCT_EVENT_TYPE_KNOCKBACK` # 36
--- | `SCT_EVENT_TYPE_LEVITATED` # 30
--- | `SCT_EVENT_TYPE_MISS` # 4
--- | `SCT_EVENT_TYPE_NONE` # 0
--- | `SCT_EVENT_TYPE_OFFBALANCE` # 32
--- | `SCT_EVENT_TYPE_PACIFIED` # 29
--- | `SCT_EVENT_TYPE_PARRIED` # 3
--- | `SCT_EVENT_TYPE_PARTIAL_RESIST` # 8
--- | `SCT_EVENT_TYPE_REFLECTED` # 1
--- | `SCT_EVENT_TYPE_RESIST` # 7
--- | `SCT_EVENT_TYPE_ROOTED` # 37
--- | `SCT_EVENT_TYPE_SILENCED` # 26
--- | `SCT_EVENT_TYPE_SNARED` # 44
--- | `SCT_EVENT_TYPE_SPEED_BOOST` # 45
--- | `SCT_EVENT_TYPE_SST_COMBAT` # 41
--- | `SCT_EVENT_TYPE_SST_MOVEMENT` # 43
--- | `SCT_EVENT_TYPE_SST_STATE` # 42
--- | `SCT_EVENT_TYPE_STAGGERED` # 35
--- | `SCT_EVENT_TYPE_STUNNED` # 25
--- | `SCT_EVENT_TYPE_WEAPONSWAP` # 33
--- | `SCT_EVENT_TYPE_WRONG_WEAPON` # 16

SCT_EVENT_TYPE_ABSORBED = 2
SCT_EVENT_TYPE_ALLIANCE_POINTS = 39
SCT_EVENT_TYPE_BLADETURN = 24
SCT_EVENT_TYPE_BLOCKED = 6
SCT_EVENT_TYPE_BLOCKED_DAMAGE = 12
SCT_EVENT_TYPE_CHARMED = 50
SCT_EVENT_TYPE_DAMAGE = 10
SCT_EVENT_TYPE_DAMAGE_CRIT = 11
SCT_EVENT_TYPE_DAMAGE_IMMUNE = 46
SCT_EVENT_TYPE_DAMAGE_SHIELDED = 17
SCT_EVENT_TYPE_DAMAGE_SHIELDED_BY_LOCAL_PLAYER_CAST_SHIELD = 49
SCT_EVENT_TYPE_DEBUG_MESSAGE = 40
SCT_EVENT_TYPE_DEFENDED = 13
SCT_EVENT_TYPE_DISARMED = 31
SCT_EVENT_TYPE_DISORIENTED = 28
SCT_EVENT_TYPE_DODGED = 5
SCT_EVENT_TYPE_DOT_IMMUNE = 47
SCT_EVENT_TYPE_DOT_TICK = 18
SCT_EVENT_TYPE_DOT_TICK_CRIT = 19
SCT_EVENT_TYPE_EXPERIENCE_POINTS = 38
SCT_EVENT_TYPE_FALL_DAMAGE = 9
SCT_EVENT_TYPE_FEARED = 27
SCT_EVENT_TYPE_HEAL = 20
SCT_EVENT_TYPE_HEAL_ABSORBED = 48
SCT_EVENT_TYPE_HEAL_CRIT = 21
SCT_EVENT_TYPE_HOT_TICK = 22
SCT_EVENT_TYPE_HOT_TICK_CRIT = 23
SCT_EVENT_TYPE_IMMUNE = 34
SCT_EVENT_TYPE_INTERCEPTED = 15
SCT_EVENT_TYPE_INTERRUPT = 14
SCT_EVENT_TYPE_KNOCKBACK = 36
SCT_EVENT_TYPE_LEVITATED = 30
SCT_EVENT_TYPE_MISS = 4
SCT_EVENT_TYPE_NONE = 0
SCT_EVENT_TYPE_OFFBALANCE = 32
SCT_EVENT_TYPE_PACIFIED = 29
SCT_EVENT_TYPE_PARRIED = 3
SCT_EVENT_TYPE_PARTIAL_RESIST = 8
SCT_EVENT_TYPE_REFLECTED = 1
SCT_EVENT_TYPE_RESIST = 7
SCT_EVENT_TYPE_ROOTED = 37
SCT_EVENT_TYPE_SILENCED = 26
SCT_EVENT_TYPE_SNARED = 44
SCT_EVENT_TYPE_SPEED_BOOST = 45
SCT_EVENT_TYPE_SST_COMBAT = 41
SCT_EVENT_TYPE_SST_MOVEMENT = 43
SCT_EVENT_TYPE_SST_STATE = 42
SCT_EVENT_TYPE_STAGGERED = 35
SCT_EVENT_TYPE_STUNNED = 25
SCT_EVENT_TYPE_WEAPONSWAP = 33
SCT_EVENT_TYPE_WRONG_WEAPON = 16
