--- @meta SCTUnitType

--- @alias SCTUnitType integer
--- | `SCT_UNIT_TYPE_ALL` # 1
--- | `SCT_UNIT_TYPE_ALL_PLAYERS` # 4
--- | `SCT_UNIT_TYPE_LOCAL_PLAYER` # 2
--- | `SCT_UNIT_TYPE_LOCAL_PLAYER_FOLLOWER` # 6
--- | `SCT_UNIT_TYPE_MONSTERS` # 5
--- | `SCT_UNIT_TYPE_NONE` # 0
--- | `SCT_UNIT_TYPE_OTHER_PLAYERS` # 3

SCT_UNIT_TYPE_ALL = 1
SCT_UNIT_TYPE_ALL_PLAYERS = 4
SCT_UNIT_TYPE_LOCAL_PLAYER = 2
SCT_UNIT_TYPE_LOCAL_PLAYER_FOLLOWER = 6
SCT_UNIT_TYPE_MONSTERS = 5
SCT_UNIT_TYPE_NONE = 0
SCT_UNIT_TYPE_OTHER_PLAYERS = 3
