--- @meta SCTUnitAnchorType

--- @alias SCTUnitAnchorType integer
--- | `SCT_UNIT_ANCHOR_HEAD` # 0
--- | `SCT_UNIT_ANCHOR_LEFT_MIDDLE` # 3
--- | `SCT_UNIT_ANCHOR_LEFT_TOP` # 1
--- | `SCT_UNIT_ANCHOR_RIGHT_MIDDLE` # 4
--- | `SCT_UNIT_ANCHOR_RIGHT_TOP` # 2

SCT_UNIT_ANCHOR_HEAD = 0
SCT_UNIT_ANCHOR_LEFT_MIDDLE = 3
SCT_UNIT_ANCHOR_LEFT_TOP = 1
SCT_UNIT_ANCHOR_RIGHT_MIDDLE = 4
SCT_UNIT_ANCHOR_RIGHT_TOP = 2
