--- @meta SendMailResult

--- @alias SendMailResult integer
--- | `MAIL_SEND_RESULT_CANCELED` # 16
--- | `MAIL_SEND_RESULT_CANT_SEND_CASH_COD` # 8
--- | `MAIL_SEND_RESULT_CANT_SEND_TO_SELF` # 11
--- | `MAIL_SEND_RESULT_FAIL_BLANK_MAIL` # 7
--- | `MAIL_SEND_RESULT_FAIL_DB_ERROR` # 1
--- | `MAIL_SEND_RESULT_FAIL_IGNORED` # 4
--- | `MAIL_SEND_RESULT_FAIL_INVALID_NAME` # 2
--- | `MAIL_SEND_RESULT_FAIL_IN_PROGRESS` # 10
--- | `MAIL_SEND_RESULT_FAIL_MAILBOX_FULL` # 3
--- | `MAIL_SEND_RESULT_INVALID_ITEM` # 6
--- | `MAIL_SEND_RESULT_MAILBOX_NOT_OPEN` # 13
--- | `MAIL_SEND_RESULT_MAIL_DISABLED` # 12
--- | `MAIL_SEND_RESULT_NOT_ENOUGH_ITEMS_FOR_COD` # 9
--- | `MAIL_SEND_RESULT_NOT_ENOUGH_MONEY` # 5
--- | `MAIL_SEND_RESULT_RECIPIENT_NOT_FOUND` # 15
--- | `MAIL_SEND_RESULT_SUCCESS` # 0
--- | `MAIL_SEND_RESULT_TOO_MANY_ATTACHMENTS` # 14

MAIL_SEND_RESULT_CANCELED = 16
MAIL_SEND_RESULT_CANT_SEND_CASH_COD = 8
MAIL_SEND_RESULT_CANT_SEND_TO_SELF = 11
MAIL_SEND_RESULT_FAIL_BLANK_MAIL = 7
MAIL_SEND_RESULT_FAIL_DB_ERROR = 1
MAIL_SEND_RESULT_FAIL_IGNORED = 4
MAIL_SEND_RESULT_FAIL_INVALID_NAME = 2
MAIL_SEND_RESULT_FAIL_IN_PROGRESS = 10
MAIL_SEND_RESULT_FAIL_MAILBOX_FULL = 3
MAIL_SEND_RESULT_INVALID_ITEM = 6
MAIL_SEND_RESULT_MAILBOX_NOT_OPEN = 13
MAIL_SEND_RESULT_MAIL_DISABLED = 12
MAIL_SEND_RESULT_NOT_ENOUGH_ITEMS_FOR_COD = 9
MAIL_SEND_RESULT_NOT_ENOUGH_MONEY = 5
MAIL_SEND_RESULT_RECIPIENT_NOT_FOUND = 15
MAIL_SEND_RESULT_SUCCESS = 0
MAIL_SEND_RESULT_TOO_MANY_ATTACHMENTS = 14
