--- @meta ServiceTokenType

--- @alias ServiceTokenType integer
--- | `SERVICE_TOKEN_ALLIANCE_CHANGE` # 4
--- | `SERVICE_TOKEN_APPEARANCE_CHANGE` # 3
--- | `SERVICE_TOKEN_NAME_CHANGE` # 1
--- | `SERVICE_TOKEN_NONE` # 0
--- | `SERVICE_TOKEN_RACE_CHANGE` # 2

SERVICE_TOKEN_ALLIANCE_CHANGE = 4
SERVICE_TOKEN_APPEARANCE_CHANGE = 3
SERVICE_TOKEN_NAME_CHANGE = 1
SERVICE_TOKEN_NONE = 0
SERVICE_TOKEN_RACE_CHANGE = 2
