--- @meta SetMapResultCode

--- @alias SetMapResultCode integer
--- | `SET_MAP_RESULT_CURRENT_MAP_UNCHANGED` # 1
--- | `SET_MAP_RESULT_FAILED` # 0
--- | `SET_MAP_RESULT_MAP_CHANGED` # 2

SET_MAP_RESULT_CURRENT_MAP_UNCHANGED = 1
SET_MAP_RESULT_FAILED = 0
SET_MAP_RESULT_MAP_CHANGED = 2
