--- @meta SetOutfitNameResult

--- @alias SetOutfitNameResult integer
--- | `SET_OUTFIT_NAME_RESULT_NAME_INVALID` # 2
--- | `SET_OUTFIT_NAME_RESULT_NO_CHANGE` # 3
--- | `SET_OUTFIT_NAME_RESULT_OUTFIT_INVALID` # 1
--- | `SET_OUTFIT_NAME_RESULT_SUCCESS` # 0

SET_OUTFIT_NAME_RESULT_NAME_INVALID = 2
SET_OUTFIT_NAME_RESULT_NO_CHANGE = 3
SET_OUTFIT_NAME_RESULT_OUTFIT_INVALID = 1
SET_OUTFIT_NAME_RESULT_SUCCESS = 0
