--- @meta SetOptions

--- @alias SetOptions integer
--- | `SETTINGS_SET_OPTION_DO_NOT_SAVE_TO_PERSISTED_DATA` # 0
--- | `SETTINGS_SET_OPTION_SAVE_TO_PERSISTED_DATA` # 1

SETTINGS_SET_OPTION_DO_NOT_SAVE_TO_PERSISTED_DATA = 0
SETTINGS_SET_OPTION_SAVE_TO_PERSISTED_DATA = 1
