--- @meta SettingSystemType

--- @alias SettingSystemType integer
--- | `SETTING_TYPE_ACCESSIBILITY` # 21
--- | `SETTING_TYPE_ACCOUNT` # 4
--- | `SETTING_TYPE_ACTION_BARS` # 1
--- | `SETTING_TYPE_ACTIVE_COMBAT_TIP` # 9
--- | `SETTING_TYPE_AUDIO` # 11
--- | `SETTING_TYPE_BUFFS` # 20
--- | `SETTING_TYPE_CAMERA` # 2
--- | `SETTING_TYPE_CHAT_BUBBLE` # 14
--- | `SETTING_TYPE_CHAT_GLOBALS` # 18
--- | `SETTING_TYPE_CHAT_TABS` # 17
--- | `SETTING_TYPE_COMBAT` # 7
--- | `SETTING_TYPE_DEVELOPER_DEBUG` # 8
--- | `SETTING_TYPE_GAMEPAD` # 15
--- | `SETTING_TYPE_GRAPHICS` # 5
--- | `SETTING_TYPE_IN_WORLD` # 13
--- | `SETTING_TYPE_LANGUAGE` # 12
--- | `SETTING_TYPE_LOOT` # 6
--- | `SETTING_TYPE_NAMEPLATES` # 0
--- | `SETTING_TYPE_SUBTITLES` # 19
--- | `SETTING_TYPE_TUTORIAL` # 10
--- | `SETTING_TYPE_UI` # 3
--- | `SETTING_TYPE_VOICE` # 16

SETTING_TYPE_ACCESSIBILITY = 21
SETTING_TYPE_ACCOUNT = 4
SETTING_TYPE_ACTION_BARS = 1
SETTING_TYPE_ACTIVE_COMBAT_TIP = 9
SETTING_TYPE_AUDIO = 11
SETTING_TYPE_BUFFS = 20
SETTING_TYPE_CAMERA = 2
SETTING_TYPE_CHAT_BUBBLE = 14
SETTING_TYPE_CHAT_GLOBALS = 18
SETTING_TYPE_CHAT_TABS = 17
SETTING_TYPE_COMBAT = 7
SETTING_TYPE_DEVELOPER_DEBUG = 8
SETTING_TYPE_GAMEPAD = 15
SETTING_TYPE_GRAPHICS = 5
SETTING_TYPE_IN_WORLD = 13
SETTING_TYPE_LANGUAGE = 12
SETTING_TYPE_LOOT = 6
SETTING_TYPE_NAMEPLATES = 0
SETTING_TYPE_SUBTITLES = 19
SETTING_TYPE_TUTORIAL = 10
SETTING_TYPE_UI = 3
SETTING_TYPE_VOICE = 16
