--- @meta SettingSystemPanel

--- @alias SettingSystemPanel integer
--- | `SETTING_PANEL_ACCESSIBILITY` # 11
--- | `SETTING_PANEL_ACCOUNT` # 10
--- | `SETTING_PANEL_AUDIO` # 0
--- | `SETTING_PANEL_CAMERA` # 2
--- | `SETTING_PANEL_CINEMATIC` # 7
--- | `SETTING_PANEL_COMBAT` # 9
--- | `SETTING_PANEL_DEBUG` # 6
--- | `SETTING_PANEL_GAMEPLAY` # 4
--- | `SETTING_PANEL_INTERFACE` # 3
--- | `SETTING_PANEL_NAMEPLATES` # 8
--- | `SETTING_PANEL_SOCIAL` # 5
--- | `SETTING_PANEL_VIDEO` # 1

SETTING_PANEL_ACCESSIBILITY = 11
SETTING_PANEL_ACCOUNT = 10
SETTING_PANEL_AUDIO = 0
SETTING_PANEL_CAMERA = 2
SETTING_PANEL_CINEMATIC = 7
SETTING_PANEL_COMBAT = 9
SETTING_PANEL_DEBUG = 6
SETTING_PANEL_GAMEPLAY = 4
SETTING_PANEL_INTERFACE = 3
SETTING_PANEL_NAMEPLATES = 8
SETTING_PANEL_SOCIAL = 5
SETTING_PANEL_VIDEO = 1
