--- @meta ShadowsChoice

--- @alias ShadowsChoice integer
--- | `SHADOWS_CHOICE_HIGH` # 3
--- | `SHADOWS_CHOICE_LOW` # 1
--- | `SHADOWS_CHOICE_MEDIUM` # 2
--- | `SHADOWS_CHOICE_OFF` # 0
--- | `SHADOWS_CHOICE_PS4` # 5
--- | `SHADOWS_CHOICE_ULTRA` # 4
--- | `SHADOWS_CHOICE_XB1` # 6

SHADOWS_CHOICE_HIGH = 3
SHADOWS_CHOICE_LOW = 1
SHADOWS_CHOICE_MEDIUM = 2
SHADOWS_CHOICE_OFF = 0
SHADOWS_CHOICE_PS4 = 5
SHADOWS_CHOICE_ULTRA = 4
SHADOWS_CHOICE_XB1 = 6
