--- @meta ShaderEffectType

--- @alias ShaderEffectType integer
--- | `SHADER_EFFECT_TYPE_CAUSTIC` # 3
--- | `SHADER_EFFECT_TYPE_GAUSSIAN_BLUR` # 6
--- | `SHADER_EFFECT_TYPE_HALO` # 1
--- | `SHADER_EFFECT_TYPE_MOTION_BLUR` # 4
--- | `SHADER_EFFECT_TYPE_NONE` # 0
--- | `SHADER_EFFECT_TYPE_RADIAL_BLUR` # 5
--- | `SHADER_EFFECT_TYPE_WAVE` # 2

SHADER_EFFECT_TYPE_CAUSTIC = 3
SHADER_EFFECT_TYPE_GAUSSIAN_BLUR = 6
SHADER_EFFECT_TYPE_HALO = 1
SHADER_EFFECT_TYPE_MOTION_BLUR = 4
SHADER_EFFECT_TYPE_NONE = 0
SHADER_EFFECT_TYPE_RADIAL_BLUR = 5
SHADER_EFFECT_TYPE_WAVE = 2
