--- @meta SiegeType

--- @alias SiegeType integer
--- | `SIEGE_TYPE_BALLISTA` # 2
--- | `SIEGE_TYPE_CATAPULT` # 5
--- | `SIEGE_TYPE_GRAVEYARD` # 6
--- | `SIEGE_TYPE_LANCER` # 10
--- | `SIEGE_TYPE_MONSTER` # 7
--- | `SIEGE_TYPE_NONE` # 0
--- | `SIEGE_TYPE_OIL` # 8
--- | `SIEGE_TYPE_RAM` # 3
--- | `SIEGE_TYPE_REUSE_ME1` # 9
--- | `SIEGE_TYPE_TREBUCHET` # 1
--- | `SIEGE_TYPE_UNIVERSAL` # 4

SIEGE_TYPE_BALLISTA = 2
SIEGE_TYPE_CATAPULT = 5
SIEGE_TYPE_GRAVEYARD = 6
SIEGE_TYPE_LANCER = 10
SIEGE_TYPE_MONSTER = 7
SIEGE_TYPE_NONE = 0
SIEGE_TYPE_OIL = 8
SIEGE_TYPE_RAM = 3
SIEGE_TYPE_REUSE_ME1 = 9
SIEGE_TYPE_TREBUCHET = 1
SIEGE_TYPE_UNIVERSAL = 4
