--- @meta SkillGrowthType

--- @alias SkillGrowthType integer
--- | `SKILL_GROWTH_TYPE_AP` # 1
--- | `SKILL_GROWTH_TYPE_EXP` # 0
--- | `SKILL_GROWTH_TYPE_INSPIRATION` # 4
--- | `SKILL_GROWTH_TYPE_JUSTICE_THIEF` # 5
--- | `SKILL_GROWTH_TYPE_KEEP` # 3
--- | `SKILL_GROWTH_TYPE_SIEGE` # 2

SKILL_GROWTH_TYPE_AP = 1
SKILL_GROWTH_TYPE_EXP = 0
SKILL_GROWTH_TYPE_INSPIRATION = 4
SKILL_GROWTH_TYPE_JUSTICE_THIEF = 5
SKILL_GROWTH_TYPE_KEEP = 3
SKILL_GROWTH_TYPE_SIEGE = 2
