--- @meta SkillType

--- @alias SkillType integer
--- | `SKILL_TYPE_ARMOR` # 3
--- | `SKILL_TYPE_AVA` # 6
--- | `SKILL_TYPE_CHAMPION` # 9
--- | `SKILL_TYPE_CLASS` # 1
--- | `SKILL_TYPE_GUILD` # 5
--- | `SKILL_TYPE_NONE` # 0
--- | `SKILL_TYPE_RACIAL` # 7
--- | `SKILL_TYPE_TRADESKILL` # 8
--- | `SKILL_TYPE_WEAPON` # 2
--- | `SKILL_TYPE_WORLD` # 4

SKILL_TYPE_ARMOR = 3
SKILL_TYPE_AVA = 6
SKILL_TYPE_CHAMPION = 9
SKILL_TYPE_CLASS = 1
SKILL_TYPE_GUILD = 5
SKILL_TYPE_NONE = 0
SKILL_TYPE_RACIAL = 7
SKILL_TYPE_TRADESKILL = 8
SKILL_TYPE_WEAPON = 2
SKILL_TYPE_WORLD = 4
