--- @meta SkillPointReason

--- @alias SkillPointReason integer
--- | `SKILL_POINT_CHANGE_REASON_ACHIEVEMENT` # 5
--- | `SKILL_POINT_CHANGE_REASON_ACHIEVEMENT_COMPONENT` # 6
--- | `SKILL_POINT_CHANGE_REASON_ACTION` # 7
--- | `SKILL_POINT_CHANGE_REASON_AVA_RANK_UP` # 3
--- | `SKILL_POINT_CHANGE_REASON_CHAMPION_RANK_UP` # 4
--- | `SKILL_POINT_CHANGE_REASON_IGNORE` # 8
--- | `SKILL_POINT_CHANGE_REASON_INITIALIZE` # 12
--- | `SKILL_POINT_CHANGE_REASON_LEVEL_UP` # 1
--- | `SKILL_POINT_CHANGE_REASON_OTHER` # 0
--- | `SKILL_POINT_CHANGE_REASON_PURCHASE` # 11
--- | `SKILL_POINT_CHANGE_REASON_QUEST_REWARD` # 2
--- | `SKILL_POINT_CHANGE_REASON_SKILL_RESET` # 10
--- | `SKILL_POINT_CHANGE_REASON_SKILL_RESPEC` # 9
--- | `SKILL_POINT_CHANGE_REASON_SKYSHARD` # 14
--- | `SKILL_POINT_CHANGE_REASON_SKYSHARD_INSTANT_UNLOCK` # 13

SKILL_POINT_CHANGE_REASON_ACHIEVEMENT = 5
SKILL_POINT_CHANGE_REASON_ACHIEVEMENT_COMPONENT = 6
SKILL_POINT_CHANGE_REASON_ACTION = 7
SKILL_POINT_CHANGE_REASON_AVA_RANK_UP = 3
SKILL_POINT_CHANGE_REASON_CHAMPION_RANK_UP = 4
SKILL_POINT_CHANGE_REASON_IGNORE = 8
SKILL_POINT_CHANGE_REASON_INITIALIZE = 12
SKILL_POINT_CHANGE_REASON_LEVEL_UP = 1
SKILL_POINT_CHANGE_REASON_OTHER = 0
SKILL_POINT_CHANGE_REASON_PURCHASE = 11
SKILL_POINT_CHANGE_REASON_QUEST_REWARD = 2
SKILL_POINT_CHANGE_REASON_SKILL_RESET = 10
SKILL_POINT_CHANGE_REASON_SKILL_RESPEC = 9
SKILL_POINT_CHANGE_REASON_SKYSHARD = 14
SKILL_POINT_CHANGE_REASON_SKYSHARD_INSTANT_UNLOCK = 13
