--- @meta SkillPointAllocationMode

--- @alias SkillPointAllocationMode integer
--- | `SKILL_POINT_ALLOCATION_MODE_FULL` # 2
--- | `SKILL_POINT_ALLOCATION_MODE_MORPHS_ONLY` # 1
--- | `SKILL_POINT_ALLOCATION_MODE_PURCHASE_ONLY` # 0

SKILL_POINT_ALLOCATION_MODE_FULL = 2
SKILL_POINT_ALLOCATION_MODE_MORPHS_ONLY = 1
SKILL_POINT_ALLOCATION_MODE_PURCHASE_ONLY = 0
