--- @meta SkyshardDiscoveryStatus

--- @alias SkyshardDiscoveryStatus integer
--- | `SKYSHARD_DISCOVERY_STATUS_ACQUIRED` # 2
--- | `SKYSHARD_DISCOVERY_STATUS_DISCOVERED` # 1
--- | `SKYSHARD_DISCOVERY_STATUS_UNDISCOVERED` # 0

SKYSHARD_DISCOVERY_STATUS_ACQUIRED = 2
SKYSHARD_DISCOVERY_STATUS_DISCOVERED = 1
SKYSHARD_DISCOVERY_STATUS_UNDISCOVERED = 0
