--- @meta SmithingFilterType

--- @alias SmithingFilterType integer
--- | `SMITHING_FILTER_TYPE_ARMOR` # 4
--- | `SMITHING_FILTER_TYPE_JEWELRY` # 6
--- | `SMITHING_FILTER_TYPE_RAW_MATERIALS` # 1
--- | `SMITHING_FILTER_TYPE_SET_ARMOR` # 5
--- | `SMITHING_FILTER_TYPE_SET_JEWELRY` # 7
--- | `SMITHING_FILTER_TYPE_SET_WEAPONS` # 3
--- | `SMITHING_FILTER_TYPE_WEAPONS` # 2

SMITHING_FILTER_TYPE_ARMOR = 4
SMITHING_FILTER_TYPE_JEWELRY = 6
SMITHING_FILTER_TYPE_RAW_MATERIALS = 1
SMITHING_FILTER_TYPE_SET_ARMOR = 5
SMITHING_FILTER_TYPE_SET_JEWELRY = 7
SMITHING_FILTER_TYPE_SET_WEAPONS = 3
SMITHING_FILTER_TYPE_WEAPONS = 2
