--- @meta SmithingDeconstructionType

--- @alias SmithingDeconstructionType integer
--- | `SMITHING_DECONSTRUCTION_TYPE_ARMOR` # 2
--- | `SMITHING_DECONSTRUCTION_TYPE_JEWELRY` # 3
--- | `SMITHING_DECONSTRUCTION_TYPE_RAW_MATERIALS` # 4
--- | `SMITHING_DECONSTRUCTION_TYPE_WEAPONS_AND_ARMOR` # 1

SMITHING_DECONSTRUCTION_TYPE_ARMOR = 2
SMITHING_DECONSTRUCTION_TYPE_JEWELRY = 3
SMITHING_DECONSTRUCTION_TYPE_RAW_MATERIALS = 4
SMITHING_DECONSTRUCTION_TYPE_WEAPONS_AND_ARMOR = 1
