--- @meta SocketType

--- @alias SocketType integer
--- | `SOCKET_TYPE_AMMO` # 32
--- | `SOCKET_TYPE_ENCHANTMENT` # 1
--- | `SOCKET_TYPE_LAUNCH_VELOCITY` # 64
--- | `SOCKET_TYPE_NONE` # 0
--- | `SOCKET_TYPE_PRECISION` # 16
--- | `SOCKET_TYPE_TOUGHNESS` # 128

SOCKET_TYPE_AMMO = 32
SOCKET_TYPE_ENCHANTMENT = 1
SOCKET_TYPE_LAUNCH_VELOCITY = 64
SOCKET_TYPE_NONE = 0
SOCKET_TYPE_PRECISION = 16
SOCKET_TYPE_TOUGHNESS = 128
