--- @meta SpamWarningType

--- @alias SpamWarningType integer
--- | `SPAM_WARNING_TYPE_ACTION_SLOTS` # 1
--- | `SPAM_WARNING_TYPE_CHAT_MESSAGE` # 3
--- | `SPAM_WARNING_TYPE_GUILD_BANK_SELECTOR` # 4
--- | `SPAM_WARNING_TYPE_GUILD_DESCRIPTION` # 6
--- | `SPAM_WARNING_TYPE_GUILD_MOTD` # 5
--- | `SPAM_WARNING_TYPE_GUILD_RANK_CHANGE` # 7
--- | `SPAM_WARNING_TYPE_HOUSE_SAFE_LOC` # 8
--- | `SPAM_WARNING_TYPE_NONE` # 0
--- | `SPAM_WARNING_TYPE_TRADE_INVENTORY` # 2

SPAM_WARNING_TYPE_ACTION_SLOTS = 1
SPAM_WARNING_TYPE_CHAT_MESSAGE = 3
SPAM_WARNING_TYPE_GUILD_BANK_SELECTOR = 4
SPAM_WARNING_TYPE_GUILD_DESCRIPTION = 6
SPAM_WARNING_TYPE_GUILD_MOTD = 5
SPAM_WARNING_TYPE_GUILD_RANK_CHANGE = 7
SPAM_WARNING_TYPE_HOUSE_SAFE_LOC = 8
SPAM_WARNING_TYPE_NONE = 0
SPAM_WARNING_TYPE_TRADE_INVENTORY = 2
