--- @meta SpecializedItemType

--- @alias SpecializedItemType integer
--- | `SPECIALIZED_ITEMTYPE_ADDITIVE` # 550
--- | `SPECIALIZED_ITEMTYPE_ARMOR` # 300
--- | `SPECIALIZED_ITEMTYPE_ARMOR_BOOSTER` # 1150
--- | `SPECIALIZED_ITEMTYPE_ARMOR_TRAIT` # 2000
--- | `SPECIALIZED_ITEMTYPE_AVA_REPAIR` # 2100
--- | `SPECIALIZED_ITEMTYPE_BLACKSMITHING_BOOSTER` # 1800
--- | `SPECIALIZED_ITEMTYPE_BLACKSMITHING_MATERIAL` # 1550
--- | `SPECIALIZED_ITEMTYPE_BLACKSMITHING_RAW_MATERIAL` # 1500
--- | `SPECIALIZED_ITEMTYPE_CLOTHIER_BOOSTER` # 1900
--- | `SPECIALIZED_ITEMTYPE_CLOTHIER_MATERIAL` # 1750
--- | `SPECIALIZED_ITEMTYPE_CLOTHIER_RAW_MATERIAL` # 1700
--- | `SPECIALIZED_ITEMTYPE_COLLECTIBLE_MONSTER_TROPHY` # 81
--- | `SPECIALIZED_ITEMTYPE_COLLECTIBLE_RARE_FISH` # 80
--- | `SPECIALIZED_ITEMTYPE_COLLECTIBLE_STYLE_PAGE` # 82
--- | `SPECIALIZED_ITEMTYPE_CONTAINER` # 850
--- | `SPECIALIZED_ITEMTYPE_CONTAINER_CURRENCY` # 875
--- | `SPECIALIZED_ITEMTYPE_CONTAINER_EVENT` # 851
--- | `SPECIALIZED_ITEMTYPE_CONTAINER_STYLE_PAGE` # 852
--- | `SPECIALIZED_ITEMTYPE_COSTUME` # 600
--- | `SPECIALIZED_ITEMTYPE_CRAFTED_ABILITY` # 3200
--- | `SPECIALIZED_ITEMTYPE_CRAFTED_ABILITY_SCRIPT_PRIMARY` # 3250
--- | `SPECIALIZED_ITEMTYPE_CRAFTED_ABILITY_SCRIPT_SECONDARY` # 3251
--- | `SPECIALIZED_ITEMTYPE_CRAFTED_ABILITY_SCRIPT_TERTIARY` # 3252
--- | `SPECIALIZED_ITEMTYPE_CROWN_ITEM` # 2600
--- | `SPECIALIZED_ITEMTYPE_CROWN_REPAIR` # 2500
--- | `SPECIALIZED_ITEMTYPE_DISGUISE` # 650
--- | `SPECIALIZED_ITEMTYPE_DRINK_ALCOHOLIC` # 20
--- | `SPECIALIZED_ITEMTYPE_DRINK_CORDIAL_TEA` # 25
--- | `SPECIALIZED_ITEMTYPE_DRINK_DISTILLATE` # 26
--- | `SPECIALIZED_ITEMTYPE_DRINK_LIQUEUR` # 23
--- | `SPECIALIZED_ITEMTYPE_DRINK_TEA` # 21
--- | `SPECIALIZED_ITEMTYPE_DRINK_TINCTURE` # 24
--- | `SPECIALIZED_ITEMTYPE_DRINK_TONIC` # 22
--- | `SPECIALIZED_ITEMTYPE_DRINK_UNIQUE` # 27
--- | `SPECIALIZED_ITEMTYPE_DYE_STAMP` # 2700
--- | `SPECIALIZED_ITEMTYPE_ENCHANTING_RUNE_ASPECT` # 2350
--- | `SPECIALIZED_ITEMTYPE_ENCHANTING_RUNE_ESSENCE` # 2400
--- | `SPECIALIZED_ITEMTYPE_ENCHANTING_RUNE_POTENCY` # 2300
--- | `SPECIALIZED_ITEMTYPE_ENCHANTMENT_BOOSTER` # 1200
--- | `SPECIALIZED_ITEMTYPE_FISH` # 2450
--- | `SPECIALIZED_ITEMTYPE_FLAVORING` # 1350
--- | `SPECIALIZED_ITEMTYPE_FOOD_ENTREMET` # 6
--- | `SPECIALIZED_ITEMTYPE_FOOD_FRUIT` # 2
--- | `SPECIALIZED_ITEMTYPE_FOOD_GOURMET` # 7
--- | `SPECIALIZED_ITEMTYPE_FOOD_MEAT` # 1
--- | `SPECIALIZED_ITEMTYPE_FOOD_RAGOUT` # 5
--- | `SPECIALIZED_ITEMTYPE_FOOD_SAVOURY` # 4
--- | `SPECIALIZED_ITEMTYPE_FOOD_UNIQUE` # 8
--- | `SPECIALIZED_ITEMTYPE_FOOD_VEGETABLE` # 3
--- | `SPECIALIZED_ITEMTYPE_FURNISHING_ATTUNABLE_STATION` # 215
--- | `SPECIALIZED_ITEMTYPE_FURNISHING_CRAFTING_STATION` # 213
--- | `SPECIALIZED_ITEMTYPE_FURNISHING_LIGHT` # 211
--- | `SPECIALIZED_ITEMTYPE_FURNISHING_MATERIAL_ALCHEMY` # 1460
--- | `SPECIALIZED_ITEMTYPE_FURNISHING_MATERIAL_BLACKSMITHING` # 1560
--- | `SPECIALIZED_ITEMTYPE_FURNISHING_MATERIAL_CLOTHIER` # 1760
--- | `SPECIALIZED_ITEMTYPE_FURNISHING_MATERIAL_ENCHANTING` # 2410
--- | `SPECIALIZED_ITEMTYPE_FURNISHING_MATERIAL_JEWELRYCRAFTING` # 2860
--- | `SPECIALIZED_ITEMTYPE_FURNISHING_MATERIAL_PROVISIONING` # 1465
--- | `SPECIALIZED_ITEMTYPE_FURNISHING_MATERIAL_WOODWORKING` # 1660
--- | `SPECIALIZED_ITEMTYPE_FURNISHING_ORNAMENTAL` # 210
--- | `SPECIALIZED_ITEMTYPE_FURNISHING_SEATING` # 212
--- | `SPECIALIZED_ITEMTYPE_FURNISHING_TARGET_DUMMY` # 214
--- | `SPECIALIZED_ITEMTYPE_GLYPH_ARMOR` # 1000
--- | `SPECIALIZED_ITEMTYPE_GLYPH_JEWELRY` # 1250
--- | `SPECIALIZED_ITEMTYPE_GLYPH_WEAPON` # 950
--- | `SPECIALIZED_ITEMTYPE_GROUP_REPAIR` # 3150
--- | `SPECIALIZED_ITEMTYPE_HOLIDAY_WRIT` # 2760
--- | `SPECIALIZED_ITEMTYPE_INGREDIENT_ALCOHOL` # 44
--- | `SPECIALIZED_ITEMTYPE_INGREDIENT_DRINK_ADDITIVE` # 47
--- | `SPECIALIZED_ITEMTYPE_INGREDIENT_FOOD_ADDITIVE` # 43
--- | `SPECIALIZED_ITEMTYPE_INGREDIENT_FRUIT` # 42
--- | `SPECIALIZED_ITEMTYPE_INGREDIENT_MEAT` # 40
--- | `SPECIALIZED_ITEMTYPE_INGREDIENT_RARE` # 48
--- | `SPECIALIZED_ITEMTYPE_INGREDIENT_TEA` # 45
--- | `SPECIALIZED_ITEMTYPE_INGREDIENT_TONIC` # 46
--- | `SPECIALIZED_ITEMTYPE_INGREDIENT_VEGETABLE` # 41
--- | `SPECIALIZED_ITEMTYPE_JEWELRYCRAFTING_BOOSTER` # 2900
--- | `SPECIALIZED_ITEMTYPE_JEWELRYCRAFTING_MATERIAL` # 2850
--- | `SPECIALIZED_ITEMTYPE_JEWELRYCRAFTING_RAW_BOOSTER` # 3000
--- | `SPECIALIZED_ITEMTYPE_JEWELRYCRAFTING_RAW_MATERIAL` # 2800
--- | `SPECIALIZED_ITEMTYPE_JEWELRY_RAW_TRAIT` # 3050
--- | `SPECIALIZED_ITEMTYPE_JEWELRY_TRAIT` # 2950
--- | `SPECIALIZED_ITEMTYPE_LOCKPICK` # 1050
--- | `SPECIALIZED_ITEMTYPE_LURE` # 750
--- | `SPECIALIZED_ITEMTYPE_MASTER_WRIT` # 2750
--- | `SPECIALIZED_ITEMTYPE_MOUNT` # 2250
--- | `SPECIALIZED_ITEMTYPE_NONE` # 0
--- | `SPECIALIZED_ITEMTYPE_PLUG` # 350
--- | `SPECIALIZED_ITEMTYPE_POISON` # 1400
--- | `SPECIALIZED_ITEMTYPE_POISON_BASE` # 2650
--- | `SPECIALIZED_ITEMTYPE_POTION` # 450
--- | `SPECIALIZED_ITEMTYPE_POTION_BASE` # 1450
--- | `SPECIALIZED_ITEMTYPE_RACIAL_STYLE_MOTIF_BOOK` # 60
--- | `SPECIALIZED_ITEMTYPE_RACIAL_STYLE_MOTIF_CHAPTER` # 61
--- | `SPECIALIZED_ITEMTYPE_RAW_MATERIAL` # 800
--- | `SPECIALIZED_ITEMTYPE_REAGENT_ANIMAL_PART` # 152
--- | `SPECIALIZED_ITEMTYPE_REAGENT_FUNGUS` # 151
--- | `SPECIALIZED_ITEMTYPE_REAGENT_HERB` # 150
--- | `SPECIALIZED_ITEMTYPE_RECALL_STONE_KEEP` # 3100
--- | `SPECIALIZED_ITEMTYPE_RECIPE_ALCHEMY_FORMULA_FURNISHING` # 175
--- | `SPECIALIZED_ITEMTYPE_RECIPE_BLACKSMITHING_DIAGRAM_FURNISHING` # 172
--- | `SPECIALIZED_ITEMTYPE_RECIPE_CLOTHIER_PATTERN_FURNISHING` # 173
--- | `SPECIALIZED_ITEMTYPE_RECIPE_ENCHANTING_SCHEMATIC_FURNISHING` # 174
--- | `SPECIALIZED_ITEMTYPE_RECIPE_JEWELRYCRAFTING_SKETCH_FURNISHING` # 178
--- | `SPECIALIZED_ITEMTYPE_RECIPE_PROVISIONING_DESIGN_FURNISHING` # 176
--- | `SPECIALIZED_ITEMTYPE_RECIPE_PROVISIONING_STANDARD_DRINK` # 171
--- | `SPECIALIZED_ITEMTYPE_RECIPE_PROVISIONING_STANDARD_FOOD` # 170
--- | `SPECIALIZED_ITEMTYPE_RECIPE_WOODWORKING_BLUEPRINT_FURNISHING` # 177
--- | `SPECIALIZED_ITEMTYPE_SCRIBING_INK` # 3300
--- | `SPECIALIZED_ITEMTYPE_SIEGE_BALLISTA` # 401
--- | `SPECIALIZED_ITEMTYPE_SIEGE_CATAPULT` # 404
--- | `SPECIALIZED_ITEMTYPE_SIEGE_GRAVEYARD` # 405
--- | `SPECIALIZED_ITEMTYPE_SIEGE_LANCER` # 409
--- | `SPECIALIZED_ITEMTYPE_SIEGE_MONSTER` # 406
--- | `SPECIALIZED_ITEMTYPE_SIEGE_OIL` # 407
--- | `SPECIALIZED_ITEMTYPE_SIEGE_RAM` # 402
--- | `SPECIALIZED_ITEMTYPE_SIEGE_TREBUCHET` # 400
--- | `SPECIALIZED_ITEMTYPE_SIEGE_UNIVERSAL` # 403
--- | `SPECIALIZED_ITEMTYPE_SOUL_GEM` # 900
--- | `SPECIALIZED_ITEMTYPE_SPICE` # 1300
--- | `SPECIALIZED_ITEMTYPE_STYLE_MATERIAL` # 1950
--- | `SPECIALIZED_ITEMTYPE_TABARD` # 700
--- | `SPECIALIZED_ITEMTYPE_TOOL` # 500
--- | `SPECIALIZED_ITEMTYPE_TRASH` # 2150
--- | `SPECIALIZED_ITEMTYPE_TREASURE` # 2550
--- | `SPECIALIZED_ITEMTYPE_TROPHY_COLLECTIBLE_FRAGMENT` # 109
--- | `SPECIALIZED_ITEMTYPE_TROPHY_DUNGEON_BUFF_INGREDIENT` # 112
--- | `SPECIALIZED_ITEMTYPE_TROPHY_KEY` # 107
--- | `SPECIALIZED_ITEMTYPE_TROPHY_KEY_FRAGMENT` # 102
--- | `SPECIALIZED_ITEMTYPE_TROPHY_MATERIAL_UPGRADER` # 106
--- | `SPECIALIZED_ITEMTYPE_TROPHY_MUSEUM_PIECE` # 103
--- | `SPECIALIZED_ITEMTYPE_TROPHY_RECIPE_FRAGMENT` # 104
--- | `SPECIALIZED_ITEMTYPE_TROPHY_RUNEBOX_FRAGMENT` # 108
--- | `SPECIALIZED_ITEMTYPE_TROPHY_SCROLL` # 105
--- | `SPECIALIZED_ITEMTYPE_TROPHY_SURVEY_REPORT` # 101
--- | `SPECIALIZED_ITEMTYPE_TROPHY_TOY` # 111
--- | `SPECIALIZED_ITEMTYPE_TROPHY_TREASURE_MAP` # 100
--- | `SPECIALIZED_ITEMTYPE_TROPHY_TRIBUTE_CLUE` # 113
--- | `SPECIALIZED_ITEMTYPE_TROPHY_UPGRADE_FRAGMENT` # 110
--- | `SPECIALIZED_ITEMTYPE_WEAPON` # 250
--- | `SPECIALIZED_ITEMTYPE_WEAPON_BOOSTER` # 1100
--- | `SPECIALIZED_ITEMTYPE_WEAPON_TRAIT` # 2050
--- | `SPECIALIZED_ITEMTYPE_WOODWORKING_BOOSTER` # 1850
--- | `SPECIALIZED_ITEMTYPE_WOODWORKING_MATERIAL` # 1650
--- | `SPECIALIZED_ITEMTYPE_WOODWORKING_RAW_MATERIAL` # 1600

SPECIALIZED_ITEMTYPE_ADDITIVE = 550
SPECIALIZED_ITEMTYPE_ARMOR = 300
SPECIALIZED_ITEMTYPE_ARMOR_BOOSTER = 1150
SPECIALIZED_ITEMTYPE_ARMOR_TRAIT = 2000
SPECIALIZED_ITEMTYPE_AVA_REPAIR = 2100
SPECIALIZED_ITEMTYPE_BLACKSMITHING_BOOSTER = 1800
SPECIALIZED_ITEMTYPE_BLACKSMITHING_MATERIAL = 1550
SPECIALIZED_ITEMTYPE_BLACKSMITHING_RAW_MATERIAL = 1500
SPECIALIZED_ITEMTYPE_CLOTHIER_BOOSTER = 1900
SPECIALIZED_ITEMTYPE_CLOTHIER_MATERIAL = 1750
SPECIALIZED_ITEMTYPE_CLOTHIER_RAW_MATERIAL = 1700
SPECIALIZED_ITEMTYPE_COLLECTIBLE_MONSTER_TROPHY = 81
SPECIALIZED_ITEMTYPE_COLLECTIBLE_RARE_FISH = 80
SPECIALIZED_ITEMTYPE_COLLECTIBLE_STYLE_PAGE = 82
SPECIALIZED_ITEMTYPE_CONTAINER = 850
SPECIALIZED_ITEMTYPE_CONTAINER_CURRENCY = 875
SPECIALIZED_ITEMTYPE_CONTAINER_EVENT = 851
SPECIALIZED_ITEMTYPE_CONTAINER_STYLE_PAGE = 852
SPECIALIZED_ITEMTYPE_COSTUME = 600
SPECIALIZED_ITEMTYPE_CRAFTED_ABILITY = 3200
SPECIALIZED_ITEMTYPE_CRAFTED_ABILITY_SCRIPT_PRIMARY = 3250
SPECIALIZED_ITEMTYPE_CRAFTED_ABILITY_SCRIPT_SECONDARY = 3251
SPECIALIZED_ITEMTYPE_CRAFTED_ABILITY_SCRIPT_TERTIARY = 3252
SPECIALIZED_ITEMTYPE_CROWN_ITEM = 2600
SPECIALIZED_ITEMTYPE_CROWN_REPAIR = 2500
SPECIALIZED_ITEMTYPE_DISGUISE = 650
SPECIALIZED_ITEMTYPE_DRINK_ALCOHOLIC = 20
SPECIALIZED_ITEMTYPE_DRINK_CORDIAL_TEA = 25
SPECIALIZED_ITEMTYPE_DRINK_DISTILLATE = 26
SPECIALIZED_ITEMTYPE_DRINK_LIQUEUR = 23
SPECIALIZED_ITEMTYPE_DRINK_TEA = 21
SPECIALIZED_ITEMTYPE_DRINK_TINCTURE = 24
SPECIALIZED_ITEMTYPE_DRINK_TONIC = 22
SPECIALIZED_ITEMTYPE_DRINK_UNIQUE = 27
SPECIALIZED_ITEMTYPE_DYE_STAMP = 2700
SPECIALIZED_ITEMTYPE_ENCHANTING_RUNE_ASPECT = 2350
SPECIALIZED_ITEMTYPE_ENCHANTING_RUNE_ESSENCE = 2400
SPECIALIZED_ITEMTYPE_ENCHANTING_RUNE_POTENCY = 2300
SPECIALIZED_ITEMTYPE_ENCHANTMENT_BOOSTER = 1200
SPECIALIZED_ITEMTYPE_FISH = 2450
SPECIALIZED_ITEMTYPE_FLAVORING = 1350
SPECIALIZED_ITEMTYPE_FOOD_ENTREMET = 6
SPECIALIZED_ITEMTYPE_FOOD_FRUIT = 2
SPECIALIZED_ITEMTYPE_FOOD_GOURMET = 7
SPECIALIZED_ITEMTYPE_FOOD_MEAT = 1
SPECIALIZED_ITEMTYPE_FOOD_RAGOUT = 5
SPECIALIZED_ITEMTYPE_FOOD_SAVOURY = 4
SPECIALIZED_ITEMTYPE_FOOD_UNIQUE = 8
SPECIALIZED_ITEMTYPE_FOOD_VEGETABLE = 3
SPECIALIZED_ITEMTYPE_FURNISHING_ATTUNABLE_STATION = 215
SPECIALIZED_ITEMTYPE_FURNISHING_CRAFTING_STATION = 213
SPECIALIZED_ITEMTYPE_FURNISHING_LIGHT = 211
SPECIALIZED_ITEMTYPE_FURNISHING_MATERIAL_ALCHEMY = 1460
SPECIALIZED_ITEMTYPE_FURNISHING_MATERIAL_BLACKSMITHING = 1560
SPECIALIZED_ITEMTYPE_FURNISHING_MATERIAL_CLOTHIER = 1760
SPECIALIZED_ITEMTYPE_FURNISHING_MATERIAL_ENCHANTING = 2410
SPECIALIZED_ITEMTYPE_FURNISHING_MATERIAL_JEWELRYCRAFTING = 2860
SPECIALIZED_ITEMTYPE_FURNISHING_MATERIAL_PROVISIONING = 1465
SPECIALIZED_ITEMTYPE_FURNISHING_MATERIAL_WOODWORKING = 1660
SPECIALIZED_ITEMTYPE_FURNISHING_ORNAMENTAL = 210
SPECIALIZED_ITEMTYPE_FURNISHING_SEATING = 212
SPECIALIZED_ITEMTYPE_FURNISHING_TARGET_DUMMY = 214
SPECIALIZED_ITEMTYPE_GLYPH_ARMOR = 1000
SPECIALIZED_ITEMTYPE_GLYPH_JEWELRY = 1250
SPECIALIZED_ITEMTYPE_GLYPH_WEAPON = 950
SPECIALIZED_ITEMTYPE_GROUP_REPAIR = 3150
SPECIALIZED_ITEMTYPE_HOLIDAY_WRIT = 2760
SPECIALIZED_ITEMTYPE_INGREDIENT_ALCOHOL = 44
SPECIALIZED_ITEMTYPE_INGREDIENT_DRINK_ADDITIVE = 47
SPECIALIZED_ITEMTYPE_INGREDIENT_FOOD_ADDITIVE = 43
SPECIALIZED_ITEMTYPE_INGREDIENT_FRUIT = 42
SPECIALIZED_ITEMTYPE_INGREDIENT_MEAT = 40
SPECIALIZED_ITEMTYPE_INGREDIENT_RARE = 48
SPECIALIZED_ITEMTYPE_INGREDIENT_TEA = 45
SPECIALIZED_ITEMTYPE_INGREDIENT_TONIC = 46
SPECIALIZED_ITEMTYPE_INGREDIENT_VEGETABLE = 41
SPECIALIZED_ITEMTYPE_JEWELRYCRAFTING_BOOSTER = 2900
SPECIALIZED_ITEMTYPE_JEWELRYCRAFTING_MATERIAL = 2850
SPECIALIZED_ITEMTYPE_JEWELRYCRAFTING_RAW_BOOSTER = 3000
SPECIALIZED_ITEMTYPE_JEWELRYCRAFTING_RAW_MATERIAL = 2800
SPECIALIZED_ITEMTYPE_JEWELRY_RAW_TRAIT = 3050
SPECIALIZED_ITEMTYPE_JEWELRY_TRAIT = 2950
SPECIALIZED_ITEMTYPE_LOCKPICK = 1050
SPECIALIZED_ITEMTYPE_LURE = 750
SPECIALIZED_ITEMTYPE_MASTER_WRIT = 2750
SPECIALIZED_ITEMTYPE_MOUNT = 2250
SPECIALIZED_ITEMTYPE_NONE = 0
SPECIALIZED_ITEMTYPE_PLUG = 350
SPECIALIZED_ITEMTYPE_POISON = 1400
SPECIALIZED_ITEMTYPE_POISON_BASE = 2650
SPECIALIZED_ITEMTYPE_POTION = 450
SPECIALIZED_ITEMTYPE_POTION_BASE = 1450
SPECIALIZED_ITEMTYPE_RACIAL_STYLE_MOTIF_BOOK = 60
SPECIALIZED_ITEMTYPE_RACIAL_STYLE_MOTIF_CHAPTER = 61
SPECIALIZED_ITEMTYPE_RAW_MATERIAL = 800
SPECIALIZED_ITEMTYPE_REAGENT_ANIMAL_PART = 152
SPECIALIZED_ITEMTYPE_REAGENT_FUNGUS = 151
SPECIALIZED_ITEMTYPE_REAGENT_HERB = 150
SPECIALIZED_ITEMTYPE_RECALL_STONE_KEEP = 3100
SPECIALIZED_ITEMTYPE_RECIPE_ALCHEMY_FORMULA_FURNISHING = 175
SPECIALIZED_ITEMTYPE_RECIPE_BLACKSMITHING_DIAGRAM_FURNISHING = 172
SPECIALIZED_ITEMTYPE_RECIPE_CLOTHIER_PATTERN_FURNISHING = 173
SPECIALIZED_ITEMTYPE_RECIPE_ENCHANTING_SCHEMATIC_FURNISHING = 174
SPECIALIZED_ITEMTYPE_RECIPE_JEWELRYCRAFTING_SKETCH_FURNISHING = 178
SPECIALIZED_ITEMTYPE_RECIPE_PROVISIONING_DESIGN_FURNISHING = 176
SPECIALIZED_ITEMTYPE_RECIPE_PROVISIONING_STANDARD_DRINK = 171
SPECIALIZED_ITEMTYPE_RECIPE_PROVISIONING_STANDARD_FOOD = 170
SPECIALIZED_ITEMTYPE_RECIPE_WOODWORKING_BLUEPRINT_FURNISHING = 177
SPECIALIZED_ITEMTYPE_SCRIBING_INK = 3300
SPECIALIZED_ITEMTYPE_SIEGE_BALLISTA = 401
SPECIALIZED_ITEMTYPE_SIEGE_CATAPULT = 404
SPECIALIZED_ITEMTYPE_SIEGE_GRAVEYARD = 405
SPECIALIZED_ITEMTYPE_SIEGE_LANCER = 409
SPECIALIZED_ITEMTYPE_SIEGE_MONSTER = 406
SPECIALIZED_ITEMTYPE_SIEGE_OIL = 407
SPECIALIZED_ITEMTYPE_SIEGE_RAM = 402
SPECIALIZED_ITEMTYPE_SIEGE_TREBUCHET = 400
SPECIALIZED_ITEMTYPE_SIEGE_UNIVERSAL = 403
SPECIALIZED_ITEMTYPE_SOUL_GEM = 900
SPECIALIZED_ITEMTYPE_SPICE = 1300
SPECIALIZED_ITEMTYPE_STYLE_MATERIAL = 1950
SPECIALIZED_ITEMTYPE_TABARD = 700
SPECIALIZED_ITEMTYPE_TOOL = 500
SPECIALIZED_ITEMTYPE_TRASH = 2150
SPECIALIZED_ITEMTYPE_TREASURE = 2550
SPECIALIZED_ITEMTYPE_TROPHY_COLLECTIBLE_FRAGMENT = 109
SPECIALIZED_ITEMTYPE_TROPHY_DUNGEON_BUFF_INGREDIENT = 112
SPECIALIZED_ITEMTYPE_TROPHY_KEY = 107
SPECIALIZED_ITEMTYPE_TROPHY_KEY_FRAGMENT = 102
SPECIALIZED_ITEMTYPE_TROPHY_MATERIAL_UPGRADER = 106
SPECIALIZED_ITEMTYPE_TROPHY_MUSEUM_PIECE = 103
SPECIALIZED_ITEMTYPE_TROPHY_RECIPE_FRAGMENT = 104
SPECIALIZED_ITEMTYPE_TROPHY_RUNEBOX_FRAGMENT = 108
SPECIALIZED_ITEMTYPE_TROPHY_SCROLL = 105
SPECIALIZED_ITEMTYPE_TROPHY_SURVEY_REPORT = 101
SPECIALIZED_ITEMTYPE_TROPHY_TOY = 111
SPECIALIZED_ITEMTYPE_TROPHY_TREASURE_MAP = 100
SPECIALIZED_ITEMTYPE_TROPHY_TRIBUTE_CLUE = 113
SPECIALIZED_ITEMTYPE_TROPHY_UPGRADE_FRAGMENT = 110
SPECIALIZED_ITEMTYPE_WEAPON = 250
SPECIALIZED_ITEMTYPE_WEAPON_BOOSTER = 1100
SPECIALIZED_ITEMTYPE_WEAPON_TRAIT = 2050
SPECIALIZED_ITEMTYPE_WOODWORKING_BOOSTER = 1850
SPECIALIZED_ITEMTYPE_WOODWORKING_MATERIAL = 1650
SPECIALIZED_ITEMTYPE_WOODWORKING_RAW_MATERIAL = 1600
