--- @meta SpecialMove

--- @alias SpecialMove integer
--- | `SPECIAL_MOVE_INDEX_BLOCK` # 0
--- | `SPECIAL_MOVE_INDEX_CROUCH` # 2
--- | `SPECIAL_MOVE_INDEX_INTERRUPT` # 3
--- | `SPECIAL_MOVE_INDEX_ROLL_DODGE` # 4
--- | `SPECIAL_MOVE_INDEX_SPRINT` # 1

SPECIAL_MOVE_INDEX_BLOCK = 0
SPECIAL_MOVE_INDEX_CROUCH = 2
SPECIAL_MOVE_INDEX_INTERRUPT = 3
SPECIAL_MOVE_INDEX_ROLL_DODGE = 4
SPECIAL_MOVE_INDEX_SPRINT = 1
