--- @meta SpecializedCollectibleType

--- @alias SpecializedCollectibleType integer
--- | `SPECIALIZED_COLLECTIBLE_TYPE_BUST` # 1
--- | `SPECIALIZED_COLLECTIBLE_TYPE_HOUSEGUEST` # 4
--- | `SPECIALIZED_COLLECTIBLE_TYPE_KEEPSAKE` # 3
--- | `SPECIALIZED_COLLECTIBLE_TYPE_NONE` # 0
--- | `SPECIALIZED_COLLECTIBLE_TYPE_TOOL` # 2

SPECIALIZED_COLLECTIBLE_TYPE_BUST = 1
SPECIALIZED_COLLECTIBLE_TYPE_HOUSEGUEST = 4
SPECIALIZED_COLLECTIBLE_TYPE_KEEPSAKE = 3
SPECIALIZED_COLLECTIBLE_TYPE_NONE = 0
SPECIALIZED_COLLECTIBLE_TYPE_TOOL = 2
