--- @meta SprintBlockRule

--- @alias SprintBlockRule integer
--- | `SPRINT_BLOCK_RULE_ALWAYS` # 1
--- | `SPRINT_BLOCK_RULE_NEVER` # 0
--- | `SPRINT_BLOCK_RULE_WHILE_MOUNTED` # 2
--- | `SPRINT_BLOCK_RULE_WHILE_NOT_MOUNTED` # 3

SPRINT_BLOCK_RULE_ALWAYS = 1
SPRINT_BLOCK_RULE_NEVER = 0
SPRINT_BLOCK_RULE_WHILE_MOUNTED = 2
SPRINT_BLOCK_RULE_WHILE_NOT_MOUNTED = 3
