--- @meta StatValueColors

--- @alias StatValueColors integer
--- | `STAT_VALUE_COLOR_BATTLE_LEVELED` # 2
--- | `STAT_VALUE_COLOR_HIGHER` # 1
--- | `STAT_VALUE_COLOR_LOWER` # 0

STAT_VALUE_COLOR_BATTLE_LEVELED = 2
STAT_VALUE_COLOR_HIGHER = 1
STAT_VALUE_COLOR_LOWER = 0
