--- @meta StatusEffectType

--- @alias StatusEffectType integer
--- | `STATUS_EFFECT_TYPE_BLEED` # 3
--- | `STATUS_EFFECT_TYPE_BLIND` # 6
--- | `STATUS_EFFECT_TYPE_CHARM` # 17
--- | `STATUS_EFFECT_TYPE_DAZED` # 12
--- | `STATUS_EFFECT_TYPE_DISEASE` # 8
--- | `STATUS_EFFECT_TYPE_ENVIRONMENT` # 20
--- | `STATUS_EFFECT_TYPE_FEAR` # 15
--- | `STATUS_EFFECT_TYPE_LEVITATE` # 18
--- | `STATUS_EFFECT_TYPE_MAGIC` # 21
--- | `STATUS_EFFECT_TYPE_MESMERIZE` # 16
--- | `STATUS_EFFECT_TYPE_NEARSIGHT` # 7
--- | `STATUS_EFFECT_TYPE_NONE` # 0
--- | `STATUS_EFFECT_TYPE_PACIFY` # 14
--- | `STATUS_EFFECT_TYPE_POISON` # 4
--- | `STATUS_EFFECT_TYPE_PUNCTURE` # 10
--- | `STATUS_EFFECT_TYPE_ROOT` # 1
--- | `STATUS_EFFECT_TYPE_SILENCE` # 13
--- | `STATUS_EFFECT_TYPE_SNARE` # 2
--- | `STATUS_EFFECT_TYPE_STUN` # 19
--- | `STATUS_EFFECT_TYPE_TRAUMA` # 9
--- | `STATUS_EFFECT_TYPE_WEAKNESS` # 5
--- | `STATUS_EFFECT_TYPE_WOUND` # 11

STATUS_EFFECT_TYPE_BLEED = 3
STATUS_EFFECT_TYPE_BLIND = 6
STATUS_EFFECT_TYPE_CHARM = 17
STATUS_EFFECT_TYPE_DAZED = 12
STATUS_EFFECT_TYPE_DISEASE = 8
STATUS_EFFECT_TYPE_ENVIRONMENT = 20
STATUS_EFFECT_TYPE_FEAR = 15
STATUS_EFFECT_TYPE_LEVITATE = 18
STATUS_EFFECT_TYPE_MAGIC = 21
STATUS_EFFECT_TYPE_MESMERIZE = 16
STATUS_EFFECT_TYPE_NEARSIGHT = 7
STATUS_EFFECT_TYPE_NONE = 0
STATUS_EFFECT_TYPE_PACIFY = 14
STATUS_EFFECT_TYPE_POISON = 4
STATUS_EFFECT_TYPE_PUNCTURE = 10
STATUS_EFFECT_TYPE_ROOT = 1
STATUS_EFFECT_TYPE_SILENCE = 13
STATUS_EFFECT_TYPE_SNARE = 2
STATUS_EFFECT_TYPE_STUN = 19
STATUS_EFFECT_TYPE_TRAUMA = 9
STATUS_EFFECT_TYPE_WEAKNESS = 5
STATUS_EFFECT_TYPE_WOUND = 11
