--- @meta StealthState

--- @alias StealthState integer
--- | `STEALTH_STATE_DETECTED` # 1
--- | `STEALTH_STATE_HIDDEN` # 3
--- | `STEALTH_STATE_HIDDEN_ALMOST_DETECTED` # 5
--- | `STEALTH_STATE_HIDING` # 2
--- | `STEALTH_STATE_NONE` # 0
--- | `STEALTH_STATE_STEALTH` # 4
--- | `STEALTH_STATE_STEALTH_ALMOST_DETECTED` # 6

STEALTH_STATE_DETECTED = 1
STEALTH_STATE_HIDDEN = 3
STEALTH_STATE_HIDDEN_ALMOST_DETECTED = 5
STEALTH_STATE_HIDING = 2
STEALTH_STATE_NONE = 0
STEALTH_STATE_STEALTH = 4
STEALTH_STATE_STEALTH_ALMOST_DETECTED = 6
