--- @meta StoreEntryType

--- @alias StoreEntryType integer
--- | `STORE_ENTRY_TYPE_ANTIQUITY_LEAD` # 7
--- | `STORE_ENTRY_TYPE_COLLECTIBLE` # 4
--- | `STORE_ENTRY_TYPE_HOUSE_WITH_TEMPLATE` # 5
--- | `STORE_ENTRY_TYPE_INTERACTABLE` # 2
--- | `STORE_ENTRY_TYPE_ITEM` # 0
--- | `STORE_ENTRY_TYPE_MONSTER` # 1
--- | `STORE_ENTRY_TYPE_QUEST_ITEM` # 3
--- | `STORE_ENTRY_TYPE_SUBSTORE` # 6

STORE_ENTRY_TYPE_ANTIQUITY_LEAD = 7
STORE_ENTRY_TYPE_COLLECTIBLE = 4
STORE_ENTRY_TYPE_HOUSE_WITH_TEMPLATE = 5
STORE_ENTRY_TYPE_INTERACTABLE = 2
STORE_ENTRY_TYPE_ITEM = 0
STORE_ENTRY_TYPE_MONSTER = 1
STORE_ENTRY_TYPE_QUEST_ITEM = 3
STORE_ENTRY_TYPE_SUBSTORE = 6
