--- @meta StoreFailure

--- @alias StoreFailure integer
--- | `STORE_FAILURE_ALREADY_HAVE_ANTIQUITY_LEAD` # 31
--- | `STORE_FAILURE_ALREADY_HAVE_COLLECTIBLE` # 24
--- | `STORE_FAILURE_ALREADY_OWN_COMBINATION_RESULT` # 33
--- | `STORE_FAILURE_ALREADY_UNEARTHED_ANTIQUITY` # 32
--- | `STORE_FAILURE_AT_FENCE_LIMIT` # 23
--- | `STORE_FAILURE_AWARDS_ALREADY_OWNED_COLLECTIBLE` # 29
--- | `STORE_FAILURE_AWARDS_FRAGMENT_OF_ALREADY_OWNED_COLLECTIBLE` # 34
--- | `STORE_FAILURE_BUY_ITEM_FAILED_REQS` # 8
--- | `STORE_FAILURE_CANT_BE_SOLD` # 3
--- | `STORE_FAILURE_CANT_BUY_MULTIPLES` # 6
--- | `STORE_FAILURE_ITEM_BUY_UNIQUE` # 9
--- | `STORE_FAILURE_NOT_ENOUGH_ALLIANCE_POINTS` # 13
--- | `STORE_FAILURE_NOT_ENOUGH_ARCHIVAL_FORTUNES` # 35
--- | `STORE_FAILURE_NOT_ENOUGH_CHAOS_CREATIA` # 26
--- | `STORE_FAILURE_NOT_ENOUGH_EVENT_TICKETS` # 28
--- | `STORE_FAILURE_NOT_ENOUGH_ITEM` # 12
--- | `STORE_FAILURE_NOT_ENOUGH_STABLE_SPACE` # 18
--- | `STORE_FAILURE_NOT_ENOUGH_STYLE_STONES` # 27
--- | `STORE_FAILURE_NOT_ENOUGH_TELVAR_STONES` # 15
--- | `STORE_FAILURE_NOT_ENOUGH_UNDAUNTED_KEYS` # 30
--- | `STORE_FAILURE_NOT_ENOUGH_WRIT_VOUCHERS` # 25
--- | `STORE_FAILURE_NOT_STOLEN` # 20
--- | `STORE_FAILURE_NO_NEED_FOR_QUEST_ITEM` # 5
--- | `STORE_FAILURE_NO_NEED_FOR_THAT_MANY_QUEST_ITEM` # 7
--- | `STORE_FAILURE_SELL_FAILED_MONEY_CAP` # 4
--- | `STORE_FAILURE_STOLEN` # 19
--- | `STORE_FAILURE_WORTHLESS_TO_FENCE` # 22

STORE_FAILURE_ALREADY_HAVE_ANTIQUITY_LEAD = 31
STORE_FAILURE_ALREADY_HAVE_COLLECTIBLE = 24
STORE_FAILURE_ALREADY_OWN_COMBINATION_RESULT = 33
STORE_FAILURE_ALREADY_UNEARTHED_ANTIQUITY = 32
STORE_FAILURE_AT_FENCE_LIMIT = 23
STORE_FAILURE_AWARDS_ALREADY_OWNED_COLLECTIBLE = 29
STORE_FAILURE_AWARDS_FRAGMENT_OF_ALREADY_OWNED_COLLECTIBLE = 34
STORE_FAILURE_BUY_ITEM_FAILED_REQS = 8
STORE_FAILURE_CANT_BE_SOLD = 3
STORE_FAILURE_CANT_BUY_MULTIPLES = 6
STORE_FAILURE_ITEM_BUY_UNIQUE = 9
STORE_FAILURE_NOT_ENOUGH_ALLIANCE_POINTS = 13
STORE_FAILURE_NOT_ENOUGH_ARCHIVAL_FORTUNES = 35
STORE_FAILURE_NOT_ENOUGH_CHAOS_CREATIA = 26
STORE_FAILURE_NOT_ENOUGH_EVENT_TICKETS = 28
STORE_FAILURE_NOT_ENOUGH_ITEM = 12
STORE_FAILURE_NOT_ENOUGH_STABLE_SPACE = 18
STORE_FAILURE_NOT_ENOUGH_STYLE_STONES = 27
STORE_FAILURE_NOT_ENOUGH_TELVAR_STONES = 15
STORE_FAILURE_NOT_ENOUGH_UNDAUNTED_KEYS = 30
STORE_FAILURE_NOT_ENOUGH_WRIT_VOUCHERS = 25
STORE_FAILURE_NOT_STOLEN = 20
STORE_FAILURE_NO_NEED_FOR_QUEST_ITEM = 5
STORE_FAILURE_NO_NEED_FOR_THAT_MANY_QUEST_ITEM = 7
STORE_FAILURE_SELL_FAILED_MONEY_CAP = 4
STORE_FAILURE_STOLEN = 19
STORE_FAILURE_WORTHLESS_TO_FENCE = 22
