--- @meta StoreItemResult

--- @alias StoreItemResult integer
--- | `STORE_ITEM_RESULT_INVALID_ITEM` # 1
--- | `STORE_ITEM_RESULT_INVENTORY_FULL` # 2
--- | `STORE_ITEM_RESULT_IS_UNIQUE` # 3
--- | `STORE_ITEM_RESULT_SUCCESS` # 0

STORE_ITEM_RESULT_INVALID_ITEM = 1
STORE_ITEM_RESULT_INVENTORY_FULL = 2
STORE_ITEM_RESULT_IS_UNIQUE = 3
STORE_ITEM_RESULT_SUCCESS = 0
