--- @meta SubtitleSetting

--- @alias SubtitleSetting integer
--- | `SUBTITLE_SETTING_ENABLED_FOR_NPCS` # 0
--- | `SUBTITLE_SETTING_ENABLED_FOR_VIDEOS` # 1

SUBTITLE_SETTING_ENABLED_FOR_NPCS = 0
SUBTITLE_SETTING_ENABLED_FOR_VIDEOS = 1
