--- @meta TargetMarkerType

--- @alias TargetMarkerType integer
--- | `TARGET_MARKER_TYPE_EIGHT` # 8
--- | `TARGET_MARKER_TYPE_FIVE` # 5
--- | `TARGET_MARKER_TYPE_FOUR` # 4
--- | `TARGET_MARKER_TYPE_NONE` # 0
--- | `TARGET_MARKER_TYPE_ONE` # 1
--- | `TARGET_MARKER_TYPE_SEVEN` # 7
--- | `TARGET_MARKER_TYPE_SIX` # 6
--- | `TARGET_MARKER_TYPE_THREE` # 3
--- | `TARGET_MARKER_TYPE_TWO` # 2

TARGET_MARKER_TYPE_EIGHT = 8
TARGET_MARKER_TYPE_FIVE = 5
TARGET_MARKER_TYPE_FOUR = 4
TARGET_MARKER_TYPE_NONE = 0
TARGET_MARKER_TYPE_ONE = 1
TARGET_MARKER_TYPE_SEVEN = 7
TARGET_MARKER_TYPE_SIX = 6
TARGET_MARKER_TYPE_THREE = 3
TARGET_MARKER_TYPE_TWO = 2
