--- @meta TextType

--- @alias TextType integer
--- | `TEXT_TYPE_ALL` # 0
--- | `TEXT_TYPE_ALPHABETIC` # 4
--- | `TEXT_TYPE_ALPHABETIC_NO_FULLWIDTH_LATIN` # 5
--- | `TEXT_TYPE_NUMERIC` # 2
--- | `TEXT_TYPE_NUMERIC_UNSIGNED_INT` # 3
--- | `TEXT_TYPE_PASSWORD` # 1

TEXT_TYPE_ALL = 0
TEXT_TYPE_ALPHABETIC = 4
TEXT_TYPE_ALPHABETIC_NO_FULLWIDTH_LATIN = 5
TEXT_TYPE_NUMERIC = 2
TEXT_TYPE_NUMERIC_UNSIGNED_INT = 3
TEXT_TYPE_PASSWORD = 1
