--- @meta TimeFormatDirectionCode

--- @alias TimeFormatDirectionCode integer
--- | `TIME_FORMAT_DIRECTION_ASCENDING` # 0
--- | `TIME_FORMAT_DIRECTION_DESCENDING` # 1
--- | `TIME_FORMAT_DIRECTION_NONE` # 2

TIME_FORMAT_DIRECTION_ASCENDING = 0
TIME_FORMAT_DIRECTION_DESCENDING = 1
TIME_FORMAT_DIRECTION_NONE = 2
