--- @meta TimeFormatPrecisionCode

--- @alias TimeFormatPrecisionCode integer
--- | `TIME_FORMAT_PRECISION_MILLISECONDS` # 5
--- | `TIME_FORMAT_PRECISION_MILLISECONDS_NO_HOURS_OR_DAYS` # 6
--- | `TIME_FORMAT_PRECISION_SECONDS` # 0
--- | `TIME_FORMAT_PRECISION_TENTHS` # 1
--- | `TIME_FORMAT_PRECISION_TENTHS_RELEVANT` # 2
--- | `TIME_FORMAT_PRECISION_TWELVE_HOUR` # 3
--- | `TIME_FORMAT_PRECISION_TWELVE_HOUR_NO_SECONDS` # 7
--- | `TIME_FORMAT_PRECISION_TWENTY_FOUR_HOUR` # 4

TIME_FORMAT_PRECISION_MILLISECONDS = 5
TIME_FORMAT_PRECISION_MILLISECONDS_NO_HOURS_OR_DAYS = 6
TIME_FORMAT_PRECISION_SECONDS = 0
TIME_FORMAT_PRECISION_TENTHS = 1
TIME_FORMAT_PRECISION_TENTHS_RELEVANT = 2
TIME_FORMAT_PRECISION_TWELVE_HOUR = 3
TIME_FORMAT_PRECISION_TWELVE_HOUR_NO_SECONDS = 7
TIME_FORMAT_PRECISION_TWENTY_FOUR_HOUR = 4
