--- @meta TimedActivityDifficulty

--- @alias TimedActivityDifficulty integer
--- | `TIMED_ACTIVITY_DIFFICULTY_EASY` # 1
--- | `TIMED_ACTIVITY_DIFFICULTY_HARD` # 3
--- | `TIMED_ACTIVITY_DIFFICULTY_MEDIUM` # 2
--- | `TIMED_ACTIVITY_DIFFICULTY_VERY_EASY` # 0
--- | `TIMED_ACTIVITY_DIFFICULTY_VERY_HARD` # 4

TIMED_ACTIVITY_DIFFICULTY_EASY = 1
TIMED_ACTIVITY_DIFFICULTY_HARD = 3
TIMED_ACTIVITY_DIFFICULTY_MEDIUM = 2
TIMED_ACTIVITY_DIFFICULTY_VERY_EASY = 0
TIMED_ACTIVITY_DIFFICULTY_VERY_HARD = 4
