--- @meta TimeFormatStyleCode

--- @alias TimeFormatStyleCode integer
--- | `TIME_FORMAT_STYLE_CAST_TIME` # 4
--- | `TIME_FORMAT_STYLE_CHANNEL_TIME` # 6
--- | `TIME_FORMAT_STYLE_CLOCK_TIME` # 11
--- | `TIME_FORMAT_STYLE_COLONS` # 0
--- | `TIME_FORMAT_STYLE_COOLDOWN_TIME` # 5
--- | `TIME_FORMAT_STYLE_DESCRIPTIVE` # 7
--- | `TIME_FORMAT_STYLE_DESCRIPTIVE_MINIMAL` # 14
--- | `TIME_FORMAT_STYLE_DESCRIPTIVE_MINIMAL_HIDE_ZEROES` # 16
--- | `TIME_FORMAT_STYLE_DESCRIPTIVE_MINIMAL_SHOW_TENTHS_SECS` # 15
--- | `TIME_FORMAT_STYLE_DESCRIPTIVE_SHORT` # 8
--- | `TIME_FORMAT_STYLE_DESCRIPTIVE_SHORT_SHOW_ZERO_SECS` # 9
--- | `TIME_FORMAT_STYLE_DURATION` # 12
--- | `TIME_FORMAT_STYLE_RELATIVE_TIMESTAMP` # 10
--- | `TIME_FORMAT_STYLE_SHOW_LARGEST_TWO_UNITS` # 17
--- | `TIME_FORMAT_STYLE_SHOW_LARGEST_UNIT` # 1
--- | `TIME_FORMAT_STYLE_SHOW_LARGEST_UNIT_DESCRIPTIVE` # 2
--- | `TIME_FORMAT_STYLE_SHOW_LARGEST_UNIT_DESCRIPTIVE_COLOR` # 13
--- | `TIME_FORMAT_STYLE_SHOW_LARGEST_UNIT_DESCRIPTIVE_SHORT` # 3

TIME_FORMAT_STYLE_CAST_TIME = 4
TIME_FORMAT_STYLE_CHANNEL_TIME = 6
TIME_FORMAT_STYLE_CLOCK_TIME = 11
TIME_FORMAT_STYLE_COLONS = 0
TIME_FORMAT_STYLE_COOLDOWN_TIME = 5
TIME_FORMAT_STYLE_DESCRIPTIVE = 7
TIME_FORMAT_STYLE_DESCRIPTIVE_MINIMAL = 14
TIME_FORMAT_STYLE_DESCRIPTIVE_MINIMAL_HIDE_ZEROES = 16
TIME_FORMAT_STYLE_DESCRIPTIVE_MINIMAL_SHOW_TENTHS_SECS = 15
TIME_FORMAT_STYLE_DESCRIPTIVE_SHORT = 8
TIME_FORMAT_STYLE_DESCRIPTIVE_SHORT_SHOW_ZERO_SECS = 9
TIME_FORMAT_STYLE_DURATION = 12
TIME_FORMAT_STYLE_RELATIVE_TIMESTAMP = 10
TIME_FORMAT_STYLE_SHOW_LARGEST_TWO_UNITS = 17
TIME_FORMAT_STYLE_SHOW_LARGEST_UNIT = 1
TIME_FORMAT_STYLE_SHOW_LARGEST_UNIT_DESCRIPTIVE = 2
TIME_FORMAT_STYLE_SHOW_LARGEST_UNIT_DESCRIPTIVE_COLOR = 13
TIME_FORMAT_STYLE_SHOW_LARGEST_UNIT_DESCRIPTIVE_SHORT = 3
