--- @meta TooltipGameDataType

--- @alias TooltipGameDataType integer
--- | `TOOLTIP_GAME_DATA_CHAMPION_PROGRESSION` # 9
--- | `TOOLTIP_GAME_DATA_CHARGES` # 2
--- | `TOOLTIP_GAME_DATA_CONDITION` # 6
--- | `TOOLTIP_GAME_DATA_DIVIDER` # 3
--- | `TOOLTIP_GAME_DATA_EQUIPPED_INFO` # 4
--- | `TOOLTIP_GAME_DATA_ITEM_ICON` # 7
--- | `TOOLTIP_GAME_DATA_MYTHIC_OR_STOLEN` # 8
--- | `TOOLTIP_GAME_DATA_NONE` # 0
--- | `TOOLTIP_GAME_DATA_PROGRESSION` # 5
--- | `TOOLTIP_GAME_DATA_SKILL_UPGRADE` # 1

TOOLTIP_GAME_DATA_CHAMPION_PROGRESSION = 9
TOOLTIP_GAME_DATA_CHARGES = 2
TOOLTIP_GAME_DATA_CONDITION = 6
TOOLTIP_GAME_DATA_DIVIDER = 3
TOOLTIP_GAME_DATA_EQUIPPED_INFO = 4
TOOLTIP_GAME_DATA_ITEM_ICON = 7
TOOLTIP_GAME_DATA_MYTHIC_OR_STOLEN = 8
TOOLTIP_GAME_DATA_NONE = 0
TOOLTIP_GAME_DATA_PROGRESSION = 5
TOOLTIP_GAME_DATA_SKILL_UPGRADE = 1
