--- @meta TrackerGoalTextError

--- @alias TrackerGoalTextError integer
--- | `TRACKER_GOAL_DEFAULT_TEXT_ERROR_DEFAULT_TRACKER_GOAL_TEXT` # 0
--- | `TRACKER_GOAL_DEFAULT_TEXT_ERROR_PLAYER_DIED` # 2
--- | `TRACKER_GOAL_DEFAULT_TEXT_ERROR_PLAYER_LOGOFF` # 1

TRACKER_GOAL_DEFAULT_TEXT_ERROR_DEFAULT_TRACKER_GOAL_TEXT = 0
TRACKER_GOAL_DEFAULT_TEXT_ERROR_PLAYER_DIED = 2
TRACKER_GOAL_DEFAULT_TEXT_ERROR_PLAYER_LOGOFF = 1
