--- @meta TrackingLevel

--- @alias TrackingLevel integer
--- | `TRACKING_LEVEL_ASSISTED` # 2
--- | `TRACKING_LEVEL_TRACKED` # 1
--- | `TRACKING_LEVEL_UNTRACKED` # 0

TRACKING_LEVEL_ASSISTED = 2
TRACKING_LEVEL_TRACKED = 1
TRACKING_LEVEL_UNTRACKED = 0
