--- @meta TradeState

--- @alias TradeState integer
--- | `TRADE_STATE_IDLE` # 0
--- | `TRADE_STATE_INVITE_CONSIDERING` # 2
--- | `TRADE_STATE_INVITE_WAITING` # 1
--- | `TRADE_STATE_TRADING` # 3

TRADE_STATE_IDLE = 0
TRADE_STATE_INVITE_CONSIDERING = 2
TRADE_STATE_INVITE_WAITING = 1
TRADE_STATE_TRADING = 3
