--- @meta TradingHouseFeatureCategory

--- @alias TradingHouseFeatureCategory integer
--- | `TRADING_HOUSE_FEATURE_CATEGORY_ENCHANTMENT` # 4
--- | `TRADING_HOUSE_FEATURE_CATEGORY_ITEM_CATEGORY` # 1
--- | `TRADING_HOUSE_FEATURE_CATEGORY_LEVEL_RANGE` # 2
--- | `TRADING_HOUSE_FEATURE_CATEGORY_NAME_SEARCH` # 0
--- | `TRADING_HOUSE_FEATURE_CATEGORY_PRICE_RANGE` # 6
--- | `TRADING_HOUSE_FEATURE_CATEGORY_QUALITY` # 5
--- | `TRADING_HOUSE_FEATURE_CATEGORY_TRAIT` # 3

TRADING_HOUSE_FEATURE_CATEGORY_ENCHANTMENT = 4
TRADING_HOUSE_FEATURE_CATEGORY_ITEM_CATEGORY = 1
TRADING_HOUSE_FEATURE_CATEGORY_LEVEL_RANGE = 2
TRADING_HOUSE_FEATURE_CATEGORY_NAME_SEARCH = 0
TRADING_HOUSE_FEATURE_CATEGORY_PRICE_RANGE = 6
TRADING_HOUSE_FEATURE_CATEGORY_QUALITY = 5
TRADING_HOUSE_FEATURE_CATEGORY_TRAIT = 3
