--- @meta TradeskillResult

--- @alias TradeskillResult integer
--- | `CRAFTING_RESULT_ALREADY_RESEARCHING` # 126
--- | `CRAFTING_RESULT_BUSY` # 103
--- | `CRAFTING_RESULT_CANNOT_AFFORD` # 19
--- | `CRAFTING_RESULT_CANNOT_RESEARCH_RETRAITED_ITEM` # 128
--- | `CRAFTING_RESULT_CANT_DECONSTRUCT_WORN` # 127
--- | `CRAFTING_RESULT_CRAFT_SUCCESS` # 1
--- | `CRAFTING_RESULT_DECONSTRUCT_BAD_QUANTITY` # 116
--- | `CRAFTING_RESULT_DECONSTRUCT_SUCCESS` # 2
--- | `CRAFTING_RESULT_EMPTY_SCRIPT_SLOT` # 151
--- | `CRAFTING_RESULT_FAILED_TO_ADD_CRAFTING_RESULT` # 133
--- | `CRAFTING_RESULT_FAIL_MATERIAL_REQUIREMENTS` # 140
--- | `CRAFTING_RESULT_FAIL_PATTERN_REQUIREMENTS` # 124
--- | `CRAFTING_RESULT_GRIMOIRE_DISABLED` # 152
--- | `CRAFTING_RESULT_IMPROVE_FAILED` # 119
--- | `CRAFTING_RESULT_INTERNAL_ERROR` # 5
--- | `CRAFTING_RESULT_INTERRUPTED` # 18
--- | `CRAFTING_RESULT_INVALID_ALCHEMY_INGREDIENT` # 137
--- | `CRAFTING_RESULT_INVALID_BASE` # 104
--- | `CRAFTING_RESULT_INVALID_CRAFTING_RESULT` # 132
--- | `CRAFTING_RESULT_INVALID_GRIMOIRE` # 145
--- | `CRAFTING_RESULT_INVALID_MATERIAL` # 112
--- | `CRAFTING_RESULT_INVALID_PATTERN` # 113
--- | `CRAFTING_RESULT_INVALID_REAGENT` # 106
--- | `CRAFTING_RESULT_INVALID_RESEARCH` # 122
--- | `CRAFTING_RESULT_INVALID_RESEARCH_TRADESKILL` # 121
--- | `CRAFTING_RESULT_INVALID_RUNE` # 109
--- | `CRAFTING_RESULT_INVALID_SCRIBING_COMBINATION` # 149
--- | `CRAFTING_RESULT_INVALID_SCRIPT` # 147
--- | `CRAFTING_RESULT_INVALID_STYLE_MATERIAL` # 114
--- | `CRAFTING_RESULT_INVALID_TRAIT_MATERIAL` # 115
--- | `CRAFTING_RESULT_INVENTORY_FULL` # 6
--- | `CRAFTING_RESULT_ITEM_CRAFT_UNIQUE` # 12
--- | `CRAFTING_RESULT_ITEM_NOT_DECONSTRUCTABLE` # 30
--- | `CRAFTING_RESULT_ITEM_NOT_IMPROVABLE` # 118
--- | `CRAFTING_RESULT_ITEM_NOT_REFINEABLE` # 70
--- | `CRAFTING_RESULT_ITEM_NOT_RESEARCHABLE` # 129
--- | `CRAFTING_RESULT_MUST_LEARN_STYLE` # 138
--- | `CRAFTING_RESULT_MUST_LEARN_TRAIT` # 120
--- | `CRAFTING_RESULT_NEEDS_SMITHING_MATERIAL` # 141
--- | `CRAFTING_RESULT_NEEDS_STYLE_MATERIAL` # 142
--- | `CRAFTING_RESULT_NEEDS_TRAIT_MATERIAL` # 143
--- | `CRAFTING_RESULT_NEED_BASE_RANK` # 105
--- | `CRAFTING_RESULT_NEED_COMPONENTS_FOR_CRAFT` # 14
--- | `CRAFTING_RESULT_NEED_DECONSTRUCT_RANK` # 35
--- | `CRAFTING_RESULT_NEED_ENCHANTING_QUALITY_RANK` # 111
--- | `CRAFTING_RESULT_NEED_ENCHANTING_RANK` # 110
--- | `CRAFTING_RESULT_NEED_ITEM_TO_RESEARCH` # 125
--- | `CRAFTING_RESULT_NEED_RANK_FOR_CRAFT` # 17
--- | `CRAFTING_RESULT_NEED_RECIPE_QUALITY_RANK` # 102
--- | `CRAFTING_RESULT_NEED_RECIPE_RANK` # 101
--- | `CRAFTING_RESULT_NEED_REFINE_RANK` # 74
--- | `CRAFTING_RESULT_NEED_REQUIREMENTS_FOR_CRAFT` # 16
--- | `CRAFTING_RESULT_NEED_UNLOCK_TO_DECONSTRUCT` # 33
--- | `CRAFTING_RESULT_NEED_UNLOCK_TO_RESEARCH` # 131
--- | `CRAFTING_RESULT_NOT_HOUSE_OWNER` # 80
--- | `CRAFTING_RESULT_NO_ITEM_TO_DECONSTRUCT` # 32
--- | `CRAFTING_RESULT_NO_ITEM_TO_REFINE` # 72
--- | `CRAFTING_RESULT_NO_ITEM_TO_RESEARCH` # 130
--- | `CRAFTING_RESULT_NO_MATCH` # 9
--- | `CRAFTING_RESULT_NO_RECIPE` # 144
--- | `CRAFTING_RESULT_NO_RESULT` # 0
--- | `CRAFTING_RESULT_REFINE_SUCCESS` # 3
--- | `CRAFTING_RESULT_SCRIBING_DISABLED` # 153
--- | `CRAFTING_RESULT_SKILL_UNCHANGED` # 150
--- | `CRAFTING_RESULT_SOME_STATIONS_NOT_CONSUMED` # 81
--- | `CRAFTING_RESULT_TOO_FEW_REAGENTS` # 107
--- | `CRAFTING_RESULT_TOO_LOW_LEVEL_FOR_STYLE` # 139
--- | `CRAFTING_RESULT_TOO_MANY_CRAFTING_INPUTS` # 135
--- | `CRAFTING_RESULT_TOO_MANY_CRAFTING_ITERATIONS` # 134
--- | `CRAFTING_RESULT_TOO_MANY_CRAFTING_RESULTS` # 136
--- | `CRAFTING_RESULT_TOO_MANY_REAGENTS` # 108
--- | `CRAFTING_RESULT_TOO_MANY_RESEARCH` # 123
--- | `CRAFTING_RESULT_UNKNOWN_RECIPE` # 100
--- | `CRAFTING_RESULT_UNKNOWN_SKILL_DECONSTRUCT` # 34
--- | `CRAFTING_RESULT_UNKNOWN_SKILL_REFINE` # 73
--- | `CRAFTING_RESULT_UNOWNED_GRIMOIRE` # 146
--- | `CRAFTING_RESULT_UNOWNED_SCRIPT` # 148
--- | `CRAFTING_RESULT_WRONG_ADDITIVE_CATEGORY` # 10
--- | `CRAFTING_RESULT_WRONG_BOOSTER` # 117
--- | `CRAFTING_RESULT_WRONG_STYLE_CRAFT` # 21
--- | `CRAFTING_RESULT_WRONG_TARGET_CRAFT` # 20
--- | `CRAFTING_RESULT_WRONG_TARGET_DECONSTRUCT` # 31
--- | `CRAFTING_RESULT_WRONG_TARGET_REFINE` # 71
--- | `CRAFTING_RESULT_WRONG_TRADESKILL_FOR_CRAFT` # 13

CRAFTING_RESULT_ALREADY_RESEARCHING = 126
CRAFTING_RESULT_BUSY = 103
CRAFTING_RESULT_CANNOT_AFFORD = 19
CRAFTING_RESULT_CANNOT_RESEARCH_RETRAITED_ITEM = 128
CRAFTING_RESULT_CANT_DECONSTRUCT_WORN = 127
CRAFTING_RESULT_CRAFT_SUCCESS = 1
CRAFTING_RESULT_DECONSTRUCT_BAD_QUANTITY = 116
CRAFTING_RESULT_DECONSTRUCT_SUCCESS = 2
CRAFTING_RESULT_EMPTY_SCRIPT_SLOT = 151
CRAFTING_RESULT_FAILED_TO_ADD_CRAFTING_RESULT = 133
CRAFTING_RESULT_FAIL_MATERIAL_REQUIREMENTS = 140
CRAFTING_RESULT_FAIL_PATTERN_REQUIREMENTS = 124
CRAFTING_RESULT_GRIMOIRE_DISABLED = 152
CRAFTING_RESULT_IMPROVE_FAILED = 119
CRAFTING_RESULT_INTERNAL_ERROR = 5
CRAFTING_RESULT_INTERRUPTED = 18
CRAFTING_RESULT_INVALID_ALCHEMY_INGREDIENT = 137
CRAFTING_RESULT_INVALID_BASE = 104
CRAFTING_RESULT_INVALID_CRAFTING_RESULT = 132
CRAFTING_RESULT_INVALID_GRIMOIRE = 145
CRAFTING_RESULT_INVALID_MATERIAL = 112
CRAFTING_RESULT_INVALID_PATTERN = 113
CRAFTING_RESULT_INVALID_REAGENT = 106
CRAFTING_RESULT_INVALID_RESEARCH = 122
CRAFTING_RESULT_INVALID_RESEARCH_TRADESKILL = 121
CRAFTING_RESULT_INVALID_RUNE = 109
CRAFTING_RESULT_INVALID_SCRIBING_COMBINATION = 149
CRAFTING_RESULT_INVALID_SCRIPT = 147
CRAFTING_RESULT_INVALID_STYLE_MATERIAL = 114
CRAFTING_RESULT_INVALID_TRAIT_MATERIAL = 115
CRAFTING_RESULT_INVENTORY_FULL = 6
CRAFTING_RESULT_ITEM_CRAFT_UNIQUE = 12
CRAFTING_RESULT_ITEM_NOT_DECONSTRUCTABLE = 30
CRAFTING_RESULT_ITEM_NOT_IMPROVABLE = 118
CRAFTING_RESULT_ITEM_NOT_REFINEABLE = 70
CRAFTING_RESULT_ITEM_NOT_RESEARCHABLE = 129
CRAFTING_RESULT_MUST_LEARN_STYLE = 138
CRAFTING_RESULT_MUST_LEARN_TRAIT = 120
CRAFTING_RESULT_NEEDS_SMITHING_MATERIAL = 141
CRAFTING_RESULT_NEEDS_STYLE_MATERIAL = 142
CRAFTING_RESULT_NEEDS_TRAIT_MATERIAL = 143
CRAFTING_RESULT_NEED_BASE_RANK = 105
CRAFTING_RESULT_NEED_COMPONENTS_FOR_CRAFT = 14
CRAFTING_RESULT_NEED_DECONSTRUCT_RANK = 35
CRAFTING_RESULT_NEED_ENCHANTING_QUALITY_RANK = 111
CRAFTING_RESULT_NEED_ENCHANTING_RANK = 110
CRAFTING_RESULT_NEED_ITEM_TO_RESEARCH = 125
CRAFTING_RESULT_NEED_RANK_FOR_CRAFT = 17
CRAFTING_RESULT_NEED_RECIPE_QUALITY_RANK = 102
CRAFTING_RESULT_NEED_RECIPE_RANK = 101
CRAFTING_RESULT_NEED_REFINE_RANK = 74
CRAFTING_RESULT_NEED_REQUIREMENTS_FOR_CRAFT = 16
CRAFTING_RESULT_NEED_UNLOCK_TO_DECONSTRUCT = 33
CRAFTING_RESULT_NEED_UNLOCK_TO_RESEARCH = 131
CRAFTING_RESULT_NOT_HOUSE_OWNER = 80
CRAFTING_RESULT_NO_ITEM_TO_DECONSTRUCT = 32
CRAFTING_RESULT_NO_ITEM_TO_REFINE = 72
CRAFTING_RESULT_NO_ITEM_TO_RESEARCH = 130
CRAFTING_RESULT_NO_MATCH = 9
CRAFTING_RESULT_NO_RECIPE = 144
CRAFTING_RESULT_NO_RESULT = 0
CRAFTING_RESULT_REFINE_SUCCESS = 3
CRAFTING_RESULT_SCRIBING_DISABLED = 153
CRAFTING_RESULT_SKILL_UNCHANGED = 150
CRAFTING_RESULT_SOME_STATIONS_NOT_CONSUMED = 81
CRAFTING_RESULT_TOO_FEW_REAGENTS = 107
CRAFTING_RESULT_TOO_LOW_LEVEL_FOR_STYLE = 139
CRAFTING_RESULT_TOO_MANY_CRAFTING_INPUTS = 135
CRAFTING_RESULT_TOO_MANY_CRAFTING_ITERATIONS = 134
CRAFTING_RESULT_TOO_MANY_CRAFTING_RESULTS = 136
CRAFTING_RESULT_TOO_MANY_REAGENTS = 108
CRAFTING_RESULT_TOO_MANY_RESEARCH = 123
CRAFTING_RESULT_UNKNOWN_RECIPE = 100
CRAFTING_RESULT_UNKNOWN_SKILL_DECONSTRUCT = 34
CRAFTING_RESULT_UNKNOWN_SKILL_REFINE = 73
CRAFTING_RESULT_UNOWNED_GRIMOIRE = 146
CRAFTING_RESULT_UNOWNED_SCRIPT = 148
CRAFTING_RESULT_WRONG_ADDITIVE_CATEGORY = 10
CRAFTING_RESULT_WRONG_BOOSTER = 117
CRAFTING_RESULT_WRONG_STYLE_CRAFT = 21
CRAFTING_RESULT_WRONG_TARGET_CRAFT = 20
CRAFTING_RESULT_WRONG_TARGET_DECONSTRUCT = 31
CRAFTING_RESULT_WRONG_TARGET_REFINE = 71
CRAFTING_RESULT_WRONG_TRADESKILL_FOR_CRAFT = 13
