--- @meta TradeskillType

--- @alias TradeskillType integer
--- | `CRAFTING_TYPE_ALCHEMY` # 4
--- | `CRAFTING_TYPE_BLACKSMITHING` # 1
--- | `CRAFTING_TYPE_CLOTHIER` # 2
--- | `CRAFTING_TYPE_ENCHANTING` # 3
--- | `CRAFTING_TYPE_INVALID` # 0
--- | `CRAFTING_TYPE_JEWELRYCRAFTING` # 7
--- | `CRAFTING_TYPE_PROVISIONING` # 5
--- | `CRAFTING_TYPE_SCRIBING` # 8
--- | `CRAFTING_TYPE_WOODWORKING` # 6

CRAFTING_TYPE_ALCHEMY = 4
CRAFTING_TYPE_BLACKSMITHING = 1
CRAFTING_TYPE_CLOTHIER = 2
CRAFTING_TYPE_ENCHANTING = 3
CRAFTING_TYPE_INVALID = 0
CRAFTING_TYPE_JEWELRYCRAFTING = 7
CRAFTING_TYPE_PROVISIONING = 5
CRAFTING_TYPE_SCRIBING = 8
CRAFTING_TYPE_WOODWORKING = 6
