--- @meta TradingHouseCategoryHeader

--- @alias TradingHouseCategoryHeader integer
--- | `TRADING_HOUSE_CATEGORY_HEADER_ALL_ITEMS` # 0
--- | `TRADING_HOUSE_CATEGORY_HEADER_APPAREL` # 2
--- | `TRADING_HOUSE_CATEGORY_HEADER_COMPANION_EQUIPMENT` # 9
--- | `TRADING_HOUSE_CATEGORY_HEADER_CONSUMABLES` # 3
--- | `TRADING_HOUSE_CATEGORY_HEADER_FURNISHINGS` # 6
--- | `TRADING_HOUSE_CATEGORY_HEADER_GLYPHS` # 5
--- | `TRADING_HOUSE_CATEGORY_HEADER_JEWELRY` # 8
--- | `TRADING_HOUSE_CATEGORY_HEADER_MATERIALS` # 4
--- | `TRADING_HOUSE_CATEGORY_HEADER_MISC` # 7
--- | `TRADING_HOUSE_CATEGORY_HEADER_WEAPONS` # 1

TRADING_HOUSE_CATEGORY_HEADER_ALL_ITEMS = 0
TRADING_HOUSE_CATEGORY_HEADER_APPAREL = 2
TRADING_HOUSE_CATEGORY_HEADER_COMPANION_EQUIPMENT = 9
TRADING_HOUSE_CATEGORY_HEADER_CONSUMABLES = 3
TRADING_HOUSE_CATEGORY_HEADER_FURNISHINGS = 6
TRADING_HOUSE_CATEGORY_HEADER_GLYPHS = 5
TRADING_HOUSE_CATEGORY_HEADER_JEWELRY = 8
TRADING_HOUSE_CATEGORY_HEADER_MATERIALS = 4
TRADING_HOUSE_CATEGORY_HEADER_MISC = 7
TRADING_HOUSE_CATEGORY_HEADER_WEAPONS = 1
