--- @meta TradingHouseListingSortType

--- @alias TradingHouseListingSortType integer
--- | `TRADING_HOUSE_LISTING_SORT_TYPE_NAME` # 2
--- | `TRADING_HOUSE_LISTING_SORT_TYPE_PRICE` # 1
--- | `TRADING_HOUSE_LISTING_SORT_TYPE_TIME` # 0

TRADING_HOUSE_LISTING_SORT_TYPE_NAME = 2
TRADING_HOUSE_LISTING_SORT_TYPE_PRICE = 1
TRADING_HOUSE_LISTING_SORT_TYPE_TIME = 0
