--- @meta TradingHouseSortField

--- @alias TradingHouseSortField integer
--- | `TRADING_HOUSE_SORT_EXPIRY_TIME` # 1
--- | `TRADING_HOUSE_SORT_SALE_PRICE` # 2
--- | `TRADING_HOUSE_SORT_SALE_PRICE_PER_UNIT` # 3

TRADING_HOUSE_SORT_EXPIRY_TIME = 1
TRADING_HOUSE_SORT_SALE_PRICE = 2
TRADING_HOUSE_SORT_SALE_PRICE_PER_UNIT = 3
