--- @meta TradingHouseSearchState

--- @alias TradingHouseSearchState integer
--- | `TRADING_HOUSE_SEARCH_STATE_COMPLETE` # 2
--- | `TRADING_HOUSE_SEARCH_STATE_NONE` # 0
--- | `TRADING_HOUSE_SEARCH_STATE_WAITING` # 1

TRADING_HOUSE_SEARCH_STATE_COMPLETE = 2
TRADING_HOUSE_SEARCH_STATE_NONE = 0
TRADING_HOUSE_SEARCH_STATE_WAITING = 1
