--- @meta TradeActionResult

--- @alias TradeActionResult integer
--- | `TRADE_ACTION_RESULT_ADD_ITEM_DUPLICATE` # 65
--- | `TRADE_ACTION_RESULT_DISABLED` # 80
--- | `TRADE_ACTION_RESULT_IGNORING_YOU` # 1
--- | `TRADE_ACTION_RESULT_INVALID_TRADE_SLOT` # 61
--- | `TRADE_ACTION_RESULT_ITEM_ADD_LOCKED` # 62
--- | `TRADE_ACTION_RESULT_ITEM_IS_BOUND` # 63
--- | `TRADE_ACTION_RESULT_ITEM_IS_STOLEN` # 66
--- | `TRADE_ACTION_RESULT_ITEM_UNIQUE_FROM_OTHER` # 45
--- | `TRADE_ACTION_RESULT_NEED_ALLIANCE_FOR_TRADE` # 8
--- | `TRADE_ACTION_RESULT_NEED_PLAYER_FOR_TRADE` # 7
--- | `TRADE_ACTION_RESULT_NOT_CONSIDERING_TRADE_INVITE` # 10
--- | `TRADE_ACTION_RESULT_NOT_ENOUGH_EMPTY_SLOTS` # 46
--- | `TRADE_ACTION_RESULT_NOT_ENOUGH_SLOTS` # 64
--- | `TRADE_ACTION_RESULT_NOT_TRADING` # 20
--- | `TRADE_ACTION_RESULT_NOT_WAITING_TRADE_INVITE` # 11
--- | `TRADE_ACTION_RESULT_OTHER_HAS_TOO_MUCH_MONEY` # 44
--- | `TRADE_ACTION_RESULT_OTHER_IS_MISSING_MONEY` # 42
--- | `TRADE_ACTION_RESULT_OTHER_PLAYER_MISSING` # 21
--- | `TRADE_ACTION_RESULT_PARTICIPANT_IS_DEAD` # 14
--- | `TRADE_ACTION_RESULT_SUCCESS` # 40
--- | `TRADE_ACTION_RESULT_TARGET_IS_TRADING` # 9
--- | `TRADE_ACTION_RESULT_TOO_FAR_TO_TRADE` # 6
--- | `TRADE_ACTION_RESULT_TRADE_INVITE_ALREADY_SENT` # 0
--- | `TRADE_ACTION_RESULT_TRADE_INVITE_FAILED` # 12
--- | `TRADE_ACTION_RESULT_TRADE_INVITE_PENDING` # 2
--- | `TRADE_ACTION_RESULT_TRADE_INVITE_WHEN_ACTIVE` # 3
--- | `TRADE_ACTION_RESULT_TRADE_SELF_ERROR` # 5
--- | `TRADE_ACTION_RESULT_TRADE_TARGET_REQUIRED` # 4
--- | `TRADE_ACTION_RESULT_UKNOWN_ITEM` # 60
--- | `TRADE_ACTION_RESULT_YOU_ARE_BUSY` # 13
--- | `TRADE_ACTION_RESULT_YOU_ARE_MISSING_MONEY` # 41
--- | `TRADE_ACTION_RESULT_YOU_HAVE_TOO_MUCH_MONEY` # 43

TRADE_ACTION_RESULT_ADD_ITEM_DUPLICATE = 65
TRADE_ACTION_RESULT_DISABLED = 80
TRADE_ACTION_RESULT_IGNORING_YOU = 1
TRADE_ACTION_RESULT_INVALID_TRADE_SLOT = 61
TRADE_ACTION_RESULT_ITEM_ADD_LOCKED = 62
TRADE_ACTION_RESULT_ITEM_IS_BOUND = 63
TRADE_ACTION_RESULT_ITEM_IS_STOLEN = 66
TRADE_ACTION_RESULT_ITEM_UNIQUE_FROM_OTHER = 45
TRADE_ACTION_RESULT_NEED_ALLIANCE_FOR_TRADE = 8
TRADE_ACTION_RESULT_NEED_PLAYER_FOR_TRADE = 7
TRADE_ACTION_RESULT_NOT_CONSIDERING_TRADE_INVITE = 10
TRADE_ACTION_RESULT_NOT_ENOUGH_EMPTY_SLOTS = 46
TRADE_ACTION_RESULT_NOT_ENOUGH_SLOTS = 64
TRADE_ACTION_RESULT_NOT_TRADING = 20
TRADE_ACTION_RESULT_NOT_WAITING_TRADE_INVITE = 11
TRADE_ACTION_RESULT_OTHER_HAS_TOO_MUCH_MONEY = 44
TRADE_ACTION_RESULT_OTHER_IS_MISSING_MONEY = 42
TRADE_ACTION_RESULT_OTHER_PLAYER_MISSING = 21
TRADE_ACTION_RESULT_PARTICIPANT_IS_DEAD = 14
TRADE_ACTION_RESULT_SUCCESS = 40
TRADE_ACTION_RESULT_TARGET_IS_TRADING = 9
TRADE_ACTION_RESULT_TOO_FAR_TO_TRADE = 6
TRADE_ACTION_RESULT_TRADE_INVITE_ALREADY_SENT = 0
TRADE_ACTION_RESULT_TRADE_INVITE_FAILED = 12
TRADE_ACTION_RESULT_TRADE_INVITE_PENDING = 2
TRADE_ACTION_RESULT_TRADE_INVITE_WHEN_ACTIVE = 3
TRADE_ACTION_RESULT_TRADE_SELF_ERROR = 5
TRADE_ACTION_RESULT_TRADE_TARGET_REQUIRED = 4
TRADE_ACTION_RESULT_UKNOWN_ITEM = 60
TRADE_ACTION_RESULT_YOU_ARE_BUSY = 13
TRADE_ACTION_RESULT_YOU_ARE_MISSING_MONEY = 41
TRADE_ACTION_RESULT_YOU_HAVE_TOO_MUCH_MONEY = 43
