--- @meta TradingHouseResult

--- @alias TradingHouseResult integer
--- | `TRADING_HOUSE_RESULT_AWAITING_INITIAL_STATUS` # 17
--- | `TRADING_HOUSE_RESULT_CANCEL_SALE_PENDING` # 20
--- | `TRADING_HOUSE_RESULT_CANT_AFFORD_BUYPRICE` # 13
--- | `TRADING_HOUSE_RESULT_CANT_AFFORD_POST_FEE` # 7
--- | `TRADING_HOUSE_RESULT_CANT_BUY_YOUR_OWN_POSTS` # 19
--- | `TRADING_HOUSE_RESULT_CANT_POST_BOUND` # 6
--- | `TRADING_HOUSE_RESULT_CANT_POST_FROM_THAT_BAG` # 9
--- | `TRADING_HOUSE_RESULT_CANT_POST_LOCKED` # 25
--- | `TRADING_HOUSE_RESULT_CANT_POST_STOLEN` # 23
--- | `TRADING_HOUSE_RESULT_CANT_SELL_FOR_FREE` # 21
--- | `TRADING_HOUSE_RESULT_CANT_SELL_FOR_OVER_MAX_AMOUNT` # 22
--- | `TRADING_HOUSE_RESULT_CANT_SWITCH_GUILDS_WHILE_AWAITING_RESPONSE` # 16
--- | `TRADING_HOUSE_RESULT_GUILD_TOO_SMALL` # 12
--- | `TRADING_HOUSE_RESULT_INVALID_GUILD_ID` # 10
--- | `TRADING_HOUSE_RESULT_ITEM_NOT_FOUND` # 5
--- | `TRADING_HOUSE_RESULT_LISTINGS_PENDING` # 15
--- | `TRADING_HOUSE_RESULT_NAME_MATCH_PENDING` # 26
--- | `TRADING_HOUSE_RESULT_NOT_A_MEMBER` # 2
--- | `TRADING_HOUSE_RESULT_NOT_IN_A_GUILD` # 24
--- | `TRADING_HOUSE_RESULT_NOT_OPEN` # 1
--- | `TRADING_HOUSE_RESULT_NO_NAME_SEARCH_DATA` # 27
--- | `TRADING_HOUSE_RESULT_NO_PERMISSION` # 11
--- | `TRADING_HOUSE_RESULT_POST_PENDING` # 4
--- | `TRADING_HOUSE_RESULT_PURCHASE_PENDING` # 18
--- | `TRADING_HOUSE_RESULT_QUEUED_POST` # 28
--- | `TRADING_HOUSE_RESULT_SEARCH_PENDING` # 14
--- | `TRADING_HOUSE_RESULT_SEARCH_RATE_EXCEEDED` # 8
--- | `TRADING_HOUSE_RESULT_SUCCESS` # 0
--- | `TRADING_HOUSE_RESULT_TOO_MANY_POSTS` # 3

TRADING_HOUSE_RESULT_AWAITING_INITIAL_STATUS = 17
TRADING_HOUSE_RESULT_CANCEL_SALE_PENDING = 20
TRADING_HOUSE_RESULT_CANT_AFFORD_BUYPRICE = 13
TRADING_HOUSE_RESULT_CANT_AFFORD_POST_FEE = 7
TRADING_HOUSE_RESULT_CANT_BUY_YOUR_OWN_POSTS = 19
TRADING_HOUSE_RESULT_CANT_POST_BOUND = 6
TRADING_HOUSE_RESULT_CANT_POST_FROM_THAT_BAG = 9
TRADING_HOUSE_RESULT_CANT_POST_LOCKED = 25
TRADING_HOUSE_RESULT_CANT_POST_STOLEN = 23
TRADING_HOUSE_RESULT_CANT_SELL_FOR_FREE = 21
TRADING_HOUSE_RESULT_CANT_SELL_FOR_OVER_MAX_AMOUNT = 22
TRADING_HOUSE_RESULT_CANT_SWITCH_GUILDS_WHILE_AWAITING_RESPONSE = 16
TRADING_HOUSE_RESULT_GUILD_TOO_SMALL = 12
TRADING_HOUSE_RESULT_INVALID_GUILD_ID = 10
TRADING_HOUSE_RESULT_ITEM_NOT_FOUND = 5
TRADING_HOUSE_RESULT_LISTINGS_PENDING = 15
TRADING_HOUSE_RESULT_NAME_MATCH_PENDING = 26
TRADING_HOUSE_RESULT_NOT_A_MEMBER = 2
TRADING_HOUSE_RESULT_NOT_IN_A_GUILD = 24
TRADING_HOUSE_RESULT_NOT_OPEN = 1
TRADING_HOUSE_RESULT_NO_NAME_SEARCH_DATA = 27
TRADING_HOUSE_RESULT_NO_PERMISSION = 11
TRADING_HOUSE_RESULT_POST_PENDING = 4
TRADING_HOUSE_RESULT_PURCHASE_PENDING = 18
TRADING_HOUSE_RESULT_QUEUED_POST = 28
TRADING_HOUSE_RESULT_SEARCH_PENDING = 14
TRADING_HOUSE_RESULT_SEARCH_RATE_EXCEEDED = 8
TRADING_HOUSE_RESULT_SUCCESS = 0
TRADING_HOUSE_RESULT_TOO_MANY_POSTS = 3
