--- @meta TradingHouseSearchOutcome

--- @alias TradingHouseSearchOutcome integer
--- | `TRADING_HOUSE_SEARCH_OUTCOME_ALL_RESULTS_PURCHASED` # 4
--- | `TRADING_HOUSE_SEARCH_OUTCOME_HAS_RESULTS` # 0
--- | `TRADING_HOUSE_SEARCH_OUTCOME_NAME_SEARCH_TOO_SHORT` # 3
--- | `TRADING_HOUSE_SEARCH_OUTCOME_NO_NAME_MATCHES` # 2
--- | `TRADING_HOUSE_SEARCH_OUTCOME_NO_RESULTS` # 1

TRADING_HOUSE_SEARCH_OUTCOME_ALL_RESULTS_PURCHASED = 4
TRADING_HOUSE_SEARCH_OUTCOME_HAS_RESULTS = 0
TRADING_HOUSE_SEARCH_OUTCOME_NAME_SEARCH_TOO_SHORT = 3
TRADING_HOUSE_SEARCH_OUTCOME_NO_NAME_MATCHES = 2
TRADING_HOUSE_SEARCH_OUTCOME_NO_RESULTS = 1
