--- @meta TradingHouseFilterType

--- @alias TradingHouseFilterType integer
--- | `TRADING_HOUSE_FILTER_TYPE_ARMOR` # 3
--- | `TRADING_HOUSE_FILTER_TYPE_CHAMPION_POINTS` # 8
--- | `TRADING_HOUSE_FILTER_TYPE_ENCHANTMENT` # 9
--- | `TRADING_HOUSE_FILTER_TYPE_EQUIP` # 0
--- | `TRADING_HOUSE_FILTER_TYPE_FURNITURE_CATEGORY` # 11
--- | `TRADING_HOUSE_FILTER_TYPE_FURNITURE_SUBCATEGORY` # 12
--- | `TRADING_HOUSE_FILTER_TYPE_GAMEPLAY_ACTOR_CATEGORY` # 14
--- | `TRADING_HOUSE_FILTER_TYPE_ITEM` # 1
--- | `TRADING_HOUSE_FILTER_TYPE_LEVEL` # 6
--- | `TRADING_HOUSE_FILTER_TYPE_NAME_HASH` # 10
--- | `TRADING_HOUSE_FILTER_TYPE_PRICE` # 7
--- | `TRADING_HOUSE_FILTER_TYPE_QUALITY` # 5
--- | `TRADING_HOUSE_FILTER_TYPE_SPECIALIZED_ITEM` # 13
--- | `TRADING_HOUSE_FILTER_TYPE_TRAIT` # 4
--- | `TRADING_HOUSE_FILTER_TYPE_WEAPON` # 2

TRADING_HOUSE_FILTER_TYPE_ARMOR = 3
TRADING_HOUSE_FILTER_TYPE_CHAMPION_POINTS = 8
TRADING_HOUSE_FILTER_TYPE_ENCHANTMENT = 9
TRADING_HOUSE_FILTER_TYPE_EQUIP = 0
TRADING_HOUSE_FILTER_TYPE_FURNITURE_CATEGORY = 11
TRADING_HOUSE_FILTER_TYPE_FURNITURE_SUBCATEGORY = 12
TRADING_HOUSE_FILTER_TYPE_GAMEPLAY_ACTOR_CATEGORY = 14
TRADING_HOUSE_FILTER_TYPE_ITEM = 1
TRADING_HOUSE_FILTER_TYPE_LEVEL = 6
TRADING_HOUSE_FILTER_TYPE_NAME_HASH = 10
TRADING_HOUSE_FILTER_TYPE_PRICE = 7
TRADING_HOUSE_FILTER_TYPE_QUALITY = 5
TRADING_HOUSE_FILTER_TYPE_SPECIALIZED_ITEM = 13
TRADING_HOUSE_FILTER_TYPE_TRAIT = 4
TRADING_HOUSE_FILTER_TYPE_WEAPON = 2
