--- @meta TraitBonus

--- @alias TraitBonus integer
--- | `TRAIT_BONUS_AGGRESSIVE` # 10
--- | `TRAIT_BONUS_AUGMENTED` # 12
--- | `TRAIT_BONUS_BLOODTHIRSTY` # 5
--- | `TRAIT_BONUS_BOLSTERED` # 9
--- | `TRAIT_BONUS_CHARGED` # 2
--- | `TRAIT_BONUS_DECISIVE` # 1
--- | `TRAIT_BONUS_POWERED` # 3
--- | `TRAIT_BONUS_PROLIFIC` # 6
--- | `TRAIT_BONUS_QUICKENED` # 11
--- | `TRAIT_BONUS_STURDY` # 8
--- | `TRAIT_BONUS_SWIFT` # 4
--- | `TRAIT_BONUS_TRAINING_XP` # 0
--- | `TRAIT_BONUS_WELL_FITTED` # 7

TRAIT_BONUS_AGGRESSIVE = 10
TRAIT_BONUS_AUGMENTED = 12
TRAIT_BONUS_BLOODTHIRSTY = 5
TRAIT_BONUS_BOLSTERED = 9
TRAIT_BONUS_CHARGED = 2
TRAIT_BONUS_DECISIVE = 1
TRAIT_BONUS_POWERED = 3
TRAIT_BONUS_PROLIFIC = 6
TRAIT_BONUS_QUICKENED = 11
TRAIT_BONUS_STURDY = 8
TRAIT_BONUS_SWIFT = 4
TRAIT_BONUS_TRAINING_XP = 0
TRAIT_BONUS_WELL_FITTED = 7
