--- @meta TranslateAnimationDeltaType

--- @alias TranslateAnimationDeltaType integer
--- | `TRANSLATE_ANIMATION_DELTA_TYPE_FROM_END` # 1
--- | `TRANSLATE_ANIMATION_DELTA_TYPE_FROM_START` # 0

TRANSLATE_ANIMATION_DELTA_TYPE_FROM_END = 1
TRANSLATE_ANIMATION_DELTA_TYPE_FROM_START = 0
