--- @meta TrialAccountRestrictionType

--- @alias TrialAccountRestrictionType integer
--- | `TRIAL_RESTRICTION_CANNOT_USE_GUILDS` # 4
--- | `TRIAL_RESTRICTION_CANNOT_WHISPER` # 2
--- | `TRIAL_RESTRICTION_CANNOT_ZONE_YELL` # 1
--- | `TRIAL_RESTRICTION_NO_RESTRICTION` # 0
--- | `TRIAL_RESTRICTION_WHISPER_FRIENDS_ONLY` # 3

TRIAL_RESTRICTION_CANNOT_USE_GUILDS = 4
TRIAL_RESTRICTION_CANNOT_WHISPER = 2
TRIAL_RESTRICTION_CANNOT_ZONE_YELL = 1
TRIAL_RESTRICTION_NO_RESTRICTION = 0
TRIAL_RESTRICTION_WHISPER_FRIENDS_ONLY = 3
