--- @meta TributeMoveAction

--- @alias TributeMoveAction integer
--- | `TRIBUTE_MOVE_ACTION_ACTIVATE_AGENT` # 8
--- | `TRIBUTE_MOVE_ACTION_BEGIN_TURN` # 9
--- | `TRIBUTE_MOVE_ACTION_BUY_CARD` # 1
--- | `TRIBUTE_MOVE_ACTION_DRAFT_PATRON` # 5
--- | `TRIBUTE_MOVE_ACTION_END_TURN` # 3
--- | `TRIBUTE_MOVE_ACTION_PLAY_CARD` # 0
--- | `TRIBUTE_MOVE_ACTION_READY_UP` # 6
--- | `TRIBUTE_MOVE_ACTION_SELECT_CHOOSE_ONE_MECHANIC` # 10
--- | `TRIBUTE_MOVE_ACTION_SELECT_TARGETS` # 7
--- | `TRIBUTE_MOVE_ACTION_USE_PATRON_POWER` # 2
--- | `TRIBUTE_MOVE_ACTION_USE_POWER_TO_DAMAGE_AGENT` # 4

TRIBUTE_MOVE_ACTION_ACTIVATE_AGENT = 8
TRIBUTE_MOVE_ACTION_BEGIN_TURN = 9
TRIBUTE_MOVE_ACTION_BUY_CARD = 1
TRIBUTE_MOVE_ACTION_DRAFT_PATRON = 5
TRIBUTE_MOVE_ACTION_END_TURN = 3
TRIBUTE_MOVE_ACTION_PLAY_CARD = 0
TRIBUTE_MOVE_ACTION_READY_UP = 6
TRIBUTE_MOVE_ACTION_SELECT_CHOOSE_ONE_MECHANIC = 10
TRIBUTE_MOVE_ACTION_SELECT_TARGETS = 7
TRIBUTE_MOVE_ACTION_USE_PATRON_POWER = 2
TRIBUTE_MOVE_ACTION_USE_POWER_TO_DAMAGE_AGENT = 4
