--- @meta TributePatronPerspectiveFavorState

--- @alias TributePatronPerspectiveFavorState integer
--- | `TRIBUTE_PATRON_PERSPECTIVE_FAVOR_STATE_FAVORS_OPPONENT` # 2
--- | `TRIBUTE_PATRON_PERSPECTIVE_FAVOR_STATE_FAVORS_PLAYER` # 0
--- | `TRIBUTE_PATRON_PERSPECTIVE_FAVOR_STATE_NEUTRAL` # 1

TRIBUTE_PATRON_PERSPECTIVE_FAVOR_STATE_FAVORS_OPPONENT = 2
TRIBUTE_PATRON_PERSPECTIVE_FAVOR_STATE_FAVORS_PLAYER = 0
TRIBUTE_PATRON_PERSPECTIVE_FAVOR_STATE_NEUTRAL = 1
