--- @meta TributeMechanicActivationSource

--- @alias TributeMechanicActivationSource integer
--- | `TRIBUTE_MECHANIC_ACTIVATION_SOURCE_ACTIVATION` # 0
--- | `TRIBUTE_MECHANIC_ACTIVATION_SOURCE_COMBO` # 1

TRIBUTE_MECHANIC_ACTIVATION_SOURCE_ACTIVATION = 0
TRIBUTE_MECHANIC_ACTIVATION_SOURCE_COMBO = 1
