--- @meta TributeTier

--- @alias TributeTier integer
--- | `TRIBUTE_TIER_COPPER` # 3
--- | `TRIBUTE_TIER_ELECTRUM` # 5
--- | `TRIBUTE_TIER_INVALID` # 0
--- | `TRIBUTE_TIER_PEWTER` # 2
--- | `TRIBUTE_TIER_PLATINUM` # 6
--- | `TRIBUTE_TIER_SILVER` # 4
--- | `TRIBUTE_TIER_UNRANKED` # 1

TRIBUTE_TIER_COPPER = 3
TRIBUTE_TIER_ELECTRUM = 5
TRIBUTE_TIER_INVALID = 0
TRIBUTE_TIER_PEWTER = 2
TRIBUTE_TIER_PLATINUM = 6
TRIBUTE_TIER_SILVER = 4
TRIBUTE_TIER_UNRANKED = 1
