--- @meta TributeNPCSkillLevel

--- @alias TributeNPCSkillLevel integer
--- | `TRIBUTE_NPC_SKILL_LEVEL_ADEPT` # 2
--- | `TRIBUTE_NPC_SKILL_LEVEL_HIDDEN_MASTER` # 4
--- | `TRIBUTE_NPC_SKILL_LEVEL_INVALID` # 0
--- | `TRIBUTE_NPC_SKILL_LEVEL_NOVICE` # 1
--- | `TRIBUTE_NPC_SKILL_LEVEL_VETERAN` # 3

TRIBUTE_NPC_SKILL_LEVEL_ADEPT = 2
TRIBUTE_NPC_SKILL_LEVEL_HIDDEN_MASTER = 4
TRIBUTE_NPC_SKILL_LEVEL_INVALID = 0
TRIBUTE_NPC_SKILL_LEVEL_NOVICE = 1
TRIBUTE_NPC_SKILL_LEVEL_VETERAN = 3
