--- @meta TributeVictoryType

--- @alias TributeVictoryType integer
--- | `TRIBUTE_VICTORY_TYPE_CONCESSION` # 3
--- | `TRIBUTE_VICTORY_TYPE_EARLY_CONCESSION` # 5
--- | `TRIBUTE_VICTORY_TYPE_NONE` # 0
--- | `TRIBUTE_VICTORY_TYPE_PATRON` # 2
--- | `TRIBUTE_VICTORY_TYPE_PRESTIGE` # 1
--- | `TRIBUTE_VICTORY_TYPE_SYSTEM_DISBAND` # 4

TRIBUTE_VICTORY_TYPE_CONCESSION = 3
TRIBUTE_VICTORY_TYPE_EARLY_CONCESSION = 5
TRIBUTE_VICTORY_TYPE_NONE = 0
TRIBUTE_VICTORY_TYPE_PATRON = 2
TRIBUTE_VICTORY_TYPE_PRESTIGE = 1
TRIBUTE_VICTORY_TYPE_SYSTEM_DISBAND = 4
