--- @meta TributeCardStateFlags

--- @alias TributeCardStateFlags integer
--- | `TRIBUTE_CARD_STATE_FLAGS_BUYABLE` # 4
--- | `TRIBUTE_CARD_STATE_FLAGS_CALLOUT` # 256
--- | `TRIBUTE_CARD_STATE_FLAGS_DAMAGEABLE` # 8
--- | `TRIBUTE_CARD_STATE_FLAGS_HIGHLIGHTED` # 128
--- | `TRIBUTE_CARD_STATE_FLAGS_PLAYABLE` # 1
--- | `TRIBUTE_CARD_STATE_FLAGS_STACK_DAMAGEABLE` # 16
--- | `TRIBUTE_CARD_STATE_FLAGS_STACK_PLAYABLE` # 2
--- | `TRIBUTE_CARD_STATE_FLAGS_TARGETABLE` # 32
--- | `TRIBUTE_CARD_STATE_FLAGS_TARGETED` # 64

TRIBUTE_CARD_STATE_FLAGS_BUYABLE = 4
TRIBUTE_CARD_STATE_FLAGS_CALLOUT = 256
TRIBUTE_CARD_STATE_FLAGS_DAMAGEABLE = 8
TRIBUTE_CARD_STATE_FLAGS_HIGHLIGHTED = 128
TRIBUTE_CARD_STATE_FLAGS_PLAYABLE = 1
TRIBUTE_CARD_STATE_FLAGS_STACK_DAMAGEABLE = 16
TRIBUTE_CARD_STATE_FLAGS_STACK_PLAYABLE = 2
TRIBUTE_CARD_STATE_FLAGS_TARGETABLE = 32
TRIBUTE_CARD_STATE_FLAGS_TARGETED = 64
