--- @meta TributeGameFlowState

--- @alias TributeGameFlowState integer
--- | `TRIBUTE_GAME_FLOW_STATE_BOARD_SETUP` # 3
--- | `TRIBUTE_GAME_FLOW_STATE_GAME_OVER` # 5
--- | `TRIBUTE_GAME_FLOW_STATE_INACTIVE` # 0
--- | `TRIBUTE_GAME_FLOW_STATE_INTRO` # 1
--- | `TRIBUTE_GAME_FLOW_STATE_PATRON_DRAFT` # 2
--- | `TRIBUTE_GAME_FLOW_STATE_PLAYING` # 4

TRIBUTE_GAME_FLOW_STATE_BOARD_SETUP = 3
TRIBUTE_GAME_FLOW_STATE_GAME_OVER = 5
TRIBUTE_GAME_FLOW_STATE_INACTIVE = 0
TRIBUTE_GAME_FLOW_STATE_INTRO = 1
TRIBUTE_GAME_FLOW_STATE_PATRON_DRAFT = 2
TRIBUTE_GAME_FLOW_STATE_PLAYING = 4
