--- @meta TributeBoardLocation

--- @alias TributeBoardLocation integer
--- | `TRIBUTE_BOARD_LOCATION_CREATED_CARD_INTRO` # 18
--- | `TRIBUTE_BOARD_LOCATION_DOCKS` # 10
--- | `TRIBUTE_BOARD_LOCATION_DOCKS_DECK` # 11
--- | `TRIBUTE_BOARD_LOCATION_DOCKS_DECK_INTRO` # 15
--- | `TRIBUTE_BOARD_LOCATION_DOCKS_DISCARD` # 12
--- | `TRIBUTE_BOARD_LOCATION_OPPONENT_BOARD_ACTION` # 5
--- | `TRIBUTE_BOARD_LOCATION_OPPONENT_BOARD_AGENT` # 7
--- | `TRIBUTE_BOARD_LOCATION_OPPONENT_COOLDOWN` # 9
--- | `TRIBUTE_BOARD_LOCATION_OPPONENT_DECK` # 1
--- | `TRIBUTE_BOARD_LOCATION_OPPONENT_DECK_INTRO` # 17
--- | `TRIBUTE_BOARD_LOCATION_OPPONENT_HAND` # 3
--- | `TRIBUTE_BOARD_LOCATION_OPPONENT_PERM_REMOVED` # 14
--- | `TRIBUTE_BOARD_LOCATION_OPPONENT_PRISON` # 20
--- | `TRIBUTE_BOARD_LOCATION_PLAYER_BOARD_ACTION` # 4
--- | `TRIBUTE_BOARD_LOCATION_PLAYER_BOARD_AGENT` # 6
--- | `TRIBUTE_BOARD_LOCATION_PLAYER_COOLDOWN` # 8
--- | `TRIBUTE_BOARD_LOCATION_PLAYER_DECK` # 0
--- | `TRIBUTE_BOARD_LOCATION_PLAYER_DECK_INTRO` # 16
--- | `TRIBUTE_BOARD_LOCATION_PLAYER_HAND` # 2
--- | `TRIBUTE_BOARD_LOCATION_PLAYER_PERM_REMOVED` # 13
--- | `TRIBUTE_BOARD_LOCATION_PLAYER_PRISON` # 19

TRIBUTE_BOARD_LOCATION_CREATED_CARD_INTRO = 18
TRIBUTE_BOARD_LOCATION_DOCKS = 10
TRIBUTE_BOARD_LOCATION_DOCKS_DECK = 11
TRIBUTE_BOARD_LOCATION_DOCKS_DECK_INTRO = 15
TRIBUTE_BOARD_LOCATION_DOCKS_DISCARD = 12
TRIBUTE_BOARD_LOCATION_OPPONENT_BOARD_ACTION = 5
TRIBUTE_BOARD_LOCATION_OPPONENT_BOARD_AGENT = 7
TRIBUTE_BOARD_LOCATION_OPPONENT_COOLDOWN = 9
TRIBUTE_BOARD_LOCATION_OPPONENT_DECK = 1
TRIBUTE_BOARD_LOCATION_OPPONENT_DECK_INTRO = 17
TRIBUTE_BOARD_LOCATION_OPPONENT_HAND = 3
TRIBUTE_BOARD_LOCATION_OPPONENT_PERM_REMOVED = 14
TRIBUTE_BOARD_LOCATION_OPPONENT_PRISON = 20
TRIBUTE_BOARD_LOCATION_PLAYER_BOARD_ACTION = 4
TRIBUTE_BOARD_LOCATION_PLAYER_BOARD_AGENT = 6
TRIBUTE_BOARD_LOCATION_PLAYER_COOLDOWN = 8
TRIBUTE_BOARD_LOCATION_PLAYER_DECK = 0
TRIBUTE_BOARD_LOCATION_PLAYER_DECK_INTRO = 16
TRIBUTE_BOARD_LOCATION_PLAYER_HAND = 2
TRIBUTE_BOARD_LOCATION_PLAYER_PERM_REMOVED = 13
TRIBUTE_BOARD_LOCATION_PLAYER_PRISON = 19
