--- @meta TributeLeaderboardTier

--- @alias TributeLeaderboardTier integer
--- | `TRIBUTE_LEADERBOARD_TIER_NONE` # 0
--- | `TRIBUTE_LEADERBOARD_TIER_TOP_10` # 1
--- | `TRIBUTE_LEADERBOARD_TIER_TOP_2` # 2

TRIBUTE_LEADERBOARD_TIER_NONE = 0
TRIBUTE_LEADERBOARD_TIER_TOP_10 = 1
TRIBUTE_LEADERBOARD_TIER_TOP_2 = 2
