--- @meta TributePatronStateFlags

--- @alias TributePatronStateFlags integer
--- | `TRIBUTE_PATRON_STATE_FLAGS_CALLOUT` # 8
--- | `TRIBUTE_PATRON_STATE_FLAGS_HIGHLIGHTED` # 4
--- | `TRIBUTE_PATRON_STATE_FLAGS_SELECTABLE` # 1
--- | `TRIBUTE_PATRON_STATE_FLAGS_SELECTED` # 2

TRIBUTE_PATRON_STATE_FLAGS_CALLOUT = 8
TRIBUTE_PATRON_STATE_FLAGS_HIGHLIGHTED = 4
TRIBUTE_PATRON_STATE_FLAGS_SELECTABLE = 1
TRIBUTE_PATRON_STATE_FLAGS_SELECTED = 2
