--- @meta TributeMatchEvent

--- @alias TributeMatchEvent integer
--- | `TRIBUTE_MATCH_EVENT_ACTIVE_PLAYER_AFK` # 66
--- | `TRIBUTE_MATCH_EVENT_ALREADY_IN_MATCH` # 29
--- | `TRIBUTE_MATCH_EVENT_CAMPAIGN_ENDED` # 62
--- | `TRIBUTE_MATCH_EVENT_CAMPAIGN_MATCH_TYPE_MISMATCH` # 64
--- | `TRIBUTE_MATCH_EVENT_CAMPAIGN_MISMATCH` # 63
--- | `TRIBUTE_MATCH_EVENT_CAMPAIGN_NOT_STARTED` # 61
--- | `TRIBUTE_MATCH_EVENT_CANNOT_ACCEPT` # 32
--- | `TRIBUTE_MATCH_EVENT_CANNOT_CANCEL` # 39
--- | `TRIBUTE_MATCH_EVENT_CANNOT_CONCEDE` # 54
--- | `TRIBUTE_MATCH_EVENT_CANNOT_DECLINE` # 30
--- | `TRIBUTE_MATCH_EVENT_CANNOT_FORFEIT` # 40
--- | `TRIBUTE_MATCH_EVENT_CANNOT_WIN` # 35
--- | `TRIBUTE_MATCH_EVENT_FAILED_SETUP` # 31
--- | `TRIBUTE_MATCH_EVENT_FORCED_SHUTDOWN` # 34
--- | `TRIBUTE_MATCH_EVENT_INVALID_INVITE` # 44
--- | `TRIBUTE_MATCH_EVENT_INVALID_INVITER` # 45
--- | `TRIBUTE_MATCH_EVENT_MATCHES_DISABLED` # 65
--- | `TRIBUTE_MATCH_EVENT_MATCH_FULL` # 23
--- | `TRIBUTE_MATCH_EVENT_NATURAL_SHUTDOWN` # 42
--- | `TRIBUTE_MATCH_EVENT_NONE` # 0
--- | `TRIBUTE_MATCH_EVENT_NOT_IN_MATCH` # 33
--- | `TRIBUTE_MATCH_EVENT_NO_ACTIVE_CAMPAIGN` # 28
--- | `TRIBUTE_MATCH_EVENT_PLAYER_ACCEPT` # 43
--- | `TRIBUTE_MATCH_EVENT_PLAYER_CANCEL` # 38
--- | `TRIBUTE_MATCH_EVENT_PLAYER_CONCEDE` # 53
--- | `TRIBUTE_MATCH_EVENT_PLAYER_DEATH` # 46
--- | `TRIBUTE_MATCH_EVENT_PLAYER_DECLINE` # 41
--- | `TRIBUTE_MATCH_EVENT_PLAYER_EXIT` # 47
--- | `TRIBUTE_MATCH_EVENT_PLAYER_FORFEIT` # 37
--- | `TRIBUTE_MATCH_EVENT_PLAYER_LOST` # 22
--- | `TRIBUTE_MATCH_EVENT_PLAYER_WON` # 36
--- | `TRIBUTE_MATCH_EVENT_PROXY_DESTROY` # 48
--- | `TRIBUTE_MATCH_EVENT_RANKED_MATCHES_DISABLED` # 25
--- | `TRIBUTE_MATCH_EVENT_RECENTLY_DECLINED` # 20
--- | `TRIBUTE_MATCH_EVENT_REGION_SHUTDOWN` # 55
--- | `TRIBUTE_MATCH_EVENT_SELF_ACTIVE_TRIBUTE` # 7
--- | `TRIBUTE_MATCH_EVENT_SELF_CONSIDERING_INVITE` # 6
--- | `TRIBUTE_MATCH_EVENT_SELF_CRAFTING` # 17
--- | `TRIBUTE_MATCH_EVENT_SELF_CS_CAMPAIGN_DISABLED` # 71
--- | `TRIBUTE_MATCH_EVENT_SELF_CS_DISABLED` # 69
--- | `TRIBUTE_MATCH_EVENT_SELF_DEAD` # 11
--- | `TRIBUTE_MATCH_EVENT_SELF_INELIGIBLE_AREA` # 19
--- | `TRIBUTE_MATCH_EVENT_SELF_IN_COMBAT` # 15
--- | `TRIBUTE_MATCH_EVENT_SELF_IN_MATCH` # 78
--- | `TRIBUTE_MATCH_EVENT_SELF_LOADING` # 56
--- | `TRIBUTE_MATCH_EVENT_SELF_MATCH_REJECT_INVITE_TYPE` # 49
--- | `TRIBUTE_MATCH_EVENT_SELF_NOT_INITIALIZED` # 26
--- | `TRIBUTE_MATCH_EVENT_SELF_NO_ACCESS` # 59
--- | `TRIBUTE_MATCH_EVENT_SELF_ON_TIMEOUT` # 24
--- | `TRIBUTE_MATCH_EVENT_SELF_PENDING_REQUEST` # 5
--- | `TRIBUTE_MATCH_EVENT_SELF_QUEUED` # 74
--- | `TRIBUTE_MATCH_EVENT_SELF_SWIMMING` # 13
--- | `TRIBUTE_MATCH_EVENT_SELF_TRAVELING` # 67
--- | `TRIBUTE_MATCH_EVENT_SELF_UNAVAILABLE` # 77
--- | `TRIBUTE_MATCH_EVENT_SYSTEM_DISBAND` # 73
--- | `TRIBUTE_MATCH_EVENT_TARGET_ACTIVE_TRIBUTE` # 10
--- | `TRIBUTE_MATCH_EVENT_TARGET_CONSIDERING_INVITE` # 9
--- | `TRIBUTE_MATCH_EVENT_TARGET_CRAFTING` # 18
--- | `TRIBUTE_MATCH_EVENT_TARGET_CS_CAMPAIGN_DISABLED` # 72
--- | `TRIBUTE_MATCH_EVENT_TARGET_CS_DISABLED` # 70
--- | `TRIBUTE_MATCH_EVENT_TARGET_DEAD` # 12
--- | `TRIBUTE_MATCH_EVENT_TARGET_INELIGIBLE_AREA` # 52
--- | `TRIBUTE_MATCH_EVENT_TARGET_INVALID` # 2
--- | `TRIBUTE_MATCH_EVENT_TARGET_IN_COMBAT` # 16
--- | `TRIBUTE_MATCH_EVENT_TARGET_IN_MATCH` # 79
--- | `TRIBUTE_MATCH_EVENT_TARGET_LOADING` # 57
--- | `TRIBUTE_MATCH_EVENT_TARGET_MATCH_REJECT_INVITE_TYPE` # 50
--- | `TRIBUTE_MATCH_EVENT_TARGET_NOT_INITIALIZED` # 27
--- | `TRIBUTE_MATCH_EVENT_TARGET_NO_ACCESS` # 60
--- | `TRIBUTE_MATCH_EVENT_TARGET_ON_TIMEOUT` # 51
--- | `TRIBUTE_MATCH_EVENT_TARGET_PENDING_REQUEST` # 8
--- | `TRIBUTE_MATCH_EVENT_TARGET_QUEUED` # 75
--- | `TRIBUTE_MATCH_EVENT_TARGET_SELF` # 3
--- | `TRIBUTE_MATCH_EVENT_TARGET_SWIMMING` # 14
--- | `TRIBUTE_MATCH_EVENT_TARGET_TRAVELING` # 68
--- | `TRIBUTE_MATCH_EVENT_TARGET_UNAVAILABLE` # 1
--- | `TRIBUTE_MATCH_EVENT_TOO_FAR` # 4
--- | `TRIBUTE_MATCH_EVENT_TOO_MANY_NEARBY` # 21
--- | `TRIBUTE_MATCH_EVENT_TRIBUTE_CAMPAIGN_INITIALIZING` # 58
--- | `TRIBUTE_MATCH_EVENT_UNKNOWN_TARGET_FAILURE` # 76

TRIBUTE_MATCH_EVENT_ACTIVE_PLAYER_AFK = 66
TRIBUTE_MATCH_EVENT_ALREADY_IN_MATCH = 29
TRIBUTE_MATCH_EVENT_CAMPAIGN_ENDED = 62
TRIBUTE_MATCH_EVENT_CAMPAIGN_MATCH_TYPE_MISMATCH = 64
TRIBUTE_MATCH_EVENT_CAMPAIGN_MISMATCH = 63
TRIBUTE_MATCH_EVENT_CAMPAIGN_NOT_STARTED = 61
TRIBUTE_MATCH_EVENT_CANNOT_ACCEPT = 32
TRIBUTE_MATCH_EVENT_CANNOT_CANCEL = 39
TRIBUTE_MATCH_EVENT_CANNOT_CONCEDE = 54
TRIBUTE_MATCH_EVENT_CANNOT_DECLINE = 30
TRIBUTE_MATCH_EVENT_CANNOT_FORFEIT = 40
TRIBUTE_MATCH_EVENT_CANNOT_WIN = 35
TRIBUTE_MATCH_EVENT_FAILED_SETUP = 31
TRIBUTE_MATCH_EVENT_FORCED_SHUTDOWN = 34
TRIBUTE_MATCH_EVENT_INVALID_INVITE = 44
TRIBUTE_MATCH_EVENT_INVALID_INVITER = 45
TRIBUTE_MATCH_EVENT_MATCHES_DISABLED = 65
TRIBUTE_MATCH_EVENT_MATCH_FULL = 23
TRIBUTE_MATCH_EVENT_NATURAL_SHUTDOWN = 42
TRIBUTE_MATCH_EVENT_NONE = 0
TRIBUTE_MATCH_EVENT_NOT_IN_MATCH = 33
TRIBUTE_MATCH_EVENT_NO_ACTIVE_CAMPAIGN = 28
TRIBUTE_MATCH_EVENT_PLAYER_ACCEPT = 43
TRIBUTE_MATCH_EVENT_PLAYER_CANCEL = 38
TRIBUTE_MATCH_EVENT_PLAYER_CONCEDE = 53
TRIBUTE_MATCH_EVENT_PLAYER_DEATH = 46
TRIBUTE_MATCH_EVENT_PLAYER_DECLINE = 41
TRIBUTE_MATCH_EVENT_PLAYER_EXIT = 47
TRIBUTE_MATCH_EVENT_PLAYER_FORFEIT = 37
TRIBUTE_MATCH_EVENT_PLAYER_LOST = 22
TRIBUTE_MATCH_EVENT_PLAYER_WON = 36
TRIBUTE_MATCH_EVENT_PROXY_DESTROY = 48
TRIBUTE_MATCH_EVENT_RANKED_MATCHES_DISABLED = 25
TRIBUTE_MATCH_EVENT_RECENTLY_DECLINED = 20
TRIBUTE_MATCH_EVENT_REGION_SHUTDOWN = 55
TRIBUTE_MATCH_EVENT_SELF_ACTIVE_TRIBUTE = 7
TRIBUTE_MATCH_EVENT_SELF_CONSIDERING_INVITE = 6
TRIBUTE_MATCH_EVENT_SELF_CRAFTING = 17
TRIBUTE_MATCH_EVENT_SELF_CS_CAMPAIGN_DISABLED = 71
TRIBUTE_MATCH_EVENT_SELF_CS_DISABLED = 69
TRIBUTE_MATCH_EVENT_SELF_DEAD = 11
TRIBUTE_MATCH_EVENT_SELF_INELIGIBLE_AREA = 19
TRIBUTE_MATCH_EVENT_SELF_IN_COMBAT = 15
TRIBUTE_MATCH_EVENT_SELF_IN_MATCH = 78
TRIBUTE_MATCH_EVENT_SELF_LOADING = 56
TRIBUTE_MATCH_EVENT_SELF_MATCH_REJECT_INVITE_TYPE = 49
TRIBUTE_MATCH_EVENT_SELF_NOT_INITIALIZED = 26
TRIBUTE_MATCH_EVENT_SELF_NO_ACCESS = 59
TRIBUTE_MATCH_EVENT_SELF_ON_TIMEOUT = 24
TRIBUTE_MATCH_EVENT_SELF_PENDING_REQUEST = 5
TRIBUTE_MATCH_EVENT_SELF_QUEUED = 74
TRIBUTE_MATCH_EVENT_SELF_SWIMMING = 13
TRIBUTE_MATCH_EVENT_SELF_TRAVELING = 67
TRIBUTE_MATCH_EVENT_SELF_UNAVAILABLE = 77
TRIBUTE_MATCH_EVENT_SYSTEM_DISBAND = 73
TRIBUTE_MATCH_EVENT_TARGET_ACTIVE_TRIBUTE = 10
TRIBUTE_MATCH_EVENT_TARGET_CONSIDERING_INVITE = 9
TRIBUTE_MATCH_EVENT_TARGET_CRAFTING = 18
TRIBUTE_MATCH_EVENT_TARGET_CS_CAMPAIGN_DISABLED = 72
TRIBUTE_MATCH_EVENT_TARGET_CS_DISABLED = 70
TRIBUTE_MATCH_EVENT_TARGET_DEAD = 12
TRIBUTE_MATCH_EVENT_TARGET_INELIGIBLE_AREA = 52
TRIBUTE_MATCH_EVENT_TARGET_INVALID = 2
TRIBUTE_MATCH_EVENT_TARGET_IN_COMBAT = 16
TRIBUTE_MATCH_EVENT_TARGET_IN_MATCH = 79
TRIBUTE_MATCH_EVENT_TARGET_LOADING = 57
TRIBUTE_MATCH_EVENT_TARGET_MATCH_REJECT_INVITE_TYPE = 50
TRIBUTE_MATCH_EVENT_TARGET_NOT_INITIALIZED = 27
TRIBUTE_MATCH_EVENT_TARGET_NO_ACCESS = 60
TRIBUTE_MATCH_EVENT_TARGET_ON_TIMEOUT = 51
TRIBUTE_MATCH_EVENT_TARGET_PENDING_REQUEST = 8
TRIBUTE_MATCH_EVENT_TARGET_QUEUED = 75
TRIBUTE_MATCH_EVENT_TARGET_SELF = 3
TRIBUTE_MATCH_EVENT_TARGET_SWIMMING = 14
TRIBUTE_MATCH_EVENT_TARGET_TRAVELING = 68
TRIBUTE_MATCH_EVENT_TARGET_UNAVAILABLE = 1
TRIBUTE_MATCH_EVENT_TOO_FAR = 4
TRIBUTE_MATCH_EVENT_TOO_MANY_NEARBY = 21
TRIBUTE_MATCH_EVENT_TRIBUTE_CAMPAIGN_INITIALIZING = 58
TRIBUTE_MATCH_EVENT_UNKNOWN_TARGET_FAILURE = 76
