--- @meta TributePatronDraftId

--- @alias TributePatronDraftId integer
--- | `TRIBUTE_PATRON_DRAFT_ID_FIRST_PLAYER_FIRST_PICK` # 0
--- | `TRIBUTE_PATRON_DRAFT_ID_FIRST_PLAYER_SECOND_PICK` # 1
--- | `TRIBUTE_PATRON_DRAFT_ID_NEUTRAL` # 4
--- | `TRIBUTE_PATRON_DRAFT_ID_SECOND_PLAYER_FIRST_PICK` # 2
--- | `TRIBUTE_PATRON_DRAFT_ID_SECOND_PLAYER_SECOND_PICK` # 3

TRIBUTE_PATRON_DRAFT_ID_FIRST_PLAYER_FIRST_PICK = 0
TRIBUTE_PATRON_DRAFT_ID_FIRST_PLAYER_SECOND_PICK = 1
TRIBUTE_PATRON_DRAFT_ID_NEUTRAL = 4
TRIBUTE_PATRON_DRAFT_ID_SECOND_PLAYER_FIRST_PICK = 2
TRIBUTE_PATRON_DRAFT_ID_SECOND_PLAYER_SECOND_PICK = 3
