--- @meta TributeMechanicSetbackType

--- @alias TributeMechanicSetbackType integer
--- | `TRIBUTE_MECHANIC_SETBACK_TYPE_NEGATIVE_FOR_PLAYER` # 1
--- | `TRIBUTE_MECHANIC_SETBACK_TYPE_NONE` # 0
--- | `TRIBUTE_MECHANIC_SETBACK_TYPE_POSITIVE_FOR_OPPONENT` # 2

TRIBUTE_MECHANIC_SETBACK_TYPE_NEGATIVE_FOR_PLAYER = 1
TRIBUTE_MECHANIC_SETBACK_TYPE_NONE = 0
TRIBUTE_MECHANIC_SETBACK_TYPE_POSITIVE_FOR_OPPONENT = 2
