--- @meta TributeInputStyle

--- @alias TributeInputStyle integer
--- | `TRIBUTE_INPUT_STYLE_GAMEPAD` # 2
--- | `TRIBUTE_INPUT_STYLE_MOUSE` # 1
--- | `TRIBUTE_INPUT_STYLE_NONE` # 0

TRIBUTE_INPUT_STYLE_GAMEPAD = 2
TRIBUTE_INPUT_STYLE_MOUSE = 1
TRIBUTE_INPUT_STYLE_NONE = 0
