--- @meta TributePlayerInitializationState

--- @alias TributePlayerInitializationState integer
--- | `TRIBUTE_PLAYER_INITIALIZATION_STATE_FAILURE` # 3
--- | `TRIBUTE_PLAYER_INITIALIZATION_STATE_NONE` # 0
--- | `TRIBUTE_PLAYER_INITIALIZATION_STATE_PENDING` # 1
--- | `TRIBUTE_PLAYER_INITIALIZATION_STATE_SUCCESS` # 2

TRIBUTE_PLAYER_INITIALIZATION_STATE_FAILURE = 3
TRIBUTE_PLAYER_INITIALIZATION_STATE_NONE = 0
TRIBUTE_PLAYER_INITIALIZATION_STATE_PENDING = 1
TRIBUTE_PLAYER_INITIALIZATION_STATE_SUCCESS = 2
