--- @meta TributeMatchType

--- @alias TributeMatchType integer
--- | `TRIBUTE_MATCH_TYPE_CASUAL` # 4
--- | `TRIBUTE_MATCH_TYPE_CLIENT` # 3
--- | `TRIBUTE_MATCH_TYPE_COMPETITIVE` # 1
--- | `TRIBUTE_MATCH_TYPE_DEFAULT` # 0
--- | `TRIBUTE_MATCH_TYPE_PRIVATE` # 2

TRIBUTE_MATCH_TYPE_CASUAL = 4
TRIBUTE_MATCH_TYPE_CLIENT = 3
TRIBUTE_MATCH_TYPE_COMPETITIVE = 1
TRIBUTE_MATCH_TYPE_DEFAULT = 0
TRIBUTE_MATCH_TYPE_PRIVATE = 2
