--- @meta TributeCardTypeFilter

--- @alias TributeCardTypeFilter integer
--- | `TRIBUTE_CARD_TYPE_FILTER_ACTION` # 0
--- | `TRIBUTE_CARD_TYPE_FILTER_AGENT` # 1
--- | `TRIBUTE_CARD_TYPE_FILTER_ANY` # 2
--- | `TRIBUTE_CARD_TYPE_FILTER_CONTRACT` # 4
--- | `TRIBUTE_CARD_TYPE_FILTER_CURSE` # 5
--- | `TRIBUTE_CARD_TYPE_FILTER_NON_CONTRACT` # 6
--- | `TRIBUTE_CARD_TYPE_FILTER_SAME_SUIT` # 3

TRIBUTE_CARD_TYPE_FILTER_ACTION = 0
TRIBUTE_CARD_TYPE_FILTER_AGENT = 1
TRIBUTE_CARD_TYPE_FILTER_ANY = 2
TRIBUTE_CARD_TYPE_FILTER_CONTRACT = 4
TRIBUTE_CARD_TYPE_FILTER_CURSE = 5
TRIBUTE_CARD_TYPE_FILTER_NON_CONTRACT = 6
TRIBUTE_CARD_TYPE_FILTER_SAME_SUIT = 3
