--- @meta TributePlayerPerspective

--- @alias TributePlayerPerspective integer
--- | `TRIBUTE_PLAYER_PERSPECTIVE_OPPONENT` # 1
--- | `TRIBUTE_PLAYER_PERSPECTIVE_SELF` # 0

TRIBUTE_PLAYER_PERSPECTIVE_OPPONENT = 1
TRIBUTE_PLAYER_PERSPECTIVE_SELF = 0
