--- @meta TributePatronRequirement

--- @alias TributePatronRequirement integer
--- | `TRIBUTE_PATRON_REQUIREMENT_DISCARD_CARD` # 3
--- | `TRIBUTE_PATRON_REQUIREMENT_HAS_CARD` # 2
--- | `TRIBUTE_PATRON_REQUIREMENT_PAY_RESOURCE` # 1
--- | `TRIBUTE_PATRON_REQUIREMENT_SACRIFICE_CARD` # 0

TRIBUTE_PATRON_REQUIREMENT_DISCARD_CARD = 3
TRIBUTE_PATRON_REQUIREMENT_HAS_CARD = 2
TRIBUTE_PATRON_REQUIREMENT_PAY_RESOURCE = 1
TRIBUTE_PATRON_REQUIREMENT_SACRIFICE_CARD = 0
