--- @meta TributeDockSlot

--- @alias TributeDockSlot integer
--- | `TRIBUTE_DOCK_SLOT_FIVE` # 4
--- | `TRIBUTE_DOCK_SLOT_FOUR` # 3
--- | `TRIBUTE_DOCK_SLOT_ONE` # 0
--- | `TRIBUTE_DOCK_SLOT_THREE` # 2
--- | `TRIBUTE_DOCK_SLOT_TWO` # 1

TRIBUTE_DOCK_SLOT_FIVE = 4
TRIBUTE_DOCK_SLOT_FOUR = 3
TRIBUTE_DOCK_SLOT_ONE = 0
TRIBUTE_DOCK_SLOT_THREE = 2
TRIBUTE_DOCK_SLOT_TWO = 1
