--- @meta TributeMechanicTargetType

--- @alias TributeMechanicTargetType integer
--- | `TRIBUTE_MECHANIC_TARGET_TYPE_EXACT_QUANTITY` # 2
--- | `TRIBUTE_MECHANIC_TARGET_TYPE_NOT_TARGETED` # 0
--- | `TRIBUTE_MECHANIC_TARGET_TYPE_UP_TO_QUANTITY` # 1

TRIBUTE_MECHANIC_TARGET_TYPE_EXACT_QUANTITY = 2
TRIBUTE_MECHANIC_TARGET_TYPE_NOT_TARGETED = 0
TRIBUTE_MECHANIC_TARGET_TYPE_UP_TO_QUANTITY = 1
