--- @meta TributePlayerType

--- @alias TributePlayerType integer
--- | `TRIBUTE_PLAYER_TYPE_BASE` # 0
--- | `TRIBUTE_PLAYER_TYPE_NPC` # 3
--- | `TRIBUTE_PLAYER_TYPE_PLAYER` # 1
--- | `TRIBUTE_PLAYER_TYPE_REMOTE_PLAYER` # 2

TRIBUTE_PLAYER_TYPE_BASE = 0
TRIBUTE_PLAYER_TYPE_NPC = 3
TRIBUTE_PLAYER_TYPE_PLAYER = 1
TRIBUTE_PLAYER_TYPE_REMOTE_PLAYER = 2
