--- @meta TributeMechanic

--- @alias TributeMechanic integer
--- | `TRIBUTE_MECHANIC_ACQUIRE_AND_GIVE_COPY` # 16
--- | `TRIBUTE_MECHANIC_ACQUIRE_CARDS` # 8
--- | `TRIBUTE_MECHANIC_AGENT_SELF_HEAL` # 13
--- | `TRIBUTE_MECHANIC_BONUS_PATRON_INTERACTION` # 9
--- | `TRIBUTE_MECHANIC_CONFINE_CARDS` # 14
--- | `TRIBUTE_MECHANIC_CREATE_CARDS` # 11
--- | `TRIBUTE_MECHANIC_DESTROY_CARDS` # 7
--- | `TRIBUTE_MECHANIC_DISCARD_CARDS` # 3
--- | `TRIBUTE_MECHANIC_DONATE_CARDS` # 15
--- | `TRIBUTE_MECHANIC_DRAW_CARDS` # 4
--- | `TRIBUTE_MECHANIC_GAIN_RESOURCES` # 0
--- | `TRIBUTE_MECHANIC_HEAL_AGENT` # 6
--- | `TRIBUTE_MECHANIC_KO_AGENT` # 2
--- | `TRIBUTE_MECHANIC_KO_ALL` # 18
--- | `TRIBUTE_MECHANIC_LOSE_RESOURCES` # 5
--- | `TRIBUTE_MECHANIC_REFRESH_CARDS` # 10
--- | `TRIBUTE_MECHANIC_TAVERN_REPLACE` # 1
--- | `TRIBUTE_MECHANIC_TAVERN_REPLACE_ALL` # 17
--- | `TRIBUTE_MECHANIC_TOSS_CARDS` # 12

TRIBUTE_MECHANIC_ACQUIRE_AND_GIVE_COPY = 16
TRIBUTE_MECHANIC_ACQUIRE_CARDS = 8
TRIBUTE_MECHANIC_AGENT_SELF_HEAL = 13
TRIBUTE_MECHANIC_BONUS_PATRON_INTERACTION = 9
TRIBUTE_MECHANIC_CONFINE_CARDS = 14
TRIBUTE_MECHANIC_CREATE_CARDS = 11
TRIBUTE_MECHANIC_DESTROY_CARDS = 7
TRIBUTE_MECHANIC_DISCARD_CARDS = 3
TRIBUTE_MECHANIC_DONATE_CARDS = 15
TRIBUTE_MECHANIC_DRAW_CARDS = 4
TRIBUTE_MECHANIC_GAIN_RESOURCES = 0
TRIBUTE_MECHANIC_HEAL_AGENT = 6
TRIBUTE_MECHANIC_KO_AGENT = 2
TRIBUTE_MECHANIC_KO_ALL = 18
TRIBUTE_MECHANIC_LOSE_RESOURCES = 5
TRIBUTE_MECHANIC_REFRESH_CARDS = 10
TRIBUTE_MECHANIC_TAVERN_REPLACE = 1
TRIBUTE_MECHANIC_TAVERN_REPLACE_ALL = 17
TRIBUTE_MECHANIC_TOSS_CARDS = 12
