--- @meta TributeTargetSelectionSourceType

--- @alias TributeTargetSelectionSourceType integer
--- | `TRIBUTE_TARGET_SELECTION_SOURCE_TYPE_MECHANIC` # 2
--- | `TRIBUTE_TARGET_SELECTION_SOURCE_TYPE_NONE` # 0
--- | `TRIBUTE_TARGET_SELECTION_SOURCE_TYPE_PATRON_REQUIREMENT` # 1

TRIBUTE_TARGET_SELECTION_SOURCE_TYPE_MECHANIC = 2
TRIBUTE_TARGET_SELECTION_SOURCE_TYPE_NONE = 0
TRIBUTE_TARGET_SELECTION_SOURCE_TYPE_PATRON_REQUIREMENT = 1
