--- @meta TributeMatchPhase

--- @alias TributeMatchPhase integer
--- | `TRIBUTE_MATCH_PHASE_BOARD_SETUP` # 2
--- | `TRIBUTE_MATCH_PHASE_PATRON_DRAFT` # 1
--- | `TRIBUTE_MATCH_PHASE_POST_GAME` # 4
--- | `TRIBUTE_MATCH_PHASE_PRE_GAME` # 0
--- | `TRIBUTE_MATCH_PHASE_RUNNING` # 3

TRIBUTE_MATCH_PHASE_BOARD_SETUP = 2
TRIBUTE_MATCH_PHASE_PATRON_DRAFT = 1
TRIBUTE_MATCH_PHASE_POST_GAME = 4
TRIBUTE_MATCH_PHASE_PRE_GAME = 0
TRIBUTE_MATCH_PHASE_RUNNING = 3
