--- @meta TributeCardPile

--- @alias TributeCardPile integer
--- | `TRIBUTE_CARD_PILE_BOARD_ACTION` # 2
--- | `TRIBUTE_CARD_PILE_BOARD_AGENT` # 3
--- | `TRIBUTE_CARD_PILE_COOLDOWN` # 4
--- | `TRIBUTE_CARD_PILE_DECK` # 0
--- | `TRIBUTE_CARD_PILE_DOCKS` # 5
--- | `TRIBUTE_CARD_PILE_DOCKS_DECK` # 6
--- | `TRIBUTE_CARD_PILE_DOCKS_DISCARD` # 7
--- | `TRIBUTE_CARD_PILE_HAND` # 1
--- | `TRIBUTE_CARD_PILE_PERM_REMOVED` # 8

TRIBUTE_CARD_PILE_BOARD_ACTION = 2
TRIBUTE_CARD_PILE_BOARD_AGENT = 3
TRIBUTE_CARD_PILE_COOLDOWN = 4
TRIBUTE_CARD_PILE_DECK = 0
TRIBUTE_CARD_PILE_DOCKS = 5
TRIBUTE_CARD_PILE_DOCKS_DECK = 6
TRIBUTE_CARD_PILE_DOCKS_DISCARD = 7
TRIBUTE_CARD_PILE_HAND = 1
TRIBUTE_CARD_PILE_PERM_REMOVED = 8
