--- @meta TributeClubRank

--- @alias TributeClubRank integer
--- | `TRIBUTE_CLUB_RANK_ADEPT` # 4
--- | `TRIBUTE_CLUB_RANK_EXPERT` # 5
--- | `TRIBUTE_CLUB_RANK_INITIATE` # 0
--- | `TRIBUTE_CLUB_RANK_MASTER` # 7
--- | `TRIBUTE_CLUB_RANK_NOVICE` # 2
--- | `TRIBUTE_CLUB_RANK_REGULAR` # 3
--- | `TRIBUTE_CLUB_RANK_TRAINEE` # 1
--- | `TRIBUTE_CLUB_RANK_VETERAN` # 6

TRIBUTE_CLUB_RANK_ADEPT = 4
TRIBUTE_CLUB_RANK_EXPERT = 5
TRIBUTE_CLUB_RANK_INITIATE = 0
TRIBUTE_CLUB_RANK_MASTER = 7
TRIBUTE_CLUB_RANK_NOVICE = 2
TRIBUTE_CLUB_RANK_REGULAR = 3
TRIBUTE_CLUB_RANK_TRAINEE = 1
TRIBUTE_CLUB_RANK_VETERAN = 6
