--- @meta TributeTargetSelectionConfirmationResult

--- @alias TributeTargetSelectionConfirmationResult integer
--- | `TRIBUTE_TARGET_SELECTION_CONFIRMATION_RESULT_MAX_CONFINE_TARGETS_REACHED` # 4
--- | `TRIBUTE_TARGET_SELECTION_CONFIRMATION_RESULT_NOT_ENOUGH_TARGETS` # 2
--- | `TRIBUTE_TARGET_SELECTION_CONFIRMATION_RESULT_REQUIRES_TAUNT_AGENTS` # 3
--- | `TRIBUTE_TARGET_SELECTION_CONFIRMATION_RESULT_SUCCESS` # 0
--- | `TRIBUTE_TARGET_SELECTION_CONFIRMATION_RESULT_TARGET_SELECTION_NOT_ACTIVE` # 1

TRIBUTE_TARGET_SELECTION_CONFIRMATION_RESULT_MAX_CONFINE_TARGETS_REACHED = 4
TRIBUTE_TARGET_SELECTION_CONFIRMATION_RESULT_NOT_ENOUGH_TARGETS = 2
TRIBUTE_TARGET_SELECTION_CONFIRMATION_RESULT_REQUIRES_TAUNT_AGENTS = 3
TRIBUTE_TARGET_SELECTION_CONFIRMATION_RESULT_SUCCESS = 0
TRIBUTE_TARGET_SELECTION_CONFIRMATION_RESULT_TARGET_SELECTION_NOT_ACTIVE = 1
