--- @meta TributeInviteState

--- @alias TributeInviteState integer
--- | `TRIBUTE_INVITE_STATE_GAME_PENDING` # 4
--- | `TRIBUTE_INVITE_STATE_INVITE_ACCEPTED` # 5
--- | `TRIBUTE_INVITE_STATE_INVITE_CONSIDERING` # 2
--- | `TRIBUTE_INVITE_STATE_INVITE_REQUESTING` # 1
--- | `TRIBUTE_INVITE_STATE_NONE` # 0

TRIBUTE_INVITE_STATE_GAME_PENDING = 4
TRIBUTE_INVITE_STATE_INVITE_ACCEPTED = 5
TRIBUTE_INVITE_STATE_INVITE_CONSIDERING = 2
TRIBUTE_INVITE_STATE_INVITE_REQUESTING = 1
TRIBUTE_INVITE_STATE_NONE = 0
