--- @meta TriggerExcludeType

--- @alias TriggerExcludeType integer
--- | `TRIGGER_EXCLUDE_TYPE_NONE` # 0
--- | `TRIGGER_EXCLUDE_TYPE_TRANSFER_DAMAGE` # 1

TRIGGER_EXCLUDE_TYPE_NONE = 0
TRIGGER_EXCLUDE_TYPE_TRANSFER_DAMAGE = 1
