--- @meta TriggerSourceIdentifier

--- @alias TriggerSourceIdentifier integer
--- | `TRIGGER_SOURCE_IDENTIFIER_MEMENTO` # 1
--- | `TRIGGER_SOURCE_IDENTIFIER_NONE` # 0
--- | `TRIGGER_SOURCE_IDENTIFIER_RESOURCE_TAP` # 3
--- | `TRIGGER_SOURCE_IDENTIFIER_TOOL` # 2

TRIGGER_SOURCE_IDENTIFIER_MEMENTO = 1
TRIGGER_SOURCE_IDENTIFIER_NONE = 0
TRIGGER_SOURCE_IDENTIFIER_RESOURCE_TAP = 3
TRIGGER_SOURCE_IDENTIFIER_TOOL = 2
