--- @meta TutorialShowOptions

--- @alias TutorialShowOptions integer
--- | `TUTORIAL_SHOW_OPTIONS_ALL` # 2
--- | `TUTORIAL_SHOW_OPTIONS_GAMEPAD` # 1
--- | `TUTORIAL_SHOW_OPTIONS_KEYBOARD` # 0

TUTORIAL_SHOW_OPTIONS_ALL = 2
TUTORIAL_SHOW_OPTIONS_GAMEPAD = 1
TUTORIAL_SHOW_OPTIONS_KEYBOARD = 0
