--- @meta TutorialType

--- @alias TutorialType integer
--- | `TUTORIAL_TYPE_HUD_BRIEF` # 0
--- | `TUTORIAL_TYPE_HUD_INFO_BOX` # 1
--- | `TUTORIAL_TYPE_POINTER_BOX` # 3
--- | `TUTORIAL_TYPE_UI_INFO_BOX` # 2

TUTORIAL_TYPE_HUD_BRIEF = 0
TUTORIAL_TYPE_HUD_INFO_BOX = 1
TUTORIAL_TYPE_POINTER_BOX = 3
TUTORIAL_TYPE_UI_INFO_BOX = 2
