--- @meta TutorialTrigger

--- @alias TutorialTrigger integer
--- | `TUTORIAL_TRIGGER_ABILITY_PURCHASED_TIMELY_ESCAPE` # 146
--- | `TUTORIAL_TRIGGER_ACCOUNT_BANK_OPENED` # 23
--- | `TUTORIAL_TRIGGER_ACHIEVEMENTS_OPENED` # 22
--- | `TUTORIAL_TRIGGER_ACQUIRED_COLLECTIBLE` # 133
--- | `TUTORIAL_TRIGGER_ACQUIRED_SPECIFIC_COLLECTIBLE` # 205
--- | `TUTORIAL_TRIGGER_ADD_CONSOLIDATED_ITEM_SETS_SHOWN_GAMEPAD` # 272
--- | `TUTORIAL_TRIGGER_ADD_CONSOLIDATED_ITEM_SETS_SHOWN_POINTER_BOX` # 271
--- | `TUTORIAL_TRIGGER_ALCHEMY_OPENED` # 34
--- | `TUTORIAL_TRIGGER_ALCHEMY_STATION_OIL_SLOTTED` # 163
--- | `TUTORIAL_TRIGGER_ANTIQUITY_DIGGING_ANTIQUITY_DAMAGED` # 214
--- | `TUTORIAL_TRIGGER_ANTIQUITY_DIGGING_ANTIQUITY_DESTROYED` # 219
--- | `TUTORIAL_TRIGGER_ANTIQUITY_DIGGING_ANTIQUITY_UNEARTHED` # 221
--- | `TUTORIAL_TRIGGER_ANTIQUITY_DIGGING_BASIC_EXCAVATION_UNLOCKED` # 216
--- | `TUTORIAL_TRIGGER_ANTIQUITY_DIGGING_BASIC_EXCAVATION_UPGRADED` # 224
--- | `TUTORIAL_TRIGGER_ANTIQUITY_DIGGING_BONUS_LOOT_UNEARTHED` # 220
--- | `TUTORIAL_TRIGGER_ANTIQUITY_DIGGING_CAREFUL_TOUCH_UNLOCKED` # 215
--- | `TUTORIAL_TRIGGER_ANTIQUITY_DIGGING_CAREFUL_TOUCH_UPGRADED` # 223
--- | `TUTORIAL_TRIGGER_ANTIQUITY_DIGGING_FISSURE_SPAWNED` # 222
--- | `TUTORIAL_TRIGGER_ANTIQUITY_DIGGING_HEAVY_SHOVEL_UNLOCKED` # 218
--- | `TUTORIAL_TRIGGER_ANTIQUITY_DIGGING_HEAVY_SHOVEL_UPGRADED` # 226
--- | `TUTORIAL_TRIGGER_ANTIQUITY_DIGGING_OPENED` # 213
--- | `TUTORIAL_TRIGGER_ANTIQUITY_DIGGING_RADAR_OUT_OF_ENERGY` # 240
--- | `TUTORIAL_TRIGGER_ANTIQUITY_DIGGING_RADAR_SENSE_UNLOCKED` # 217
--- | `TUTORIAL_TRIGGER_ANTIQUITY_DIGGING_RADAR_SENSE_UPGRADED` # 225
--- | `TUTORIAL_TRIGGER_ANTIQUITY_JOURNAL_OPENED` # 238
--- | `TUTORIAL_TRIGGER_ANTIQUITY_SCRYING_CO_OPT_UNLOCKED` # 230
--- | `TUTORIAL_TRIGGER_ANTIQUITY_SCRYING_CO_OPT_UPGRADED` # 233
--- | `TUTORIAL_TRIGGER_ANTIQUITY_SCRYING_EXTEND_UNLOCKED` # 231
--- | `TUTORIAL_TRIGGER_ANTIQUITY_SCRYING_EXTEND_UPGRADED` # 234
--- | `TUTORIAL_TRIGGER_ANTIQUITY_SCRYING_GOAL_CAPTURED` # 228
--- | `TUTORIAL_TRIGGER_ANTIQUITY_SCRYING_OPENED` # 227
--- | `TUTORIAL_TRIGGER_ANTIQUITY_SCRYING_UNITE_UNLOCKED` # 229
--- | `TUTORIAL_TRIGGER_ANTIQUITY_SCRYING_UNITE_UPGRADED` # 232
--- | `TUTORIAL_TRIGGER_ARMORY_OPENED` # 251
--- | `TUTORIAL_TRIGGER_ATTEMPTED_TO_FISH_WITHOUT_BAIT` # 39
--- | `TUTORIAL_TRIGGER_AVA_FAST_TRAVEL` # 29
--- | `TUTORIAL_TRIGGER_BANK_FULL_NO_ESO_PLUS` # 179
--- | `TUTORIAL_TRIGGER_BANK_OPENED_AS_SUBSCRIBER` # 180
--- | `TUTORIAL_TRIGGER_BANK_OVERFULL` # 178
--- | `TUTORIAL_TRIGGER_BATTLE_LEVEL_ZONE_ENTERED` # 148
--- | `TUTORIAL_TRIGGER_BATTLE_LEVEL_ZONE_ENTERED_VETERAN` # 149
--- | `TUTORIAL_TRIGGER_BLACKSMITHING_CREATION_OPENED` # 35
--- | `TUTORIAL_TRIGGER_BLACKSMITHING_DECONSTRUCTION_OPENED` # 45
--- | `TUTORIAL_TRIGGER_BLACKSMITHING_IMPROVEMENT_OPENED` # 36
--- | `TUTORIAL_TRIGGER_BLACKSMITHING_REFINEMENT_OPENED` # 91
--- | `TUTORIAL_TRIGGER_BLACKSMITHING_RESEARCH_OPENED` # 46
--- | `TUTORIAL_TRIGGER_BOUNTY_ADDED` # 119
--- | `TUTORIAL_TRIGGER_CADWELLS_ALMANAC_OPENED` # 76
--- | `TUTORIAL_TRIGGER_CAMPAIGN_AVAILABLE_TO_ENTER` # 90
--- | `TUTORIAL_TRIGGER_CAMPAIGN_BROWSER_OPENED` # 73
--- | `TUTORIAL_TRIGGER_CAMPAIGN_OVERVIEW_OPENED` # 75
--- | `TUTORIAL_TRIGGER_CHAMPION_POINTS_UNSPENT` # 211
--- | `TUTORIAL_TRIGGER_CHAMPION_POINT_GAINED` # 124
--- | `TUTORIAL_TRIGGER_CHAMPION_RANK_UP` # 79
--- | `TUTORIAL_TRIGGER_CHAMPION_SLOTTABLE_STAR_PURCHASED` # 241
--- | `TUTORIAL_TRIGGER_CHAMPION_SYSTEM_UNLOCKED` # 123
--- | `TUTORIAL_TRIGGER_CHAMPION_UI_SHOWN` # 125
--- | `TUTORIAL_TRIGGER_CLOTHIER_CREATION_OPENED` # 86
--- | `TUTORIAL_TRIGGER_CLOTHIER_DECONSTRUCTION_OPENED` # 88
--- | `TUTORIAL_TRIGGER_CLOTHIER_IMPROVEMENT_OPENED` # 87
--- | `TUTORIAL_TRIGGER_CLOTHIER_REFINEMENT_OPENED` # 93
--- | `TUTORIAL_TRIGGER_CLOTHIER_RESEARCH_OPENED` # 89
--- | `TUTORIAL_TRIGGER_COLLECTIBLE_OF_CATEGORYID_ACQUIRED` # 242
--- | `TUTORIAL_TRIGGER_COLLECTIONS_DLC_OPENED_AS_SUBSCRIBER` # 182
--- | `TUTORIAL_TRIGGER_COLLECTIONS_OPENED` # 134
--- | `TUTORIAL_TRIGGER_COMBAT_MONSTER_DIFFICULTY` # 103
--- | `TUTORIAL_TRIGGER_COMBAT_ROOTED` # 101
--- | `TUTORIAL_TRIGGER_COMBAT_SKILLS_OPENED` # 15
--- | `TUTORIAL_TRIGGER_COMBAT_STATUS_EFFECT` # 104
--- | `TUTORIAL_TRIGGER_COMBAT_STUNNED` # 102
--- | `TUTORIAL_TRIGGER_COMPANION_ABILITY_ACQUIRED` # 243
--- | `TUTORIAL_TRIGGER_COMPANION_ABILITY_SLOT_ACQUIRED` # 244
--- | `TUTORIAL_TRIGGER_COMPANION_EQUIPMENT_ACQUIRED` # 247
--- | `TUTORIAL_TRIGGER_COMPANION_RAPPORT_DECREASE` # 246
--- | `TUTORIAL_TRIGGER_COMPANION_RAPPORT_INCREASE` # 245
--- | `TUTORIAL_TRIGGER_CONSOLIDATED_STATION_OPENED` # 273
--- | `TUTORIAL_TRIGGER_CONTACTS_OPENED` # 24
--- | `TUTORIAL_TRIGGER_CONTROLLING_SIEGE` # 25
--- | `TUTORIAL_TRIGGER_CONVERTED_GRAIN_OR_PLATING` # 270
--- | `TUTORIAL_TRIGGER_CRAFT_BAG_ITEM_GAINED` # 151
--- | `TUTORIAL_TRIGGER_CRAFT_BAG_OPENED` # 152
--- | `TUTORIAL_TRIGGER_CROWN_CONSUMABLE_PURCHASED` # 136
--- | `TUTORIAL_TRIGGER_CROWN_CRATE_UI_OPENED` # 167
--- | `TUTORIAL_TRIGGER_CROWN_STORE_PRODUCT_PURCHASED_1` # 153
--- | `TUTORIAL_TRIGGER_CROWN_STORE_PRODUCT_PURCHASED_10` # 162
--- | `TUTORIAL_TRIGGER_CROWN_STORE_PRODUCT_PURCHASED_2` # 154
--- | `TUTORIAL_TRIGGER_CROWN_STORE_PRODUCT_PURCHASED_3` # 155
--- | `TUTORIAL_TRIGGER_CROWN_STORE_PRODUCT_PURCHASED_4` # 156
--- | `TUTORIAL_TRIGGER_CROWN_STORE_PRODUCT_PURCHASED_5` # 157
--- | `TUTORIAL_TRIGGER_CROWN_STORE_PRODUCT_PURCHASED_6` # 158
--- | `TUTORIAL_TRIGGER_CROWN_STORE_PRODUCT_PURCHASED_7` # 159
--- | `TUTORIAL_TRIGGER_CROWN_STORE_PRODUCT_PURCHASED_8` # 160
--- | `TUTORIAL_TRIGGER_CROWN_STORE_PRODUCT_PURCHASED_9` # 161
--- | `TUTORIAL_TRIGGER_CROWN_STORE_TABS_SHOWN_POINTER_BOX` # 199
--- | `TUTORIAL_TRIGGER_CURRENCY_GAINED_ARCHIVAL_FORTUNES` # 268
--- | `TUTORIAL_TRIGGER_CURRENCY_GAINED_CHAOTIC_CREATIA` # 184
--- | `TUTORIAL_TRIGGER_CURRENCY_GAINED_CROWN_GEMS` # 166
--- | `TUTORIAL_TRIGGER_CURRENCY_GAINED_ENDEAVOR_SEALS` # 204
--- | `TUTORIAL_TRIGGER_CURRENCY_GAINED_EVENT_TICKETS` # 202
--- | `TUTORIAL_TRIGGER_CURRENCY_GAINED_STYLE_STONES` # 188
--- | `TUTORIAL_TRIGGER_CURRENCY_GAINED_UNDAUNTED_KEYS` # 203
--- | `TUTORIAL_TRIGGER_DAILY_LOGIN_REWARDS_OPENED` # 198
--- | `TUTORIAL_TRIGGER_DAILY_QUEST_ADDED` # 94
--- | `TUTORIAL_TRIGGER_DAMAGED_EQUIPMENT_REDUCING_EFFECTIVENESS` # 58
--- | `TUTORIAL_TRIGGER_DEATH_AVA` # 26
--- | `TUTORIAL_TRIGGER_DEATH_PVE` # 27
--- | `TUTORIAL_TRIGGER_DECONSTRUCTION_LEVEL_PENALTY` # 113
--- | `TUTORIAL_TRIGGER_DISCOVERED_ENDLESS_DUNGEON` # 274
--- | `TUTORIAL_TRIGGER_DISCOVERED_GROUP_DUNGEON` # 56
--- | `TUTORIAL_TRIGGER_DISCOVERED_PUBLIC_DUNGEON` # 57
--- | `TUTORIAL_TRIGGER_DISCOVERED_TRIAL` # 250
--- | `TUTORIAL_TRIGGER_DISREPUTABLE_REACHED` # 131
--- | `TUTORIAL_TRIGGER_DYEING_OPENED` # 98
--- | `TUTORIAL_TRIGGER_DYEING_OPENED_AS_SUBSCRIBER` # 181
--- | `TUTORIAL_TRIGGER_DYE_STAMP_CONFIRMATION_SEEN` # 165
--- | `TUTORIAL_TRIGGER_EARNED_ALLIANCE_POINTS` # 2
--- | `TUTORIAL_TRIGGER_EIDETIC_MEMORY` # 112
--- | `TUTORIAL_TRIGGER_EMOTES_MENU_OPENED` # 150
--- | `TUTORIAL_TRIGGER_ENCHANTING_CREATION_OPENED` # 32
--- | `TUTORIAL_TRIGGER_ENCHANTING_EXTRACTION_OPENED` # 33
--- | `TUTORIAL_TRIGGER_ENDEAVORS_OPENED` # 248
--- | `TUTORIAL_TRIGGER_ENLIGHTENED_STATE_GAINED` # 114
--- | `TUTORIAL_TRIGGER_ENLIGHTENED_STATE_LOST` # 115
--- | `TUTORIAL_TRIGGER_ENTERED_BATTLEGROUND_CAPTURE_THE_FLAG` # 172
--- | `TUTORIAL_TRIGGER_ENTERED_BATTLEGROUND_CRAZY_KING` # 176
--- | `TUTORIAL_TRIGGER_ENTERED_BATTLEGROUND_DEATHMATCH` # 173
--- | `TUTORIAL_TRIGGER_ENTERED_BATTLEGROUND_DOMINATION` # 175
--- | `TUTORIAL_TRIGGER_ENTERED_BATTLEGROUND_KING_OF_THE_HILL` # 174
--- | `TUTORIAL_TRIGGER_ENTERED_BATTLEGROUND_MURDERBALL` # 177
--- | `TUTORIAL_TRIGGER_ENTERED_EDITABLE_HOME` # 168
--- | `TUTORIAL_TRIGGER_ENTERED_OBJECTIVE_CAPTURE_AREA` # 72
--- | `TUTORIAL_TRIGGER_ENTERED_OWNED_HOUSING_EDITOR_AS_SUBSCRIBER` # 183
--- | `TUTORIAL_TRIGGER_EQUIPMENT_DAMAGED` # 50
--- | `TUTORIAL_TRIGGER_EQUIPMENT_OUT_OF_CHARGES` # 59
--- | `TUTORIAL_TRIGGER_EQUIPPED_ANY_ARMOR` # 61
--- | `TUTORIAL_TRIGGER_EQUIPPED_ANY_WEAPON` # 60
--- | `TUTORIAL_TRIGGER_EVENT_TICKET_DROP_ON_COOLDOWN` # 267
--- | `TUTORIAL_TRIGGER_FENCE_OPENED` # 117
--- | `TUTORIAL_TRIGGER_FILLETING_OPENED` # 99
--- | `TUTORIAL_TRIGGER_FUGITIVE_REACHED` # 132
--- | `TUTORIAL_TRIGGER_GAINED_BIND_ON_EQUIP_ITEM` # 81
--- | `TUTORIAL_TRIGGER_GAINED_CRAFTING_MATERIAL` # 37
--- | `TUTORIAL_TRIGGER_GAINED_DISGUISE` # 49
--- | `TUTORIAL_TRIGGER_GAINED_EMPTY_SOUL_GEM` # 105
--- | `TUTORIAL_TRIGGER_GAINED_FORWARD_CAMP_ITEM` # 69
--- | `TUTORIAL_TRIGGER_GAINED_MYTHIC_ITEM` # 212
--- | `TUTORIAL_TRIGGER_GAINED_SIEGE_BALLISTA_ITEM` # 66
--- | `TUTORIAL_TRIGGER_GAINED_SIEGE_CATAPULT_ITEM` # 68
--- | `TUTORIAL_TRIGGER_GAINED_SIEGE_LANCER_ITEM` # 239
--- | `TUTORIAL_TRIGGER_GAINED_SIEGE_MASONRY_KIT` # 63
--- | `TUTORIAL_TRIGGER_GAINED_SIEGE_MONSTER_ITEM` # 70
--- | `TUTORIAL_TRIGGER_GAINED_SIEGE_OIL_ITEM` # 71
--- | `TUTORIAL_TRIGGER_GAINED_SIEGE_RAM_ITEM` # 67
--- | `TUTORIAL_TRIGGER_GAINED_SIEGE_TREBUCHET_ITEM` # 65
--- | `TUTORIAL_TRIGGER_GAINED_SIEGE_WOODWORKING_KIT` # 64
--- | `TUTORIAL_TRIGGER_GAINED_SOUL_GEM` # 62
--- | `TUTORIAL_TRIGGER_GIFT_INVENTORY_OPENED` # 200
--- | `TUTORIAL_TRIGGER_GIFT_RECEIVED` # 201
--- | `TUTORIAL_TRIGGER_GROUP_CHAT` # 109
--- | `TUTORIAL_TRIGGER_GROUP_FINDER_OPENED` # 269
--- | `TUTORIAL_TRIGGER_GROUP_TOOLS_OPENED` # 41
--- | `TUTORIAL_TRIGGER_GUILDS_HERALDRY_OPENED` # 100
--- | `TUTORIAL_TRIGGER_GUILDS_HOME_OPENED` # 42
--- | `TUTORIAL_TRIGGER_GUILDS_ROSTER_OPENED` # 43
--- | `TUTORIAL_TRIGGER_GUILD_BANK_OPENED` # 44
--- | `TUTORIAL_TRIGGER_GUILD_CHAT` # 110
--- | `TUTORIAL_TRIGGER_HELP_CUSTOMER_SUPPORT_OPENED` # 78
--- | `TUTORIAL_TRIGGER_HELP_TUTORIALS_OPENED` # 77
--- | `TUTORIAL_TRIGGER_HOME_STORAGE_OPENED` # 186
--- | `TUTORIAL_TRIGGER_HOUSING_EDITOR_ENTERED_LINK_MODE` # 206
--- | `TUTORIAL_TRIGGER_HOUSING_EDITOR_ENTERED_PATH_MODE` # 237
--- | `TUTORIAL_TRIGGER_HOUSING_EDITOR_ENTERED_PRECISION_PLACEMENT_MODE` # 236
--- | `TUTORIAL_TRIGGER_IMPORTANT_DIALOGUE` # 111
--- | `TUTORIAL_TRIGGER_INCOMING_PLAYER_TO_PLAYER_NOTIFICATION` # 38
--- | `TUTORIAL_TRIGGER_INVENTORY_FULL` # 4
--- | `TUTORIAL_TRIGGER_INVENTORY_OPENED` # 3
--- | `TUTORIAL_TRIGGER_INVENTORY_OPENED_AND_FISH_PRESENT` # 192
--- | `TUTORIAL_TRIGGER_INVENTORY_OPENED_AND_QUICKSLOTS_AVAILABLE` # 5
--- | `TUTORIAL_TRIGGER_INVENTORY_OPENED_AND_STOLEN_ITEMS_PRESENT` # 122
--- | `TUTORIAL_TRIGGER_INVENTORY_OPENED_AND_WEAPON_SETS_AVAILABLE` # 6
--- | `TUTORIAL_TRIGGER_JEWELRYCRAFTING_CREATION_OPENED` # 193
--- | `TUTORIAL_TRIGGER_JEWELRYCRAFTING_DECONSTRUCTION_OPENED` # 195
--- | `TUTORIAL_TRIGGER_JEWELRYCRAFTING_IMPROVEMENT_OPENED` # 194
--- | `TUTORIAL_TRIGGER_JEWELRYCRAFTING_REFINEMENT_OPENED` # 197
--- | `TUTORIAL_TRIGGER_JEWELRYCRAFTING_RESEARCH_OPENED` # 196
--- | `TUTORIAL_TRIGGER_JOURNAL_OPENED` # 7
--- | `TUTORIAL_TRIGGER_LAUNDER_OPENED` # 118
--- | `TUTORIAL_TRIGGER_LEADERBOARDS_OPENED` # 74
--- | `TUTORIAL_TRIGGER_LEVEL_UP` # 28
--- | `TUTORIAL_TRIGGER_LIVESTOCK_TARGETED` # 129
--- | `TUTORIAL_TRIGGER_LOCKPICKING_OPENED` # 8
--- | `TUTORIAL_TRIGGER_LORE_LIBRARY_OPENED` # 9
--- | `TUTORIAL_TRIGGER_MAELSTROM_ARENA_ZONE_ENTERED` # 143
--- | `TUTORIAL_TRIGGER_MAIL_OPENED` # 10
--- | `TUTORIAL_TRIGGER_MAIL_OPENED_AND_FULL` # 11
--- | `TUTORIAL_TRIGGER_MAP_OPENED_ANTIQUITY_DIG_SITES` # 235
--- | `TUTORIAL_TRIGGER_MAP_OPENED_BATTLEGROUND` # 171
--- | `TUTORIAL_TRIGGER_MAP_OPENED_CYRODIIL` # 55
--- | `TUTORIAL_TRIGGER_MAP_OPENED_IMPERIAL_CITY` # 209
--- | `TUTORIAL_TRIGGER_MAP_OPENED_PVE` # 54
--- | `TUTORIAL_TRIGGER_MARKET_OPENED` # 135
--- | `TUTORIAL_TRIGGER_MOUNTED` # 137
--- | `TUTORIAL_TRIGGER_MOUNT_SET` # 48
--- | `TUTORIAL_TRIGGER_NONE` # 0
--- | `TUTORIAL_TRIGGER_NON_SUBSCRIBER_LIMIT_REACHED` # 170
--- | `TUTORIAL_TRIGGER_NOTIFICATIONS_OPENED` # 19
--- | `TUTORIAL_TRIGGER_NOTORIOUS_REACHED` # 130
--- | `TUTORIAL_TRIGGER_OPENED_EDITOR` # 169
--- | `TUTORIAL_TRIGGER_OUTFIT_SELECTOR_SHOWN_POINTER_BOX` # 106
--- | `TUTORIAL_TRIGGER_OUTFIT_STYLES_SHOWN` # 187
--- | `TUTORIAL_TRIGGER_OUTLAW_DOOR_VIEWED` # 190
--- | `TUTORIAL_TRIGGER_OWNED_LOCK_VIEWED` # 121
--- | `TUTORIAL_TRIGGER_PICKPOCKET_PROMPT_VIEWED` # 120
--- | `TUTORIAL_TRIGGER_POISON_EQUIPPED` # 164
--- | `TUTORIAL_TRIGGER_PROVISIONING_OPENED` # 31
--- | `TUTORIAL_TRIGGER_PURCHASED_ABILITY` # 52
--- | `TUTORIAL_TRIGGER_PURCHASED_CRIMINAL_ABILITY` # 210
--- | `TUTORIAL_TRIGGER_PURCHASED_PASSIVE_ABILITY` # 80
--- | `TUTORIAL_TRIGGER_PURCHASED_ULTIMATE_ABILITY` # 53
--- | `TUTORIAL_TRIGGER_PVE_FAST_TRAVEL` # 30
--- | `TUTORIAL_TRIGGER_QUEST_ADDED` # 191
--- | `TUTORIAL_TRIGGER_QUEUED_FOR_CAMPAIGN_AS_GUEST` # 208
--- | `TUTORIAL_TRIGGER_RAID_TRIAL_COMPLETED` # 97
--- | `TUTORIAL_TRIGGER_RAID_TRIAL_FAILED` # 96
--- | `TUTORIAL_TRIGGER_RAID_TRIAL_STARTED` # 95
--- | `TUTORIAL_TRIGGER_RECEIVED_MAIL` # 21
--- | `TUTORIAL_TRIGGER_RECEIVED_WHISPER` # 20
--- | `TUTORIAL_TRIGGER_REFUGE_ENTERED` # 127
--- | `TUTORIAL_TRIGGER_RETRAIT_STATION_OPENED` # 185
--- | `TUTORIAL_TRIGGER_RIDING_SKILL_MANAGEMENT_OPENED` # 12
--- | `TUTORIAL_TRIGGER_SCALEABLE_REGION_ENTERED` # 116
--- | `TUTORIAL_TRIGGER_SCRIBING_ABILITY_SCRIBED` # 279
--- | `TUTORIAL_TRIGGER_SCRIBING_GRIMOIRE_SELECTED` # 277
--- | `TUTORIAL_TRIGGER_SCRIBING_OPENED` # 276
--- | `TUTORIAL_TRIGGER_SCRIBING_SCRIPT_SELECTED` # 278
--- | `TUTORIAL_TRIGGER_SEAL_MARKET_OPENED` # 249
--- | `TUTORIAL_TRIGGER_SKILLS_SCRIBING_OPENED` # 280
--- | `TUTORIAL_TRIGGER_SKILLS_SKILL_STYLING` # 281
--- | `TUTORIAL_TRIGGER_SKILL_BUILD_SELECTION_GAMEPAD` # 282
--- | `TUTORIAL_TRIGGER_SKILL_BUILD_SELECTION_POINTER_BOX` # 189
--- | `TUTORIAL_TRIGGER_SKYSHARDS_DISCOVERED` # 51
--- | `TUTORIAL_TRIGGER_STATS_OPENED` # 13
--- | `TUTORIAL_TRIGGER_STATS_OPENED_AND_ATTRIBUTE_POINTS_UNSPENT` # 14
--- | `TUTORIAL_TRIGGER_STOLEN_ITEM_EQUIPPED` # 128
--- | `TUTORIAL_TRIGGER_STOLEN_ITEM_TARGETED` # 126
--- | `TUTORIAL_TRIGGER_STORE_OPENED` # 18
--- | `TUTORIAL_TRIGGER_TELVAR_STONES_GAINED` # 140
--- | `TUTORIAL_TRIGGER_TELVAR_THRESHOLD_CROSSED` # 141
--- | `TUTORIAL_TRIGGER_TELVAR_ZONE_ENTERED` # 142
--- | `TUTORIAL_TRIGGER_TRADESKILLS_OPENED` # 16
--- | `TUTORIAL_TRIGGER_TRADE_OPENED` # 17
--- | `TUTORIAL_TRIGGER_TRESPASS_SUBZONE_ENTERED` # 144
--- | `TUTORIAL_TRIGGER_TRESPASS_SUBZONE_EXITED_WITH_BOUNTY` # 147
--- | `TUTORIAL_TRIGGER_TRIBUTE_AGENT_CARD_SEEN` # 259
--- | `TUTORIAL_TRIGGER_TRIBUTE_CARD_UPGRADED` # 255
--- | `TUTORIAL_TRIGGER_TRIBUTE_CHOICE_CARD_SEEN` # 258
--- | `TUTORIAL_TRIGGER_TRIBUTE_CLUE_ACQUIRED` # 254
--- | `TUTORIAL_TRIGGER_TRIBUTE_CONFINE_CARD_SEEN` # 265
--- | `TUTORIAL_TRIGGER_TRIBUTE_CONTRACT_AGENT_CARD_SEEN` # 261
--- | `TUTORIAL_TRIGGER_TRIBUTE_CONTRACT_CARD_SEEN` # 260
--- | `TUTORIAL_TRIGGER_TRIBUTE_CURSE_CARD_SEEN` # 263
--- | `TUTORIAL_TRIGGER_TRIBUTE_DONATE_CARD_SEEN` # 266
--- | `TUTORIAL_TRIGGER_TRIBUTE_FINDER_OPENED` # 253
--- | `TUTORIAL_TRIGGER_TRIBUTE_LOSE_PRESTIGE` # 257
--- | `TUTORIAL_TRIGGER_TRIBUTE_PVP_VICTORY` # 256
--- | `TUTORIAL_TRIGGER_TRIBUTE_SETBACK_CARD_SEEN` # 275
--- | `TUTORIAL_TRIGGER_TRIBUTE_TAUNT_AGENT_CARD_SEEN` # 262
--- | `TUTORIAL_TRIGGER_TRIBUTE_TRIGGER_CARD_SEEN` # 264
--- | `TUTORIAL_TRIGGER_TWO_FAST_TRAVEL_NODES` # 1
--- | `TUTORIAL_TRIGGER_ULTIMATE_AVAILABLE` # 108
--- | `TUTORIAL_TRIGGER_UNIVERSAL_DECONSTRUCTION_OPENED` # 252
--- | `TUTORIAL_TRIGGER_UNIVERSAL_STYLE_ITEM` # 145
--- | `TUTORIAL_TRIGGER_VOICE_CHAT_OPEN_CHANNELS` # 138
--- | `TUTORIAL_TRIGGER_VOICE_CHAT_OPEN_HISTORY` # 139
--- | `TUTORIAL_TRIGGER_WEAPON_SWAPPING_UNLOCKED` # 47
--- | `TUTORIAL_TRIGGER_WEAPON_SWAP_SHOWN_IN_SKILLS_AFTER_UNLOCK_POINTER_BOX` # 107
--- | `TUTORIAL_TRIGGER_WOODWORKING_CREATION_OPENED` # 82
--- | `TUTORIAL_TRIGGER_WOODWORKING_DECONSTRUCTION_OPENED` # 84
--- | `TUTORIAL_TRIGGER_WOODWORKING_IMPROVEMENT_OPENED` # 83
--- | `TUTORIAL_TRIGGER_WOODWORKING_REFINEMENT_OPENED` # 92
--- | `TUTORIAL_TRIGGER_WOODWORKING_RESEARCH_OPENED` # 85
--- | `TUTORIAL_TRIGGER_YOUR_GROUP_OPENED` # 40
--- | `TUTORIAL_TRIGGER_ZONE_STORIES_SHOWN` # 207

TUTORIAL_TRIGGER_ABILITY_PURCHASED_TIMELY_ESCAPE = 146
TUTORIAL_TRIGGER_ACCOUNT_BANK_OPENED = 23
TUTORIAL_TRIGGER_ACHIEVEMENTS_OPENED = 22
TUTORIAL_TRIGGER_ACQUIRED_COLLECTIBLE = 133
TUTORIAL_TRIGGER_ACQUIRED_SPECIFIC_COLLECTIBLE = 205
TUTORIAL_TRIGGER_ADD_CONSOLIDATED_ITEM_SETS_SHOWN_GAMEPAD = 272
TUTORIAL_TRIGGER_ADD_CONSOLIDATED_ITEM_SETS_SHOWN_POINTER_BOX = 271
TUTORIAL_TRIGGER_ALCHEMY_OPENED = 34
TUTORIAL_TRIGGER_ALCHEMY_STATION_OIL_SLOTTED = 163
TUTORIAL_TRIGGER_ANTIQUITY_DIGGING_ANTIQUITY_DAMAGED = 214
TUTORIAL_TRIGGER_ANTIQUITY_DIGGING_ANTIQUITY_DESTROYED = 219
TUTORIAL_TRIGGER_ANTIQUITY_DIGGING_ANTIQUITY_UNEARTHED = 221
TUTORIAL_TRIGGER_ANTIQUITY_DIGGING_BASIC_EXCAVATION_UNLOCKED = 216
TUTORIAL_TRIGGER_ANTIQUITY_DIGGING_BASIC_EXCAVATION_UPGRADED = 224
TUTORIAL_TRIGGER_ANTIQUITY_DIGGING_BONUS_LOOT_UNEARTHED = 220
TUTORIAL_TRIGGER_ANTIQUITY_DIGGING_CAREFUL_TOUCH_UNLOCKED = 215
TUTORIAL_TRIGGER_ANTIQUITY_DIGGING_CAREFUL_TOUCH_UPGRADED = 223
TUTORIAL_TRIGGER_ANTIQUITY_DIGGING_FISSURE_SPAWNED = 222
TUTORIAL_TRIGGER_ANTIQUITY_DIGGING_HEAVY_SHOVEL_UNLOCKED = 218
TUTORIAL_TRIGGER_ANTIQUITY_DIGGING_HEAVY_SHOVEL_UPGRADED = 226
TUTORIAL_TRIGGER_ANTIQUITY_DIGGING_OPENED = 213
TUTORIAL_TRIGGER_ANTIQUITY_DIGGING_RADAR_OUT_OF_ENERGY = 240
TUTORIAL_TRIGGER_ANTIQUITY_DIGGING_RADAR_SENSE_UNLOCKED = 217
TUTORIAL_TRIGGER_ANTIQUITY_DIGGING_RADAR_SENSE_UPGRADED = 225
TUTORIAL_TRIGGER_ANTIQUITY_JOURNAL_OPENED = 238
TUTORIAL_TRIGGER_ANTIQUITY_SCRYING_CO_OPT_UNLOCKED = 230
TUTORIAL_TRIGGER_ANTIQUITY_SCRYING_CO_OPT_UPGRADED = 233
TUTORIAL_TRIGGER_ANTIQUITY_SCRYING_EXTEND_UNLOCKED = 231
TUTORIAL_TRIGGER_ANTIQUITY_SCRYING_EXTEND_UPGRADED = 234
TUTORIAL_TRIGGER_ANTIQUITY_SCRYING_GOAL_CAPTURED = 228
TUTORIAL_TRIGGER_ANTIQUITY_SCRYING_OPENED = 227
TUTORIAL_TRIGGER_ANTIQUITY_SCRYING_UNITE_UNLOCKED = 229
TUTORIAL_TRIGGER_ANTIQUITY_SCRYING_UNITE_UPGRADED = 232
TUTORIAL_TRIGGER_ARMORY_OPENED = 251
TUTORIAL_TRIGGER_ATTEMPTED_TO_FISH_WITHOUT_BAIT = 39
TUTORIAL_TRIGGER_AVA_FAST_TRAVEL = 29
TUTORIAL_TRIGGER_BANK_FULL_NO_ESO_PLUS = 179
TUTORIAL_TRIGGER_BANK_OPENED_AS_SUBSCRIBER = 180
TUTORIAL_TRIGGER_BANK_OVERFULL = 178
TUTORIAL_TRIGGER_BATTLE_LEVEL_ZONE_ENTERED = 148
TUTORIAL_TRIGGER_BATTLE_LEVEL_ZONE_ENTERED_VETERAN = 149
TUTORIAL_TRIGGER_BLACKSMITHING_CREATION_OPENED = 35
TUTORIAL_TRIGGER_BLACKSMITHING_DECONSTRUCTION_OPENED = 45
TUTORIAL_TRIGGER_BLACKSMITHING_IMPROVEMENT_OPENED = 36
TUTORIAL_TRIGGER_BLACKSMITHING_REFINEMENT_OPENED = 91
TUTORIAL_TRIGGER_BLACKSMITHING_RESEARCH_OPENED = 46
TUTORIAL_TRIGGER_BOUNTY_ADDED = 119
TUTORIAL_TRIGGER_CADWELLS_ALMANAC_OPENED = 76
TUTORIAL_TRIGGER_CAMPAIGN_AVAILABLE_TO_ENTER = 90
TUTORIAL_TRIGGER_CAMPAIGN_BROWSER_OPENED = 73
TUTORIAL_TRIGGER_CAMPAIGN_OVERVIEW_OPENED = 75
TUTORIAL_TRIGGER_CHAMPION_POINTS_UNSPENT = 211
TUTORIAL_TRIGGER_CHAMPION_POINT_GAINED = 124
TUTORIAL_TRIGGER_CHAMPION_RANK_UP = 79
TUTORIAL_TRIGGER_CHAMPION_SLOTTABLE_STAR_PURCHASED = 241
TUTORIAL_TRIGGER_CHAMPION_SYSTEM_UNLOCKED = 123
TUTORIAL_TRIGGER_CHAMPION_UI_SHOWN = 125
TUTORIAL_TRIGGER_CLOTHIER_CREATION_OPENED = 86
TUTORIAL_TRIGGER_CLOTHIER_DECONSTRUCTION_OPENED = 88
TUTORIAL_TRIGGER_CLOTHIER_IMPROVEMENT_OPENED = 87
TUTORIAL_TRIGGER_CLOTHIER_REFINEMENT_OPENED = 93
TUTORIAL_TRIGGER_CLOTHIER_RESEARCH_OPENED = 89
TUTORIAL_TRIGGER_COLLECTIBLE_OF_CATEGORYID_ACQUIRED = 242
TUTORIAL_TRIGGER_COLLECTIONS_DLC_OPENED_AS_SUBSCRIBER = 182
TUTORIAL_TRIGGER_COLLECTIONS_OPENED = 134
TUTORIAL_TRIGGER_COMBAT_MONSTER_DIFFICULTY = 103
TUTORIAL_TRIGGER_COMBAT_ROOTED = 101
TUTORIAL_TRIGGER_COMBAT_SKILLS_OPENED = 15
TUTORIAL_TRIGGER_COMBAT_STATUS_EFFECT = 104
TUTORIAL_TRIGGER_COMBAT_STUNNED = 102
TUTORIAL_TRIGGER_COMPANION_ABILITY_ACQUIRED = 243
TUTORIAL_TRIGGER_COMPANION_ABILITY_SLOT_ACQUIRED = 244
TUTORIAL_TRIGGER_COMPANION_EQUIPMENT_ACQUIRED = 247
TUTORIAL_TRIGGER_COMPANION_RAPPORT_DECREASE = 246
TUTORIAL_TRIGGER_COMPANION_RAPPORT_INCREASE = 245
TUTORIAL_TRIGGER_CONSOLIDATED_STATION_OPENED = 273
TUTORIAL_TRIGGER_CONTACTS_OPENED = 24
TUTORIAL_TRIGGER_CONTROLLING_SIEGE = 25
TUTORIAL_TRIGGER_CONVERTED_GRAIN_OR_PLATING = 270
TUTORIAL_TRIGGER_CRAFT_BAG_ITEM_GAINED = 151
TUTORIAL_TRIGGER_CRAFT_BAG_OPENED = 152
TUTORIAL_TRIGGER_CROWN_CONSUMABLE_PURCHASED = 136
TUTORIAL_TRIGGER_CROWN_CRATE_UI_OPENED = 167
TUTORIAL_TRIGGER_CROWN_STORE_PRODUCT_PURCHASED_1 = 153
TUTORIAL_TRIGGER_CROWN_STORE_PRODUCT_PURCHASED_10 = 162
TUTORIAL_TRIGGER_CROWN_STORE_PRODUCT_PURCHASED_2 = 154
TUTORIAL_TRIGGER_CROWN_STORE_PRODUCT_PURCHASED_3 = 155
TUTORIAL_TRIGGER_CROWN_STORE_PRODUCT_PURCHASED_4 = 156
TUTORIAL_TRIGGER_CROWN_STORE_PRODUCT_PURCHASED_5 = 157
TUTORIAL_TRIGGER_CROWN_STORE_PRODUCT_PURCHASED_6 = 158
TUTORIAL_TRIGGER_CROWN_STORE_PRODUCT_PURCHASED_7 = 159
TUTORIAL_TRIGGER_CROWN_STORE_PRODUCT_PURCHASED_8 = 160
TUTORIAL_TRIGGER_CROWN_STORE_PRODUCT_PURCHASED_9 = 161
TUTORIAL_TRIGGER_CROWN_STORE_TABS_SHOWN_POINTER_BOX = 199
TUTORIAL_TRIGGER_CURRENCY_GAINED_ARCHIVAL_FORTUNES = 268
TUTORIAL_TRIGGER_CURRENCY_GAINED_CHAOTIC_CREATIA = 184
TUTORIAL_TRIGGER_CURRENCY_GAINED_CROWN_GEMS = 166
TUTORIAL_TRIGGER_CURRENCY_GAINED_ENDEAVOR_SEALS = 204
TUTORIAL_TRIGGER_CURRENCY_GAINED_EVENT_TICKETS = 202
TUTORIAL_TRIGGER_CURRENCY_GAINED_STYLE_STONES = 188
TUTORIAL_TRIGGER_CURRENCY_GAINED_UNDAUNTED_KEYS = 203
TUTORIAL_TRIGGER_DAILY_LOGIN_REWARDS_OPENED = 198
TUTORIAL_TRIGGER_DAILY_QUEST_ADDED = 94
TUTORIAL_TRIGGER_DAMAGED_EQUIPMENT_REDUCING_EFFECTIVENESS = 58
TUTORIAL_TRIGGER_DEATH_AVA = 26
TUTORIAL_TRIGGER_DEATH_PVE = 27
TUTORIAL_TRIGGER_DECONSTRUCTION_LEVEL_PENALTY = 113
TUTORIAL_TRIGGER_DISCOVERED_ENDLESS_DUNGEON = 274
TUTORIAL_TRIGGER_DISCOVERED_GROUP_DUNGEON = 56
TUTORIAL_TRIGGER_DISCOVERED_PUBLIC_DUNGEON = 57
TUTORIAL_TRIGGER_DISCOVERED_TRIAL = 250
TUTORIAL_TRIGGER_DISREPUTABLE_REACHED = 131
TUTORIAL_TRIGGER_DYEING_OPENED = 98
TUTORIAL_TRIGGER_DYEING_OPENED_AS_SUBSCRIBER = 181
TUTORIAL_TRIGGER_DYE_STAMP_CONFIRMATION_SEEN = 165
TUTORIAL_TRIGGER_EARNED_ALLIANCE_POINTS = 2
TUTORIAL_TRIGGER_EIDETIC_MEMORY = 112
TUTORIAL_TRIGGER_EMOTES_MENU_OPENED = 150
TUTORIAL_TRIGGER_ENCHANTING_CREATION_OPENED = 32
TUTORIAL_TRIGGER_ENCHANTING_EXTRACTION_OPENED = 33
TUTORIAL_TRIGGER_ENDEAVORS_OPENED = 248
TUTORIAL_TRIGGER_ENLIGHTENED_STATE_GAINED = 114
TUTORIAL_TRIGGER_ENLIGHTENED_STATE_LOST = 115
TUTORIAL_TRIGGER_ENTERED_BATTLEGROUND_CAPTURE_THE_FLAG = 172
TUTORIAL_TRIGGER_ENTERED_BATTLEGROUND_CRAZY_KING = 176
TUTORIAL_TRIGGER_ENTERED_BATTLEGROUND_DEATHMATCH = 173
TUTORIAL_TRIGGER_ENTERED_BATTLEGROUND_DOMINATION = 175
TUTORIAL_TRIGGER_ENTERED_BATTLEGROUND_KING_OF_THE_HILL = 174
TUTORIAL_TRIGGER_ENTERED_BATTLEGROUND_MURDERBALL = 177
TUTORIAL_TRIGGER_ENTERED_EDITABLE_HOME = 168
TUTORIAL_TRIGGER_ENTERED_OBJECTIVE_CAPTURE_AREA = 72
TUTORIAL_TRIGGER_ENTERED_OWNED_HOUSING_EDITOR_AS_SUBSCRIBER = 183
TUTORIAL_TRIGGER_EQUIPMENT_DAMAGED = 50
TUTORIAL_TRIGGER_EQUIPMENT_OUT_OF_CHARGES = 59
TUTORIAL_TRIGGER_EQUIPPED_ANY_ARMOR = 61
TUTORIAL_TRIGGER_EQUIPPED_ANY_WEAPON = 60
TUTORIAL_TRIGGER_EVENT_TICKET_DROP_ON_COOLDOWN = 267
TUTORIAL_TRIGGER_FENCE_OPENED = 117
TUTORIAL_TRIGGER_FILLETING_OPENED = 99
TUTORIAL_TRIGGER_FUGITIVE_REACHED = 132
TUTORIAL_TRIGGER_GAINED_BIND_ON_EQUIP_ITEM = 81
TUTORIAL_TRIGGER_GAINED_CRAFTING_MATERIAL = 37
TUTORIAL_TRIGGER_GAINED_DISGUISE = 49
TUTORIAL_TRIGGER_GAINED_EMPTY_SOUL_GEM = 105
TUTORIAL_TRIGGER_GAINED_FORWARD_CAMP_ITEM = 69
TUTORIAL_TRIGGER_GAINED_MYTHIC_ITEM = 212
TUTORIAL_TRIGGER_GAINED_SIEGE_BALLISTA_ITEM = 66
TUTORIAL_TRIGGER_GAINED_SIEGE_CATAPULT_ITEM = 68
TUTORIAL_TRIGGER_GAINED_SIEGE_LANCER_ITEM = 239
TUTORIAL_TRIGGER_GAINED_SIEGE_MASONRY_KIT = 63
TUTORIAL_TRIGGER_GAINED_SIEGE_MONSTER_ITEM = 70
TUTORIAL_TRIGGER_GAINED_SIEGE_OIL_ITEM = 71
TUTORIAL_TRIGGER_GAINED_SIEGE_RAM_ITEM = 67
TUTORIAL_TRIGGER_GAINED_SIEGE_TREBUCHET_ITEM = 65
TUTORIAL_TRIGGER_GAINED_SIEGE_WOODWORKING_KIT = 64
TUTORIAL_TRIGGER_GAINED_SOUL_GEM = 62
TUTORIAL_TRIGGER_GIFT_INVENTORY_OPENED = 200
TUTORIAL_TRIGGER_GIFT_RECEIVED = 201
TUTORIAL_TRIGGER_GROUP_CHAT = 109
TUTORIAL_TRIGGER_GROUP_FINDER_OPENED = 269
TUTORIAL_TRIGGER_GROUP_TOOLS_OPENED = 41
TUTORIAL_TRIGGER_GUILDS_HERALDRY_OPENED = 100
TUTORIAL_TRIGGER_GUILDS_HOME_OPENED = 42
TUTORIAL_TRIGGER_GUILDS_ROSTER_OPENED = 43
TUTORIAL_TRIGGER_GUILD_BANK_OPENED = 44
TUTORIAL_TRIGGER_GUILD_CHAT = 110
TUTORIAL_TRIGGER_HELP_CUSTOMER_SUPPORT_OPENED = 78
TUTORIAL_TRIGGER_HELP_TUTORIALS_OPENED = 77
TUTORIAL_TRIGGER_HOME_STORAGE_OPENED = 186
TUTORIAL_TRIGGER_HOUSING_EDITOR_ENTERED_LINK_MODE = 206
TUTORIAL_TRIGGER_HOUSING_EDITOR_ENTERED_PATH_MODE = 237
TUTORIAL_TRIGGER_HOUSING_EDITOR_ENTERED_PRECISION_PLACEMENT_MODE = 236
TUTORIAL_TRIGGER_IMPORTANT_DIALOGUE = 111
TUTORIAL_TRIGGER_INCOMING_PLAYER_TO_PLAYER_NOTIFICATION = 38
TUTORIAL_TRIGGER_INVENTORY_FULL = 4
TUTORIAL_TRIGGER_INVENTORY_OPENED = 3
TUTORIAL_TRIGGER_INVENTORY_OPENED_AND_FISH_PRESENT = 192
TUTORIAL_TRIGGER_INVENTORY_OPENED_AND_QUICKSLOTS_AVAILABLE = 5
TUTORIAL_TRIGGER_INVENTORY_OPENED_AND_STOLEN_ITEMS_PRESENT = 122
TUTORIAL_TRIGGER_INVENTORY_OPENED_AND_WEAPON_SETS_AVAILABLE = 6
TUTORIAL_TRIGGER_JEWELRYCRAFTING_CREATION_OPENED = 193
TUTORIAL_TRIGGER_JEWELRYCRAFTING_DECONSTRUCTION_OPENED = 195
TUTORIAL_TRIGGER_JEWELRYCRAFTING_IMPROVEMENT_OPENED = 194
TUTORIAL_TRIGGER_JEWELRYCRAFTING_REFINEMENT_OPENED = 197
TUTORIAL_TRIGGER_JEWELRYCRAFTING_RESEARCH_OPENED = 196
TUTORIAL_TRIGGER_JOURNAL_OPENED = 7
TUTORIAL_TRIGGER_LAUNDER_OPENED = 118
TUTORIAL_TRIGGER_LEADERBOARDS_OPENED = 74
TUTORIAL_TRIGGER_LEVEL_UP = 28
TUTORIAL_TRIGGER_LIVESTOCK_TARGETED = 129
TUTORIAL_TRIGGER_LOCKPICKING_OPENED = 8
TUTORIAL_TRIGGER_LORE_LIBRARY_OPENED = 9
TUTORIAL_TRIGGER_MAELSTROM_ARENA_ZONE_ENTERED = 143
TUTORIAL_TRIGGER_MAIL_OPENED = 10
TUTORIAL_TRIGGER_MAIL_OPENED_AND_FULL = 11
TUTORIAL_TRIGGER_MAP_OPENED_ANTIQUITY_DIG_SITES = 235
TUTORIAL_TRIGGER_MAP_OPENED_BATTLEGROUND = 171
TUTORIAL_TRIGGER_MAP_OPENED_CYRODIIL = 55
TUTORIAL_TRIGGER_MAP_OPENED_IMPERIAL_CITY = 209
TUTORIAL_TRIGGER_MAP_OPENED_PVE = 54
TUTORIAL_TRIGGER_MARKET_OPENED = 135
TUTORIAL_TRIGGER_MOUNTED = 137
TUTORIAL_TRIGGER_MOUNT_SET = 48
TUTORIAL_TRIGGER_NONE = 0
TUTORIAL_TRIGGER_NON_SUBSCRIBER_LIMIT_REACHED = 170
TUTORIAL_TRIGGER_NOTIFICATIONS_OPENED = 19
TUTORIAL_TRIGGER_NOTORIOUS_REACHED = 130
TUTORIAL_TRIGGER_OPENED_EDITOR = 169
TUTORIAL_TRIGGER_OUTFIT_SELECTOR_SHOWN_POINTER_BOX = 106
TUTORIAL_TRIGGER_OUTFIT_STYLES_SHOWN = 187
TUTORIAL_TRIGGER_OUTLAW_DOOR_VIEWED = 190
TUTORIAL_TRIGGER_OWNED_LOCK_VIEWED = 121
TUTORIAL_TRIGGER_PICKPOCKET_PROMPT_VIEWED = 120
TUTORIAL_TRIGGER_POISON_EQUIPPED = 164
TUTORIAL_TRIGGER_PROVISIONING_OPENED = 31
TUTORIAL_TRIGGER_PURCHASED_ABILITY = 52
TUTORIAL_TRIGGER_PURCHASED_CRIMINAL_ABILITY = 210
TUTORIAL_TRIGGER_PURCHASED_PASSIVE_ABILITY = 80
TUTORIAL_TRIGGER_PURCHASED_ULTIMATE_ABILITY = 53
TUTORIAL_TRIGGER_PVE_FAST_TRAVEL = 30
TUTORIAL_TRIGGER_QUEST_ADDED = 191
TUTORIAL_TRIGGER_QUEUED_FOR_CAMPAIGN_AS_GUEST = 208
TUTORIAL_TRIGGER_RAID_TRIAL_COMPLETED = 97
TUTORIAL_TRIGGER_RAID_TRIAL_FAILED = 96
TUTORIAL_TRIGGER_RAID_TRIAL_STARTED = 95
TUTORIAL_TRIGGER_RECEIVED_MAIL = 21
TUTORIAL_TRIGGER_RECEIVED_WHISPER = 20
TUTORIAL_TRIGGER_REFUGE_ENTERED = 127
TUTORIAL_TRIGGER_RETRAIT_STATION_OPENED = 185
TUTORIAL_TRIGGER_RIDING_SKILL_MANAGEMENT_OPENED = 12
TUTORIAL_TRIGGER_SCALEABLE_REGION_ENTERED = 116
TUTORIAL_TRIGGER_SCRIBING_ABILITY_SCRIBED = 279
TUTORIAL_TRIGGER_SCRIBING_GRIMOIRE_SELECTED = 277
TUTORIAL_TRIGGER_SCRIBING_OPENED = 276
TUTORIAL_TRIGGER_SCRIBING_SCRIPT_SELECTED = 278
TUTORIAL_TRIGGER_SEAL_MARKET_OPENED = 249
TUTORIAL_TRIGGER_SKILLS_SCRIBING_OPENED = 280
TUTORIAL_TRIGGER_SKILLS_SKILL_STYLING = 281
TUTORIAL_TRIGGER_SKILL_BUILD_SELECTION_GAMEPAD = 282
TUTORIAL_TRIGGER_SKILL_BUILD_SELECTION_POINTER_BOX = 189
TUTORIAL_TRIGGER_SKYSHARDS_DISCOVERED = 51
TUTORIAL_TRIGGER_STATS_OPENED = 13
TUTORIAL_TRIGGER_STATS_OPENED_AND_ATTRIBUTE_POINTS_UNSPENT = 14
TUTORIAL_TRIGGER_STOLEN_ITEM_EQUIPPED = 128
TUTORIAL_TRIGGER_STOLEN_ITEM_TARGETED = 126
TUTORIAL_TRIGGER_STORE_OPENED = 18
TUTORIAL_TRIGGER_TELVAR_STONES_GAINED = 140
TUTORIAL_TRIGGER_TELVAR_THRESHOLD_CROSSED = 141
TUTORIAL_TRIGGER_TELVAR_ZONE_ENTERED = 142
TUTORIAL_TRIGGER_TRADESKILLS_OPENED = 16
TUTORIAL_TRIGGER_TRADE_OPENED = 17
TUTORIAL_TRIGGER_TRESPASS_SUBZONE_ENTERED = 144
TUTORIAL_TRIGGER_TRESPASS_SUBZONE_EXITED_WITH_BOUNTY = 147
TUTORIAL_TRIGGER_TRIBUTE_AGENT_CARD_SEEN = 259
TUTORIAL_TRIGGER_TRIBUTE_CARD_UPGRADED = 255
TUTORIAL_TRIGGER_TRIBUTE_CHOICE_CARD_SEEN = 258
TUTORIAL_TRIGGER_TRIBUTE_CLUE_ACQUIRED = 254
TUTORIAL_TRIGGER_TRIBUTE_CONFINE_CARD_SEEN = 265
TUTORIAL_TRIGGER_TRIBUTE_CONTRACT_AGENT_CARD_SEEN = 261
TUTORIAL_TRIGGER_TRIBUTE_CONTRACT_CARD_SEEN = 260
TUTORIAL_TRIGGER_TRIBUTE_CURSE_CARD_SEEN = 263
TUTORIAL_TRIGGER_TRIBUTE_DONATE_CARD_SEEN = 266
TUTORIAL_TRIGGER_TRIBUTE_FINDER_OPENED = 253
TUTORIAL_TRIGGER_TRIBUTE_LOSE_PRESTIGE = 257
TUTORIAL_TRIGGER_TRIBUTE_PVP_VICTORY = 256
TUTORIAL_TRIGGER_TRIBUTE_SETBACK_CARD_SEEN = 275
TUTORIAL_TRIGGER_TRIBUTE_TAUNT_AGENT_CARD_SEEN = 262
TUTORIAL_TRIGGER_TRIBUTE_TRIGGER_CARD_SEEN = 264
TUTORIAL_TRIGGER_TWO_FAST_TRAVEL_NODES = 1
TUTORIAL_TRIGGER_ULTIMATE_AVAILABLE = 108
TUTORIAL_TRIGGER_UNIVERSAL_DECONSTRUCTION_OPENED = 252
TUTORIAL_TRIGGER_UNIVERSAL_STYLE_ITEM = 145
TUTORIAL_TRIGGER_VOICE_CHAT_OPEN_CHANNELS = 138
TUTORIAL_TRIGGER_VOICE_CHAT_OPEN_HISTORY = 139
TUTORIAL_TRIGGER_WEAPON_SWAPPING_UNLOCKED = 47
TUTORIAL_TRIGGER_WEAPON_SWAP_SHOWN_IN_SKILLS_AFTER_UNLOCK_POINTER_BOX = 107
TUTORIAL_TRIGGER_WOODWORKING_CREATION_OPENED = 82
TUTORIAL_TRIGGER_WOODWORKING_DECONSTRUCTION_OPENED = 84
TUTORIAL_TRIGGER_WOODWORKING_IMPROVEMENT_OPENED = 83
TUTORIAL_TRIGGER_WOODWORKING_REFINEMENT_OPENED = 92
TUTORIAL_TRIGGER_WOODWORKING_RESEARCH_OPENED = 85
TUTORIAL_TRIGGER_YOUR_GROUP_OPENED = 40
TUTORIAL_TRIGGER_ZONE_STORIES_SHOWN = 207
