--- @meta UIMapType

--- @alias UIMapType integer
--- | `MAPTYPE_COSMIC` # 5
--- | `MAPTYPE_DEPRECATED_1` # 4
--- | `MAPTYPE_NONE` # 0
--- | `MAPTYPE_SUBZONE` # 1
--- | `MAPTYPE_WORLD` # 3
--- | `MAPTYPE_ZONE` # 2

MAPTYPE_COSMIC = 5
MAPTYPE_DEPRECATED_1 = 4
MAPTYPE_NONE = 0
MAPTYPE_SUBZONE = 1
MAPTYPE_WORLD = 3
MAPTYPE_ZONE = 2
