--- @meta UIMonsterDifficulty

--- @alias UIMonsterDifficulty integer
--- | `MONSTER_DIFFICULTY_DEADLY` # 4
--- | `MONSTER_DIFFICULTY_EASY` # 1
--- | `MONSTER_DIFFICULTY_HARD` # 3
--- | `MONSTER_DIFFICULTY_NONE` # 0
--- | `MONSTER_DIFFICULTY_NORMAL` # 2

MONSTER_DIFFICULTY_DEADLY = 4
MONSTER_DIFFICULTY_EASY = 1
MONSTER_DIFFICULTY_HARD = 3
MONSTER_DIFFICULTY_NONE = 0
MONSTER_DIFFICULTY_NORMAL = 2
