--- @meta UISetting

--- @alias UISetting integer
--- | `UI_SETTING_ALWAYS_SHOW_STATUS_TEXT` # 5
--- | `UI_SETTING_AUTOMATIC_QUEST_TRACKING` # 43
--- | `UI_SETTING_AUTO_DECLINE_DUEL_INVITES` # 24
--- | `UI_SETTING_AUTO_DECLINE_TRIBUTE_INVITES` # 39
--- | `UI_SETTING_COMPASS_ACTIVE_QUESTS` # 14
--- | `UI_SETTING_COMPASS_COMPANION` # 36
--- | `UI_SETTING_COMPASS_GROUP_LEADER` # 26
--- | `UI_SETTING_COMPASS_GROUP_MEMBER_AVA` # 32
--- | `UI_SETTING_COMPASS_GROUP_MEMBER_BATTLEGROUND` # 31
--- | `UI_SETTING_COMPASS_GROUP_MEMBER_DELVE` # 28
--- | `UI_SETTING_COMPASS_GROUP_MEMBER_DUNGEON` # 29
--- | `UI_SETTING_COMPASS_GROUP_MEMBER_GENERAL` # 27
--- | `UI_SETTING_COMPASS_GROUP_MEMBER_RAID` # 30
--- | `UI_SETTING_COMPASS_QUEST_GIVERS` # 13
--- | `UI_SETTING_COMPASS_TARGET_MARKERS` # 41
--- | `UI_SETTING_CUSTOM_SCALE` # 1
--- | `UI_SETTING_DEPRECATED3` # 6
--- | `UI_SETTING_FADE_PLAYER_BARS` # 4
--- | `UI_SETTING_FRAMERATE_LATENCY_LOCK` # 12
--- | `UI_SETTING_GAMEPAD_CHAT_HUD_ENABLED` # 23
--- | `UI_SETTING_GAMEPAD_CUSTOM_SCALE` # 35
--- | `UI_SETTING_PRIMARY_PLAYER_NAME_GAMEPAD` # 17
--- | `UI_SETTING_PRIMARY_PLAYER_NAME_KEYBOARD` # 16
--- | `UI_SETTING_RESOURCE_NUMBERS` # 20
--- | `UI_SETTING_RETURN_CURSOR_ON_CHAT_FOCUS` # 3
--- | `UI_SETTING_SHOW_ACTION_BAR` # 8
--- | `UI_SETTING_SHOW_ACTION_BAR_BACK_ROW` # 38
--- | `UI_SETTING_SHOW_ACTION_BAR_TIMERS` # 37
--- | `UI_SETTING_SHOW_ARMOR_INDICATOR` # 19
--- | `UI_SETTING_SHOW_AVA_NOTIFICATIONS` # 33
--- | `UI_SETTING_SHOW_FRAMERATE` # 10
--- | `UI_SETTING_SHOW_GUILD_KEEP_NOTICES` # 42
--- | `UI_SETTING_SHOW_HOUSE_TRACKER` # 40
--- | `UI_SETTING_SHOW_LATENCY` # 11
--- | `UI_SETTING_SHOW_LEADERBOARD_NOTIFICATIONS` # 15
--- | `UI_SETTING_SHOW_PVP_KILL_FEED_NOTIFICATIONS` # 44
--- | `UI_SETTING_SHOW_QUEST_BESTOWER_INDICATORS` # 2
--- | `UI_SETTING_SHOW_QUEST_TRACKER` # 7
--- | `UI_SETTING_SHOW_RAID_LIVES` # 9
--- | `UI_SETTING_SHOW_RESOURCE_BARS` # 25
--- | `UI_SETTING_SHOW_WEAPON_INDICATOR` # 18
--- | `UI_SETTING_SOCIAL_LIST_HIDE_OFFLINE` # 21
--- | `UI_SETTING_ULTIMATE_NUMBER` # 22
--- | `UI_SETTING_USE_CUSTOM_SCALE` # 0
--- | `UI_SETTING_USE_GAMEPAD_CUSTOM_SCALE` # 34

UI_SETTING_ALWAYS_SHOW_STATUS_TEXT = 5
UI_SETTING_AUTOMATIC_QUEST_TRACKING = 43
UI_SETTING_AUTO_DECLINE_DUEL_INVITES = 24
UI_SETTING_AUTO_DECLINE_TRIBUTE_INVITES = 39
UI_SETTING_COMPASS_ACTIVE_QUESTS = 14
UI_SETTING_COMPASS_COMPANION = 36
UI_SETTING_COMPASS_GROUP_LEADER = 26
UI_SETTING_COMPASS_GROUP_MEMBER_AVA = 32
UI_SETTING_COMPASS_GROUP_MEMBER_BATTLEGROUND = 31
UI_SETTING_COMPASS_GROUP_MEMBER_DELVE = 28
UI_SETTING_COMPASS_GROUP_MEMBER_DUNGEON = 29
UI_SETTING_COMPASS_GROUP_MEMBER_GENERAL = 27
UI_SETTING_COMPASS_GROUP_MEMBER_RAID = 30
UI_SETTING_COMPASS_QUEST_GIVERS = 13
UI_SETTING_COMPASS_TARGET_MARKERS = 41
UI_SETTING_CUSTOM_SCALE = 1
UI_SETTING_DEPRECATED3 = 6
UI_SETTING_FADE_PLAYER_BARS = 4
UI_SETTING_FRAMERATE_LATENCY_LOCK = 12
UI_SETTING_GAMEPAD_CHAT_HUD_ENABLED = 23
UI_SETTING_GAMEPAD_CUSTOM_SCALE = 35
UI_SETTING_PRIMARY_PLAYER_NAME_GAMEPAD = 17
UI_SETTING_PRIMARY_PLAYER_NAME_KEYBOARD = 16
UI_SETTING_RESOURCE_NUMBERS = 20
UI_SETTING_RETURN_CURSOR_ON_CHAT_FOCUS = 3
UI_SETTING_SHOW_ACTION_BAR = 8
UI_SETTING_SHOW_ACTION_BAR_BACK_ROW = 38
UI_SETTING_SHOW_ACTION_BAR_TIMERS = 37
UI_SETTING_SHOW_ARMOR_INDICATOR = 19
UI_SETTING_SHOW_AVA_NOTIFICATIONS = 33
UI_SETTING_SHOW_FRAMERATE = 10
UI_SETTING_SHOW_GUILD_KEEP_NOTICES = 42
UI_SETTING_SHOW_HOUSE_TRACKER = 40
UI_SETTING_SHOW_LATENCY = 11
UI_SETTING_SHOW_LEADERBOARD_NOTIFICATIONS = 15
UI_SETTING_SHOW_PVP_KILL_FEED_NOTIFICATIONS = 44
UI_SETTING_SHOW_QUEST_BESTOWER_INDICATORS = 2
UI_SETTING_SHOW_QUEST_TRACKER = 7
UI_SETTING_SHOW_RAID_LIVES = 9
UI_SETTING_SHOW_RESOURCE_BARS = 25
UI_SETTING_SHOW_WEAPON_INDICATOR = 18
UI_SETTING_SOCIAL_LIST_HIDE_OFFLINE = 21
UI_SETTING_ULTIMATE_NUMBER = 22
UI_SETTING_USE_CUSTOM_SCALE = 0
UI_SETTING_USE_GAMEPAD_CUSTOM_SCALE = 34
