--- @meta UISystem

--- @alias UISystem integer
--- | `UI_SYSTEM_ALLIANCE_WAR` # 2
--- | `UI_SYSTEM_ANTIQUITY_DIGGING` # 5
--- | `UI_SYSTEM_ANTIQUITY_JOURNAL_SCRYABLE` # 0
--- | `UI_SYSTEM_ANTIQUITY_SCRYING` # 6
--- | `UI_SYSTEM_BATTLEGROUND_FINDER` # 4
--- | `UI_SYSTEM_DUNGEON_FINDER` # 3
--- | `UI_SYSTEM_GUILD_FINDER` # 1
--- | `UI_SYSTEM_NONE` # -1
--- | `UI_SYSTEM_TRIBUTE` # 9
--- | `UI_SYSTEM_TRIBUTE_FINDER` # 8
--- | `UI_SYSTEM_ZONE_GUIDE` # 7

UI_SYSTEM_ALLIANCE_WAR = 2
UI_SYSTEM_ANTIQUITY_DIGGING = 5
UI_SYSTEM_ANTIQUITY_JOURNAL_SCRYABLE = 0
UI_SYSTEM_ANTIQUITY_SCRYING = 6
UI_SYSTEM_BATTLEGROUND_FINDER = 4
UI_SYSTEM_DUNGEON_FINDER = 3
UI_SYSTEM_GUILD_FINDER = 1
UI_SYSTEM_NONE = -1
UI_SYSTEM_TRIBUTE = 9
UI_SYSTEM_TRIBUTE_FINDER = 8
UI_SYSTEM_ZONE_GUIDE = 7
