--- @meta UIWorldEffect

--- @alias UIWorldEffect integer
--- | `UI_WORLD_EFFECT_ENEMY_TELEGRAPH` # 1
--- | `UI_WORLD_EFFECT_FRIENDLY_TELEGRAPH` # 0

UI_WORLD_EFFECT_ENEMY_TELEGRAPH = 1
UI_WORLD_EFFECT_FRIENDLY_TELEGRAPH = 0
