--- @meta UltimateBarColors

--- @alias UltimateBarColors integer
--- | `ULTIMATE_BAR_COLOR_BAR_END` # 1
--- | `ULTIMATE_BAR_COLOR_BAR_START` # 0
--- | `ULTIMATE_BAR_COLOR_FULL_BAR_END` # 3
--- | `ULTIMATE_BAR_COLOR_FULL_BAR_START` # 2

ULTIMATE_BAR_COLOR_BAR_END = 1
ULTIMATE_BAR_COLOR_BAR_START = 0
ULTIMATE_BAR_COLOR_FULL_BAR_END = 3
ULTIMATE_BAR_COLOR_FULL_BAR_START = 2
