--- @meta UnassignCampaignResult

--- @alias UnassignCampaignResult integer
--- | `UNASSIGN_CAMPAIGN_RESULT_FAILED_INSUFFICIENT_AP` # 3
--- | `UNASSIGN_CAMPAIGN_RESULT_FAILED_INSUFFICIENT_GOLD` # 2
--- | `UNASSIGN_CAMPAIGN_RESULT_FAILED_NOT_ASSIGNED_TO_CAMPAIGN` # 4
--- | `UNASSIGN_CAMPAIGN_RESULT_FAILED_PLAYER_IN_CAMPAIGN` # 1
--- | `UNASSIGN_CAMPAIGN_RESULT_FAILED_UNASSIGN` # 6
--- | `UNASSIGN_CAMPAIGN_RESULT_FAILED_UNASSIGN_COOLDOWN` # 5
--- | `UNASSIGN_CAMPAIGN_RESULT_SUCCESS` # 0

UNASSIGN_CAMPAIGN_RESULT_FAILED_INSUFFICIENT_AP = 3
UNASSIGN_CAMPAIGN_RESULT_FAILED_INSUFFICIENT_GOLD = 2
UNASSIGN_CAMPAIGN_RESULT_FAILED_NOT_ASSIGNED_TO_CAMPAIGN = 4
UNASSIGN_CAMPAIGN_RESULT_FAILED_PLAYER_IN_CAMPAIGN = 1
UNASSIGN_CAMPAIGN_RESULT_FAILED_UNASSIGN = 6
UNASSIGN_CAMPAIGN_RESULT_FAILED_UNASSIGN_COOLDOWN = 5
UNASSIGN_CAMPAIGN_RESULT_SUCCESS = 0
