--- @meta UnitNameplateType

--- @alias UnitNameplateType integer
--- | `UNIT_NAMEPLATE_ALLY_GROUP` # 4
--- | `UNIT_NAMEPLATE_ALLY_GROUP_TARGET` # 18
--- | `UNIT_NAMEPLATE_ALLY_NPC` # 2
--- | `UNIT_NAMEPLATE_ALLY_NPC_TARGET` # 16
--- | `UNIT_NAMEPLATE_ALLY_PLAYER` # 3
--- | `UNIT_NAMEPLATE_ALLY_PLAYER_TARGET` # 17
--- | `UNIT_NAMEPLATE_DEAD` # 1
--- | `UNIT_NAMEPLATE_DEAD_TARGET` # 15
--- | `UNIT_NAMEPLATE_DEFAULT` # 0
--- | `UNIT_NAMEPLATE_DEFAULT_TARGET` # 14
--- | `UNIT_NAMEPLATE_ENEMY_NPC_FRIENDLY` # 5
--- | `UNIT_NAMEPLATE_ENEMY_NPC_FRIENDLY_TARGET` # 19
--- | `UNIT_NAMEPLATE_ENEMY_NPC_HOSTILE` # 7
--- | `UNIT_NAMEPLATE_ENEMY_NPC_HOSTILE_TARGET` # 21
--- | `UNIT_NAMEPLATE_ENEMY_NPC_IN_COMBAT_WITH_LOCAL_PLAYER` # 10
--- | `UNIT_NAMEPLATE_ENEMY_NPC_IN_COMBAT_WITH_LOCAL_PLAYER_JUSTICE_NEUTRAL` # 12
--- | `UNIT_NAMEPLATE_ENEMY_NPC_IN_COMBAT_WITH_LOCAL_PLAYER_JUSTICE_NEUTRAL_TARGET` # 26
--- | `UNIT_NAMEPLATE_ENEMY_NPC_IN_COMBAT_WITH_LOCAL_PLAYER_TARGET` # 24
--- | `UNIT_NAMEPLATE_ENEMY_NPC_JUSTICE_NEUTRAL` # 11
--- | `UNIT_NAMEPLATE_ENEMY_NPC_JUSTICE_NEUTRAL_IGNORE_COMBAT` # 13
--- | `UNIT_NAMEPLATE_ENEMY_NPC_JUSTICE_NEUTRAL_IGNORE_COMBAT_TARGET` # 27
--- | `UNIT_NAMEPLATE_ENEMY_NPC_JUSTICE_NEUTRAL_TARGET` # 25
--- | `UNIT_NAMEPLATE_ENEMY_NPC_NEUTRAL` # 6
--- | `UNIT_NAMEPLATE_ENEMY_NPC_NEUTRAL_TARGET` # 20
--- | `UNIT_NAMEPLATE_ENEMY_PLAYER_NO_PVP` # 8
--- | `UNIT_NAMEPLATE_ENEMY_PLAYER_NO_PVP_TARGET` # 22
--- | `UNIT_NAMEPLATE_ENEMY_PLAYER_PVP` # 9
--- | `UNIT_NAMEPLATE_ENEMY_PLAYER_PVP_TARGET` # 23

UNIT_NAMEPLATE_ALLY_GROUP = 4
UNIT_NAMEPLATE_ALLY_GROUP_TARGET = 18
UNIT_NAMEPLATE_ALLY_NPC = 2
UNIT_NAMEPLATE_ALLY_NPC_TARGET = 16
UNIT_NAMEPLATE_ALLY_PLAYER = 3
UNIT_NAMEPLATE_ALLY_PLAYER_TARGET = 17
UNIT_NAMEPLATE_DEAD = 1
UNIT_NAMEPLATE_DEAD_TARGET = 15
UNIT_NAMEPLATE_DEFAULT = 0
UNIT_NAMEPLATE_DEFAULT_TARGET = 14
UNIT_NAMEPLATE_ENEMY_NPC_FRIENDLY = 5
UNIT_NAMEPLATE_ENEMY_NPC_FRIENDLY_TARGET = 19
UNIT_NAMEPLATE_ENEMY_NPC_HOSTILE = 7
UNIT_NAMEPLATE_ENEMY_NPC_HOSTILE_TARGET = 21
UNIT_NAMEPLATE_ENEMY_NPC_IN_COMBAT_WITH_LOCAL_PLAYER = 10
UNIT_NAMEPLATE_ENEMY_NPC_IN_COMBAT_WITH_LOCAL_PLAYER_JUSTICE_NEUTRAL = 12
UNIT_NAMEPLATE_ENEMY_NPC_IN_COMBAT_WITH_LOCAL_PLAYER_JUSTICE_NEUTRAL_TARGET = 26
UNIT_NAMEPLATE_ENEMY_NPC_IN_COMBAT_WITH_LOCAL_PLAYER_TARGET = 24
UNIT_NAMEPLATE_ENEMY_NPC_JUSTICE_NEUTRAL = 11
UNIT_NAMEPLATE_ENEMY_NPC_JUSTICE_NEUTRAL_IGNORE_COMBAT = 13
UNIT_NAMEPLATE_ENEMY_NPC_JUSTICE_NEUTRAL_IGNORE_COMBAT_TARGET = 27
UNIT_NAMEPLATE_ENEMY_NPC_JUSTICE_NEUTRAL_TARGET = 25
UNIT_NAMEPLATE_ENEMY_NPC_NEUTRAL = 6
UNIT_NAMEPLATE_ENEMY_NPC_NEUTRAL_TARGET = 20
UNIT_NAMEPLATE_ENEMY_PLAYER_NO_PVP = 8
UNIT_NAMEPLATE_ENEMY_PLAYER_NO_PVP_TARGET = 22
UNIT_NAMEPLATE_ENEMY_PLAYER_PVP = 9
UNIT_NAMEPLATE_ENEMY_PLAYER_PVP_TARGET = 23
