--- @meta UnitReactionColor

--- @alias UnitReactionColor integer
--- | `UNIT_REACTION_COLOR_COMPANION` # 8
--- | `UNIT_REACTION_COLOR_DEAD` # 6
--- | `UNIT_REACTION_COLOR_DEFAULT` # 0
--- | `UNIT_REACTION_COLOR_FRIENDLY` # 3
--- | `UNIT_REACTION_COLOR_HOSTILE` # 1
--- | `UNIT_REACTION_COLOR_INTERACT` # 7
--- | `UNIT_REACTION_COLOR_NEUTRAL` # 2
--- | `UNIT_REACTION_COLOR_NPC_ALLY` # 5
--- | `UNIT_REACTION_COLOR_PLAYER_ALLY` # 4

UNIT_REACTION_COLOR_COMPANION = 8
UNIT_REACTION_COLOR_DEAD = 6
UNIT_REACTION_COLOR_DEFAULT = 0
UNIT_REACTION_COLOR_FRIENDLY = 3
UNIT_REACTION_COLOR_HOSTILE = 1
UNIT_REACTION_COLOR_INTERACT = 7
UNIT_REACTION_COLOR_NEUTRAL = 2
UNIT_REACTION_COLOR_NPC_ALLY = 5
UNIT_REACTION_COLOR_PLAYER_ALLY = 4
