--- @meta UnitAttributeVisual

--- @alias UnitAttributeVisual integer
--- | `ATTRIBUTE_VISUAL_AUTOMATIC` # 0
--- | `ATTRIBUTE_VISUAL_DECREASED_MAX_POWER` # 2
--- | `ATTRIBUTE_VISUAL_DECREASED_REGEN_POWER` # 4
--- | `ATTRIBUTE_VISUAL_DECREASED_STAT` # 8
--- | `ATTRIBUTE_VISUAL_INCREASED_MAX_POWER` # 1
--- | `ATTRIBUTE_VISUAL_INCREASED_REGEN_POWER` # 3
--- | `ATTRIBUTE_VISUAL_INCREASED_STAT` # 7
--- | `ATTRIBUTE_VISUAL_NONE` # -1
--- | `ATTRIBUTE_VISUAL_NO_HEALING` # 11
--- | `ATTRIBUTE_VISUAL_POSSESSION` # 9
--- | `ATTRIBUTE_VISUAL_POWER_SHIELDING` # 5
--- | `ATTRIBUTE_VISUAL_TRAUMA` # 10
--- | `ATTRIBUTE_VISUAL_UNWAVERING_POWER` # 6

ATTRIBUTE_VISUAL_AUTOMATIC = 0
ATTRIBUTE_VISUAL_DECREASED_MAX_POWER = 2
ATTRIBUTE_VISUAL_DECREASED_REGEN_POWER = 4
ATTRIBUTE_VISUAL_DECREASED_STAT = 8
ATTRIBUTE_VISUAL_INCREASED_MAX_POWER = 1
ATTRIBUTE_VISUAL_INCREASED_REGEN_POWER = 3
ATTRIBUTE_VISUAL_INCREASED_STAT = 7
ATTRIBUTE_VISUAL_NONE = -1
ATTRIBUTE_VISUAL_NO_HEALING = 11
ATTRIBUTE_VISUAL_POSSESSION = 9
ATTRIBUTE_VISUAL_POWER_SHIELDING = 5
ATTRIBUTE_VISUAL_TRAUMA = 10
ATTRIBUTE_VISUAL_UNWAVERING_POWER = 6
