--- @meta UnitEndCastReason

--- @alias UnitEndCastReason integer
--- | `END_CAST_REASON_COMPLETED` # 0
--- | `END_CAST_REASON_FAILED` # 1
--- | `END_CAST_REASON_INTERRUPTED` # 3
--- | `END_CAST_REASON_PLAYER_CANCELLED` # 2

END_CAST_REASON_COMPLETED = 0
END_CAST_REASON_FAILED = 1
END_CAST_REASON_INTERRUPTED = 3
END_CAST_REASON_PLAYER_CANCELLED = 2
