--- @meta UnitReactionType

--- @alias UnitReactionType integer
--- | `UNIT_REACTION_COMPANION` # 6
--- | `UNIT_REACTION_DEFAULT` # 0
--- | `UNIT_REACTION_FRIENDLY` # 3
--- | `UNIT_REACTION_HOSTILE` # 1
--- | `UNIT_REACTION_NEUTRAL` # 2
--- | `UNIT_REACTION_NPC_ALLY` # 5
--- | `UNIT_REACTION_PLAYER_ALLY` # 4

UNIT_REACTION_COMPANION = 6
UNIT_REACTION_DEFAULT = 0
UNIT_REACTION_FRIENDLY = 3
UNIT_REACTION_HOSTILE = 1
UNIT_REACTION_NEUTRAL = 2
UNIT_REACTION_NPC_ALLY = 5
UNIT_REACTION_PLAYER_ALLY = 4
