--- @meta UpdateGuildMetaDataResponse

--- @alias UpdateGuildMetaDataResponse integer
--- | `UPDATE_GUILD_META_DATA_FAIL` # 2
--- | `UPDATE_GUILD_META_DATA_PENDING` # 4
--- | `UPDATE_GUILD_META_DATA_SUCCESS` # 1
--- | `UPDATE_GUILD_META_DATA_TEXT_TOO_LONG` # 3

UPDATE_GUILD_META_DATA_FAIL = 2
UPDATE_GUILD_META_DATA_PENDING = 4
UPDATE_GUILD_META_DATA_SUCCESS = 1
UPDATE_GUILD_META_DATA_TEXT_TOO_LONG = 3
