--- @meta VERTEX_POINTS

--- @alias VERTEX_POINTS integer
--- | `VERTEX_POINTS_BOTTOMLEFT` # 4
--- | `VERTEX_POINTS_BOTTOMRIGHT` # 8
--- | `VERTEX_POINTS_TOPLEFT` # 1
--- | `VERTEX_POINTS_TOPRIGHT` # 2

VERTEX_POINTS_BOTTOMLEFT = 4
VERTEX_POINTS_BOTTOMRIGHT = 8
VERTEX_POINTS_TOPLEFT = 1
VERTEX_POINTS_TOPRIGHT = 2
