--- @meta VideoSkipMode

--- @alias VideoSkipMode integer
--- | `VIDEO_SKIP_MODE_ALLOW_SKIP` # 1
--- | `VIDEO_SKIP_MODE_NO_SKIP` # 0
--- | `VIDEO_SKIP_MODE_REQUIRE_CONFIRMATION_FOR_SKIP` # 2

VIDEO_SKIP_MODE_ALLOW_SKIP = 1
VIDEO_SKIP_MODE_NO_SKIP = 0
VIDEO_SKIP_MODE_REQUIRE_CONFIRMATION_FOR_SKIP = 2
