--- @meta VideoPlaybackErrorReason

--- @alias VideoPlaybackErrorReason integer
--- | `VIDEO_PLAYBACK_ERROR_REASON_INVALID_VIDEO_NAME` # 0
--- | `VIDEO_PLAYBACK_ERROR_REASON_UNABLE_TO_FIND_VIDEO` # 1

VIDEO_PLAYBACK_ERROR_REASON_INVALID_VIDEO_NAME = 0
VIDEO_PLAYBACK_ERROR_REASON_UNABLE_TO_FIND_VIDEO = 1
