--- @meta VisualLayer

--- @alias VisualLayer integer
--- | `VISUAL_LAYER_COSTUME` # 4
--- | `VISUAL_LAYER_DISGUISE` # 6
--- | `VISUAL_LAYER_EQUIPMENT` # 1
--- | `VISUAL_LAYER_HAT` # 5
--- | `VISUAL_LAYER_HIDE_POLYMORPH_HELM_OPTION` # 9
--- | `VISUAL_LAYER_NONE` # 0
--- | `VISUAL_LAYER_OUTFIT` # 8
--- | `VISUAL_LAYER_POLYMORPH` # 3
--- | `VISUAL_LAYER_SKIN` # 7
--- | `VISUAL_LAYER_TRANSFORMATION` # 2

VISUAL_LAYER_COSTUME = 4
VISUAL_LAYER_DISGUISE = 6
VISUAL_LAYER_EQUIPMENT = 1
VISUAL_LAYER_HAT = 5
VISUAL_LAYER_HIDE_POLYMORPH_HELM_OPTION = 9
VISUAL_LAYER_NONE = 0
VISUAL_LAYER_OUTFIT = 8
VISUAL_LAYER_POLYMORPH = 3
VISUAL_LAYER_SKIN = 7
VISUAL_LAYER_TRANSFORMATION = 2
