--- @meta VisualSlot

--- @alias VisualSlot integer
--- | `VISUAL_SLOT_CHEST` # 2
--- | `VISUAL_SLOT_COSTUME` # 9
--- | `VISUAL_SLOT_FEET` # 8
--- | `VISUAL_SLOT_HAND` # 10
--- | `VISUAL_SLOT_HEAD_ADORNMENTS` # 12
--- | `VISUAL_SLOT_HELM` # 1
--- | `VISUAL_SLOT_LEGS` # 7
--- | `VISUAL_SLOT_NONE` # 0
--- | `VISUAL_SLOT_SHOULDERS` # 3
--- | `VISUAL_SLOT_SKIN` # 11
--- | `VISUAL_SLOT_WAIST` # 5
--- | `VISUAL_SLOT_WEAPON` # 4
--- | `VISUAL_SLOT_WEAPON_BACKUP` # 14
--- | `VISUAL_SLOT_WEAPON_OFF` # 13
--- | `VISUAL_SLOT_WEAPON_OFF_BACKUP` # 15
--- | `VISUAL_SLOT_WRIST` # 6

VISUAL_SLOT_CHEST = 2
VISUAL_SLOT_COSTUME = 9
VISUAL_SLOT_FEET = 8
VISUAL_SLOT_HAND = 10
VISUAL_SLOT_HEAD_ADORNMENTS = 12
VISUAL_SLOT_HELM = 1
VISUAL_SLOT_LEGS = 7
VISUAL_SLOT_NONE = 0
VISUAL_SLOT_SHOULDERS = 3
VISUAL_SLOT_SKIN = 11
VISUAL_SLOT_WAIST = 5
VISUAL_SLOT_WEAPON = 4
VISUAL_SLOT_WEAPON_BACKUP = 14
VISUAL_SLOT_WEAPON_OFF = 13
VISUAL_SLOT_WEAPON_OFF_BACKUP = 15
VISUAL_SLOT_WRIST = 6
