--- @meta VisualArmorType

--- @alias VisualArmorType integer
--- | `VISUAL_ARMORTYPE_CLOTHING` # 5
--- | `VISUAL_ARMORTYPE_HEAVY` # 3
--- | `VISUAL_ARMORTYPE_LIGHT` # 1
--- | `VISUAL_ARMORTYPE_MEDIUM` # 2
--- | `VISUAL_ARMORTYPE_NONE` # 0
--- | `VISUAL_ARMORTYPE_SIGNATURE` # 6
--- | `VISUAL_ARMORTYPE_UNDAUNTED` # 4

VISUAL_ARMORTYPE_CLOTHING = 5
VISUAL_ARMORTYPE_HEAVY = 3
VISUAL_ARMORTYPE_LIGHT = 1
VISUAL_ARMORTYPE_MEDIUM = 2
VISUAL_ARMORTYPE_NONE = 0
VISUAL_ARMORTYPE_SIGNATURE = 6
VISUAL_ARMORTYPE_UNDAUNTED = 4
