--- @meta VoiceChatColors

--- @alias VoiceChatColors integer
--- | `VOICE_CHAT_COLORS_AREA` # 0
--- | `VOICE_CHAT_COLORS_GROUP` # 1
--- | `VOICE_CHAT_COLORS_GUILD` # 2
--- | `VOICE_CHAT_COLORS_MUTED` # 3

VOICE_CHAT_COLORS_AREA = 0
VOICE_CHAT_COLORS_GROUP = 1
VOICE_CHAT_COLORS_GUILD = 2
VOICE_CHAT_COLORS_MUTED = 3
