--- @meta VoiceChatSpeakState

--- @alias VoiceChatSpeakState integer
--- | `VOICE_CHAT_SPEAK_STATE_IDLE` # 1
--- | `VOICE_CHAT_SPEAK_STATE_MUTED` # 3
--- | `VOICE_CHAT_SPEAK_STATE_NONE` # 0
--- | `VOICE_CHAT_SPEAK_STATE_SPEAKING` # 2

VOICE_CHAT_SPEAK_STATE_IDLE = 1
VOICE_CHAT_SPEAK_STATE_MUTED = 3
VOICE_CHAT_SPEAK_STATE_NONE = 0
VOICE_CHAT_SPEAK_STATE_SPEAKING = 2
