--- @meta VoiceChannelType

--- @alias VoiceChannelType integer
--- | `VOICE_CHANNEL_ALL` # 4
--- | `VOICE_CHANNEL_AREA` # 0
--- | `VOICE_CHANNEL_BATTLEGROUP` # 3
--- | `VOICE_CHANNEL_GROUP` # 1
--- | `VOICE_CHANNEL_GUILD` # 2
--- | `VOICE_CHANNEL_NONE` # 5

VOICE_CHANNEL_ALL = 4
VOICE_CHANNEL_AREA = 0
VOICE_CHANNEL_BATTLEGROUP = 3
VOICE_CHANNEL_GROUP = 1
VOICE_CHANNEL_GUILD = 2
VOICE_CHANNEL_NONE = 5
