--- @meta WeaponType

--- @alias WeaponType integer
--- | `WEAPONTYPE_AXE` # 1
--- | `WEAPONTYPE_BOW` # 8
--- | `WEAPONTYPE_DAGGER` # 11
--- | `WEAPONTYPE_FIRE_STAFF` # 12
--- | `WEAPONTYPE_FROST_STAFF` # 13
--- | `WEAPONTYPE_HAMMER` # 2
--- | `WEAPONTYPE_HEALING_STAFF` # 9
--- | `WEAPONTYPE_LIGHTNING_STAFF` # 15
--- | `WEAPONTYPE_NONE` # 0
--- | `WEAPONTYPE_RUNE` # 10
--- | `WEAPONTYPE_SHIELD` # 14
--- | `WEAPONTYPE_SWORD` # 3
--- | `WEAPONTYPE_TWO_HANDED_AXE` # 5
--- | `WEAPONTYPE_TWO_HANDED_HAMMER` # 6
--- | `WEAPONTYPE_TWO_HANDED_SWORD` # 4

WEAPONTYPE_AXE = 1
WEAPONTYPE_BOW = 8
WEAPONTYPE_DAGGER = 11
WEAPONTYPE_FIRE_STAFF = 12
WEAPONTYPE_FROST_STAFF = 13
WEAPONTYPE_HAMMER = 2
WEAPONTYPE_HEALING_STAFF = 9
WEAPONTYPE_LIGHTNING_STAFF = 15
WEAPONTYPE_NONE = 0
WEAPONTYPE_RUNE = 10
WEAPONTYPE_SHIELD = 14
WEAPONTYPE_SWORD = 3
WEAPONTYPE_TWO_HANDED_AXE = 5
WEAPONTYPE_TWO_HANDED_HAMMER = 6
WEAPONTYPE_TWO_HANDED_SWORD = 4
