--- @meta WeaponConfigType

--- @alias WeaponConfigType integer
--- | `WEAPON_CONFIG_TYPE_BOW` # 4
--- | `WEAPON_CONFIG_TYPE_DESTRO_STAFF` # 5
--- | `WEAPON_CONFIG_TYPE_DUAL_WIELD` # 2
--- | `WEAPON_CONFIG_TYPE_FIRE_STAFF` # 7
--- | `WEAPON_CONFIG_TYPE_FROST_STAFF` # 8
--- | `WEAPON_CONFIG_TYPE_LIGHTNING_STAFF` # 9
--- | `WEAPON_CONFIG_TYPE_NONE` # 0
--- | `WEAPON_CONFIG_TYPE_ONE_HANDED` # 10
--- | `WEAPON_CONFIG_TYPE_ONE_HAND_AND_SHIELD` # 1
--- | `WEAPON_CONFIG_TYPE_RESTO_STAFF` # 6
--- | `WEAPON_CONFIG_TYPE_SHIELD_ONLY` # 13
--- | `WEAPON_CONFIG_TYPE_TWO_HANDED` # 3
--- | `WEAPON_CONFIG_TYPE_UNARMED` # 11
--- | `WEAPON_CONFIG_TYPE_WEREWOLF` # 12

WEAPON_CONFIG_TYPE_BOW = 4
WEAPON_CONFIG_TYPE_DESTRO_STAFF = 5
WEAPON_CONFIG_TYPE_DUAL_WIELD = 2
WEAPON_CONFIG_TYPE_FIRE_STAFF = 7
WEAPON_CONFIG_TYPE_FROST_STAFF = 8
WEAPON_CONFIG_TYPE_LIGHTNING_STAFF = 9
WEAPON_CONFIG_TYPE_NONE = 0
WEAPON_CONFIG_TYPE_ONE_HANDED = 10
WEAPON_CONFIG_TYPE_ONE_HAND_AND_SHIELD = 1
WEAPON_CONFIG_TYPE_RESTO_STAFF = 6
WEAPON_CONFIG_TYPE_SHIELD_ONLY = 13
WEAPON_CONFIG_TYPE_TWO_HANDED = 3
WEAPON_CONFIG_TYPE_UNARMED = 11
WEAPON_CONFIG_TYPE_WEREWOLF = 12
