--- @meta WeaponModelType

--- @alias WeaponModelType integer
--- | `WEAPON_MODEL_TYPE_AXE` # 1
--- | `WEAPON_MODEL_TYPE_BOW` # 5
--- | `WEAPON_MODEL_TYPE_DAGGER` # 4
--- | `WEAPON_MODEL_TYPE_HAMMER` # 2
--- | `WEAPON_MODEL_TYPE_NONE` # 0
--- | `WEAPON_MODEL_TYPE_PROP` # 9
--- | `WEAPON_MODEL_TYPE_RUNE` # 8
--- | `WEAPON_MODEL_TYPE_SHIELD` # 7
--- | `WEAPON_MODEL_TYPE_STAFF` # 6
--- | `WEAPON_MODEL_TYPE_SWORD` # 3

WEAPON_MODEL_TYPE_AXE = 1
WEAPON_MODEL_TYPE_BOW = 5
WEAPON_MODEL_TYPE_DAGGER = 4
WEAPON_MODEL_TYPE_HAMMER = 2
WEAPON_MODEL_TYPE_NONE = 0
WEAPON_MODEL_TYPE_PROP = 9
WEAPON_MODEL_TYPE_RUNE = 8
WEAPON_MODEL_TYPE_SHIELD = 7
WEAPON_MODEL_TYPE_STAFF = 6
WEAPON_MODEL_TYPE_SWORD = 3
