--- @meta WorldEventLocationContext

--- @alias WorldEventLocationContext integer
--- | `WORLD_EVENT_LOCATION_CONTEXT_NONE` # 0
--- | `WORLD_EVENT_LOCATION_CONTEXT_POINT_OF_INTEREST` # 2
--- | `WORLD_EVENT_LOCATION_CONTEXT_UNIT` # 1

WORLD_EVENT_LOCATION_CONTEXT_NONE = 0
WORLD_EVENT_LOCATION_CONTEXT_POINT_OF_INTEREST = 2
WORLD_EVENT_LOCATION_CONTEXT_UNIT = 1
