--- @meta WorldEventType

--- @alias WorldEventType integer
--- | `WORLD_EVENT_TYPE_DARK_ANCHOR` # 2
--- | `WORLD_EVENT_TYPE_FISSURE` # 4
--- | `WORLD_EVENT_TYPE_GEYSER` # 3
--- | `WORLD_EVENT_TYPE_HARROWSTORM` # 1
--- | `WORLD_EVENT_TYPE_MIRRORMOOR` # 5
--- | `WORLD_EVENT_TYPE_MONSTER_HUNT` # 0

WORLD_EVENT_TYPE_DARK_ANCHOR = 2
WORLD_EVENT_TYPE_FISSURE = 4
WORLD_EVENT_TYPE_GEYSER = 3
WORLD_EVENT_TYPE_HARROWSTORM = 1
WORLD_EVENT_TYPE_MIRRORMOOR = 5
WORLD_EVENT_TYPE_MONSTER_HUNT = 0
