--- @meta ZoneDisplayType

--- @alias ZoneDisplayType integer
--- | `ZONE_DISPLAY_TYPE_BATTLEGROUND` # 9
--- | `ZONE_DISPLAY_TYPE_COMPANION` # 11
--- | `ZONE_DISPLAY_TYPE_DELVE` # 7
--- | `ZONE_DISPLAY_TYPE_DUNGEON` # 2
--- | `ZONE_DISPLAY_TYPE_ENDLESS_DUNGEON` # 12
--- | `ZONE_DISPLAY_TYPE_GROUP_AREA` # 5
--- | `ZONE_DISPLAY_TYPE_GROUP_DELVE` # 4
--- | `ZONE_DISPLAY_TYPE_HOUSING` # 8
--- | `ZONE_DISPLAY_TYPE_NONE` # 0
--- | `ZONE_DISPLAY_TYPE_PUBLIC_DUNGEON` # 6
--- | `ZONE_DISPLAY_TYPE_RAID` # 3
--- | `ZONE_DISPLAY_TYPE_SOLO` # 1
--- | `ZONE_DISPLAY_TYPE_ZONE_STORY` # 10

ZONE_DISPLAY_TYPE_BATTLEGROUND = 9
ZONE_DISPLAY_TYPE_COMPANION = 11
ZONE_DISPLAY_TYPE_DELVE = 7
ZONE_DISPLAY_TYPE_DUNGEON = 2
ZONE_DISPLAY_TYPE_ENDLESS_DUNGEON = 12
ZONE_DISPLAY_TYPE_GROUP_AREA = 5
ZONE_DISPLAY_TYPE_GROUP_DELVE = 4
ZONE_DISPLAY_TYPE_HOUSING = 8
ZONE_DISPLAY_TYPE_NONE = 0
ZONE_DISPLAY_TYPE_PUBLIC_DUNGEON = 6
ZONE_DISPLAY_TYPE_RAID = 3
ZONE_DISPLAY_TYPE_SOLO = 1
ZONE_DISPLAY_TYPE_ZONE_STORY = 10
