--- @meta ZoneCompletionType

--- @alias ZoneCompletionType integer
--- | `ZONE_COMPLETION_TYPE_DELVES` # 5
--- | `ZONE_COMPLETION_TYPE_FEATURED_ACHIEVEMENTS` # 3
--- | `ZONE_COMPLETION_TYPE_GROUP_BOSSES` # 9
--- | `ZONE_COMPLETION_TYPE_GROUP_DELVES` # 6
--- | `ZONE_COMPLETION_TYPE_MAGES_GUILD_BOOKS` # 11
--- | `ZONE_COMPLETION_TYPE_MUNDUS_STONES` # 12
--- | `ZONE_COMPLETION_TYPE_NONE` # 0
--- | `ZONE_COMPLETION_TYPE_POINTS_OF_INTEREST` # 2
--- | `ZONE_COMPLETION_TYPE_PRIORITY_QUESTS` # 1
--- | `ZONE_COMPLETION_TYPE_PUBLIC_DUNGEONS` # 13
--- | `ZONE_COMPLETION_TYPE_SET_STATIONS` # 14
--- | `ZONE_COMPLETION_TYPE_SKYSHARDS` # 7
--- | `ZONE_COMPLETION_TYPE_STRIKING_LOCALES` # 10
--- | `ZONE_COMPLETION_TYPE_WAYSHRINES` # 4
--- | `ZONE_COMPLETION_TYPE_WORLD_EVENTS` # 8

ZONE_COMPLETION_TYPE_DELVES = 5
ZONE_COMPLETION_TYPE_FEATURED_ACHIEVEMENTS = 3
ZONE_COMPLETION_TYPE_GROUP_BOSSES = 9
ZONE_COMPLETION_TYPE_GROUP_DELVES = 6
ZONE_COMPLETION_TYPE_MAGES_GUILD_BOOKS = 11
ZONE_COMPLETION_TYPE_MUNDUS_STONES = 12
ZONE_COMPLETION_TYPE_NONE = 0
ZONE_COMPLETION_TYPE_POINTS_OF_INTEREST = 2
ZONE_COMPLETION_TYPE_PRIORITY_QUESTS = 1
ZONE_COMPLETION_TYPE_PUBLIC_DUNGEONS = 13
ZONE_COMPLETION_TYPE_SET_STATIONS = 14
ZONE_COMPLETION_TYPE_SKYSHARDS = 7
ZONE_COMPLETION_TYPE_STRIKING_LOCALES = 10
ZONE_COMPLETION_TYPE_WAYSHRINES = 4
ZONE_COMPLETION_TYPE_WORLD_EVENTS = 8
